pmem/pmdk

src/test/vmem_aligned_alloc/out1.log.match
src/test/vmem_calloc/out1.log.match
src/test/vmem_check_allocations/out1.log.match
src/test/vmem_malloc/out1.log.match
src/test/vmem_malloc_usable_size/out1.log.match
src/test/vmem_mix_allocations/out1.log.match
src/test/vmem_out_of_memory/out1.log.match
src/test/vmem_realloc/out1.log.match
src/test/vmem_strdup/out1.log.match

Fix several vmem match files for tests run on pmem.

test: fix more vmem match files

---

src/test/blk_nblock/out0.log.match
src/test/blk_nblock/out1.log.match
src/test/blk_recovery/out0.log.match
src/test/blk_rw/out0.log.match
src/test/blk_rw/out1.log.match
src/test/blk_rw/out2.log.match
src/test/blk_rw/out3.log.match
src/test/blk_rw/out4.log.match
src/test/blk_rw/out5.log.match
src/test/blk_rw/out6.log.match
src/test/blk_rw_mt/out0.log.match
src/test/blk_rw_mt/out1.log.match
src/test/blk_rw_mt/out2.log.match
src/test/log_basic/out0.log.match
src/test/log_basic/out1.log.match
src/test/log_basic/out2.log.match
src/test/log_basic/out3.log.match
src/test/log_recovery/out0.log.match
src/test/log_recovery/out1.log.match
src/test/log_walker/out0.log.match
src/test/pmem_is_pmem/out0.log.match
src/test/pmem_is_pmem/out1.log.match
src/test/pmem_is_pmem/out2.log.match
src/test/pmem_is_pmem/out3.log.match
src/test/pmem_map/out0.log.match
src/test/pmem_map/out1.log.match
src/test/util_pool_create/out0.log.match
src/test/util_pool_create/out1.log.match
src/test/util_pool_open/out0.log.match
src/test/util_pool_open/out1.log.match

Change token for $DIR from $(*) to $(nW) in match files.

test: change token for $DIR in match files

---

doc/libvmem.3
src/include/libvmem.h
src/test/Makefile
src/test/match
src/vmem.c

Update year in copyright headers only in files changed in 2015 year.

common: update year in copyright headers

---

src/btt.c

btt: validate layout against parent UUID

---

Makefile
src/Makefile
src/test/Makefile
src/test/Makefile.inc

common: fix make clobber

---

Makefile
src/Makefile
src/Makefile.inc
src/libpmem/Makefile
src/libpmemblk/Makefile
src/libpmemlog/Makefile
src/libpmemobj/Makefile
src/libvmem/Makefile

Update dates in copyright headers.

common: add missing linking to pthread library

---

src/test/vmem_valgrind/valgrind_check.sh
src/test/vmmalloc_valgrind/TEST0
src/test/vmmalloc_valgrind/TEST1
src/test/vmmalloc_valgrind/TEST2
src/test/vmmalloc_valgrind/valgrind_check.sh

test: fix valgrind detection

---

src/include/libvmmalloc.h
src/libvmmalloc/libvmmalloc.c

vmmalloc: check compiler support for selected function attributes

---

src/Makefile

- fix install dependencies
- fix tools dependencies
Ref: pmem/issues#29

common: fix make dependencies

---

index.md
libpmem/libpmem.3.html
libpmemblk/libpmemblk.3.html
libpmemlog/libpmemlog.3.html
libpmemobj/libpmemobj.3.html
libvmem/libvmem.3.html
libvmmalloc/index.md
libvmmalloc/libvmmalloc.3.html

Also updates the man pages for other NVML libraries.

doc: add man pages for libvmmalloc

---

doc/Makefile
src/Makefile
src/Makefile.inc
src/libpmemblk/Makefile
src/libpmemlog/Makefile
src/libpmemobj/Makefile
src/tools/Makefile.inc

Some fixes in makefiles:
- fix dependencies in make install -j
- add -lpmem to libpmemblk, libpmemlog and libpmemobj
- move building pmempool manpages to doc directory

Makefiles fixes

---

src/benchmarks/blk_mt/blk_mt.c
src/benchmarks/blk_mt/gnuplot_blk_mt_read.p
src/benchmarks/blk_mt/gnuplot_blk_mt_write.p
src/benchmarks/log_mt/gnuplot_log_mt_append.p
src/benchmarks/log_mt/gnuplot_log_mt_read.p
src/benchmarks/log_mt/log_mt.c

- do warmup of fileio in log_mt, add more columns to results
- add more columns to blk_mt results

benchmarks: fix blk_mt and log_mt benchmarks

---

src/libpmemblk/btt.c

Not only can 32-bit overflow happen when multiplying the LBA found in the map times the block size, it was pretty much *always* happening because the EZ bits weren't masked off.  The overflow had the side-effect of masking off the EZ bits, hiding the bug.
The fix is to use 64-bit math and correct the missing mask of the EZ bits.

btt: avoid integer overflow, do  EZ bit masking

---

README.md
src/Makefile

common: add test type support for make check

---

doc/libpmemblk.3

common: add info about the minimum number of blocks

---

src/common/out.c
src/test/traces/custom_file.log.match
src/test/traces/redir_stderr2.log.match
src/test/traces/redir_stderr3.log.match
src/test/traces/redir_stderr4.log.match
src/test/traces/redir_stderr5.log.match
src/test/traces/redir_stderr6.log.match
src/test/traces_custom_function/out0.log.match
src/test/traces_custom_function/out1.log.match
src/test/unittest/unittest.sh

common: add check for compilation with valgrind support

---

src/test/blk_recovery/blk_recovery.c
src/test/log_recovery/log_recovery.c
src/test/log_walker/log_walker.c
src/test/unittest/unittest.h
src/test/unittest/ut_signal.c
src/test/vmem_create/vmem_create.c
src/test/vmem_delete/vmem_delete.c

common: change obsolete sigvec to sigaction

---

src/test/obj_tx_locks/TEST1
src/test/obj_tx_locks/TEST2
src/test/vmem_valgrind/TEST0
src/test/vmem_valgrind/TEST1
src/test/vmem_valgrind/TEST2
src/test/vmem_valgrind/TEST3
src/test/vmem_valgrind/TEST4
src/test/vmem_valgrind/TEST5
src/test/vmmalloc_valgrind/TEST0
src/test/vmmalloc_valgrind/TEST1
src/test/vmmalloc_valgrind/TEST2

Fix tx locks valgrind log

---

src/libpmemobj/obj.c

Do not call pmemobj_alloc_construct from pmemobj_alloc,
pmemobj_zalloc and pmemobj_strdup. Use obj_alloc_construct instead.

obj: add obj_alloc_construct

---

src/include/libpmemobj.h
src/test/obj_basic_integration/obj_basic_integration.c

obj: fix POBJ_LIST_LAST macro when used on an empty list

---

doc/libpmemobj.3
src/include/libpmemobj.h
src/libpmemobj/tx.c
src/test/Makefile
src/test/obj_tx_add_range_direct/.gitignore
src/test/obj_tx_add_range_direct/Makefile
src/test/obj_tx_add_range_direct/TEST0
src/test/obj_tx_add_range_direct/TEST1
src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c
src/test/obj_tx_add_range_direct/out0.log.match
src/test/obj_tx_add_range_direct/out1.log.match
src/test/obj_tx_add_range_direct/valgrind1.log.match
src/test/scope/out4.log.match

Enable adding blocks of memory through virtual addresses to the undo
log.

pmemobj: add new type of tx_add_range

---

doc/libpmem.3

doc: fix pmem_msync() signature in man page

---

doc/libvmem.3

doc: update vmem_create_in_region() description

---

doc/libpmemobj.3

doc: update description of pmemobj_create() arguments

---

doc/libpmemobj.3

obj: fix description of DIRECT_RW and DIRECT_RO in manpage

---

Makefile
doc/Makefile
src/Makefile
src/Makefile.inc
src/tools/Makefile
src/tools/Makefile.inc

common: add uninstall target

---

doc/Makefile

Regression after commit 563e4499530e5155a23240d7b2dae7574f1933bf

common: fix make install in doc

---

src/jemalloc/include/jemalloc/internal/huge.h
src/jemalloc/include/jemalloc/internal/jemalloc_internal.h.in
src/jemalloc/include/jemalloc/internal/util.h
src/jemalloc/src/huge.c
src/test/Makefile
src/test/vmem_realloc_inplace/.gitignore
src/test/vmem_realloc_inplace/Makefile
src/test/vmem_realloc_inplace/TEST0
src/test/vmem_realloc_inplace/TEST1
src/test/vmem_realloc_inplace/out0.log.match
src/test/vmem_realloc_inplace/out1.log.match
src/test/vmem_realloc_inplace/vmem_realloc_inplace.c

Fixes the core of issue #24.
(another pull request coming soon)

Jemalloc: shrink alloc in place

---

doc/libpmemobj.3

doc: fix signatures of list API

---

doc/libpmemblk.3

pmemblk: clarify manpage issue

---

src/examples/libpmemobj/pmemblk/obj_pmemblk.c
src/examples/libpmemobj/pmemlog/obj_pmemlog.c
src/examples/libpmemobj/pmemlog/obj_pmemlog_macros.c
src/examples/libpmemobj/pmemlog/obj_pmemlog_minimal.c
src/examples/libpmemobj/pmemlog/obj_pmemlog_simple.c

pmemobj: fix possible NULL reference

---

src/test/RUNTESTS

test: check if 'timeout' supports '-k' option

---

src/examples/libpmemobj/.gitignore

example: add btree to .gitignore

---

src/benchmarks/pmem_persist_msync/pmem_persist_msync.c
src/examples/libpmemblk/assetdb/asset_load.c
src/examples/libpmemlog/logfile/addlog.c
src/examples/libpmemobj/pminvaders/pminvaders.c
src/test/blk_nblock/blk_nblock.c
src/test/blk_non_zero/blk_non_zero.c
src/test/blk_recovery/blk_recovery.c
src/test/blk_rw/blk_rw.c
src/test/blk_rw_mt/blk_rw_mt.c
src/test/log_basic/log_basic.c
src/test/log_recovery/log_recovery.c
src/test/log_walker/log_walker.c
src/test/obj_basic_integration/obj_basic_integration.c
src/test/obj_debug/obj_debug.c
src/test/obj_direct/obj_direct.c
src/test/obj_recovery/obj_recovery.c
src/test/obj_store/obj_store.c
src/test/obj_tx_add_range/obj_tx_add_range.c
src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c
src/test/obj_tx_alloc/obj_tx_alloc.c
src/test/obj_tx_flow/obj_tx_flow.c
src/test/obj_tx_free/obj_tx_free.c
src/test/obj_tx_locks/obj_tx_locks.c
src/test/obj_tx_realloc/obj_tx_realloc.c
src/test/obj_tx_strdup/obj_tx_strdup.c
src/test/util_pool_create/util_pool_create.c

Do not use exec permission flag when creating a new pool.

common: fix permission flags for pool files

---

src/common/util.h
src/libpmemblk/blk.c
src/libpmemlog/log.c
src/libpmemobj/obj.c
src/test/pmempool_info/out0.log.match
src/test/pmempool_info/out1.log.match
src/test/pmempool_info/out2.log.match
src/test/pmempool_info/out3.log.match
src/test/pmempool_info/out4.log.match
src/test/pmempool_info/out5.log.match
src/test/pmempool_info/out6.log.match
src/test/pmempool_info/out7.log.match
src/test/pmempool_info/out8.log.match
src/tools/pmempool/info.c

Add header fields required to support pool sets & replicas.

common: add new fields to pool header

---

utils/build-dpkg.sh

Fix regression introduced by the commit b6c77792

dpkg: fix 'make dpkg'

---

doc/pmempool-create.1
src/test/pmempool_check/TEST1
src/test/pmempool_check/TEST3
src/test/pmempool_check/TEST4
src/test/pmempool_create/TEST0
src/test/pmempool_create/TEST1
src/test/pmempool_create/TEST2
src/test/pmempool_create/TEST3
src/test/pmempool_create/TEST4
src/test/pmempool_info/TEST2
src/test/pmempool_info/TEST3
src/test/pmempool_info/TEST4
src/test/pmempool_info/TEST9
src/test/pmemspoil/Makefile
src/test/pmemwrite/Makefile
src/test/pmemwrite/write.c
src/test/unittest/unittest.sh
src/tools/pmempool/Makefile
src/tools/pmempool/check.c
src/tools/pmempool/common.c
src/tools/pmempool/common.h
src/tools/pmempool/create.c
src/tools/pmempool/dump.c
src/tools/pmempool/output.c

Add support for pmemobj in pmempool create command.

pmempool create obj

---

src/test/blk_non_zero/.gitignore
src/test/blk_non_zero/TEST0
src/test/blk_non_zero/TEST1
src/test/blk_non_zero/TEST2
src/test/blk_non_zero/TEST3
src/test/blk_non_zero/TEST4
src/test/blk_non_zero/out0.log.match

Use alternate method for generating non-zeroed files.

test: speed up blk_non_zero test

---

src/libpmemobj/list.c

list_set_oid_redo_log has an optimization which avoids writing pool_uuid_id into an oidp when it already has a correct value. However on alloc oidp might be uninitialized, so we should not look at it. To fix this, introduce a flag which tells whether we are allowed to look at oidp and allow it from realloc/free/move, but disallow from alloc.
Found by valgrind/memcheck.

obj: do not read uninitialized value on alloc

---

src/tools/pmempool/pmempool.sh

- Add support for pmemobj pool type.
- Add support for multiple values in a singe argument.

pmempool: update pmempool bash completion script

---

doc/pmempool-check.1
doc/pmempool-create.1
doc/pmempool-dump.1
doc/pmempool-info.1
doc/pmempool.1
src/test/obj_list/obj_list.c
src/test/pmempool_help/out0.log.match
src/test/pmempool_info/out14.log.match
src/tools/pmempool/check.c
src/tools/pmempool/common.c
src/tools/pmempool/create.c
src/tools/pmempool/dump.c
src/tools/pmempool/info.c
src/tools/pmempool/info_obj.c
src/tools/pmempool/pmempool.c

Fix some issues with pmempool utility.

pmempool fixes

---

src/libpmemobj/heap.c

The unavailable bitmap space wasn't properly marked in a newly
initalized runs resulting in runs registerting too much memory as free.

obj: fix run bitmap initialization

---

src/libpmemblk/blk.c
src/libpmemlog/log.c
src/test/blk_non_zero/TEST9
src/test/blk_non_zero/out9.log.match
src/test/blk_non_zero/valgrind9.log.match
src/test/blk_rw/TEST7
src/test/blk_rw/out7.log.match
src/test/blk_rw/valgrind7.log.match
src/test/log_basic/TEST4
src/test/log_basic/out4.log.match
src/test/log_basic/valgrind4.log.match

Remove volatile parts of headers from both block and log.

pmemcheck: add tests for block and log

---

src/test/blk_non_zero/TEST2

Fixed spelling of create_nonzeroed_file.

test: fix typo in command

---

src/test/pmempool_check/TEST5
src/test/pmempool_check/out5.log.match
src/tools/pmempool/check.c

- fix command line arguments
- implement nszero function callback
- update test's match file

pmempool: fix long test for check

---

doc/libpmemobj.3
src/include/libpmemobj.h
src/libpmemobj/obj.c
src/test/obj_basic_integration/obj_basic_integration.c

Ref: pmem/issues#87
Ref: pmem/issues#100

obj: fix type number issues

---

pmempool/pmempool-check.1.html
pmempool/pmempool-create.1.html
pmempool/pmempool-dump.1.html
pmempool/pmempool-info.1.html
pmempool/pmempool.1.html

They are referenced from doc/README (on master branch).

doc: add pmempool docs

---

doc/libpmemobj.3
src/include/libpmemobj.h
src/libpmemobj/libpmemobj.c
src/libpmemobj/libpmemobj.map
src/libpmemobj/obj.c
src/test/scope/out4.log.match

Preparation for pool set support.

obj: update API

---

src/test/unittest/unittest.sh

- Add function for dummy pool sets creation.
- Add functions for checking if selected files has been deleted or left
untouched in case of test (pool set creation) failure.
- Fix locale settings for consistent output sorting in selected tests.

test: add helper functions for pool set testing

---

src/libpmemobj/list.c

It's constructor's job now. The only exception is root object's size.

obj: remove pmem_persist on reallocated object

---

src/examples/libpmemobj/tree_map/ctree_map.c

This patch cuts the number of allocations performed by the crit-bit
tree in half by merging the internal and leaf nodes into a single
structure.

obj: optimize ctree example

---

index.md
pmempool/index.md
pmempool/pmempool-rm.1.html

Add description of pmempool in NVM Library website on pmem.io.
Add references to manual pages.
Add manual page for rm command.

doc: add pmempool page to pmem.io

---

src/test/pmempool_check/TEST0
src/test/unittest/unittest.sh

Useful when test fails on travis.

test: dump error log file on stdout when test fails

---

src/examples/libpmemobj/pmemobjfs/README
src/examples/libpmemobj/pmemobjfs/pmemobjfs.c

- fix printing help message
- update README file

examples: pmemobjfs: minor fixes

---

src/test/RUNTESTS
src/test/unittest/unittest.sh

ut: print test failures/passes messages in color

---

src/benchmarks/Makefile
src/benchmarks/obj_pmalloc.c
src/benchmarks/pmembench_obj_pmalloc.cfg

Add benchmarks for the pmalloc and pfree internal NVML routines.

bench: add benchmark for pmalloc and pfree

---

src/tools/pmempool/check.c
src/tools/pmempool/common.c
src/tools/pmempool/common.h
src/tools/pmempool/create.c
src/tools/pmempool/dump.c
src/tools/pmempool/info.c

- fix segmentation fault in info command if pool has invalid signature
but valid checksum
- fix checking pool hdr if pool has invalid signature but valid checksum
- improve error messages for invalid pools

pmempool: bug fixes in info, dump and check

---

src/test/traces_custom_function/traces_custom_function.c
src/tools/pmempool/common.c

Minor stack overflow fixes

---

utils/build-rpm.sh

common: fix building rpm packages with debug info

---

src/test/RUNTESTS
src/test/match
src/test/pmempool_check/TEST2
src/test/unittest/unittest.sh

With this change "make check >/dev/null" will print only errors.

test: dump errors on stderr

---

src/libpmemobj/heap.c

We've seen performance drop for number of threads exceeding number of
cpus. Changing the number of bucket caches to be 2 x ncpus improves the
performance in such case.

obj: change number of bucket caches

---

.travis.yml

common: add autoconf to travis config

---

src/examples/libpmemobj/map/data_store.c

example: fix small memory leak

---

doc/libpmemobj.3

doc: define minimal file size of a pool set part

---

doc/libpmemobj.3
src/libpmemobj/obj.c

Fix pmemobj_free/realloc/zrealloc(NULL/root object)

obj: fix pmemobj_free/realloc/zrealloc

---

src/test/vmem_mix_allocations/vmem_mix_allocations.c

We were overflowing "ptr" array when mapped region allowed to do
21 allocations. Vmem - depending on address returned from mmap - wastes
part of the pool for alignment, which reduces number of possible
allocations. (This uncertainty will be fixed soon)
Instead of just fixing off-by-one error, this patch reworks the loop
which lead to this bug.
Reported-by: Jeff Moyer@RedHat
Debugged-by: Krzysztof Czuryło

test: fix vmem_mix_allocations

---

doc/README

pmempool: update doc/README with rm command

---

src/common/set.c

Fix issue reported by memcheck for blk_nblock/TEST0:
Conditional jump or move depends on uninitialised value(s).
The issue appears when mapping the file fails. This was the case
in blk_nblock test which creates huge file.

common: fix issue reported by memcheck

---

src/examples/libpmemobj/pmemlog/obj_pmemlog.c
src/examples/libpmemobj/pmemlog/obj_pmemlog_macros.c
src/examples/libpmemobj/pmemlog/obj_pmemlog_minimal.c
src/examples/libpmemobj/pmemlog/obj_pmemlog_simple.c
src/test/ex_libpmemobj/out11.log.match
src/test/ex_libpmemobj/out14.log.match

Appendv did a silent abort.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/551)

obj: fix examples

---

src/examples/libpmemobj/tree_map/rbtree_map.c

Add missing entry to undo log.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/559)

examples: fix rb tree map insert function

---

src/test/obj_sync/err0.log.match
src/test/obj_sync/err1.log.match
src/test/obj_sync/err2.log.match
src/test/obj_sync/err3.log.match
src/test/obj_sync/err4.log.match
src/test/obj_sync/err5.log.match
src/test/obj_sync/err6.log.match
src/test/unittest/ut.c

Useful when the same assertion is used multiple times in the same
function.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/555)

ut: include file & line number in fatal & error messages

---

src/test/unittest/unittest.sh

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/556)

ut: dump last 30 lines of all log files on failure

---

src/libvmem/vmem.h

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/566)

vmem: remove duplicated Pagesize declaration

---

src/libpmemobj/obj.c
src/test/tools/pmemobjcli/.gitignore
src/test/tools/pmemobjcli/Makefile
src/test/tools/pmemobjcli/README
src/test/tools/pmemobjcli/example.posc
src/test/tools/pmemobjcli/pmemobjcli.c
src/test/tools/pmemspoil/Makefile
src/test/tools/pmemwrite/Makefile
src/tools/Makefile.inc
src/tools/pmempool/Makefile

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/557)

Add CLI tool for testing pmemobj API

---

src/benchmarks/Makefile
src/benchmarks/pmembench.c
src/benchmarks/pmembench_atomic_lists.cfg
src/benchmarks/pmemobj_atomic_lists.c

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/517)

pmembench: add benchmark for pmemobj atomic lists

---

src/test/obj_sync/TEST0
src/test/obj_sync/err1.log.match
src/test/obj_sync/err2.log.match

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/569)

test: obj_sync fixes

---

src/benchmarks/pmem_memset.c

benchmark: fix address calculation in pmem_memset

---

src/examples/libpmemobj/pminvaders/.gitignore
src/examples/libpmemobj/pminvaders/README
src/examples/libpmemobj/pminvaders/pminvaders2.c
src/test/ex_libpmemobj/TEST16

A second version of a simple, PMEM-based clone of Space Invaders.
This version is fully based on the transactional pmemobj API.

obj: add pminvaders 2.0 example

---

src/libpmemobj/lane.c
src/libpmemobj/obj.h

Reduce number of mutexattr allocations/initializations.

obj: lane_init() refactoring

---

src/common/util.h
src/libpmemobj/sync.c

Up to 20% improvement in number of ops per second, as benchmarked by pmembench.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/574)

obj: optimize pmem locks

---

src/examples/Makefile.inc
src/examples/libpmemobj/cpp/Makefile
src/examples/libpmemobj/cpp/queue.cpp
src/test/Makefile.inc
src/test/obj_cpp_ptr/Makefile

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/585)

common: change conflicting makefile variable

---

src/Makefile.inc
src/benchmarks/Makefile
src/common.inc
src/test/Makefile.inc
src/test/unittest/Makefile
src/tools/Makefile.inc

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/584)

benchmarks: autogenerate build dependencies

---

src/libpmemobj/bucket.c
src/libpmemobj/bucket.h
src/libpmemobj/heap.c
src/libpmemobj/heap.h
src/libpmemobj/pmalloc.c
src/test/obj_bucket/obj_bucket.c
src/test/obj_heap/obj_heap.c
src/test/obj_realloc/obj_realloc.c
src/tools/pmempool/info.h
src/tools/pmempool/info_obj.c

In preparation for change of allocation classes.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/586)

obj: buckets code refactor

---

src/libpmemobj/heap.c

Had to merge changes by hand when error handling
code went in, missed few things.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/587)

obj: bring back changes reverted by rebase

---

src/libpmemobj/bucket.c

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/588)

obj: avoid upcasts

---

src/examples/libpmemobj/map/kv_protocol.h
src/examples/libpmemobj/map/kv_server.c
src/examples/libpmemobj/map/kv_server_test.sh

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/590)

example: kv store async tcp server

---

src/libvmem/vmem.h
src/test/vmem_realloc_inplace/Makefile
src/test/vmem_realloc_inplace/TEST0
src/test/vmem_realloc_inplace/TEST1
src/test/vmem_realloc_inplace/vmem_realloc_inplace.c

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/593)

common: fix format of copyright headers

---

src/examples/libpmemobj/tree_map/rbtree_map.c

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/592)

obj: add stopping logic to rb tree clear function

---

src/common/set.c
src/test/obj_pool/README
src/test/obj_pool/TEST29
src/test/obj_pool/out29.log.match
src/test/obj_pool/pool.set

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/595)

obj: pmemobj_open() should set errno on error

---

doc/libpmemobj.3

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/591)

doc: update pmemobj_tx_errno description

---

src/examples/libpmemobj/cpp/queue.cpp
src/include/libpmemobj/persistent_ptr.hpp
src/test/obj_cpp_ptr/obj_cpp_ptr.cpp

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/606)

Obj cpp fixes

---

src/libpmemobj/obj.c

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/603)

obj: fix a small typo in comments

---

src/test/unittest/unittest.sh

Bad interaction between my fs_type changes and
2a38fcec48d8b590c75222a4db20fe50ea157bd8.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/607)

ut: fix require_fs_type any

---

src/examples/libpmemobj/map/.gitignore

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/610)

examples: fix gitignore for kv server example

---

src/libpmemobj/ctree.c

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/612)

obj: take locks on ctree read operations

---

doc/libpmemobj.3
src/examples/libpmemobj/cpp/queue.cpp

Add a section describing the setjmp/longjmp problem with automatic
variables.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/617)

doc: setjump issue explanation

---

src/libpmemobj/heap.c

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/622)

obj: fix 2 off by ones in bucket walk

---

src/include/libpmemobj/pext.hpp

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/625)

obj: add missing header guard

---

src/include/libpmemobj/persistent_ptr.hpp

Refs pmem/issues#147
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/624)

obj: disallow polymorhism in default constructor

---

doc/libpmemobj.3
src/include/libpmemobj.h
src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c
src/test/obj_tx_add_range_direct/valgrind1.log.match

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/626)

obj: add TX_ADD_DIRECT & co

---

src/libpmemobj/list.c
src/libpmemobj/obj.c
src/test/obj_list/README
src/test/obj_list/obj_list.c
src/test/obj_list_move/TEST2
src/test/obj_list_move/out1.log.match
src/test/obj_list_move/out2.log.match

Ref: pmem/issues#146
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/628)

obj: fix moving objects within one list

---

src/test/README
src/test/unittest/unittest.sh

... when environment variable TM is set to 1
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/629)

ut: display test run times

---

src/libpmemobj/tx.c

a) When user application stores locks (protecting persistent memory
structures) in volatile memory and unlocks them in ONCOMMIT / ONABORT /
FINALLY sections, pmemcheck may see those objects snapshotted
simultaneously in multiple transactions, which is considered a bug.
It's happening because objects are removed from transaction (implicitly)
by VALGRIND_END_TX macro called from pmemobj_tx_end, *after* ONCOMMIT /
ONABORT / FINALLY section.
b) When user application allocates and frees (different) objects in
multiple threads, pmemcheck may see overlapping blocks of memory
snapshotted in different transactions, because between commit/abort and
TX_END, allocator may use recently freed (but not yet removed from
transaction by VALGRIND_END_TX) memory for new allocations.
Fix this by explicitly …

obj: fix pmemcheck vs multi-threaded app interaction

---

.travis.yml
README.md
src/benchmarks/Makefile
src/benchmarks/README
src/common.inc
src/examples/libpmemobj/map/Makefile
src/examples/libpmemobj/map/README
src/examples/libpmemobj/pmemobjfs/Makefile
src/examples/libpmemobj/pmemobjfs/README
src/examples/libpmemobj/pminvaders/Makefile
src/examples/libpmemobj/pminvaders/README
src/test/Makefile.inc
src/test/ex_libpmemobj/Makefile
src/test/ex_libpmemobj/TEST15
src/test/ex_libpmemobj/TEST16
src/test/ex_libpmemobj_cpp/Makefile
src/test/unittest/Makefile
src/test/unittest/unittest.sh

- Fail building if pkg-config is not available
- Print message if specified dependency is not met
- Update README files of components which have external dependencies
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/614)

common: fix checking for dependencies

---

README.md
src/test/unittest/unittest.sh

Modify the require function to take into account the default c++
compiler.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/618)

ut: change require_cxx11

---

src/include/libpmemobj/detail/pexceptions.hpp
src/include/libpmemobj/detail/specialization.hpp
src/include/libpmemobj/p.hpp
src/include/libpmemobj/persistent_ptr.hpp
src/include/libpmemobj/pext.hpp
src/include/libpmemobj/pool.hpp
src/test/Makefile
src/test/obj_cpp_pool/.gitignore
src/test/obj_cpp_pool/Makefile
src/test/obj_cpp_pool/TEST0
src/test/obj_cpp_pool/TEST1
src/test/obj_cpp_pool/TEST2
src/test/obj_cpp_pool/obj_cpp_pool.cpp
src/test/obj_cpp_pool/out0.log.match
src/test/obj_cpp_pool/out1.log.match
src/test/obj_cpp_pool/out2.log.match

Initial implementation by @pbalcer
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/631)

obj: C++ pool implementation

---

src/test/unittest/unittest.sh

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/634)

common: do not print path to pkg-config in tests

---

CONTRIBUTING.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/620)

doc: changes to the contribution terms

---

doc/libpmemobj.3

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/623)

doc: update libpmemobj man page

---

src/benchmarks/blk.c
src/benchmarks/log.c

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/640)

Pmembench fixes

---

src/examples/Makefile.inc
src/examples/libpmemobj/libart/Makefile
src/examples/libvmem/libart/Makefile

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/641)

common: refactor libart makefiles

---

src/test/obj_tx_flow/obj_tx_flow.c

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/644)

ut: pmemobj_tx_commit case added

---

.travis.yml
src/test/vmem_multiple_pools/TEST3

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/648)

travis: install valgrind only if necessary

---

src/tools/pmempool/info_obj.c

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/649)

pmempool: fix possible division by zero

---

src/examples/libpmemblk/assetdb/asset_checkin.c
src/examples/libpmemblk/assetdb/asset_checkout.c
src/examples/libpmemobj/pi.c

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/651)

examples: validate input

---

src/libpmemobj/list.c
src/test/obj_list/Makefile
src/test/obj_list/obj_list.c

Ref: pmem/issues#146
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/642)

obj: fix deadlock in obj_list_move()

---

src/examples/libpmemobj/libart/art.c
src/examples/libpmemobj/libart/arttree.c
src/examples/libpmemobj/libart/arttree_examine.c
src/examples/libpmemobj/libart/arttree_search.c
src/examples/libpmemobj/libart/arttree_structures.c
src/examples/libvmem/libart/art.c
src/examples/libvmem/libart/arttree.c

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/653)

example: libart: some fixes and assertions

---

src/benchmarks/config_reader.c
src/benchmarks/pmembench.c
src/benchmarks/pmembench_atomic_lists.cfg
src/benchmarks/pmembench_blk.cfg
src/benchmarks/pmembench_log.cfg
src/benchmarks/pmembench_map.cfg
src/benchmarks/pmembench_memcpy.cfg
src/benchmarks/pmembench_memset.cfg
src/benchmarks/pmembench_obj_gen.cfg
src/benchmarks/pmembench_obj_lanes.cfg
src/benchmarks/pmembench_obj_locks.cfg
src/benchmarks/pmembench_obj_pmalloc.cfg
src/benchmarks/pmembench_tx.cfg
src/benchmarks/pmembench_vmem.cfg
src/benchmarks/scenario.c
src/benchmarks/scenario.h

The group value is printed in results header. It may be useful for
grouping results.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/656)

benchmarks: add group key to scenario

---

src/examples/libpmemobj/libart/art.c
src/examples/libvmem/libart/art.c

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/654)

example: libart: correct two asserts

---

src/libpmemblk/blk.c

Please review
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/659)

blk: fix valgrind instrumentation

---

src/test/Makefile
src/test/obj_strdup/.gitignore
src/test/obj_strdup/Makefile
src/test/obj_strdup/TEST0
src/test/obj_strdup/obj_strdup.c

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/645)

ut: unit test fot pmemobj_strdup added

---

src/include/libpmemobj/p.hpp
src/include/libpmemobj/persistent_ptr.hpp
src/include/libpmemobj/pext.hpp
src/include/libpmemobj/pool.hpp

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/663)

obj: add doxygen-style comments to cpp classes

---

src/common/set.c
src/common/util.c
src/common/util.h
src/libpmemblk/btt.c
src/libpmemobj/cuckoo.c
src/libpmemobj/tx.c

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/665)

common: introduce Zalloc as Malloc + memset(addr,0,len)

---

src/include/libpmemobj/mutex.hpp
src/include/libpmemobj/p.hpp
src/include/libpmemobj/shared_mutex.hpp

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/667)

obj: fix some typos in comments

---

src/benchmarks/map_bench.c

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/669)

benchmark: fix map benchmark

---

src/test/obj_cpp_pool_primitives/pmemcheck1.log.match

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/672)

test: fix tokens in a match file

---

src/include/libpmemobj/detail/check_persistent_ptr_array.hpp
src/include/libpmemobj/detail/common.hpp
src/include/libpmemobj/make_persistent.hpp
src/include/libpmemobj/persistent_ptr.hpp
src/test/Makefile
src/test/obj_cpp_make_persistent/.gitignore
src/test/obj_cpp_make_persistent/Makefile
src/test/obj_cpp_make_persistent/TEST0
src/test/obj_cpp_make_persistent/TEST1
src/test/obj_cpp_make_persistent/obj_cpp_make_persistent.cpp
src/test/obj_cpp_make_persistent/valgrind1.log.match

Implementation of the transactional version of make_persistent.
Initial implementation by @pbalcer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/673)

obj: cpp make_persistent implementation

---

src/include/libpmemobj/detail/common.hpp
src/include/libpmemobj/make_persistent.hpp

Correct two typos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/674)

obj: fix problem with obsolete macro

---

src/test/obj_cpp_cond_var/TEST0
src/test/obj_cpp_cond_var_posix/TEST0
src/test/obj_cpp_cond_var_posix/TEST1
src/test/obj_cpp_cond_var_posix/TEST2
src/test/obj_cpp_mutex/TEST0
src/test/obj_cpp_shared_mutex/TEST0
src/test/unittest/unittest.sh

Fix possible locale problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/677)

ut: fix require_binary

---

src/examples/libpmemobj/map/mapcli.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/676)

examples: mapcli: fix memory leak

---

src/libpmemobj/tx.c

We don't care about the order of flushes for user data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/678)

obj: split persists in tx_pre_commit

---

src/tools/.gitignore
src/tools/pmempool/.gitignore

Add *.static-debug and *.static-nondebug to gitignore in tools
directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/680)

tools: update src/tools/.gitignore file

---

utils/check_whitespace

cpp & hpp are C++ files/headers.
inc files are Makefile includes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/683)

utils/check_whitespace: check "cpp", "hpp" and "inc" files

---

src/libpmemobj/tx.c
src/test/obj_tx_free/obj_tx_free.c
src/test/obj_tx_free/valgrind1.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/682)

obj: fix transactional free regression

---

doc/libpmemobj.3

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/684)

doc: libpmemobj: fix two typos

---

doc/libpmem.3
src/benchmarks/pmem_memcpy.c
src/benchmarks/pmem_memset.c
src/common/util.c
src/common/util.h
src/examples/libpmem/full_copy.c
src/examples/libpmem/manpage.c
src/examples/libpmem/simple_copy.c
src/include/libpmem.h
src/libpmem/libpmem.map
src/libpmem/pmem.c
src/libvmmalloc/libvmmalloc.c
src/test/obj_list/obj_list.c
src/test/obj_redo_log/obj_redo_log.c
src/test/pmem_is_pmem/pmem_is_pmem.c
src/test/pmem_map/Makefile
src/test/pmem_map/README
src/test/pmem_map/TEST0
src/test/pmem_map/TEST1
src/test/pmem_map/out0.log.match
src/test/pmem_map/out1.log.match
src/test/pmem_map/pmem_map.c
src/test/pmem_memcpy/pmem_memcpy.c
src/test/pmem_memmove/pmem_memmove.c
src/test/pmem_memset/pmem_memset.c
src/test/pmem_valgr_simple/pmem_valgr_simple.c
src/test/pmem_valgr_simple/valgrind0.log.match
src/test/scope/out1.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/687)

pmem: change pmem_map() interface

---

doc/libpmemobj.3
src/include/libpmemobj.h
src/libpmemobj/libpmemobj.map
src/libpmemobj/sync.c
src/test/obj_sync/TEST7
src/test/obj_sync/obj_sync.c
src/test/obj_sync/out7.log.match
src/test/scope/out4.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/689)

obj: add timedlock

---

src/test/match

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/690)

ut: handle EOFs in files processed by "match"

---

src/libpmemobj/redo.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/692)

obj: fix redo log typo

---

src/include/libpmemobj/condition_variable.hpp
src/include/libpmemobj/timed_mutex.hpp
src/test/obj_cpp_timed_mtx/.gitignore
src/test/obj_cpp_timed_mtx/Makefile
src/test/obj_cpp_timed_mtx/TEST0
src/test/obj_cpp_timed_mtx/obj_cpp_timed_mtx.cpp
src/test/obj_cpp_timed_mtx_posix/.gitignore
src/test/obj_cpp_timed_mtx_posix/Makefile
src/test/obj_cpp_timed_mtx_posix/TEST0
src/test/obj_cpp_timed_mtx_posix/TEST1
src/test/obj_cpp_timed_mtx_posix/TEST2
src/test/obj_cpp_timed_mtx_posix/obj_cpp_timed_mtx_posix.cpp
src/test/obj_cpp_timed_mtx_posix/valgrind0.log.match
src/test/obj_cpp_timed_mtx_posix/valgrind1.log.match
src/test/obj_cpp_timed_mtx_posix/valgrind2.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/694)

obj: cpp timed_mutex implementation

---

src/include/libpmemobj/detail/array_traits.hpp
src/include/libpmemobj/detail/check_persistent_ptr_array.hpp
src/include/libpmemobj/detail/destroyer.hpp
src/include/libpmemobj/make_persistent.hpp
src/include/libpmemobj/make_persistent_array.hpp
src/include/libpmemobj/make_persistent_array_atomic.hpp
src/test/Makefile
src/test/obj_cpp_make_persistent_array/.gitignore
src/test/obj_cpp_make_persistent_array/Makefile
src/test/obj_cpp_make_persistent_array/TEST0
src/test/obj_cpp_make_persistent_array/TEST1
src/test/obj_cpp_make_persistent_array/obj_cpp_make_persistent_array.cpp
src/test/obj_cpp_make_persistent_array/valgrind1.log.match
src/test/obj_cpp_make_persistent_array_atomic/.gitignore
src/test/obj_cpp_make_persistent_array_atomic/Makefile
src/test/obj_cpp_make_persistent_array_atomic/TEST0
src/test/obj_cpp_make_persistent_array_atomic/TEST1
src/test/obj_cpp_make_persistent_array_atomic/obj_cpp_make_persistent_array_atomic.cpp
src/test/obj_cpp_make_persistent_array_atomic/valgrind1.log.match

Implement make_persistent and make_persistent_atomic for array types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/696)

obj: cpp make array implementation

---

src/.gitignore
src/Makefile
src/Makefile.inc
src/common.inc
src/examples/Makefile.inc
utils/build-dpkg.sh
utils/build-rpm.sh
utils/make-pkg-config.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/698)

common: add pkg-config files

---

doc/libpmem.3

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/701)

doc: fix typos in libpmem man page

---

doc/libpmemobj.3
src/include/libpmemobj.h
src/libpmemobj/libpmemobj.map
src/libpmemobj/tx.c
src/test/Makefile
src/test/obj_tx_lock/.gitignore
src/test/obj_tx_lock/Makefile
src/test/obj_tx_lock/TEST0
src/test/obj_tx_lock/obj_tx_lock.c
src/test/scope/out4.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/697)

obj: add pmemobj_tx_lock function to C api

---

.travis.yml
src/test/obj_realloc/TEST1
src/test/testconfig.sh.example
src/test/unittest/unittest.sh

... and enable it on travis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/704)

ut: add an ability to run PMEM tests without DAX

---

src/libpmemobj/ctree.c
src/libpmemobj/ctree.h
src/libpmemobj/tx.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/705)

obj: optimize tx_add operations

---

src/benchmarks/pmembench_atomic_lists.cfg
src/benchmarks/pmemobj_tx.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/706)
Ref: pmem/issues#141

pmembench: #141 bug fixed

---

src/libpmemobj/tx.c

Currently we memset the whole tx_add cache for small objects on each
commit, independent of how many entries were used in the transaction.
We can memset less, but only if we didn't get here from lane recovery
(where tx.section might be stale).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/709)

obj: optimize tx_post_commit_set

---

.travis.yml

Commit 34eb523e79fef5188da622daab8f42168ec8cf7f was incomplete.
With this change builds take 50% more time (10min -> 15min).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/710)

travis: enable pmem tests

---

src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/712)

test: add missing prefix to macros from unittest.h

---

src/libpmemobj/obj.h

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/715)

obj: fix a small typo

---

src/libpmemobj/ctree.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/716)

obj: optimize ctree_delete even more

---

CONTRIBUTING.md
README.md
doc/README
doc/libpmem.3
doc/libpmemblk.3
doc/libpmemlog.3
doc/libpmemobj.3
doc/librpmem.3
doc/libvmem.3
doc/libvmmalloc.3
doc/pmempool-check.1
doc/pmempool-create.1
doc/pmempool-dump.1
doc/pmempool-info.1
doc/pmempool-rm.1
doc/pmempool.1
src/include/README
src/libpmem/libpmem.map
src/libpmemblk/libpmemblk.map
src/libpmemlog/libpmemlog.map
src/libpmemobj/libpmemobj.map
src/librpmem/librpmem.map
src/libvmem/libvmem.map
src/tools/pmempool/README

- Bump up version numbers in man pages.
- Update API's version names in library symbol maps.
- Update README's, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/717)

common: prepare for 1.0 release

---

src/test/obj_sync/obj_sync.c

Change test pass criteria.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/719)

obj: obj_sync fix

---

src/examples/libpmemobj/map/map_btree.c
src/examples/libpmemobj/map/map_ctree.c
src/examples/libpmemobj/map/map_hashmap_atomic.c
src/examples/libpmemobj/map/map_hashmap_tx.c
src/examples/libpmemobj/map/map_rbtree.c
src/examples/libpmemobj/tree_map/btree_map.c
src/examples/libpmemobj/tree_map/rbtree_map.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/729)

examples: fix some typos in comments

---

Makefile
doc/Makefile
src/Makefile
src/Makefile.inc
src/common.inc
src/tools/Makefile.inc
utils/build-dpkg.sh
utils/build-rpm.sh

Follow the GNU convention for variables for installation directories
defined on the following page:
https://www.gnu.org/prep/standards/html_node/Directory-Variables.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/734)

common: fix variables for installation directories

---

src/libpmemobj/tx.c
src/test/obj_tx_add_range/obj_tx_add_range.c

All objects on undo log set and undo log set cache lists were removed
but not freed. This resulted in persistent memory leak.
Ref: pmem/issues#162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/733)

obj: fix undo log set recovery

---

src/examples/libpmemobj/tree_map/ctree_map.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/744)

pmembench: error when OID_NULL given to OID_INSTANCEOF

---

src/benchmarks/pmembench_obj_pmalloc.cfg

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/745)

pmembench: large allocations for pmalloc removed

---

src/benchmarks/pmemobj_tx.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/743)

pmembench: wrong exit operation when tx is aborted

---

src/test/obj_tx_add_range/TEST0
src/test/obj_tx_add_range/TEST2
src/test/obj_tx_add_range/obj_tx_add_range.c
src/test/obj_tx_add_range/out0.log.match
src/test/obj_tx_add_range/out1.log.match
src/test/obj_tx_add_range/valgrind1.log.match

The obj_tx_add_range was timeouting sometimes because of new scenario
which checks for persistent memory leaks (pmem/issues#162)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/746)

test: fix timeouting obj_tx_add_range test

---

src/test/tools/pmemspoil/README
src/test/tools/pmemspoil/spoil.c

Please review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/737)

test: add support for btt device to pmemspoil

---

src/include/libpmemobj/pool.hpp
src/test/obj_cpp_pool/TEST3
src/test/obj_cpp_pool/obj_cpp_pool.cpp
src/test/obj_cpp_pool/out3.log.match

Add throw to get_root.
Refs: pmem/issues#156
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/721)

obj: cpp pool.get_root() fix

---

src/include/libpmemobj/persistent_ptr.hpp
src/test/obj_cpp_ptr_arith/obj_cpp_ptr_arith.cpp

Fix type in std::less<>()
Refs pmem/issues#152
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/722)

obj: fix compare array pptr to nullptr

---

doc/.gitignore
doc/Makefile
doc/README
doc/cppobj.Doxyfile
src/include/libpmemobj/README.md
src/include/libpmemobj/mutex.hpp
src/include/libpmemobj/shared_mutex.hpp
src/include/libpmemobj/timed_mutex.hpp
src/include/libpmemobj/transaction.hpp

Add doxygen documentation to C++ bindings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/720)

obj: add cpp html docs

---

src/benchmarks/pmemobj_tx.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/747)

benchmarks: fix two typos

---

src/benchmarks/pmem_memcpy.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/748)

benchmarks: fix possible null pointer dereference

---

src/benchmarks/pmem_memset.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/751)

benchmarks: initialize memset value

---

src/test/unittest/unittest.sh

While creating the windows version of unittest.sh, found a few
minor cleanup items.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/753)

test: minor cleanup

---

src/test/Makefile
src/test/obj_locks/.gitignore
src/test/obj_locks/Makefile
src/test/obj_locks/TEST0
src/test/obj_locks/TEST1
src/test/obj_locks/TEST2
src/test/obj_locks/obj_locks.c
src/test/obj_locks/out1.log.match
src/test/obj_locks/out2.log.match
src/test/obj_locks/valgrind1.log.match
src/test/obj_locks/valgrind2.log.match

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/646)

ut: unit test for locks in pmemobj added

---

src/include/libpmemobj/make_persistent.hpp
src/include/libpmemobj/make_persistent_array.hpp

Change exception message in delete_persistent.
Refs: pmem/issues#163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/754)

cpp: change exception message

---

src/benchmarks/pmembench.c
src/benchmarks/pmemobj_atomic_lists.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/756)

benchmarks: fix error handling

---

src/benchmarks/pmembench.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/757)

benchmarks: fix pmembench_run()

---

src/test/ld.supp
src/test/obj_memcheck/TEST0
src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/764)

ut: workaround Valgrind issues on Debian testing

---

src/libvmem/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/768)

vmem: fix libvmem's Makefile

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/767)

common: add release badge to main README file

---

src/libpmemobj/heap.c
src/libpmemobj/lane.c
src/libpmemobj/lane.h
src/libpmemobj/obj.c
src/libpmemobj/obj.h
src/test/obj_bucket/obj_bucket.c
src/test/obj_heap/obj_heap.c
src/test/obj_lane/Makefile
src/test/obj_lane/obj_lane.c
src/test/obj_list/Makefile
src/test/obj_pmalloc_basic/obj_pmalloc_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/723)

obj: lane array locking

---

src/test/tools/pmemobjcli/example.posc
src/test/tools/pmemobjcli/pmemobjcli.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/769)

pmemobjcli: missing non-transactional api added

---

Makefile
README.md
doc/Makefile
src/Makefile
src/common.inc
utils/build-dpkg.sh
utils/build-rpm.sh
utils/make-pkg-config.sh

Add conditional build of experimental features.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/771)

common: add experimental install and package build

---

src/test/tools/bttcreate/bttcreate.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/779)

test: bttcreate - fix the way of opening file

---

src/test/obj_locks/TEST1
src/test/obj_memcheck/memcheck0.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/781)

test: update for Valgrind 3.11

---

src/test/Makefile
src/test/rpmemd_config/.gitignore
src/test/rpmemd_config/Makefile
src/test/rpmemd_config/README
src/test/rpmemd_config/TEST0
src/test/rpmemd_config/TEST1
src/test/rpmemd_config/TEST2
src/test/rpmemd_config/TEST3
src/test/rpmemd_config/grep_stdout2.log.match
src/test/rpmemd_config/in1.conf
src/test/rpmemd_config/in3.conf
src/test/rpmemd_config/rpmemd_config_test.c
src/test/rpmemd_config/stdout0.log.match
src/test/rpmemd_config/stdout1.log.match
src/test/rpmemd_config/stdout3.log.match
src/tools/rpmemd/rpmemd_config.c
src/tools/rpmemd/rpmemd_config.h
src/tools/rpmemd/rpmemd_log.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/777)

rpmemd: read config from command line and config file

---

src/examples/libpmemobj/cpp/queue.cpp

Use new C++ features in the queue example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/783)

cpp: update queue example

---

src/Makefile
src/common.inc
utils/build-dpkg.sh
utils/build-rpm.sh

Recursively install C++ headers. Fix package build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/784)

common: cpp install experimental recursively

---

src/test/rpmemd_obc/rpmemd_obc_test_accept.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/787)

rpmemd: fix a typo

---

src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/788)

test: add support for Valgrind to remote tests

---

Makefile
src/Makefile
src/test/Makefile

Add check-remote target that runs only remote tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/790)

test: add check-remote target

---

src/test/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/791)

test: replace spaces with tabs in Makefile

---

src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/794)

test: fix copying remote Valgrind logs

---

utils/build-rpm.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/795)

common: add docdir to rpm spec file

---

src/common/set.c
src/common/util.c
src/common/util.h
src/include/librpmem.h
src/test/Makefile
src/test/arch_flags/log0.log.match
src/test/rpmemd_db/.gitignore
src/test/rpmemd_db/Makefile
src/test/rpmemd_db/README
src/test/rpmemd_db/TEST0
src/test/rpmemd_db/TEST1
src/test/rpmemd_db/err1.log.match
src/test/rpmemd_db/out0.log.match
src/test/rpmemd_db/out1.log.match
src/test/rpmemd_db/rpmemd1.log.match
src/test/rpmemd_db/rpmemd_db_test.c
src/test/rpmemd_db/test0-root/test0-pool0.set
src/test/rpmemd_db/test0-root/test0-pool1.set
src/test/rpmemd_db/test1-root/test1-pool0.set
src/test/rpmemd_db/test1-root/test1-pool1.set
src/test/rpmemd_db/trace0.log.match
src/test/rpmemd_db/trace1.log.match
src/tools/rpmemd/Makefile
src/tools/rpmemd/rpmemd_db.c
src/tools/rpmemd/rpmemd_db.h

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/778)

rpmemd: add database of pool sets

---

src/tools/rpmemd/rpmemd_db.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/799)

rpmemd: fix checking duplicates

---

doc/pmempool-info.1
src/libpmemblk/btt.c
src/libpmemblk/btt_layout.h
src/test/Makefile
src/test/Makefile.inc
src/test/bttdevice/Makefile
src/test/bttdevice/README
src/test/bttdevice/TEST0
src/test/bttdevice/TEST1
src/test/bttdevice/out0.log.match
src/test/bttdevice/out1.log.match
src/test/unittest/unittest.sh
src/tools/pmempool/Makefile
src/tools/pmempool/check.c
src/tools/pmempool/common.c
src/tools/pmempool/common.h
src/tools/pmempool/info.c
src/tools/pmempool/info.h
src/tools/pmempool/info_blk.c
src/tools/pmempool/output.c

Please review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/793)

Btt unit test

---

src/libpmemlog/log.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/802)

log: simplify error handling in pmemlog_append[v]

---

src/benchmarks/perf.cfg

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/804)

benchmarks: common performance config file

---

src/libpmemobj/memblock.h

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/808)

obj: fix a typo

---

src/test/unittest/unittest.sh

Automatically register PID files in run_on_node_background().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/807)

test: automatically register PID files

---

src/test/RUNTESTS
src/test/remote_basic/TEST1
src/test/tools/ctrld/ctrld.c
src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/809)

test: add timeout to ctrld's run command

---

src/common/pthread_windows.c
utils/check_license/check-headers.sh

... and fix a typo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/811)

utils: remove redundant grep calls

---

CONTRIBUTING.md
src/common.inc
utils/style_check.sh

Add possibility to chose which clang-format to use during cstyle/format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/812)

common: add choice of clang-format

---

src/libpmemobj/bucket.c
src/libpmemobj/ctree.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/813)

obj: add documentation for bucket heap abstraction

---

src/libpmemobj/heap.c
src/libpmemobj/heap.h
src/libpmemobj/memblock.c
src/libpmemobj/memblock.h
src/libpmemobj/memops.c
src/libpmemobj/memops.h
src/libpmemobj/pmalloc.c
src/test/obj_heap/obj_heap.c
src/test/obj_memblock/Makefile
src/test/obj_memblock/obj_memblock.c
src/test/obj_realloc/Makefile
src/tools/pmempool/common.h

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/814)

obj: perform pmalloc tiny refactor and add more comments

---

src/benchmarks/Makefile
src/benchmarks/pmem_flush.c
src/benchmarks/pmembench_flush.cfg

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/759)

bench: add pmem_persist and pmem_msync benchmark

---

src/test/rpmem_obc/TEST2
src/test/rpmem_obc/TEST3
src/test/rpmem_obc/TEST4
src/test/rpmem_obc/TEST5
src/test/rpmem_obc/TEST6
src/test/rpmem_obc/TEST7
src/test/rpmem_obc/rpmem_obc_test_misc.c
src/test/rpmem_obc_int/TEST0
src/test/rpmem_obc_int/TEST1
src/test/rpmemd_obc/TEST0
src/test/rpmemd_obc/TEST1
src/test/rpmemd_obc/TEST2
src/test/rpmemd_obc/TEST3
src/test/rpmemd_obc/TEST4
src/test/rpmemd_obc/TEST5
src/test/rpmemd_obc/TEST6
src/test/rpmemd_obc/TEST7
src/test/rpmemd_obc/TEST8
src/test/rpmemd_obc/TEST9
src/test/rpmemd_obc/rpmemd_obc_test_common.c
src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/815)

Make it possible to overwrite RPMEM_PORT

---

src/benchmarks/pmem_flush.c
src/common/out.c
src/common/pthread_windows.c
src/common/util.h
src/examples/libpmemobj/lists.c
src/include/librpmem.h
src/test/rpmemd_db/rpmemd_db_test.c
utils/cstyle

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/817)

common: fix cstyle rules

---

src/libpmemobj/bucket.c
src/libpmemobj/memblock.c
src/libpmemobj/pmalloc.c
src/test/ex_linkedlist/TEST1
src/test/ex_linkedlist/ex_linkedlist.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/820)

common: fix spelling errors

---

src/examples/libpmemobj/pman/README
src/examples/libpmemobj/pman/pman.cpp
src/test/ex_libpmemobj_cpp/TEST1
utils/style_check.sh

Fix pman crash on bomb cleanup. Add pman unit test. Modify pman
to take arbitrary map file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/823)

examples: fix pman

---

src/test/tools/bttcreate/bttcreate.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/825)

test: bttcreate fix for memcheck

---

src/include/libpmemobj/condition_variable.hpp
src/include/libpmemobj/detail/array_traits.hpp
src/include/libpmemobj/detail/check_persistent_ptr_array.hpp
src/include/libpmemobj/detail/common.hpp
src/include/libpmemobj/detail/conversions.hpp
src/include/libpmemobj/detail/destroyer.hpp
src/include/libpmemobj/detail/integer_sequence.hpp
src/include/libpmemobj/detail/make_atomic_impl.hpp
src/include/libpmemobj/detail/pexceptions.hpp
src/include/libpmemobj/detail/specialization.hpp
src/include/libpmemobj/make_persistent.hpp
src/include/libpmemobj/make_persistent_array.hpp
src/include/libpmemobj/make_persistent_array_atomic.hpp
src/include/libpmemobj/make_persistent_atomic.hpp
src/include/libpmemobj/mutex.hpp
src/include/libpmemobj/p.hpp
src/include/libpmemobj/persistent_ptr.hpp
src/include/libpmemobj/pext.hpp
src/include/libpmemobj/pool.hpp
src/include/libpmemobj/shared_mutex.hpp
src/include/libpmemobj/timed_mutex.hpp
src/include/libpmemobj/transaction.hpp

This enables the generation of documentation for functions such as
make_persistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/826)

cpp: add file comments

---

src/libpmemobj/obj.h

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/828)

obj: remove object store pointer

---

src/common/util.c
src/test/testconfig.ps1.example

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/830)

win: address a few minor items as followup to the windows UT merge

---

src/libpmemobj/memblock.h
src/libpmemobj/pmalloc.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/833)

obj: add explanation of memory block operations

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/834)

doc: clarify statement in readme.md about travis.yml dependencies

---

src/common/set.c
src/test/blk_nblock/out0.log.match
src/test/blk_pool/out7.log.match
src/test/log_pool/out6.log.match
src/test/obj_pool/out7.log.match
src/test/rpmemd_db/TEST0
src/test/rpmemd_db/TEST1
src/test/util_poolset/out0.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/835)

common: fix errno value

---

src/common/set.c
src/common/util.h
src/tools/rpmemd/rpmemd_db.c
src/tools/rpmemd/rpmemd_db.h

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/837)

rpmemd: split create and open functions

---

src/common/set.c
src/common/util.h
src/test/blk_nblock/blk_nblock.c
src/test/blk_non_zero/blk_non_zero.c
src/test/blk_pool/blk_pool.c
src/test/log_pool/log_pool.c
src/test/obj_heap_state/obj_heap_state.c
src/test/obj_many_size_allocs/obj_many_size_allocs.c
src/test/obj_out_of_memory/obj_out_of_memory.c
src/test/unittest/unittest.h
src/test/unittest/ut.c
src/test/unittest/ut_file.c
src/tools/pmempool/common.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/836)

win: few minor tweaks

---

src/common/set.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/840)

common: fix setting created in part file

---

src/examples/libpmemobj/cpp_map/ctree_map_persistent.hpp
src/examples/libpmemobj/cpp_map/ctree_map_transient.hpp
src/libpmemobj/memblock.h

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/843)

obj: fix typos in comments

---

src/test/rpmemd_db/TEST0
src/test/rpmemd_db/TEST1
src/test/rpmemd_db/err1.log.match
src/test/rpmemd_db/out0.log.match
src/test/rpmemd_db/out1.log.match
src/test/rpmemd_db/rpmem1.log.match
src/test/rpmemd_db/rpmemd1.log.match
src/test/rpmemd_db/rpmemd_db_test.c
src/test/rpmemd_db/trace0.log.match
src/test/rpmemd_db/trace1.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/845)

test: extend rpmemd_db tests

---

doc/librpmem.3
src/examples/librpmem/basic.c
src/include/librpmem.h
src/librpmem/rpmem.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/846)

rpmem: fix type of nlanes argument

---

README.md
appveyor.yml
src/NVML.sln
src/test/.gitignore
src/test/RUNTESTS
src/test/tools/sparsefile/README
src/test/tools/sparsefile/TEST_SPARSE.ps1
src/test/tools/sparsefile/sparsefile.c
src/test/tools/sparsefile/sparsefile.vcxproj
src/test/tools/sparsefile/sparsefile.vcxproj.filters
src/test/unittest/unittest.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/842)

win: a few unit test tweaks

---

src/libpmemobj/tx.c

1) When application snapshotted an area from inside of
a PMEMmutex / PMEMrwlock, we would restore it on abort.
2) When application snapshotted 2 areas - one ending in the middle
of a lock and one starting in the middle of a lock, we would restore
the 2nd one.
Applications that snapshot part of a lock are buggy anyway, so for
correct apps this fix should not matter.
I noticed these bugs while cleaning up tx_restore_range function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/848)

obj: fix 2 bugs in transaction abort

---

src/common/set.c
src/test/tools/ctrld/ctrld.c

Ref: pmem/issues#176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/849)

common: remove redundant EOL chars in debug traces

---

src/test/tools/sparsefile/sparsefile.c
src/test/win_tests/TEST0.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/854)

test: fix typos in comments

---

appveyor.yml
src/NVML.sln
src/common/liblinux.vcxproj.filters
src/test/blk_nblock/TEST0w.ps1
src/test/blk_nblock/TEST1.ps1
src/test/blk_nblock/TEST2w.ps1
src/test/blk_nblock/blk_nblock.vcxproj
src/test/blk_nblock/blk_nblock.vcxproj.filters
src/test/blk_non_zero/TEST1.ps1
src/test/blk_non_zero/TEST2.ps1
src/test/blk_non_zero/TEST3.ps1
src/test/blk_non_zero/TEST4.ps1
src/test/blk_non_zero/TEST9.ps1
src/test/blk_non_zero/blk_non_zero.vcxproj
src/test/blk_non_zero/blk_non_zero.vcxproj.filters
src/test/blk_non_zero/blk_non_zero.vcxproj.user
src/test/blk_pool/blk_pool.vcxproj.filters
src/test/blk_rw/blk_rw.vcxproj.filters
src/test/log_basic/log_basic.vcxproj.filters
src/test/log_pool/log_pool.vcxproj.filters
src/test/obj_check/obj_check.vcxproj.filters
src/test/obj_heap_state/obj_heap_state.vcxproj.filters
src/test/obj_many_size_allocs/obj_many_size_allocs.vcxproj.filters
src/test/obj_out_of_memory/obj_out_of_memory.vcxproj.filters
src/test/unittest/libut.vcxproj.filters
src/test/unittest/unittest.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/853)

win: speed up test execution on AppVeyor

---

src/include/libpmemobj/transaction.hpp

Refs pmem/issues#173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/857)

cpp: transaction.hpp style changes

---

src/test/Makefile.inc
src/test/RUNTESTS

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/855)

test: do not run Windows tests on Linux

---

src/examples/libpmemobj/pman/pman.cpp
src/test/Makefile.inc
src/test/ex_libpmemobj/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/861)

test: pman fixes

---

src/examples/libpmemobj/cpp/queue.cpp
src/examples/libpmemobj/cpp_map/ctree_map_persistent.hpp
src/examples/libpmemobj/cpp_map/ctree_map_transient.hpp
src/examples/libpmemobj/cpp_map/map_cli.cpp
src/examples/libpmemobj/pman/pman.cpp
src/include/libpmemobj/make_persistent_atomic.hpp
src/include/libpmemobj/utils.hpp
src/test/obj_cpp_cond_var/obj_cpp_cond_var.cpp
src/test/obj_cpp_cond_var_posix/obj_cpp_cond_var_posix.cpp
src/test/obj_cpp_make_persistent/obj_cpp_make_persistent.cpp
src/test/obj_cpp_make_persistent_array/obj_cpp_make_persistent_array.cpp
src/test/obj_cpp_make_persistent_array_atomic/obj_cpp_make_persistent_array_atomic.cpp
src/test/obj_cpp_make_persistent_atomic/obj_cpp_make_persistent_atomic.cpp
src/test/obj_cpp_mutex/obj_cpp_mutex.cpp
src/test/obj_cpp_mutex_posix/obj_cpp_mutex_posix.cpp
src/test/obj_cpp_p_ext/obj_cpp_p_ext.cpp
src/test/obj_cpp_pool/obj_cpp_pool.cpp
src/test/obj_cpp_pool_primitives/obj_cpp_pool_primitives.cpp
src/test/obj_cpp_ptr/obj_cpp_ptr.cpp
src/test/obj_cpp_ptr_arith/obj_cpp_ptr_arith.cpp
src/test/obj_cpp_shared_mutex/obj_cpp_shared_mutex.cpp
src/test/obj_cpp_shared_mutex_posix/obj_cpp_shared_mutex_posix.cpp
src/test/obj_cpp_timed_mtx/obj_cpp_timed_mtx.cpp
src/test/obj_cpp_timed_mtx_posix/obj_cpp_timed_mtx_posix.cpp
src/test/obj_cpp_transaction/obj_cpp_transaction.cpp

Use a unified style for C++ code in the example and unit tests. `using namespace` should never be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/864)

Fix cpp style

---

src/.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/866)

common: update .gitignore

---

src/common/mmap_windows.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/869)

win:fix bug in msync

---

src/include/libpmemobj.h
src/test/ex_linkedlist/ex_linkedlist.c
src/test/obj_basic_integration/obj_basic_integration.c
src/test/obj_constructor/obj_constructor.c
src/test/obj_convert/obj_convert.c
src/test/obj_heap_interrupt/obj_heap_interrupt.c
src/test/obj_memcheck/obj_memcheck.c
src/test/obj_realloc/obj_realloc.c
src/test/obj_recovery/obj_recovery.c
src/test/obj_recreate/obj_recreate.c
src/test/obj_tx_invalid/obj_tx_invalid.c

...and POBJ_LAYOUT_TYPES_NUM macro to make them work with VC++ compiler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/868)

obj: modify POBJ_LAYOUT_END macro

---

doc/pmempool.1
src/tools/pmempool/rm.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/870)

pmempool: minor fixes

---

doc/librpmem.3
src/include/librpmem.h
src/librpmem/rpmem.c

Ref: pmem/issues#171
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/872)

rpmem: fix order of parameters in rpmem_read()

---

src/tools/rpmemd/rpmemd_db.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/876)

rpmemd: fix providing size in rpmemd_db

---

src/test/rpmemd_db/rpmemd1.log.match
src/test/rpmemd_db/test0-root/test0-pool0.set
src/test/rpmemd_db/test0-root/test0-pool1.set
src/test/rpmemd_db/test1-root/test1-pool0.set
src/test/rpmemd_db/test1-root/test1-pool1.set

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/875)

test: fix rpmemd_db parallel tests

---

src/examples/libpmemobj/Makefile

Somehow Makefile change was not upstreamed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/879)

examples: build panaconda

---

src/examples/libpmemobj/tree_map/btree_map.c
src/examples/libpmemobj/tree_map/ctree_map.c
src/examples/libpmemobj/tree_map/rbtree_map.c

Side effect of my header split work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/880)

examples: use transactional free in tree maps

---

doc/libpmemobj.3
src/include/libpmemobj.h

It will be used extensively in pmemobj_list.h.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/878)

obj: add TOID_TYPEOF macro

---

src/tools/rpmemd/rpmemd_db.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/881)

rpmemd: fix rpmemd_db_concat

---

src/test/unittest/libut.vcxproj
src/test/unittest/libut.vcxproj.filters
src/test/unittest/ut_backtrace.c
src/windows/include/platform.h

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/873)

test: dump stacktrace on fatal signals (Windows)

---

src/examples/libpmemobj/Makefile
src/test/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/886)

build: warn about skipped C++ tests/examples

---

doc/pmempool-create.1
src/tools/pmempool/create.c

Remove the details of BTT layout writing from pmempool.
Refs pmem/issues#183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/884)

tools: clarify pmempool create -w flag

---

src/test/ex_libpmemobj_cpp/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/885)

test: fix ncurses detection in pman test

---

doc/libpmemblk.3
doc/libpmemlog.3
doc/libpmemobj.3

Ref: pmem/issues#133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/887)

doc: update description of valid file size units

---

src/libpmemobj/tx.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/891)

obj: minor optimizations

---

src/common/set.c

... in util_header_check_remote()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/897)

common: fix checking UUID of next replica

---

src/libpmemobj/pvector.c
src/libpmemobj/tx.c
src/test/obj_pmalloc_basic/obj_pmalloc_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/896)

obj: simplify undo log vector initialization

---

src/examples/libpmemobj/linkedlist/Makefile
src/examples/libpmemobj/linkedlist/fifo.c
src/examples/libpmemobj/linkedlist/pmemobj_list.h
src/test/ex_linkedlist/TEST0
src/test/ex_linkedlist/ex_linkedlist.c
src/test/ex_linkedlist/out0.log.match
src/test/ex_linkedlist/out1.log.match

1) Allow embedding of list head (previously head must had been a separate object).
2) Snapshot only modified parts of objects.
3) Other cleanups/optimizations/fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/900)

examples/lists: refactor

---

src/test/tools/pmemspoil/spoil.c

Just a simple field addition
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/901)

test/tools: add uuid field to bbt_info in spoil

---

src/libpmemobj/heap_layout.h
src/libpmemobj/list.c
src/libpmemobj/list.h
src/libpmemobj/pmalloc.c
src/test/obj_lane/obj_lane.c
src/test/tools/pmemspoil/spoil.c
src/tools/pmempool/info_obj.c

Its been bugging me for literally months now ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/899)

obj: unify lane section layout naming scheme

---

src/libpmemobj/memblock.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/898)

obj: change camelCase variable name in memblock code

---

src/common/set.c
src/common/util.h
src/tools/rpmemd/rpmemd_db.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/865)

rpmemd: set arch_flags

---

src/libpmemobj/heap.c
src/libpmemobj/pvector.c
src/librpmem/rpmem_fip.c
src/rpmem_common/rpmem_fip_common.c
src/rpmem_common/rpmem_fip_lane.h
src/test/blk_pool/TEST0.PS1
src/test/blk_pool/TEST25.PS1
src/test/blk_pool/TEST26.PS1
src/test/blk_pool/TEST30w.PS1
src/test/obj_convert/obj_convert.c
src/tools/rpmemd/rpmemd_fip_worker.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/907)

common: fix a bunch of typos in comments

---

appveyor.yml
src/test/RUNTESTS.ps1
src/test/blk_nblock/TEST0w.PS1
src/test/blk_nblock/blk_nblock.vcxproj.filters
src/test/blk_non_zero/blk_non_zero.vcxproj.filters
src/test/blk_pool/TEST10.PS1
src/test/blk_pool/TEST11.PS1
src/test/blk_pool/TEST25.PS1
src/test/blk_pool/TEST26.PS1
src/test/blk_pool/TEST5.PS1
src/test/blk_pool/blk_pool.vcxproj
src/test/blk_pool/blk_pool.vcxproj.filters
src/test/tools/sparsefile/sparsefile.vcxproj.filters
src/test/unittest/unittest.ps1
src/test/util_is_absolute/util_is_absolute.vcxproj.filters
src/test/win_lists/win_lists.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/903)

A bunch of fixes for Windows test scripts

---

doc/libpmemobj.3
src/libpmemobj/list.c

Ref: pmem/issues#151
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/871)

obj: validate before flag value

---

doc/cppobj.Doxyfile
src/examples/Makefile.inc
src/examples/libpmemobj/doc_snippets/Makefile
src/examples/libpmemobj/doc_snippets/make_persistent.cpp
src/examples/libpmemobj/doc_snippets/mutex.cpp
src/examples/libpmemobj/doc_snippets/persistent.cpp
src/examples/libpmemobj/doc_snippets/pool.cpp
src/examples/libpmemobj/doc_snippets/transaction.cpp
src/include/libpmemobj/README.md
src/include/libpmemobj/condition_variable.hpp
src/include/libpmemobj/make_persistent.hpp
src/include/libpmemobj/make_persistent_array.hpp
src/include/libpmemobj/make_persistent_array_atomic.hpp
src/include/libpmemobj/make_persistent_atomic.hpp
src/include/libpmemobj/mutex.hpp
src/include/libpmemobj/p.hpp
src/include/libpmemobj/persistent_ptr.hpp
src/include/libpmemobj/pool.hpp
src/include/libpmemobj/shared_mutex.hpp
src/include/libpmemobj/timed_mutex.hpp
src/include/libpmemobj/transaction.hpp

Added examples to most functions and classes. Code snippets are compiled
as part of examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/912)

cpp: extend documentation

---

src/Makefile

from 5.7s to 4.8s
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/911)

build: speed up no-rebuild case by 15%

---

src/Makefile.inc
src/test/Makefile.inc
src/tools/Makefile.inc

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/918)

build: small improvements

---

doc/Makefile
doc/README
doc/pmempool-convert.1
doc/pmempool.1
src/test/obj_convert/TEST0
src/tools/pmempool/Makefile
src/tools/pmempool/convert.c
utils/build-dpkg.sh
utils/build-rpm.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/932)

add pmempool convert documentation

---

src/Makefile
src/libpmempool/Makefile
utils/build-dpkg.sh
utils/build-rpm.sh
utils/make-pkg-config.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/931)

libpmempool: fix package building

---

index.md
libpmemblk/libpmemblk.3.html
libpmemlog/libpmemlog.3.html
libpmemobj/libpmemobj.3.html
libpmempool/index.md
libpmempool/libpmempool.3.html
pmempool/index.md
pmempool/pmempool-convert.1.html
pmempool/pmempool-create.1.html
pmempool/pmempool-info.1.html
pmempool/pmempool.1.html

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/940)

doc: update man pages

---

doc/libpmempool.3
src/examples/README
src/examples/libpmempool/.gitignore
src/examples/libpmempool/Makefile
src/examples/libpmempool/README
src/examples/libpmempool/manpage.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/941)

doc: add example for libpmempool man page

---

src/test/unittest/unittest.h
src/tools/rpmemd/rpmemd_db.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/945)

Fix build issues on Fedora

---

src/examples/librpmem/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/937)

examples: fix libfabric detection

---

src/libpmemobj/pvector.c
src/libpmemobj/pvector.h
src/libpmemobj/tx.c
src/test/obj_pvector/obj_pvector.c
src/tools/pmempool/Makefile
src/tools/pmempool/info_obj.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/919)

obj: unify all alloc & init functions to _new

---

src/test/testconfig.sh.example

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/938)

test: document NODE_ADDR in testconfig example

---

src/test/unittest/unittest.ps1
src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/908)

test: add remote replicas to create_poolset()

---

src/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/924)

common: check cstyle for windows files

---

src/libpmemobj/pmalloc.c
src/test/obj_constructor/TEST1
src/test/obj_constructor/memcheck1.log.match
src/test/obj_constructor/obj_constructor.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/936)

obj: fix valgrind instrumentation for canceled allocs

---

src/tools/pmempool/output.c

Ref: pmem/issues#178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/939)

tools: fix the format of checksum printing

---

src/librpmem/README
src/tools/rpmemd/README

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/946)

rpmem: add README files for rpmemd and librpmem

---

src/common/set.c
src/common/util.c
src/common/util.h
src/test/arch_flags/log0.log.match
src/test/rpmemd_db/rpmemd_db_test.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/895)

test: randomize attributes in rpmemd_db test

---

src/NVML.sln
src/common/mmap_windows.c
src/test/unittest/libut.vcxproj
src/test/unittest/libut.vcxproj.filters
src/test/unittest/unittest.h
src/test/unittest/ut_signal.c
src/test/win_mmap/.gitignore
src/test/win_mmap/Makefile
src/test/win_mmap/TEST0
src/test/win_mmap/TEST0.ps1
src/test/win_mmap/win_mmap.c
src/test/win_mmap/win_mmap.vcxproj
src/test/win_mmap/win_mmap.vcxproj.filters
src/windows/include/platform.h

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/925)

common: fix memory mapping implementation on Windows

---

utils/check_license/check-headers.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/890)

utils: do not check license in groff files

---

src/NVML.sln
src/libpmem/libpmem.def
src/test/unittest/libut.vcxproj
src/test/win_mmap/TEST0.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/947)

win: fix compilation issues

---

.travis.yml
utils/docker/README
utils/docker/build.sh
utils/docker/configure-tests.sh
utils/docker/images/Dockerfile.fedora:23
utils/docker/images/Dockerfile.ubuntu:16.04
utils/docker/images/README
utils/docker/images/build-image.sh
utils/docker/images/install-libfabric.sh
utils/docker/images/install-valgrind.sh
utils/docker/prepare-environment.sh
utils/docker/prepare-for-build.sh
utils/docker/run-build-package.sh
utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/942)

Travis integration with docker - ubuntu + fedora

---

doc/libpmemobj.3
src/include/libpmemobj.h
src/test/obj_basic_integration/obj_basic_integration.c

...and use it in POBJ_LIST_* macros.
Ref: pmem/issues#191
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/950)

obj: add TOID_OFFSETOF macro

---

src/benchmarks/benchmark_worker.c
src/benchmarks/log.c
src/benchmarks/pmembench.c
src/benchmarks/pmemobj_atomic_lists.c
src/benchmarks/pmemobj_gen.c
src/benchmarks/pmemobj_tx.c
src/libpmemobj/heap.c
src/tools/pmempool/common.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/951)

common: klocwork fixes

---

src/benchmarks/benchmark_worker.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/952)

benchmark: fix benchmark_worker_alloc()

---

src/libpmemobj/cuckoo.c
src/libpmemobj/cuckoo.h
src/test/obj_cuckoo/obj_cuckoo.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/955)

obj: slightly improve hashtable avg load factor

---

src/common/set.c
src/common/util.h

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/953)

common: move part handling functions to interface

---

src/tools/rpmemd/rpmemd_config.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/954)

rpmemd: fix types in parse_cl_args()

---

src/test/rpmem_fip/README

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/961)

test: document interaction with systemd >= 230

---

src/test/pmemspoil/TEST0
src/tools/pmempool/common.c
src/tools/pmempool/common.h
src/tools/pmempool/info.c

Ref: pmem/issues#177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/959)

tools: correct misleading message

---

doc/librpmem.3.md
src/examples/librpmem/.gitignore
src/examples/librpmem/Makefile
src/examples/librpmem/manpage.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/958)

rpmem: manpage for librpmem

---

src/libpmempool/check.c
src/libpmempool/check_pool_hdr.c
src/libpmempool/check_util.c
src/test/pmempool_check/TEST9
src/test/pmempool_check/out9.log.match

Closes pmem/issues#186
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/964)

libpmempool: check: fix obj support

---

src/tools/rpmemd/rpmemd.c

- fix use of possibly uninitialized structure
- fix memleak in error handling in rpmemd
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/968)

rpmem: fix some minor issues

---

README.md
utils/build-dpkg.sh

.. when RPMEM_DPKG=y is set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/972)

rpmem: build dpkg packages optionally

---

src/test/win_lists/TEST0.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/978)

test: change FS requirement for win_lists test

---

src/libpmemobj/obj.c
src/libpmemobj/redo.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/981)

obj: fix redo log initialization

---

CODING_STYLE.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/982)

doc: add NVML coding style guide

---

src/libpmemobj/heap.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/989)

obj: fix an error-case issue /w accessing bucket array

---

src/include/libpmemobj/mutex.hpp
src/include/libpmemobj/shared_mutex.hpp
src/include/libpmemobj/timed_mutex.hpp

Changes in mutex, timed_mutex, shared_mutex comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/988)

cpp: refactor file comments

---

src/test/tools/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/992)

test: fix parallel build when "test" target is used

---

src/libpmemobj/tx.c
src/test/obj_tx_add_range/obj_tx_add_range.c
src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c

Ref: pmem/issues#203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/995)

obj: add a validity check for too large snapshots

---

appveyor.yml
src/test/unittest/unittest.ps1
utils/CHECK_WHITESPACE.PS1
utils/check_whitespace

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/996)

win: include PS1 files in check_whitespace script 

---

src/test/win_mmap/win_mmap.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/998)

test: add mprotect tests with anon mappings

---

src/librpmem/rpmem_ssh.c
src/tools/rpmemd/rpmemd.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1006)

rpmem: fix klocwork issues

---

src/libpmemobj/obj.c
src/libpmemobj/obj.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1008)

obj: fix double free corruption

---

utils/docker/configure-tests.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1009)

common: add RPMEM_PORT variable to testconfig.sh

---

src/common.inc

Error due to a wrong doc install path.
Refs: pmem/issues#210
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1013)

cpp: fix deb doc-base error

---

src/test/obj_cpp_timed_mtx/obj_cpp_timed_mtx.cpp

Fix timed_mutex tests failing on windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1014)

win: add espilon to timed_mtx tests

---

src/libpmemobj/heap.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1017)

obj: fix a typo in comment

---

src/libpmemobj/lane.c
src/test/obj_lane/TEST1
src/test/obj_lane/obj_lane.c
src/test/obj_lane/out0.log.match
src/test/obj_lane/out1.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/993)

obj: lane cleanup fix

---

src/common/set.c
src/test/obj_rpmem_basic_integration/TEST0
src/test/obj_rpmem_basic_integration/TEST1
src/test/obj_rpmem_basic_integration/TEST2
src/test/obj_rpmem_basic_integration/TEST3
src/test/obj_rpmem_basic_integration/TEST4
src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1020)

rpmem: fix obj testing and error handling

---

.travis.yml
utils/docker/README
utils/docker/images/Dockerfile.fedora-23
utils/docker/images/Dockerfile.ubuntu-16.04
utils/docker/images/build-image.sh
utils/docker/images/push-image.sh
utils/docker/prepare-environment.sh
utils/docker/pull-or-rebuild-image.sh

When Travis is running NVML build with changes to the scripts which
build the Docker images, appropriate Docker images will be rebuilt.
If the build is after merge of a pull request, the newly created
Docker image will be pushed to the Docker Hub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1018)

common: automated Docker image builds on Travis

---

src/libpmemobj/pmalloc.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1025)

obj: add missing briefs

---

src/test/log_basic/TEST0.PS1
src/test/log_basic/TEST1.PS1
src/test/log_basic/TEST2.PS1
src/test/log_basic/TEST3.PS1
src/test/log_basic/TEST4.PS1
src/test/log_basic/TEST5.PS1
src/test/log_basic/TEST6w.PS1
src/test/log_basic/log_basic.vcxproj
src/test/log_basic/log_basic.vcxproj.filters
src/test/log_basic/out0.log.match
src/test/log_basic/out1.log.match
src/test/log_basic/out2.log.match
src/test/log_basic/out3.log.match
src/test/log_basic/out4.log.match
src/test/log_basic/out5.log.match
src/test/log_basic/out6.log.match
src/test/log_basic/out6w.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1028)

win: add tests for log_basic

---

src/libpmemobj/heap.c
src/libpmemobj/lane.c
src/libpmemobj/list.c
src/libpmemobj/pmalloc.c
src/libpmemobj/tx.c

Ref: pmem/issues#215
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1029)

obj: update comments

---

utils/docker/images/Dockerfile.ubuntu-16.04

It's used by Doxygen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1033)

docker/ubuntu: install graphviz

---

src/.gitignore
src/common/libpmemcommon.vcxproj
src/libpmem/libpmem.vcxproj
src/libpmemblk/libpmemblk.vcxproj
src/libpmemlog/libpmemlog.vcxproj
src/libpmemobj/libpmemobj.vcxproj
src/libpmempool/libpmempool.vcxproj
src/test/tools/pmemalloc/pmemalloc.vcxproj
src/test/tools/pmemspoil/pmemspoil.vcxproj
src/test/tools/pmemwrite/pmemwrite.vcxproj
src/tools/pmempool/pmempool.vcxproj
src/windows/liblinux.vcxproj
utils/SRCVERSION.ps1

This patch sets SRCVERSION on windows based on git describe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1040)

win: add SRCVERSION

---

src/NVML.sln
src/test/obj_heap/TEST0.PS1
src/test/obj_heap/obj_heap.vcxproj
src/test/obj_heap/obj_heap.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1046)

win: test obj_heap windows port

---

src/include/libpmemobj++/condition_variable.hpp
src/include/libpmemobj++/detail/common.hpp
src/include/libpmemobj++/make_persistent.hpp
src/include/libpmemobj++/make_persistent_array.hpp
src/include/libpmemobj++/make_persistent_array_atomic.hpp
src/include/libpmemobj++/make_persistent_atomic.hpp
src/include/libpmemobj++/mutex.hpp
src/include/libpmemobj++/pool.hpp
src/include/libpmemobj++/timed_mutex.hpp
src/include/libpmemobj++/transaction.hpp
src/include/libpmemobj++/utils.hpp

Reformat files according to clang-format after changes in the tree.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1050)

cpp: reformat cpp files

---

src/libpmemobj/obj.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1052)

obj: remove unused parameter

---

src/NVML.sln
src/test/log_pool_lock/TEST0.PS1
src/test/log_pool_lock/log_pool_lock.c
src/test/log_pool_lock/log_pool_lock.vcxproj
src/test/log_pool_lock/log_pool_lock.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1049)

win: port log_pool_lock test

---

src/NVML.sln
src/test/obj_locks/TEST0.PS1
src/test/obj_locks/obj_locks.c
src/test/obj_locks/obj_locks.vcxproj
src/test/obj_locks/obj_locks.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1055)

win: test obj_locks windows port

---

doc/librpmem.3.md
doc/rpmemd.1.md
src/librpmem/rpmem_obc.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1054)

doc: rpmem minor fixes

---

src/examples/libpmemobj/map/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1059)

examples: fix libuv detection

---

doc/libpmemobj.3.md
src/examples/libpmemobj/.gitignore
src/examples/libpmemobj/Makefile
src/examples/libpmemobj/README
src/examples/libpmemobj/setjmp.c

...and add it to libpmemobj examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1066)

doc: fix setjmp example in pmemobj man page

---

src/NVML.sln
src/test/obj_pool_lock/TEST0.PS1
src/test/obj_pool_lock/obj_pool_lock.c
src/test/obj_pool_lock/obj_pool_lock.vcxproj
src/test/obj_pool_lock/obj_pool_lock.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1070)

win: port test obj_pool_lock

---

src/test/blk_pool/TEST22.PS1
src/test/log_pool/TEST22.PS1
src/test/unittest/unittest.ps1

... and use it in log_pool/blk_pool to shrink the file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1075)

win: emulate 'truncate' command

---

utils/docker/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1069)

docker: use good clang-format version

---

src/libpmemobj/tx.c
src/test/obj_basic_integration/obj_basic_integration.c
src/test/obj_basic_integration/out0.log.match
src/test/obj_basic_integration/out1.log.match
src/test/obj_basic_integration/out2.log.match
src/test/obj_basic_integration/out3.log.match
src/test/obj_basic_integration/out4.log.match
src/test/obj_rpmem_basic_integration/node_1_out0.log.match
src/test/obj_rpmem_basic_integration/node_1_out1.log.match
src/test/obj_rpmem_basic_integration/node_1_out2.log.match
src/test/obj_rpmem_basic_integration/node_1_out3.log.match
src/test/obj_rpmem_basic_integration/node_1_out4.log.match
src/test/obj_tx_alloc/obj_tx_alloc.c

Before this change pmemobj_errormsg returned previous error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1035)

obj: set error message when user called pmemobj_tx_abort 

---

src/NVML.sln
src/common/util.c
src/test/util_parse_size/TEST0.PS1
src/test/util_parse_size/out0.log.match
src/test/util_parse_size/util_parse_size.c
src/test/util_parse_size/util_parse_size.vcxproj
src/test/util_parse_size/util_parse_size.vcxproj.filters
src/windows/win_signal.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1080)

win: add tests for util_parse_size

---

src/test/blk_recovery/TEST0.PS1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1078)

win: fix blk_recovery merge issue

---

src/NVML.sln
src/test/util_cpuid/TEST0.PS1
src/test/util_cpuid/util_cpuid.c
src/test/util_cpuid/util_cpuid.vcxproj
src/test/util_cpuid/util_cpuid.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1083)

win: port util_cpuid

---

src/NVML.sln
src/test/log_recovery/TEST0.PS1
src/test/log_recovery/TEST1.PS1
src/test/log_recovery/log_recovery.c
src/test/log_recovery/log_recovery.vcxproj
src/test/log_recovery/log_recovery.vcxproj.filters
src/test/log_recovery/out0.log.match
src/test/log_recovery/out1.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1086)

win: port log_recovery test

---

src/test/libpmempool_bttdev/TEST1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1090)

common: silence the pmemspoil tool in test script

---

src/NVML.sln
src/test/util_is_poolset/TEST0.PS1
src/test/util_is_poolset/out0.log.match
src/test/util_is_poolset/util_is_poolset.vcxproj
src/test/util_is_poolset/util_is_poolset.vcxproj.filters
src/test/util_parse_size/util_parse_size.vcxproj.filters

Also added a few missing test script folders in recently added
projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1084)

win: add test for util_is_poolset

---

src/NVML.sln
src/test/obj_pool_lookup/TEST0.PS1
src/test/obj_pool_lookup/obj_pool_lookup.c
src/test/obj_pool_lookup/obj_pool_lookup.vcxproj
src/test/obj_pool_lookup/obj_pool_lookup.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1093)

win: port test obj_pool_lookup

---

src/NVML.sln
src/test/pmem_memmove/TEST0.PS1
src/test/pmem_memmove/TEST1.PS1
src/test/pmem_memmove/TEST10.PS1
src/test/pmem_memmove/TEST11.PS1
src/test/pmem_memmove/TEST12.PS1
src/test/pmem_memmove/TEST2.PS1
src/test/pmem_memmove/TEST3.PS1
src/test/pmem_memmove/TEST4.PS1
src/test/pmem_memmove/TEST5.PS1
src/test/pmem_memmove/TEST6.PS1
src/test/pmem_memmove/TEST7.PS1
src/test/pmem_memmove/TEST8.PS1
src/test/pmem_memmove/TEST9.PS1
src/test/pmem_memmove/out0.log.match
src/test/pmem_memmove/out1.log.match
src/test/pmem_memmove/out10.log.match
src/test/pmem_memmove/out11.log.match
src/test/pmem_memmove/out12.log.match
src/test/pmem_memmove/out2.log.match
src/test/pmem_memmove/out3.log.match
src/test/pmem_memmove/out4.log.match
src/test/pmem_memmove/out5.log.match
src/test/pmem_memmove/out6.log.match
src/test/pmem_memmove/out7.log.match
src/test/pmem_memmove/out8.log.match
src/test/pmem_memmove/out9.log.match
src/test/pmem_memmove/pmem_memmove.vcxproj
src/test/pmem_memmove/pmem_memmove.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1099)

win: add tests for pmem_memmove

---

src/NVML.sln
src/test/pmem_memset/TEST0.PS1
src/test/pmem_memset/TEST1.PS1
src/test/pmem_memset/out0.log.match
src/test/pmem_memset/out1.log.match
src/test/pmem_memset/pmem_memset.c
src/test/pmem_memset/pmem_memset.vcxproj
src/test/pmem_memset/pmem_memset.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1097)

win: add tests for pmem_memset

---

src/NVML.sln
src/test/pmem_memcpy/TEST0.PS1
src/test/pmem_memcpy/TEST1.PS1
src/test/pmem_memcpy/TEST2.PS1
src/test/pmem_memcpy/TEST3.PS1
src/test/pmem_memcpy/out0.log.match
src/test/pmem_memcpy/out1.log.match
src/test/pmem_memcpy/out2.log.match
src/test/pmem_memcpy/out3.log.match
src/test/pmem_memcpy/pmem_memcpy.c
src/test/pmem_memcpy/pmem_memcpy.vcxproj
src/test/pmem_memcpy/pmem_memcpy.vcxproj.filters

Includes .vcxproj file and 4 powershell scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1095)

win: add tests for windows pmem_memcpy

---

src/NVML.sln
src/test/obj_tx_mt/TEST0.PS1
src/test/obj_tx_mt/obj_tx_mt.c
src/test/obj_tx_mt/obj_tx_mt.vcxproj
src/test/obj_tx_mt/obj_tx_mt.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1101)

win: port test obj_tx_mt

---

src/NVML.sln
src/test/obj_strdup/TEST0.PS1
src/test/obj_strdup/obj_strdup.vcxproj
src/test/obj_strdup/obj_strdup.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1106)

win: port test obj_strdup

---

src/NVML.sln
src/test/obj_tx_locks/TEST0.PS1
src/test/obj_tx_locks/TEST1
src/test/obj_tx_locks/TEST1.PS1
src/test/obj_tx_locks/TEST2.PS1
src/test/obj_tx_locks/obj_tx_locks.vcxproj
src/test/obj_tx_locks/obj_tx_locks.vcxproj.filters
src/test/obj_tx_locks/out0.log.match
src/test/obj_tx_locks/out1.log.match
src/test/obj_tx_locks/out2.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1105)

win: add tests for obj_tx_locks

---

src/NVML.sln
src/test/traces_pmem/TEST0.PS1
src/test/traces_pmem/traces_pmem.vcxproj
src/test/traces_pmem/traces_pmem.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1103)

win: add tests for traces_pmem

---

src/test/RUNTESTS.ps1

Fix incorrect implementation of -s.  -s should specify the test
script name but was being used as test dir name.  Test dir name
on linux does not require a switch however in PS we can't have
a combo of switched args and positional args so the fix is to
use -i to specify test dir.  So, for example, to run just TEST0
in the blk_nblock test dir:
.\RUNTESTS -i blk_nblock -s TEST0
to run all test in the dir:
.\RUNTESTS -i blk-nblock
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1098)

win: fix bug in RUNTESTS

---

src/test/obj_tx_locks/obj_tx_locks.vcxproj
src/test/pmem_memcpy/pmem_memcpy.vcxproj
src/test/pmem_memmove/pmem_memmove.vcxproj
src/test/pmem_memset/pmem_memset.vcxproj
src/test/util_is_poolset/util_is_poolset.vcxproj
src/test/util_poolset_foreach/util_poolset_foreach.vcxproj
src/test/util_poolset_size/util_poolset_size.vcxproj
src/test/util_uuid_generate/util_uuid_generate.vcxproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1108)

win: fix targetPlatformVersion

---

src/common/libpmemcommon.vcxproj
src/test/blk_pool_lock/blk_pool_lock.vcxproj
src/test/obj_constructor/obj_constructor.vcxproj
src/test/tools/pmemalloc/pmemalloc.vcxproj
src/test/tools/pmemspoil/pmemspoil.vcxproj
src/test/tools/pmemwrite/pmemwrite.vcxproj
src/test/util_is_absolute/util_is_absolute.vcxproj
src/test/win_lists/win_lists.vcxproj
src/test/win_mmap/win_mmap.vcxproj
src/tools/pmempool/pmempool.vcxproj
src/windows/srcversion/srcversion.vcxproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1110)

win: fix-namespace-root-in-solution-projects

---

src/NVML.sln
src/test/traces_custom_function/TEST0.PS1
src/test/traces_custom_function/TEST1.PS1
src/test/traces_custom_function/out0.log.match
src/test/traces_custom_function/out1.log.match
src/test/traces_custom_function/traces_custom_function.c
src/test/traces_custom_function/traces_custom_function.vcxproj
src/test/traces_custom_function/traces_custom_function.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1104)

win: add tests for traces_custom_function

---

src/NVML.sln
src/common/util_windows.c
src/test/out_err/TEST0.PS1
src/test/out_err/out0.log.match
src/test/out_err/out_err.vcxproj
src/test/out_err/out_err.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1102)

win: add tests for out_err

---

src/NVML.sln
src/test/obj_pmalloc_basic/TEST0.PS1
src/test/obj_pmalloc_basic/obj_pmalloc_basic.c
src/test/obj_pmalloc_basic/obj_pmalloc_basic.vcxproj
src/test/obj_pmalloc_basic/obj_pmalloc_basic.vcxproj.filters
src/test/obj_pmalloc_mt/TEST0.PS1
src/test/obj_pmalloc_mt/obj_pmalloc_mt.vcxproj
src/test/obj_pmalloc_mt/obj_pmalloc_mt.vcxproj.filters
src/test/obj_pmalloc_oom_mt/TEST0.PS1
src/test/obj_pmalloc_oom_mt/obj_pmalloc_oom_mt.vcxproj
src/test/obj_pmalloc_oom_mt/obj_pmalloc_oom_mt.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1111)

win: tests obj_pmalloc_* windows port

---

src/NVML.sln
src/test/obj_tx_lock/TEST0.PS1
src/test/obj_tx_lock/obj_tx_lock.vcxproj
src/test/obj_tx_lock/obj_tx_lock.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1114)

win: port test obj_tx_lock

---

Makefile
README.md
utils/md2man.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1082)

doc: fix failing on missing pandoc

---

doc/librpmem.3.md
src/librpmem/librpmem.c
src/librpmem/rpmem_ssh.c
src/librpmem/rpmem_util.c
src/librpmem/rpmem_util.h
src/test/obj_basic_integration/Makefile.inc
src/test/obj_rpmem_basic_integration/TEST5
src/test/obj_rpmem_basic_integration/TEST6
src/test/obj_rpmem_basic_integration/TEST7
src/test/obj_rpmem_basic_integration/TEST8
src/test/obj_rpmem_basic_integration/node_2_out5.log.match
src/test/obj_rpmem_basic_integration/node_2_out6.log.match
src/test/obj_rpmem_basic_integration/node_2_out7.log.match
src/test/rpmem_obc/rpmem_obc_test.c
src/test/rpmem_obc/rpmem_obc_test_common.c
src/test/rpmem_obc_int/rpmem_obc_int.c
src/test/rpmemd_db/Makefile
src/test/rpmemd_obc/Makefile
src/test/rpmemd_obc/rpmemd_obc_test.c
src/test/rpmemd_obc/rpmemd_obc_test_common.c
src/test/rpmemd_obc/rpmemd_obc_test_common.h
src/test/unittest/unittest.sh
utils/docker/configure-tests.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1109)

rpmem: allow separate RPMEM_CMD for each remote node

---

src/tools/pmempool/common.c
src/tools/pmempool/common.h
src/tools/pmempool/info.c

Ref: pmem/issues#202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1089)

pmempool: validate replica number in info command

---

src/test/obj_heap_state/TEST0.PS1
src/test/obj_heap_state/TEST1.PS1
src/test/obj_heap_state/TEST2.PS1
src/test/obj_heap_state/obj_heap_state.vcxproj
src/test/obj_heap_state/obj_heap_state.vcxproj.filters
src/test/obj_heap_state/out0.log.match
src/test/obj_heap_state/out1.log.match
src/test/obj_heap_state/out2.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1119)

win: port test obj_heap_state

---

src/NVML.sln
src/test/obj_tx_strdup/TEST0.PS1
src/test/obj_tx_strdup/TEST1.PS1
src/test/obj_tx_strdup/obj_tx_strdup.vcxproj
src/test/obj_tx_strdup/obj_tx_strdup.vcxproj.filters
src/test/obj_tx_strdup/out0.log.match
src/test/obj_tx_strdup/out1.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1116)

win: port obj_tx_strdup test

---

src/test/ex_libpmemobj/TEST15
src/test/ex_libpmemobj/TEST16
src/test/ex_libpmemobj_cpp/TEST1
src/test/unittest/unittest.sh

Useful when running tests from cron.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1120)

test: skip ncurses tests when stdout is not a terminal

---

src/include/libpmemobj++/p.hpp

Remove an indefinite article: "a transactions" -> "transactions".
Plural "to be": "changes ... is made" -> "changes ... are made".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1121)

obj: minor typo fixes in comments

---

src/NVML.sln
src/test/obj_toid/TEST0.PS1
src/test/obj_toid/obj_toid.vcxproj
src/test/obj_toid/obj_toid.vcxproj.filters
src/test/obj_toid/out0.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1124)

win: add tests for obj_toid

---

src/NVML.sln
src/common/util.h
src/test/obj_tx_alloc/TEST0.PS1
src/test/obj_tx_alloc/TEST1.PS1
src/test/obj_tx_alloc/obj_tx_alloc.c
src/test/obj_tx_alloc/obj_tx_alloc.vcxproj
src/test/obj_tx_alloc/obj_tx_alloc.vcxproj.filters
src/test/obj_tx_alloc/out0.log.match
src/test/obj_tx_alloc/out1.log.match
src/test/obj_tx_free/TEST0.PS1
src/test/obj_tx_free/TEST1.PS1
src/test/obj_tx_free/obj_tx_free.vcxproj
src/test/obj_tx_free/obj_tx_free.vcxproj.filters
src/test/obj_tx_free/out0.log.match
src/test/obj_tx_free/out1.log.match
src/test/obj_tx_realloc/TEST0.PS1
src/test/obj_tx_realloc/TEST1.PS1
src/test/obj_tx_realloc/obj_tx_realloc.vcxproj
src/test/obj_tx_realloc/obj_tx_realloc.vcxproj.filters
src/test/obj_tx_realloc/out0.log.match
src/test/obj_tx_realloc/out1.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1117)

win: port obj_tx_alloc free and realloc tests

---

src/NVML.sln
src/test/obj_tx_locks_abort/TEST0.PS1
src/test/obj_tx_locks_abort/TEST1.PS1
src/test/obj_tx_locks_abort/TEST2.PS1
src/test/obj_tx_locks_abort/obj_tx_locks_abort.vcxproj
src/test/obj_tx_locks_abort/obj_tx_locks_abort.vcxproj.filters
src/test/obj_tx_locks_abort/out0.log.match
src/test/obj_tx_locks_abort/out1.log.match
src/test/obj_tx_locks_abort/out2.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1118)

win: port obj_tx_locks_abort

---

src/test/obj_many_size_allocs/TEST0.PS1
src/test/obj_many_size_allocs/TEST1.PS1
src/test/obj_many_size_allocs/TEST2.PS1
src/test/obj_many_size_allocs/TEST3.PS1
src/test/obj_many_size_allocs/obj_many_size_allocs.vcxproj
src/test/obj_many_size_allocs/obj_many_size_allocs.vcxproj.filters
src/test/obj_many_size_allocs/out0.log.match
src/test/obj_many_size_allocs/out1.log.match
src/test/obj_many_size_allocs/out2.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1125)

win: port test obj_many_size_allocs

---

doc/libpmem.3.md
doc/libpmemblk.3.md
doc/libpmemlog.3.md
doc/libpmemobj.3.md
doc/libpmempool.3.md
doc/librpmem.3.md
doc/libvmem.3.md
doc/libvmmalloc.3.md
doc/pmempool-check.1.md
doc/pmempool-convert.1.md
doc/pmempool-create.1.md
doc/pmempool-dump.1.md
doc/pmempool-info.1.md
doc/pmempool-rm.1.md
doc/pmempool.1.md
doc/rpmemd.1.md
src/examples/libvmem/manpage.c

... and update libvmem man page example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1131)

doc: fix man page formatting

---

src/NVML.sln
src/test/obj_tx_flow/TEST0.PS1
src/test/obj_tx_flow/obj_tx_flow.vcxproj
src/test/obj_tx_flow/obj_tx_flow.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1132)

win: port test obj_tx_flow

---

src/test/obj_out_of_memory/TEST0.PS1
src/test/obj_out_of_memory/TEST1.PS1
src/test/obj_out_of_memory/TEST2.PS1
src/test/obj_out_of_memory/obj_out_of_memory.vcxproj
src/test/obj_out_of_memory/obj_out_of_memory.vcxproj.filters
src/test/obj_out_of_memory/out0.log.match
src/test/obj_out_of_memory/out1.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1126)

win: port test obj_out_of_memory

---

src/NVML.sln
src/test/obj_recreate/TEST0.PS1
src/test/obj_recreate/TEST1.PS1
src/test/obj_recreate/obj_recreate.c
src/test/obj_recreate/obj_recreate.vcxproj
src/test/obj_recreate/obj_recreate.vcxproj.filters
src/test/unittest/ut_file.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1123)

win: add test for obj_recreate

---

src/tools/pmempool/info.c

Ref: pmem/issues#202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1135)

pmempool: add missing % to format string

---

src/test/obj_ctree/obj_ctree.c
src/test/obj_cuckoo/obj_cuckoo.c

obj_cuckoo and obj_ctree tests can be easily modified to not use
FUNC_MOCK macros but simply override Malloc with a pointer to custom
malloc function.
This would make it easier to port those tests to Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1139)

test: do not use FUNC_MOCK macros in some tests

---

src/test/win_mmap/win_mmap.c
src/windows/win_mmap.c

Handle len==0 case, as well as the situation when addr+len is beyond
the process address space.
Add debug traces to win_mmap.c
Ref: pmem/issues#182
Ref: pmem/issues#227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1137)

win: handle invalid 'len' in msync/munmap/mprotect

---

src/test/unittest/unittest.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1145)

win: remove unnecessary new line prints

---

src/include/libpmemobj++/utils.hpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1151)

doc: remove unncessary backticks

---

src/test/Makefile

Do not copy testconfig.sh to the sync dir.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1152)

test: fix 'make sync-remotes'

---

src/libpmemobj/lane.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1154)

obj: remove unnecessary assertion in lane_release

---

doc/libpmemblk.3.md
doc/libpmemlog.3.md
doc/libpmemobj.3.md
doc/libpmempool.3.md
doc/libvmem.3.md
doc/libvmmalloc.3.md
doc/pmempool-check.1.md
doc/pmempool-dump.1.md
doc/pmempool-info.1.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1157)

doc: remove trailing whitespace from man pages

---

src/tools/pmempool/info.c

Ref: pmem/issues#202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1150)

pmempool: validate parsing replica number

---

CONTRIBUTING.md
utils/check_whitespace

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1129)

common: add *.md extension to check_whitespace

---

src/NVML.sln
src/test/obj_ctree/TEST0.PS1
src/test/obj_ctree/obj_ctree.vcxproj
src/test/obj_ctree/obj_ctree.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1160)

win: port test obj_ctree

---

src/NVML.sln
src/test/obj_cuckoo/TEST0.PS1
src/test/obj_cuckoo/obj_cuckoo.vcxproj
src/test/obj_cuckoo/obj_cuckoo.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1158)

win: port test obj_cuckoo

---

src/common/util.c
src/common/valgrind_internal.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1162)

common: fix build with Valgrind DRD, but without other tools

---

src/libpmemobj/ctree.c
src/libpmemobj/cuckoo.c
src/libpmemobj/lane.c
src/libpmemobj/memops.c
src/libpmemobj/obj.c
src/test/obj_bucket/obj_bucket.c
src/test/set_funcs/set_funcs.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1148)

obj: defer allocation of global structures

---

src/NVML.sln
src/test/obj_realloc/TEST0.PS1
src/test/obj_realloc/TEST1.PS1
src/test/obj_realloc/obj_realloc.c
src/test/obj_realloc/obj_realloc.vcxproj
src/test/obj_realloc/obj_realloc.vcxproj.filters
src/test/obj_realloc/out0.log.match
src/test/obj_realloc/out1.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1140)

win: port test obj_realloc

---

src/libpmemobj/heap.c
src/test/obj_many_size_allocs/Makefile
src/test/obj_many_size_allocs/TEST0
src/test/obj_many_size_allocs/TEST0.PS1
src/test/obj_many_size_allocs/TEST1
src/test/obj_many_size_allocs/TEST1.PS1
src/test/obj_many_size_allocs/TEST2
src/test/obj_many_size_allocs/TEST2.PS1
src/test/obj_many_size_allocs/TEST3
src/test/obj_many_size_allocs/TEST3.PS1
src/test/obj_many_size_allocs/obj_many_size_allocs.c
src/test/obj_out_of_memory/out0.log.match
src/test/obj_out_of_memory/out1.log.match

Ref: pmem/issues/issues/220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1107)

obj: fix degrading runs for certain edge cases 

---

src/test/arch_flags/README
src/test/rpmemd_log/README
src/test/util_map_proc/README
src/test/vmmalloc_init/README

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1166)

win: update README for Linux specific tests

---

doc/libpmemobj.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1173)

doc: add missing asterisk to pmemobj_direct description

---

src/rpmem_common/rpmem_fip_common.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1176)

rpmem: fix setting errno in rpmem_fip_read_eq()

---

src/test/obj_constructor/memcheck1.log.match
src/test/pmem_valgr_simple/pmemcheck0.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1180)

test: update match files for Valgrind 3.11

---

src/common/uuid.c
src/common/uuid.h
src/librpmem/rpmem.c
src/librpmem/rpmem_cmd.c
src/librpmem/rpmem_fip.c
src/librpmem/rpmem_obc.c
src/librpmem/rpmem_ssh.c
src/rpmem_common/rpmem_common.c
src/rpmem_common/rpmem_common.h
src/rpmem_common/rpmem_fip_common.c
src/rpmem_common/rpmem_fip_common.h
src/test/rpmemd_log/rpmemd_log_test.c
src/tools/rpmemd/Makefile
src/tools/rpmemd/rpmemd.c
src/tools/rpmemd/rpmemd_fip.c
src/tools/rpmemd/rpmemd_log.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1169)

rpmem: add more logs to rpmemd and librpmem

---

appveyor.yml
src/NVML.sln
utils/sort_solution

this script sorts visual studio projects lists by a project GUID.
Keeping solution sorted by a random number (GUID is random) will cause
that a new project will be added in random place on a projects lists,
significantly reducing probability of merge conflict in case
when 2 commits adds new project to solution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1112)

win: add script to sort solutions files

---

src/rpmem_common/rpmem_common.c
src/rpmem_common/rpmem_common.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1179)

rpmem: add places for NULL-terminator

---

src/test/out_err/TEST0
src/test/out_err/TEST0.PS1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1182)

test: add debug requirement to out_err test scripts

---

src/NVML.sln

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1184)

win: fix duplicate projects in solution

---

src/test/obj_check/TEST0.PS1
src/test/obj_check/TEST1.PS1
src/test/obj_check/TEST2.PS1
src/test/obj_check/TEST3.PS1
src/test/obj_check/TEST4.PS1
src/test/obj_check/out0.log.match
src/test/obj_check/out1.log.match
src/test/obj_check/out2.log.match
src/test/obj_check/out3.log.match
src/test/obj_check/out4.log.match

add scrips and modify match files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1185)

win: obj_check add test scrips

---

src/test/obj_cpp_timed_mtx/obj_cpp_timed_mtx.cpp
src/test/obj_cpp_timed_mtx_posix/obj_cpp_timed_mtx_posix.cpp

Introduce a loop to remove a possible timeout race.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1195)

cpp: fix timed_mutex test

---

src/test/testconfig.ps1.example

Add "P" to MEM_FS_DIR_FORCE_PMEM
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1198)

win: fix important typo in testconfig.ps1.example

---

src/test/obj_check/TEST0.PS1
src/test/obj_check/TEST1.PS1
src/test/obj_check/TEST2.PS1
src/test/obj_check/TEST3.PS1
src/test/obj_check/TEST4.PS1
src/test/util_poolset_parse/TEST0.PS1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1204)

win: remove harcoded PMEM_IS_PMEM in PS1 tests

---

src/librpmem/rpmem.c
src/librpmem/rpmem_fip.c
src/rpmem_common/rpmem_common.c
src/tools/rpmemd/rpmemd_obc.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1174)

rpmem: add more logs

---

libpmempool/index.md
manpages/master/pmempool-sync.1.md
manpages/master/pmempool-transform.1.md
pmempool/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1194)

libpmempool: examples for transform

---

src/librpmem/rpmem_obc.c

Ref: pmem/issues#251
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1212)

rpmem: fix invalid log message

---

doc/librpmem.3.md
src/librpmem/rpmem.c
src/librpmem/rpmem_fip.c
src/librpmem/rpmem_obc.c
src/librpmem/rpmem_ssh.c
src/librpmem/rpmem_ssh.h
src/test/rpmem_basic/rpmem_basic.c
src/tools/rpmemd/rpmemd.c
src/tools/rpmemd/rpmemd_db.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1216)

rpmem: bug fixes

---

src/test/libpmempool_sync/TEST0
src/test/libpmempool_sync/TEST1
src/test/libpmempool_transform/TEST0
src/test/libpmempool_transform/TEST1

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1219)

pmempool: fixes incorrect paths to poolset files

---

src/librpmem/rpmem.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1222)

rpmem: fix wrong message in rpmem_open()

---

src/test/Makefile.inc

... and the root directory will not be copied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1223)

test: make sure variables are set

---

src/common/file_windows.c
src/windows/win_file.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1231)

win: fix deletion of temporary files

---

src/include/libpmemobj++/README.md

Refs: pmem/issues#270
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1237)

doc: add C++ compiler version notice

---

.gitignore
src/benchmarks/map_bench.c
src/benchmarks/perf.cfg
src/benchmarks/pmembench_map.cfg
src/examples/libpmemobj/.gitignore
src/examples/libpmemobj/map/Makefile
src/examples/libpmemobj/map/README
src/examples/libpmemobj/map/kv_server.c
src/examples/libpmemobj/map/map_btree.c
src/examples/libpmemobj/map/map_btree.h
src/examples/libpmemobj/map/map_ctree.c
src/examples/libpmemobj/map/map_ctree.h
src/examples/libpmemobj/map/map_hashmap_atomic.c
src/examples/libpmemobj/map/map_hashmap_atomic.h
src/examples/libpmemobj/map/map_hashmap_tx.c
src/examples/libpmemobj/map/map_hashmap_tx.h
src/examples/libpmemobj/map/map_rbtree.c
src/examples/libpmemobj/map/map_rbtree.h
src/examples/libpmemobj/map/map_rtree.c
src/examples/libpmemobj/map/map_rtree.h
src/examples/libpmemobj/map/map_skiplist.c
src/examples/libpmemobj/map/map_skiplist.h
src/examples/libpmemobj/map/mapcli.c
src/examples/libpmemobj/tree_map/Makefile
src/examples/libpmemobj/tree_map/btree_map.c
src/examples/libpmemobj/tree_map/rtree_map.c
src/examples/libpmemobj/tree_map/rtree_map.h
utils/cstyle

Please pull Radix Tree example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1228)

Radix Tree

---

src/test/unittest/unittest.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1236)

win: fix-write-host-order-in-unittest

---

Makefile
doc/Makefile
utils/check-doc.sh

Allow generated docs to be modified only by nvml-bot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1241)

doc: add doc modification check

---

.mailmap

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1244)

common: .mailmap update

---

doc/pmempool-create.1.md
src/test/pmempool_check/out5.log.match
src/tools/pmempool/create.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1251)

pmempool: fixes for create command

---

doc/libpmemobj.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1254)

doc: add remote replicas to libpmemobj manual

---

src/test/blk_pool/TEST15w.PS1
src/test/blk_pool/TEST16.PS1
src/test/blk_pool/TEST29.PS1
src/test/blk_rw/TEST4.PS1
src/test/log_recovery/TEST0.PS1
src/test/log_recovery/TEST1.PS1
src/test/unittest/unittest.ps1
src/test/win_getopt/TEST0.PS1
src/test/win_getopt/TEST1.PS1
src/test/win_getopt/win_getopt.vcxproj
src/test/win_getopt/win_getopt.vcxproj.filters
src/test/win_mmap/TEST0.PS1

Note: uncovered two tests in blk_rw that do not pass check_pool
so markes as XXX so as to not hold up this patch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1240)

win: start using check_pool (and other misc cleanup)

---

appveyor.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1272)

win: appveyor should fail on cstyle

---

src/test/Makefile
src/test/rpmem_basic/Makefile
src/test/rpmem_fip/Makefile
utils/docker/configure-tests.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1270)

rpmem: fix copying files to remote nodes

---

src/common/set.c
src/common/set.h
src/libpmemblk/blk.c
src/libpmemlog/log.c
src/libpmemobj/obj.c
src/test/util_poolset/util_poolset.c
src/tools/rpmemd/rpmemd_db.c

Ref: pmem/issues#289
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1268)

common: check if replicas are supported

---

src/libpmemobj/heap.c

Helgrind is currently complaining about races between
checking if a block is allocated and various other
operations on runs. Because this code is debug-only
the easy solution is to simply add a lock.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1279)

obj: protect heap_block_is_allocated with a run lock

---

src/tools/pmempool/common.c

Read whole input line if an user provides more than one character as an answer
to the question.
fixes pmem/issues#267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1275)

pmempool: read whole input line

---

src/include/libpmemobj++/make_persistent.hpp
src/include/libpmemobj++/pool.hpp

cpp bindings should work without platform.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1262)

win: fix cpp bindings on windows

---

src/common/set.c
src/common/set.h
src/libpmemblk/blk.c
src/libpmemlog/log.c
src/libpmemobj/obj.c
src/test/util_poolset/util_poolset.c
src/tools/rpmemd/rpmemd_db.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1286)

common: minor fixes

---

src/windows/include/platform.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1288)

win: prevent compilation for 32-bit platforms

---

Makefile
doc/Makefile
utils/check-doc.sh
utils/docker/prepare-for-build.sh

Move generated ddocumentation check to travis pull requests only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1285)

doc: move the doc check to travis

---

src/test/log_include/TEST0
src/test/win_getopt/TEST0
src/test/win_getopt/stderr1.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1289)

test: fix windows tests on linux

---

src/libpmempool/replica.c
src/test/pmempool_sync_remote/TEST0
src/test/pmempool_sync_remote/TEST2
src/test/pmempool_sync_remote/TEST3
src/test/pmempool_sync_remote/TEST4

Fix SEGV for healthy pool with remote replica and add tests to cover
this issue.
Ref: pmem/issues#294
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1295)

pmempool: fix sync for healthy pool

---

.travis.yml

```
As we have 6 jobs and 5 concurrent threads in Travis our job schedule
is presented in the figure below:
#1 ======
#2 ======
#3 ========================
#4 ========================
#5       ========================
#6       ======
a new order will look like this:
#3 ========================
#4 ========================
#5 ========================
#1 ======
#2       ======
#6             ======
what give us '======' improvement (at the time of this commit it's ~13 min)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1304)

utils: change order of jobs in Travis

---

utils/cstyle

One example:
if (x < -128)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1293)

cstyle: Allow more cases of unary minus operator

---

src/include/libpmemobj++/README.md

Ref: pmem/issues#297
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1303)

doc: doc update

---

utils/make-pkg-config.sh

Mention dependencies for statically linked libraries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1312)

pkg: add Libs.private info to .pc files

---

src/test/README
src/test/RUNTESTS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1314)

test: fix 'make check TEST_TYPE=all'

---

README.md

Ref: pmem/issues#296
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1307)

doc: clarify EXPERIMENTAL flag in README file

---

src/common/set.c
src/tools/pmempool/common.c
src/tools/pmempool/rm.c

Ref: pmem/issues#264
Ref: pmem/issues#266
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1306)

pmempool: rm command bugs fixes

---

src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1311)

test: redirect all error messages to stderr

---

src/test/blk_rw_mt/blk_rw_mt.vcxproj
src/test/obj_realloc/obj_realloc.vcxproj
src/test/obj_recovery/obj_recovery.vcxproj
src/test/obj_tx_mt/obj_tx_mt.vcxproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1313)

win: fix linker warnings in release configuration

---

src/benchmarks/Makefile
src/benchmarks/pmembench_obj_persist.cfg
src/benchmarks/pmembench_rpmem.cfg
src/benchmarks/pmemobj_persist.c
src/benchmarks/rpmem_persist.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1315)

pmembench: add pmemobj_persist and rpmem_persist benchmarks

---

doc/libpmemobj.3.md
src/examples/libpmemobj/pmemblk/obj_pmemblk.c
src/examples/libpmemobj/pmemlog/obj_pmemlog.c
src/examples/libpmemobj/pmemlog/obj_pmemlog_macros.c
src/examples/libpmemobj/pmemlog/obj_pmemlog_simple.c
src/examples/libpmemobj/pmemobjfs/pmemobjfs.c
src/include/libpmemobj++/mutex.hpp
src/include/libpmemobj++/shared_mutex.hpp
src/include/libpmemobj++/transaction.hpp
src/include/libpmemobj/tx.h
src/include/libpmemobj/tx_base.h
src/libpmemobj/tx.c
src/test/Makefile
src/test/obj_basic_integration/obj_basic_integration.c
src/test/obj_recovery/obj_recovery.c
src/test/obj_tx_callbacks/.gitignore
src/test/obj_tx_callbacks/Makefile
src/test/obj_tx_callbacks/TEST0
src/test/obj_tx_callbacks/obj_tx_callbacks.c
src/test/obj_tx_callbacks/out0.log.match
src/test/obj_tx_flow/obj_tx_flow.c
src/test/obj_tx_lock/obj_tx_lock.c
src/test/obj_tx_locks/obj_tx_locks.c
src/test/obj_tx_locks_abort/obj_tx_locks_abort.c
src/test/tools/pmemobjcli/pmemobjcli.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1177)

[new API, for 1.3] obj: transaction stage callbacks

---

doc/README

Ref: pmem/issues#305
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1322)

doc: update rpmem paths in doc/README

---

doc/librpmem.3.md
src/common.inc
src/common/set.c
src/common/util.h
src/examples/librpmem/Makefile
src/examples/librpmem/basic.c
src/libpmempool/replica.c
src/libpmempool/sync.c
src/librpmem/Makefile
src/librpmem/librpmem.c
src/librpmem/rpmem.c
src/librpmem/rpmem_fip.c
src/test/pmempool_sync_remote/common.sh
src/test/rpmem_basic/Makefile
src/test/rpmem_basic/rpmem_basic.c
src/test/unittest/unittest.sh
src/tools/pmempool/synchronize.c
src/tools/rpmemd/Makefile
src/tools/rpmemd/rpmemd.c
utils/docker/run-build-package.sh
utils/docker/run-build.sh

Ref: pmem/issues#233
Ref: pmem/issues#301
Ref: pmem/issues#303
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1317)

rpmem fixes

---

src/libpmemobj/palloc.c
src/test/obj_pmalloc_mt/TEST1

ref: pmem/issues#287
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1320)

obj: fix a race palloc debug check

---

src/examples/ex_common.h
src/examples/libpmemblk/assetdb/asset_checkin.c
src/examples/libpmemblk/assetdb/asset_checkin.vcxproj
src/examples/libpmemblk/assetdb/asset_checkout.c
src/examples/libpmemblk/assetdb/asset_checkout.vcxproj
src/examples/libpmemblk/assetdb/asset_list.c
src/examples/libpmemblk/assetdb/asset_list.vcxproj
src/examples/libpmemblk/assetdb/asset_load.c
src/examples/libpmemblk/assetdb/asset_load.vcxproj
src/examples/libpmemlog/logfile/addlog.c
src/examples/libpmemlog/logfile/addlog.vcxproj
src/examples/libpmemlog/logfile/printlog.c
src/examples/libpmemlog/logfile/printlog.vcxproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1330)

Update log and blk examples to use ex_common.h

---

src/benchmarks/pmembench.c
src/benchmarks/rpmem_persist.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1327)

benchmark: add missing new line characters

---

src/benchmarks/pmemobj_persist.c
src/benchmarks/rpmem_persist.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1333)

benchmark: make sure pool's size is aligned

---

src/examples/librpmem/basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1336)

examples: fix memory leak

---

src/common/set.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1337)

common: fix possible NULL pointer dereference

---

src/libpmempool/sync.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1338)

libpmempool: fix copy_data_to_broken_parts()

---

src/examples/libpmemobj/pi.c

Fix possible NULL pointer dereference
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1340)

examples: pi: fix NULL pointer dereference

---

src/benchmarks/rpmem_persist.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1339)

benchmark: fix error handling in rpmem_persist

---

src/common/uuid.h
src/libpmempool/check_pool_hdr.c
src/libpmempool/check_util.h
src/libpmempool/pool.c
src/libpmempool/replica.c
src/test/pmempool_check/TEST4
src/test/pmempool_check/TEST4.PS1
src/test/pmempool_check/TEST5
src/test/pmempool_check/TEST5w.PS1
src/test/pmempool_check/TEST7
src/test/pmempool_check/TEST7.PS1
src/test/pmempool_check/TEST8
src/test/pmempool_check/TEST8w.PS1
src/test/pmempool_check/out0.log.match
src/test/pmempool_check/out1.log.match
src/test/pmempool_check/out3.log.match
src/test/pmempool_check/out4.log.match
src/test/pmempool_check/out5.log.match
src/test/pmempool_check/out6.log.match
src/test/pmempool_check/out7.log.match
src/test/pmempool_check/out8.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1278)

libpmempool: fix checking pool_hdr.uuid

---

src/tools/pmempool/README
src/tools/pmempool/convert.c

ref: pmem/issues#300
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1347)

pmempool: add missing spaces and add convert to README

---

src/libpmemobj/heap.c

ref: pmem/issues#311
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1345)

obj: remove unnecessary calculations during foreach

---

src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1353)

test: fix copy_files_from_node()

---

src/common/out.h
src/examples/libpmemobj/pmemlog/obj_pmemlog.c
src/examples/libpmemobj/pmemlog/obj_pmemlog_minimal.c
src/libpmempool/check_btt_info.c
src/libpmempool/check_util.c
src/libpmempool/pool.c
src/tools/pmempool/common.c
src/tools/pmempool/dump.c
src/tools/pmempool/pmempool.c
src/tools/pmempool/rm.c

Ref: pmem/issues#306
Ref: pmem/issues#308
Ref: pmem/issues#312
Ref: pmem/issues#316
Ref: pmem/issues#315
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1355)

minor fixes

---

doc/libpmemobj.3.md
src/test/obj_pool/TEST14
src/test/obj_pool/TEST6
src/tools/pmempool/create.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1354)

common: be more precise about length of layout

---

src/libpmempool/check_btt_info.c
src/libpmempool/check_pool_hdr.c
src/libpmempool/pool.c
src/libpmempool/replica.c
src/libpmempool/sync.c
src/libpmempool/transform.c
src/test/pmempool_check/out4.log.match
src/test/pmempool_check/out5.log.match
src/test/pmempool_check/out7.log.match
src/test/pmempool_check/out8.log.match
src/test/pmempool_transform/out3.log.match
src/test/pmempool_transform/out6.log.match

Ref: pmem/issues#242
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1350)

libpmempool: typo and message formatting

---

src/libpmempool/check_pool_hdr.c
src/test/pmempool_check/TEST10
src/test/pmempool_check/TEST10.PS1
src/test/pmempool_check/out10.log.match

Fix checking multiple replicas and add unittest testing it.
Ref: pmem/issues#245
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1349)

libpmempool: fix multiple replicas checking

---

utils/check_license/check-headers.sh

Only modified files are checked by default.
It speeds up 'make check-license'.
In order to check all files the '-a' option
has to be provided.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1358)

utils: check license in modified files

---

src/benchmarks/pmem_memset.c
src/benchmarks/pmemobj_persist.c
src/benchmarks/rpmem_persist.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1356)

benchmarks: fix or remove unreachable code

---

src/tools/pmempool/dump.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1360)

pmempool: remove unreachable code

---

src/benchmarks/pmembench.c

Print units along with the result header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1361)

bench: add units to benchmark results

---

src/benchmarks/pmemobj_persist.c

Remove dead code that was accidentally left in a recent commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1362)

benchmark: remove dead code

---

src/test/pmempool_check/TEST10
src/test/pmempool_check/TEST10.PS1
src/test/pmempool_check/TEST5

Ref: pmem/issues#317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1364)

test: fix pmempool test output

---

utils/check_license/check-headers.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1368)

utils: skip checking non-existing files

---

src/tools/pmempool/create.c

Ref: pmem/issues#319
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1369)

pmempool: fix error message

---

utils/check-doc.sh
utils/docker/build.sh

Forward some Travis related variables to docker. Fail build when preparing
to run tests and performing other checks (generated docs for example).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1371)

travis: forward variables and fix script

---

doc/libpmemobj.3.md
src/include/libpmemobj/tx.h
src/include/libpmemobj/tx_base.h
src/libpmemobj/ctree.c
src/libpmemobj/ctree.h
src/libpmemobj/libpmemobj.def
src/libpmemobj/libpmemobj.map
src/libpmemobj/tx.c
src/test/obj_basic_integration/obj_basic_integration.c
src/test/obj_persist_count/out0.log.match
src/test/obj_persist_count/out1.log.match
src/test/obj_tx_add_range/TEST1
src/test/obj_tx_add_range/obj_tx_add_range.c
src/test/obj_tx_add_range/pmemcheck1.log.match
src/test/obj_tx_add_range_direct/TEST1.PS1
src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c
src/test/obj_tx_add_range_direct/pmemcheck1.log.match
src/test/obj_tx_alloc/TEST1.PS1
src/test/obj_tx_alloc/obj_tx_alloc.c
src/test/obj_tx_alloc/pmemcheck1.log.match
src/test/scope/out4.log.match

... with PMEMOBJ_FLAG_ZERO and PMEMOBJ_FLAG_NO_FLUSH.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1178)

[new API] obj: add pmemobj_tx_xalloc, pmemobj_tx_xadd_range and pmemobj_tx_xadd_range_direct

---

src/libpmempool/replica.c

Ref: pmem/issues#284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1380)

libpmempool: cleanup after failed transformation

---

utils/check-doc.sh

The TRAVIS_COMMIT_RANGE supplied by travis might consist of
commits outside of the pull request when the branch is out of date.
This might cause the check to fail, this change should fix this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1379)

doc: modify check on travis

---

src/test/obj_heap/obj_heap.c
src/test/obj_list_recovery/TEST0.PS1
src/test/obj_list_recovery/TEST1.PS1
src/test/obj_list_recovery/TEST2.PS1
src/test/obj_pmalloc_basic/obj_pmalloc_basic.c
src/test/obj_recovery/TEST3.PS1
src/test/unittest/unittest.ps1
src/test/win_mmap/win_mmap.c
src/windows/win_mmap.c
utils/cstyle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1378)

win: duplicate file handles in mmap() #2

---

src/libpmempool/pool.c

pmempool used stat() to get the backing file's size, but that doesn't work is the backing file is a raw block device. Detect if this is the case, and use an ioctl to get the size if so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1351)

Allow pmempool to be run against block devices

---

src/tools/pmempool/README

Ref: pmem/issues#300
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1385)

pmempool: add missing convert reference in README

---

src/test/obj_pool/TEST14
src/test/obj_pool/TEST6

Ref: pmem/issues#326
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1383)

test: obj_pool: redirect error message

---

src/test/obj_convert/TEST1
src/test/obj_convert/out1.log.match
src/tools/pmempool/convert.c

ref: pmem/issues#298
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1386)

pmempool: disallow convert on part files

---

src/common/file.c

found by static analysis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1389)

common: fix potential buffer overflow in dax size query

---

doc/librpmem.3.md
src/common/set.c
src/common/set.h
src/examples/librpmem/basic.c
src/include/librpmem.h
src/librpmem/rpmem.c
src/librpmem/rpmem_ssh.c
src/librpmem/rpmem_ssh.h
src/test/rpmem_basic/TEST6
src/test/rpmem_basic/node_1_out6.log.match
src/test/rpmem_basic/rpmem_basic.c
src/test/rpmemd_db/TEST0
src/test/rpmemd_db/TEST1
src/test/rpmemd_db/err1.log.match
src/test/rpmemd_db/out0.log.match
src/test/rpmemd_db/out1.log.match
src/test/rpmemd_db/rpmemd0.log.match
src/test/rpmemd_db/rpmemd1.log.match
src/test/rpmemd_db/rpmemd_db_test.c
src/test/rpmemd_db/trace0.log.match
src/test/rpmemd_db/trace1.log.match
src/tools/pmempool/rm.c
src/tools/rpmemd/rpmemd.c
src/tools/rpmemd/rpmemd_config.c
src/tools/rpmemd/rpmemd_config.h
src/tools/rpmemd/rpmemd_db.c
src/tools/rpmemd/rpmemd_db.h

Ref: pmem/issues#323
Ref: pmem/issues#293
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1387)

fix rpmem issues

---

src/tools/pmempool/common.c
src/tools/pmempool/common.h
src/tools/pmempool/info.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1397)

pmempool: remove superfluous field

---

doc/libpmempool.3.md
doc/pmempool-sync.1.md
src/libpmempool/replica.c
src/libpmempool/replica.h
src/libpmempool/sync.c
src/libpmempool/transform.c
src/test/pmempool_sync/TEST10
src/test/pmempool_sync/TEST8
src/test/pmempool_sync/TEST9
src/test/pmempool_sync/out10.log.match
src/test/pmempool_sync/out8.log.match
src/test/pmempool_sync/out9.log.match

Ref. pmem/issues#302
Ref. pmem/issues#304
+ test for cycle of healthy replicas
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1359)

pmempool: fixes issues in sync

---

src/libpmempool/check_pool_hdr.c
src/test/pmempool_check/TEST13
src/test/pmempool_check/out13.log.match

Ref: pmem/issues#332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1401)

pmempool: don't call msync directly from pmempool check

---

src/common/file.c

ref: pmem/issues#334
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1402)

common: fix typos in open call error handling

---

src/libpmemobj/heap.c

During pmalloc that retrieves a chunk from a used runs list it acquires locks in this order:
bucket->lock(), memblock->lock(), memblock->unlock, bucket->unlock()
and during pfree we lock in this order:
memblock->lock(), bucket->lock(), bucket->unlock(),  memblock->unlock()
This can cause a deadlock in some fringe cases.
Found by helgrind.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1408)

obj: fix potential lock ordering issue in pmalloc

---

src/common/set.c
src/test/obj_basic_integration/obj_basic_integration.c

ref: pmem/issues#335
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1409)

common: use existing file descriptor for dax part mmap

---

src/examples/libpmemobj/hashmap/hashmap_atomic.c
src/examples/libpmemobj/hashmap/hashmap_tx.c

Artificially limiting them can give really bad distribution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1412)

examples: fix hash function coefficients

---

src/benchmarks/Makefile
src/examples/Makefile.inc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1413)

benchmarks/examples: add Makefiles as dependencies

---

src/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1418)

common: add missing directories to cscope target

---

src/test/obj_convert/TEST3
src/test/obj_convert/TEST4
src/test/obj_convert/obj_convert.c
src/tools/pmempool/common.c
src/tools/pmempool/common.h
src/tools/pmempool/convert.c
src/tools/pmempool/convert.h
src/tools/pmempool/convert_obj_v1_v2.c

ref: pmem/issues#336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1406)

pmempool: add poolset support in convert

---

src/test/pmempool_sync/TEST8

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1420)

test: fixed test for pmempool sync

---

doc/libpmempool.3.md
doc/pmempool-check.1.md
src/common/set.c
src/common/set.h
src/libpmempool/check_pool_hdr.c
src/libpmempool/check_write.c
src/libpmempool/pool.c
src/libpmempool/pool.h
src/libpmempool/replica.c
src/tools/pmempool/convert.c

Ref: pmem/issues#331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1398)

pmempool: set proper flags and mode for check mmap

---

src/libpmempool/pool.c
src/test/pmempool_check/TEST14
src/test/pmempool_check/out14.log.match

Ref: pmem/issues#331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1425)

pmempool: use shared read-only mappings for parsing

---

src/test/pmempool_info/TEST18
src/test/pmempool_info/out18.log.match
src/tools/pmempool/common.c

ref: pmem/issues#345
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1427)

pmempool: use shared read-only mappings in param parse

---

src/libpmempool/check_backup.c
src/libpmempool/check_util.c
src/libpmempool/pool.c
src/libpmempool/pool.h
src/test/libpmempool_backup/TEST6
src/test/libpmempool_backup/TEST6.PS1
src/test/libpmempool_backup/TEST7
src/test/libpmempool_backup/TEST7.PS1
src/test/libpmempool_backup/out4.log.match
src/test/libpmempool_backup/out6.log.match
src/test/libpmempool_backup/out7.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1422)

libpmempool: allow backup to existing location

---

src/libpmempool/pool.c
src/libpmempool/transform.c
src/librpmem/rpmem.c
src/tools/pmempool/convert.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1430)

common: important fixes

---

src/include/libpmemobj++/detail/common.hpp
src/libpmemobj/obj.c
src/libpmemobj/tx.c
src/libpmemobj/tx.h

Fix scaling of detail::conditional_add_to_tx.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1431)

Fix cpp scaling

---

src/libpmempool/check_backup.c

Make sure array's index is in bounds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1432)

pmempool: check array's index

---

src/windows/include/platform.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1437)

win: remove duplicate include

---

src/libpmempool/replica.c
src/libpmempool/transform.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1441)

pmempool: fix unreachable code

---

doc/libpmemobj.3.md

.. performed by pmemobj_tx_process(). Also clarify that pmemobj_tx_end
can be called from TX_STAGE_NONE.
Ref: pmem/issues#291
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1434)

obj: clarify tx stage transitions

---

doc/libpmem.3.md
src/libpmem/pmem.c
src/test/pmem_map/TEST2
src/test/pmem_map/out2.log.match

ref: pmem/issues#350
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1436)

pmem: fix pmem_map regression on devdax /w zero size

---

src/libpmempool/sync.c
src/test/pmempool_sync/TEST11
src/test/pmempool_sync/TEST11w.PS1
src/test/pmempool_sync/out11.log.match
src/test/pmempool_sync/out11w.log.match

Ref. pmem/issues#344
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1438)

pmempool: sync: fix reusing uuids

---

src/libpmempool/sync.c

Ref. pmem/issues#353
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1452)

pmempool: fix granting permissions

---

src/windows/include/sys/queue.h
utils/check_whitespace

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1454)

win: replace sys/queue.h with version released under 3-clause BSD license

---

src/libpmempool/check_btt_info.c
src/libpmempool/check_btt_map_flog.c
src/libpmempool/check_log_blk.c
src/libpmempool/check_pool_hdr.c
src/libpmempool/check_write.c

Make sure arrays' indexes are in bounds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1450)

pmempool: check arrays' indexes

---

src/tools/pmempool/info.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1460)

pmempool: do not call mprotect for remote replicas

---

src/Makefile
src/examples/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1463)

common: remove remaining temporary files on make clean/clobber

---

src/libpmempool/check_backup.c
src/test/libpmempool_backup/out6.log.match
src/test/libpmempool_backup/out7.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1459)

libpmempool: fix typo in check backup

---

src/libpmempool/transform.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1462)

pmempool: minor refactoring

---

src/tools/pmempool/common.c

Ref: pmem/issues#338
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1464)

pmempool: fix typo

---

src/common/set.c
src/common/util.c
src/test/obj_heap_interrupt/TEST0
src/test/obj_recovery/TEST0
src/test/obj_recovery/TEST1
src/test/obj_recovery/TEST2
src/test/obj_recovery/TEST3
src/test/obj_recovery/TEST4
src/test/obj_recovery/TEST5
src/test/obj_recovery/TEST6
src/test/obj_recovery/TEST7
src/test/obj_recovery/TEST8
src/test/obj_tx_invalid/TEST0

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1465)

Address Sanitizer fixes

---

src/common/util_linux.c
src/libpmempool/transform.c

Ref: pmem/issues#355
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1461)

pmempool: fix incorrect errno after transform

---

src/test/obj_convert/TEST11
src/test/obj_convert/TEST12
src/test/obj_convert/TEST13
src/test/obj_convert/TEST14
src/test/obj_convert/TEST15
src/test/obj_convert/TEST16
src/test/obj_convert/TEST17
src/test/obj_convert/TEST18
src/test/obj_convert/TEST19
src/test/obj_convert/common.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1467)

obj: split convert test

---

doc/cppobj.Doxyfile
doc/libpmem.3.md
doc/libpmemblk.3.md
doc/libpmemlog.3.md
doc/libpmemobj.3.md
doc/libpmempool.3.md
doc/librpmem.3.md
doc/libvmem.3.md
doc/libvmmalloc.3.md
doc/pmempool-check.1.md
doc/pmempool-convert.1.md
doc/pmempool-create.1.md
doc/pmempool-dump.1.md
doc/pmempool-info.1.md
doc/pmempool-rm.1.md
doc/pmempool-sync.1.md
doc/pmempool-transform.1.md
doc/pmempool.1.md
doc/rpmemd.1.md
src/include/libpmemobj/base.h
utils/build-rpm.sh

Bumps up API version numbers and man page revisions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1468)

common: prepare for 1.2 release

---

src/Makefile
src/Makefile.inc
src/benchmarks/Makefile
src/common.inc
src/examples/Makefile.inc
src/rpmem_common/Makefile
src/test/Makefile.inc
src/test/unittest/Makefile
src/tools/Makefile.inc

1) Don't create htmp/hpptmp files when CSTYLEON=0
2) Create missing directories for htmp/hpptmp files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1472)

common: fix 2 small CSTYLEON issues

---

doc/libpmem.3.md
doc/libpmemblk.3.md
doc/libpmemlog.3.md
doc/libpmemobj.3.md
doc/libpmempool.3.md
doc/pmempool-check.1.md

Ref: pmem/issues#359
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1476)

doc: fix devdax documentation

---

src/test/blk_rw_mt/TEST0.PS1
src/test/blk_rw_mt/TEST1.PS1
src/test/blk_rw_mt/TEST2.PS1
src/test/pmem_is_pmem/TEST0.PS1
src/test/pmem_is_pmem/TEST1.PS1
src/test/pmem_is_pmem/TEST2.PS1
src/test/pmem_is_pmem/TEST3.PS1
src/test/pmem_is_pmem/TEST4.PS1
src/test/pmem_is_pmem/TEST5.PS1
src/test/win_common/TEST0.PS1
src/test/win_lists/TEST1.PS1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1482)

win: XXX cleanup

---

src/examples/libpmem/full_copy.vcxproj
src/examples/libpmem/manpage.vcxproj
src/examples/libpmem/simple_copy.vcxproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1466)

win: upgrade target platform version in libpmem examples

---

src/test/pmempool_create/TEST4w.PS1
src/test/unittest/unittest.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1478)

win: fix check_mode api

---

src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1487)

tests: append pkgconfig suffix to all provided paths

---

src/include/libpmemobj++/detail/common.hpp
src/include/libpmemobj++/transaction.hpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1458)

cpp: fix ignore return value and constexpr

---

src/test/blk_rw/TEST0.PS1
src/test/blk_rw/TEST1.PS1
src/test/blk_rw/TEST2.PS1
src/test/blk_rw/TEST3.PS1
src/test/blk_rw/TEST4.PS1
src/test/blk_rw/TEST5.PS1
src/test/blk_rw/TEST6.PS1
src/test/blk_rw/TEST7.PS1
src/test/blk_rw/TEST8w.PS1
src/test/blk_rw/TEST9w.PS1
src/test/obj_out_of_memory/TEST0.PS1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1490)

win: add missing PASS in PS1 scripts

---

src/common/set.c
src/test/obj_rpmem_basic_integration/TEST12
src/test/rpmem_basic/TEST7
src/test/rpmem_basic/rpmem_basic.c
src/test/testconfig.sh.example
src/test/tools/Makefile
src/test/tools/pmemdetect/Makefile
src/test/tools/pmemdetect/README
src/test/tools/pmemdetect/pmemdetect.c
src/test/unittest/unittest.sh

Ref: pmem/issues#356
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1488)

obj: fix using device dax with remote replication

---

src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1496)

test: fix absolute path check

---

src/windows/win_mmap.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1494)

win: fix file handle leak in mmap_fini()

---

src/test/unittest/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1512)

test: don't relink tests each time when CSTYLEON=0

---

cpp_obj/index.md
index.md
libpmem/index.md
libpmemblk/index.md
libpmemlog/index.md
libpmemobj/index.md
libpmempool/index.md
librpmem/index.md
libvmem/index.md
libvmmalloc/index.md
manpages/v1.2/libpmem.3.md
manpages/v1.2/libpmemblk.3.md
manpages/v1.2/libpmemlog.3.md
manpages/v1.2/libpmemobj.3.md
manpages/v1.2/libpmempool.3.md
manpages/v1.2/librpmem.3.md
manpages/v1.2/libvmem.3.md
manpages/v1.2/libvmmalloc.3.md
manpages/v1.2/pmempool-check.1.md
manpages/v1.2/pmempool-convert.1.md
manpages/v1.2/pmempool-create.1.md
manpages/v1.2/pmempool-dump.1.md
manpages/v1.2/pmempool-info.1.md
manpages/v1.2/pmempool-rm.1.md
manpages/v1.2/pmempool-sync.1.md
manpages/v1.2/pmempool-transform.1.md
manpages/v1.2/pmempool.1.md
manpages/v1.2/rpmemd.1.md
pmempool/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1520)

doc: update C++ bindings documentation

---

CODING_STYLE.md
CONTRIBUTING.md
README.md
doc/README

- Update on how to document NVML version when reporting a bug.
- Add information about NVML for Windows status.
- Add information about libpmempool library.
- Add information about librpmem library.
- Update on OS versions used by Travis.
- Add information on how to build and how to run NVML tests on Windows.
- Add instructions for Windows contributors.
Ref: pmem/issues#70
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1521)

doc: update documentation

---

src/test/pmempool_check/out13.log.match

Ref: pmem/issues#369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1528)

test: fix dax match file

---

src/test/vmmalloc_fork/vmmalloc_fork.c

The vmmalloc_fork test spawns multiple threads and forks multiple
child processess, which may cause a deadlocks if a lock is held in
the spawned thread.
Ref: pmem/issues#365
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1505)

vmmalloc: fix vmmalloc_fork test

---

src/test/obj_basic_integration/TEST10
src/test/unittest/unittest.sh

Ref: pmem/issues#372
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1529)

test: add require_command()

---

src/test/unittest/unittest.sh
src/test/util_poolset/TEST0
src/test/util_poolset/TEST1
src/test/util_poolset/grep0.log.match
src/test/util_poolset/grep1.log.match
src/test/util_poolset/out0.log.match
src/test/util_poolset/out1.log.match

... and util_poolset test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1515)

test: fix create_poolset function

---

src/benchmarks/rpmem_persist.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1504)

benchmarks: check return value of rpmem_persist

---

src/test/Makefile.inc
utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1501)

test: handle BUILD_STATIC_  in remote tests

---

src/librpmem/rpmem_fip.c
src/rpmem_common/rpmem_common.c

Ref: pmem/issues#361
Ref: pmem/issues#362
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1513)

rpmem: fix return value of rpmem_persist

---

src/benchmarks/map_bench.c
src/benchmarks/obj_locks.c
src/benchmarks/pmembench.c
src/benchmarks/pmemobj_gen.c
src/libpmemobj/obj.c
src/libpmempool/pool.c
src/libvmmalloc/libvmmalloc.c
src/tools/pmempool/create.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1532)

common: various fixes

---

src/tools/pmempool/pmempool.c

Ref: pmem/issues#366
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1514)

pmempool: fix exit code

---

src/benchmarks/pmembench.c
src/common/mmap_linux.c
src/common/set.c
src/libpmem/pmem.c
src/librpmem/rpmem_ssh.c
src/librpmem/rpmem_ssh.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1526)

common: various fixes #2

---

src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1534)

test: dump only logs of current unit test

---

src/test/blk_pool_lock/blk_pool_lock.c
src/test/blk_pool_lock/blk_pool_lock.vcxproj
src/test/log_pool_lock/log_pool_lock.c
src/test/log_pool_lock/log_pool_lock.vcxproj
src/test/obj_pool_lock/obj_pool_lock.c
src/test/obj_pool_lock/obj_pool_lock.vcxproj
src/test/unittest/unittest.h
src/test/unittest/ut.c
src/test/util_poolset_parse/TEST0.PS1
src/test/util_poolset_parse/TEST1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1477)

win: fix tests for nondebug config

---

src/jemalloc/msvc/jemalloc.vcxproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1537)

win: fix-jemalloc-database-manager-mismatch

---

src/libpmempool/replica.c
src/test/libpmempool_sync/TEST0
src/test/libpmempool_sync/TEST0.PS1
src/test/libpmempool_sync/TEST1.PS1
src/test/libpmempool_sync/TEST2
src/test/libpmempool_sync/TEST2.PS1
src/test/libpmempool_sync/libpmempool_sync.c
src/test/libpmempool_sync/out0.log.match
src/test/libpmempool_sync/out1.log.match
src/test/libpmempool_sync/out2.log.match
src/test/libpmempool_transform/TEST0
src/test/libpmempool_transform/TEST1
src/test/libpmempool_transform/TEST1.PS1
src/test/libpmempool_transform/TEST2
src/test/libpmempool_transform/TEST2.PS1
src/test/libpmempool_transform/libpmempool_transform.c
src/test/libpmempool_transform/out0.log.match
src/test/libpmempool_transform/out1.log.match
src/test/libpmempool_transform/out2.log.match

Ref: pmem/issues#367
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1506)

pmempool: fix check flags support

---

src/libpmempool/pool.c
src/tools/pmempool/info_obj.c

Ref: pmem/issues#374
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1539)

pmempool: fix coverity issues

---

src/benchmarks/blk.c
src/benchmarks/log.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1538)

benchmark: fix coverity issues

---

src/libpmem/libpmem.vcxproj
src/libpmem/pmem.c
src/libpmem/pmem.h
src/libpmem/pmem_windows.c
src/test/pmem_is_pmem_proc_windows/pmem_is_pmem_proc_windows.vcxproj
src/test/pmem_map/pmem_map.vcxproj
src/test/tools/bttcreate/bttcreate.vcxproj
src/test/tools/ddmap/ddmap.vcxproj
utils/cstyle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1544)

win: detect QueryVirtualMemoryInformation in runtime

---

src/windows/win_mmap.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1519)

win: clean up possible race condition in mmap_init

---

src/NVML.sln
src/test/unittest/libut.vcxproj
src/test/unittest/ut.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1541)

test: (win) check open handles at START/DONE

---

src/test/obj_locks/obj_locks.c

Due to some timing issues the test could hang.
Refs: pmem/issues#368
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1522)

obj: fix obj_locks hangup
