src/blk.c
src/blk.h
src/btt.c
src/btt.h
src/btt_layout.h
src/test/blk_non_zero/.gitignore
src/test/blk_non_zero/Makefile
src/test/blk_non_zero/README
src/test/blk_non_zero/TEST0
src/test/blk_non_zero/TEST1
src/test/blk_non_zero/TEST2
src/test/blk_non_zero/TEST3
src/test/blk_non_zero/TEST4
src/test/blk_non_zero/TEST5
src/test/blk_non_zero/TEST6
src/test/blk_non_zero/TEST7
src/test/blk_non_zero/TEST8
src/test/blk_non_zero/blk_non_zero.c
src/test/blk_non_zero/out0.log.match
src/test/blk_non_zero/out1.log.match
src/test/blk_non_zero/out2.log.match
src/test/blk_non_zero/out3.log.match
src/test/blk_non_zero/out4.log.match
src/test/blk_non_zero/out5.log.match
src/test/blk_non_zero/out6.log.match
src/test/blk_non_zero/out7.log.match
src/test/blk_non_zero/out8.log.match

This change reduces the time to write out the initial map in a zero-filled pool to zero.

blk: change how the EZ flags are handled in the blk map

---

src/benchmarks/log_mt/RUN.sh
src/benchmarks/log_mt/log_mt.c
src/benchmarks/log_mt/threads.c

- pmemlog_rewind required after warm up
- take DIR and OPS_COUNT from command line options in RUN.sh
- don't allocate separate buffer for each operation
- check for fails
- use malloc instead of calloc

benchmarks: fix log_mt benchmark

---

src/include/libvmmalloc.h

clang v.3.5.0 (x86_64-redhat-linux-gnu) defines __GNUC__ (4)
and __GNUC_MINOR__ (3), so we have to check if __clang__
is defined in order to distinguish clang from gcc.

vmmalloc: distinguish clang from gcc

---

src/libpmemblk/btt.c
src/libpmemblk/btt_layout.h

Update the BTT info block to contain the BTT uuid field
and appropriate padding as defined by the NVDIMM Namespace
Specification at http://pmem.io/documents.

btt: update layout to match latest spec

---

src/include/libpmemobj.h
src/libpmemobj/obj.c

"head" should be before "dest" - it is more natural.
The new order matches the order of arguments in API
of atomic lists.

obj: change order of arguments in pmemobj_list_*()

---

src/include/libpmemobj.h
src/libpmemobj/obj.c

Change order of arguments in pmemobj_list_move()
to match API of atomic lists.

obj: change order of arguments in pmemobj_list_move()

---

src/test/obj_sync/TEST3
src/test/obj_sync/TEST4
src/test/obj_sync/TEST5
src/test/obj_sync/TEST6
src/test/obj_sync/err5.log.match
src/test/obj_sync/err6.log.match
src/test/obj_sync/obj_sync.c

The test could fail randomly on a race condition on file output. Add
line count check to verify if mock failed to initialize each
synchronization primitive.

pmemobj: fix condition variable test

---

src/libpmemobj/obj.c
src/test/obj_store/README
src/test/obj_store/TEST4
src/test/obj_store/obj_store.c
src/test/obj_store/out4.log.match

Handle OID_NULL in 3 pmemobj functions:
- pmemobj_free, pmemobj_alloc_usable_size and pmemobj_next

obj: handle OID_NULL in 3 pmemobj functions

---

src/test/Makefile.inc

By default debug and non-debug static versions are built.
It can be changed by setting BUILD_STATIC_DEBUG
or BUILD_STATIC_NONDEBUG to 'n'.
It will be used by debug features.

test: let user choose static build types

---

src/libpmemobj/sync.c
src/libpmemobj/tx.c

Due to possible compiler optimizations, the atomic lock acquisition
could be significantly altered, causing a multi-threaded program to
deadlock.

pmemobj: fix atomic lock acquire

---

src/test/obj_sync/TEST1
src/test/obj_sync/TEST2
src/test/obj_sync/TEST3
src/test/obj_sync/TEST4
src/test/obj_sync/TEST5
src/test/obj_sync/TEST6
src/test/obj_tx_locks/TEST1
src/test/obj_tx_locks/TEST2
src/test/unittest/unittest.sh

On some OSes with older versions of valgrind installed, some tests
reported problems with msync not being thread safe. Newer versions of
valgrind do not report this issue - probably a false-positive.

common: add check valgrind version 3.10

---

src/libpmemobj/list.c
src/test/obj_list/obj_list.c
src/test/obj_list_realloc/out0.log.match
src/test/obj_list_realloc/out1.log.match
src/test/obj_list_realloc/out2.log.match
src/test/obj_list_realloc/out3.log.match
src/test/obj_list_realloc/out4.log.match
src/test/obj_list_realloc/out5.log.match
src/test/obj_list_realloc/out6.log.match
src/test/obj_list_realloc/out7.log.match
src/test/obj_list_realloc_move/out0.log.match
src/test/obj_list_realloc_move/out1.log.match
src/test/obj_list_valgrind/out7.log.match
src/test/obj_list_valgrind/out8.log.match

If the realloc was performed not in place the old PMEMoid was returned.

obj: fix return value in list_realloc_move function

---

src/test/obj_list/TEST0
src/test/obj_list/obj_list.c

Add some simple test to obj_list so it is possible to invoke
./RUNTESTS obj_* which runs all tests for pmemobj.
The dummy tests just opens the pool and checks the oob_header size.

obj: add dummy test to obj_list

---

src/libpmemobj/list.c
src/test/obj_list_remove/TEST3
src/test/obj_list_remove/out3.log.match

The pool_uuid_lo is not cleared when removing from list,
because the the object is OID_NULL if offset is zero. Thus
there cannot be an assert on pool_uuid_lo because it is
not possible to insert element to a list which the last
element was removed from.

obj: remove assert on pool_uuid_lo from list_insert_user

---

src/include/libpmemobj.h

To provide compile-time error checking the assign typed macro
uses a tricky gnu99 construct that has no direct C++ counterpart so
a simplified macro is used for cpp compilers.

obj: fix OID_ASSIGN_TYPED macro for C++ compilers

---

src/include/libpmemobj.h
src/libpmemobj/sync.c

Unlike C99 there's no restrict keyword in C++, but most
compilers have extension to workaround that problem.

obj: use __restrict keyword in sync API

---

src/test/util_pool_create/TEST2
src/test/util_pool_create/out0.log.match
src/test/util_pool_create/out2.log.match

On some systems, the creation of a very large file might hang the test
execution. This happens on travis which in consequence fails builds.

pmemobj: fix util_pool_create hangup

---

src/libpmemobj/tx.c
src/test/obj_debug/README
src/test/obj_debug/TEST2
src/test/obj_debug/grep2.log.match
src/test/obj_debug/obj_debug.c
src/test/obj_debug/out2.log.match

Log a debug notice message if the currently being added range
had already been added to the undo log earlier.

obj: debug feature for pmemobj_tx_add_range

---

doc/libpmemobj.3
src/examples/libpmemobj/pminvaders/pminvaders.c
src/include/libpmemobj.h
src/libpmemobj/libpmemobj.map
src/libpmemobj/list.c
src/libpmemobj/list.h
src/libpmemobj/obj.c
src/libpmemobj/obj.h
src/libpmemobj/tx.c
src/test/obj_basic_integration/TEST0
src/test/obj_basic_integration/obj_basic_integration.c
src/test/obj_debug/obj_debug.c
src/test/obj_list/obj_list.c
src/test/obj_store/obj_store.c
src/test/obj_tx_add_range/obj_tx_add_range.c
src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c
src/test/obj_tx_alloc/obj_tx_alloc.c
src/test/obj_tx_free/obj_tx_free.c
src/test/obj_tx_realloc/obj_tx_realloc.c
src/test/obj_tx_strdup/obj_tx_strdup.c
src/test/scope/out4.log.match

- new type safety macros with named unions
- atomic allocation API changes:
-- remove pmemobj_alloc_construct()
-- change return values to int
-- return PMEMoid using reference
-- change PMEMoid atomically using redo log
- add TX_NEW, TX_ZNEW, POBJ_NEW and POBJ_ZNEW macros
- add size parameter to TX_ALLOC, TX_ZALLOC, POBJ_ALLOC and POBJ_ZALLOC
- update manpage

obj: type safety macros and API changes

---

doc/libpmemobj.3
src/libpmemobj/obj.c
src/libpmemobj/tx.c

- pmemobj_alloc and pmemobj_zalloc return error
- pmemobj_tx_alloc and pmemobj_tx_zalloc return OID_NULL
- update manpage
Ref: pmem/issues#71

obj: change return value for allocations with zero size

---

Makefile
doc/libpmem.3
utils/check_whitespace.sh

Add script for checking whitespaces in man pages with respect to the
workarounds related to groff 1.22 issue from commit
4bab1a174be434a5c499a2b87943575410a1c023

common: check for trailing whitespaces in man pages

---

src/libpmemobj/lane.c
src/libpmemobj/list.c
src/libpmemobj/obj.c
src/libpmemobj/obj.h
src/libpmemobj/tx.c
src/test/Makefile
src/test/obj_tx_locks_abort/.gitignore
src/test/obj_tx_locks_abort/Makefile
src/test/obj_tx_locks_abort/README
src/test/obj_tx_locks_abort/TEST0
src/test/obj_tx_locks_abort/TEST1
src/test/obj_tx_locks_abort/TEST2
src/test/obj_tx_locks_abort/obj_tx_locks_abort.c
src/test/obj_tx_locks_abort/out0.log.match
src/test/obj_tx_locks_abort/out1.log.match
src/test/obj_tx_locks_abort/out2.log.match
src/test/obj_tx_locks_abort/valgrind1.log.match
src/test/obj_tx_locks_abort/valgrind2.log.match

Also renames *OBJ_OOB_OFFSET* to *OBJ_OOB_SIZE*.

obj: fix tx locks handling in aborted transaction

---

README.md
src/Makefile
src/test/README
src/test/RUNTESTS

All check test are run with a default timeout of 3 minutes. This can be
overridden by either providing the RUNTESTS script with the new value
using the -o flag, or by setting the TEST_TIME value in the make
check command.

common: add test timeout

---

src/common/out.c

Libraries should never call exit() - exit code may mean something specific for calling application and we may interfere with something.

common: abort() instead of exit()ing when internal assertion fails

---

src/test/unittest/unittest.h
src/test/unittest/ut_alloc.c
src/test/vmem_aligned_alloc/vmem_aligned_alloc.c
src/test/vmem_calloc/vmem_calloc.c
src/test/vmem_check/vmem_check.c
src/test/vmem_check_allocations/vmem_check_allocations.c
src/test/vmem_create_in_region/vmem_create_in_region.c
src/test/vmem_custom_alloc/vmem_custom_alloc.c
src/test/vmem_delete/vmem_delete.c
src/test/vmem_fork/vmem_fork.c
src/test/vmem_malloc/vmem_malloc.c
src/test/vmem_malloc_usable_size/vmem_malloc_usable_size.c
src/test/vmem_mix_allocations/vmem_mix_allocations.c
src/test/vmem_multiple_pools/vmem_multiple_pools.c
src/test/vmem_out_of_memory/vmem_out_of_memory.c
src/test/vmem_realloc/vmem_realloc.c
src/test/vmem_realloc_inplace/vmem_realloc_inplace.c
src/test/vmem_stats/vmem_stats.c
src/test/vmem_strdup/vmem_strdup.c
src/test/vmem_valgrind/vmem_valgrind.c

It lets tests be deterministic wrt how much memory is available from the pool and may catch some memory corruption bugs.

test/vmem: align mmaped anonymous memory to 4MB and add guard pages around it

---

src/libpmemobj/list.c
src/test/obj_list/obj_list.c

The offset stored using redo log was the old one.
Change the obj_list test app to cover this issue.
Ref: pmem/issues#78

obj: fix storing new offset after realloc

---

src/libpmemobj/obj.c
src/libpmemobj/obj.h
src/libpmemobj/tx.c
src/test/obj_direct/obj_direct.c

Otherwise, when user provides garbage oids, we hit crashes or assertion failures deep in the library and it's not easy for application developer to figure out what happened.
I was bitten by this when testing my new pmemobj example, which did not initialize dynamically allocated array of PMEMoids.

obj: validate user-provided oids in debug builds

---

src/examples/libpmemobj/pmemblk/obj_pmemblk.c
src/examples/libpmemobj/pmemlog/obj_pmemlog_simple.c

Revert changes made while correcting whitespace between operators.

obj: typo fix in examples

---

Makefile
utils/build-dpkg.sh
utils/build-rpm.sh

Use local 'src/test/testconfig.sh' (if it exists)
instead of coping 'testconfig.sh.example' as a unit tests'
config file during 'make rpm' and 'make dpkg'.

rpm/dpkg: use local testconfig.sh

---

src/libpmemobj/obj.c
src/test/blk_pool/TEST7
src/test/blk_pool/TEST8
src/test/blk_pool/out8.log.match
src/test/log_pool/TEST6
src/test/log_pool/TEST7
src/test/obj_pool/TEST7
src/test/obj_pool/TEST8
src/test/obj_pool/out8.log.match
src/test/obj_store/TEST0
src/test/obj_store/TEST1
src/test/obj_store/TEST2
src/test/obj_store/TEST3
src/test/obj_store/TEST4
src/test/obj_store/TEST5
src/test/obj_store/obj_store.c
src/test/obj_tx_alloc/TEST0
src/test/obj_tx_alloc/TEST1
src/test/obj_tx_alloc/obj_tx_alloc.c
src/test/obj_tx_alloc/valgrind1.log.match
src/test/obj_tx_realloc/TEST0
src/test/obj_tx_realloc/obj_tx_realloc.c
src/test/unittest/unittest.sh

This patch includes:
- Fixed allocation and reallocation of root object
- Unit tests improvements to cover zalloc/zrealloc path
- Improved generation of non-zeroed pool files

obj: fix allocation of zeroed objects

---

src/test/util_pool_open/TEST0
src/test/util_pool_open/TEST1

They do not pass when LOCAL_FS_DIR is a relative path ("." by default).

test: fix util_pool_open tests

---

src/libpmemobj/bucket.c
src/libpmemobj/bucket.h
src/libpmemobj/ctree.c
src/libpmemobj/heap.c
src/libpmemobj/heap.h
src/libpmemobj/heap_layout.h
src/libpmemobj/obj.h
src/libpmemobj/pmalloc.c
src/test/Makefile
src/test/obj_basic_integration/obj_basic_integration.c
src/test/obj_bucket/obj_bucket.c
src/test/obj_ctree/obj_ctree.c
src/test/obj_heap/obj_heap.c
src/test/obj_pmalloc_basic/obj_pmalloc_basic.c
src/test/obj_pmalloc_mt/.gitignore
src/test/obj_pmalloc_mt/Makefile
src/test/obj_pmalloc_mt/TEST0
src/test/obj_pmalloc_mt/obj_pmalloc_mt.c
src/test/obj_pmalloc_mt/valgrind0.log.match

Memory block heap operations are now unified regardless of their type,
this enables a simple and efficient implementation of realloc and
simplifies other operations. This patch also addresses issues related
to persistent/volatile heap state mismatch, which, combined with small
ctree optimization, significantly improves allocation performance.

obj: rewrite allocator memory block handling

---

README.md
src/common/out.c
src/common/util.c
src/common/valgrind_internal.h
src/libpmemobj/tx.c
src/test/arch_flags/log0.log.match
src/test/out_err/traces0.log.match
src/test/traces_custom_function/out0.log.match
src/test/traces_custom_function/out1.log.match
src/test/unittest/unittest.sh

... in preparation for memcheck support
USE_VALGRIND will be a shortcut for both.

obj: rename USE_VALGRIND to USE_VG_PMEMCHECK

---

src/include/libpmemobj.h
src/libpmemobj/libpmemobj.map
src/test/scope/out4.log.match

- change strndup to strdup in linker map file
- fix comment in libpmemobj header
Ref: pmem/issues#89

obj: fix libpmemobj linker map file

---

doc/libpmemobj.3
src/include/libpmemobj.h
src/libpmemobj/libpmemobj.map
src/libpmemobj/obj.c
src/test/obj_direct/obj_direct.c
src/test/obj_list/obj_list.c
src/test/scope/TEST4
src/test/scope/out4.log.match

Right now each D_* macro invocation used for ptr dereferencing calls
a function that then performs a lookup in a hashtable - which had a
considerable performance impact on many workloads. This patch adds
a global per-thread variable that serves as a pool ptr cache. Quick
measurements show over 2x improvement.

obj: implement optimized version of pmemobj_direct

---

src/libpmemobj/bucket.c
src/test/obj_bucket/obj_bucket.c

When multiple threads currently try to allocate from a single bucket
that has only one memory block available, an OOM error may occur.
This patch forces the threads to lock before determining whether the
bucket can satisfy the allocation request or not.

obj: fix race condition during small allocations

---

src/test/RUNTESTS

Test for the --foreground option. Disable timeout when --foreground
not available.

test: fixed checks and changed timeout run condition

---

utils/check_whitespace

Ignore rpmbuild and dpkgbuild directories in in check_whitespace
script.

common: fix check_whitespace script

---

src/common/valgrind_internal.h
src/libpmemobj/heap.c
src/libpmemobj/lane.c
src/libpmemobj/list.c
src/libpmemobj/obj.c
src/libpmemobj/obj.h
src/libpmemobj/pmalloc.c
src/libpmemobj/redo.c
src/libpmemobj/tx.c
src/test/obj_basic_integration/TEST1
src/test/obj_basic_integration/obj_basic_integration.c
src/test/obj_basic_integration/valgrind1.log.match
src/test/obj_debug/README
src/test/obj_debug/TEST3
src/test/obj_debug/grep3.log.match
src/test/obj_debug/obj_debug.c
src/test/obj_debug/valgrind3.log.match
src/test/obj_tx_add_range/valgrind1.log.match
src/test/obj_tx_add_range_direct/valgrind1.log.match
src/test/obj_tx_alloc/obj_tx_alloc.c
src/test/obj_tx_alloc/valgrind1.log.match
src/test/obj_tx_free/valgrind1.log.match
src/test/obj_tx_realloc/TEST1
src/test/obj_tx_realloc/obj_tx_realloc.c
src/test/obj_tx_realloc/out1.log.match
src/test/obj_tx_realloc/valgrind1.log.match
src/test/obj_tx_strdup/TEST1
src/test/obj_tx_strdup/out1.log.match
src/test/obj_tx_strdup/valgrind1.log.match

Modify library source so that it includes transaction macros from
pmemcheck. Add some tests using transactions.

obj: add pmemcheck transactions support

---

src/test/pmem_valgr_simple/valgrind0.log.match

Add missing $(N) wildcard in one of pmemcheck tests.

test: add missing wildcard

---

src/test/unittest/ut.c

Right now, asserts closes all the global log files and calls exit(1)
once done. This has two major drawbacks: debuggers don't catch ASSERTs
and the macros themselves are not threadsafe, making it difficult to
write multithreaded tests.

ut: change tests to abort on assert

---

doc/libpmem.3
doc/libpmemblk.3
doc/libpmemlog.3
doc/libpmemobj.3
doc/libvmem.3
doc/libvmmalloc.3

Some macros don't need alternating BR or IR.

doc: fix groff font macros

---

doc/libpmemobj.3
src/include/libpmemobj.h
src/libpmemobj/heap_layout.h
src/libpmemobj/obj.c
src/libpmemobj/tx.c
src/test/obj_basic_integration/obj_basic_integration.c
src/test/obj_pmalloc_basic/obj_pmalloc_basic.c

The allocator shouldn't attempt to satisfy requests
that are sure to fail, i.e. larger than ~16GB.
Ref: pmem/issues#84
Ref: pmem/issues#86
Ref: pmem/issues#97
Ref: pmem/issues#98

obj: block too large allocation requests

---

src/include/libpmemobj.h
src/test/obj_tx_locks_abort/obj_tx_locks_abort.c

Compile-time detection of typed OID's declared with type number
exceeding the PMEMOBJ_NUM_OID_TYPES limit.
Ref: pmem/issues#83

obj: add compile-time check for incorrect type num

---

src/Makefile.inc
src/test/Makefile.inc
src/test/unittest/Makefile
src/tools/Makefile.inc

rm "-d" option is not recognized on all the systems.  Use "-r" instead.

common: fix make clobber

---

src/test/util_poolset/TEST0
src/test/util_poolset/TEST2

The match files for TEST0 and TEST2 are prepared for running on
non-pmem filesystem. Just add proper requirement for fs.

common: fix util_poolset tests for pmem fs

---

src/libpmemobj/lane.c
src/libpmemobj/lane.h
src/libpmemobj/list.c
src/libpmemobj/obj.c
src/libpmemobj/pmalloc.c
src/libpmemobj/tx.c
src/test/obj_lane/obj_lane.c
src/test/obj_lane/out0.log.match
src/test/obj_list/obj_list.c

This patch adds a lane mechanism to call initialization function
after the corresponding lane sections were recovered. This fixes
an issue in which allocator volatile and persistent states were
mismatched after redo log recovery.

obj: fix order of sections initialization

---

Makefile
src/Makefile
src/test/Makefile
src/test/Makefile.inc
src/test/RUNTESTS
src/test/pmemalloc/Makefile
src/test/pmemspoil/Makefile
src/test/pmemwrite/Makefile
src/test/scope/Makefile
src/test/unittest/Makefile
utils/build-dpkg.sh
utils/build-rpm.sh

Add "pcheck" target for each test directory and call "pcheck" target recursively from main Makefile.
Note: make pcheck enters each test directory. make -s disables printing enter/leave directory messages.

test: add parallel execution support

---

doc/pmempool-info.1
src/tools/pmempool/info.c
src/tools/pmempool/info_obj.c

The chunk headers between 'used' or 'free' and the footer are
not changed when merging chunks, thus displaying the 'unknown'
chunk types doesn't make sense anymore. In such case it is also
required to traverse through all chunks in the zone by jumping over
size_idx of the current chunk rather than traversing through all chunks
from the zone and filtering chunks by range and types.

pmempool: fix printing chunk headers

---

doc/libpmemobj.3

- Fix description of POBJ_FOREACH_SAFE_TYPE() macro.
- Clarify behavior of non-transactional allocation functions when NULL is
passed as "oidp" argument.
- Add a note about undefined order of objects in the internal object containers.
Ref: pmem/issues#88
Ref: pmem/issues#106

doc: update libpmemobj man page

---

src/test/util_poolset/out2.log.match
src/test/util_poolset/util_poolset.c

set->zeroed can be used only in "create" path. In "open" path it's left uninitialized.

test: fix read of uninitialized value in util_poolset

---

src/libpmemobj/ctree.c
src/libpmemobj/list.c
src/libpmemobj/tx.c
src/test/obj_basic_integration/obj_basic_integration.c
src/test/obj_tx_alloc/obj_tx_alloc.c
src/test/obj_tx_alloc/valgrind1.log.match
src/test/obj_tx_realloc/obj_tx_realloc.c
src/test/obj_tx_strdup/obj_tx_strdup.c

Abort transaction in case of:
- allocation with size 0,
- allocation/reallocation with size larger than PMEMOBJ_MAX_ALLOC_SIZE.
Fix overwriting "errno" with 0, when no error occured.

obj: abort transaction on allocation failure

---

src/include/libpmemobj.h
src/libpmemobj/libpmemobj.map
src/libpmemobj/obj.c
src/test/obj_direct/obj_direct.c
src/test/obj_list/obj_list.c
src/test/scope/out4.log.match

Currently when using pmemobj_close only the thread that executed the
function had its cache invalidated which led to invalid direct ptrs
being returned in multithreaded applications.

obj: invalidate cache pool in all threads on close

---

doc/libpmemobj.3
src/test/obj_basic_integration/obj_basic_integration.c
src/test/obj_basic_integration/out0.log.match
src/test/obj_basic_integration/out1.log.match
src/test/obj_basic_integration/out2.log.match
src/test/obj_basic_integration/out3.log.match
src/test/obj_basic_integration/out4.log.match

- Update macro descriptions in man page.
- Add unit tests for POBJ_LIST_PREV/NEXT macros.
Ref: pmem/issues#104

obj: fix description of POBJ_LIST_PREV/NEXT macros

---

doc/libpmemblk.3
doc/libpmemlog.3
src/include/libpmemblk.h
src/include/libpmemlog.h
src/libpmemblk/libpmemblk.c
src/libpmemlog/libpmemlog.c
src/test/Makefile
src/test/set_funcs/.gitignore
src/test/set_funcs/Makefile
src/test/set_funcs/TEST0
src/test/set_funcs/set_funcs.c

src/common/set.c uses Realloc and Strdup, so we need a way to replace them in all libraries.

blk,log: add realloc and strdup to pmem*_set_funcs 

---

src/libpmemblk/blk.c
src/test/pmempool_check/out4.log.match
src/tools/pmempool/check.c

Use the poolset_uuid as parent uuid for btt arena info instead of
the uuid field from pool header. It seems like the poolset uuid
is more appropriate field for this because if the replication
would be enabled for the pmemblk mode the other replica would
have different uuid fiel but the same parent_uuid.

blk: use poolset_uuid as parent uuid for btt

---

src/test/obj_check/TEST5
src/test/obj_check/out5.log.match
src/test/pmemspoil/spoil.c

Fix returning error by pmemspoil and fix obj_check/TEST5 which didn't fail because of the pmemspoil issue.

Fix pmemspoil return value

---

src/libpmemobj/tx.c
src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c
src/test/obj_tx_add_range_direct/valgrind1.log.match

This patch addresses an issue in which data, that was already commited
by a transaction that used only one cache set instance, could be
erroneously reverted by an abort or pool recovery.

obj: fix aborts using old cache values

---

src/tools/pmempool/info_blk.c
src/tools/pmempool/info_log.c
src/tools/pmempool/info_obj.c

pmempool: fix possible NULL pointer dereference / memory leaks

---

doc/libpmem.3
src/examples/libpmem/full_copy.c
src/examples/libpmem/manpage.c
src/examples/libpmem/simple_copy.c
src/include/libpmem.h
src/libpmem/libpmem.map
src/libpmem/pmem.c
src/test/pmem_valgr_simple/pmem_valgr_simple.c
src/test/scope/out1.log.match

Adding the `pmem_unmap()` function call. The reason behind this addition is that it will help to make 
code portable and consistent. The first reason is that libpmem has a function called `pmem_map()` but not `pmem_unmap()`, so the user is required to use `munmap(2)` to delete the mappings. If the library is ported to another platform, let's say Windows, the calls for mapping and unmapping may be different, so the user may still continue using `pmem_map()` but not `munmap()`, however, if we have the `pmem_unmap()` function present, the user can continue using `pmem_map()` and `pmem_unmap()` without having to change his code to change from `munmap(2)` to its Windows counterpart. I think that it is reasonable to add this function and it will help with portability and consistency.
Changes in …

Adding pmem_unmap() function

---

src/libpmemobj/heap.c
src/test/obj_pmalloc_oom_mt/obj_pmalloc_oom_mt.c

This patch changes the biggest size that can be handled by runs to be
exactly CHUNKSIZE/2. Should improve fragmentation a tiny bit.
Also fixes an off-by-one error in the bucket selection logic.

obj: increase largest run allocation size

---

src/benchmarks/Makefile

The glib headers use GCC attributes which are not supported by clang -
for example the __alloc_size__.
We must test if this is an issue and turn off warning on unknown
attributes using the -Wno-unknown-attributes.

benchmark: silence glib unknown attributes

---

src/test/unittest/Makefile

EXTRA_CFLAGS is used everywhere. unittest helper library is the only exception.

ut: use EXTRA_CFLAGS consistently

---

Makefile
README.md
doc/Makefile
src/Makefile
src/Makefile.inc
src/tools/Makefile.inc

Add support for the prefix variable when running make install.
Example:
Command                               Installation directory
make install                          #/usr/local/include/libpmemlog.h
make install prefix=/usr              #/usr/include/libpmemlog.h
make install DESTDIR=/tmp             #/tmp/usr/local/include/libpmemlog.h
make install DESTDIR=/tmp prefix=/usr #/tmp/usr/include/libpmemlog.h
Signed-off-by: Daniel Verkamp <daniel.verkamp@intel.com>

common: support make install prefix

---

utils/build-rpm.sh

The commit 30c2a270b2c0d9b6a3779c0a7c100c95911a7c6f didn't fix the
make rpm on all systems. This patch adds the rpmbuild environment
variables to all installed files and sets the prefix appropriately.

common: fix prefix in make rpm

---

src/test/Makefile.inc
src/test/unittest/Makefile
src/test/unittest/unittest.h
src/test/unittest/ut.c
src/test/unittest/ut_backtrace.c

Libc's implementation:
Signal 6, backtrace:
0: ./obj_many_size_allocs() [0x4041bf]
1: ./obj_many_size_allocs() [0x40426f]
2: /lib/x86_64-linux-gnu/libc.so.6(+0x35180) [0x56c3180]
3: /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x56c3107]
4: /lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x56c44e8]
5: ../../debug/libpmemobj.so.1(+0x236ab) [0x4e556ab]
6: ../../debug/libpmemobj.so.1(pmemobj_alloc_usable_size+0xb9) [0x4e39ef2]
7: ../../debug/libpmemobj.so.1(+0x4225) [0x4e36225]
8: ../../debug/libpmemobj.so.1(+0x4a49) [0x4e36a49]
9: ../../debug/libpmemobj.so.1(+0x60ec) [0x4e380ec]
10: ../../debug/libpmemobj.so.1(pmemobj_check+0x66) [0x4e38609]
11: ./obj_many_size_allocs() [0x401c18]
12: ./obj_many_size_allocs() [0x401de6]
13: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x56afb45] …

test: dump stacktraces on fatal signals

---

src/jemalloc/include/jemalloc/internal/arena.h

This code is fishy. I'm not sure what was intended here.

jemalloc: fix left shift which overflows

---

src/test/unittest/ut_backtrace.c

Otherwise we loop forever between signal handler and crashing code.
I'm not sure how I tested the original patch...

ut: exit from ut_sighandler

---

src/libpmem/pmem.c
src/test/pmem_valgr_simple/pmem_valgr_simple.c
src/test/pmem_valgr_simple/valgrind0.log.match

Since pmemcheck now automatically recognizes the new instructions, the
additional instrumentation is unnecessary.

common: remove unnecessary pmemcheck macros

---

src/Makefile.inc

Currently when EXTRA_CFLAGS contains something which compiler does not
recognize (eg typo) we get misleading message about NVML not supporting
32-bit arch.

all: test whether compiler is functional

---

src/common/out.c
src/common/out.h
src/libpmemblk/btt.c
src/libpmemobj/pmalloc.c
src/libpmemobj/redo.c
src/libvmmalloc/libvmmalloc.c

Now compiler can check type compatibility in non-debug builds, sees
which variables are used and not generate warnings about unused
variables / parameters, etc. This patch is necessary for enabling
-Wunused-parameter.
When those arguments do not have any side effects they are optimized
away by the compiler.
Size comparison:
nondebug/libpmemblk.so.1.0.0   63872 ->  63848 -24b
nondebug/libpmemlog.so.1.0.0   49752 ->  49736 -16b
nondebug/libpmemobj.so.1.0.0  141240 -> 141208 -32b
nondebug/libpmem.so.1.0.0      36048 ->  36048 no diff
nondebug/libvmem.so.1.0.0     291752 -> 291752 no diff
nondebug/libvmmalloc.so.1.0.0 291584 -> 291584 no diff
New binaries - with ASSERT & LOG arg evaluation - are smaller.
This is a bit suprising, but the difference is within noise.

all: always evaluate LOG & ASSERT arguments

---

src/benchmarks/Makefile
src/benchmarks/obj_locks.c
src/benchmarks/pmembench_obj_locks.cfg

Adds benchmark for mutexes and rwlocks (PMEM vs. pthread).
There is also a benchmark for an alternate variant of PMEMmutex,
that stores the actual pthread mutex in RAM.

bench: add benchmark for pmem locks

---

src/benchmarks/Makefile
src/benchmarks/obj_lanes.c
src/benchmarks/pmembench_obj_lanes.cfg

The lane operation is repeated to minimize the benchmark framework
overhead influence on the results.

bench: add benchmark for lane operations

---

doc/pmempool-create.1
doc/pmempool-info.1
src/test/pmempool_create/TEST1
src/test/pmempool_info/TEST13
src/tools/pmempool/create.c
src/tools/pmempool/info.c

- do not use optional arguments
- the ranges for pmempool info can be specified using -r range
for -Z, -C and -l options
Ref: pmem/issues#96

pmempool: fix parsing optional arguments

---

src/test/pmem_valgr_simple/valgrind0.log.match

One of the lines matched hex-encoded address as decimal integer ($(N)).
Change it to $(X) and fix other address matches.

test: fix pmem_valgr_simple match file

---

src/include/libpmemobj.h

Assignment operation "_o.oid = _o.oid" has no effect.
This assignment was intentionaly wrote to have no effect but to
get compile time error when using D_RW macro on const TOID(struct ..)
variable. This patch avoids the warning.

obj: fix coverity warning on D_RW macro

---

doc/libpmemobj.3
src/include/libpmemobj.h
src/libpmemobj/libpmemobj.map
src/libpmemobj/obj.c
src/test/obj_store/TEST6
src/test/obj_store/obj_store.c
src/test/scope/out4.log.match

Right now the root object is initialized with zeroes and there's no
way around it. This patch addresses this problem by allowing the user
to specify a constructor which is called when the root object is first
created.

obj: add root object constructor

---

.travis.yml
src/test/Makefile.inc

Libunwind on Travis' systems is very old and does not provide pkg-config
files, so we have to provide a fallback. Additionally we have to move
-lunwind to after libut.a is linked.

travis: enable libunwind

---

src/test/obj_list/obj_list.c
src/test/obj_store/obj_store_mocks.c
src/test/unittest/unittest.sh

Fallout from ASan tests on newer gcc.
(These commits do not look very interesting, but note that ASan found a horrible memory corruption fixed by commit 88e71438113d15601ab2a3c4a0915543d30b5429)

Address Sanitizer fixes

---

src/test/Makefile

New 'make' targets:
- pcheck_blk
- pcheck_log
- pcheck_obj
- pcheck_other
- pcheck_pmem
- pcheck_pmempool
- pcheck_vmem
- pcheck_vmmalloc
Obj tests are the most time consuming and most important - run them
first. It speeds up pcheck by 20% on my machine.

test: split tests by type

---

src/include/libpmemobj.h

Do not define global variable for layout name because it is not
possible to use the layout declaration across multiple compilation
units.

obj: fix definition of POBJ_LAYOUT_BEGIN

---

src/test/ex_libpmemobj/Makefile
src/test/ex_libpmemobj/TEST15

... but only if running in parallel mode (pcheck) or stdout is not
terminal.

examples: redirect pminvaders output to /dev/null

---

doc/libpmemblk.3

Specify the behaviour for calling pmemblk_open function
with zero bsize.
Ref: pmem/issues#111

blk: update manpage for pmemblk_open function

---

src/libvmmalloc/libvmmalloc.c

This macro is not defined in older versions of malloc.h.

vmmalloc: add missing __MALLOC_HOOK_VOLATILE macro

---

doc/libpmemobj.3

Remove the manpage "support" for remote replication.

doc: obj manpage clarification

---

src/test/obj_list_macro/obj_list_macro.c

Fix issue reported by memcheck:
Conditional jump or move depends on uninitialised value(s).

test: fix use of uninitialised value

---

src/libpmemobj/tx.c
src/test/obj_tx_realloc/obj_tx_realloc.c

obj: handle invalid type numbers in tx_realloc

---

doc/libpmemobj.3
src/include/libpmemobj.h
src/libpmemobj/list.c

The POBJ_LIST_INSERT_HEAD, POBJ_LIST_INSERT_TAIL,
POBJ_LIST_INSERT_NEW_HEAD, POBJ_LIST_INSERT_NEW_TAIL,
POBJ_LIST_MOVE_ELEMENT_HEAD and POBJ_LIST_MOVE_ELEMENT_TAIL
macros were using POBJ_LIST_FIRST/POBJ_LIST_LAST macros which was not
thread safe atomic, because the lock on list head was held after
passing the first/last element to the appropriate function. This patch
changes mentioned macros to use OID_NULL as destination and depending
on the _before_ value the destination will be either head or tail of
the list. The POBJ_LIST_DEST_HEAD and POBJ_LIST_DEST_TAIL defines
constant values for appropriate destination.
This approach is thread safe atomic for mentioned macros.

obj: fix concurrency issue in user lists macros

---

src/test/magic/TEST0

There is no point in testing the file command with memcheck.

tests: do not run magic test with memcheck

---

.travis.yml

Use tmpfs to workaround the kernel oops in msync on travis.
Ref: pmem/issues#33
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/553)

common: use tmpfs for tests

---

src/test/vmmalloc_init/vmmalloc_init.c

When library is compiled with default flags, malloc and __malloc_hook
do not point to the actual malloc function, but to the proper PLT entry.
And since this is the same PLT entry (both should point to malloc from
libvmmalloc), the pointers do match.
However, when library is compiled with -Bsymbolic-functions flag (which
is automatically added when building packages on some Linux distros),
__malloc_hook no longer points to PLT, but directly to libvmmalloc's
implementation of malloc.  So, even though the same function is
referenced in both cases, the pointers are different resulting
in assertion failure.

test: remove asserts from vmmalloc_init test

---

src/libpmemobj/list.c
src/libpmemobj/list.h
src/libpmemobj/obj.c
src/libpmemobj/pmalloc.c
src/libpmemobj/pmalloc.h
src/libpmemobj/tx.c
src/test/obj_list/obj_list.c
src/test/obj_persist_count/out1.log.match
src/test/obj_realloc/Makefile
src/test/obj_realloc/obj_realloc.c
src/test/obj_store/obj_store_mocks.c

This patch makes the zalloc an zrealloc functions to
zero initialize the entire allocated area - not just the
requested area. The problem was if the zallocated object
was zreallocated, in such situation the memory above requested area and
below the usable size was not zeroed, next in zrealloc the memory above
the usable size was zeroed which resulted in non-zeroed part of emmory
after zrealloc.
Ref: pmem/issues#120
Ref: pmem/issues#121
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/550)

obj: fix zalloc and zrealloc

---

src/test/unittest/unittest.sh

When TEST file is not requiring any fs type, we are running it against
pmem, non-pmem and local. In such cases local tests are redundant,
because they are equal to either non-pmem or pmem tests.
This patch speeds up make check by 30% on my system.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/548)

ut: disable useless local tests

---

src/Makefile
src/Makefile.inc
src/benchmarks/Makefile
src/common.inc
src/common/Makefile
src/examples/Makefile.inc
src/test/Makefile.inc
src/test/unittest/Makefile
src/tools/Makefile.inc

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/532)

common: fix double path separators in makefiles

---

src/test/ex_libpmemobj/TEST15

May happen when pminvaders unit test is executed via sudo.

test: avoid permission denied error on /dev/stdout

---

src/common/util.c
src/common/valgrind_internal.h

With this change compiler can shuffle the code around to give CPU's
branch predictor better information and reduce instruction cache usage.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/549)

valgrind: use __builtin_expect

---

src/Makefile.inc
src/common.inc
src/test/unittest/Makefile
src/tools/Makefile.inc

All problems reported by -Wconversion are already solved. This commit only enables it *when* the compiler is smart enough. (gcc 4.6, as used by travis, is not)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/518)

libs, ut, tools: enable -Wconversion

---

src/test/unittest/ut.c

The issue occurs with gcc version 4.9.2 20150212 (Red Hat 4.9.2-6)

test: fix more implicit conversion warnings

---

src/common/out.h
src/libpmemobj/heap.c
src/libpmemobj/tx.c
src/test/obj_basic_integration/obj_basic_integration.c
src/test/obj_lane/obj_lane.c
src/test/obj_list/obj_list.c
src/test/out_err/out_err.c
src/test/traces/traces.c
src/test/traces_custom_function/traces_custom_function.c
src/test/unittest/unittest.h

Noticed in libpmemobj/tx.c.
After this change ASSERT* fails to build when the expression is
possible to evaluate at compile time and it's always true.
(See nice table in the commit description)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/567)

common, ut: detect useless ASSERT(1)

---

src/common/set.c
src/common/util.c
src/common/util.h
src/libpmem/pmem.c
src/libvmem/vmem.c
src/libvmem/vmem.h
src/libvmmalloc/libvmmalloc.c
src/test/util_map_proc/util_map_proc.c
src/test/vmem_check_allocations/vmem_check_allocations.c

jemalloc divides passed memory between base allocator and "usable" space
in a way which depends on alignment of passed address.
It means the amount of usable space for files of the same size depends
on luck. This is quite suprising.
This patch takes the luck out and makes the division at fixed point.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/533)

vmem, vmmalloc: align start of pool to 4MB

---

src/test/obj_sync/err0.log.match

After adding function name to error messages in commit
d915be3c3636adef5f08d072230154a31d5f392b the err0.log.match file didn't
match always due to race between mutex_write_worker and
mutex_check_worker. Add regex to match both write and check workers
which can print an error string.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/568)

test: fix obj_sync match file

---

src/benchmarks/obj_locks.c

Address of passed lock changes during init_lock, so get_lock was
returning old (and unitialized) address.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/576)

benchmarks: fix volatile locks benchmark

---

src/jemalloc/include/jemalloc/internal/jemalloc_internal.h.in
src/jemalloc/src/jemalloc.c
src/test/vmem_realloc_inplace/vmem_realloc_inplace.c

If shrinking the huge allocation (>=4MB) to some smaller size fails due
to the lack of memory for a new arena, return the original allocation
pointer instead of NULL.
For allocations larger than a single chunk, try to shrink them to a
single chunk first, then there is a chance that the actual reallocation
will succeed.
Ref: pmem/issues#24

vmem: fix reallocation to smaller size

---

doc/libpmemobj.3

- Fix POBJ_FREE macro signature.
- Fix description of TX_ZNEW macro.
- Add missing prototypes for POBJ_LIST_MOVE_ELEMENT_AFTER and
POBJ_LIST_MOVE_ELEMENT_BEFORE macros.
Ref: pmem/issues#124
Ref: pmem/issues#126
Ref: pmem/issues#131

doc: minor tweaks of libpmemobj man page

---

src/include/libpmemobj.h

In an effort to make our header file usable with a broad spectrum
of standards (-std=c++11 in particular) typeof has to be changed to an
alternate keyword. This solution is suggested by gcc documentation:
https://gcc.gnu.org/onlinedocs/gcc/Typeof.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/594)

obj: change typeof to more universal __typeof__

---

.travis.yml
src/benchmarks/Makefile
src/common/set.c
src/common/util.h
src/libpmemblk/blk.c
src/libpmemblk/btt.c
src/libpmemlog/Makefile
src/libpmemlog/log.c
src/libpmemobj/Makefile
src/test/Makefile
src/test/Makefile.inc
src/test/unittest/unittest.h
src/test/unittest/ut.c
src/test/util_uuid_generate/.gitignore
src/test/util_uuid_generate/Makefile
src/test/util_uuid_generate/TEST0
src/test/util_uuid_generate/TEST1
src/test/util_uuid_generate/TEST2
src/test/util_uuid_generate/out0.log.match
src/test/util_uuid_generate/out1.log.match
src/test/util_uuid_generate/out2.log.match
src/test/util_uuid_generate/util_uuid_generate.c
src/tools/Makefile.inc
src/tools/pmempool/check.c
src/tools/pmempool/output.c
src/tools/pmempool/output.h
utils/build-dpkg.sh
utils/build-rpm.sh

The BSD libuuid library has one file that is licensed as LGPL. Some consumers
of NVML require that there be no dependency on LGPL license. As a result we
implemented our own functions that we require in NVML.
Ref: pmem/issues#122
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/597)

common: remove dependency on libuuid

---

src/libpmemobj/bucket.c
src/libpmemobj/bucket.h
src/libpmemobj/heap.c
src/libpmemobj/heap.h
src/libpmemobj/pmalloc.c
src/test/obj_out_of_memory/TEST2
src/test/obj_out_of_memory/obj_out_of_memory.c

When a program tried to free memory from a zone that wasn't previously
processed in current volatile state the library tried to dereference
potentially old and invalid bucket memory address.
This patch changes the logic to completely skip the volatile state
update in case of frees to unitialized zones.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/598)

obj: fix pfree operations on unitialized zones

---

src/benchmarks/Makefile
src/common.inc

According to clock_gettime(3) man page, linking with librt explicitly
is required for glibc versions before 2.17.
Add a simple check if explicit linking is required.
Ref: pmem/issues#140
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/599)

benchmark: check if linking librt is required

---

doc/libpmem.3
doc/libpmemobj.3
src/include/libpmem.h
src/include/libpmemobj.h
src/libpmem/pmem.c
src/libpmemobj/obj.c
src/libpmemobj/obj.h
src/test/obj_heap/obj_heap.c
src/test/obj_list/obj_list.c
src/test/obj_pmalloc_basic/obj_pmalloc_basic.c
src/test/obj_redo_log/obj_redo_log.c
src/test/obj_sync/obj_sync.c

Add missing "const" qualifier to the "addr" argument of selected libpmem
and libpmemobj interfaces, like pmem_is_pmem(), pmem_flush(),
pmem_msync(), ...).
Ref: pmem/issues#139
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/600)

pmem: add missing "const" qualifier

---

src/include/libpmemobj/p.hpp
src/include/libpmemobj/persistent_ptr.hpp
src/include/libpmemobj/pext.hpp
src/test/Makefile
src/test/obj_cpp_p_ext/.gitignore
src/test/obj_cpp_p_ext/Makefile
src/test/obj_cpp_p_ext/TEST0
src/test/obj_cpp_p_ext/obj_cpp_p_ext.cpp

The additional templated operator overloads are in a separate header.
This was done to ease the integration of existing applications.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/601)

cpp: Added extended functionality to p<>

---

src/include/libpmemobj/persistent_ptr.hpp
src/test/obj_cpp_ptr/obj_cpp_ptr.cpp

Two small fixes to the copy constructor and assignment operator.
This is to properly disable conversion between incompatibile types.
closes pmem/issues#143
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/605)

cpp: fix constructor and assignment operator

---

doc/libpmemobj.3
src/include/libpmemobj.h

... and POBJ_TX_CRASH_ON_NO_ONABORT macro is defined.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/602)

obj: abort() when there's no ONABORT section

---

src/test/unittest/unittest.sh

Another bad interaction between my fs_type changes and
2a38fcec48d8b590c75222a4db20fe50ea157bd8 :(
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/609)

ut: fix require_fs_type none

---

src/test/obj_realloc/TEST0

The obj_realloc test timeouts very often on non-pmem filesystem. Use
PMEM_IS_PMEM_FORCE to speed up the test.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/613)

tests: fix timeouting obj_realloc test

---

src/test/Makefile.inc

Eg it's not possible to disable -Werror in tests.
Fixes regression from 7cd94abad4177d7766755092be21df8ccdb9f684.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/616)

test: add EXTRA_CFLAGS after our CFLAGS

---

src/test/Makefile
src/test/blk_pool/TEST25
src/test/blk_pool/TEST26
src/test/log_pool/TEST24
src/test/log_pool/TEST25
src/test/obj_pool/TEST25
src/test/obj_pool/TEST26
src/test/pmempool_rm/TEST1

Add missing "require_no_superuser" macro to selected unit tests.
Add missing "vmmalloc_valloc" test to the main UT makefile.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/619)

test: prevent executing selected test as superuser

---

src/common/out.c
src/test/out_err/traces0.log.match

`<libpmem>: <1> [out.c:225 out_init] libpmem version 1.0`
instead of:
`<libpmem>: <1> [../../src/../src/common/out.c:225 out_init] libpmem version 1.0`
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/621)

common: remove directories from printed file names

---

src/test/ex_libpmemobj/TEST15
src/test/ex_libpmemobj/TEST16

Without it ncurses initialization messes up stderr when pcheck is used
and one of the tests fails.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/627)

test: redirect pminvaders stderr to /dev/null

---

src/include/libpmemobj/detail/common.hpp
src/include/libpmemobj/detail/specialization.hpp
src/include/libpmemobj/persistent_ptr.hpp
src/test/Makefile
src/test/match
src/test/obj_cpp_ptr_arith/.gitignore
src/test/obj_cpp_ptr_arith/Makefile
src/test/obj_cpp_ptr_arith/TEST0
src/test/obj_cpp_ptr_arith/TEST1
src/test/obj_cpp_ptr_arith/TEST2
src/test/obj_cpp_ptr_arith/obj_cpp_ptr_arith.cpp
src/test/obj_cpp_ptr_arith/out0.log.match
src/test/obj_cpp_ptr_arith/valgrind1.log.match
src/test/obj_cpp_ptr_arith/valgrind2.log.match

Add all essential arithmetic and pointer operators to the
persistent_ptr<>.
Initial implementation by @pbalcer
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/632)

obj: add persistent_ptr<> comparison and arith operators

---

src/benchmarks/pmemobj_tx.c

The allocation overhead is approximately 64 bytes. If the requested
allocation size is for example 1b it would require the FACTOR to be at
least 64. This patch adds the allocation overhead to the allocation
size in order to allocate enough space in pmemobj pool.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/633)

benchmarks: fix determining the pool size

---

src/test/Makefile.inc

It's used by require_fs_type pmem/non-pmem.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/636)

ut: add pmemdetect as dependency for all tests

---

src/examples/libpmemobj/pmemobjfs/Makefile
src/examples/libpmemobj/pmemobjfs/README

The required version for FUSE is  2.9.1 because in this version the
fallocate function was introduced.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/637)

pmemobjfs: add required version of FUSE

---

src/test/match

... when all lines from the ".match" were already processed.
We already print the whole file when matching fails in the middle
of a match file.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/650)

test: dump contents of file that didn't match

---

utils/cstyle

... as found in Debian testing.
Issues:
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\S{ <-- HERE / at ../../../src/../utils/cstyle line 640.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE / at ../../../src/../utils/cstyle line 640.
Redundant argument in printf at ../../../src/../utils/cstyle line 194, <GEN3> line 138.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/657)

cstyle: fix issues found by perl 5.22

---

src/test/memcheck-stdcpp.supp

The existing suppression file didn't work for gcc 5.3.1 on Fedora 22.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/662)

test: update suppression file for memcheck

---

Makefile
utils/check_whitespace

New options:
-g - check all files tracked by git
-r dir - recursively check all files in specified directory
-v verbose - print whether file was checked or not
-f force - disable blacklist
Previous behavior can be restored by passing "-r ."
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/666)

utils/check_whitespace: check files tracked by git

---

src/include/libpmemobj/persistent_ptr.hpp
src/include/libpmemobj/pool.hpp
src/test/Makefile
src/test/obj_cpp_pool_primitives/.gitignore
src/test/obj_cpp_pool_primitives/Makefile
src/test/obj_cpp_pool_primitives/TEST0
src/test/obj_cpp_pool_primitives/TEST1
src/test/obj_cpp_pool_primitives/obj_cpp_pool_primitives.cpp
src/test/obj_cpp_pool_primitives/pmemcheck1.log.match

-Add the following methods to the pool class:
-- persist
-- flush
-- drain
-- memcpy_persist
-- memset_persist
- And the following methods to the persistent_ptr class:
-- persist
-- flush
- Add noexcept operator to relevant functions.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/664)

obj: add primitives to pool and persistent_ptr

---

src/benchmarks/pmemobj_tx.c

The 1.2 factor was too small for huge allocations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/675)

benchmarks: fix factor in obj_tx_alloc

---

src/libpmemobj/obj.c

Replace '%c' with '0x%02x' to avoid corrupted or truncated messages when
the argument is non-printable character.
Ref: pmem/issues#154
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/679)

obj: modify formatting string in memset() traces

---

src/test/obj_persist_count/out1.log.match

In commit e7a87d3f624d5e9a270701e1dc719d48135248ea I decreased number
of persists and increased number of flushes and drains, but forgot to
update one of the match files. Fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/685)

test: update number of persists/flushes/drains

---

src/include/libpmemobj/detail/integer_sequence.hpp
src/include/libpmemobj/detail/make_atomic_impl.hpp
src/include/libpmemobj/make_persistent_atomic.hpp
src/include/libpmemobj/persistent_ptr.hpp
src/include/libpmemobj/pool.hpp
src/test/Makefile
src/test/obj_cpp_make_persistent_atomic/.gitignore
src/test/obj_cpp_make_persistent_atomic/Makefile
src/test/obj_cpp_make_persistent_atomic/TEST0
src/test/obj_cpp_make_persistent_atomic/TEST1
src/test/obj_cpp_make_persistent_atomic/obj_cpp_make_persistent_atomic.cpp
src/test/obj_cpp_make_persistent_atomic/valgrind1.log.match

Use C++14-style make_integer_sequence to unpack variadic tuple.
Refs: pmem/issues#155
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/686)

obj: cpp make_persistent_atomic implementation

---

src/test/pmem_map/out1.log.match

The pmem_map/TEST1 test expected the ENOSPC errno returned from
posix_fallocate when trying to allocate very big file, but in fact the
posix_fallocate can return EFBIG errno as well for such a big file.
Change the match file to accept both error messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/693)

pmem: fix pmem_map test

---

doc/libpmemobj.3

Remove duplicate 'also' in libpmemobj man page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/695)

doc: libpmemobj: fix duplicate 'also' typo

---

src/libpmemobj/tx.c
src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c

When one transaction issued more than 127 small (less than 32 bytes)
tx_adds and committed, tx_abort in the next transaction could restore
some memory from the 1st transaction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/708)

obj: fix nasty tx corruption bug

---

src/test/obj_sync/obj_sync.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/711)

obj: report timedlock error in obj_sync unit test

---

src/libpmemobj/obj.h

For quite some time the range cache structure size was mis-aligned
with the internal heap allocation class sizes and caused some
unnecessary fragmentation to occur.
pmem/issues#159
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/714)

obj: fix range cache size to match alloc class

---

doc/libpmemobj.3
src/include/libpmemobj/detail/conversions.hpp
src/include/libpmemobj/detail/pexceptions.hpp
src/include/libpmemobj/mutex.hpp
src/include/libpmemobj/pool.hpp
src/include/libpmemobj/shared_mutex.hpp
src/include/libpmemobj/transaction.hpp
src/libpmemobj/tx.c
src/test/Makefile
src/test/obj_cpp_transaction/.gitignore
src/test/obj_cpp_transaction/Makefile
src/test/obj_cpp_transaction/TEST0
src/test/obj_cpp_transaction/TEST1
src/test/obj_cpp_transaction/obj_cpp_transaction.cpp
src/test/obj_cpp_transaction/valgrind1.log.match

Introduce two types of transactions: closure and scoped.
Closure transactions are implemented fully in c++11 and are the
preffered choice of transactions for this standard.
C++11 does not support all features to make scoped transactions
fully automatic. Scoped transactions have been divided into:
- `manual`, which need to be commited manually or they 
abort upon scope end,
- `automatic`, which commit and abort automatically, but
are available only if your compiler defines the
`__cpp_lib_uncaught_exceptions` feature macro.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/713)

obj: add c++ transactions

---

src/libpmemobj/heap.c

The function to calculate zone size index didn't do it properly for
all zones except for the last one, this resulted in an off-by-one
error in heap structures where the zone was one chunk smaller than
it really was.
pmem/issues#137
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/724)

obj: fix heap not properly using the last chunk

---

src/test/obj_cpp_timed_mtx/TEST0
src/test/unittest/unittest.sh

... it was missing the binary name. Additionally add reporting an error
if binary is not provided.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/730)

test: fix require binary in obj_cpp_timed_mtx test

---

doc/libpmemobj.3

'dest' pointer in TX_MEMCPY/TX_MEMSET macros cannot be 'const'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/731)

doc: remove "const" qualifier from some macros

---

doc/libpmemblk.3
doc/libpmemlog.3
src/examples/libpmemblk/assetdb/asset_checkin.c
src/examples/libpmemblk/assetdb/asset_checkout.c
src/examples/libpmemblk/assetdb/asset_list.c
src/examples/libpmemblk/assetdb/asset_load.c
src/examples/libpmemblk/manpage.c
src/examples/libpmemlog/manpage.c
src/examples/libpmemobj/manpage.c
src/examples/libpmemobj/pmemblk/obj_pmemblk.c
src/examples/libpmemobj/pmemlog/obj_pmemlog.c
src/examples/libpmemobj/pmemlog/obj_pmemlog_macros.c
src/examples/libpmemobj/pmemlog/obj_pmemlog_minimal.c
src/examples/libpmemobj/pmemlog/obj_pmemlog_simple.c
src/include/libpmemblk.h
src/include/libpmemlog.h
src/libpmemblk/blk.c
src/libpmemlog/log.c

Modify libpmemlog and libpmemblk API to not use "off_t" type for
function arguments or returned value.
This modification is dictated by incompatible "off_t" definitions on
64-bit Linux and Windows operating systems.  On Windows, "off_t" is
always 32-bit long, which is not enough to hold offsets of large (>4GB)
pmem pool files.
To avoid potential problems with redefining "off_t" or with adding
additional typedefs, seems like the best choice is to use "long long"
type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/732)

common: substitute "off_t" with "long long int"

---

src/test/Makefile
utils/build-dpkg.sh
utils/build-rpm.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/736)

Fix parallel building tests and pcheck in packages

---

src/test/tools/pmemobjcli/pmemobjcli.c

Before commit cafc94809b7d9ee886b66367a5eda6ba8042fae0 pmemobj_type_num
could handle invalid oids, because type numbers had a maximum value.
After this commit type numbers can have arbitrary values, so there's no
way to return an error.
Handle null oids at the caller side instead of crashing in the library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/741)

pmemobjcli: handle null oids in pmemobj_type_num wrapper

---

src/Makefile

Pmempool depends on libpmemobj.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/739)

tools: build pmemobj before tools

---

src/Makefile.inc
src/benchmarks/Makefile
src/test/unittest/Makefile
src/tools/Makefile.inc

...and add support for EXTRA_CFLAGS_DEBUG and EXTRA_CFLAGS_RELEASE.
Without appending EXTRA_CFLAGS at the end it's not possible to disable some warnings.
EXTRA_CFLAGS_RELEASE allows overriding eg optimization flags in release mode without also enabling them for debug mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/749)

all: always append EXTRA_CFLAGS after our CFLAGS

---

src/common/out.c
src/common/set.c
src/examples/libpmemobj/tree_map/ctree_map.c
src/include/libpmemobj.h
src/libpmem/pmem.c
src/libpmemobj/ctree.c
src/libpmemobj/heap.c
src/libpmemobj/heap_layout.h
src/libpmemobj/obj.h
src/test/tools/pmemspoil/spoil.c
src/tools/pmempool/info_obj.c

There is no Windows-specific code in these patches yet.
It's just to address some incompatibilities between gcc/clang and MSFT C compiler and to make further   work on NVML for Windows easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/702)

A bunch of patches required to compile NVML on Windows

---

src/libpmemobj/tx.c

ctree_insert error interrupted the surrounding loop, but didn't set
return value, so function returned success.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/752)

obj: fix error handling in pmemobj_tx_add*

---

src/Makefile
utils/make-pkg-config.sh

Fix passing appropriate libdir variable to make-pkg-config.sh.
Fix dependency for libpmem.
Ref: pmem/issues#165
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/761)

common: fix creating pkg-config scripts

---

src/test/unittest/unittest.sh

Get rid of 'error: ' message if valgrind is not available when running
tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/765)

test: fix confusing message if no valgrind

---

doc/cppobj.Doxyfile

Strip full file path in generated html files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/755)

doc: cpp strip filename

---

src/test/Makefile

Add two tests for timed_mutex missing from the Makefile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/774)

cpp: add missing tests

---

src/test/remote_obj_basic/TEST0
src/test/remote_obj_basic/TEST1
src/test/remote_obj_basic/TEST2
src/test/remote_obj_basic/TEST3
src/test/remote_obj_basic/pool0.set
src/test/remote_obj_basic/pool1.set
src/test/remote_obj_basic/pool2.set
src/test/remote_obj_basic/pool3.set

Pool files have to have unique names
in order to enable running parallel tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/775)

test: fix remote poolset files

---

src/libvmmalloc/libvmmalloc.c

Modify posix_memalign() and aligned_alloc() implementation to avoid
using je_vmem_memalign().
The use of je_vmem_memalign() causes problems on platforms that don't
include that legacy API.  The jemalloc configure logic doesn't export
that function unless the platform already provides memalign().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/776)

vmmalloc: avoid using je_vmem_memalign()

---

src/Makefile.inc

From gcc manpage:
"-Og enables optimizations that do not interfere with debugging. It
should be the optimization level of choice for the standard
edit-compile-debug cycle, offering a reasonable level of optimization
while maintaining fast compilation and a good debugging experience."
Available since gcc 4.8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/780)

all: enable some optimizations in debug builds

---

utils/check_license/check-headers.sh

"git log" may not work correctly, if PWD contains symlinks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/798)

common: use physical paths in check-headers script

---

src/test/unittest/unittest.sh

When test creates huge log files, next invocation can be quite slow,
because "*" pattern matches those log files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/806)

ut: speed up require_valgrind without arguments

---

src/libpmemobj/memblock.c
src/libpmemobj/memops.c
src/libpmemobj/memops.h
src/test/Makefile
src/test/obj_heap_interrupt/.gitignore
src/test/obj_heap_interrupt/Makefile
src/test/obj_heap_interrupt/TEST0
src/test/obj_heap_interrupt/obj_heap_interrupt.c
src/test/obj_memblock/obj_memblock.c

This patches addresses an issue in the way pfree handled coalescing of
chunks that, when interrupted at a specific moment, would result in an
inconsistent state of the persistent heap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/816)

obj: fix a pfree bug that could cause corruption

---

src/benchmarks/Makefile
src/benchmarks/map_bench.c
src/benchmarks/obj_locks.c

- Fixes broken makefile rules.
- Adds missing pthread.h includes.
- Fixes benchmarks refering to internal PMEM-locks definitions.
Ref: pmem/issues#174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/821)

bench: re-enable benchmarks compilation

---

src/libpmemobj/heap_layout.h
src/libpmemobj/pmalloc.c
src/test/pmempool_info/out14.log.match
src/test/tools/pmemspoil/spoil.c
src/tools/pmempool/info_obj.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/832)

obj: fix mismatch in alloc redo log size defines

---

src/test/RUNTESTS.ps1
src/test/blk_nblock/out0w.log.match

An error code change in pull request #836 resulted in different
output on the windows side requiring different match text.  Also
fix an issue where RUNTESTS.PS1 wouldn't stop on a timed out test.
Note: change was from EINVAL to EEXIST in util_header_create()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/838)

win: fix windows UT broken by recent error code change

---

src/test/blk_nblock/TEST0w.ps1
src/test/blk_nblock/TEST1.ps1
src/test/blk_nblock/TEST2w.ps1
src/test/blk_non_zero/TEST0.ps1
src/test/blk_non_zero/TEST1.ps1
src/test/blk_non_zero/TEST2.ps1
src/test/blk_non_zero/TEST3.ps1
src/test/blk_non_zero/TEST4.ps1
src/test/blk_non_zero/TEST5.ps1
src/test/blk_non_zero/TEST6.ps1
src/test/blk_non_zero/TEST7.ps1
src/test/blk_non_zero/TEST8.ps1
src/test/blk_non_zero/TEST9.ps1
src/test/unittest/unittest.ps1

Comment/code was incorrect for windows usage when it comes to
manual override of DIR and create_poolset() needed to be
updated to handle a windows path that included a drive letter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/839)

win: enable test directory override for unit tests

---

doc/libpmemobj.3

"Thread cancellation is not supported. The pool will never be corrupted because of canceled thread, but other threads may stall waiting on locks taken by that thread. If  application  wants  to  use pthread_cancel(2),  cancellation  must  be  disabled before calling libpmemobj APIs (see pthread_setcancelstate(2) with PTHREAD_CANCEL_DISABLE).  Deferring cancellation (pthread_setcanceltype with PTHREAD_CANCEL_DEFERRED) is not enough, because libpmemobj internally may call functions that are marked as cancellation points in POSIX API."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/841)

doc: document interaction with thread cancellation

---

src/libpmemobj/lane.c

Clang-3.8 issues a compilation warning->error on use of '!'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/844)

obj: fix compilation error

---

doc/libpmemblk.3
doc/libpmemlog.3

Removes not existing 'pmempool' option ('--from-set') from pool set
creation examples.
Ref: pmem/issues#169
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/850)

doc: fix pool set creation examples in man pages

---

src/libpmemblk/btt.c

https://github.com/torvalds/linux/blob/master/drivers/nvdimm/btt.c#L427
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/856)

blk: match BTT Flog initialization to Linux NVDIMM BTT Flog initialization

---

src/include/libpmemobj/persistent_ptr.hpp

Clarify that trying to use composition for polymorphic types in persistent_ptr
yields undefined behavior.
Refs pmem/issues#150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/858)

cpp: clarify polymorphism in persistent_ptr

---

src/include/libpmemobj/make_persistent_array_atomic.hpp
src/include/libpmemobj/make_persistent_atomic.hpp

State clearly, that using the atomic API inside transactions might yield
undefined behavior in the presence of transaction aborts.
Refs pmem/issues#170
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/859)

cpp: clarify make_persistent_atomic

---

src/libpmemobj/obj.c

Perform the same consistency check on master replica as in
pmemobj_check().  This way, it should not happen that pmemobj_open()
succeeds, while pmemobj_check() fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/852)

obj: check pool consistency in pmemobj_open()

---

src/include/libpmemobj.h

For example this code didn't compile:
struct { int field_name; } var; /* embedded in some pmem data structure */
TX_SET_DIRECT(&var, field_name, 12345);
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/867)

obj: fix macro parameter expansion issues

---

src/test/Makefile.inc
src/test/unittest/Makefile

USE_LIBUNWIND=0 disables detection
USE_LIBUNWIND=1 force enables libunwind (still needed by travis)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/877)

ut: automatically detect libunwind

---

src/examples/libpmemobj/cpp_map/ctree_map_persistent.hpp

This is not needed for correctness, because the field is only modified in the transaction the enclosing object was created in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/882)

cpp: add p<> to ctree example

---

doc/libpmem.3
src/common/cpu.c
src/common/cpu.h
src/libpmem/pmem.c
src/test/util_cpuid/util_cpuid.c

Since PCOMMIT is deprecated before ever being implemented in a CPU, the CPUID check will always return false and the code protected by that check will never be enabled.  There's no API change and this pull request simply removes dead code.
The only visible change to a programmer is the libpmem.3 man page, which no longer mentions PCOMMIT and no longer describes the debug environment variable PMEM_NO_PCOMMIT which forced the library to act as if PCOMMIT doesn't exist.  It will never exist now so that debug variable is no longer necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/889)

pmem: deprecate PCOMMIT

---

src/examples/libpmemobj/panaconda/panaconda.cpp
src/examples/libpmemobj/panaconda/panaconda.hpp

Generated by "make format".
panaconda does not follow common coding style because cstyle rules
were never checked against it (see 028bfdd9c81a1069c009f0443616757507015d05).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/892)

examples/panaconda: fix coding style

---

src/test/Makefile.inc
src/test/RUNTESTS

Fix parallel unit tests ('make pcheck') broken by commit 971d91.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/905)

test: fix 'make pcheck'

---

doc/libpmem.3
doc/libpmemblk.3
doc/libpmemlog.3
doc/libpmemobj.3
src/libpmem/pmem.c
src/test/pmem_is_pmem/TEST1
src/test/pmem_is_pmem/TEST2
src/test/pmem_is_pmem/TEST3
src/test/pmem_is_pmem/TEST4
src/test/pmem_is_pmem/TEST5
src/test/pmem_is_pmem/out0.log.match
src/test/pmem_is_pmem/out1.log.match
src/test/pmem_is_pmem/out2.log.match
src/test/pmem_is_pmem/out3.log.match
src/test/pmem_is_pmem/out4.log.match
src/test/pmem_is_pmem/out5.log.match
src/test/pmem_is_pmem/pmem_is_pmem.c

Query PMEM_IS_PMEM_FORCE environment variable on the first call to
pmem_is_pmem(), not at library load time.
Ref: pmem/issues#158
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/888)

pmem: defer pmem_is_pmem() initialization

---

src/benchmarks/perf.cfg
src/benchmarks/pmembench_tx.cfg
src/benchmarks/pmemobj_tx.c

- use type-number instead of type-num in benchmarks arguments
- increase number of repeats
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/913)

benchmarks: minor updates

---

src/include/libpmemobj/make_persistent_array_atomic.hpp
src/include/libpmemobj/make_persistent_atomic.hpp
src/test/obj_cpp_make_persistent_array_atomic/obj_cpp_make_persistent_array_atomic.cpp
src/test/obj_cpp_make_persistent_atomic/obj_cpp_make_persistent_atomic.cpp

Properly handle deletion of nullptr in the atomic allocation API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/914)

cpp: check for nullptr deletion in atomic API

---

src/test/Makefile

Caue all libpmempool_* unittests use libpmempool_test app build in libpmempool_api unittest directory we must add dependency to make parallel make possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/916)

lpp: fix Makefile dependencies

---

src/test/Makefile

$(TEST_DEPS) (unittest & tools) need to be built before $(LIBPMEMPOOL_DEPS)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/917)

test: fix parallel build

---

doc/cppobj.Doxyfile

The include path now shows `#include <libpmemobj/XXX.hpp>`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/929)

cpp: add include path to C++ documentation

---

src/Makefile.inc

The -Og flag makes it harder to debug the program when performing
instruction steps.
This reverts commit 19a0802f4f929ed8ef014f3f717b7db9b2dffc95.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/921)

common: do not use -Og for debug build

---

src/libpmemblk/btt.c

In btt_read() and btt_write(), when calculating the final data offset, the translation entry value and arena internal_lbasize are 32-bit, resulting in truncation when the offset is large followed by a read/write of the wrong offset.  Cast the entry value to uint64_t to avoid the truncation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/920)

pmemblk: cast translation entry to uint64_t when calculating data offset

---

src/tools/rpmemd/rpmemd_fip.c

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/943)

rpmem: fix use of uninitialized value issue

---

src/common/liblinux.vcxproj
src/common/liblinux.vcxproj.filters
src/libpmem/libpmem.def
src/libpmemblk/libpmemblk.vcxproj
src/libpmemblk/libpmemblk.vcxproj.filters
src/libpmemlog/libpmemlog.vcxproj
src/libpmemlog/libpmemlog.vcxproj.filters
src/libpmemobj/libpmemobj.vcxproj
src/libpmemobj/libpmemobj.vcxproj.filters

Windows implementation of mmap(), munmap(), msync() and mprotect() has
been moved to libpmem.
On Windows, those functions are exported by libpmem, making them available
for all the other NVM libraries. So, there is no need to link mmap_windows
unit to each NVM library or test program.
libpmem now holds the only instance of file mapping list, so it is able
to find the file handle associated with the address passed to
pmem_msync() and flush the data to persistence, regardless of which
library created the file mapping.
Note: This is a temporary solution - a subject for change in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/904)

win: move memory mapping routines to libpmem

---

src/test/obj_memcheck/TEST0
src/test/unittest/unittest.sh

Now obj_constructor test requires it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/948)

test: use Valgrind workaround for all tests

---

src/test/unittest/unittest.h

This workaround does not disable some asserts and forces them from
compile time to runtime.
Refs pmem/issues#189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/949)

cpp: workaround for gcc bug

---

doc/Makefile
src/Makefile
src/tools/rpmemd/Makefile
utils/build-dpkg.sh
utils/build-rpm.sh
utils/make-pkg-config.sh

Enable bulding librpmem and rpmemd packages as an experimental ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/957)

rpmem: build packages

---

src/rpmem_common/base64.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/971)

rpmem: fix conversion from 'int' to 'uint32_t'

---

utils/docker/images/Dockerfile.fedora-23
utils/docker/images/Dockerfile.ubuntu-16.04

Pandoc and doxygen packages are required for conversion of markdown into manual pages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/973)

common: pandoc and doxygen packages added to Docker images

---

Makefile
doc/Makefile
src/Makefile
src/Makefile.inc
src/common.inc
src/examples/librpmem/Makefile
src/librpmem/Makefile
src/test/rpmem_basic/Makefile
src/test/rpmem_fip/Makefile
src/test/tools/fip/Makefile
src/tools/rpmemd/Makefile
utils/build-dpkg.sh
utils/build-rpm.sh

Build librpmem and rpmemd packages only if libfabric is available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/986)

rpmem: fix building packages

---

src/test/obj_cpp_cond_var/obj_cpp_cond_var.cpp

Sporadically the 10ms tolerance wasn't enough. This issue with
timeouts on Windows will be investigated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/987)

win: adjust epsilon tolerance

---

src/libpmemobj/heap.c
src/libpmemobj/heap.h

The bucket index is usually represented by 8 byte unsigned variable whereas
the max bucket constant (and by extension the bucket array size) was
UINT8_MAX - 1. This was done to avoid problems with loops that used iters
of uint8_t type. In retrospect that caused more static analysis problems
than it avoided.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/994)

obj: increase max buckets by one to fill uint8_t range

---

src/libpmemobj/obj.c
src/libpmemobj/pmalloc.c
src/libpmemobj/tx.c
src/test/obj_persist_count/out0.log.match
src/test/obj_persist_count/out1.log.match

The allocation and OOB headers are currently created and persisted
separately even though they reside on the same 64 byte cacheline. This
patch removes the requirement of flushing OOB header data from the internal
constructors and combines the flushes into one call after both of the
object headers have been written.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1007)

obj: remove one redundant flush from atomic allocs API

---

src/test/.gitignore

The libs.tar files were visible in untracked files after
37bc8d98218fa68965bdc600b1628aff0f99f7ba.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1010)

common: update gitignore in tests

---

src/tools/rpmemd/rpmemd_config.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1011)

rpmem: fix casting type in parse_cl_args()

---

src/test/unittest/unittest.sh

- use PKG_CONFIG_PATH only if LD_LIBRARY_PATH is set
- use '=' instead of '+=' syntax
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1012)

common: fix setting PKG_CONFIG_PATH on remote node

---

src/libpmemobj/heap.c
src/libpmemobj/palloc.c
src/test/obj_out_of_memory/out0.log.match
src/test/obj_out_of_memory/out1.log.match
src/test/obj_pmalloc_basic/obj_pmalloc_basic.c
src/test/pmemobjcli/out0.log.match

The current default allocation classes result in duplicate buckets
supporting the same unit size because the bucket map for the class unit
size didn't point to the corresponding bucket. This patch addresses that
issue and also simplifies the related logic in a way that hopefully
makes it easier to reason about.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1005)

obj: simplify & optimize alloc class generation

---

.mailmap

From "git shortlog" man page:
"The .mailmap feature is used to coalesce together commits by
the same person in the shortlog, where their name and/or email
address was spelled differently."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/984)

common: add .mailmap

---

src/test/Makefile

The patch cleans up the main Makefile.
It splits tests into local and remote ones.
The 'obj_rpmem_basic_integration' unit test has not been run
during 'make pcheck' so far. The patch fixes this issue too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1022)

test: split tests into local and remote ones

---

utils/build-dpkg.sh
utils/build-rpm.sh
utils/docker/build.sh

Fix docker build script to pass the EXPERIMENTAL env variable.
Fix paths in package build scripts for C++ bindings.
Refs: pmem/issues#213
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1027)

common: fix build scripts

---

appveyor.yml
src/test/unittest/ut.c

Calling abort in our unit tests was causing appveyour build to hang -
build was waiting for pressing a button on abort message box...
This commit disables that message box.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1037)

win: disable abort msgbox on appveyor

---

src/test/Makefile
utils/build-dpkg.sh
utils/build-rpm.sh
utils/docker/prepare-for-build.sh
utils/docker/run-build-package.sh
utils/docker/run-build.sh

Times for configurations without Valgrind and remote tests decrease from 18 minutes to 15 minutes (16%).
Times for configurations with Valgrind and remote tests decrease from 40 minutes to 34 minutes (15%).
Total time decreases from 2h56m to 2h29m (15%).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1038)

Speed up tests on Travis by 15%

---

src/test/unittest/unittest.sh

Release libraries ignore *_LOG_FILE variables, so when test passes
in debug mode, but fails in release mode, it's easy to get confused
by looking at log file from previous run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1034)

ut: remove all log files in setup()

---

src/test/unittest/unittest.sh

It manifested during "make pcheck -jN" as eg:
find: './out2.log': No such file or directory
find: './err2.log': No such file or directory
find: './trace2.log': No such file or directory
RUNTESTS: stopping: util_map_proc/TEST3 failed, TEST=check FS=none BUILD=nondebug
(Note how TEST3 fails with errors which mention logs for TEST2)
http://git.savannah.gnu.org/cgit/findutils.git/commit/?h=rel-4-2-fixes&id=bfa4fbe01262070f1274c60110e44e2020108d75
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1042)

ut: workaround race in find

---

src/libpmemobj/tx.c
src/test/Makefile
src/test/obj_tx_mt/.gitignore
src/test/obj_tx_mt/Makefile
src/test/obj_tx_mt/TEST0
src/test/obj_tx_mt/TEST1
src/test/obj_tx_mt/obj_tx_mt.c

Originally fixed by 862263318de2c3d6befbb18e602f511c9b30d9ae (merged Feb 2016). 
Broken since ced2ce3cb2187143dc95a50930701d2f06b4ee52 (merged March 2016).
Now with tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1045)

obj: restore part of pmemcheck vs multi-threaded app fix

---

src/test/unittest/unittest.sh

Fix parallel test execution by removing find, which has a well-known
race condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1053)

test: substitute find in unittest.sh

---

src/test/blk_pool_lock/blk_pool_lock.c
src/test/log_pool_lock/log_pool_lock.c
src/windows/win_file.c

Let it set the same error code (errno) as on Linux.
If the file is already locked, errno should be set to EWOULDBLOCK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1056)

win: fix flock() implementation

---

utils/docker/images/Dockerfile.ubuntu-16.04

Adding it only to ubuntu, because the fedora used does not have the desired version of clang-format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1058)

docker: add clang-format to docker script

---

src/test/unittest/unittest.sh

"configure_valgrind" started to call "stat" utility, which is
affected by locale settings and "configure_valgrind" is called
before "setup", so we have to set locale earlier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1064)

ut: set locale earlier

---

src/libpmemobj/memblock.c
src/test/obj_memblock/obj_memblock.c

The size index of a run memory allocation is currently capped by
RUN_UNIT_MAX compile-time constant, which happens to be 8. This caused
a potential issue to creep into the algorithm. The issue could trigger
undefined behavior to present itself when the above mentioned constant
is changed to its edge value of 64.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1062)

obj: allow for memblocks /w size index equal to 64

---

src/libpmem/cpu.c
src/libpmem/cpu.h
src/libpmem/pmem.c
src/test/util_cpuid/util_cpuid.c

The CPU dispatching code checking for SSE2 is wrong,
and very misleading.
The code is either compiled using SSE2 instructions - in which
case, such instructions might end up in other places in the binary -
or compiled without such instructions, in which case the
_mm_stream_si128 identifier is not present, thus doesn't compile.
The right way to do such CPU feature based dispatching is to
place appropriate code segments in different translation units,
compiled with appropriate flags e.g. -msse2
and to conditionally call such code from translation units compiled
with some least common denominator platform in mind.
The code not using movnt is left in the code, to available via
an environment variable, as before.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Use movnt by default

---

src/common/set.c

According to ISO:
"the argument is an int, the value of which shall be representable
as an unsigned char or shall equal the value of the macro EOF."
Thus a negative char value supplied to isblank ( except EOF ) is undefined
behaviour. E.g. the implementation might use a lookup table, in which
case a negative index can result in a crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1068)

common: fix isblank usage in set.c

---

src/benchmarks/pmembench.c

In case of odd nresults use the middle element.
In case of even nresults use the two middle elements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1071)

benchmark: fix result time calculation

---

src/common/util.h
src/libpmem/pmem.c
src/libpmemobj/heap.c
src/libpmemobj/lane.c
src/libpmemobj/sync.c
src/windows/include/platform.h

Add wrapper macros for 32- and 64-bit variant of CAS intrinsics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1072)

win: fix warning in __sync_bool_compare_and_swap

---

doc/libpmemobj.3.md

Fix the signature of memcpy().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1088)

doc: fix typo in man page example

---

src/include/libpmempool.h

The <sys/types.h> include is required to use size_t type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1134)

libpmempool: add missing include

---

src/test/Makefile

Parallel build sometimes fails with errors like:
cc: obj_basic_integration.o: No such file or directory
obj_basic_integration.o: file not recognized: File truncated
Reported by krzycz.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1138)

test: add explicit dependencies between obj_rpmem* and obj_*

---

src/include/libpmemobj++/condition_variable.hpp
src/test/obj_cpp_cond_var/obj_cpp_cond_var.cpp
src/test/obj_cpp_cond_var_posix/obj_cpp_cond_var_posix.cpp

Fix wait_for to work with locks in condition_variable.hpp . Fix tests that did not checked locks (obj_cpp_con_var and obj_cpp_con_var_posix).
Refs: pmem/issues#225
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1144)

cpp: fix condition_variable

---

src/libpmemobj/list.c
src/libpmemobj/obj.c
src/test/obj_list_macro/obj_list_macro.c

... pmemobj_list_move() and pmemobj_list_remove().
On failure, these functions should return -1, not errno.
Ref: pmem/issues#226
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1155)

obj: fix status returned by pmemobj_list_insert()

---

_layouts/manual.html
css/pmem.css
js/nvml_formatter.js

Add a javascript code highlighting NVML defined types on HTML pages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1170)

doc: highlight NVML types

---

utils/docker/images/install-valgrind.sh

Currently pmem branch in our Valgrind repository contains both Valgrind
and VEX, while upstream have it separated.
We are going to follow upstream on this soon (and have per-version
branches with full history), so prepare our docker scripts to download
both Valgrind and VEX submodule.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1181)

common: prepare for submodule-based Valgrind repo

---

src/tools/rpmemd/rpmemd.c

Rpmem handle 'rpmemd' should be freed at the end.
Reorder function calls like in the error handling path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1189)

rpmemd: fix dereferencing freed pointer

---

doc/rpmemd.1.md
src/test/rpmem_basic/TEST5
src/test/rpmem_basic/node_1_out5.log.match
src/test/rpmemd_config/stdout0.log.match
src/tools/rpmemd/rpmemd.c
src/tools/rpmemd/rpmemd_config.c
src/tools/rpmemd/rpmemd_config.h

Make it possible to remove pool using rpmemd. The benefit of doing this
by rpmemd is that it parses config file and command line arguments
which can set the poolset-dir option. Thus it is possible to remove
pool using the same pool descriptor as for rpmem API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1187)

rpmemd: add removing pool functionality

---

src/examples/libpmemobj/tree_map/ctree_map.c

Check if node is OID_NULL before checking the type number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1197)

obj: fix clearing ctree map

---

src/test/RUNTESTS.ps1

Changed FAILED to TIMED OUT error msg in case of a RUNTEST.ps1 timeout
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1201)

win: RUNTEST.ps1 add missing timeout msg

---

src/examples/libpmemobj/cpp/queue.cpp
src/examples/libpmemobj/cpp_map/ctree_map_persistent.hpp
src/examples/libpmemobj/cpp_map/ctree_map_transient.hpp
src/examples/libpmemobj/list.hpp

Add const qualifiers to non modifying methods in C++ examples.
Refs: pmem/issues#232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1211)

cpp: fix const correctness in examples

---

src/test/obj_rpmem_basic_integration/TEST4
src/test/obj_rpmem_basic_integration/TEST8

Redirect stderr in obj_rpmem_basic_integration/TEST4 and TEST8 to a file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1215)

test: redirect stderr in two unit tests

---

src/libpmemobj/obj.c
src/test/obj_pool_lookup/obj_pool_lookup.c

Add check for uninitialized global structures before first pool open
in `pmemobj_pool_by_ptr` and `pmemobj_pool_by_oid`. Introduced by
fb7cd8761ca51cfbbefcf33fba237c8ef95c42dc.
Refs: pmem/issues#238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1218)

obj: fix possible NULL dereference

---

utils/build-rpm.sh

A temporary workaround for RPM's build issue on RedHat.
Since there is no pandoc package available, rpm build fails on pandoc
dependency, even if pandoc is actually installed (from source).

common: remove pandoc dependency from spec

---

src/common/pool_hdr.c
src/common/pool_hdr.h
src/common/set.c

...that does not validate the major number
when opening a remote replica.
Ref: pmem/issues#279
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1229)

common: add util_convert_hdr_remote

---

src/benchmarks/Makefile
src/benchmarks/pmembench.c
src/common/set.c
src/common/set.h
src/librpmem/rpmem.c
src/librpmem/rpmem_ssh.c
src/librpmem/rpmem_ssh.h
src/test/util_poolset_foreach/TEST1
src/test/util_poolset_foreach/out1.log.match
src/test/util_poolset_foreach/util_poolset_foreach.c
src/tools/pmempool/rm.c

Add support for removing remote pools in pmembench. This is required to run any scenario with pool set file configured with remote replication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1193)

benchmarks: support for removing remote pools

---

src/common.inc
src/test/Makefile
src/test/Makefile.inc
src/test/RUNTESTS
utils/docker/configure-tests.sh
utils/docker/run-build.sh

Speed up travis builds by running tests on debug
and nondebug builds in 3 of 6 jobs and by forcing running
remote tests on sockets provider.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1232)

common: speed up travis

---

src/test/obj_pmalloc_mt/obj_pmalloc_mt.c

It's marked as "long", so it's not executed on each pull request.
It fails because framework detects resource leak:
{ut.c:254 open_file_remove} obj_pmalloc_mt/TEST0: unexpected open file: fd 9 => "/tmp/nvml-qa/test_obj_pmalloc_mt0/testfile"
{ut.c:373 check_open_files} obj_pmalloc_mt/TEST0: Error: open file list changed between START() and DONE()
The other reason it fails is much deeper (helgrind finds some races)
and needs to be investigated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1261)

test: fix one reason why obj_pmalloc_mt test fails

---

src/test/pmempool_sync/TEST5

Use 'stat -c %A <file>' instead of 'ls -l <file> | cut -f1 -d' ' '
because there can be one additional character ('.' or '+')
following the file mode bits (specifing whether an alternate
access method such as an access control list (ACL) applies to the file)
and in such case the 'out5.log.match' file does not match.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1273)

test: fix pmempool_sync/TEST5

---

src/common/set.c
src/common/set.h
src/libpmempool/pool.c
src/test/rpmem_basic/rpmem_basic.c
src/tools/pmempool/common.c
src/tools/rpmemd/rpmemd_db.c

Prevent from opening poolset if it contains remote replicas.
fixes pmem/issues#290
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1266)

libpmempool: do not open poolsets with remote replicas

---

src/libpmempool/check_btt_map_flog.c
src/test/libpmempool_map_flog/out2.log.match

After write map[lba] == flog_entry.new_map. But map[lba] can be altered by
following writes to the same lba.
fixes pmem/issues#283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1274)

libpmempool: do not assume new_map must be in map

---

src/libpmemobj/heap.c

The free code path includes a coalescing step that searches for the
neighbouring blocks by traversing the on-media layout and than it verified
the ownership of the block by looking it up in the bucket tree. Due to the
fact that the lock during that process is the bucket lock, the layout was
left unprotected. In general that algorithm was correct but it produced
errors in helgrind, so for correctness sake from now on the on-media layout
is protected by the default bucket lock. This should have minimal impact
on scaling but will ensure that the thread error detecting tools will be
happy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1283)

obj: fix benign race in the huge chunk free logic

---

doc/libpmempool.3.md
doc/pmempool-check.1.md
doc/pmempool-convert.1.md
doc/pmempool-sync.1.md
doc/pmempool-transform.1.md

Add missing references to libpmempool and add information about lack
of support for remote replicas.
fixes pmem/issues#290
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1294)

doc: pmempool does not support remote replicas

---

src/libpmempool/check_pool_hdr.c

Check pool_hdr checksum after fixes to quit checks as soon as
possible. Otherwise check assume consecutive pool_hdr fields are
invalid and trying fixing them may run into dead end despite those
fields can be totally good.
fixes pmem/issues#243
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1281)

libpmempool: check pool_hdr checksum after fixes

---

src/libpmemobj/obj.c
src/test/pmempool_transform/TEST4
src/test/pmempool_transform/out4.log.match

Ref: pmem/issues#261
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1319)

pmempool: fixes incorrect obj poolset size

---

src/test/obj_tx_callbacks/obj_tx_callbacks.c

Old versions of clang optimize away TX_ALLOC with void cast.
Just save its value to root->obj.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1323)

test: workaround clang bug

---

src/test/obj_pmalloc_mt/obj_pmalloc_mt.c

This test had narrowly calculated pool size that did not account for
metadata nor the per-thread allocator caches, which manifested itself as
sporadic fails in environments with high number of CPUs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1324)

obj: increase the pool size for pmalloc_mt test

---

src/libpmemblk/blk.c

The locks will never be allocated in the err label, hence no need to
free them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1329)

blk: remove dead code

---

src/test/RUNTESTS.ps1

1. Fixed broken ifs
2. -h | -help should now print usage
3. removed unused command line parameter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1331)

win: RUNTESTS.PS1 cleanup

---

src/common.inc
src/examples/librpmem/Makefile
src/librpmem/Makefile
src/tools/rpmemd/Makefile

Detect libibverbs availability by compilation minimal program with
ibverbs API. The fi_info turned out to be too slow in some cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1328)

rpmem: fix detecting libibverbs

---

doc/libpmem.3.md
src/libpmem/pmem.c

The PMEM_NO_FLUSH=1 environment variable can be used to force not
flushing the CPU cache. This variable is intended for library testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1334)

pmem: add flag for not flushing CPU cache

---

src/libpmemobj/heap.c
src/libpmemobj/heap.h
src/libpmemobj/memblock.c
src/libpmemobj/memblock.h
src/libpmemobj/palloc.c
src/test/obj_heap/obj_heap.c
src/test/obj_memblock/obj_memblock.c

This patch reduces the number of locks acquired and released in the
duration of the palloc_operation function and also removes the recursive
attribute from the run locks. This also fixes a very rare race in which
threads freeing blocks from the same run tried to concurrently degrade
the same run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1342)

obj: simplify palloc locking scheme

---

src/test/unittest/unittest.sh
src/test/vmmalloc_valgrind/TEST1
src/test/vmmalloc_valgrind/TEST2

From Valgrind 3.12 release notes (http://valgrind.org/docs/manual/dist.news.html):
- Replacement/wrapping of malloc/new related functions is now done not just
for system libraries by default, but for any globally defined malloc/new
related function (both in shared libraries and statically linked alternative
malloc implementations).  The dynamic (runtime) linker is excluded, though.
To only intercept malloc/new related functions in
system libraries use --soname-synonyms=somalloc=nouserintercepts (where
"nouserintercepts" can be any non-existing library name).
This new functionality is not implemented for MacOS X.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1346)

test: add support for Valgrind 3.12

---

src/libpmemobj/heap.h
src/libpmemobj/memblock.h
src/libpmemobj/obj.c
src/libpmemobj/palloc.c
src/libpmemobj/palloc.h

pmalloc is an outer layer of the real allocator (palloc + heap + bucket + memblock).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1373)

obj: don't include pmalloc.h from heap.h and memblock.h

---

src/test/unittest/unittest.sh

It was failing with this message:
../unittest/unittest.sh: line 533: return: g: numeric argument required
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1374)

test: fix TRACE support

---

src/include/libpmemobj++/README.md

C++ static class members are not held in persistent memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1375)

doc: add note on static class members

---

src/libpmemobj/memblock.c

Currently each used or free huge chunk with size index
larger than two has multiple unused headers in the
metadata. Those headers can be sometimes read from the
queue of unused runs to verify if those runs are still
valid. This patch removes the instrumentation that
marked those headers as undefined.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1390)

obj: fix overzealous vg instrumentation of chunk hdrs

---

src/common/pool_hdr_windows.c

Make sure that CPU-specific arch flags in the pool header have
the same values on each OS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1394)

win: arch flags compatibility

---

src/libpmemobj/heap.c
src/libpmemobj/heap.h
src/libpmemobj/obj.c
src/libpmemobj/obj.h
src/libpmemobj/palloc.c
src/libpmemobj/palloc.h
src/libpmemobj/pmalloc.c
src/test/obj_heap/obj_heap.c
src/test/obj_pmalloc_basic/obj_pmalloc_basic.c

The original problem was that if root object was allocated from chunks
(huge allocation) the memcheck reported errors:
Conditional jump or move depends on uninitialised value(s)
in pmemobj_vg_boot() function, because the root object's size was
accessed before registering it's header to valgrind.
This issue doesn't reproduce if root object is allocated from run
because the entire run space was registered as defined in valgrind -
which is wrong because only allocated objects with its headers should
be registered as defined.
The problem also applies to normal objects, because the loop which
registers the objects to valgrind was touching object's headers which
are not registered yet.
This patch fixes above issues by registering allocated objects during
booting the heap and at the same time …

obj: fix memcheck instrumentation

---

src/windows/srcversion/srcversion.vcxproj

fixed an issue when building solution fails if it is located in path
including whitespace
Ref: pmem/issues#322
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1405)

win: fix srcversion project

---

doc/Makefile

Normal dependencies sometimes did not force a rebuild on fresh
checkouts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1407)

doc: force doc rebuild

---

src/test/util_poolset/TEST0
src/test/util_poolset/TEST1

In 61d6bb2c3783f9be51710320c3b21e998078bfc6 resolving symbolic links in
create_poolset function has been removed, but util_poolset/TEST{0,1}
assumed they are resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1421)

common: fix mocking in util_poolset test

---

src/libpmem/pmem.c
src/test/pmem_map/TEST2

Don't know why would anyone ever do this on purpose, but might be useful for cross-compatible stuff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1414)

pmem: fix dev dax map /w create flag and non-zero size

---

doc/libpmemblk.3.md
doc/libpmemlog.3.md
doc/libpmemobj.3.md
src/common/set.c
src/test/obj_basic_integration/obj_basic_integration.c
src/tools/pmempool/info.c
src/tools/pmempool/output.c

Individual libraries API depend on being able to create a private
mapping of the pool, which is sadly impossible for device dax.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1417)

common: disable pmemxxx_check() function for device dax

---

utils/pkg-common.sh

When cloning with a limited depth, the git describe does not include the last
tag version. Fix by adding an artificial 0.0 source version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1426)

pkg: fix git describe matching

---

src/librpmem/rpmem.c
src/librpmem/rpmem_ssh.c

When closing the out-of-band connection the monitor thread was
receiving close request response message and reported an error.
This patch disables printing this error if closing the connection.
Ref: pmem/issues#346
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1428)

rpmem: do not print 'unexpected data received' log

---

src/common/file.c
src/common/set.c

Fixes two following valgrind's issues (found by
the obj_rpmem_basic_integration/TEST9 unit test):
==24880== Syscall param stat(file_name) points to unaddressable byte(s)
==24880==    at 0x5BB82F5: _xstat (xstat.c:37)
==24880==    by 0x504D05B: util_file_is_device_dax (file.c:117)
==24880==    by 0x50526CB: util_parse_add_part (set.c:742)
==24880==    by 0x5052CC3: util_parse_add_remote_replica (set.c:853)
==24880==    by 0x50531DF: util_poolset_parse (set.c:989)
==24880==    by 0x5054244: util_poolset_create_set (set.c:1432)
==24880==    by 0x5056591: util_pool_create_uuids (set.c:2034)
==24880==    by 0x5056B0C: util_pool_create (set.c:2164)
==24880==    by 0x5069C47: pmemobj_create (obj.c:1061)
==24880==    by 0x406A6A: main (obj_basic_integration.c:589)
==24880==  Address 0x0 is not …

common: fix two valgrind issues

---

src/libpmempool/pool.c
src/tools/pmempool/common.c
src/tools/pmempool/info.c

This is a workaround for a kernel issue in which an mprotect with len
not aligned to page boundry causes a SIGBUS on the next page fault with a
"__dax_dev_pmd_fault: fail, unaligned vma" message. This caused issues
with poolsets that had non-dax replicas with sizes that weren't aligned
to the dax replica page size - that was the case of pmempool_sync/TEST7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1433)

pmempool: use master replica size for mprotect

---

doc/Makefile

This patch f66c711ecdf5404d4fc034ee77303675e0aeeb69 introcuced forcing
generating of manpages. This resulted in having a dependency on pandoc
again because the 'make install' depends on documentation and manapges
were generated always. This patch changes the behavior so the generating
manpages is done only explicitly by calling 'make doc' from top
directory or 'make' inside doc directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1473)

doc: change behavior of generating manpages

---

src/common/file.c

Use <sys/sysmacros.h> for makedev(), major() and minor() decls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1474)

common: fix compilation warning/error on Fedora 26

---

src/test/obj_pmalloc_mt/TEST0
src/test/obj_pmalloc_mt/helgrind_adjacent_block.supp

This is an on-purpose race that has no negative effects. In happens during
a free of a huge block, when the algorithm tries to coalesce the block with
its free neighbours. The blocks are first identified in the persistent
layout without grabing a lock and then they are retrieved from a protected
container - this ensures that the block is correct. Even if the data that
was read is stale or invalid, nothing bad can happen - the chunk that is
being freed simply won't get coalesced.
This is a temporary solution to pmem/issues#342
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1485)

test: suppress helgrind issues /w adjacent blocks

---

src/test/obj_out_of_memory/TEST2
src/test/obj_out_of_memory/TEST2.PS1

The old pool size was unreasonable...
The next largest pool size currently is 2GB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1479)

test: reduce the pool size of oom test to 2GB from 20GB

---

src/benchmarks/obj_locks.c
src/include/libpmemobj/thread.h
src/libpmemobj/pmalloc.c
src/libpmemobj/sync.h
src/libpmemobj/tx.c

The name _POBJ_CL_ALIGNMENT was very confusing,
as it is never used to sepcify alignment. It is always
used to specify size, and is compared with results of
sizeof(), not with results of alignof().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1471)

obj: Rename the macro specifying lock sizes

---

src/test/tools/pmemdetect/pmemdetect.c

Pmemdetect has not recognized DAX device so far.
Correct return value of is_dev_dax() to fix that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1524)

test: tools: make pmemdetect recognize DAX device

---

src/test/blk_rw_mt/TEST2
src/test/blk_rw_mt/TEST2.PS1
src/test/obj_many_size_allocs/TEST0
src/test/obj_many_size_allocs/TEST0.PS1
src/test/obj_many_size_allocs/TEST1
src/test/obj_many_size_allocs/TEST1.PS1
src/test/obj_many_size_allocs/TEST2
src/test/obj_many_size_allocs/TEST2.PS1
src/test/obj_many_size_allocs/TEST3
src/test/obj_many_size_allocs/TEST3.PS1

The two changed tests generate huge logs. Change the default log level
to 2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1507)

test: change log level for some tests

---

src/libpmempool/pool.c

This change is required on account of DAX devices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1531)

pmempool: fix mapping type in pool_params_parse

---

src/test/unittest/unittest.sh

Output of pmemdetect is not printed, beacuse of usage
of run_command(). It looks like this:
obj_rpmem_basic_integration/TEST12: SKIP NODE 0:
Remove run_command() so that output of pmemdetect was printed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1523)

test: fix require_dev_dax_node()

---

.travis.yml
README.md

The new travis.yml introduces a new entry/job in the build matrix to
trigger the Coverity Scan build for static code analysis.
The "COVERITY" job is executed only if the build is made from
"coverity_scan" branch and skipped (early exit) otherwise.
On the other hand, the normal build jobs are skipped for "coverity_scan"
branch.
Thanks to that, we can have a single travis.yml file on all the branches
and simply push the code from "master" to "coverity_scan" periodically
(i.e. daily) to trigger Coverity scans.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1475)

common: integrate Coverity scans with Travis

---

src/libpmemobj/pvector.c
src/test/obj_tx_free/obj_tx_free.c

For small tx undo logs, the vector structure usesan embedded array that is
located in lane, if the undo log needs to grow beyond the initial size it
allocates an array from a heap. The issue was that the lanes are added
to the pmemcheck tx ignore list whereas the heap allocations must be
manually added to the transaction to suppress the pmemcheck warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1509)

obj: fix pmemcheck for large free undo logs

---

src/benchmarks/benchmark.hpp
src/benchmarks/benchmark_time.cpp
src/benchmarks/benchmark_time.hpp
src/benchmarks/benchmark_worker.cpp
src/benchmarks/blk.cpp
src/benchmarks/clo.cpp
src/benchmarks/clo_vec.cpp
src/benchmarks/clo_vec.hpp
src/benchmarks/config_reader.cpp
src/benchmarks/config_reader_win.cpp
src/benchmarks/log.cpp
src/benchmarks/map_bench.cpp
src/benchmarks/obj_lanes.cpp
src/benchmarks/obj_locks.cpp
src/benchmarks/obj_pmalloc.cpp
src/benchmarks/pmem_flush.cpp
src/benchmarks/pmem_memcpy.cpp
src/benchmarks/pmem_memset.cpp
src/benchmarks/pmembench.cpp
src/benchmarks/pmemobj_atomic_lists.cpp
src/benchmarks/pmemobj_gen.cpp
src/benchmarks/pmemobj_persist.cpp
src/benchmarks/pmemobj_tx.cpp
src/benchmarks/rpmem_persist.cpp
src/benchmarks/scenario.cpp
src/benchmarks/scenario.hpp
src/benchmarks/vmem.cpp

Use proper C++ includes since benchmarks are compiled as C++.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1549)

benchmark: use C++ includes

---

src/test/obj_sync/TEST8
src/test/obj_sync/TEST8.PS1
src/test/obj_sync/TEST9
src/test/obj_sync/TEST9.PS1
src/test/obj_sync/obj_sync.c

Wrong cleanup routine caused a reinitialization of one mutex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1552)

obj: fix obj_sync test

---

src/benchmarks/Makefile
src/benchmarks/pmemobj_atomic_lists.cpp

There is nothing in benchmark code that requires C++11.
Also, it appears like '-std=c++11' is not supported by the current
version of Coverity Scan Analysis Tool that is integrated with TravisCI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1561)

benchmark: do not use '-std=c++11'

---

src/libpmemobj/obj.c
src/libpmemobj/obj.h
src/libpmemobj/tx.c
src/test/obj_persist_count/out0.log.match
src/test/obj_persist_count/out1.log.match
src/test/pmempool_info/out12.log.match
src/test/pmempool_info/out13.log.match
src/test/pmempool_info/out14.log.match
src/test/pmempool_info/out15.log.match
src/tools/pmempool/info_obj.c

First patch from the series related to pmem/issues#347
Lots of code removed and even a tiny performance gain /w transactional allocations - their performance is now on par with atomic allocations ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1435)

obj: remove now unecessery tx_free optimization

---

utils/docker/images/Dockerfile.fedora-23
utils/docker/images/Dockerfile.ubuntu-16.04
utils/docker/images/install-libcxx.sh

Our docker images build and install packages as root and run tests
as nvmluser. Change install dir to /var/install to enable all users
to use the custom libcxx.
Add cmake to docker images to build libcxx.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1571)

travis: fix path issues in script

---

utils/docker/build.sh
utils/docker/pull-or-rebuild-image.sh
utils/docker/run-coverity.sh

Make use of new Travis feature and trigger daily Coverity scans
on 'master' branch using 'cron' builds.
The 'coverity_scan' branch is not needed anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1572)

common: run Coverity scan builds via 'cron'

---

utils/docker/configure-tests.sh
utils/docker/run-build.sh

The test for valgrind support compiled into our libraries needs
statically linkied binaries. Enable build and disable running tests
to save time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1577)

docker: fix valgrind tests under docker

---

src/include/libpmemobj++/allocator.hpp

Wrong pointer type in unused parameters of allocate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1581)

cpp: fix wrong pointer type in the allocator

---

src/librpmem/rpmem_fip.c

Read the maximum message size from endpoint's attributes and respect
this in rpmem_persist function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1592)

rpmem: limit the message size to maximum

---

src/include/libpmemobj++/detail/persistent_ptr_base.hpp
src/include/libpmemobj++/p.hpp
src/include/libpmemobj++/persistent_ptr.hpp
src/test/obj_cpp_p_ext/TEST1
src/test/obj_cpp_p_ext/obj_cpp_p_ext.cpp
src/test/obj_cpp_ptr/TEST1
src/test/obj_cpp_ptr/obj_cpp_ptr.cpp

The swap implementation for both p<> and persistent_ptr<> was incorrect
in terms of powerfail safety. After these changes swap for both classes
may throw an exception. The C++ [swappable.requirements] does not specify
that a user defined swap be noexcept.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1595)

cpp: fix swap implementation

---

src/libpmemobj/libpmemobj.map

pmemobj_direct is only declared as static inline in headers,
it is not a public symbol.
See also:
nm src/nondebug/libpmemobj/libpmemobj_unscoped.o | grep direct
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1608)

obj: remove pmemobj_direct from libpmemobj.map

---

utils/docker/build.sh
utils/docker/pull-or-rebuild-image.sh
utils/docker/run-coverity.sh

This allows users to run Coverity scans on their own forks just by pushing to 'coverity_scan' branch.
Users have to define COVERITY_SCAN_NOTIFICATION_EMAIL and COVERITY_SCAN_TOKEN in their project's settings on Travis. For details see https://scan.coverity.com/travis_ci.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1607)

common: allow coverity scans on Travis without a cron

---

src/benchmarks/pmemobj_tx.cpp
src/examples/libpmemobj/hashmap/hashmap_tx.c

Returning from ONABORT section does not close the surrounding transaction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1576)

examples/benchmarks: properly end the transaction on abort

---

src/libpmemobj/heap.c

This is covered by a long test in obj_recovery.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1626)

obj: fix heap memcheck instrumentation

---

src/test/obj_sync/TEST0
src/test/obj_sync/TEST0.PS1
src/test/obj_sync/TEST1
src/test/obj_sync/TEST1.PS1
src/test/obj_sync/TEST2
src/test/obj_sync/TEST2.PS1
src/test/obj_sync/TEST3
src/test/obj_sync/TEST3.PS1
src/test/obj_sync/TEST4
src/test/obj_sync/TEST4.PS1
src/test/obj_sync/TEST5
src/test/obj_sync/TEST5.PS1
src/test/obj_sync/TEST6
src/test/obj_sync/TEST6.PS1
src/test/obj_sync/TEST7
src/test/obj_sync/TEST7.PS1
src/test/obj_sync/TEST8
src/test/obj_sync/TEST8.PS1
src/test/obj_sync/TEST9
src/test/obj_sync/TEST9.PS1
src/test/obj_sync/obj_sync.c

The test sporadically triggered the cgroup/pids.max limit which caused the
pthread_create to fail. This change limits the number of threads spawned in
succesion and makes them run longer. This way the test does not behave like
a fork bomb and should not trigger the cgroup limit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1630)

obj: fix obj_sync cgroup/pids trigger

---

utils/check_license/check-license.c

Using a GNU extension is not necessery for the ERROR
macro in check-license.c
error: named variadic macros are a GNU extension
error: token pasting of ',' and __VA_ARGS__ is a GNU extension
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1636)

common: check-license remove named variadic macro

---

Makefile
utils/check_license/check-headers.sh

This is useful for the case of using this script while
doing out of source builds.
Also, print errors to stderr.

common: check-headers.sh -- path arguments

---

utils/cstyle

Use an escaped version of character #1 in the
script, used as placeholder for comment sections
in the parsed C source file input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1642)

common: cstyle script - make it printible

---

src/libpmemblk/blk.c
src/libpmemblk/btt.c

For the case where clang issues a warning about
'long long' vs. 'long'.
Both are 64 bit in System V ABI, but still, clang warns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1649)

blk: Fix some format strings

---

src/libpmemobj/lane.c
src/libpmemobj/list.c
src/libpmemobj/obj.c
src/libpmemobj/redo.c
src/libpmemobj/sync.c

To avoid clang's -Wformat warnings.
This doesn't manifest itself with GNU libc, as uintmax_t,
uint64_t, size_t all are typedef-ed to 'long long'.
But Darwin libc uses both 'long' and 'long long', I don't
know why.

obj: Fix format specifiers

---

src/libpmemobj/sync.c

Managed to build libpmemobj with incosistent PMEMmutex
and PMEMrwlock types. This basic error should definitely be
caught compile time, not just in obj_layout tests.
Ref: pmem/issues#427
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1653)

obj: Add a few more compiler time assertions

---

src/test/Makefile

make test does NOT depend on make sync-remote.
make sync-remote depends on make test.
make check-remote depends on make sync-remote.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1657)

common: fix make test and make sync-remote issue

---

src/common/out.h

... reported by Coverity for nondebug build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1656)

common: suppress errors after ASSERT* macros

---

src/tools/rpmemd/rpmemd_config.c

It shouldn't have any visible effect, because memset internally
truncates higher 24-bits.
Reported by Coverity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1655)

tools: use byte value for memset fill argument in rpmemd

---

src/test/match

(Keeping the script in sync with other projects using the same script)
The output log and the match file don't have
to be in the same directory.
This helps while using the match script in
out of source builds. E.g.:
$(SRC)/match -o $(BUILD)/output_log $(SRC)/matchfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1658)

test: new argument to match script

---

src/test/obj_sync/obj_sync.c

On the odd case the tv_nsec=10e9, the timedlock fails with EINVAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1660)

test: fix sync timeout calculation

---

src/libpmempool/check_pool_hdr.c
src/libpmempool/check_util.h
src/test/pmempool_check/TEST19
src/test/pmempool_check/TEST19.PS1
src/test/pmempool_check/out19.log.match

If other part in replica has valid pool header it is possible to use it to
validate arch_flags. arch_flags in all parts of the replica should be equal.
Ref: pmem/issues#387
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1659)

pool: add arch_flags check

---

src/test/rpmemd_config/TEST0

Ref: pmem/issues#383
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1662)

test: do not use default rpmemd config location

---

utils/make-pkg-config.sh

From pkg-config documentation:
"Requires and Requires.private define other modules needed by the
library. It is usually preferred to use the private variant of Requires
to avoid exposing unnecessary libraries to the program that is linking
with your library. If the program will not be using the symbols of the
required library, it should not be linking directly to that library.
(...)
Since pkg-config always exposes the link flags of the Requires
libraries, these modules will become direct dependencies of the
program. On the other hand, libraries from Requires.private will only
be included when static linking. For this reason, it is usually only
appropriate to add modules from the same package in Requires."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

common: fix pkg-config files

---

src/test/obj_cpp_deque/TEST0
src/test/obj_cpp_deque/TEST1
src/test/obj_cpp_list/TEST0
src/test/obj_cpp_list/TEST1
src/test/obj_cpp_map/TEST0
src/test/obj_cpp_map/TEST1
src/test/obj_cpp_multimap/TEST0
src/test/obj_cpp_multimap/TEST1
src/test/obj_cpp_multiset/TEST0
src/test/obj_cpp_multiset/TEST1
src/test/obj_cpp_queue/TEST0
src/test/obj_cpp_queue/TEST1
src/test/obj_cpp_set/TEST0
src/test/obj_cpp_set/TEST1
src/test/obj_cpp_stack/TEST0
src/test/obj_cpp_stack/TEST1
src/test/obj_cpp_unordered_map/TEST0
src/test/obj_cpp_unordered_map/TEST1
src/test/obj_cpp_unordered_multimap/TEST0
src/test/obj_cpp_unordered_multimap/TEST1
src/test/obj_cpp_unordered_multiset/TEST0
src/test/obj_cpp_unordered_multiset/TEST1
src/test/obj_cpp_unordered_set/TEST0
src/test/obj_cpp_unordered_set/TEST1
src/test/obj_cpp_vector/TEST0
src/test/obj_cpp_vector/TEST1

All container tests shall require the binary to be present as
their compilation is conditional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1684)

cpp: add conditional test execution for containers

---

utils/docker/images/install-libfabric.sh
utils/docker/images/install-valgrind.sh

That's 500MB in uncompressed image...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1699)

common: actually remove Valgrind and libfabric sources

---

src/libpmemobj/bucket.c
src/libpmemobj/heap.c

It's a third attempt at fixing helgrind, but this patch ultimately gets rid
of all the false positives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1695)

obj: add instrumentation to all instances of new chunks

---

src/Makefile.inc
utils/build-dpkg.sh
utils/build-rpm.sh

If user installs NVML to $HOME and try to build his application using
pmemobj the linking phase fails, because of missing path to libpmem.
Solve it by setting runtime path of the directory with libpmem for all
libraries.
In general use of rpath is discouraged for distro packages, so disable
it for both Debian and Fedora packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1706)

common: use rpath when linking libraries

---

src/test/unittest/unittest.sh

Export host UNITTEST_DO_NOT_CHECK_OPEN_FILES variable to remote nodes,
which allows to control this behavior over testconfig.sh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1719)

test: export some host variables to remote nodes

---

src/test/magic/TEST0
src/test/obj_list_recovery/TEST0
src/test/obj_list_recovery/TEST1
src/test/obj_list_recovery/TEST2
src/test/pmempool_check/TEST11
src/test/pmempool_check/TEST12
src/test/pmempool_check/TEST13
src/test/pmempool_check/TEST14
src/test/pmempool_check/TEST5
src/test/unittest/unittest.sh
src/test/vmmalloc_init/TEST16
src/test/vmmalloc_init/TEST6

Some tests require to specify binary explicitly in order to properly
detect if valgrind support was enabled.
Ref: pmem/issues#488
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1724)

test: fix skipping tests under Valgrind tools

---

src/test/RUNTESTS
src/test/RUNTESTS.ps1
src/test/unittest/unittest.ps1
src/test/unittest/unittest.sh

Fix running tests requiring fs type to be any and forcing a specific fs
through RUNTESTS.
Ref: pmem/issues#468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1712)

test: fix require_fs_type any and RUNTESTS -f

---

src/test/vmem_stats/TEST0
src/test/vmem_stats/TEST0.PS1
src/test/vmem_stats/TEST1
src/test/vmem_stats/TEST1.PS1
src/test/vmem_stats/TEST2
src/test/vmem_stats/TEST2.PS1
src/test/vmem_stats/TEST3
src/test/vmem_stats/TEST3.PS1
src/test/vmem_stats/TEST4
src/test/vmem_stats/TEST4.PS1
src/test/vmem_stats/TEST5
src/test/vmem_stats/TEST5.PS1
src/test/vmem_stats/TEST6
src/test/vmem_stats/TEST6.PS1
src/test/vmem_stats/TEST7
src/test/vmem_stats/TEST7.PS1
src/test/vmem_stats/TEST8
src/test/vmem_stats/TEST8.PS1
src/test/vmem_stats/TEST9
src/test/vmem_stats/TEST9.PS1

By default, jemalloc allocates 4 * num_of_cpu arenas. If statistics
are enabled, it also allocates the corresponding per-arena stat
structures for all the arenas, even if only one arena is actually used
(single-threaded program).  If this test is run on a machine with
the number of cores >=64, the amount of memory required to keep all
the statistics is larger than the usable space of the pool.
The easiest workaround is to limit the number of arenas for this test
by setting JE_VMEM_MALLOC_CONF environment variable.  Thus, the test can
be run on any machine and we don't need to calculate the pool size
based on number of available CPU cores.
--- …

test: limit number of arenas in vmem_stats

---

src/test/obj_basic_integration/TEST10
src/test/obj_basic_integration/TEST7
src/test/obj_basic_integration/TEST8
src/test/obj_basic_integration/TEST9
src/test/obj_many_size_allocs/TEST3

this change fixes an issue when improper skip messages from tests which
should not be run (i.e. ./RUNTEST -t short)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1744)

test: change order of require in tests

---

doc/libpmemobj.3.md
src/include/libpmemobj/base.h
src/libpmemobj/Makefile
src/libpmemobj/libpmemobj.map
src/libpmemobj/obj.c
src/test/obj_direct/Makefile
src/test/obj_direct/obj_direct.c
src/test/obj_direct/obj_direct.h
src/test/obj_direct/obj_direct.vcxproj
src/test/obj_direct/obj_direct.vcxproj.filters
src/test/obj_direct/obj_direct_inline.c
src/test/obj_direct/obj_direct_non_inline.c
src/test/scope/out4.log.match

Users may decide at compile-time to use inlined (default) or non-inlined
variant in their programs by defining PMEMOBJ_DIRECT_NON_INLINE macro.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1716)

obj: export non-inlined pmemobj_direct

---

src/libpmem/pmem_windows.c
src/test/pmem_is_pmem_windows/pmem_is_pmem_windows.c
src/windows/include/win_mmap.h
src/windows/win_mmap.c

this change will improve performance of msync and mprotect
functions in multithreaded environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1752)

common: change mmap list mutex to RWlock

---

src/test/obj_memcheck/memcheck0.log.match

Memcheck produces slightly different messages on the
newer versions. It also points the original allocated
block instead of the reallocated one - this seems related
to test_memcheck_bug2.
Ref: pmem/issues#467
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1753)

obj: fix obj_memcheck matches for vg > 3.11

---

src/libpmem/libpmem.vcxproj
src/libpmemblk/libpmemblk.vcxproj
src/libpmemlog/libpmemlog.vcxproj
src/libpmemobj/libpmemobj.vcxproj
src/libpmempool/libpmempool.vcxproj
src/libvmem/libvmem.vcxproj
src/windows/libs_debug.props
src/windows/libs_release.props

Adds shared property sheet files for NVM libraries.
The properties that are common for all the libraries (include paths,
preprocessor macros, optimization settings, etc.) can be stored in
one file (actually two files - for debug and release configurations),
so if there is a need to i.e. add/modify some include path in all
the projects, it can be done by modification of the .props files.
No need to modify all the *.vcxproj files anymore.
Most of the properties in the library project files have their default
values, as all the custom settings are now in *.props files.
Only libvmem has some additional include paths and preprocessor macros
(for jemalloc), and those are still in libvmem.vcxproj.
NOTE: The next step would be to do the same for unit test projects,
examples, etc. This will …

win: add shared property sheets

---

utils/check_whitespace

check-whitespace should always print line number
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1762)

common: fix check-whitespace error style

---

src/test/pmempool_info/out10.log.match
src/test/pmempool_info/out11.log.match
src/test/pmempool_info/out12.log.match
src/test/pmempool_info/out13.log.match
src/test/pmempool_info/out14.log.match
src/test/pmempool_info/out15.log.match
src/test/pmempool_info/out16.log.match
src/test/pmempool_info/out16w.log.match
src/test/pmempool_info/out18.log.match

Add optional unicode suffix to the layout field in the test's match
file.
Refs: pmem/issues#496
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1759)

test: fix match file

---

src/libpmempool/libpmempool.c
src/libpmempool/pool.c

When calling mmap without a hint address under Valgrind, Valgrind intercepts the call and passes its own hint address which is not properly aligned for device DAX.
Ref: pmem/issues#462
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1764)

pool: fix mapping device dax

---

src/libpmempool/pool.c

Missed change in returned value on error.
Ref: pmem/issues#462
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1773)

pool: fix checking returned address

---

src/include/libpmemobj++/condition_variable.hpp
src/include/libpmemobj++/mutex.hpp
src/include/libpmemobj++/shared_mutex.hpp
src/include/libpmemobj++/timed_mutex.hpp
src/test/obj_cpp_cond_var/obj_cpp_cond_var.cpp
src/test/obj_cpp_cond_var_posix/obj_cpp_cond_var_posix.cpp
src/test/obj_cpp_mutex/obj_cpp_mutex.cpp
src/test/obj_cpp_mutex_posix/obj_cpp_mutex_posix.cpp
src/test/obj_cpp_shared_mutex/obj_cpp_shared_mutex.cpp
src/test/obj_cpp_shared_mutex_posix/obj_cpp_shared_mutex_posix.cpp
src/test/obj_cpp_timed_mtx/obj_cpp_timed_mtx.cpp
src/test/obj_cpp_timed_mtx_posix/obj_cpp_timed_mtx_posix.cpp

In fringe, highly unlikely cases mutex/shared_mutex locking could
block indefinitely due to improper underlying C type initialization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1775)

cpp: fix sync primitives' constructors

---

src/test/obj_lane/obj_lane.c

Ref: pmem/issues#509
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1782)

obj: fix obj_lane memcheck bug

---

src/libpmemobj/tx.c
src/test/obj_tx_add_range_direct/TEST0.PS1
src/test/obj_tx_add_range_direct/TEST1.PS1
src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c
src/test/obj_tx_add_range_direct/pmemcheck1.log.match

The calculations that decided whether or not creating a new
transaction range cache now take the size of the range header into
account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1774)

obj: fix range cache segfaulting on last snapshot

---

src/include/libpmemobj/types.h

It relies on undefined behavior (dereference of null pointer) and it's
not really needed.
Found by UBSAN.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1785)

obj: remove offsetofp

---

src/Makefile.inc
src/test/Makefile.inc
src/test/obj_sync/Makefile
src/tools/Makefile.inc

The librt is needed for clock_gettime(), if glibc version < 2.17.
This patch fixes the NVML build failures on some old Linux distros,
as well as the Coverity build failures on TravisCI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1787)

common: link with '-lrt' when necessary

---

src/libpmemobj/sync.c
src/test/obj_debug/README
src/test/obj_debug/TEST5
src/test/obj_debug/TEST5.PS1
src/test/obj_debug/obj_debug.c
src/test/obj_list/mocks_windows.h
src/test/obj_list/obj_list_mocks.c
src/test/obj_sync/obj_sync.c
src/test/obj_tx_lock/obj_tx_lock.c
src/test/obj_tx_locks/obj_tx_locks.c

Add a debug check to the thread synchronization API to check the
provided pmemobj pool handle against the location of the synchronization
primitive. Since this check is costly, it will be performed only in the
debug version of the library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1783)

obj: add pop debug check in sync.c

---

src/libpmemobj/tx.c

This change affects empty transactions.
We can't move this check to pmemops_memset_persist, because it has
built-in fence, which someone might rely on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1798)

obj: small optimization in tx_post_commit_set

---

src/test/unicode_api/TEST0

The script looks for C API functions which operate on strings and
verifies that Windows U/W unicode versions are available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1741)

common: add unicode api test script

---

src/benchmarks/pmembench.cpp

- add assert after allocation
- use types consistently
(otherwise static code analyzers are confused)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1805)

benchmark: fix some minor issues

---

src/benchmarks/pmembench.cpp

Potential fix for minor Coverity Scan issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1809)

benchmark: validate path

---

utils/build-dpkg.sh
utils/build-rpm.sh

-ggdb does not affect generated code and for distro packages all
debug info is moved to a separate package with debug informations.
-fno-omit-frame-pointer affects generated code, but its overhead
should be negligible.
With those two flags in release builds it's possible to analyze
performance traces. Without -fno-omit-frame-pointer the stacktraces
are flat and spread randomly making the analysis impossible.
Without -ggdb stacktraces are reliable, but the part in NVML has
"unknown" as function names. (-ggdb without -fno-omit-frame-pointer
is useless)
Builds on top of #1819.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1820)

common: set some flags for release packages

---

utils/build-dpkg.sh

... from make dpkg. It's already happening in make rpm.
It speeds up building packages with BUILD_PACKAGE_CHECK=n by a factor of 2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1814)

common: don't build tests when requested

---

src/libpmemobj/obj.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1829)

obj: fix memleak in ctl after pmemobj_check

---

src/test/obj_constructor/memcheck1.log.match

The output from memcheck provides more info in valgrind 3.12.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1830)

obj: fix memcheck match file

---

src/include/libpmemobj/base.h
src/libpmemobj/tx.c

Each reference to __thread variable generates a call to __tls_get_addr which takes time.
Instead of reading "tx" and "_pobj_cached_pool" every time we need it, cache it in local variable and pass to other functions that need them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1813)

obj: optimize TLS usage

---

src/test/pmempool_info/out1.log.match
src/test/pmempool_info/out16.log.match
src/test/pmempool_info/out16w.log.match
src/test/pmempool_info/out4.log.match
src/test/pmempool_info/out5.log.match
src/test/pmempool_info/out5w.log.match
src/test/pmempool_info/out6.log.match
src/test/pmempool_info/out7.log.match
src/tools/pmempool/info_log.c

Unified naming in output of pmempool info command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1833)

pmempool: unified capital letters in info output

---

doc/libpmemobj.3.md
src/libpmemobj/obj.c
src/libpmemobj/obj.h
src/libpmemobj/tx.c
src/libpmemobj/tx.h

~~Currently it's not possible to profile applications using pmemobj.
Release versions of the library don't have debug symbols and
debug versions are very slow because of single check in
pmemobj_tx_commit.~~
~~To allow profiling introduce PMEMOBJ_DEBUG_SUPPRESS_EXPENSIVE_CHECKS
environment variable.~~
The new ctl variable is: tx.debug.skip_expensive_checks=1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1797)

obj: add ctl var for suppressing expensive checks

---

src/libpmempool/pool.c
src/tools/pmempool/common.c

This provides a clarification for safe usage of memcpy function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1845)

common: add comments clarifying usage

---

src/libpmemobj/lane.c
src/libpmemobj/lane.h

This patch introduces an optimization that makes false sharing of
lanes less likely. It does so by assigning threads a *primary*
lane which is always picked as the first candidate for acqurining.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1850)

obj: implement primary lanes

---

src/examples/Makefile.inc
src/examples/libpmemobj/hashmap/Makefile
src/examples/libpmemobj/libart/Makefile
src/examples/libpmemobj/list_map/Makefile
src/examples/libpmemobj/tree_map/Makefile
src/examples/libvmem/libart/Makefile

The linking command in examples/Makefile.inc didn't use the LIB
variable.
Also, some libraries didn't reference pmemobj -- such shared objects
should reference all their dependecies.
Remove some references to pthreads, as it is already a dependancy
of libpmemobj, thus probably there should be no need to mention it when
using pmemobj.
This also reverts a few mistakes made in an earlier commit:
"examples: Remove unused LIBS variable from some makefiles"
Before:
```
$ ldd libart.so
linux-vdso.so.1
libc.so.6 => /usr/lib/libc.so.6
/usr/lib64/ld-linux-x86-64.so.2
$ ldd libhashmap_tx.so
linux-vdso.so.1
libc.so.6 => /usr/lib/libc.so.6
/usr/lib64/ld-linux-x86-64.so.2
```
After:
```
$ ldd libart.so
linux-vdso.so.1
libpmemobj.so.1 => ../../../debug/libpmemobj.so.1
libpthread.so.0 => …
```

examples: Fix dynamic linking issues

---

src/common/mmap.c
src/common/mmap.h
src/common/mmap_linux.c
src/common/mmap_windows.c
src/common/set.c
src/libvmem/vmem.c
src/test/util_map_proc/util_map_proc.c

Adds support for user defined hint address (via PMEM_MMAP_HINT)
and for proper mapping address alignment on Windows.
Ref: pmem/issues#513
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1851)

common: (win) fix mapping alignment

---

src/test/unicode_api/TEST0

Use a different column for the function name for older clang
versions.
Refs: pmem/issues#524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1857)

test: use different column in unicode_api

---

src/test/obj_pmalloc_mt/obj_pmalloc_mt.c

The test was not deterministic because depending on the performance of
allocations in a transaction, various different undo log alloc vectors
might have been allocated, which in turn triggered creation of buckets.
Ref: pmem/issues#523
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1858)

obj: reorder workloads in obj_pmalloc_mt

---

src/common/os.h
src/libpmempool/libpmempool.c
src/libpmempool/rm.c

The librpmem library is loaded on demand only if there are any remote
replicas in the pool set.
This also fixes one of the issues detected by Coverity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1812)

pool: remove util_remote_load from lib ctor

---

src/common/set.c

those changes should fix sporadical fails on pmempool_check TEST7 and TEST17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1864)

common: crtime fix

---

src/libpmemobj/ctl.c

Silence the warning about potential NULL pointer dereference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1869)

obj: fix issue detected by Coverity

---

src/common/util.c
src/common/util.h
src/libpmempool/check_util.c
src/test/pmempool_check/TEST16
src/test/pmempool_check/TEST16.PS1
src/tools/pmempool/output.c
utils/docker/build.sh

/etc/localtime file is not present inside a Docker image with Ubuntu
16.04. Without this file a call to localtime(3) sets errno to 2.
This also reenables the test pmempool_check/TEST16.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1866)

common: fix failing localtime under docker

---

src/examples/libpmemlog/logfile/addlog.c
src/examples/libpmemlog/logfile/printlog.c

This patch makes headers aligned to sizeof(long) bytes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1872)

examples: fix misaligned memory access

---

src/common/out.c
src/common/out.h
src/common/util.h
src/libpmempool/check_btt_map_flog.c
src/libpmempool/check_log_blk.c
src/libpmempool/check_pool_hdr.c
src/libpmempool/check_util.h
src/test/pmempool_info/out12.log.match
src/test/pmempool_info/out13.log.match
src/test/pmempool_info/out14.log.match
src/test/tools/pmemspoil/spoil.c
src/tools/pmempool/check.c
src/tools/pmempool/common.h
src/tools/pmempool/create.c
src/tools/pmempool/info.c
src/tools/pmempool/info_blk.c
src/tools/pmempool/info_log.c
src/tools/pmempool/info_obj.c
src/tools/pmempool/output.h
utils/cstyle

Adding "format" attribute to functions which accept printf-like format arguments enforces verifying format specifiers in compile time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1880)

common: add checking printf-like formats

---

utils/docker/pull-or-rebuild-image.sh

TRAVIS_COMMIT_RANGE usually contains invalid range when developer
uses git push -f to his own repository.
Travis build failures caused by push -f are much more frequent
then Dockerfile modifications.
Work around this problem by ignoring invalid TRAVIS_COMMIT_RANGE
values and relying on TRAVIS_COMMIT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1888)

common: work around Travis bug

---

src/libpmemobj/lane.c
src/libpmemobj/pvector.c
src/libpmemobj/pvector.h
src/libpmemobj/tx.c
src/test/obj_pmalloc_mt/obj_pmalloc_mt.c

Currently all applications ran under helgrind/drd that had two or more threads
use the same lane would report possible races due to reuse of memory.
This patch adds relevant instrumentation that marks all possible lane resources
as new when acquiring a lane.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1881)

obj: fix valgrind instrumentation for lane reuse

---

doc/pmempool-create.1.md
src/tools/pmempool/create.c

If executed with --force flag the pool will be removed first.
Ref: pmem/issues#529
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1876)

pool: add --force flag for create command

---

src/test/testconfig.ps1.example
src/test/testconfig.sh.example
utils/docker/configure-tests.sh

Turns on printing test execution time for Travis builds and for example
test configurations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1902)

common: display test execution time

---

doc/libpmemobj.3.md
doc/librpmem.3.md
src/include/librpmem.h
src/tools/rpmemd/rpmemd_db.c

This patch clarifies what sizes are allowed for a pool and part files in librpmem.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1892)

rpmem: clarify pool and part file sizes

---

src/common/file_linux.c

minor change to parse the align file in /sys as decimal instead of hex (the base was changed in more recent Linux kernels).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1906)

common: device dax align from /sys is decimal

---

src/common/file_linux.c

In older kernels (4.8.x) Device DAX alignment was printed
in hex format, so if the alignment value does not match any valid
number (4K, 2M or 1G) in decimal format, try to interpret it as hex
number.  This would make it work with both new and older kernels.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1914)

common: fix fetching Device DAX alignment

---

src/benchmarks/pmem_memset.cpp
src/benchmarks/pmembench_memset.cfg

Add option to sync data with pmem_msync after libc memset.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1913)

benchmarks: add msync option to pmem_memset

---

utils/docker/images/install-libfabric.sh
utils/docker/run-build.sh

Inappropriate use of '&&' inside a batch script (even with 'set -e' option) caused docker image build to happily succeed despite a failure of one of the &&-ed command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1920)

common: fix silent build fails under docker

---

src/test/vmmalloc_calloc/TEST0
src/test/vmmalloc_calloc/vmmalloc_calloc.c

Makes cfree() an alias to free(), if cfree() is not exported by glibc.
The cfree() function has been removed from glibc since version 2.26.
This is why vmmalloc_calloc test compilation started to fail
on Fedora 27.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1923)

vmmalloc: cfree removal (master)

---

src/Makefile

After previous fix all pc files started with
"-e version=1.2+b1-391-g5ba7c8d39".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1930)

common: fix pkg-config generation fix

---

src/libpmemobj/pmalloc.c
src/libpmemobj/pmalloc.h

Found by code coverage analysis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1932)

obj: remove unused prealloc_construct

---

src/libpmemobj/palloc.c
src/test/obj_constructor/TEST2
src/test/obj_constructor/obj_constructor.c
src/test/obj_rpmem_constructor/TEST0

If a canceled huge allocation operated on split memory block,
that block didn't get properly coalesced in the persistent
state of the heap which could have lead to crashes when an
allocation of a similar block was attempted again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1934)

obj: fix huge allocations cancel

---

src/libpmemobj/heap.c
src/libpmemobj/heap.h
src/libpmemobj/palloc.c
src/test/obj_heap/obj_heap.c

This patch moves all bucket retrievals to the earliest possible place
in the code path which makes locking explicit for functions that
require access to memory block containers.
This is purely a refactor, there are no functional changes.
The changes are in preparation for a larger patch that overhauls
the way buckets are scheduled for threads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1931)

obj: refactor heap bucket retrieval

---

doc/librpmem.3.md
src/benchmarks/Makefile
src/common.inc
src/common/set.c
src/examples/librpmem/Makefile
src/librpmem/Makefile
src/librpmem/README
src/librpmem/librpmem.c
src/librpmem/rpmem.c
src/librpmem/rpmem_fip.c
src/librpmem/rpmem_fip.h
src/test/rpmem_basic/Makefile
src/test/rpmem_basic/rpmem_basic.c
src/test/rpmemd_db/Makefile
src/test/rpmemd_db/rpmem1.log.match
src/test/rpmemd_db/rpmemd_db_test.c
src/test/tools/fip/Makefile
src/tools/rpmemd/Makefile

Libfabric by default initialize libibverbs to handle fork properly.
Requires libfabric version >= 1.4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1722)

rpmem: do not call ibv_fork_init directly

---

src/common/file_linux.c

Use <sys/sysmacros.h> for makedev(), major() and minor() decls.
Otherwise, on latest Fedora (glibc 2.25+) compilation fails with
the following error:
"error: In the GNU C Library, "major" is defined by <sys/sysmacros.h>.
For historical compatibility, it is currently defined by <sys/types.h>
as well, but we plan to remove this soon. To use "major", include
<sys/sysmacros.h> directly. (...)"
Ref: pmem/issues#551
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1936)

common: use <sys/sysmacros.h> for major()/minor()

---

src/jemalloc/test/unit/mallctl.c

The mallctl tests are currently failing on machines with large amount
of CPUs because there's not enough room for CTL arena statistics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1956)

vmem: increase the pool size of mallctl tests

---

src/test/obj_ringbuf/obj_ringbuf.c

Ref: pmem/issues#557
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1960)

test: fix memleak in obj_ringbuf

---

src/test/obj_many_size_allocs/obj_many_size_allocs.c

This test relied on sequence of open,close,open always returning the
same address in the second open as the first time - this is not always
true.
Ref: pmem/issues#563
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1962)

test: fix assumptions in obj_many_size_allocs

---

src/libpmemobj/tx.c
src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c
src/test/obj_tx_add_range_direct/pmemcheck1.log.match

If there's not enough space in a tx cache, the snapshot is split into
two parts: one part is small enough to fit in the remaining space in the
cache, and the second one lands in a new cache.
There is a bug in this logic that results in the second part having
both offset and size cut by 16 bytes. This patch fixes that and adds
a test for that logic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1967)

obj: fix split snapshot being cut by 16 bytes

---

src/test/obj_tx_add_range/obj_tx_add_range.c
src/test/obj_tx_add_range/pmemcheck1.log.match
src/test/obj_tx_realloc/obj_tx_realloc.c

This patch brings statement code coverage to 100% (excluding volatile failure paths, some currently unused code and tiny ctl entry points).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1976)

test: add missing obj tests

---

src/common/os_thread.h
src/common/os_thread_linux.c

Fixes os_cpu_set_t size to make it compatible with SLES12.
Ref: pmem/issues#554
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1978)

common: modify os_cpu_set_t definition

---

src/test/obj_convert/TEST0
src/test/obj_convert/TEST11
src/test/obj_convert/TEST12
src/test/obj_convert/TEST13
src/test/obj_convert/TEST14
src/test/obj_convert/TEST15
src/test/obj_convert/TEST16
src/test/obj_convert/TEST17
src/test/obj_convert/TEST18
src/test/obj_convert/TEST19
src/test/obj_convert/common.sh
src/test/obj_convert/obj_convert.c
utils/docker/images/Dockerfile.fedora-25
utils/docker/images/Dockerfile.ubuntu-16.04

This patch changes the obj_convert test so that it also runs all of
the scenarios on the current version of the library. This makes sure
that a) the test is correct and b) the library didn't have a
regression in recovery path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1974)

test: create obj_convert scenarios from head

---

src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c

There seems to be a problem with valgrind pmemcheck not falling back
to using anonymous mmap when sbrk fails. This leads to volatile
malloc failures when a test exceeds the applications break. What's
worse, the behavior depends on the operation system malloc
implementation and so it's pretty difficult to predict. For now, I've
reduced the amount of allocated memory for the problematic test but
we will probably need to tackle that problem eventually.
Ref: pmem/issues#565 pmem/issues#569
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1989)

test: fix add_range_direct under pmemcheck

---

doc/libpmem.3.md
doc/libpmemblk.3.md
doc/libpmemlog.3.md
doc/libpmemobj.3.md
doc/libpmempool.3.md
doc/librpmem.3.md
doc/libvmem.3.md
doc/libvmmalloc.3.md
doc/pmempool-check.1.md
doc/pmempool-convert.1.md
doc/pmempool-create.1.md
doc/pmempool-dump.1.md
doc/pmempool-info.1.md
doc/pmempool-rm.1.md
doc/pmempool-sync.1.md
doc/pmempool-transform.1.md
doc/pmempool.1.md
doc/rpmemd.1.md

Removes revision number from the man page version, leaving only
the API major.minor version number.  Revision number is replaced
with the date of the last modification.
It also changes the man page titles to be written all in caps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1984)

doc: change man page versioning

---

src/windows/srcversion/srcversion.vcxproj
utils/SRCVERSION.ps1

When building NVML from a source tarball, it is not possible to obtain
the version number via 'git describe' and '1.0' will be used in such
case.  This patch allows to pass the version string as an argument to
msbuild (/p:SRCVERSION=...) and override the default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1996)

common: (win) allow to override SRCVERSION

---

src/common/mmap.c
src/common/mmap.h
src/common/mmap_linux.c
src/common/mmap_windows.c
src/common/set.c
src/test/util_map_proc/util_map_proc.c

This fixes the problem with invalid mapping address alignment
on Device DAX (if the internal alignment is other than 4096), when
the program is run under memcheck.
Ref: pmem/issues#556
Ref: pmem/issues#558
Ref: pmem/issues#559
Ref: pmem/issues#560
Ref: pmem/issues#561
Ref: pmem/issues#562
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2001)

common: use hint address when mapping pool hdr

---

utils/check-commit.sh
utils/check-doc.sh

When the new man page is added, it is required to have its initial
version in doc/generated.  Otherwise, the build would fail on rpm/dpkg.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2000)

common: allow new files in doc/generated

---

src/test/unittest/unittest.ps1
src/test/unittest/unittest.sh

When the test failure occurs it might be helpful to dump not only
the "out.log", but also "err.log" file.
However, it's easier to simply dump "trace.log" as it contains
all the traces from the out/err log files plus some more
detailed info on file/line/function for each trace message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2017)

test: dump trace.log on failure

---

src/test/unittest/ut.c

Object type numbers are undocumented and may change in newer
Windows releases.  Using type name to determine object/handle
type seems to be more reliable.
Ref: pmem/issues#579
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2027)

test: check open handle type using type name

---

.codecov.yml

because we compile one source file multiple times codecov
cannot properly interpret branch data. As it is affecting our
test coverage results we have to disable this feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2015)

common: disable branch detection in codecov

---

src/libpmemobj/alloc_class.c
src/test/obj_constructor/TEST0
src/test/obj_constructor/TEST0.PS1
src/test/obj_constructor/TEST1
src/test/obj_constructor/TEST2
src/test/obj_constructor/obj_constructor.c
src/test/obj_convert/obj_convert.c
src/test/obj_memcheck/memcheck0.log.match
src/test/obj_memcheck/obj_memcheck.c
src/test/obj_out_of_memory/out0.log.match
src/test/obj_out_of_memory/out1.log.match
src/test/obj_pmalloc_basic/obj_pmalloc_basic.c
src/test/obj_pmalloc_rand_mt/obj_pmalloc_rand_mt.c
src/test/obj_pvector/obj_pvector.c
src/test/obj_realloc/TEST0
src/test/obj_realloc/TEST0.PS1
src/test/obj_realloc/TEST1
src/test/obj_realloc/TEST1.PS1
src/test/obj_tx_alloc/TEST1
src/test/obj_tx_alloc/obj_tx_alloc.c
src/test/pmemobjcli/TEST0.PS1
src/test/pmempool_info/TEST12
src/test/pmempool_info/TEST12.PS1
src/test/pmempool_info/TEST13
src/test/pmempool_info/TEST13.PS1
src/test/pmempool_info/out12.log.match

This patch significantly improves the allocation classes with regards
to the new header sizes. The algorithm now takes the header sizes
into account.
There are also changes that simplify generation interface.
Internal fragmentation comes down from average of 6.77% to 3.46%
while using less alloc classes.
This patch also increases the maximum run blocks size to
4 megabytes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2014)

obj: tune allocation classes

---

src/common/util.h
src/libpmemobj/heap.c

This patch improves the way buckets are assigned by counting how many
threads are currently using a given bucket and always picking the
first one that is the least used.
This patch also changes the 'bucket_cache' name to a more meaningful
'arena', a term that is widely used and understood.
Ref: pmem/issues#564
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2002)

obj: optimize thread utilization of buckets

---

utils/SRCVERSION.ps1

If the build scripts have no access to GIT, then the source version
cannot be determined (git describe) and the version string is empty.
This patch changes the default to "UNKNOWN VERSION".
Ref: pmem/issues#578
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2030)

common: fix default version string

---

doc/libpmemobj.3.md
src/libpmemobj/obj.c

Ref: pmem/issues#549
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2031)

obj: stop grabbing a lock when querying pool ptr

---

src/test/obj_convert/TEST17

This test hits a bug in vg 3.10, we should revert this
once we move on to a newer version.
Ref: pmem/issues#581
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2040)

test: disable memcheck for obj_convert TEST17

---

src/test/blk_rw/TEST11
src/test/blk_rw/TEST12
src/test/log_basic/TEST8
src/test/log_basic/TEST9
src/test/obj_basic_integration/TEST11
src/test/obj_basic_integration/TEST12
src/test/pmempool_check/TEST24
src/test/pmempool_check/TEST25
src/test/pmempool_info/TEST19
src/test/pmempool_rm/TEST6
src/test/unittest/unittest.sh
src/test/util_poolset_parse/TEST2
src/test/util_poolset_parse/TEST3

Allows to have multiple Device DAX devices with different alignment
specified in testconfig.sh.  The script would pick the devices having
the appropriate/requested alignment for given test.
Ref: pmem/issues#567
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2051)

test: improve Device DAX alignment detection

---

src/test/match
src/test/unittest/unittest.sh
utils/docker/run-coverage.sh

On Travis, the amount of log produced during a coverage measuring build sometimes exceeds 4MB, which causes the build to fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2045)

common: hush error messages during coverage build

---

src/librpmem/rpmem_obc.c
src/rpmem_common/rpmem_proto.h
src/test/rpmem_proto/rpmem_proto.c
src/tools/rpmemd/rpmemd.c
src/tools/rpmemd/rpmemd_obc.c

Add a __attribute__((packed)) version of the rpmem_pool_attr structure
which is sent OTA/OTC. This causes an unaligned access on clang-4.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2061)

rpmem: add attribute packed

---

src/tools/pmempool/rm.c

Remove redundant remote init / fini.
Ref: pmem/issues#587
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2068)

pool: fix rm remote init / fini

---

doc/libpmempool.3.md
doc/pmempool-sync.1.md

Added note that pmempool and libpmempool sync only supports pmemobj pools.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2078)

doc: sync supports only pmemobj

---

doc/librpmem.3.md

A Chelsio T4 and T5 hardware can not handle a memory region grater
than or equal to 8GB due to a hardware bug.
Ref: torvalds/linux@2550a88d956fb77c34d71b46a0a8e9ebf1c5b4a3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2067)

doc: Chelsio pool size limit

---

src/libpmempool/rm.c

This patch is only to silence Coverity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2097)

pool: ignore error while loading librpmem

---

src/test/obj_rpmem_basic_integration/config.sh

Because some tests from this unittest requires valgrind support
missing test type causes printing skip messages. For other
unittests a test type value in config.sh is still optional.
Ref: pmem/issues#495
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2095)

test: add missing test type

---

src/test/Makefile

Ref: pmem/issues#472
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2104)

test: remove invalid rpmem obj dependencies

---

src/libpmemobj/heap.c

This might have lead to some free chunks not being properly
coalesced when recoverying after a crash that happened in the
middle of a pmalloc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2105)

obj: write free chunks footers on recovery

---

src/libpmemobj/heap.c

The old behavior theoretically might have lead to a situation where
a bucket associated with an allocation class that had runs with
different header types, might have given out blocks that were
too small (or too large) for the requested object.
FYI: this might only happen with legacy headers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2107)

obj: don't put runs with incompat hdr in recycler

---

doc/librpmem.3.md

The librpmem API is experimental but remote
replication in libpmemobj is safe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2118)

rpmem: add note about experimental API

---

utils/SRCVERSION.ps1

This patch removes spaces in srcversion to avoid issues with tests match failed when version is not detected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2125)

common: fix matches unknown srcversion

---

src/libpmemobj/heap.c
src/test/Makefile
src/test/obj_zones/.gitignore
src/test/obj_zones/Makefile
src/test/obj_zones/TEST0
src/test/obj_zones/obj_zones.c
src/test/obj_zones/out0.log.match

The function that initialized a zone for the first time had
a wrong return value that indicated that no memory was found
when an entire new zone was inserted into the bucket.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2128)

obj: fix bogus OOM after exhausting first zone

---

src/libpmemobj/heap.c
src/libpmemobj/recycler.c
src/test/obj_constructor/memcheck1.log.match
src/test/obj_heap/obj_heap.c
src/test/obj_pmalloc_basic/obj_pmalloc_basic.c

This patch improves the recycler by changing the score calculation
function to include the largest available block. This means that now
the threads can accurately tell if a run in the recycler satisfies the
users request and there's no need for different fallbacks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2114)

obj: reclaim run immediately after deactivation

---

src/include/libpmemobj/tx.h

Ref: pmem/issues#598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2119)

obj: remove uses of TOID_OFFSETOF for user-supplied types

---

src/include/libvmmalloc.h
src/libvmmalloc/libvmmalloc.c

Modifies libvmmalloc to always export aligned_alloc(), memalign(),
valloc() and pvalloc(), even if those functions are not supported by
installed version of glibc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2098)

vmmalloc: always export all aligned alloc variants

---

src/benchmarks/rpmem_persist.cpp

Ref: pmem/issues#600
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2134)

benchmark: fix buffer overflow in rpmem_persist

---

src/benchmarks/Makefile
src/common.inc

When building nvml under different environments (ie. buildroot),
the objcopy and pkg-config need to be settable thru the environment
since the gcc, binutils, etc might not match the host during this
build.
This prevents errors on relocation symbols not being understood
by link specically discovered when working on Ubuntu 14.04 and
build 2017.02 to add an nvml package support.
Signed-off-by: Charles Hardin <ckhardin@exablox.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2137)

make: allow the objcopy and pkg-config to be overridden

---

src/test/RUNTESTLIB.PS1
src/test/RUNTESTS.PS1
src/test/unittest/unittest.ps1
src/test/unittest/unittest.sh

Treat '-f any' as '-f pmem' if $Env:PMEM_FS_DIR is specified.
Plus some minor code cleanup and formatting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2147)

test: fix RUNTESTS.PS1 with '-f any'

---

src/test/obj_pool/TEST30
src/test/obj_pool/out30.log.match

Testset will be created by the default umask. And it will cause a
fail during match. Setting the umask, and modified the log for
comparison.
Signed-off-by: Xiaodong Jia <jiaxd-fnst@cn.fujitsu.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2155)

test/obj_pool: add the umask in TEST30

---

src/test/.gitignore
src/test/unittest/unittest.sh
utils/docker/build-local.sh
utils/docker/prepare-for-build.sh

This patch adds a lock on Device DAXes for tests executed with `make pcheck`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2084)

test: make pcheck handle dev-dax tests

---

src/libpmemobj/palloc.c
src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c

this patch improves performance of palloc_operation by ~8% on windows
on windows errno is a function call which is surprisingly heavy....
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2156)

obj: improve performance of palloc on windows

---

src/libpmemblk/btt.c
src/test/unittest/ut.c

Fix two false positive -Wconversion warnings.
In libpmemblk/btt.c, refactor with internal inline function get_map_lock_num()
that casts multiply/divide result to avoid warning.
In test/unittest/ut.c, apply cast to entire expression to avoid warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2150)

common: gcc sanitize fixes

---

src/libpmemobj/heap.c
src/test/obj_persist_count/out0.log.match
src/test/obj_persist_count/out1.log.match

This makes the first heap zone traversal to happen at the time
of the first allocation. This means that if you want to open the
pool only for reading, you won't ever have to pay this cost.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2166)

obj: stop populating buckets at heap init

---

utils/style_check.sh

Configures $clang_format_bin variable to default value, in case it
was not set by the caller (Makefile).  This allows to run the
style checker script from the command line.
Ref: pmem/issues#618
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2170)

common: allow to run style_check.sh from cmdline

---

src/test/obj_lane/TEST0.PS1
src/test/obj_lane/TEST1.PS1

There is an expected exception (abort) in this test, handled
by the test program.  However, on Windows the error message
is still printed on stderr, so it must be redirected to $null.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2174)

test: get rid of error messages in obj_lane

---

src/libvmem/vmem.c
src/test/vmem_valgrind_region/.gitignore
src/test/vmem_valgrind_region/Makefile
src/test/vmem_valgrind_region/TEST0
src/test/vmem_valgrind_region/TEST1
src/test/vmem_valgrind_region/TEST2
src/test/vmem_valgrind_region/TEST3
src/test/vmem_valgrind_region/TEST4
src/test/vmem_valgrind_region/excluded-errors.supp
src/test/vmem_valgrind_region/memcheck0.log.match
src/test/vmem_valgrind_region/memcheck1.log.match
src/test/vmem_valgrind_region/memcheck2.log.match
src/test/vmem_valgrind_region/memcheck3.log.match
src/test/vmem_valgrind_region/memcheck4.log.match
src/test/vmem_valgrind_region/vmem_valgrind_region.c

In case the program creates the pool using vmem_create_in_region(),
the memory region passed to je_vmem_pool_create() should be treated
as addressable, but undefined, even though the program has ininitialized
this memory region before creating the pool.
Once the pool is created, jemalloc will also mark registered free chunks
(usable heap space) as unaddressable.
This hels memcheck to detect accesses to vmem pool memory regions
that were not explicitly allocated via libvmem APIs.
Also, the application cannot do any assumptions about the content
of such memory region after the pool has been destroyed.
So, in vmem_delete() it must be marked as undefined.
--- …

vmem: fix valgrind instrumentation

---

src/benchmarks/perf.cfg

* removed obsolete benchmarks
* fixed misleading tests name
* reduced rtree ops-per-thread (this tree is quite slow)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2180)

benchmark: fix perf.cfg script

---

src/rpmem_common/rpmem_fip_common.c

Limit maximum number of lanes to the optimal number of resources which
includes tx and rx contexts and number of CQ.
Ref: pmem/issues#609
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2181)

rpmem: limit max lanes

---

utils/cstyle

The cstyle script (usually) does not allow spaces after
casts. As a side effect, it does not accept the following line:
`return (struct x) {.a = 0, .b = 1};` -> space after cast
At the same time, it did not accept the following line:
`return (struct x){.a = 0, .b = 1};` -> missing space before left brace
This patch resolves the "space after cast/space before left brace" paradox.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2183)

common: allow inline structs in cstlye

---

src/libpmemobj/alloc_class.c

Custom allocation classes were incorrectly stopping the search
for the optimal one. This manifested in triggering the ASSERT
that the allocation class must be found in some cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2187)

obj: fix lazy custom class selection

---

src/benchmarks/pmembench.cpp

The formula used here is not actually a very good estimator but it is simple to calculate and suffices for the purpose of benchmarks.
Ref: pmem/issues#318
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2189)

benchmark: fix calculating standard deviation

---

src/benchmarks/perf.cfg

- reduce ops-per-thread in obj_hashmap_atomic_map_insert to match
other map benchmarks
- fix misleading name of obj_hashmap_atomic_map_insert
- reduce ops-per-thread in blk-test to decrase run time of these
benchmarks(was ~3h per blk benchmarks)
- reduce repeat number to limit benchmarks execution time to ~1h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2195)

benchmark: perf.cfg script adjustments

---

src/libpmemlog/log.c
src/libpmemlog/log.h
src/libpmempool/Makefile
src/libpmempool/libpmempool.c
src/libpmempool/libpmempool.vcxproj
src/libpmempool/libpmempool.vcxproj.filters
src/tools/pmempool/Makefile

Changes functions required by pmempool to static inline functions
and moves them to log.h.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2198)

pool: avoid static linking of log.c

---

src/test/libpmempool_bttdev/TEST0
src/test/libpmempool_bttdev/TEST1
src/test/libpmempool_bttdev/TEST10
src/test/libpmempool_bttdev/TEST11
src/test/libpmempool_bttdev/TEST2
src/test/libpmempool_bttdev/TEST3
src/test/libpmempool_bttdev/TEST4
src/test/libpmempool_bttdev/TEST5
src/test/libpmempool_bttdev/TEST6
src/test/libpmempool_bttdev/TEST7
src/test/libpmempool_bttdev/TEST8
src/test/libpmempool_bttdev/TEST9
src/test/libpmempool_bttdev/out0.log.match
src/test/libpmempool_bttdev/out1.log.match
src/test/libpmempool_bttdev/out10.log.match
src/test/libpmempool_bttdev/out11.log.match
src/test/libpmempool_bttdev/out2.log.match
src/test/libpmempool_bttdev/out3.log.match
src/test/libpmempool_bttdev/out4.log.match
src/test/libpmempool_bttdev/out5.log.match
src/test/libpmempool_bttdev/out6.log.match
src/test/libpmempool_bttdev/out7.log.match
src/test/libpmempool_bttdev/out8.log.match
src/test/libpmempool_bttdev/out9.log.match

Use canonical argument ordering in libpmempool_bttdev tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2203)

test: FreeBSD portability #3

---

src/benchmarks/pmembench.cpp
src/common/file.c
src/common/file.h
src/examples/libpmemobj/libart/arttree.c
src/examples/libpmemobj/libart/arttree_structures.c
src/examples/libpmemobj/panaconda/panaconda.cpp
src/examples/libpmemobj/pman/pman.cpp
src/examples/libpmemobj/pminvaders/pminvaders.c
src/examples/libpmemobj/pminvaders/pminvaders2.c
src/examples/libvmem/libart/arttree.c
src/include/libpmemobj++/pool.hpp
src/libpmemblk/btt.c
src/libpmempool/pool.c
src/librpmem/rpmem_cmd.c
src/librpmem/rpmem_ssh.c
src/rpmem_common/rpmem_common.h
src/test/blk_recovery/blk_recovery.c
src/test/bttdevice/TEST0
src/test/bttdevice/TEST1
src/test/tools/pmemspoil/spoil.c
src/tools/pmempool/info.c
src/tools/rpmemd/rpmemd_log.c
utils/check-os.sh
utils/check_license/check-headers.sh
utils/check_license/check-license.c

These non-invasive changes are intended to reduce the
size of the main FreeBSD port commit.
Change #includes and add #ifdefs for FreeBSD, for files
where there are otherwise no code changes.
Canonicalize arguments for test/bttdevice.
Use common options in utils/check-os.sh.
Use redirect rather than unsupported -o option in
utils/check_license/check-headers.sh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2208)

common: FreeBSD portability #4

---

doc/librpmem.3.md

We are using **SSH_CONNECTION** variable (see **ssh**(1)). It happens IPv6 address pop out there when ssh to loopback interface (even if other loopback interface address is used explicitly). I wrote about this because it took a bit to debug the issue. Maybe it will save somebody few minutes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2210)

doc: sockets provider does not support IPv6

---

utils/build-dpkg.sh

Development packages for libraries that depend on libpmem need to depend
on libpmem-dev.
Without that pkg-config can't find those libraries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2215)

common: fix dependencies for Debian's dev packages

---

src/librpmem/rpmem_cmd.c
src/librpmem/rpmem_ssh.c

If fork() failed in rpmem_{open,create} there is a call to kill() with
pid equals -1, which sends a signal to all processes which the current
process has permissions to send to.
Ref: pmem/issues634
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2222)

rpmem: fix cleanup if fork() failed

---

src/benchmarks/blk.cpp
src/benchmarks/perf.cfg
src/benchmarks/pmembench_blk.cfg

Adds an additional operation type that allows to compare performance
of pmemblk_read/write vs. pmem_memcpy.  Replaces 'file-io' argument
with 'operation', which can be 'blk', 'file' or 'memcpy'.
Replaces 'random' flag with 'mode' argument, which controls
the read/write pattern amd culd be 'stat', 'seq' or 'rand'.
For tests run on Device DAX, 'files-size' argument can be used
to limit the size of the device that is actually used for the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2216)

benchmark: add memcpy operation to blk

---

.codecov.yml

Code coverage is supposed to tell us about how much the code we ship is
tested. We are not shipping tests, so including them in coverage reports
doesn't make much sense.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2230)

common: disable reporting of coverage for tests

---

src/benchmarks/benchmark.hpp
src/benchmarks/pmembench.cpp

Previous affinity setting method (even CPU first, odd CPU after) is working
as expected only on windows machines where physical and logical CPU's are
interleaved. To don't add more platform specific code, i added an option for
user to set affinity how he wants.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2214)

benchmark: change affinity set method

---

src/Makefile.inc
src/benchmarks/pmembench.cpp
src/test/Makefile.inc
src/test/unittest/unittest.sh

Fix broken ASAN check in unittest.sh.
Remove FreeBSD libvmmalloc SANITIZE check (handled by
corrected ASAN check).
Fix gcc maybe-uninitialized error in pmembench.cpp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2235)

common: Fix ASAN check

---

src/libpmemobj/palloc.c

When two threads simultaneously tried to reallocate two objects,
and when the source size of the object A matched the destination size
of the object B, and the the object A resided on the same run as
object B, there was a chance for a deadlock. The only solution to
this problem while keeping atomicity guarantees (we have to keep the
redo log for the entire operation), is to sort locks by their address,
and that's what this patch does.
Found by helgrind.
Ref: pmem/issues#635 pmem/issues#636 pmem/issues#637
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2240)

obj: fix potential deadlock during realloc

---

src/libpmemobj/palloc.c
src/test/obj_pmalloc_basic/obj_pmalloc_basic.c

Currently, when performing realloc, the new block is unconditionally
allocated, and when the decision to bail out (because the request is
a no-op) happens, the volatile state changes are not reversed. This
is a pointless waste of CPU cycles, and in some cases might even lead
to persistent memory being locked out until the next heap incarnation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2245)

obj: fix same-size realloc volatile state change

---

src/include/libpmemobj/types.h

Ref: pmem/issues#645
Here is the issue described:
https://developercommunity.visualstudio.com/content/problem/96174/offsetof-macro-is-broken-for-nested-objects.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2254)

common: issue vs15.3 offsetof fix

---

utils/cstyle

The current cstyle prohibits "long long internal_var" because it doesn't look for whitespace after "int".
Split from FreeBSD port PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2255)

common: Fix cstyle for "long long intxxx"

---

src/common.inc
src/examples/Makefile.inc
src/examples/libpmemobj/panaconda/Makefile
src/examples/libpmemobj/pmpong/Makefile
src/jemalloc/jemalloc.mk
src/test/Makefile.inc
src/tools/Makefile.inc

Use uname -s rather than $OSTYPE.
Add more flags in common.inc.
Avoid need for GNU grep.
Split from FreeBSD port PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2256)

common: More Makefile portability changes

---

src/libpmemobj/alloc_class.c
src/libpmemobj/alloc_class.h
src/libpmemobj/heap.c
src/libpmemobj/pmalloc.c
src/test/obj_ctl_alloc_class/obj_ctl_alloc_class.c
src/test/obj_heap/obj_heap.vcxproj
src/test/obj_heap/obj_heap.vcxproj.filters
src/tools/pmempool/Makefile
src/tools/pmempool/info_obj.c

This patch changes the internal unit_size<>class mapping from a
simple array into a hashmap, thus allowing for arbitrary sized
classes.
Ref: pmem/issues#626
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2253)

obj: fix very large allocation classes

---

src/test/README
src/test/match
src/test/out_err/out0.log.match
src/test/out_err/traces0.log.match
src/test/util_map_proc/out0.log.match
src/test/util_map_proc/out1.log.match
src/test/util_map_proc/out2.log.match
src/test/util_map_proc/out3.log.match
src/test/util_map_proc/out4.log.match
src/test/util_map_proc/out5.log.match
src/test/vmem_valgrind/memcheck2.log.match
src/test/vmem_valgrind/memcheck3.log.match
src/test/vmem_valgrind/memcheck4.log.match
src/test/vmem_valgrind/vmem_valgrind.c
src/test/vmmalloc_valgrind/memcheck1.log.match
src/test/vmmalloc_valgrind/memcheck2.log.match

Add $(OPX) and $(NC) match macros.
Make match files portable across Linux and FreeBSD.
Fix vmem_valgrind.c to call vmem_delete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2259)

test: Match file enhancement and cleanup

---

src/examples/libpmemobj/pi.c

Modified result has type 'long double' that is twice the size of 'double'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2270)

examples: pi: fix persist range

---

src/include/libpmemobj++/transaction.hpp
src/test/obj_cpp_transaction/obj_cpp_transaction.cpp

In C++17 it is possible to control when exceptions are thrown in the
destructor and not trigger the std::terminate call.
This enables the destructor to throw an exception if the transaction
failed without an active exception. Calling last_tx_error is now
unnecessary to check if the transaction aborted.
Take two.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2252)

cpp: throw from transaction::automatic

---

src/Makefile.inc
utils/nvml.spec.in

Allows to specify user-defined CFLAGS when invoking make.
NVML default flags are used only if CFLAGS are not specified.
In most cases it only affects the compiler optimization settings
and enabled warnings.  The remaining options (include paths, etc.)
are still appended to CFLAGS.
For debug builds, user-defined optimizations are overriden by NVML
makefiles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2261)

common: use system-default or user-defined CFLAGS

---

src/common/errno_freebsd.h
src/common/os.h
src/common/out.c
src/common/pmemcommon.inc
src/common/util.h
src/common/util_linux.c
src/common/util_windows.c
src/libpmemblk/Makefile
src/libpmemlog/Makefile
src/libpmemobj/Makefile
src/libpmempool/Makefile
src/test/arch_flags/arch_flags.c
src/test/arch_flags/log0.log.match

Add os-specific util_getexecname().
Use sysctl rather than /proc to get executable pathname on FreeBSD.
Refactor Makefiles for library common files.
Add common/errno_freebsd.h
Split from FreeBSD port.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2271)

common: Remove /proc dependency for FreeBSD

---

src/common.inc
utils/style_check.sh

Even using 3.9 appears to break the build:
```
$ CLANG_FORMAT=clang-format-3.9 make cstyle
diff --git a/pmemobj_atomic_lists.cpp b/
index 1bc5ffccc..000000000 100644
--- a/pmemobj_atomic_lists.cpp
+++ b/
@@ -166,10 +166,10 @@ struct obj_worker {
size_t n_elm;                /* number of elements in array */
fn_position_t *fn_positions; /* element access functions */
struct element elm;       /* pointer to current element */
-                                    /*
-                                     * list_move is a pointer to structure storing variables used by
-                                     * second list (used only for obj_move benchmark).
-                                     */
+       /*
+        * list_move is a pointer to structure storing variables used by
+        * …
```

common: Use clang-format 3.8 only

---

src/test/RUNTESTS
src/test/testconfig.sh.example

Make KEEP_GOING flag more useful by recording and counting
failures.
Document KEEP_GOING flag in testconfig.sh.example.
Add note on remote account requirements in testconfig.sh.example.
Split from FreeBSD port.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2287)

test: KEEP_GOING support

---

src/common/os_linux.c
src/common/out.c
src/libpmemobj/ctl.c
src/rpmem_common/rpmem_proto.h
src/test/Makefile
src/test/ex_libpmem/TEST0
src/test/ex_libpmemobj/TEST15
src/test/unittest/ut_file.c
src/test/vmmalloc_init/TEST16
src/test/vmmalloc_init/TEST6
src/test/vmmalloc_init/vmmalloc_init.c
src/test/vmmalloc_malloc_hooks/TEST0
src/tools/pmempool/info_obj.c

Fix clang warning in common/os_linux.c.
Address PR comments that do not conflict with PR 2277.
More FreeBSD portability fixes.
Shorten pminvaders test to avoid timeout when sanitizing.
Fix divide by zero in tools/pmempool/info_obj.c.
Split from FreeBSD port.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2285)

common: PR cleanup for FreeBSD port

---

src/benchmarks/obj_locks.cpp
src/common/util.h
src/jemalloc/include/jemalloc/internal/util.h
src/libpmem/pmem.c
src/libpmemblk/blk.c
src/libpmemblk/btt.c
src/libpmemobj/container_seglists.c
src/libpmemobj/ctree.c
src/libpmemobj/heap.c
src/libpmemobj/lane.c
src/libpmemobj/pvector.c
src/libpmemobj/recycler.c
src/libpmemobj/ringbuf.c
src/libpmemobj/sync.c
src/librpmem/rpmem.c
src/librpmem/rpmem_obc.c
src/test/obj_ctree/obj_ctree.c
src/test/obj_cuckoo/obj_cuckoo.c
src/test/obj_ringbuf/obj_ringbuf.c
src/test/obj_sync/obj_sync.c
src/test/tools/pmemspoil/spoil.c
src/test/unittest/unittest.h
src/tools/pmempool/common.h
src/tools/pmempool/info_obj.c
src/tools/rpmemd/rpmemd_fip.c
src/windows/include/platform.h

The usage of __sync* builtin functions was very inconsistent.
This patch brings these usages into sync thorough most of
the code, with the exceptions of jemalloc and examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2289)

common: Unify (most of) __sync builtin usage

---

src/test/vmem_multiple_pools/TEST1
src/test/vmem_multiple_pools/TEST1.PS1
src/test/vmem_multiple_pools/out1.log.match

Originally, there could be 256 pools created simultaneously (>3.6GB).
Now, it is only 64 pools (900MB).
Ref: pmem/issues#670
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2300)

test: reduce number of pools in vmem_multi_pools

---

src/test/vmem_multiple_pools/TEST1

Tests #2/#3 are specifically for helgrind/drd tests.
Test #1 should never be executed under valgrind, even if force-enabled
via command-line options.
Ref: pmem/issues#664
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2299)

test: disable Valgrind in vmem_multiple_pools #1

---

src/test/obj_rpmem_basic_integration/node_0_rpmemd20.log.match
src/test/rpmem_basic/out10.log.match
src/test/rpmem_basic/out11.log.match
src/test/rpmemd_util/stdout0.log.match
src/tools/rpmemd/rpmemd.c
src/tools/rpmemd/rpmemd_log.h
src/tools/rpmemd/rpmemd_util.c

rpmemd log may end in syslog which does not handle a tab character properly.
Ref: pmem/issues#622
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2297)

rpmem: do not use tabs in rpmemd log

---

src/libpmemobj/bucket.c

Building with both worked, but building with only one of them meant trying to use a macro that was never defined.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2309)

obj: Allow building with memcheck or DRD

---

src/test/libpmempool_api/TEST11

The test calls mmap with a size argument specifying one
terabyte, which just apprently DRD is not happy about.
Fixes pmem/issues#668
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2310)

test: disable drd in libpmempool_api/TEST11

---

src/test/freebsd.supp
src/test/obj_pmalloc_mt/TEST0
src/test/obj_pmalloc_mt/TEST1
src/test/obj_pmalloc_mt/TEST2
src/test/obj_pmalloc_mt/TEST3
src/test/obj_pmalloc_mt/obj_pmalloc_mt.c

Parameterize src/test/obj_pmalloc_mt.c.
Add new medium helgrind and drd tests to catch locking issues
without having to run long tests (Ref Issue pmem/issues#669).
NOTE: Tests are expected to fail until issue pmem/issues#669 is resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2303)

test: Medium helgrind/drd tests for obj_pmalloc_mt

---

src/benchmarks/benchmark.hpp
src/benchmarks/obj_pmalloc.cpp

A simple benchmark that mixes allocations and deallocations in a single run. This workload puts a strain on the memory reuse mechanisms in the heap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2314)

benchmark: add mixed allocator workload

---

src/jemalloc/include/jemalloc/internal/chunk.h
src/jemalloc/src/chunk.c
src/jemalloc/src/jemalloc.c
src/libvmmalloc/libvmmalloc.c

Ref: pmem/issues#665
Ref: pmem/issues#639
There are some more bugs around fork in vmmalloc/jemalloc, so the vmmalloc_fork tests still fail with helgrind.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2318)

Jemalloc lock order fixes

---

src/libpmemobj/obj.c
src/test/obj_list/obj_list_mocks.c
src/test/pmem_valgr_simple/pmemcheck0.log.match

Need to mark lock list heads as non-persistent.
Memset on FreeBSD does 8 1-byte writes in pmem_valgr_simple.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2316)

common: pmemcheck fixes for FreeBSD

---

src/test/obj_pmalloc_rand_mt/obj_pmalloc_rand_mt.c

Make a local copy of the seed to avoid a race on FreeBSD in
rand_r(). It's not clear why the race is not triggered with
a global seed on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2320)

test: Fix race in obj_pmalloc_rand_mt

---

src/include/libpmemobj++/pool.hpp
src/test/obj_cpp_ptr/obj_cpp_ptr.cpp

Persist and flush functions should be performed on the persistent
object, not the smart pointer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2319)

obj: fix pool's C++ persist and flush functions

---

src/common/out.h

ASSERTeq does not abort when called in release mode, but it still
evaluates its arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2173)

common: ifdef out asserts that call some functions

---

src/common/file_linux.c
src/test/vmmalloc_init/TEST3
src/test/vmmalloc_init/TEST4
src/test/vmmalloc_init/grep3.log.match
src/test/vmmalloc_init/grep4.log.match

This affects vmem, vmmalloc and pmemdetect (tool we use in tests).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2322)

common: use O_TMPFILE to create temporary files

---

src/common/os_linux.c
src/libpmem/pmem.c

Since util_tmpfile() already uses O_TMPFILE flag if it's supported,
there is no need to deal with O_TMPFILE in pmem.c anymore.
If O_CREAT or O_TMPFILE flag is specified then mode argument is
mandatory and os_open() must pass it to open().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2324)

pmem: fix using O_TMPFILE

---

src/test/obj_tx_lock/TEST0
src/test/obj_tx_lock/obj_tx_lock.c

drd complained about calling trywrlock on already locked rwlock
Ref pmem/issues#662
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2327)

test: obj_tx_lock fix and disbale drd

---

src/test/vmmalloc_fork/TEST1
src/test/vmmalloc_fork/TEST3

Ref: pmem/issues#639
Ref: pmem/issues#665
Apparently valgrind just can't handle the way jemalloc
uses mutexes across forks, as demonstrated by this
dummy program:
```
$ cat dummy.c
pthread_mutex_t dummy = PTHREAD_MUTEX_INITIALIZER;
static void prefork(void)
{
pthread_mutex_lock(&dummy);
}
static void postfork_child(void)
{
pthread_mutexattr_t attr;
if (pthread_mutexattr_init(&attr) != 0)
abort();
if (pthread_mutex_init(&dummy, &attr) != 0) {
pthread_mutexattr_destroy(&attr);
abort();
}
pthread_mutexattr_destroy(&attr);
}
static void postfork_parent(void)
{
pthread_mutex_unlock(&dummy);
}
int main()
{
pthread_atfork(prefork,
postfork_parent, postfork_child);
fork();
pthread_mutex_lock(&dummy);
pthread_mutex_unlock(&dummy);
}
$ cc -pthread dummy.c -o dummy
$ valgrind --tool=helgrind ./dummy …
```

test: Disable drd, helgrind in vmmalloc_fork tests

---

src/test/vmmalloc_init/TEST16
src/test/vmmalloc_init/TEST6

All valgrind tools should be disabled for this tests.
Ref pmem/issues#666
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2331)

test: force-disable drd in vmmalloc_init tests

---

src/test/obj_lane/obj_lane.c

set lane layout to non-null value because drd gives assertion fail
when calling VALGRIND_ANNOTATE_NEW_MEMORY with null pointer
Ref pmem/issues#661
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2343)

test: obj_lane test fix

---

src/libpmemobj/ringbuf.c

check if pointer is null before calling VALGRIND_ANNOTATE_NEW_MEMORY
Ref pmem/issues#660
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2344)

obj: check for null in ringbuf_dequeue_s

---

src/test/ex_libpmemobj/TEST17

The test only executes the same executable with all
test-build-types, there is no statically linked version
examples/libpmemobj/list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2350)

test: Required build types in ex_libpmemobj/TEST17

---

src/test/obj_basic_integration/TEST10

This test verifies that there are no msync issued on the device
dax mapped region, but it seems that asan calls msync on its own
and pollutes the strace output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2378)

test: disable obj_basic_integration/10 under asan

---

src/test/RUNTESTS

The environment variable VERBOSE_TESTS allows to set a colon
separated list of tests which will be run with a verbose output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2380)

test: add a variable VERBOSE_TESTS list

---

src/libpmemobj/heap.c

Ref: pmem/issues#694
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2389)

obj: fix definition of SIZEOF_RUN macro

---

src/jemalloc/src/jemalloc.c
src/libvmmalloc/libvmmalloc.c
src/test/unittest/ut.c

fixed proper library destruction order (before this patch
jemalloc destructor was called before vmmalloc's) and ignore
calls to free after vmmalloc is destroyed
Ref pmem/issues#659
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2368)

jemalloc and vmmalloc fixes

---

src/common/os_linux.c
src/test/vmmalloc_dummy_funcs/Makefile

Address issues introduced in PR #2357 and #2384.
Add secure_getenv function in os_linux.c (not in FreeBSD).
Fix dependencies, add clean/clobber in vmmalloc_dummy_funcs
Makefile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2391)

common: Fix FreeBSD breakage

---

src/test/obj_convert/TEST19

obj_convert/TEST19 fails under valgrind 3.10
Ref pmem/issues#617
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2394)

test: obj_convert require valgrind 3.11

---

src/common/mmap.h
src/common/mmap_linux.c
src/test/util_map_proc/TEST6
src/test/util_map_proc/out0.log.match
src/test/util_map_proc/out1.log.match
src/test/util_map_proc/out2.log.match
src/test/util_map_proc/out3.log.match
src/test/util_map_proc/out4.log.match
src/test/util_map_proc/out5.log.match
src/test/util_map_proc/out6.log.match
src/test/util_map_proc/util_map_proc.c

Support llvm address sanitizer in test/util_map_proc.
Llvm address sanitizer interposes fopen, so util_map_proc
cannot also interpose it. It is not possible to address
this at runtime.
Change util_map_hint* to take alternate map file argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2335)

common: util_map_proc asan compatibility

---

doc/libpmem/pmem_is_pmem.3.md
doc/libpmemblk/pmemblk_create.3.md
doc/libpmemobj/pmemobj_mutex_zero.3.md
doc/libvmem/libvmem.7.md
doc/libvmmalloc/libvmmalloc.7.md

Merge Linux and FreeBSD man pages.
Remove _BSDWX macros from pmemobj_mutex_zero.3.md
and libvmmalloc.7.md.
Fix cross references.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2398)

doc: Doc cleanup, Ref pmem/issues#701

---

src/test/unittest/unittest.sh

Export the 'log' variables (*_LOG_LEVEL and *_LOG_FILE)
in the 'require_nodes()' function so that they were exported
in all remote unit tests (not only in those using
the 'init_rpmem_on_node()' function).
It also fixes the following issue:
Ref: pmem/issues#702
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2400)

test: export log variables in require_nodes()

---

src/libpmemobj/memblock.c
src/libpmemobj/memblock.h
src/libpmemobj/palloc.c
src/libpmemobj/palloc.h
src/libpmemobj/tx.c

Always reinitialize headers of undo logged objects before reading
any values from them.
Ref: pmem/issues#705
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2419)

obj: fix memcheck tx_abort instrumentation

---

src/test/obj_action/TEST0
src/test/obj_action/TEST1
src/test/obj_action/memcheck1.log.match

Fix name of TEST1 and memcheck1.log.match.
Fix matches for FreeBSD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2422)

test: obj_action fixes

---

src/libpmemobj/list.c
src/libpmemobj/tx.c

This patch changes the log level of functions that are executed
exceedingly often. The lane related logs now have level 7, and
rarer, often nested, functions have level 5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2423)

obj: increase log level of spamming functions

---

src/jemalloc/src/jemalloc.c

For the purpose of pmemcto_check(), the entire memory pool must be
marked as defined in Valgrind.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2424)

cto: fix memcheck errors in pmemcto_check

---

src/libpmemobj/palloc.c

Casting to int loses signedness of the value, which might
cause irregular sorting outcome if the locks are spaced far
apart.
Thanks @mslusarz :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2429)

obj: fix qsort lock ptr comparision

---

doc/libpmem/pmem_is_pmem.3.md
src/common/file.h
src/common/file_linux.c
src/common/file_windows.c
src/common/mmap.c
src/libpmem/pmem.c
src/libvmmalloc/libvmmalloc.c
src/test/pmem_map_file/TEST0
src/test/pmem_map_file/TEST0.PS1
src/test/pmem_map_file/mocks_linux.c
src/test/pmem_map_file/mocks_windows.c
src/test/pmem_map_file/out0.log.match
src/test/pmem_map_file/out1.log.match
src/test/pmem_map_file_win/mocks_windows.c
src/test/pmem_map_file_win/out1.log.match

If PMEM_FILE_CREATE is specified without PMEM_FILE_EXCL and
PMEM_FILE_SPARSE, the file already exists, and len is less than the
existing file length, always truncate the file to the desired length
using ftruncate(3).
Make PMEM_FILE_TMPFILE specified with PMEM_FILE_EXCL behave the same
as O_TMPFILE specified with O_EXCL for open(2).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2402)

pmem: fix pmem_map_file behavior

---

src/common/set.c
src/common/set.h
src/examples/libpmemcto/libart/Makefile
src/examples/libpmemcto/libart/arttree.c
src/examples/libpmemcto/libart/arttree.h
src/libpmemblk/blk.c
src/libpmemcto/Makefile
src/libpmemlog/log.c
src/libpmemobj/obj.c
src/libpmempool/replica.c
src/test/cto_valgrind/TEST1
src/test/cto_valgrind/TEST3
src/test/cto_valgrind/cto_valgrind.c
src/test/cto_valgrind/memcheck2.log.match
src/test/cto_valgrind/memcheck4.log.match
src/test/cto_valgrind/memcheck5.log.match
src/test/cto_valgrind/out1.log.match
src/test/freebsd.supp
src/test/unittest/unittest.sh
src/tools/Makefile.inc

Fix libpmemcto/Makefile to use pmemcommon.inc.
Add util_poolset_fdclose_always; remove #ifdef __FreeBSD__ guards
around util_poolset_fdclose.
Fix definition order in examples/libpmemcto/libart/Makefile.
Add RESET_GETOPT macro in examples/libpmemcto/libart.
Lock around pool creation/deletion in test/cto_multiple_pools
to prevent mmap race.
Compatibility fixes to test/cto_valgrind.
Fix dump_last_n_lines when argument is blank (unittest.sh).
Use $(LIBDL) in src/tools/Makefile.inc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2415)
Ref: #1979

common: FreeBSD cto port

---

src/libpmemobj/alloc_class.c
src/test/obj_ctl_alloc_class/obj_ctl_alloc_class.c

This patch fixes an infinite loop that happened when trying to
allocate objects that are too large for the allocation class.
Ref: pmem/issues#696
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2440)

obj: fix allocs whose size_idx exceed nallocs

---

src/librpmem/rpmem_fip.c
src/tools/rpmemd/rpmemd.c

Rpmemd will register the remote pool with header, but expose without header
to a user. This way rdma will work always with page aligned memory region.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2425)

rpmem: handle huge pages in rpmemd

---

src/libpmemobj/container_seglists.c
src/libpmemobj/pmalloc.c

FYI, I discovered those 2 patches today. Yes, discovered :). I wrote them in May, but I forgot to submit them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2443)

obj: speed up pmemobj_open with compiled-in Valgrind support

---

src/test/vmem_multiple_pools/TEST1.PS1

This test fails all the time on AppVeyor, making the appveyor build
almost useless. Since nobody cares enough to fix it, let's disable
it for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2451)

test: change vmem_multiple_pools/TEST1 to long

---

doc/Makefile
doc/generated/pmemobj_xreserve.3
doc/libpmemobj/pmemobj_action.3.md
src/include/libpmemobj/action_base.h
src/libpmemobj/libpmemobj.def
src/libpmemobj/libpmemobj.map
src/libpmemobj/obj.c
src/test/obj_ctl_alloc_class/obj_ctl_alloc_class.c
src/test/scope/out4.log.match
src/test/scope/out4w.log.match

This adds the ability to reserve using a custom allocation class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2447)

obj: implement pmemobj_xreserve()

---

src/test/drd-log.supp
src/test/obj_pmalloc_mt/TEST3

Silences selected data race reports found by Valgrind 3.12 drd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2449)

test: add suppressions for DRD in CTO tests

---

src/test/vmmalloc_valgrind/TEST1
src/test/vmmalloc_valgrind/TEST2
utils/docker/images/install-valgrind.sh

For some tests, older versions of valgrind reports false-positives.
Valgrind 3.10 does not even build on current travis environment with clang 3.9 and on 3.11 some valgrind tests fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2448)

common: switch to Valgrind 3.12

---

src/librpmem/rpmem.c
src/rpmem_common/rpmem_fip_common.c

The number of lanes has to be limited prior to establishing
the out-of-band connection.
Ref: pmem/pmdk#2397
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2466)

rpmem: RPMEM_MAX_NLANES fix

---

doc/libpmemobj/pmemobj_root.3.md

... in case when the requested size equals to 0.
Ref: pmem/issues#733
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2494)

doc: clarify pmemobj_root behavior

---

src/examples/libpmemobj/libart/.gitignore
src/examples/libpmemobj/libart/Makefile
src/examples/libpmemobj/libart/arttree.c
src/examples/libpmemobj/libart/arttree_examine.c
src/examples/libpmemobj/libart/arttree_search.c
src/examples/libpmemobj/libart/arttree_structures.c
src/examples/libpmemobj/libart/arttree_structures.h

Fixes memory leaks in arttree example for libpmemobj.
Instead of mapping nodes on demand, the entire file is mapped at start
and get_node() function only calculates the node address by adding
offset to the base mapping address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2489)

examples: fix arttree for libpmemobj

---

src/test/rpmem_basic/TEST12
src/test/rpmem_basic/config.sh

Sockets provider does not detect fi_cq_signal so it does not return
from fi_cq_sread. It causes rpmem_basic/TEST12 to hang sporadically.
Ref: ofiwg/libfabric#3645
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2497)

test: rpmem_basic test requires libfabric fix

---

src/benchmarks/rpmem_persist.cpp
src/common/set.c
src/libpmemobj/obj.c
src/libpmemobj/obj.h
src/libpmempool/replica.c
src/libpmempool/sync.c
src/librpmem/rpmem.c
src/rpmem_common/rpmem_common.h
src/test/rpmem_basic/TEST13
src/test/rpmem_basic/rpmem_basic.c
src/tools/rpmemd/rpmemd.c

With this patch, the whole remote and local pools are being registered to RDMA and the first 4KB of the remote pool is protected against writing. This way remote replicas on multiple Device DAX devices with alignment different than 4KB can be used.
This is the continuation of the PR with documentation: https://github.com/pmem/pmdk/pull/2463
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2492)

rpmem: register whole pool in RDMA

---

src/test/libpmempool_rm_remote/TEST3
src/test/obj_rpmem_basic_integration/TEST12
src/test/testconfig.sh.example
src/test/unittest/unittest.sh

There can be only one device dax specified for each node.
Ref: pmem/issues#739
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2505)

test: fix NODE_DEVICE_DAX_PATH usages

---

src/common/set.c
src/test/obj_extend/TEST1

The part names in directory sets are padded by leading zeroes.
What else leads with zeroes? Octal values ;) We need to explicitly
tell strtol that we want decimal numbers when deducing the part id
from its file name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2506)

common: fix loading more than 8 parts in a dir

---

src/test/match

SPDK would like to use match in our project but need one specific
feature as our test tool output can contain a variable number of
irrelevant and platform specific information making the creation
of .match files very time consuming and with every new platform
we add to our test pool we'd need to update all match files.
The proposed changes here aren't needed for PMDK but a quick
review would be appreciated and obviously you are welcome to
merge them.
The idea is that the developer create an optional .ignore file
along with the .match file. The .ignore file contains one string
per line that the match program uses to effectively ignore any
comparisons on lines that have that string anywhere in them. The
updated match utility simply filters the match file and the output
file and removes any …

test: add new feature to match utility

---

src/libpmemobj/heap.c

Every time we recycle an old chunk, helgrind will be from now on
told to clear the history of memory that is occupied by the relevant
chunk headers.
Ref: pmem/issues#709
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2512)

obj: clean vg state of headers at every init

---

src/test/obj_constructor/TEST1

The execution of this test takes about 1 minute on a local machine.
On Travis it's about 2-3 times longer, so it timeouts periodically.
Move it to 'long'  until we have a better solution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2534)

test: move obj_constructor TEST1 to 'long' group

---

src/jemalloc/include/jemalloc/internal/rb.h
src/test/obj_cpp_ptr_arith/TEST0

Only disable undefined sanitizer in jemalloc rb.h for
clang < 3.9.
Temporarily add require_no_asan to obj_cpp_ptr_arith/TEST0
due to bug.
*All* short and medium tests, including C++ tests, now build and pass with both the
sanitizer and valgrind on FreeBSD 11.1 using the native llvm4.0 compiler (except
tests requiring real DAX or verbs, which build but are skipped).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2533)

common: Sanitizer changes for llvm4.0/FreeBSD

---

src/libpmemobj/obj.c
src/test/obj_pool/TEST31
src/test/obj_pool/TEST31.PS1
src/test/obj_pool/obj_pool.c
src/test/obj_pool/out31.log.match

pmemobj_open() function wasn't cleaning up the global state
after an error resulting in failures of subsequent opens
Ref: pmem/issues#750
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2535)

obj: fix pmemobj_open() error handling

---

doc/libpmem/pmem_memmove_persist.3.md
src/libpmem/pmem.c

Removes unnecessary SFENCE from pmem_memcpy_nodrain() and
pmem_memset_nodrain() functions, since the memory barrier is done by
pmem_drain().  This fence is only required for platforms using
strongly-ordered CLFLUSH, as pmem_drain() is empty in such case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2542)

pmem: improve pmem_memcpy_nodrain performance

---

README.md
src/Makefile
src/libpmem/pmem.c

This patch changes the build requirement for 
AARCH64. Just regular "make" command is sufficient
to build in ARM processor. This patch also removes additional
CFLAGS required for building in ARM processor.
This patch also fixes a typo in the Makefile for ARM
builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2553)

pmem: change aarch64 macro and improve makefile for ARM64 build

---

src/test/obj_persist_count/mocks_windows.h
src/test/obj_persist_count/obj_persist_count.c
src/test/obj_persist_count/out0.log.match
src/test/obj_persist_count/out1.log.match

1) measure impact of an empty transaction
2) count cachelines stored and drains from memcpy/memmove/memset
3) count overall number of cachelines stored and drains
4) exclude transaction start overhead from transactional operations
5) count number of potential cache misses, by looking at type, address
and length of the operation, assuming that there was a store
before and cache was empty
6) stop using tabs in output
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2551)

tests: improve reporting of performance indicators

---

src/test/obj_memcheck/memcheck0.log.match

If the test is compiled without -DUSE_VALGRIND but the OS contains vg, the test will run but the match will fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2560)

test: fix obj_memcheck match when compiled w/o vg

---

src/common/set.c

This is difficult to test for because it requires the posix_fallocate to fail during pool extend.
Ref: pmem/issues#758
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2562)

common: fix possible double free of part path

---

src/common.inc
src/common/pmemcommon.inc
src/test/Makefile.inc

Move osdep function into common.inc.
Fixes in test/Makefile.inc: Use osdep function as needed,
"nodebug" should be "nondebug", remove extranenous "$(COMMON)/".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2566)

common: Fix makefile breakage from PR#2388

---

src/test/vmmalloc_malloc_hooks/grep2.log.match
src/test/vmmalloc_malloc_hooks/out0.log.match
src/test/vmmalloc_malloc_hooks/vmmalloc_malloc_hooks.c

The recent version of gcc (8.0), replaces 'realloc(NULL, size)'
with 'malloc(size)' at compile time.  This changes the behavior
of the test, as the actual realloc() (and its hook) is never called.
To test realloc hook, it must be called with a non-NULL pointer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2575)

test: fix vmmalloc_malloc_hooks

---

src/libpmempool/Makefile
src/librpmem/Makefile
src/tools/Makefile.inc
src/tools/rpmemd/Makefile

Adds explicit dependency on libptherad to libpmempool and librpmem.
Fixes required libs evaluation when linking tools.
Ref: pmem/issues#767
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2559)

common: fix library dependencies

---

src/libpmempool/Makefile
src/librpmem/Makefile
src/tools/Makefile.inc
src/tools/rpmemd/Makefile

Adds explicit dependency on libptherad to libpmempool and librpmem.
Fixes required libs evaluation when linking tools.
Ref: pmem/issues#767
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2558)

common: fix library dependencies (1.3.x)

---

src/test/pmem_deep_persist/TEST0
src/test/pmem_deep_persist/TEST1
src/test/pmem_deep_persist/TEST2
src/test/pmem_deep_persist/TEST3
src/test/pmem_deep_persist/TEST4
src/test/pmem_deep_persist/TEST5
src/test/pmem_deep_persist/TEST6
src/test/pmem_deep_persist/TEST7
src/test/pmem_deep_persist/TEST8
src/test/pmem_deep_persist/TEST9
src/test/unittest/unittest.sh

Add count_lines function in unittest.sh. Use for
pmem_deep_persist tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2592)

test: Portable line count support

---

src/libpmemobj/ravl.c
src/libpmemobj/ravl.h
src/libpmemobj/tx.c
src/test/obj_ravl/TEST0
src/test/obj_ravl/obj_ravl.c

This patch fixes a performance regression introduced in the RAVL patch
by allowing data buffers larger than 8 bytes in ravl_node, which
faciliates storing large data buffers directly in nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2597)

obj: remove one malloc() from add range path

---

src/librpmem/rpmem.c
src/librpmem/rpmem_obc.c
src/librpmem/rpmem_obc.h
src/rpmem_common/rpmem_common.h
src/rpmem_common/rpmem_proto.h
src/test/rpmem_obc/rpmem_obc_test_close.c
src/test/rpmem_obc/rpmem_obc_test_misc.c
src/test/rpmem_obc_int/rpmem_obc_int.c
src/test/rpmem_proto/rpmem_proto.c
src/test/rpmemd_obc/rpmemd_obc_test_common.c
src/tools/rpmemd/rpmemd.c
src/tools/rpmemd/rpmemd_obc.c
src/tools/rpmemd/rpmemd_obc.h

Ref: pmem/issues#721
This patch introduces flag to rpmem_obc_close which can specify whether to remove pool after closing.
It's needed because in some cases (when there is an error on client side), server thinks that connection
was established and doesn't call cleanup routine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2589)

rpmem: fixed removing remote pool

---

src/common/set.c

Coverity warned that dereferencing a null pointer could happen.
CID 187264
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2609)

common: fix Coverity issue

---

src/libpmemobj/pvector.c
src/libpmemobj/tx.c
src/test/obj_pmalloc_mt/obj_pmalloc_mt.c
src/test/obj_pvector/obj_pvector.c

When pvector_reserve was called with new capacity exceeding that
of a single array, it left a hole in the vector's array that later
interfered with capacity calculations, leading to invalid
dereferences.
pmem/issues#788
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2613)

obj: fix large vector reserves

---

src/libpmemobj/obj.c

Only adds assertions for debug build.
Ref: pmem/issues#772
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2629)

obj: validate pe_offset in pmemobj_list_* APIs

---

src/test/RUNTESTLIB.PS1
src/test/RUNTESTS
src/test/unittest/unittest.ps1
src/test/unittest/unittest.sh

If PMEM_FS_DIR (or NON_PMEM_FS_DIR) is set it must point to
valid directory. If RUNTEST is run with -f pmem/non-pmem
PMEM_FS_DIR/NON_PMEM_FS_DIR must be specified and valid.
Ref: pmem/issues#751
Ref: pmem/issues#790
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2620)

test: fixes for checking PMEM_FS_DIR and NON_PMEM_FS_DIR

---

doc/librpmem/rpmem_persist.3.md
src/common/set.c
src/common/set.h
src/include/librpmem.h
src/librpmem/rpmem.c
src/librpmem/rpmem_fip.c
src/librpmem/rpmem_fip.h
src/rpmem_common/rpmem_fip_common.c
src/rpmem_common/rpmem_proto.h
src/test/rpmem_basic/TEST14
src/test/rpmem_basic/TEST15
src/test/rpmem_basic/rpmem_basic.c
src/test/rpmem_fip/rpmem_fip_test.c
src/test/rpmem_proto/rpmem_proto.c
src/tools/rpmemd/rpmemd.c
src/tools/rpmemd/rpmemd_fip.c
src/tools/rpmemd/rpmemd_fip.h

Implementation of remote deep flush function which
performs WPQ flush on the remote node for given address, size and lane
number. The rpmem_deep_flush() function works exactly the same as
rpmem_persist() using GPSPM. It copies the desired data to remote node
using RDMA WRITE operation, then sends the 'deep flush' operation
using RDMA SEND and finally waits for response message.
Since the rpmemd must receive and process the 'deep flush' operation
message it must read the completion queue in APM mode as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2457)

rpmem: remote deep flush implementation

---

src/jemalloc/src/jemalloc.c
src/libvmem/libvmem_main.c
src/libvmem/vmem.c

... to fix memory leaks in libvmem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2601)

vmem: (win) call jemalloc ctor/dtor from DllMain

---

src/test/pmempool_rm_remote/TEST2
src/test/rpmemd_db/rpmemd0.log.match
src/test/rpmemd_db/rpmemd1.log.match
src/test/rpmemd_db/rpmemd_db_test.c
src/tools/rpmemd/rpmemd_db.c

Remove all existing part files on remote node even if one of them is
missing.
Ref: pmem/issues#599
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2633)

rpmem: remove all remaining parts on remote node

---

src/examples/libpmemobj++/pmpong/Makefile

Avoids this warning on make clobber:
head: cannot open 'clean-progs' for reading: No such file or directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2653)

examples: fix pmpong build issue

---

src/Makefile

EXTRA_CFLAGS in user.mk was overwriting EXTRA_CFLAGS set by
src/Makefile, which means jemalloc did not detect Valgrind headers,
and that caused all [vmem|vmmalloc|cto]_valgrind tests to fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2658)

common: fix interaction between jemalloc & user.mk

---

src/common/file.c
src/common/file_posix.c
src/common/os.h

Define os_major and os_minor macros for portability
(Linux is unsigned, FreeBSD is signed).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2659)

common: add os_major/os_minor

---

src/common/os_deep_linux.c

In some cases it is expected that there is no deep_flush file. ERR cover other potential errors that occur.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2660)

common: deep_flush change ERR to LOG

---

src/common/file_posix.c
src/common/os_deep_linux.c

In some cases it is expected that there is no deep_flush file. ERR cover other potential errors that occur.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2666)

common: change ERR to LOG in some cases

---

src/test/pmem_deep_persist/TEST8
src/test/pmem_deep_persist/TEST9
src/test/tools/pmemdetect/pmemdetect.c
src/test/unittest/unittest.sh

Ref: pmem/issues#802
This patch allows skip test if device dax region id does not exist
(in practice it will skip only for old kernels - second part of pmem issue #802)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2667)

test: add require_dev_dax_region

---

doc/libpmemobj/pmemobj_ctl_get.3.md
src/examples/libpmemobj/slab_allocator/slab_allocator.c
src/include/libpmemobj/ctl.h
src/libpmemobj/pmalloc.c
src/test/obj_ctl_alloc_class/obj_ctl_alloc_class.c
src/test/obj_ctl_alloc_class_config/alloc_class_config

We need to add the alignment field now so that it's easier to
introduce this feature in the next version of the library
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2675)

obj: add unused alignment fields to alloc class

---

src/common/pool_hdr.c
src/common/pool_hdr.h
src/common/set.c
src/test/obj_check/out1.log.match

This is to produce a valid error message in case the user attempts
to open the pool created by PMDK version 1.4 (or later).
Since the pool header checksum calculation has been modified in
PMDK 1.4, old libraries will fail to open new pools, but the error
message would report the invalid checksum, instead of incompatible
pool format or features.
With this patch, the pool signature, format and compat/incompat
flags are validated before the pool header checksum.
If feature flags or pool format are corrupted, but their value
would pass the check, opening the pool would fail anyway after
checkum validation.  However, if this is a new pool, then error
message would indicate incompatible format/features, not
the wrong checksum.
---
This change is [<img …

common: reorder pool header consistency checks

---

src/common/set.c
src/test/util_poolset_parse/grep0.log.match
src/test/util_poolset_parse/grep0w.log.match

In some cases, pmempool used to report "Invalid argument" error,
while the actual problem was different, i.e. "Permission denied".
Ref: pmem/issues#815
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2677)

common: report actual errors in poolset parser

---

src/test/drd-log.supp
src/test/helgrind-log.supp

Fixes failing tests on Fedora 28/rawhide.
(gcc 8.0, glibc 2.27, valgrind 3.13)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2700)

test: update Valgrind suppression files

---

src/test/log_recovery/TEST0
src/test/log_recovery/TEST1
src/test/obj_recovery/TEST0
src/test/obj_recovery/TEST1
src/test/obj_recovery/TEST2
src/test/obj_recovery/TEST3
src/test/obj_recovery/TEST4
src/test/obj_recovery/TEST5
src/test/obj_recovery/TEST6
src/test/obj_recovery/TEST7
src/test/obj_recovery/TEST8

These tests simulate application crash, and intentionally leave some
stores not flushed to persistence.  So, running those tests under
pmemcheck does not make sense.
Ref: pmem/issues#827
Ref: pmem/issues#828
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2701)

test: disable pmemcheck in recovery tests

---

utils/pmdk.spec.in

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2709)

common: by default build rpms without ndctl

---

src/test/pmem_has_auto_flush/mocks_posix.c

There is mock for `fs_new` and `open`, but that is not enough.
Before `fs_new` and `open` `os_auto_flush()` calls `os_stat` and checks return value.
This patch fix `pmem_has_auto_flush/TEST6 ` on machines where `"/sys/bus/nd/devices"` does not exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2712)

test: pmem_has_auto_flush add os_stat mock

---

src/common/set.c
src/common/set.h
src/libpmemobj/heap.c
src/test/obj_extend/TEST7
src/test/obj_extend/obj_extend.c
src/test/util_poolset/util_poolset.c

If extending the pool with default growth size would exceed reservation
size, adjust new part size to fit reservation size.  In such case, part
size cannot be smaller than minimum part size for given pool type.
Ref: pmem/issues#823
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2724)

obj: adjust extend size to reservation size

---

src/test/pmempool_transform/TEST22
src/test/pmempool_transform/out22.log.match

Test requires four Device-DAX devices - two with 4K alignment and two
with 2M alignment.  One pair of devices acts as an input pool set,
while the other pair will become the new replica added to the pool set
using 'pmempool transform' command.  The devices must be arranged in
the way that their internal alignment is the same within given replica
and the total size of the replica being added cannot be smaller than
the size of the original pool.
Ref: pmem/issues#809
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2727)

test: sort devices in pmempool_transform TEST22

---

src/libpmemobj/tx.c

This patch further optimizes the transient state of the add range
function by:
- changing the algorithm back to walking from the end of the
range to its beginning, allowing us to eliminate at least one
tree search per call
- merging adjacent tree range nodes, thus improving the
efficency of the ranges search for workloads performing a lot of
snapshots per transaction
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2662)

obj: implement backward merging ranges algorithm

---

src/common/badblock_linux.c

For unknown reasons it is not included automatically
by fcntl.h on CentOS 7.4 and RHEL 7.3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2735)

common: include linux/falloc.h in badblock_linux.c

---

src/test/RUNTESTS

Removes duplicates and prints each failed test name in a new line.
Applies to tests run with KEEP_GOING flag set.
Ref: pmem/issues#760
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2734)

test: improve the format of failed tests report

---

src/common/badblock_freebsd.c
src/common/extent_freebsd.c
src/common/pmemcommon.inc
src/test/Makefile.inc
src/test/pmem_deep_persist/Makefile
src/test/unittest/unittest.sh
src/test/util_badblock/TEST0
src/test/util_poolset/grep1.log.match
src/test/vmem_valgrind_region/memcheck2.log.match
src/test/vmem_valgrind_region/memcheck4.log.match

Use long for level in fs_entry (common/fs.c).
Add FreeBSD stubs for badblock handling.
Close files in cto_dirty test.
Define FALLOCATE in unittest.sh, use in util_badblock test.
Anonymize offset in vmem_valgrind_region memcheck4.log.match.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2745)

common: FreeBSD compatibility fixes

---

src/test/cto_dirty/TEST0
src/test/cto_dirty/TEST0.PS1
src/test/cto_dirty/TEST1
src/test/cto_dirty/TEST1.PS1
src/test/cto_dirty/cto_dirty.c

Modifies test scripts to expect abnormal exit for the first run of the
test program, when the crash is simulated.  Since DONE() macro is no
longer called in case of simulated failure, there should be no problem
with left-over open files reported by check_open_files() on FreeBSD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2751)

test: do not call DONE() when simulating app crash

---

src/test/obj_sds/TEST1
src/test/obj_sds/TEST2
src/test/obj_sds/TEST3
src/test/obj_sds/TEST4
src/test/obj_sds/TEST5
src/test/obj_sds/TEST6
src/test/obj_sds/TEST7
src/test/obj_sds/obj_sds.c

Call exit(1) rather than DONE() when fail is set.
Check for abnormal exit when fail is set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2756)

test: Simulated failure fixes for obj_sds.

---

src/common/extent_linux.c

Zero array of extents just to silent the memcheck's error:
Conditional jump or move depends on uninitialised value(s)
test_size (util_extent.c:70)
main (util_extent.c:85)
Ref: pmem/issues#838
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2757)

common: zero extents to silent memcheck's error

---

src/common/os_thread_windows.c
src/test/obj_sync/obj_sync.c

It was possible to return with ETIMEDOUT at least 100ns (possibly up to 1us) before reaching specified timeout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2766)

common: (win) fix timed locks

---

ChangeLog
src/windows/include/sys/select.h

Adds fake header file to fix failing build on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2772)

test: [1.3] fix building on Windows

---

src/test/tools/pmemdetect/pmemdetect.c

Invert the logic of return value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2790)

test: fix checking for MAP_SYNC in pmemdetect
