utils/SRCVERSION.ps1
accept tags in format <major>.<minor>-<anystring>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1546)
=> win: update SRCVERSION script

src/jemalloc/include/jemalloc/jemalloc_macros.h.in, src/jemalloc/msvc/jemalloc.vcxproj, src/libvmem/libvmem.vcxproj, src/windows/jemalloc_gen/include/jemalloc/jemalloc.h, utils/CREATE-ZIP.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1550)
=> win: link jemalloc lib statically

src/common/common.rc, src/libpmempool/libpmempool.vcxproj.filters, src/libvmem/libvmem.rc, src/libvmem/libvmem.vcxproj, src/libvmem/libvmem.vcxproj.filters
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1554)
=> win: add resource file for libvmem versioning

utils/build-dpkg.sh
Corrects path handling in the script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1555)
=> dpkg: fix path handling in build-dpkg.sh

src/test/vmem_aligned_alloc/vmem_aligned_alloc.vcxproj, src/test/vmem_check/vmem_check.vcxproj, src/test/vmem_check_allocations/vmem_check_allocations.vcxproj, src/test/vmem_custom_alloc/vmem_custom_alloc.vcxproj, src/test/vmem_malloc/vmem_malloc.vcxproj, src/test/vmem_malloc_usable_size/vmem_malloc_usable_size.vcxproj, src/test/vmem_mix_allocations/vmem_mix_allocations.vcxproj, src/test/vmem_multiple_pools/vmem_multiple_pools.vcxproj, src/test/vmem_out_of_memory/vmem_out_of_memory.vcxproj, src/test/vmem_realloc/vmem_realloc.vcxproj, src/test/vmem_realloc_inplace/vmem_realloc_inplace.vcxproj, src/test/vmem_stats/vmem_stats.vcxproj, src/test/vmem_strdup/vmem_strdup.vcxproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1556)
=> win: fix references identity to vmem

doc/libpmemblk.3.md
Ref: pmem/issues#384
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1562)
=> doc: fix typo in libpmemblk man page

src/common/queue.h
This is a workaround for reported clang static analyzer false
positives from queue.h.
Ref: pmem/issues#309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1548)
=> common: queue.h clang static analyzer fix

src/examples/libpmemobj/doc_snippets/Makefile, src/examples/libpmemobj/hashmap/Makefile, src/examples/libpmemobj/list_map/Makefile, src/examples/libpmemobj/tree_map/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1557)
=> examples: Remove unused LIBS variable from some makefiles

src/common/util.h
The isset, setbit macros are defined in sys/param.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1560)
=> common: Include param.h in util.h

utils/docker/images/Dockerfile.ubuntu-16.04, utils/docker/images/install-libcxx.sh
Install a customized version of libcxx both on ubuntu and fedora.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1558)
=> docker: add custom libcxx install step

src/benchmarks/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1565)
=> benchmarks: fix build with automatic cstyle check

src/benchmarks/blk.cpp, src/benchmarks/clo.cpp, src/benchmarks/pmembench.cpp, src/benchmarks/pmemobj_tx.cpp, src/common/set.c, src/examples/libpmemobj/array/array.c, src/examples/libpmemobj/libart/arttree_examine.c, src/examples/libpmemobj/libart/arttree_search.c, src/examples/libvmem/libart/art.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1566)
=> common: fix various issues detected by Coverity

doc/libpmemobj.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1568)
=> doc: fix invalid description of zrealloc and strdup

.travis.yml, utils/docker/build.sh, utils/docker/pull-or-rebuild-image.sh, utils/docker/run-coverity.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1567)
=> common: run Coverity scan from NVML build scripts

src/benchmarks/log.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1574)
=> benchmark: add missing long option name

src/benchmarks/map_bench.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1578)
=> benchmarks: fix size_per_key in map_bench

src/test/RUNTESTS.ps1, src/test/unittest/unittest.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1582)
=> win: RUNTESTS.PS1 fixes

src/test/unittest/unittest.sh
The check script returned an incorrect value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1588)
=> vmmalloc: fix valgrind version check

src/include/libpmemobj++/detail/persistent_ptr_base.hpp
Ref: pmem/issues#386
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1591)
=> cpp: return persistent_ptr::swap to being public

src/tools/rpmemd/rpmemd_config.c
Minor fix deleting death code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1586)
=> rpmemd: remove dead code

src/examples/libvmem/manpage.vcxproj, src/test/set_funcs/set_funcs.c, src/test/set_funcs/set_funcs.vcxproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1584)
=> win:  removed unnecessary ifdefs and dependencies

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1587)
=> doc: update build dependencies information

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1606)
=> common: removed redundant empty lines

src/tools/rpmemd/rpmemd_fip.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1601)
=> rpmemd: simplify error handling

src/test/obj_list/obj_list_mocks.c, src/test/obj_pmalloc_basic/obj_pmalloc_basic.c
ref:
pmem/issues#391
pmem/issues#392
pmem/issues#393
pmem/issues#394
pmem/issues#395
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1611)
=> test: fix various leaks in unit tests

src/libpmemobj/tx.c, src/test/pmemobjcli/out0.log.match, src/test/pmemobjcli/out1.log.match, src/test/tools/pmemobjcli/pmemobjcli_example.posc, src/test/tools/pmemobjcli/pmemobjcli_example_tx.posc
Ref: pmem/issues#403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1609)
=> obj: fix valgrind memcheck issues

src/test/obj_tx_invalid/obj_tx_invalid.c
Ref: pmem/issues#398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1610)
=> test: don't leak memory in obj_tx_invalid test

src/test/obj_cpp_ptr/obj_cpp_ptr.cpp
Add missing persist in persistent_ptr test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1617)
=> cpp: add persist in test

src/common/sys_util.h, src/librpmem/rpmem.c, src/librpmem/rpmem_fip.c, src/librpmem/rpmem_obc.c, src/rpmem_common/rpmem_fip_lane.h, src/test/obj_rpmem_basic_integration/TEST10, src/test/obj_rpmem_basic_integration/TEST11, src/test/obj_rpmem_basic_integration/TEST13, src/test/obj_rpmem_basic_integration/TEST14, src/test/obj_rpmem_basic_integration/TEST15, src/test/obj_rpmem_basic_integration/TEST16, src/test/obj_rpmem_basic_integration/TEST17, src/test/obj_rpmem_basic_integration/TEST18, src/test/obj_rpmem_basic_integration/TEST9, src/test/unittest/unittest.sh, src/tools/rpmemd/rpmemd_fip.c, src/tools/rpmemd/rpmemd_fip_worker.c, src/tools/rpmemd/rpmemd_log.h, src/windows/include/pthread.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1600)
=> test: add drd and helgrind tests for rpmem

src/common/set.c, src/examples/libpmemobj/lists.c, src/libpmemobj/obj.c, src/test/libpmempool_api/TEST11, src/tools/pmempool/common.c
pmem/issues#390
pmem/issues#396
pmem/issues#404
pmem/issues#406
pmem/issues#411
pmem/issues#412
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1613)
=> common: memcheck fixes

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1621)
=> common: add tags file t .gitignore

src/libpmemobj/palloc.c, src/test/Makefile, src/test/obj_pmalloc_mt/helgrind_adjacent_block.supp, src/test/obj_pmalloc_rand_mt/.gitignore, src/test/obj_pmalloc_rand_mt/Makefile, src/test/obj_pmalloc_rand_mt/TEST0, src/test/obj_pmalloc_rand_mt/TEST1, src/test/obj_pmalloc_rand_mt/obj_pmalloc_rand_mt.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1627)
=> Fix benign races related to heap layout lookups

src/test/RUNTESTS.ps1
Ref: pmem/issues#417
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1625)
=> test: unify order of running tests for Win and Lin

src/libpmemobj/alloc_class.c, src/libpmemobj/heap.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1632)
=> obj: fix various tiny coverity reported issues

appveyor.yml, src/test/unittest/unittest.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1634)
=> test: add time execution to unittest on Windows

utils/check_whitespace
To keep the check_whitespace script in sync with projects using the same script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1638)
=> common: check_whitespace in asm files

src/libpmemobj/heap.c, src/libpmemobj/memblock.c, src/test/obj_heap/obj_heap.c, src/test/obj_memblock/obj_memblock.c, src/test/obj_pmalloc_mt/TEST0, src/test/obj_pmalloc_rand_mt/TEST0, src/test/obj_pmalloc_rand_mt/TEST1, src/test/obj_pmalloc_rand_mt/obj_pmalloc_rand_mt.c
Ref:
pmem/issues#419
pmem/issues#420
pmem/issues#421
pmem/issues#422
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1635)
=> obj: fix various valgrind issues

utils/docker/images/install-libcxx.sh, utils/docker/images/install-valgrind.sh
Do not download history of llvm and valgrind repos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1645)
=> common: speed up docker image build

src/test/libpmempool_rm/out0.log.match, src/test/libpmempool_rm/out1.log.match, src/test/libpmempool_rm/out2.log.match, src/test/libpmempool_rm/out3.log.match, src/test/libpmempool_rm/out4.log.match, src/test/libpmempool_rm/out5.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1654)
=> test: fix match files for libpmempool_rm

src/Makefile
Calling "make test" from main directory should take the same effect
as calling it from src/test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1646)
=> common: fix test build

src/examples/libpmemobj/pmemblk/obj_pmemblk.c, src/libpmemobj/tx.c, src/libpmemobj/tx.h, src/test/ex_libpmemobj/out10.log.match, src/test/obj_layout/obj_layout.c, src/test/obj_persist_count/out0.log.match, src/test/obj_persist_count/out1.log.match, src/test/obj_tx_add_range/obj_tx_add_range.c, src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c, src/test/pmempool_info/out14.log.match, src/tools/pmempool/info_obj.c
ref: pmem/issues#378
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1628)
=> implement dynamic range cache

src/test/unittest/unittest.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1663)
=> test: rm unused tm on fail

src/libpmempool/check_backup.c, src/libpmempool/check_btt_info.c, src/libpmempool/check_btt_map_flog.c, src/libpmempool/check_log_blk.c, src/libpmempool/check_pool_hdr.c, src/libpmempool/check_util.c, src/libpmempool/check_util.h, src/libpmempool/check_write.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1661)
=> pool: reorganize check location structures

src/test/Makefile.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1667)
=> common: make test should not trigger sync-test

src/test/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1668)
=> test: fix typo in build message

src/test/pmempool_check/TEST5
Ref: pmem/issues#405
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1665)
=> test: fix pmempool_check valgrind requirements

src/examples/libpmemlog/logfile/printlog.c, src/libpmemobj/alloc_class.h
This path contains fixes for issues reported by ASan.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1672)
=> Fixes for static analysis issues

src/common/valgrind_internal.h, src/libpmemobj/heap.c, src/libpmemobj/memblock.c, src/libpmemobj/memblock.h, src/libpmemobj/palloc.c, src/test/obj_heap/obj_heap.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1664)
=> obj: fix helgrind issues with pmalloc

utils/check_license/check-headers.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1669)
=> utils: skip checking dates for non-Intel commits

utils/check_license/check-headers.sh
Fix regression in check_license introduced by commit b782f08d.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1678)
=> utils: fix regression in check_license

utils/check_license/check-headers.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1679)
=> common: skip checking dates for new files

src/jemalloc/test/unit/pool.h, src/test/obj_cpp_cond_var/obj_cpp_cond_var.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1688)
=> Fix NVML compilation on Fedora 26 (rawhide)

ChangeLog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1692)
=> doc: update changelog

src/examples/libvmem/libart/art.c, src/examples/libvmem/libart/art.h
Ref: pmem/issues#470
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1691)
=> examples: fix build of vmem version of libart

src/common/mmap.h, src/common/set.c, src/common/set.h, src/common/util.h, src/libpmem/pmem.c, src/libpmemblk/blk.c, src/libpmemblk/blk.h, src/libpmemlog/log.c, src/libpmemlog/log.h, src/libpmemobj/obj.c, src/libpmemobj/obj.h, src/libpmempool/check_pool_hdr.c, src/libpmempool/pool.c, src/libpmempool/pool.h, src/libpmempool/sync.c, src/libvmem/vmem.c, src/test/pmem_map_file/pmem_map_file.c, src/tools/pmempool/convert.c, src/tools/pmempool/info.c
... in pmemblk, pmemlog and pmemobj libraries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1693)
=> common: fix PMEM detection for Device DAX

src/libpmemobj/pvector.c, src/test/obj_bucket/TEST0, src/test/obj_list_recovery/TEST0, src/test/obj_list_recovery/TEST1, src/test/obj_list_recovery/TEST2, src/test/obj_locks/TEST0, src/test/obj_locks/obj_locks.c, src/test/obj_pvector/obj_pvector.c, src/test/obj_recovery/obj_recovery.c, src/test/obj_tx_flow/TEST0, src/test/vmem_stats/TEST0, src/test/vmem_stats/TEST1, src/test/vmem_stats/TEST2, src/test/vmem_stats/TEST3, src/test/vmem_stats/TEST4, src/test/vmem_stats/TEST5, src/test/vmem_stats/TEST6, src/test/vmem_stats/TEST7, src/test/vmem_stats/TEST8, src/test/vmem_stats/TEST9
Ref:
pmem/issues#443
pmem/issues#444
pmem/issues#464
pmem/issues#451
pmem/issues#445
pmem/issues#439
pmem/issues#440
pmem/issues#441
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1685)
=> obj: fix various pmemcheck issues

CODING_STYLE.md, Makefile, utils/check-commit.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1697)
=> common: check commit msg format in pull requests

utils/check_license/check-headers.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1700)
=> common: fix checking headers for shallow clones

utils/check-commit.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1701)
=> common: fix check-commit.sh

src/jemalloc/include/jemalloc/internal/jemalloc_internal.h.in, src/jemalloc/include/jemalloc/internal/valgrind.h, src/jemalloc/src/jemalloc.c, src/test/vmem_realloc_inplace/vmem_realloc_inplace.c, src/windows/jemalloc_gen/include/jemalloc/internal/jemalloc_internal.h
pmem/issues#410
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1620)
=> vmem: fix near OOM realloc regression (cd868a1)

utils/check_license/Makefile, utils/check_license/check-headers.sh, utils/check_license/check-license.c, utils/check_license/file-exceptions.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1680)
=> utils: check-license improvements

src/jemalloc/include/jemalloc/internal/jemalloc_internal.h.in, src/windows/jemalloc_gen/include/jemalloc/internal/jemalloc_internal.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1704)
=> vmem: fix compilation w/o valgrind

utils/build-dpkg.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1705)
=> Debian packaging fixes

src/test/util_poolset/README, src/test/util_poolset/TEST3, src/test/util_poolset/TEST3w.PS1, src/test/util_poolset/grep3.log.match, src/test/util_poolset/grep3w.log.match, src/test/util_poolset/util_poolset.c, src/test/util_poolset/util_poolset.vcxproj, src/test/util_poolset/util_poolset.vcxproj.filters
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1703)
=> test: add scenario for pool set with >100 parts

utils/check-commit.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1707)
=> common: fix list of commits in check-commit.sh

CODING_STYLE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1708)
=> doc: fix format in coding_style markdown

src/benchmarks/vmem.cpp, src/libpmempool/pool.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1709)
=> common: fixes for Klocwork issues

src/libpmem/pmem.c, src/test/pmem_map_file/pmem_map_file.c
Ref: pmem/issues#483
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1713)
=> pmem: fix wrong is_pmem returned by pmem_map_file

src/examples/libpmemobj/hashmap/hashmap_tx.c, src/test/blk_nblock/TEST0, src/test/blk_rw/TEST1, src/test/blk_rw/TEST2, src/test/pmemobjcli/out1.log.match, src/test/tools/pmemobjcli/pmemobjcli_example_tx.posc, src/test/tools/pmemspoil/spoil.c
Ref: pmem/issues#458
Ref: pmem/issues#457
Ref: pmem/issues#454
Ref: pmem/issues#453
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1710)
=> test: pmemcheck fixes

src/libpmempool/sync.c, src/libpmempool/transform.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1715)
=> Fixes for several pmempool transform issues

src/tools/rpmemd/rpmemd_db.c
Ref: pmem/issues#473
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1698)
=> rpmem: warkaround for device dax issue

src/libpmemblk/blk.c, src/libpmemlog/log.c, src/libpmemlog/log.h, src/libpmemobj/obj.c, src/libpmempool/Makefile, src/libpmempool/check_log_blk.c, src/libpmempool/check_write.c, src/libpmempool/pool.c, src/tools/pmempool/Makefile, src/tools/pmempool/info_log.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1721)
=> Remove "pmem" prefix from internal functions

src/test/pmempool_check/TEST16.PS1
Ref: pmem/issues#485
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1723)
=> test: fix pmempool_check timezone issue

src/test/libpmempool_rm/TEST5
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1725)
=> test: skip libpmempool_rm #5 when run as superuser

src/libpmemobj/pmalloc.c, src/test/obj_debug/TEST4, src/test/obj_debug/TEST4.PS1, src/test/obj_debug/obj_debug.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1726)
=> obj: add failsafe to prevent allocs in constructor

src/libpmempool/check_backup.c, src/test/libpmempool_backup/out6.log.match
Ref: pmem/issues#425
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1728)
=> pool: fix check backup memory leaks

src/test/libpmempool_bttdev/TEST11, src/test/libpmempool_bttdev/TEST3, src/test/libpmempool_bttdev/TEST4, src/test/libpmempool_bttdev/TEST5, src/test/libpmempool_bttdev/TEST6
Ref: pmem/issues#426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1727)
=> test: fix libpmempool_bttdev valgrind requirements

src/tools/pmempool/common.c
Ref: pmem/issues#466
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1718)
=> pool: fix non-persistent store

src/benchmarks/pmembench.cpp, src/common/file.h, src/common/file_linux.c, src/common/file_windows.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1717)
=> common: fix invalid strcpy usage

src/libpmempool/check_util.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1729)
=> pool: fix coverity in check_util

src/test/rpmemd_config/TEST4
Ref: pmem/issues#383
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1730)
=> test: do not use default rpmemd config location

src/libpmemobj/obj.c, src/test/obj_heap/obj_heap.c, src/test/obj_memcheck/TEST0, src/test/obj_recovery/obj_recovery.c
Ref:
pmem/issues#421
pmem/issues#467
pmem/issues#438
pmem/issues#445
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1731)
=> various valgrind fixes, part 2

manpages/v1.2/libpmem.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1733)
=> doc: update man pages for version 1.2

src/libpmempool/transform.c
=> pool: fix adding replica on device dax

src/test/tools/pmemdetect/pmemdetect.c
Ref: pmem/issues#490
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1734)
=> test: pmemdetect first check permission for DAX

src/test/blk_pool_lock/TEST0, src/test/blk_pool_lock/TEST0.PS1, src/test/log_pool_lock/TEST0, src/test/log_pool_lock/TEST0.PS1, src/test/obj_pool_lock/TEST0, src/test/obj_pool_lock/TEST0.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1735)
=> test: do not run pool_lock test as root

src/test/blk_nblock/TEST0, src/test/blk_rw/TEST1, src/test/blk_rw/TEST2, src/test/magic/TEST0, src/test/obj_memcheck/TEST0, src/test/rpmemd_config/TEST4, src/test/vmmalloc_init/TEST16, src/test/vmmalloc_init/TEST6, utils/check_license/check-headers.sh
Files modified in only two commits:
1) the newest one not grafted and
2) the latest one grafted
should not be skipped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1737)
=> common: grep out the grafted commits later

src/common/mmap.c
a fix for a Klocwork issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1739)
=> common: fix check return value

src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1742)
=> test: extract node addresses in IPv6 friendly way

CODING_STYLE.md, src/.clang-format, src/libpmempool/check_backup.c, utils/cstyle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1631)
=> Change coding style according breaking long strings literals 

src/test/RUNTESTS.ps1, src/test/libpmempool_sync/libpmempool_sync.vcxproj, src/test/libpmempool_sync/libpmempool_sync.vcxproj.filters
Ref: pmem/issues#502
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1754)
=> test: fix time out in runtest.ps1

src/benchmarks/pmemobj_atomic_lists.cpp, src/common/util_pmem.h, src/libpmemblk/blk.c, src/libpmemlog/log.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1749)
=> common: fix several klocwork issues

src/test/libpmempool_api/TEST11, src/test/pmem_memmove/pmem_memmove.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1750)
=> test: fix pmemcheck issues

src/jemalloc/include/jemalloc/internal/util.h
Ref: pmem/issues#505
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1757)
=> jemalloc: fix setting errno on Windows

README.md
Add a complete example how to biuld and run tests with a custom version
of libc++.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1765)
=> doc: clarify cpp tests build command

src/test/obj_lane/obj_lane.c
Ref: pmem/issues#506
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1770)
=> test: fix uninitialized stream in obj_lane

src/libpmempool/sync.c, src/test/pmempool_sync_remote/TEST7
Ref: pmem/issues#498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1767)
=> pool: fix copying data from remote replica

src/test/pmempool_sync_remote/TEST5, src/test/pmempool_sync_remote/TEST6
Ref: pmem/issues#504
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1771)
=> test: fix lack of poolset file

src/common/mmap_linux.c, utils/check_license/check-headers.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1772)
=> common: grep out all non-Intel commits

src/test/pmempool_sync_remote/TEST7
Fixes path to a poolset on a remote node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1778)
=> test: fix poolset path

src/test/obj_bucket/obj_bucket.c
Ref: pmem/issues#508
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1781)
=> test: fix obj_bucket memcheck bug

src/common/os_linux.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1784)
=> win: fix error in os_flock

src/test/pmempool_sync_remote/TEST5, src/test/pmempool_sync_remote/TEST7
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1786)
=> test: pmempool_sync_remote path fix

src/benchmarks/benchmark.hpp, src/benchmarks/pmembench.cpp, src/benchmarks/pmemobj_atomic_lists.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1776)
=> benchmark: remove op_init/op_exit from interface

appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1790)
=> common: appveyor.yml some changes

utils/build-dpkg.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1791)
=> common/deb: install obj++ package config file

utils/make-pkg-config.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1792)
=> common: Fix include dir in libpmemobj++.pc

src/Makefile
Ref: pmem/issues#511
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1788)
=> common: fix uninstall of libpmemobj in Makefile

src/common/util.h, src/common/util_linux.c, src/common/util_windows.c, src/libpmempool/transform.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1793)
=> common: clear up getting absolute paths for parts

src/benchmarks/benchmark.hpp, src/benchmarks/pmembench.cpp, src/common/pthread_windows.c, src/windows/include/pthread.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1768)
=> benchmark: change threads behaviour

src/benchmarks/rpmem_persist.cpp
- add seq-wrap and rand-wrap modes of operations, which does not
enforce a file to cover data chunk for each operation separately,
instead the consequtive chunks are wrapped around based on file size
- add option for not using memset for each operation, instead one big
memset is done during warmup
- some minor fixes, like:
-- check if number of threads is less than number of lanes
-- do not overwrite pool header on local replica
-- fix cache line alignment of data chunks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1777)
=> benchmark: update rpmem_persist benchmark

src/test/pmempool_sync_remote/TEST6
Ref: pmem/issues#504
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1796)
=> test: fix incorrect paths

src/benchmarks/benchmark.hpp, src/benchmarks/benchmark_time.cpp, src/benchmarks/benchmark_time.hpp, src/benchmarks/pmembench.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1780)
=> benchmark: fix time measurements and add min-exe time option

utils/build-dpkg.sh, utils/make-pkg-config.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1802)
=> Port Debian packaging and pkg-config fixes to 1.2.

utils/md2man.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1804)
=> common: Allow dash and underscore in manpage title

src/libpmem/pmem.h, src/libpmemobj/obj.h, src/libpmempool/pmempool.h, src/librpmem/rpmem.h
It's already declared in util.h.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1806)
=> common: remove duplicated Pagesize declaration

src/benchmarks/pmembench.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1808)
=> benchmark: fix some memory leaks

src/examples/libpmemobj/hashmap/hashmap_atomic.c, src/examples/libpmemobj/hashmap/hashmap_tx.c, src/examples/libpmemobj/libart/arttree.c, src/examples/libpmemobj/libart/arttree_examine.c, src/examples/libpmemobj/libart/arttree_search.c, src/examples/libpmemobj/map/mapcli.c, src/examples/libvmem/libart/arttree.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1815)
=> examples: Format string portability fixes

src/tools/pmempool/common.c, src/tools/pmempool/create.c, src/tools/pmempool/info_obj.c, src/tools/pmempool/output.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1816)
=> common: pmempool int type fixes

src/examples/libpmemobj/doc_snippets/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1818)
=> examples: doc_snippets Makefile fix

utils/build-dpkg.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1819)
=> common: let user build debs with its own flags

src/libpmemlog/log.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1821)
=> log: some format string fixes

src/benchmarks/benchmark.hpp, src/benchmarks/log.cpp, src/benchmarks/obj_pmalloc.cpp, src/benchmarks/pmem_memcpy.cpp, src/benchmarks/pmem_memset.cpp, src/benchmarks/pmembench.cpp, src/benchmarks/rpmem_persist.cpp, src/benchmarks/vmem.cpp, src/examples/libpmemobj/pmemblk/obj_pmemblk.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1817)
=> Fixes for Klocwork issues

src/examples/Makefile.inc
Use the LINKER variable, assigned to above in the
same file. This is needed for linking C++.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1822)
=> examples: fix linking command

src/libpmemobj/alloc_class.c, src/libpmemobj/ctl.c, src/libpmemobj/obj.c, src/tools/pmempool/output.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1827)
=> Common coverity fixes2

src/test/obj_bucket/obj_bucket.vcxproj.filters
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1828)
=> test: obj_bucket vcxproj fix

src/libpmemobj/ctl.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1832)
=> common: fix klocwork issues

src/test/unittest/unittest.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1831)
=> tests: fix dump_last_n_lines on windows

src/test/obj_pmalloc_rand_mt/obj_pmalloc_rand_mt.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1834)
=> test: fix printed test name

doc/libpmemobj.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1835)
=> doc: fix typo in ctl example

src/test/pmempool_check/TEST9.PS1, src/test/pmempool_check/out9.log.match, src/test/pmempool_check/pmempool_check.vcxproj, src/test/pmempool_check/pmempool_check.vcxproj.filters, src/test/testconfig.ps1.example
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1841)
=> test: win some update

src/libpmempool/rm.c, src/test/libpmempool_rm/TEST6, src/test/libpmempool_rm/out6.log.match, src/test/pmempool_rm/TEST5, src/test/pmempool_rm/log5.log.match, src/test/pmempool_rm/out2.log.match, src/test/pmempool_rm/out2w.log.match, src/tools/pmempool/common.c, src/tools/pmempool/common.h, src/tools/pmempool/convert.c, src/tools/pmempool/output.c, src/tools/pmempool/rm.c
Ref: pmem/issues#434
Ref: pmem/issues#436
Ref: pmem/issues#469
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1844)
=> pmempool: rm fixes

utils/check_license/check-headers.sh
When build directory is not a child of source dir check-license
complains about missing .git directory and fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1843)
=> check-license: fix out of tree builds

src/libpmemobj/heap.c, src/test/obj_many_size_allocs/obj_many_size_allocs.c
ref: pmem/issues#520
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1840)
=> obj: fix memcheck instrumentation for large runs

src/test/obj_debug/TEST5.PS1, src/test/obj_debug/obj_debug.vcxproj, src/test/obj_debug/obj_debug.vcxproj.filters
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1849)
=> test: fix obj_debug

.travis.yml, utils/docker/build.sh, utils/docker/images/build-image.sh, utils/docker/images/push-image.sh, utils/docker/pull-or-rebuild-image.sh
A new repository named pmem/nvml was created on Docker Hub.
This path makes NVML builds on Travis use the new repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1846)
=> common: move docker images to a new repo

src/test/pmempool_rm/TEST2w.PS1, src/test/pmempool_rm/out2w.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1853)
=> pool: fix match file for rm test

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1852)
=> common: show build status badges for master only

src/test/Makefile, src/test/unicode_api/Makefile, src/test/unicode_api/README, src/test/unicode_api/TEST0, src/test/unicode_match_script/Makefile, src/test/unicode_match_script/README
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1838)
=> test: add unicode makefiles

utils/docker/pull-or-rebuild-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1855)
=> common: fix building Docker image

doc/libpmemobj.3.md, src/libpmemobj/ctl.c, src/test/obj_ctl/obj_ctl.c
Ref: pmem/issues#519
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1842)
=> various ctl fixes

src/test/pmempool_check/TEST16, src/test/pmempool_check/TEST16.PS1
...due to unstable behavior.
Ref: pmem/issues#485
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1862)
=> test: temporarily disable pmempool_check #16

src/libpmemobj/ctl.c, src/libpmemobj/ctl.h, src/libpmemobj/obj.c, src/test/obj_ctl/obj_ctl.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1826)
=> obj_ctl refactoring

_data/releases.yml, libpmem/index.md, libpmemblk/index.md, libpmemlog/index.md, libpmemobj/index.md, libpmempool/index.md, librpmem/index.md, libvmem/index.md, libvmmalloc/index.md, pmempool/index.md
Autogenerate links to all the releases/versions of man pages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1863)
=> doc: autogenerate man page links

src/libpmempool/rm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1868)
=> pool: fix issue detected by Coverity

src/common/file_linux.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1871)
=> common: fix buffer overflow in util_tmpfile

doc/libpmemobj.3.md, src/libpmemobj/ctl.h, src/libpmemobj/obj.c, src/libpmemobj/obj.h, src/libpmemobj/tx.c, src/libpmemobj/tx.h, src/test/obj_persist_count/out0.log.match, src/test/obj_persist_count/out1.log.match, src/test/obj_tx_add_range/obj_tx_add_range.c
Ref: pmem/issues#515
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1865)
=> obj: configurable object cache

appveyor.yml, utils/CHECK_WHITESPACE.PS1, utils/CREATE-ZIP.PS1, utils/CSTYLE.ps1, utils/SRCVERSION.ps1, utils/ps_analyze.ps1
Analisys for tests will be added in the next pull request
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1870)
=> ps1 script analysis

src/benchmarks/pmembench.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1875)
=> benchmark: min-exe-time fix

CONTRIBUTING.md, doc/libpmemobj.3.md, src/examples/libpmemobj/libart/arttree_examine.c, src/jemalloc/ChangeLog, src/jemalloc/bin/pprof, src/jemalloc/include/jemalloc/internal/rb.h, src/jemalloc/src/ctl.c, src/test/pmempool_check/TEST19, src/test/pmempool_check/TEST19.PS1, src/test/unittest/unittest.ps1, src/windows/include/unistd.h, utils/build-rpm.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1877)
=> common: typo fixes

src/common/set.c
Ref: pmem/issues#117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1884)
=> common: fix misleading comment

src/test/tools/bttcreate/bttcreate.c
Ref: pmem/issues#526
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1885)
=> test: fix checking poolsize

src/common/set.c
Ref: pmem/issues#536
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1890)
=> common: clean pmemcheck state for prefault pages

utils/docker/images/install-libfabric.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1891)
=> common: upgrade libfabric to v1.4.1

utils/CREATE-ZIP.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1893)
=> common: create-zip.ps1 changes

LICENSE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1894)
=> common: update LICENSE

src/test/tools/pmemobjcli/pmemobjcli.c
Ref: pmem/issues#535
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1895)
=> obj: fix pmemcheck issue

src/test/obj_tx_locks/TEST0
Ref: pmem/issue#534
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1896)
=> test: disable pmemcheck for obj_tx_locks

src/libpmemobj/obj.c, src/test/obj_ctl_config/TEST1, src/test/obj_ctl_config/TEST1.PS1
Ref: pmem/issues#525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1897)
=> obj: allow empty ctl config file

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1905)
=> common: update AppVeyor badge link

src/common/file.c
Ref: pmem/issues#547
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1910)
=> common: fix 'len' adjustment in util_file_zero()

src/windows/win_mmap.c
Ref: pmem/issues#527
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1907)
=> common: fix mmap on windows

src/test/RUNTESTS.ps1, src/test/obj_sync/TEST3, src/test/obj_sync/TEST3.PS1, src/test/obj_sync/TEST4, src/test/obj_sync/TEST4.PS1, src/test/obj_sync/TEST5, src/test/obj_sync/TEST5.PS1, src/test/obj_sync/TEST6, src/test/obj_sync/TEST6.PS1, src/test/obj_sync/err3.log.match, src/test/obj_sync/err4.log.match, src/test/obj_sync/err5.log.match, src/test/obj_sync/err6.log.match, src/test/pmempool_info/TEST8.PS1, src/test/pmempool_info/TEST9.PS1, src/test/unittest/unittest.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1867)
=> test: add parallel test execution on windows

.travis.yml, src/common/util.c, src/common/util.h, src/libpmempool/check_util.c, src/test/pmempool_check/TEST16.PS1, src/tools/pmempool/output.c, utils/docker/build.sh, utils/docker/images/build-image.sh, utils/docker/images/push-image.sh, utils/docker/pull-or-rebuild-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1911)
=> common: move Docker images to the new repo

src/test/blk_rw_mt/config.sh, src/test/libpmempool_backup/config.sh, src/test/obj_basic_integration/config.sh, src/test/obj_tx_add_range/config.sh, src/test/obj_tx_mt/config.sh, src/test/obj_tx_mt/obj_tx_mt.c, src/test/pmempool_check/config.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1909)
=> Fix test timeouts (master)

ChangeLog, src/test/blk_rw_mt/config.sh, src/test/libpmempool_backup/config.sh, src/test/obj_basic_integration/config.sh, src/test/obj_tx_add_range/config.sh, src/test/obj_tx_mt/config.sh, src/test/obj_tx_mt/obj_tx_mt.c, src/test/pmempool_check/config.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1908)
=> Fix test timeouts (1.2)

utils/docker/images/install-libfabric.sh
Ref: pmem/issues#548
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1917)
=> common: fix building libfabric inside a container

src/common/set.c, src/test/blk_rw/TEST12, src/test/log_basic/TEST9, src/test/obj_basic_integration/TEST12, src/test/util_poolset_parse/grep2.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1918)
=> Fix tests for concatenated Device DAX devices

ChangeLog, src/test/vmmalloc_calloc/TEST0, src/test/vmmalloc_calloc/vmmalloc_calloc.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1922)
=> vmmalloc: cfree removal (1.2)

src/common/mmap.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1927)
=> common: remove unused include directive

src/test/util_poolset_parse/grep2.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1926)
=> test: fix match file for util_poolset_parse

src/test/unittest/unittest.sh
Ref: pmem/issues#532
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1924)
=> test: fix restoring 'errexit' shell option

src/test/ex_libpmemobj/TEST12, src/test/libpmempool_backup/TEST6
.. because they run forever...
Ref: pmem/issues#412
Ref: pmem/issues#517
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1929)
=> test: do not run some tests under pmemcheck

src/test/blk_recovery/TEST0, src/test/blk_rw_mt/TEST0, src/test/blk_rw_mt/TEST1, src/test/blk_rw_mt/TEST2, src/test/log_recovery/TEST0, src/test/log_recovery/TEST1, src/test/log_walker/TEST0, src/test/log_walker/log_walker.c, src/test/obj_heap_interrupt/TEST0, src/test/obj_list_recovery/TEST0, src/test/obj_list_recovery/TEST1, src/test/obj_list_recovery/TEST2, src/test/obj_recovery/TEST0, src/test/obj_recovery/TEST1, src/test/obj_recovery/TEST2
This patch disables most of the tests that I was certain about having bogus helgrind results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1921)
=> various helgrind fixes

src/common/set.c, src/jemalloc/src/util.c, src/windows/win_mmap.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1928)
=> A bunch of various fixes

src/tools/pmempool/create.c
Ref: pmem/issues#330
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1937)
=> pool: fix parsing cmdline options

src/test/tools/pmemdetect/pmemdetect.c, src/test/unittest/unittest.sh, src/test/util_poolset_parse/TEST3, src/test/util_poolset_parse/grep3.log.match
Ref: pmem/issues#542
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1938)
=> test: fix dev dax alignment detection

src/common/out.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1935)
=> common: Fix ASSERTinfo

src/libpmemobj/memops.c, src/libpmemobj/memops.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1933)
=> obj: remove unused operation_add_entries

doc/librpmem.3.md, src/benchmarks/Makefile, src/common/set.c, src/common/set.h, src/examples/librpmem/basic.c, src/include/librpmem.h, src/libpmemobj/obj.c, src/libpmempool/replica.c, src/libpmempool/sync.c, src/librpmem/rpmem.c, src/librpmem/rpmem_fip.c, src/librpmem/rpmem_fip.h, src/rpmem_common/rpmem_fip_common.c, src/rpmem_common/rpmem_fip_common.h, src/test/rpmem_basic/TEST0, src/test/rpmem_basic/rpmem_basic.c, src/test/rpmem_fip/rpmem_fip_test.c, src/tools/rpmemd/rpmemd_fip.c, utils/docker/images/install-libfabric.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1942)
=> rpmem: use multiple endpoints

src/common/mmap_windows.c, src/windows/win_mmap.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1944)
=> Fix PMEM_MMAP_HINT support on Windows

doc/rpmemd.1.md, src/test/Makefile, src/test/rpmem_basic/TEST10, src/test/rpmem_basic/TEST11, src/test/rpmem_basic/common_pm_policy.sh, src/test/rpmem_basic/out10.log.match, src/test/rpmem_basic/out11.log.match, src/test/rpmem_fip/Makefile, src/test/rpmem_fip/rpmem_fip_test.c, src/test/rpmemd_util/.gitignore, src/test/rpmemd_util/Makefile, src/test/rpmemd_util/README, src/test/rpmemd_util/TEST0, src/test/rpmemd_util/TEST1, src/test/rpmemd_util/rpmemd_util_test.c, src/test/rpmemd_util/stdout0.log.match, src/test/rpmemd_util/stdout1.log.match, src/tools/rpmemd/Makefile, src/tools/rpmemd/rpmemd.c, src/tools/rpmemd/rpmemd_db.c, src/tools/rpmemd/rpmemd_db.h, src/tools/rpmemd/rpmemd_fip.c, src/tools/rpmemd/rpmemd_util.c, src/tools/rpmemd/rpmemd_util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1943)
=> rpmem: persistency method detection

.travis.yml, utils/docker/build.sh, utils/docker/images/Dockerfile.ubuntu-16.04, utils/docker/pull-or-rebuild-image.sh, utils/docker/run-build-package.sh, utils/docker/run-build.sh, utils/docker/run-coverity.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1955)
=> common: include librpmem in Coverity scans

src/examples/libpmemobj/libart/art.c, src/examples/librpmem/basic.c, src/librpmem/rpmem_fip.c, src/tools/rpmemd/rpmemd_config.c, src/tools/rpmemd/rpmemd_log.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1957)
=> Fix issues detected by Coverity

src/test/rpmemd_db/rpmemd_db_test.c, src/tools/rpmemd/rpmemd_db.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1963)
=> rpmem: various valgrind fixes

src/common.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1964)
=> rpmem: require libfabric >= 1.4.2

doc/librpmem.3.md
Ref: pmem/issues#566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1966)
=> doc: fix rpmem_read() signature

src/test/unittest/ut.c
Adds missing "break" that caused all the handles to be actually
ignored.
Remove querying the handle for object/file name - only the object
type name is recorded.  In some cases NtQueryObject may hang
the process, and there is no way to handle that other than performing
the query from another thread, and killing it if it stops to respond.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1949)
=> test: (win) fix recording open files

doc/libpmemobj.3.md, src/libpmemobj/obj.c, src/test/helgrind-cxgb4.supp, src/test/obj_rpmem_basic_integration/TEST11, src/test/obj_rpmem_basic_integration/TEST13, src/test/obj_rpmem_basic_integration/TEST14, src/test/obj_rpmem_basic_integration/TEST15, src/test/obj_rpmem_basic_integration/TEST18
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1958)
=> test: rpmem valgrind fixes

src/tools/pmempool/info_obj.c
This patch simplifies pmempool by using the already calculated,
and guaranteed to be accurate, information about allocation class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1975)
=> pmempool: leverage predefined alloc class info

src/examples/libvmem/libart/arttree.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1973)
=> examples: fix race condition in arttree for vmem

doc/default.man, utils/md2man.sh
Brings title lines in NVML man pages a bit closer to the man
conventions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1972)
=> doc: update man page template

src/common.inc, src/test/unittest/unittest.sh, utils/docker/images/install-libfabric.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1980)
=> test: require libfabric version >= 1.4.2

utils/docker/images/Dockerfile.ubuntu-16.04, utils/docker/pull-or-rebuild-image.sh
Due to unfortunate merge, the build that would have pushed a new docker image failed. We need to touch docker related fields to trigger a build and push a fresh set of images.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1987)
=> common: trigger docker rebuild

doc/cppobj.Doxyfile, src/include/libpmemobj++/pool.hpp
Enable documentation for wide character string C++ API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1992)
=> doc: generate documentation for wstring API

src/test/obj_pmalloc_rand_mt/TEST0, src/test/obj_pmalloc_rand_mt/TEST1, src/test/obj_pmalloc_rand_mt/obj_pmalloc_rand_mt.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2004)
=> test: fix unstable obj_pmalloc_rand_mt

.codecov.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1999)
=> Codecov config

appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2018)
=> common: run tests for Release build on AppVeyor

appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2023)
=> common: workaround AppVeyor timeouts

src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2024)
=> test: be verbose when skipping test on Device DAX

src/libpmemobj/alloc_class.c, src/libpmemobj/palloc.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2021)
=> obj: fix issues detected by Klockwork

doc/libpmem.3.md, doc/libpmemblk.3.md, doc/libpmemlog.3.md, doc/libpmemobj.3.md, doc/libpmempool.3.md, doc/librpmem.3.md, doc/libvmem.3.md, doc/libvmmalloc.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2028)
=> doc: add comment on unloading libraries

src/libpmemobj/tx.c
This patches refactors out the on commit set cache logic into
a common function and uses this same algorithm also for aborts.
This should improve performance for use cases when aborting a
transaction is common.
Ref: pmem/issues#516
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2038)
=> obj: retain set cache after tx abort

src/common/util.c
Ref: pmem/issues#574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2039)
=> common: fix util_localtime

src/libpmemobj/heap.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2043)
=> obj: fix LOG of invalid arena pointer

src/libpmempool/rm.c
Ref: pmem/issues#531
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2042)
=> pool: fix memory leak in pmempool_rm()

src/test/pmempool_check/TEST25, src/test/pmempool_check/out25.log.match, src/test/pmempool_info/TEST19, src/test/pmempool_info/out19.log.match
Ref: pmem/issues#570
Ref: pmem/issues#571
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2032)
=> test: fix pmempool tests on Device DAX

src/examples/libpmemobj/doc_snippets/pool.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2047)
=> examples: corrected layout in cpp doc sniplets

.travis.yml, utils/docker/README, utils/docker/build-local.sh, utils/docker/build-travis.sh, utils/docker/prepare-for-build.sh
This patch allows for building the NVML project under a Docker image locally.
A blog post on that will follow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2054)
=> common: enable building NVML under docker locally

src/common/set.c
Just to make sure it won't make any local irreversible change and
fail afterwards.
Ref: pmem/issues#493
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2041)
=> common: create remote replicas first

src/test/README, src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2046)
=> test & common: remote tests do not support TRACE

src/test/pmempool_rm/TEST7, src/test/pmempool_rm/TEST7.PS1, src/tools/pmempool/rm.c
Ref: pmem/issues#555
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2053)
=> pool: treat invalid answer as 'n'

src/test/rpmemd_db/rpmemd_db_test.c
Ref: pmem/issues#585
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2057)
=> test: rpmemd_db add missing persist

src/test/obj_ctl_prefault/obj_ctl_prefault.c
Ref: pmem/issues#586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2060)
=> test: accurately measure pages in prefault test

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2058)
=> common: update Travis to Ubuntu 14.04.5 LTS Trusty

doc/macros.man
It must be merge before PR #2008 and nvml-bot changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2037)
=> doc add macros.man

doc/librpmem.3.md
Ref: pmem/issues#379
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2059)
=> doc: add rpmem ulimit info

doc/pmempool-info.1.md, src/test/Makefile, src/test/pmempool_info_remote/Makefile, src/test/pmempool_info_remote/TEST0, src/test/pmempool_info_remote/config.sh, src/test/pmempool_info_remote/out0.log.match, src/test/sync-remotes/copy-to-remote-nodes.sh, src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2044)
=> common & test: pmempool info poolset support

doc/libpmem.3.md, doc/libpmemblk.3.md, doc/libpmemlog.3.md, doc/libpmemobj.3.md, doc/libpmempool.3.md, doc/librpmem.3.md, doc/libvmem.3.md, doc/libvmmalloc.3.md, doc/pmempool-check.1.md, doc/pmempool-convert.1.md, doc/pmempool-create.1.md, doc/pmempool-dump.1.md, doc/pmempool-info.1.md, doc/pmempool-rm.1.md, doc/pmempool-sync.1.md, doc/pmempool-transform.1.md, doc/pmempool.1.md, doc/rpmemd.1.md
!NOTE: Those changes have to wait for NVML BOT configuration changes before merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2008)
=> win UW documentation

src/test/test_debug.props, src/test/test_release.props, src/windows/libs_debug.props, src/windows/libs_release.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2070)
=> remove lonely tags from props

doc/Makefile, utils/md2man.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2073)
=> doc: fix md2man and doc makefile

src/test/Makefile.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2062)
=> test: add cpp bindings to coverage test

doc/libpmemobj.3.md, doc/libpmempool.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2079)
=> doc: fix typo and formatting

doc/cppobj.Doxyfile, src/include/libpmempool.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2080)
=> common: bump up API version numbers

css/pmem.css, css/pygment_trac.css, librpmem/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2085)
=> Back some css

src/test/testconfig.sh.example
Ref: pmem/issues#588
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2086)
=> doc: change \ to / in DIRSUFFIX

_layouts/manual.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2089)
=> doc: rm rpmemd from win shortcut

appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2091)
=> common: workaround for AppVeyor timeouts

src/test/rpmem_addr/rpmem_addr.c
Ref: pmem/issues#590
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2096)
=> test: fix memory leak in rpmem_addr

src/examples/libpmemobj/panaconda/panaconda.cpp, src/examples/libpmemobj/panaconda/panaconda.hpp, src/examples/libpmemobj/pman/pman.cpp, src/include/libpmemobj++/mutex.hpp, src/include/libpmemobj++/shared_mutex.hpp, src/include/libpmemobj++/timed_mutex.hpp
Resolve some of the problems in C++ examples found by Coverity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2082)
=> Cpp coverity issues

src/test/testconfig.sh.example
Describe required device dax sizes ratio.
Ref: pmem/issues#577
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2069)
=> test: device dax size requirements

CODING_STYLE.md, utils/check-commit.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2100)
=> common: add vmmalloc to valid area names

src/librpmem/rpmem_util.c
Ref: pmem/issues#493
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2101)
=> rpmem: more descriptive ENOENT message

src/include/libpmemobj++/detail/life.hpp, src/include/libpmemobj++/detail/make_atomic_impl.hpp, src/include/libpmemobj++/make_persistent_atomic.hpp, src/include/libpmemobj++/persistent_ptr.hpp, src/test/obj_cpp_make_persistent_atomic/obj_cpp_make_persistent_atomic.cpp
Address some issues in the C++ bindings, mainly with atomic allocations and constructor parameters' forwarding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2103)
=> cpp: fix issues with bindings

utils/build-dpkg.sh, utils/build-rpm.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2094)
=> common: rpmem pkgs requires libfabric >= 1.4.2

src/test/Makefile, src/test/RUNTESTS
Ref: pmem/issues#575
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2093)
=> test: MAKEFLAG keep_going support

src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2106)
=> test: scp output fix

ChangeLog, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2108)
=> doc: update Changelog and main README

src/include/libpmemobj++/detail/persistent_ptr_base.hpp, src/test/obj_cpp_ptr/obj_cpp_ptr.cpp
Given the following structure definition:
```C++
struct A {
uint64_t a;
};
struct B {
uint64_t b;
};
struct C : public A, public B {
uint64_t c;
};
C *cptr = new C();
B *bptr = cptr;
```
`btpr` shall be offset by the size of `struct A`. This patch introduces
this behavior to `peristent_ptr`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2110)
=> cpp: add internal offset calculation

src/LongPathSupport.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2111)
=> common: remove lonely tag from props

src/test/unittest/unittest.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2112)
=> test: win: fix require_build_type

src/test/pmempool_rm/TEST7.PS1, src/test/pmempool_rm/pmempool_rm.vcxproj, src/test/pmempool_rm/pmempool_rm.vcxproj.filters
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2109)
=> test: fix pmempool_rm test7.ps1

doc/README
Ref: pmem/issues#305
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2113)
=> doc: fix paths in README

README.md, doc/Makefile, src/Makefile, src/tools/rpmemd/Makefile, utils/build-dpkg.sh, utils/build-rpm.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2115)
=> common: remove librpmem from experimental packages

_layouts/manual.html, manpages/linux/v1.2/rpmemd.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2116)
=> doc: fix rpmemd at pmem.io

ChangeLog, doc/README, doc/libpmemobj.3.md, doc/libpmempool.3.md, doc/librpmem.3.md, doc/libvmem.3.md, doc/libvmmalloc.3.md, doc/pmempool-check.1.md, doc/pmempool-convert.1.md, doc/pmempool-create.1.md, doc/pmempool-dump.1.md, doc/pmempool-info.1.md, doc/pmempool-rm.1.md, doc/pmempool-sync.1.md, doc/pmempool-transform.1.md, doc/pmempool.1.md, doc/rpmemd.1.md, src/include/libpmemobj/base.h, src/include/libpmemobj/ctl.h, src/include/libpmempool.h, src/include/librpmem.h, src/librpmem/librpmem.map
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2122)
=> prepare for 1.3 release

src/test/obj_async_postcommit/TEST0, src/test/obj_async_postcommit/TEST0.PS1, src/test/obj_convert/TEST0, src/test/obj_convert/TEST1, src/test/obj_convert/TEST11, src/test/obj_convert/TEST12, src/test/obj_convert/TEST13, src/test/obj_convert/TEST14, src/test/obj_convert/TEST15, src/test/obj_convert/TEST16, src/test/obj_convert/TEST17, src/test/obj_convert/TEST18, src/test/obj_convert/TEST19, src/test/obj_convert/TEST2, src/test/obj_convert/TEST3, src/test/obj_convert/TEST4, src/test/obj_pvector/TEST0, src/test/obj_pvector/TEST0.PS1, src/test/pmempool_info/out10.log.match, src/test/pmempool_info/out11.log.match, src/test/pmempool_info/out12.log.match, src/test/pmempool_info/out13.log.match, src/test/pmempool_info/out14.log.match, src/test/pmempool_info/out15.log.match, src/test/pmempool_info/out16.log.match, src/test/pmempool_info/out16w.log.match, src/test/pmempool_info/out18.log.match, src/test/pmempool_info/out19.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2129)
=> test: fix timeout in obj_async_postcommit

src/libpmem/cpu.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2131)
=> pmem: clflushopt instruction for AMD processors

utils/build-rpm.sh
Ref: pmem/issues#591
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2130)
=> common: fix rpm dependencies

src/test/RUNTESTS, src/test/unittest/unittest.sh
Do not run remote test if set of providers or persistency methods is empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2121)
=> test: skip remote tests if requirements are not met

src/test/rpmemd_config/rpmemd_config_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2138)
=> test: fix rpmemd config open fd

src/test/tools/pmemdetect/pmemdetect.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2139)
=> test: add unicode support in pmemdetect

src/test/pmempool_sync_remote/common.sh
Ref: pmem/issues#592
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2142)
=> test: get rid of superfluous messages in output

src/NVML.sln, src/test/pmemobjcli/pmemobjcli.vcxproj, src/test/pmemspoil/pmemspoil.vcxproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2145)
=> common: fix VS project dependencies

src/test/blk_pool/TEST31w.PS1, src/test/blk_pool/blk_pool.vcxproj, src/test/blk_pool/blk_pool.vcxproj.filters, src/test/obj_pool/TEST30.PS1, src/test/obj_pool/obj_pool.vcxproj, src/test/obj_pool/obj_pool.vcxproj.filters, src/test/util_poolset/TEST0w.PS1, src/test/util_poolset/TEST1w.PS1, src/test/util_poolset/TEST2w.PS1, src/test/util_poolset/TEST3w.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2141)
=> test: fix variable references in PS scripts

CODING_STYLE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2148)
=> doc: update coding style

utils/check_whitespace
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2149)
=> common: add .py files to check_whitespace check

src/test/pmem_is_pmem_windows/pmem_is_pmem_windows.vcxproj, src/test/pmem_is_pmem_windows/pmem_is_pmem_windows.vcxproj.filters
we have to link with entire libpmem to initialize global state
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2152)
=> test: fix pmem_is_pmem_windows_test

src/test/rpmem_basic/TEST0, src/test/rpmem_basic/TEST1, src/test/rpmem_basic/TEST10, src/test/rpmem_basic/TEST11, src/test/rpmem_basic/TEST2, src/test/rpmem_basic/TEST3, src/test/rpmem_basic/TEST4, src/test/rpmem_basic/TEST5, src/test/rpmem_basic/TEST6, src/test/rpmem_basic/TEST7, src/test/rpmem_basic/TEST8, src/test/rpmem_basic/TEST9, src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2159)
=> test: fix unittest framework and require_* order

src/test/RUNTESTS.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2154)
=> test: timeout should work only in check test

src/windows/getopt/getopt.vcxproj, src/windows/include/platform.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2120)
=> common: fix compilation issue on chinese windows server

src/libpmemobj/pmalloc.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2161)
=> obj: fix class id bounds check

src/common/os_thread_windows.c, src/windows/include/unistd.h
now we are able to set affinity to other cpu, also we getting correct
number of processors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2162)
=> common: fix cpu operations on 2< socket windows

src/test/libpmempool_rm_remote/TEST0, src/test/libpmempool_rm_remote/TEST1, src/test/libpmempool_rm_remote/TEST2, src/test/libpmempool_rm_remote/TEST3, src/test/pmempool_sync_remote/TEST0, src/test/pmempool_sync_remote/TEST1, src/test/pmempool_sync_remote/TEST2, src/test/pmempool_sync_remote/TEST3, src/test/pmempool_sync_remote/TEST4, src/test/pmempool_sync_remote/TEST5, src/test/pmempool_sync_remote/TEST6, src/test/pmempool_sync_remote/TEST7
Ref: pmem/issues#614
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2164)
=> test: call require_* before setup part 2

src/libpmemobj/alloc_class.c
Doing this at boot time for every single possible size is very
expensive. Shifting the cost to the first use moment seems like
a no brainer given that the vast majority of the sizes will
never be used.
This, together with the populate buckets change, will make the pmemobj_open nearly instantaneous regardless of the size of the pool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2167)
=> obj: lazily initialize size <> class mapping

src/libpmemobj/alloc_class.c
Ref: pmem/issues#616
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2169)
=> obj: use atomics to modify the alloc class map

src/common/out.c, src/test/arch_flags/log0.log.match, src/test/out_err/traces0.log.match, src/test/out_err_win/traces0.log.match, src/test/traces_custom_function/out0.log.match, src/test/traces_custom_function/out1.log.match, src/test/util_poolset/grep0.log.match, src/test/util_poolset/grep0w.log.match, src/test/util_poolset/grep1.log.match, src/test/util_poolset/grep1w.log.match, src/test/util_poolset/grep2.log.match, src/test/util_poolset/grep2w.log.match, src/test/util_poolset/grep3.log.match, src/test/util_poolset/grep3w.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2168)
=> common: put source version string into binaries

.gitattributes
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2172)
=> common: ignore whitespace in *.match files

src/test/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2176)
=> test: do sync-remotes on make check

src/include/librpmem.h, src/test/obj_rpmem_basic_integration/TEST19, src/test/obj_rpmem_basic_integration/TEST20, src/test/obj_rpmem_basic_integration/node_0_rpmemd20.log.match, src/test/obj_rpmem_basic_integration/node_1_out19.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2153)
=> rpmem: require minimal part size

src/common/plugin.c, src/common/plugin.h, src/test/Makefile, src/test/util_plugin/.gitignore, src/test/util_plugin/Makefile, src/test/util_plugin/TEST0, src/test/util_plugin/plugin0.c, src/test/util_plugin/plugin1.c, src/test/util_plugin/plugin2.c, src/test/util_plugin/plugin3.c, src/test/util_plugin/plugin4.c, src/test/util_plugin/util_plugin.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2179)
=> common: plugin framework

src/test/RUNTESTS.PS1, src/test/unittest/unittest.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2185)
=> test: fix some windows runtest issues

src/benchmarks/perf.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2186)
=> benchmark: perf.cfg adjustments 

src/test/blk_rw_mt/TEST1.PS1, src/test/blk_rw_mt/TEST2.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2188)
=> test: fix too long windows blk test

src/librpmem/rpmem.c
Ref: pmem/issues#596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2191)
=> rpmem: add logging rpmem functions calls

src/common/os_thread_windows.c, src/test/RUNTESTS.PS1
Ref: pmem/issues#611
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2192)
=> common: add windows tls destructor support

src/test/RUNTESTS.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2197)
=> win: fix RUNTESTS.ps1

src/test/RUNTESTS.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2199)
=> test: fix multi-threaded long tests

Makefile, utils/build-dpkg.sh, utils/build-rpm.sh, utils/nvml.spec.in, utils/pkg-common.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2178)
=> common: spec rpm nvml

src/Makefile.inc, src/common.inc, src/examples/libpmemobj/pman/pman.cpp, src/include/libpmemobj/tx_base.h, src/include/libvmmalloc.h, src/jemalloc/test/unit/util.c, src/libpmemobj/lane.c, src/test/Makefile.inc, src/test/rpmem_fip/rpmem_fip_test.c, src/test/unittest/Makefile, src/tools/Makefile.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2202)
=> common: fix compilation with icc

src/test/rpmem_addr_ext/node_1_rpmem0.log.match
Ref: pmem/issues#624
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2204)
=> test: fix rpmem_addr_ext match

src/common/out.c, src/libpmemobj/lane.c, src/libpmemobj/obj.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2200)
=> common: destroy TLS keys in lib dtor

utils/nvml.spec.in
Ref: pmem/issues#629
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2205)
=> common: restore static libraries in rpms

src/Makefile
Ref: pmem/issues#610
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2209)
=> common: generate pkg-config files on make install

src/examples/libpmemobj/pmpong/.gitignore
Ignore downloaded SFML headers and binaries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2220)
=> examples: fix .gitignore for pmpong

src/common/os_thread_windows.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2223)
=> common: (win) roll-back TLS to FLS change

src/common/os_thread_windows.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2218)
=> common: (win) fix race condition in os_once

src/test/obj_lane/obj_lane.c, src/test/traces/TEST0, src/test/traces/TEST0.PS1, src/test/traces/TEST1, src/test/traces/TEST1.PS1, src/test/traces/TEST2, src/test/traces/TEST2.PS1, src/test/traces/TEST3, src/test/traces/TEST3.PS1, src/test/traces/TEST4, src/test/traces/TEST4.PS1, src/test/traces/TEST5, src/test/traces/TEST5.PS1, src/test/traces/TEST6, src/test/traces/TEST6.PS1, src/test/traces/redir_stderr6.log.match, src/test/traces/traces.c, src/test/unittest/unittest.ps1, src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2221)
=> win: unittest.ps1 cleanup

src/test/vmem_valgrind_region/memcheck2.log.match, src/test/vmem_valgrind_region/memcheck4.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2225)
=> test: fix .match files for vmem_valgrind_region

src/test/Makefile
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2224)
=> test: compile vmem_valgrind_region

src/libpmemobj/obj.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2227)
=> obj: initialize TLS data

src/common/os_thread_windows.c, src/libpmemobj/obj.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2228)
=> win: FLS strikes back

src/benchmarks/blk.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2229)
=> benchmark: fix possible use after free

src/tools/pmempool/create.c
Ref: pmem/issues#643
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2231)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2231)
=> pool: fix incorrect error handling

src/libpmem/pmem.c, src/test/ex_libpmemobj/TEST0, src/test/libpmempool_api/TEST11
Ref: pmem/issues#638
Ref: pmem/issues#640
Ref: pmem/issues#641
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2232)
=> Helgrind fixes

src/benchmarks/clo.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2236)
=> benchmark: fix int parsing

src/libpmemobj/heap.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2239)
=> obj: add ASSERT as a precaution in chunk resize

src/test/obj_heap/obj_heap.c
Ref: pmem/issues#628
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2241)
=> test: initialize heap in recycler tests

src/test/obj_convert/TEST13
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2243)
=> test: disable obj_convert TEST13 due to vg bug

src/tools/pmempool/create.c, src/windows/include/unistd.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2234)
=> pool: fix pmempool_get_max_size

src/libpmemobj/heap.c
pmemcheck apparently *sometimes* requires flushing to be a part
of the transaction to not report an issue.
I'd say that this should be fixed in pmemcheck so that the behavior
is consistent.
Ref: pmem/issues#644
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2242)
=> obj: fix pmemcheck instrumentation in run init

src/test/obj_pmalloc_mt/obj_pmalloc_mt.c
Ref: pmem/issues#632
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2250)
=> test: add CTOR initialization in obj_pmalloc_mt

src/include/libpmemobj/types.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2257)
=> common: fix to offsetof fix

src/test/obj_realloc/obj_realloc.c
Ref: pmem/issues#649
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2258)
=> test: add CTOR initialization in obj_realloc

src/jemalloc/src/jemalloc.c
Ref: pmem/issues#646
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2262)
=> jemalloc: fix potential race condition

src/examples/ex_common.h, src/examples/libpmemobj/cpp_map/ctree_map_persistent.hpp, src/examples/libpmemobj/cpp_map/ctree_map_transient.hpp, src/examples/libpmemobj/pmpong/MainGame.cpp, src/examples/libpmemobj/tree_map/ctree_map.c
Fix namespace collision and C++ type mismatch with fls.
Fix initializer in pmpong/MainGame.cpp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2265)
=> examples: FreeBSD portability fixes

src/benchmarks/obj_pmalloc.cpp, src/benchmarks/perf.cfg, src/benchmarks/pmemobj_tx.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2272)
=> benchmark: fix pmalloc-related workloads

doc/librpmem.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2273)
=> doc: fix typo in rpmem

src/test/unittest/unittest.sh, src/test/vmmalloc_init/TEST16, src/test/vmmalloc_init/TEST6
Ref: pmem/issues#647
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2263)
=> test: fix running vmmalloc tests under helgrind

src/benchmarks/perf.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2278)
=> benchmark: fix perf.cfg configuration

src/Makefile.inc
Ref: pmem/issues#657
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2281)
=> common: fix passing handling CFLAGS in debug build

src/tools/pmempool/rm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2283)
=> pmempool: add missing new line characters

src/common.inc
Make all warnings into errors during testing compile flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2291)
=> common: fix check_flag

src/librpmem/rpmem.c, src/librpmem/rpmem_fip.c, src/rpmem_common/rpmem_common.h, src/rpmem_common/rpmem_fip_common.c, src/test/rpmem_basic/TEST12, src/test/rpmem_basic/rpmem_basic.c, src/test/rpmem_basic/setup.sh, src/test/tools/ctrld/ctrld.c, src/test/unittest/unittest.sh
Ref: pmem/issues#597
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2237)
=> rpmem: monitor in-band connection

src/libpmemobj/heap.c, src/libpmemobj/recycler.c, src/test/obj_constructor/memcheck1.log.match
Ref: pmem/issues#669 pmem/issues#671
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2293)
=> obj: recycler fixes

src/Makefile.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2298)
=> common: append -std=gnu99 to CFLAGS

src/librpmem/rpmem_fip.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2296)
=> rpmem: small optimizations

utils/nvml.spec.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2301)
=> common: rpm - restore _smp_mflags

src/test/ld.supp, src/test/vmem_valgrind_region/memcheck0.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2302)
=> test: add Valgrind suppression for newer version of ld.so

src/test/unittest/unittest.ps1, src/test/unittest/unittest.sh
Ref pmem/issues#652
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2305)
=> test: add days to printed time in unittest

src/include/libpmemobj++/README.md
Ref: pmem/issues#675
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2313)
=> obj: add info about lifetimes in C++ bindings

src/test/pmempool_info/out18.log.match
Ref pmem/issues#673
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2311)
=> test: fix pmempool_info test log.match

src/libpmemobj/heap.c, src/libpmemobj/memblock.c, src/libpmemobj/recycler.c, src/libpmemobj/recycler.h, src/test/obj_constructor/memcheck1.log.match, src/test/obj_fragmentation2/obj_fragmentation2.c, src/test/obj_heap/obj_heap.c
Finally ;)
Ref: pmem/issues#669
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2308)
=> obj: heap deadlock fix

src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2315)
=> test: date should be $DATE in unittest.sh

src/test/RUNTESTS, src/test/testconfig.sh.example, src/test/unittest/unittest.sh
It is part of pmem/issues#674 github issue (patch for remote data is in progress and it will be in another pull request)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2312)
=> test: CLEAN_FAILED functionality

src/test/Makefile.inc, src/test/vmem_pages_purging/Makefile, src/test/vmmalloc_calloc/Makefile, src/tools/Makefile.inc
Fixes pmem/issues#363
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2307)
=> common: Allow running "make DEBUG=1"

src/test/obj_pmalloc_mt/TEST0.PS1
Ref: pmem/issues#669
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2321)
=> test: fix obj_pmalloc_mt on windows

src/test/unittest/unittest.h, src/test/unittest/ut_file.c
It can always be restored from git history if it's needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/1977)
=> test: remove dead code from ut_file.c

src/test/obj_cpp_cond_var_posix/TEST0, src/test/obj_cpp_mutex_posix/TEST0, src/test/obj_cpp_shared_mutex_posix/TEST0, src/test/obj_cpp_timed_mtx_posix/TEST0, src/test/obj_locks/TEST1, src/test/unittest/unittest.sh
Ref:
pmem/issues#667
pmem/issues#663
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2325)
=> test: suppress drd in multithreaded tests that call fputs

src/test/vmmalloc_init/grep0.log.match, src/test/vmmalloc_init/grep3.log.match, src/test/vmmalloc_init/grep4.log.match, src/test/vmmalloc_init/grep7.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2330)
=> test: Fix FreeBSD matches for PR #2322

src/common/out.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2329)
=> common: fix evaluating ASSERTs in coverity

src/test/vmmalloc_fork/TEST2, src/test/vmmalloc_fork/TEST4
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2334)
=> test: fix skipping vmalloc_fork 2/4 on Linux

src/benchmarks/blk.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2336)
=> benchmark: fix memleak in blk.cpp

src/tools/rpmemd/rpmemd_log.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2337)
=> rpmem: fix issues reported by Coverity

src/test/vmmalloc_fork/TEST2, src/test/vmmalloc_fork/TEST4
Ref #2334 
Ref pmem/issues#639
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2339)
=> test: fix skipping vmmalloc_fork #2/#4 on Linux

src/examples/libpmemobj/pmemobjfs/pmemobjfs.c, src/examples/librpmem/basic.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2338)
=> examples: fix issues reported by Coverity

src/test/pmempool_info/out21.log.match
Ref: pmem/issues#682
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2348)
=> test: fix match file in pmempool_info

src/test/vmmalloc_init/grep6.log.match
Ref: pmem/issues#680
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2349)
=> test: fix match file in vmmalloc_init

src/examples/libpmemobj/cpp/queue.cpp, src/examples/libpmemobj/cpp_map/map_cli.cpp, src/examples/libpmemobj/pman/pman.cpp, src/libpmempool/check_log_blk.c, src/test/rpmemd_log/rpmemd_log_test.c, src/windows/include/unistd.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2352)
=> common: fix issues reported by CLion

src/test/unittest/unittest.sh
Force infinipath-psm to not register signal handler on remote nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2341)
=> test: workaround ipath signal handler issue

src/include/libpmemobj++/make_persistent_array_atomic.hpp
Ref: pmem/issues#684
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2351)
=> cpp: Remove name of an unused argument

utils/build-rpm.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2355)
=> common: fix rpath issue

src/libvmmalloc/libvmmalloc.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2354)
=> vmmalloc: fixed leak in destructor

utils/build-rpm.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2360)
=> common: back rpath fix for master

utils/pkg-common.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2361)
=> common: add centos to os detection

src/test/vmem_delete/TEST0, src/test/vmem_delete/vmem_delete.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2362)
=> test: vmem_delete test fix

.mailmap
As far as I know there is only one me in the team :)
There is an alias for old email so no need to provide two addresses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2364)
=> common: .mailmap fix weronika

.mailmap
This reverts commit 0261745ee061e0d7e5059c22980c9646c208a504.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2366)
=> common: revert .mailmap change

src/test/vmmalloc_malloc_hooks/TEST0
Ref pmem/issues#659
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2367)
=> test: fixed vmmalloc_malloc_hooks

doc/libpmemobj/pmemobj_ctl_get.3.md, src/libpmemobj/alloc_class.c, src/libpmemobj/pmalloc.c, src/test/obj_ctl_alloc_class/obj_ctl_alloc_class.c
Ref: pmem/issues#685 pmem/issues#686 pmem/issues#687 pmem/issues#688
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2372)
=> obj: fix failure handling of alloc classes

doc/poolset/poolset.5.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2373)
=> doc: poolset doc fix

src/librpmem/rpmem_fip.c
Registration of a memory on the initiator side was done before
connecting of all lanes. The registration of a large memory pool can
take a while so the rpmemd can timeout the connection listener already.
This patch changes the order of initialization so the memory pool is
registered after establishing conenctions of all lanes.
Ref: pmem/issues#655
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2377)
=> rpmem: change order of memory registration

src/test/RUNTESTS
Ref: pmem/issues#689
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2379)
=> test: print message about non-existent test

src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2369)
=> test: allow setting SUFFIX to empty string

src/test/rpmem_basic/rpmem_basic.c
.. in rpmem_basic test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2382)
=> rpmem: increase buffer size for path

doc/libpmemlog/pmemlog_append.3.md, src/libpmemlog/log.c, src/test/log_basic/log_basic.c
Ref: pmem/issues#690
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2381)
=> log: add check for negative iovcnt

src/common/os_linux.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2384)
=> common: replace getenv with secure_getenv

src/test/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2385)
=> test: fix MAKEFLAGS in src/test/Makefile

src/common/util.h
To be used for #2290
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2323)
=> common: introduce util_atomic_load/store

utils/docker/images/Dockerfile.fedora-25, utils/docker/images/install-libndctl.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2390)
=> common: add ndctl to docker files

src/test/obj_constructor/memcheck1.log.match, src/test/obj_memcheck/memcheck0.log.match, src/test/vmem_valgrind_region/memcheck0.log.match, src/test/vmem_valgrind_region/memcheck2.log.match, src/test/vmem_valgrind_region/memcheck4.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2393)
=> test: FreeBSD match fixes for PR #2368

src/test/pmempool_sync/TEST21, src/test/pmempool_sync/out18.log.match, src/test/pmempool_sync/out19.log.match, src/test/pmempool_sync/out20.log.match, src/test/pmempool_sync/out21.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2396)
=> test: fixes for sync tests

doc/generated/pmemcto_calloc.3, doc/generated/pmemcto_check.3, doc/generated/pmemcto_close.3, doc/generated/pmemcto_create.3, doc/generated/pmemcto_free.3, doc/generated/pmemcto_get_root_pointer.3, doc/generated/pmemcto_realloc.3, doc/libpmemcto/libpmemcto.7.md, doc/libpmemcto/pmemcto_aligned_alloc.3.md, doc/libpmemcto/pmemcto_malloc.3.md, doc/libpmemcto/pmemcto_malloc_usable_size.3.md, doc/libpmemcto/pmemcto_open.3.md, doc/libpmemcto/pmemcto_set_root_pointer.3.md, doc/libpmemcto/pmemcto_stats_print.3.md, doc/libpmemcto/pmemcto_strdup.3.md, doc/libpmemcto/pmemcto_wcsdup.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2404)
=> doc: fix pmemcto man page titles

doc/librpmem/librpmem.7.md, src/librpmem/librpmem.c, src/librpmem/rpmem.c, src/librpmem/rpmem_util.c, src/librpmem/rpmem_util.h, src/rpmem_common/rpmem_common.c, src/rpmem_common/rpmem_common.h, src/rpmem_common/rpmem_fip_common.c, src/test/rpmem_fip/rpmem_fip_test.c, src/test/rpmem_fip/setup.sh, src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2397)
=> rpmem: add RPMEM_MAX_NLANES environment

doc/generated/pmemobj_cancel.3, doc/generated/pmemobj_publish.3, doc/generated/pmemobj_reserve.3, doc/generated/pmemobj_set_value.3, doc/generated/pmemobj_tx_publish.3, doc/generated/pobj_reserve_alloc.3, doc/generated/pobj_reserve_new.3
This probably won't build on travis successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2407)
=> doc: add action generated links

src/libpmemcto/cto.c, src/tools/pmempool/create.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2409)
=> Cto coverity

doc/.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2410)
=> doc: add web-based man pages to .gitignore

src/libpmemobj/heap.c, src/libpmemobj/palloc.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2406)
=> obj: fix coverity issues

src/jemalloc/src/jemalloc.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2413)
=> jemalloc: make Valgrind-specific code optional

src/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2408)
=> cto: fix make install

src/benchmarks/map_bench.cpp
Ref: pmem/issues#695
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2411)
=> benchmark: increase min pool size for map_bench

src/libpmemobj/tx.c
This patch fixes an error path where transactional alloc fails
due to inability to allocate a vector array. What happend is that
the number of reservations made (the structs in `alloc_actv`) was
larger by one than the number of reserved entries in the undo vector,
and because the algorithm skipped `actncnt` number of entries in
the undo log (so that it doesn't call pfree() on reservations), we
incidentally skipped one valid entry of the alloc undo log when
aborting the transaction.
Ref: pmem/issues#704
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2417)
=> obj: only skip reservations actually in undo log

src/test/pmempool_sync/TEST18, src/test/pmempool_sync/TEST19, src/test/pmempool_sync/TEST20, src/test/pmempool_sync/TEST21, src/test/unittest/unittest.sh
Ref: pmem/issues#706
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2418)
=> test: fix dependency on device dax sizes

src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2420)
=> test: fix swap major-minor

utils/docker/images/install-libndctl.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2427)
=> common: fix ndctl version built inside docker

doc/libpmemobj/pmemobj_alloc.3.md, src/libpmemobj/alloc_class.c, src/libpmemobj/alloc_class.h, src/libpmemobj/memblock.c, src/libpmemobj/pmalloc.c, src/test/obj_ctl_alloc_class/obj_ctl_alloc_class.c
Ref: pmem/issues#692 pmem/issues#693 pmem/issues#700
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2430)
=> Various alloc class fixes, take 2

src/common/set.c, src/common/set.h, src/libpmemblk/blk.c, src/libpmemcto/cto.c, src/libpmemlog/log.c, src/libpmemobj/obj.c, src/libpmempool/pool.c, src/test/cto_basic/TEST0.PS1, src/test/cto_multiple_pools/TEST0, src/test/cto_multiple_pools/TEST0.PS1, src/test/cto_multiple_pools/TEST1.PS1, src/test/cto_multiple_pools/TEST2, src/test/cto_multiple_pools/TEST3, src/test/cto_multiple_pools/TEST4, src/test/cto_multiple_pools/TEST4.PS1, src/test/cto_multiple_pools/cto_multiple_pools.c, src/test/cto_stats/TEST0.PS1, src/test/cto_stats/TEST1.PS1, src/test/cto_stats/TEST2.PS1, src/test/cto_stats/TEST4.PS1, src/test/util_poolset/util_poolset.c, src/tools/pmempool/common.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2421)
=> Make pmemcto_open/pmemcto_create thread-safe

src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2434)
=> test: print error message to stderr

src/test/unicode_api/TEST0, src/test/unittest/unittest.sh, utils/docker/images/Dockerfile.fedora-25, utils/docker/images/Dockerfile.ubuntu-16.04
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2435)
=> test: install bc

src/test/cto_valgrind/memcheck5.log.match, src/test/obj_action/memcheck1.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2433)
=> test: don't verify number of suppressions hit

src/libpmemobj/heap.c, src/test/obj_action/TEST0
Ref: pmem/issues#713 pmem/issues#714
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2439)
=> obj: valgrind memcheck fixes

src/test/cto_valgrind/memcheck5.log.match, src/test/vmem_delete/TEST0, src/test/vmem_delete/vmem_delete.c
Ref: pmem/issues#710
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2438)
=> test: disable valgrind for vmem_delete

src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2441)
=> test: fix ssh rm in unittest.sh

src/test/vmmalloc_init/vmmalloc_init.c
Ref: pmem/issues#717
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2445)
=> test: fix memleak in vmmalloc_init

src/common/set.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2446)
=> common: fix issues detected by Coverity

src/test/cto_multiple_pools/cto_multiple_pools.vcxproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2455)
=> test: fix reference in cto_multiple_pools win

index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2456)
=> GH pages nitpicking

README.md, appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2471)
=> common: update AppVeyor build badge

src/libvmem/vmem.c, src/test/vmem_multiple_pools/TEST1.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2453)
=>  jemalloc: fix race in je_pool_create

utils/get_aliases.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2477)
=> common: generate aliases for libpmemcto

doc/libpmemobj/pmemobj_ctl_get.3.md, src/PMDK.sln, src/libpmemobj/heap.c, src/libpmemobj/obj.h, src/libpmemobj/palloc.h, src/libpmemobj/pmalloc.c, src/test/Makefile, src/test/obj_ctl_heap_size/.gitignore, src/test/obj_ctl_heap_size/Makefile, src/test/obj_ctl_heap_size/TEST0, src/test/obj_ctl_heap_size/TEST0.PS1, src/test/obj_ctl_heap_size/TEST1, src/test/obj_ctl_heap_size/TEST1.PS1, src/test/obj_ctl_heap_size/obj_ctl_heap_size.c, src/test/obj_ctl_heap_size/obj_ctl_heap_size.vcxproj, src/test/obj_ctl_heap_size/obj_ctl_heap_size.vcxproj.filters
This patch contains #2426, #2386 and #2358
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2428)
=> obj: implement manual pool extend

src/jemalloc/src/ctl.c, src/jemalloc/src/jemalloc.c, src/jemalloc/src/prof.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2478)
=> jemalloc: fix issues detected by Coverity

src/PMDK.sln, src/common/libpmemcommon.vcxproj.filters, src/libpmem/libpmem.vcxproj, src/libpmem/libpmem.vcxproj.filters, src/libpmemblk/libpmemblk.vcxproj, src/libpmemblk/libpmemblk.vcxproj.filters, src/libpmemcto/libpmemcto.vcxproj, src/libpmemcto/libpmemcto.vcxproj.filters, src/libpmemlog/libpmemlog.vcxproj, src/libpmemlog/libpmemlog.vcxproj.filters, src/libpmemobj/libpmemobj.vcxproj, src/libpmemobj/libpmemobj.vcxproj.filters, src/libpmempool/libpmempool.vcxproj, src/libpmempool/libpmempool.vcxproj.filters, src/libvmem/libvmem.vcxproj, src/libvmem/libvmem.vcxproj.filters, src/test/obj_action/obj_action.vcxproj.filters, src/test/obj_ctl_heap_size/obj_ctl_heap_size.vcxproj, src/test/obj_ctl_heap_size/obj_ctl_heap_size.vcxproj.filters, src/test/pmempool_create/pmempool_create.vcxproj, src/test/pmempool_create/pmempool_create.vcxproj.filters, src/test/util_poolset/util_poolset.vcxproj, src/test/util_poolset/util_poolset.vcxproj.filters
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2481)
=> common: clean up and update VS projects

src/common.inc
Ref: pmem/issues#724
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2484)
=> test: fix detection of clang template bug

src/test/rpmem_basic/TEST7
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2491)
=> test: fix call for devdax path on node

src/test/Makefile
... and sort list of tests.
Ref: pmem/issues#718
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2496)
=> test: fix build dependencies

src/test/pmem_memcpy/pmem_memcpy.c, src/test/pmem_memmove/pmem_memmove.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2487)
=> test: fix memory unmapping in libpmem tests

src/common/set.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2482)
=> common: fix long path support in pool extend

src/librpmem/rpmem.c
Ref: pmem/pmdk#2466
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2479)
=> rpmem: RPMEM_MAX_NLANES fix part 2

doc/libpmem/pmem_is_pmem.3.md
Ref: pmem/issues#719
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2485)
=> doc: clarify pmem_is_pmem behavior

doc/libpmempool/pmempool_sync.3.md, doc/librpmem/rpmem_create.3.md, doc/librpmem/rpmem_persist.3.md, doc/pmempool/pmempool-sync.1.md, doc/pmempool/pmempool-transform.1.md, doc/poolset/poolset.5.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2463)
=> doc: support for huge pages in RDMA

src/libpmemobj/obj.c
Ref: pmem/issues#735
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2501)
=> obj: free stats after pmemobj_check()

src/examples/libpmemobj++/map_cli/map_cli.cpp
Fixes "uncaught exception" issues reported by Coverity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2502)
=> examples: catch exceptions in C++ map_cli example

src/test/RUNTESTS, src/test/rpmemd_config/stdout0.log.match, src/test/rpmemd_util/stdout0.log.match, src/test/rpmemd_util/stdout1.log.match, src/test/unittest/unittest.sh, src/test/unittest/ut.c
With this patchset it's possible to do in src/test/:
```
$ UNITTEST_LOG_LEVEL=0 make pcheck -s -j8
```
and get no output from successful tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/nvml/2442)
=> test: make it possible to quiet down all normal messages from tests

src/test/obj_rpmem_basic_integration/node_1_err20.log.match
Ref: pmem/issues#720
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2508)
=> test: add missing match

src/test/obj_heap/obj_heap.c, src/test/obj_pmalloc_basic/obj_pmalloc_basic.c
Ref: pmem/issues#736
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2509)
=> test: initialize relevant set fields in mocks

src/test/RUNTESTLIB.PS1, src/test/unittest/unittest.ps1
It also introduces "msg" and "fatal" functions in Windows version
of the test scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2507)
=> test: (win) replace U..T_QUIET /w U..T_LOG_LEVEL

src/test/pmempool_sync/TEST11, src/test/pmempool_sync/TEST6, src/test/pmempool_sync/TEST6.PS1, src/test/pmempool_sync/TEST7, src/test/pmempool_sync/TEST7.PS1, src/test/pmempool_transform/TEST7, src/test/tools/ddmap/ddmap.c
Fixes regression introduced by pmem/pmdk#2401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2511)
=> test: fix ddmap

src/test/RUNTESTS, src/test/obj_rpmem_basic_integration/node_0_rpmemd20.log.match, src/test/tools/ddmap/ddmap.c
All this fixes have to go in single pull request because test type handling fix reenables some tests which require two other fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2513)
=> test: fix test type handling, ddmap arguments validation and one match file

src/jemalloc/src/chunk.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2516)
=> jemalloc: fix error handling

src/test/cto_pool/TEST14, src/test/cto_pool/TEST6, src/test/obj_cpp_pool/TEST0, src/test/obj_cpp_pool/TEST2, src/test/obj_ctl_prefault/TEST0, src/test/obj_pool/TEST14, src/test/obj_pool/TEST6, src/test/pmempool_info/TEST8, src/test/pmempool_info/TEST9, src/test/traces/TEST0
Inspired by "helpful" error message in obj_ctl_prefault:
https://bugzilla.redhat.com/show_bug.cgi?id=1365721#c11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2518)
=> test: use "fatal" function in more cases

src/tools/rpmemd/rpmemd_config.c
Return non-zero value to indicate error in parse_config_line(), instead
of depending on errno.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2519)
=> rpmemd: do not rely on errno

src/test/RUNTESTS
Ref: pmem/issues#747
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2520)
=> test: fix test type - all handling

doc/libpmemobj/pmemobj_ctl_get.3.md
Ref: pmem/issues#748
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2521)
=> common: fix ctl entry name to match the code

src/test/unittest/unittest.sh
- allow multiline messages in verbose_msg, msg and fatal
- remove trash comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2526)
=> test: allow multiline messages

src/common.inc, src/test/Makefile, src/test/Makefile.inc
Also minor build, tools and test fixes for FreeBSD 11.1/Clang 4.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2514)
=> common: Reduce restrictions on c++ tests

src/test/unittest/unittest.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2523)
=> test: run "any" tests only once if fstype == all

src/libpmempool/replica.c, src/libpmempool/replica.h, src/test/pmempool_sync/TEST24, src/test/pmempool_sync/out24.log.match
Ref: pmem/issues#731
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2531)
=> pool: fix sync with lacking replica

src/libpmempool/pool.c, src/libpmempool/pool.h, src/libpmempool/replica.c, src/libpmempool/replica.h, src/libpmempool/transform.c, src/test/pmempool_sync/TEST23, src/test/pmempool_sync/out23.log.match
Ref: pmem/issues#730
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2528)
=> pool: fix sync with switched parts

doc/Makefile, doc/generated/pmemcto_check_version.3, doc/generated/pmemcto_set_funcs.3
ref: pmem/issues#749
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2536)
=> doc: add missing pmemcto man pages

src/jemalloc/src/jemalloc.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2538)
=> jemalloc: fix issues detected by Valgrind

src/common/os_linux.c, src/test/util_file_create/TEST2, src/test/util_file_create/TEST2.PS1
Add size check to os_posix_fallocate.
Change util_file_create TEST2 to medium.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2539)
=> common: Workaround for FreeBSD bug 223287

src/common/set.c, src/libpmempool/replica.c, src/test/util_poolset/out0.log.match, src/test/util_poolset/out0w.log.match, src/test/util_poolset/out2.log.match, src/test/util_poolset/out2w.log.match, src/test/util_poolset/util_poolset.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2540)
=> common: unify parts size

src/test/compat_incompat_features/TEST0, src/test/compat_incompat_features/TEST0.PS1, src/test/compat_incompat_features/TEST1, src/test/compat_incompat_features/TEST1.PS1, src/test/compat_incompat_features/TEST2, src/test/compat_incompat_features/TEST2.PS1, src/test/compat_incompat_features/TEST3, src/test/compat_incompat_features/TEST3.PS1, src/test/compat_incompat_features/TEST4, src/test/compat_incompat_features/TEST4.PS1, src/test/compat_incompat_features/out0.log.match, src/test/compat_incompat_features/out1.log.match, src/test/compat_incompat_features/out2.log.match, src/test/compat_incompat_features/out3.log.match, src/test/compat_incompat_features/out4.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2545)
=> test: fix failing compat_incompat_features

src/common/set.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2544)
=> common: typo fix

src/test/RUNTESTS, src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2543)
=> test: disable msg with removed dir

doc/libpmemcto/libpmemcto.7.md, doc/libpmemcto/pmemcto_open.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2547)
=> doc: libpmemcto fixes

src/test/RUNTESTS, src/test/testconfig.sh.example, src/test/unittest/unittest.sh
... and fix behavior when someone sets it from testconfig.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2552)
=> test: document UNITTEST_LOG_LEVEL

doc/libpmemobj/oid_is_null.3.md, doc/libpmemobj/pmemobj_tx_add_range.3.md, doc/libpmemobj/pmemobj_tx_alloc.3.md, doc/libpmemobj/pmemobj_tx_begin.3.md, src/include/libpmemobj/base.h, src/include/libpmemobj/tx.h, src/include/libpmemobj/tx_base.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2555)
=> obj: drop experimental status from some APIs

src/libpmemobj/stats.c
Ref: pmem/issues#757
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2563)
=> obj: change stats enable flag semantics

src/test/Makefile.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2572)
=> test: restore linking to libdl for libpmempool

.travis.yml
This helps with debugging problems with travis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2577)
=> common: print TRAVIS_COMMIT_RANGE variable

utils/pmdk.spec.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2571)
=> common: rpm .spec fixes

src/test/obj_sds/obj_sds.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2579)
=> test: Close set files in obj_sds test

src/examples/libpmemobj++/pmpong/Makefile, utils/build-dpkg.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2580)
=> common: rename nvml-tools package to pmempool

src/librpmem/rpmem_fip.c
Use atomic builtins to store and read the closing flag.
This fixes errors reported by valgrind helgrind/drd.
Ref: #2532
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2576)
=> rpmem: fix data race on closing flag

src/librpmem/rpmem_util.c
Ref: pmem/issues#764
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2564)
=> rpmem: fix env variable check

src/tools/pmempool/info.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2583)
=> common: handle errno in parse_args

src/libpmemobj/tx.c, src/test/obj_tx_add_range/obj_tx_add_range.c, src/test/obj_tx_add_range/pmemcheck1.log.match
Ref: pmem/issues#781
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2588)
=> obj: fix add_range with size == 0

src/common/set.c, src/test/rpmem_basic/TEST0, src/test/rpmem_basic/TEST1, src/test/rpmem_basic/TEST12, src/test/rpmem_basic/TEST13, src/test/rpmem_basic/TEST2, src/test/rpmem_basic/TEST3, src/test/rpmem_basic/TEST4, src/test/rpmem_basic/TEST5, src/test/rpmem_basic/TEST6, src/test/rpmem_basic/TEST7, src/test/rpmem_basic/TEST8, src/test/rpmem_basic/TEST9, src/test/rpmem_basic/common_pm_policy.sh, src/test/rpmem_basic/node_1_out13.log.match, src/test/rpmem_basic/node_1_out5.log.match, src/test/rpmem_basic/node_1_out6.log.match, src/test/rpmem_basic/node_1_out7.log.match, src/test/rpmem_basic/rpmem_basic.c, src/test/rpmemd_db/rpmemd_db_test.c
Ref: pmem/issues#762
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2584)
=> pool: fix checking remote poolset options

doc/libpmemblk/pmemblk_create.3.md, doc/libpmemcto/pmemcto_open.3.md, doc/libpmemlog/pmemlog_create.3.md, doc/libpmemobj/pmemobj_open.3.md
Ref: pmem/issues#777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2585)
=> doc: update description of 'path' in pmem*_create

src/test/pmem_deep_persist/TEST8, src/test/pmem_deep_persist/TEST9
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2595)
=> test: add SINGLEHDR to pmem_deep_persist

src/test/obj_cpp_ptr/obj_cpp_ptr.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2596)
=> test: fix compilation with latest clang

src/test/obj_cpp_ptr/obj_cpp_ptr.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2599)
=> test: fix compilation with latest clang (1.3.2)

doc/Makefile, doc/generated/pmem_deep_persist.3, doc/libpmem/pmem_flush.3.md
Should be merged after #2468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2581)
=> doc: add pmem_deep_persist doc

src/test/blk_include/TEST0, src/test/cto_include/TEST0, src/test/libpmempool_include/TEST0, src/test/log_include/TEST0, src/test/obj_include/TEST0, src/test/pmem_include/TEST0
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2602)
=> test: do not require fs for 'include' tests

src/libpmemlog/libpmemlog.vcxproj.filters
Ref: pmem/issues#785
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2607)
=> common: fix libpmemlog.vcxproj.filters tags

src/Makefile.inc, utils/build-rpm.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2570)
=>  common: use system-default CFLAGS/LDFLAGS when building packages (1.3.x)

src/common/set.c, src/common/shutdown_state.c, src/common/shutdown_state.h, src/libpmempool/replica.c, src/test/obj_persist_count/obj_persist_count.vcxproj, src/test/obj_persist_count/out0.log.match, src/test/obj_persist_count/out1.log.match, src/test/util_sds/util_sds.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2605)
=> common: integrate SDS with deep_persist

doc/libpmemcto/libpmemcto.7.md, doc/libpmemcto/pmemcto_aligned_alloc.3.md, doc/libpmemcto/pmemcto_malloc.3.md, doc/libpmemcto/pmemcto_malloc_usable_size.3.md, doc/libpmemcto/pmemcto_open.3.md, doc/libpmemcto/pmemcto_set_root_pointer.3.md, doc/libpmemcto/pmemcto_strdup.3.md, doc/libpmemcto/pmemcto_wcsdup.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2611)
=> doc: fix pmemcto man pages

src/test/obj_convert/TEST17
Ref: pmem/issues#581
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2614)
=> test: change obj_convert/TEST17 to require vg3.12

src/windows/include/err.h, src/windows/include/platform.h, src/windows/include/sys/file.h, src/windows/include/sys/mman.h, src/windows/include/sys/param.h, src/windows/include/sys/uio.h
Ref: pmem/issues#792
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2621)
=> common: fix header guards and clean up comments

doc/generated/pmemcto_realloc.3
Ref: pmem/issues#791
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2622)
=> doc: fix pmemcto_realloc man page

src/tools/pmempool/convert_obj_v3_v4.c
Ref: pmem/issues#336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2618)
=> pmempool: fix set convert of v3 -> v4

src/libpmemobj/tx.c, src/test/obj_cpp_ptr_arith/obj_cpp_ptr_arith.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2612)
=> obj: detect snapshots of uninitialized data

src/test/tools/pmemdetect/pmemdetect.c
Fix overwriting errno when checking for MAP_SYNC support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2608)
=> test: fix error handling in pmemdetect

src/test/obj_sds/TEST7
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2630)
=> test: add additional obj_sds test

src/libpmempool/transform.c
Ref: pmem/issues#793
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2637)
=> pool: fix crash on transform with NOHDRS option

src/test/obj_convert/TEST17
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2638)
=> test: change old valgrind require function

src/common/out.c, src/common/shutdown_state.h, src/include/libpmemobj++/README.md, src/test/unittest/unittest.sh, utils/docker/build-local.sh, utils/docker/build-travis.sh, utils/docker/images/Dockerfile.fedora-25, utils/docker/images/Dockerfile.ubuntu-16.04, utils/docker/images/build-image.sh, utils/docker/images/push-image.sh, utils/docker/pull-or-rebuild-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2639)
=> common: project renaming cont.

src/include/libpmemobj/tx.h, src/test/obj_basic_integration/obj_basic_integration.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2640)
=> obj: single implementation of TX_REALLOC/TX_ZREALLOC

src/common/file_posix.c, src/common/os_deep_linux.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2625)
=> common: handle invalid dax reg id

doc/generated/pmem_deep_drain.3, doc/generated/pmem_deep_flush.3, doc/libpmem/libpmem.7.md, doc/libpmem/pmem_flush.3.md
Merge after PR #2600
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2615)
=> doc: add pmem_deep_flush/drain

src/common/os_windows.c, src/examples/libpmemobj++/pmpong/pmpong.vcxproj, src/examples/libpmemobj++/pmpong/pmpong.vcxproj.filters, src/test/unittest/unittest.ps1, src/windows/win_mmap.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2632)
=> win: a few various fixes

src/test/obj_action/TEST2, src/test/obj_action/pmemcheck2.log.match
force enabling pmemcheck failed for TEST0, so I added a new TEST2 with a match and disabled it for TEST0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2631)
=> test: add obj_action pmemcheck test

src/libpmemobj/pvector.c
Ref: pmem/issues#796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2644)
=> obj: fix pvector pmemcheck instrumentation

src/libpmemobj/ravl.c
Ref: pmem/issues#797
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2645)
=> obj: fix memleak on ravl duplicate entries

src/examples/libpmemobj/pmemblk/obj_pmemblk.c, src/examples/libpmemobj/pminvaders/pminvaders2.c, src/test/obj_cpp_p_ext/obj_cpp_p_ext.cpp, src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c, src/test/obj_tx_locks_abort/obj_tx_locks_abort.c, src/test/obj_tx_mt/obj_tx_mt.c
Ref: pmem/issues#798
Ref: pmem/issues#799
Ref: pmem/issues#800
Ref: pmem/issues#803
Ref: pmem/issues#804
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2646)
=> test: fix uninitialized snapshots

src/benchmarks/obj_locks.cpp, src/benchmarks/obj_pmalloc.cpp, src/benchmarks/pmembench.cpp, src/benchmarks/pmemobj_gen.cpp, src/benchmarks/pmemobj_tx.cpp, src/common/set.c, src/jemalloc/src/jemalloc.c, src/libpmemobj/heap.c, src/libpmemobj/tx.c
With an exception of memory leak in pmembench, mostly false positives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2634)
=> common: clang analyzer fixes

src/common/file_posix.c, src/test/pmem_is_pmem_posix/pmem_is_pmem_posix.c
Ref: pmem/issues#801
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2647)
=> common: handle null path in file_posix

src/common/set.c, src/test/util_poolset_parse/grep0.log.match, src/test/util_poolset_parse/grep0w.log.match
Ref: pmem/issues#784
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2650)
=> common: clarify poolset parsing error

src/test/pmem_deep_persist/pmem_deep_persist.c
Ref: pmem/issues#802
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2648)
=> test: define deep_persist memory

doc/Makefile, doc/generated/rpmem_deep_persist.3
Ref: pmem/issues#810
Ref: pmem/issues#811
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2652)
=> doc: add missing man pages

src/libpmemobj/ravl.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2657)
=> obj: simplify ravl_find predicate handling

src/test/RUNTESTS
Ref: pmem/issues#812
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2655)
=> test: skip tests on KEEP_GOING

src/common/os_dimm_ndctl.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2664)
=> common: do not copy stat_t struct

src/libpmempool/replica.c, src/test/pmempool_sync/TEST25, src/test/pmempool_sync/out25.log.match
Comparing declared and actual sizes of a device dax parts is added.
Ref: pmem/issues#805
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2663)
=> pool: fix checking device dax size

src/common/os_windows.c
Ref: pmem/issues#813
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2672)
=> common: fix NULL check in os_fopen

src/test/RUNTESTLIB.PS1, src/test/RUNTESTS.PS1, src/test/unittest/unittest.ps1
Every error in powershell script will result in script termination
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2668)
=> test: powershell exit on error

src/test/unittest/unittest.sh
valgrind tools issue a warning whenever sbrk() reaches its
limit, this is a perfectly normal situation and we can safely
ignore it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2676)
=> test: ignore unsupressable sbrk valgrind warning

src/test/unittest/unittest.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2685)
=> test: (win) redirect mkdir output to prepX.log

src/common/set.c, src/test/util_poolset_parse/TEST4, src/test/util_poolset_parse/grep4.log.match
Ref: pmem/issues#814
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2686)
=> common: disallow duplicated poolset directories

src/test/RUNTESTLIB.PS1, src/test/RUNTESTS.PS1, src/test/unittest/unittest.ps1
This reverts commit 8e3f2669c8028bad102b56fa743d2fdd098a386f.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2689)
=> test: revert powershell exit on error

src/include/libpmemobj/ctl.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2691)
=> obj: fix typo

src/libpmem/libpmem.vcxproj, src/libpmem/libpmem.vcxproj.filters, src/test/RUNTESTLIB.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2693)
=> Mini-cleanup of VS projects

src/test/Makefile, utils/docker/images/install-libfabric.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2696)
=> common: prepare for libfabric v1.6.0

src/common/os_dimm_ndctl.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2698)
=> common: fix USC_VALID_FLAG check

src/common.inc, utils/docker/images/Dockerfile.fedora-25, utils/docker/images/install-libfabric.sh, utils/docker/images/install-libndctl.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2697)
=> common: build ndctl packages in Docker

src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2699)
=> test: fix typo

src/test/sync-remotes/copy-to-remote-nodes.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2703)
=> test: ignore pmem/non-pmem fs dirs in sync-remotes

src/common/os_dimm_ndctl.c, src/tools/daxio/daxio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2702)
=> common: fix compilation errors on Fedora rawhide

utils/docker/images/install-libfabric.sh, utils/pmdk.spec.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2705)
=> common: .spec update and libfabric downgrade

doc/Makefile, doc/generated/pmem_has_auto_flush.3, doc/libpmem/libpmem.7.md, doc/libpmem/pmem_flush.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2706)
=> doc: pmem_has_auto_flush

src/test/tools/pmemdetect/pmemdetect.c
Changed on @mramotowski request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2708)
=> common: change one pmemdetect on skip message

src/libpmemcto/cto.c, src/libpmemcto/cto.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2714)
=> cto: deep persist entire replica before close

src/common.inc, src/common/shutdown_state.c, src/test/util_sds/util_sds.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2715)
=> common: do not modify SDS if not compiled with ndctl

doc/poolset/poolset.5.md, src/common/fs_windows.c, src/common/set.c, src/test/util_poolset/TEST5, src/test/util_poolset/out5.log.match, src/test/util_poolset/out5w.log.match
Ref: pmem/issues#824
Ref: pmem/issues#823
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2720)
=> common: directory based poolset fixes

src/benchmarks/log.cpp, src/common/util.h, src/libpmempool/replica.c, src/libpmempool/replica.h
pmem/issues#830
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2721)
=> pool: fix part offset and alignment calculations

src/test/helgrind-log.supp
Ignore race on writing to log files.
Ref: pmem/issues#808
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2725)
=> test: update helgrind suppression file

doc/libpmemobj/pmemobj_action.3.md, src/include/libpmemobj/action_base.h, src/libpmemobj/obj.c, src/libpmemobj/tx.c
This patch is preparation of lifting the action limit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2726)
=> obj: change action count to size_t

_layouts/manual.html, _layouts/pmdk.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2736)
=> doc: add links to ndctl man page

_data/releases_linux.yml, daxio/index.md, index.md, manpages/linux/master/daxio/daxio.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2737)
=> doc: add daxio man page

src/common/out.c, src/libpmemobj/obj.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2742)
=> common: fix free function in tls

src/benchmarks/pmembench.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2747)
=> benchmark: compute latency median

doc/libpmempool/pmempool_sync.3.md, src/libpmempool/transform.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2741)
=> pool: pmempool_transform errors

src/benchmarks/blk.cpp, src/benchmarks/log.cpp, src/benchmarks/map_bench.cpp, src/benchmarks/obj_lanes.cpp, src/benchmarks/obj_locks.cpp, src/benchmarks/obj_pmalloc.cpp, src/benchmarks/pmem_flush.cpp, src/benchmarks/pmem_memcpy.cpp, src/benchmarks/pmem_memset.cpp, src/benchmarks/pmembench.cpp, src/benchmarks/pmemobj_atomic_lists.cpp, src/benchmarks/pmemobj_gen.cpp, src/benchmarks/pmemobj_persist.cpp, src/benchmarks/pmemobj_tx.cpp, src/benchmarks/rpmem_persist.cpp, src/benchmarks/vmem.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2744)
=> pmembench: pmem_memcpy benchmark improvements

src/libpmemobj/tx.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2750)
=> obj: fix issues reported by clang static analyzer 

src/examples/libpmemobj++/map_cli/map_cli.cpp
Fixes issues detected by Coverity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2746)
=> examples: catch exceptions in map_cli

src/benchmarks/benchmark.hpp, src/benchmarks/pmem_memcpy.cpp, src/benchmarks/pmem_memset.cpp, src/benchmarks/pmembench.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2754)
=> benchmark: print bandwidth in some benchmarks

src/test/pmempool_create/TEST10, src/test/pmempool_create/TEST11, src/test/pmempool_info/TEST24, src/test/pmempool_info/TEST25, src/test/unittest/unittest.sh, src/test/util_badblock/TEST2, src/test/util_badblock/TEST3, src/test/util_badblock/TEST4, src/test/util_badblock/TEST5, src/test/util_badblock/TEST6, src/test/util_badblock/TEST7
... to bad blocks tests.
NDCTL_ENABLE=y has to be set since the commit 38271b.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2748)
=> test: add require_ndctl_enabled

src/common/set.c, src/test/rpmem_basic/TEST2
Ref: pmem/issues#839
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2755)
=> rpmem: do not write SDS when NOHDRS option is used

src/benchmarks/blk.cpp, src/benchmarks/log.cpp, src/benchmarks/pmem_flush.cpp, src/benchmarks/pmem_memcpy.cpp, src/benchmarks/pmem_memset.cpp, src/benchmarks/pmemobj_gen.cpp, src/benchmarks/vmem.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2758)
=> benchmark: device dax support for more benchmarks

src/common/set.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2762)
=> common: set errno if bad blocks are found

src/tools/daxio/daxio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2761)
=> daxio: get device dax alignment properly

src/test/common_badblock.sh, src/test/util_badblock/TEST8, src/test/util_badblock/TEST9, src/test/util_badblock/err8.log.match, src/test/util_badblock/err9.log.match, src/test/util_badblock/util_badblock.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2764)
=> test: add two new util_badblock tests

src/examples/libpmemobj++/map_cli/map_cli.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2760)
=> examples: catch more exceptions in map_cli

doc/pmempool/pmempool-create.1.md, src/common/badblock_poolset.c, src/common/badblock_poolset.h, src/common/set.c, src/test/pmempool_create/TEST12, src/test/pmempool_create/out10.log.match, src/test/pmempool_create/out11.log.match, src/tools/pmempool/common.c, src/tools/pmempool/common.h, src/tools/pmempool/create.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2763)
=> pool: clear bad blocks in pmempool-create

src/libpmempool/check_sds.c, src/test/pmempool_check/out28.log.match, src/test/pmempool_check/out29.log.match, src/test/pmempool_check/out30.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2778)
=> pool: fix some typos in SDS code and tests

src/include/libpmemobj/tx.h, src/libpmemobj/heap.c, src/test/tools/pmemobjcli/pmemobjcli.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2774)
=> obj: fix clang-7 compilation

src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2780)
=> test: fix one message in unittest.sh

src/libpmempool/transform.c
Ref: pmem/issues#835
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2733)
=> pool: fix incorrect errno after transform

src/PMDK.sln
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2782)
=> doc: add man pages to VS solution

src/common/badblock_poolset.c, src/common/set.c, src/common/set.h, src/libpmempool/rm.c, src/test/rpmemd_db/rpmemd_db_test.c, src/test/util_poolset_foreach/util_poolset_foreach.c, src/tools/pmempool/rm.c, src/tools/rpmemd/rpmemd_db.c
...  in the poolset structure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2775)
=> common: fix saving bad blocks flag

src/test/pmempool_info/TEST25, src/test/pmempool_info/out24.log.match, src/test/pmempool_info/out25.log.match
... and simplify pmempool_info/TEST25.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2784)
=> test: make 2 pmempool_info match files more exact

src/libpmempool/check.c, src/libpmempool/check_bad_blocks.c, src/libpmempool/check_util.h, src/libpmempool/libpmempool.vcxproj, src/libpmempool/libpmempool.vcxproj.filters, src/test/common_badblock.sh, src/test/pmempool_check/TEST31, src/test/pmempool_check/TEST32, src/test/pmempool_check/out31.log.match, src/test/pmempool_check/out32.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2779)
=> pool: check bad blocks in pmempool-check

src/libpmempool/replica.c, src/test/common_badblock.sh, src/test/pmempool_sync/TEST27, src/test/pmempool_sync/TEST28, src/test/pmempool_sync/out27.log.match, src/test/pmempool_sync/out28.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2773)
=> pool: clear bad blocks in pmempool-sync

doc/libpmem/libpmem.7.md, doc/libpmem/pmem_flush.3.md
Replaces "eADR" with more generic description of this mechanism.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2792)
=> doc: rephrase paragraphs mentioning eADR

doc/libpmem/libpmem.7.md, doc/libpmem/pmem_flush.3.md
Replaces "eADR" with more generic description of this mechanism.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2791)
=> doc: [1.4] rephrase paragraphs mentioning eADR

doc/README, doc/libpmem/pmem_flush.3.md, doc/libpmemcto/libpmemcto.7.md, doc/libpmemobj/libpmemobj.7.md, doc/libpmemobj/pmemobj_action.3.md, doc/libpmemobj/pmemobj_alloc.3.md, doc/libpmemobj/pmemobj_ctl_get.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2797)
=> doc: [1.4] mark experimental APIs in man pages

doc/README, doc/libpmem/pmem_flush.3.md, doc/libpmemcto/libpmemcto.7.md, doc/libpmemobj/libpmemobj.7.md, doc/libpmemobj/pmemobj_action.3.md, doc/libpmemobj/pmemobj_alloc.3.md, doc/libpmemobj/pmemobj_ctl_get.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2798)
=> doc: mark experimental APIs in man pages

src/test/RUNTESTLIB.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2796)
=> test: reset env variables which can affect tests

doc/daxio/daxio.1.md, doc/pmempool/pmempool-check.1.md, doc/pmempool/pmempool-convert.1.md, doc/pmempool/pmempool-create.1.md, doc/pmempool/pmempool-dump.1.md, doc/pmempool/pmempool-info.1.md, doc/pmempool/pmempool-rm.1.md, doc/pmempool/pmempool-sync.1.md, doc/pmempool/pmempool-transform.1.md, doc/pmempool/pmempool.1.md, doc/rpmemd/rpmemd.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2789)
=> doc: update man page version numbers

doc/daxio/daxio.1.md, doc/pmempool/pmempool-check.1.md, doc/pmempool/pmempool-convert.1.md, doc/pmempool/pmempool-create.1.md, doc/pmempool/pmempool-dump.1.md, doc/pmempool/pmempool-info.1.md, doc/pmempool/pmempool-rm.1.md, doc/pmempool/pmempool-sync.1.md, doc/pmempool/pmempool-transform.1.md, doc/pmempool/pmempool.1.md, doc/rpmemd/rpmemd.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2795)
=> doc: [1.4] update man page version numbers

src/version.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2809)
=> common: SRCVERSION for out of git tree builds
