src/test/unittest/unittest.ps1, src/test/util_poolset/TEST0w.PS1, src/test/util_poolset/TEST5w.PS1, src/test/util_poolset/grep0w.log.match, src/test/util_poolset/out0w.log.match, src/test/util_poolset/util_poolset.vcxproj, src/test/util_poolset/util_poolset.vcxproj.filters, src/test/util_sds/err6.log.match, src/test/util_sds/err7.log.match, src/test/win_getopt/TEST0.PS1
This patch fixes multiple matches issue on windows - test check was skipping when test had 2 or more mach files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2802)
=> test: win: fix multiple matches issue

src/benchmarks/pmembench.vcxproj, src/common/libpmemcommon.vcxproj, src/test/blk_non_zero/blk_non_zero.vcxproj, src/test/blk_pool/blk_pool.vcxproj, src/test/blk_pool_lock/blk_pool_lock.vcxproj, src/test/blk_rw/blk_rw.vcxproj, src/test/blk_rw_mt/blk_rw_mt.vcxproj, src/test/test_debug.props, src/test/test_release.props, src/test/tools/bttcreate/bttcreate.vcxproj, src/test/tools/cmpmap/cmpmap.vcxproj, src/test/tools/ddmap/ddmap.vcxproj, src/test/tools/pmemalloc/pmemalloc.vcxproj, src/test/tools/pmemobjcli/pmemobjcli.vcxproj, src/test/tools/pmemspoil/pmemspoil.vcxproj, src/test/tools/pmemwrite/pmemwrite.vcxproj, src/test/unittest/libut.vcxproj, src/tools/pmempool/pmempool.vcxproj, src/windows/libs_debug.props, src/windows/libs_release.props, src/windows/srcversion/srcversion.vcxproj
Generate Manifest should always be set to true, what is a default value,
so we can remove it from all project files
Manifest is required for long path support
Ref: pmem/issues#842
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2805)
=> common: remove GenerateManifest from projects

src/common/set.c, src/common/set.h, src/common/util.h, src/libpmemcto/cto.c, src/libpmempool/check_sds.c, src/libpmempool/pool.c, src/libpmempool/replica.c, src/libpmempool/replica.h, src/libpmempool/sync.c, src/libpmempool/transform.c, src/tools/pmempool/common.c
This patch is so long, because I had to change the way those macros/functions return value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2799)
=> common: replace REP*/PART*/HDR* macros by functions

src/libpmempool/replica.c
If bad blocks were found only the replica was marked as broken,
but each part containing bad blocks should also be marked as broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2806)
=> pool: mark also part as broken

src/libpmempool/sync.c
Remove redundant (doubled) calculation of 'len'
left by the b83fbe152c commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2810)
=> pool: fix copy_data_to_broken_parts()

src/benchmarks/rpmem_persist.cpp
Ref: pmem/issues#600
Backport from master. Needed because new compilers warn about it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2813)
=> benchmark: [1.3] fix buffer overflow in rpmem_persist

src/common/os_dimm_ndctl.c
The bbs 'badblocks' structure has to be zeroed,
because if (region == NULL || ndns == NULL)
then bbs has to contain valid data (zeros).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2819)
=> common: zero badblocks structure

src/include/libpmemobj++/detail/common.hpp
Remove unused internal function from the C++ bindings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2820)
=> cpp: removed unused internal function

src/libpmempool/replica.h, src/libpmempool/sync.c
Remove the 'flags' argument and the 'is_dry_run(flags)' check,
because this functions is called only once just after this check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2823)
=> pool: simplify recreate_broken_parts()

src/libpmemobj/alloc_class.c
This case is probably harmless, but in general comparing floats
for equality may be a source of "funny" bugs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2825)
=> obj: don't compare floats

src/examples/libpmemobj++/map_cli/map_cli.cpp, src/examples/libpmemobj++/panaconda/panaconda.cpp, src/include/libpmemobj++/transaction.hpp, src/test/obj_cpp_cond_var/obj_cpp_cond_var.cpp, src/test/obj_cpp_cond_var_posix/obj_cpp_cond_var_posix.cpp, src/test/obj_cpp_mutex/obj_cpp_mutex.cpp, src/test/obj_cpp_mutex_posix/obj_cpp_mutex_posix.cpp, src/test/obj_cpp_shared_mutex/obj_cpp_shared_mutex.cpp, src/test/obj_cpp_shared_mutex_posix/obj_cpp_shared_mutex_posix.cpp, src/test/obj_cpp_timed_mtx/obj_cpp_timed_mtx.cpp, src/test/obj_cpp_timed_mtx_posix/obj_cpp_timed_mtx_posix.cpp
Intention of this PR is to replace NULL with nullptr.
Test/examples are compiled with -std=c++11, which means nullptr value is supported by these module.
I could prepare additional PR for benchmark module with similar changes and additional for makefile to change the std to c++11, but I don't know if it is possible, because of:
https://github.com/pmem/pmdk/commit/485a455a64ded76f824fe4dd2b5bf6d3087287b7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2836)
=> common: replace NULL with nullptr

utils/build-rpm.sh, utils/pmdk.spec.in
Replaces "--with rpmem" with "--with fabric".
Makes "check" step to be enabled by default, unless explicilty disabled
with "_skip_check=1".
Uses default test configuration, if "_testconfig" is not supplied.
Adds version to the obsoleted "nvml-tools" subpackage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2815)
=> common: rpm spec improvements

src/libpmempool/sync.c
Remove unnecessary is_dry_run() calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2839)
=> pool: simplify replica_sync()

src/common/badblock_freebsd.c, src/common/badblock_linux.c, src/common/badblock_windows.c, src/common/os_badblock.h, src/common/os_dimm.h, src/common/os_dimm_ndctl.c, src/common/os_dimm_none.c, src/common/os_dimm_windows.c
The os_badblocks_get_and_clear() function will be needed for
advanced support for bad blocks in pmempool-sync.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2821)
=> common: add os_badblocks_get_and_clear()

src/libpmempool/replica.c
if (set_hs->nreplicas == 1) then
replica_is_replica_consistent() should be checked too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2840)
=> pool: fix replica_find_healthy_replica()

src/benchmarks/benchmark_worker.cpp, src/benchmarks/blk.cpp, src/benchmarks/clo.cpp, src/benchmarks/clo_vec.cpp, src/benchmarks/config_reader.cpp, src/benchmarks/log.cpp, src/benchmarks/map_bench.cpp, src/benchmarks/obj_lanes.cpp, src/benchmarks/obj_locks.cpp, src/benchmarks/obj_pmalloc.cpp, src/benchmarks/pmem_flush.cpp, src/benchmarks/pmem_memcpy.cpp, src/benchmarks/pmem_memset.cpp, src/benchmarks/pmembench.cpp, src/benchmarks/pmemobj_atomic_lists.cpp, src/benchmarks/pmemobj_gen.cpp, src/benchmarks/pmemobj_persist.cpp, src/benchmarks/pmemobj_tx.cpp, src/benchmarks/rpmem_persist.cpp, src/benchmarks/scenario.cpp, src/benchmarks/vmem.cpp
Intention of this PR is use nullptr in cpp files (benchmark module)
Since commit 3e4400bcddcbe22fd67438a3efe11733da60a57d benchmark module is compiled with |std=c++11| which means it supports nullptr
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2849)
=> benchmark: use nullptr instead of NULL

src/librpmem/rpmem.c
Fix typo at the description of rpmem_deep_persist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2855)
=> rpmem : (trivial) fix typo of rpmem_deep_persist

src/Makefile.inc, src/jemalloc/jemalloc.mk, src/libpmemobj/alloc_class.c, src/test/unittest/Makefile, src/tools/Makefile.inc, src/tools/pmempool/output.c, utils/check_license/Makefile
Intention of this PR is to cover the issue with compare floats.
I saw commit:
https://github.com/pmem/pmdk/commit/08654d275c1646dc07da7324d27f0f0f2c1dc911
Wfloat-equal warning is supported by Clang and GCC - it would detect issue from commit above during compilation.
I'm not sure of my changes in alloc_class.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2848)
=> obj: add Wfloat-equal warning flag

src/test/tools/pmemobjcli/pmemobjcli.c
Checking oid, oidp, src, dest, head_oid pointers in pmemobjcli are not referencing NULL. If yes, then return appropriate errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2857)
=> pmemobjcli: checking for NULL and invalid values

src/benchmarks/benchmark_worker.cpp, src/benchmarks/blk.cpp, src/benchmarks/clo.cpp, src/benchmarks/clo_vec.cpp, src/benchmarks/log.cpp, src/benchmarks/map_bench.cpp, src/benchmarks/obj_lanes.cpp, src/benchmarks/obj_locks.cpp, src/benchmarks/obj_pmalloc.cpp, src/benchmarks/pmem_flush.cpp, src/benchmarks/pmem_memcpy.cpp, src/benchmarks/pmem_memset.cpp, src/benchmarks/pmembench.cpp, src/benchmarks/pmemobj_atomic_lists.cpp, src/benchmarks/pmemobj_gen.cpp, src/benchmarks/pmemobj_persist.cpp, src/benchmarks/pmemobj_tx.cpp, src/benchmarks/rpmem_persist.cpp, src/benchmarks/vmem.cpp
Intention of this PR is improve a readability and maintenance of cpp code.
C+11 introduce auto specifier. 
When a variable is declared and initialized with a cast, the variable type is written two times: in the declaration type and in the cast expression. In this cases, the declaration type can be replaced with auto.
Variable type is present on the right side on initialization so IMHO there is no need to repeat it when auto specifier is available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2859)
=> benchmark: use auto in declaration type

src/Makefile.inc, src/jemalloc/jemalloc.mk, src/libpmemobj/ctl.c, src/libpmemobj/heap.c, src/libpmemobj/tx.c, src/test/tools/ctrld/ctrld.c, src/test/tools/pmemobjcli/pmemobjcli.c, src/test/unittest/Makefile, src/tools/Makefile.inc, src/tools/pmempool/check.c, src/tools/pmempool/output.c, src/tools/pmempool/rm.c, utils/check_license/Makefile
Intention of this PR is to extend diagnostic during compilation.
Wswitch-default is responsible to point a place where switch statement do not have a default case, which might lead to complex logical errors and resultant weaknesses.
This warning is currently disabled in project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2858)
=> obj: add Wswitch-default warning flag

src/benchmarks/pmemobj_atomic_lists.cpp
function get_move_item always return value 0 - it could be replaced to "void get_move_item" to simplify the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2863)
=> benchmark: remove dead code

src/test/Makefile
Test was failing on one of the rc releases of libfabric 1.6.0.
In final release test pass without errors.
Ref: pmem/pmdk#2696
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2877)
=> test: enable rpmem_addr_ext

src/benchmarks/Makefile, src/benchmarks/benchmark.hpp, src/benchmarks/blk.cpp, src/benchmarks/log.cpp, src/benchmarks/map_bench.cpp, src/benchmarks/obj_pmalloc.cpp, src/benchmarks/pmembench.cpp, src/benchmarks/pmembench.vcxproj, src/benchmarks/pmembench.vcxproj.filters, src/benchmarks/pmemobj_tx.cpp, src/benchmarks/poolset_util.cpp, src/benchmarks/poolset_util.hpp, src/common/file.c, src/common/file.h, src/common/util.h
When flag '-p' is specified benchmark expects testfile to be absolute path to directory in which it will create
pool from variable number of parts (depending on benchmark needs). Parts can be resued by multiple runs.
This patch allowed to decrease total time needed by benchmark on windows from 12h to 5h.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2830)
=> benchmark: allow benchmarks to reuse files

src/tools/pmempool/Makefile, src/tools/pmempool/bash_completion/pmempool, utils/build-dpkg.sh, utils/pmdk.spec.in
Drop the interpreter from script and drop .sh extension.
Ref: pmem/issues#860
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2879)
=> pool: fix bash completion script

utils/docker/run-coverity.sh
Modifies the original coverity build script to print the full response.
This way, we'll see the reason of the failure in the Travis build logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2893)
=> common: diagnose Coverity scan upload failures

src/common/mmap_posix.c, src/libpmempool/check_pool_hdr.c, src/test/tools/ctrld/ctrld.c, src/test/tools/pmemspoil/spoil.c, src/tools/pmempool/check.c, src/tools/pmempool/convert.c, src/tools/pmempool/create.c, src/tools/pmempool/dump.c, src/tools/pmempool/info.c, src/tools/pmempool/rm.c, src/tools/pmempool/synchronize.c, src/tools/pmempool/transform.c, src/tools/rpmemd/rpmemd_config.c, utils/check_license/check-license.c
Intention of this PR is to fix potential issues with string format specifier.
1.Format specifiers for help message's could be constant pointer to prevent point to any other data.
2.It is always safer to add %s specifier to print string
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2894)
=> common: fix format specifier for string

src/test/obj_pmalloc_mt/TEST3
DRD is very finnicky about the test duration, the smallest of
change can considerably lengthen the test run. Its functionality
is mostly mirrored in helgrind which will still be ran at every
build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2919)
=> test: change obj_pmalloc_mt/drd to long

src/libpmemobj/pmalloc.c, src/test/obj_ctl_alignment/obj_ctl_alignment.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2921)
=> obj: fix ctl get of alloc class alignment

doc/Makefile, doc/generated/pmemobj_volatile.3, doc/libpmemobj/oid_is_null.3.md, src/PMDK.sln, src/examples/libpmemobj++/doc_snippets/persistent.cpp, src/include/libpmemobj++/detail/volatile.hpp, src/include/libpmemobj++/v.hpp, src/include/libpmemobj/base.h, src/libpmemobj/libpmemobj.def, src/libpmemobj/libpmemobj.map, src/libpmemobj/sync.c, src/test/Makefile, src/test/obj_cpp_v/.gitignore, src/test/obj_cpp_v/Makefile, src/test/obj_cpp_v/TEST0, src/test/obj_cpp_v/TEST0.PS1, src/test/obj_cpp_v/obj_cpp_v.cpp, src/test/obj_cpp_v/obj_cpp_v.vcxproj, src/test/obj_cpp_v/obj_cpp_v.vcxproj.filters, src/test/obj_direct_volatile/.gitignore, src/test/obj_direct_volatile/Makefile, src/test/obj_direct_volatile/TEST0, src/test/obj_direct_volatile/TEST0.PS1, src/test/obj_direct_volatile/obj_direct_volatile.c, src/test/obj_direct_volatile/obj_direct_volatile.vcxproj, src/test/obj_direct_volatile/obj_direct_volatile.vcxproj.filters, src/test/scope/out4.log.match, src/test/scope/out4w.log.match
This patch adds a new feature that allows arbitrary
volatile (transient) variables to reside on persistent memory.
Ref: pmem/issues#491
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2624)
=> obj: add lazily initialized volatile variables

src/common/set.c, src/common/set.h, src/common/shutdown_state.c, src/common/shutdown_state.h, src/test/pmempool_sync_remote/TEST20, src/test/util_sds/util_sds.c
This path adds a runtime dirty flag tracker to not update a dirty flag
if the pool is corrupted. This is needed to distinguish between a dirty
flag set in current program runtime(which we can clear on close) and
dirty flag set in previous run which now shows that the pool is
corrupted (we can't clear it)
Ref: pmem/issues#865
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2920)
=> common: don't clear sds drity flag on broken pool

utils/check-commit.sh
Fixes regression from 1210b7af2025d55889dd3ba31c520e480271153b.
Nobody noticed because of Travis failure (invalid TRAVIS_COMMIT_RANGE).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2943)
=> common: fix commit message check

src/libpmemobj/obj.c, src/test/obj_list/obj_list_mocks.c, src/test/obj_list/obj_list_mocks_palloc.c, src/test/obj_memcheck/TEST0, src/test/obj_memcheck/memcheck0.log.match, src/test/obj_pmalloc_basic/obj_pmalloc_basic.c, src/test/obj_redo_log/obj_redo_log.c
Casting function to incompatible prototype is an undefined
behavior (see linked issue).
I had to remove "Unaddressable byte(s) found during client check
request" messages from obj_memcheck match file, because with
the new entry in the stack trace (obj_msync_nofail), Valgrind
merges the last 2 errors into the first one (it compares only
the first 4 entries in the stack trace when deciding to merge).
Ref: pmem/issues#867
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2933)
=> obj: test for msync failures in non-pmem path

src/test/obj_pool/TEST17
Change obj_pool/TEST17 to use 2^64-1 rather than getconf ULONG_MAX.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=164049
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2942)
=> test: Workaround getconf(1) bug in FreeBSD

src/test/pmempool_check/TEST31, src/test/pmempool_create/TEST11, src/test/pmempool_info/TEST25, src/test/pmempool_sync/TEST27, src/test/tools/extents/README, src/test/tools/extents/extents.c, src/test/util_badblock/TEST6, src/test/util_badblock/TEST7, src/test/util_badblock/TEST9
The patch extends capabilities of the 'extents' tool.
If a logical offset is given, than the output of this command
is the physical offset of the given logical one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2936)
=> test: print physical offset of given logical one

src/Makefile.inc, src/jemalloc/jemalloc.mk, src/test/unittest/Makefile, src/tools/Makefile.inc, utils/check_license/Makefile
Intention of this PR is to extend compilation warnings - add to compilation warning, when a function pointer is cast to an incompatible function pointer. For details please see : https://gcc.gnu.org/gcc-8/changes.html
I tested it locally: Ubuntu 18.04 LTS - gcc-8 (Ubuntu 8.1.0-1ubuntu1) 8.1.0- after merging changes from https://github.com/pmem/pmdk/pull/2933 compilation pass.
I kindly ask to review it - after https://github.com/pmem/pmdk/pull/2933 is merged  ( Ref: https://github.com/pmem/issues/issues/867#issuecomment-389590191 )
After merge I highly recommend to create "internally Jenkins jobs" with configuration described in comment above.
--- …
=> common: add Wcast-function-type warning

src/Makefile.inc, src/benchmarks/Makefile, src/common.inc, src/examples/libpmemcto/libart/Makefile, src/examples/libpmemobj/libart/Makefile, src/examples/libvmem/libart/Makefile, src/libpmem/Makefile, src/libpmem/aarch64/sources.inc, src/libpmem/x86_64/sources.inc, src/test/Makefile, src/test/Makefile.inc, src/test/pmem_deep_persist/Makefile, src/test/pmem_is_pmem_posix/Makefile, src/test/unittest/Makefile, src/tools/Makefile.inc
On my machine this patch set speeds up "make clean" from 78 seconds(!!!) to 13.5s.
Still a long way for sane times. For Valgrind, which has 3 times as much code, make clean takes 0.5s and for Linux kernel it's 3.4s. I don't think we can progress much without sane build system :(.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2970)
=> common: reduce build system overhead

doc/librpmem/librpmem.7.md
Update rpmem_persist() with missing "flags" argument
Ref: https://github.com/pmem/issues/issues/891
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2976)
=> doc: rpmem example fix

src/test/pmem_deep_persist/Makefile, src/test/rpmemd_config/Makefile
In ead799bde23fd649525203fb36bd33ca57e4a058 in pmem_deep_persist test
I replaced manually added list of pmemcommon files with a single line
that says "link-to-pmemcommon=y".
This had a side effect of braking this test on Device DAX (which I don't
regularly test on and Travis can't), because mocks rely on the ability
to compile each file with special flag that says "replace all references
to this symbol by __wrap_$(symbol)". Linking with already built
libpmemcommon instance (LIBPMEMCOMMON=y) broke that.
Instead of going back to the old and verbose method of linking use the
new clean syntax (LIBPMEMCOMMON=internal-debug) which does exactly what
is needed, using less code.
--- …
=> test: fix pmem_deep_persist/TEST2

src/libpmemobj/heap.c, src/test/obj_zones/TEST0, src/test/obj_zones/obj_zones.c, src/test/obj_zones/out0.log.match
This patch changes the heap traversal algorithm to keep searching
for memory despite lack of free blocks in the first attempted
zone.
This fixes a bug where allocations incorrectly failed with OOM
in situations where the zone 0 had no empty memory blocks but
other zones might have had them.
Reported by @vinser52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2971)
=> obj: fix invalid OOMs when zones are fully packed

src/libpmemobj/heap.c, src/test/obj_zones/TEST0, src/test/obj_zones/obj_zones.c, src/test/obj_zones/out0.log.match
This patch changes the heap traversal algorithm to keep searching
for memory despite lack of free blocks in the first attempted
zone.
This fixes a bug where allocations incorrectly failed with OOM
in situations where the zone 0 had no empty memory blocks but
other zones might have had them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2972)
=> obj: fix invalid OOMs when zones are fully packed (1.4)

src/test/pmempool_check/TEST31, src/test/pmempool_check/TEST32, src/test/pmempool_create/TEST10, src/test/pmempool_create/TEST11, src/test/pmempool_create/TEST12, src/test/pmempool_info/TEST24, src/test/pmempool_info/TEST25, src/test/pmempool_sync/TEST27, src/test/pmempool_sync/TEST28, src/test/util_badblock/TEST2, src/test/util_badblock/TEST3, src/test/util_badblock/TEST4, src/test/util_badblock/TEST5, src/test/util_badblock/TEST6, src/test/util_badblock/TEST7, src/test/util_badblock/TEST8, src/test/util_badblock/TEST9
Move 'require_kernel_module nfit_test'
to the top of the specific requirements,
because it is the most difficult to fullfill.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2980)
=> test: move require_kernel_module nfit_test

src/common/util.h, src/libpmemobj/heap_layout.h, src/libpmemobj/memblock.c, src/libpmemobj/memblock.h, src/libpmemobj/palloc.c, src/test/obj_action/pmemcheck2.log.match, src/test/obj_persist_count/out0.log.match, src/test/obj_persist_count/out1.log.match
If an allocation is at least 64 bytes and cacheline aligned we can
utilize non-temporal writes to store the object's header, this allows
us to avoid a cache miss that would have otherwise happened.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2909)
=> obj: use cl-aligned memcpy to write headers

src/test/blk_pool/TEST26.PS1
This is required as icacls does have problems with handling long paths
in the correct way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2985)
=> test: add require_short_path in blk_pool/TEST26

src/benchmarks/Makefile, src/common.inc, src/libpmemblk/Makefile, src/libpmemcto/Makefile, src/libpmemlog/Makefile, src/libpmemobj/Makefile, src/libpmempool/Makefile, src/test/Makefile.inc, src/tools/Makefile.inc
In 1.4 we made a mistake of using one flag (NDCTL_ENABLE) for
2 independent features: RAS and daxio. We set NDCTL_ENABLE to "n" just
before 1.4 release to disable RAS (it is incomplete and affects pool
layout), but didn't take into account that it alse disabled daxio.
This patch completely disables RAS (it was possible to force enable it)
and reenables daxio. NDCTL_ENABLE is now used only for daxio.
Ref: pmem/issues#892
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2994)
=> [1.4] common: reenable daxio

src/test/pmempool_check/out31.log.match, src/test/pmempool_check/out32.log.match, src/test/pmempool_sync/out27.log.match, src/test/pmempool_sync/out28.log.match
It fixes regression caused by the commit f327365a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2997)
=> test: add Last shutdown to match files

src/common.inc
Move libunwind check in common.inc out of ifeq -
FreeBSD requires libunwind package for type compatibility with Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3010)
=> common: libunwind check should not be Linux-specific

src/common/valgrind_internal.h, src/libpmem/pmem.c, src/test/unittest/unittest.sh, utils/docker/images/push-image.sh
pmem/valgrind#54 removes PCOMMIT (never shipped in any CPU, already deprecated) support from our Valgrind fork AND simplifies pmemcheck's state machine. As an unfortunate side effect pmemcheck can't distinguish pmem_flush from pmem_persist on pre-Skylake CPUs, because both translate to single CLFLUSH instruction. This means that one of our PMDK tests started to fail on pre-Skylake CPUs (pmem_valgr_simple verifies that pmemcheck finds missing pmem_drain after pmem_flush).
To fix that pmem/valgrind#54 introduces an option which tells pmemcheck to expect fence (real sfence or VALGRIND_PMC_DO_FENCE client request) after clflush.  VALGRIND_PMC_DO_FENCE is already emitted by pmem_drain (--expect-fence-after-clflush=yes).
This PR removes emission of fake PCOMMIT client request (real PCOMMIT …
=> common: stop simulating PCOMMIT for pmemcheck

src/libpmemobj/alloc_class.c, src/test/obj_fragmentation2/TEST8, src/test/obj_fragmentation2/obj_fragmentation2.c
This patch very slightly alters the allocation class selection
algorithm to take into account the theoretical worst-case run
leftover space. This improves the effective internal fragmentation
of workloads which predominantly allocate a single size from a class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2998)
=> obj: calc leftover run space for class selection

src/test/pmempool_check/out32.log.match, src/test/pmempool_info/out24.log.match, src/test/pmempool_sync/out27.log.match, src/test/pmempool_sync/out28.log.match, src/test/util_badblock/out3.log.match, src/test/util_badblock/out4.log.match
Update bad blocks match files to support
the range of the ndctl versions: 60.1-61.2,
because of the following commit:
https://github.com/pmem/ndctl/commit/7271760ce96c76c3f104c9ca40db61be8535fb62
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3043)
=> test: update match files to support ndctl v60.1-61.2

src/test/unittest/unittest.sh
Print warning when pmemcheck is required but missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3050)
=> test: fix unittest.sh

src/common/sys_util.h, src/libpmemobj/heap.c, src/libpmemobj/heap.h, src/libpmemobj/recycler.c, src/test/obj_fragmentation2/obj_fragmentation2.c, src/test/obj_pmalloc_mt/obj_pmalloc_mt.c
In my synthetic benchmarks I've observed 2x improvement in the runtime state performance when throwing lots of threads at the allocator (100++).
I'd like to ask for a diligent review of `heap_run_process_bitmap_value`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2884)
=> obj: scalability improvements around run reuse

src/test/common_badblock.sh
List the preparation log when ndctl failed to inject
or retain bad blocks.
Ref: pmem/issues#897
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3051)
=> test: list the preparation log in case of ndctl failure

doc/Makefile, doc/generated/pobj_xreserve_alloc.3, doc/generated/pobj_xreserve_new.3, doc/libpmemobj/pmemobj_action.3.md, src/include/libpmemobj/action.h, src/test/obj_action/obj_action.c
add POBJ_XRESERVE_NEW and POBJ_XRESERVE_ALLOC to action.h API in libpmemobj and update documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3022)
=> obj: extend action API

src/libpmempool/replica.c, src/test/pmempool_sync/out9.log.match
A healthy replica has been looked for implicitly
in check_poolset_uuids() so far, but it should be looked for
explicitly in replica_check_poolset_health().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3052)
=> pool: look for a healthy replica in replica_check_poolset_health

src/tools/daxio/Makefile
Fixes regression from a96763968edaf735aeb7bc7de09601767f2abf65.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3060)
=> daxio: fix ndctl detection

src/test/common_badblock.sh
Those tests require superuser privileges, so there's no point in using
sudo for anything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3071)
=> test: don't use sudo in badblock tests

src/test/unittest/unittest.sh, src/tools/pmreorder/loggingfacility.py, src/tools/pmreorder/pmreorder.py
This patch removes `-t` option from pmreorder tool.
But `-o` takes over its functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3095)
=> pmreorder: remove -t param

src/common/valgrind/pmemcheck.h, src/common/valgrind_internal.h, src/test/obj_reorder_basic/obj_reorder_basic.c, src/test/pmem_reorder_simple/pmem_reorder_simple.c
Merge after https://github.com/pmem/valgrind/pull/58 (by that time it will fail on travis)
This is part of changes related to new VALGRIND_EMIT_LOG macro.
For more details see:
https://github.com/pmem/valgrind/pull/59
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3094)
=> common: add VALGRIND_EMIT_LOG support

src/common/valgrind_internal.h
This is part of changes related to new VALGRIND_EMIT_LOG macro.
For more details see:
https://github.com/pmem/valgrind/pull/59
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3098)
=> common: pmreorder: rm engines related macros

Makefile, src/Makefile, src/common.inc, utils/SRCVERSION.ps1, utils/version.sh
On Linux we were using git commit id of the parent repository if
zip/tar.gz package was uncompressed inside of git repository (and
this is the case for Fedora).
We can't rely on GIT_VERSION for releases, because its contents depends
on state of the branch the tag was created from.
This file contains all refs that point to the tagged commit, so
immediately after 1.4.1 release it contained both "1.4.1" and
"stable-1.4", but after merging the first PR to "stable-1.4" branch it
contained only "1.4.1". This means that the checksum of the released
version changed! This is why vcpkg build from master fails now (it
contains initial checksum).
The fix is to remove the automatically filled GIT_VERSION file and add
static VERSION file before the release and revert this commit after.
Version reported …
=> common: fix reported version

utils/version.sh
"git -C" was added in git 1.8.5, which is not available in RH 7.x.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3124)
=> common: lower git version requirement in version.sh

Makefile, src/Makefile, src/common.inc, utils/SRCVERSION.ps1, utils/version.sh
There are many problems:
On Linux we were using git commit id of the parent repository if
zip/tar.gz package was uncompressed inside of git repository (and
this is the case for Fedora).
We can't rely on GIT_VERSION for releases, because its contents depends
on state of the branch the tag was created from.
This file contains all refs that point to the tagged commit, so
immediately after 1.4.1 release it contained both "1.4.1" and
"stable-1.4", but after merging the first PR to "stable-1.4" branch it
contained only "1.4.1". This means that the checksum of the released
version changed! This is why vcpkg build from master fails now (it
contains initial checksum).
The fix is to remove the automatically filled GIT_VERSION file and add
static VERSION file before the release and revert this …
=> [1.4] common: fix reported version

src/examples/libpmemobj/hashmap/hashmap_tx.c
Using var's content after freeing it in the transaction might
cause trouble.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3129)
=> examples: fix use-after-free in hashmap_tx

src/examples/libpmemobj/tree_map/rtree_map.c
These ranges seem modified in the transaction but not added
to undo log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3126)
=> examples: fix missing undo logging in rtree

src/examples/libpmemcto/lifesaver/lifesaver.c, src/examples/libpmemcto/lifesaver/lifesaver.def
I deleted unreferenced local variable and updated the name of an output file in lifesaver.def
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3148)
=> examples: fix warnings in lifesaver

src/test/unittest/unittest.ps1
In obj_extend/TEST8.PS1 we receive a warning:
An item with the specified name C:\temp\...\testdir10 already exists.
but the test passed.
Ref: pmem/pmdk#3130
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3147)
=> test: fix create_poolset

src/libpmemobj/container_seglists.c, src/test/obj_ctl_alloc_class/obj_ctl_alloc_class.c, src/test/obj_heap/obj_heap.c
Currently allocation classes smaller than ~128 bytes make
no sense because they leave a lot of unused memory. This will
soon change, and so, the run container, which currently uses an
intrusive data structure for memory blocks, needs to be changed
so that it can accomodate allocation classes as small as 1 byte.
This means that container can no longer embed internal metadata
in free memory blocks, as they can simply be too small.
This patch replaces the currently used STAILQ with a simple
array-based queue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3087)
=> obj: use non-intrusive container for runs

src/Makefile.inc, src/common.inc, src/test/Makefile.inc, src/test/obj_ctl_alignment/obj_ctl_alignment.c, src/test/obj_direct_volatile/obj_direct_volatile.c, src/test/obj_fragmentation2/obj_fragmentation2.c, src/test/obj_persist_count/obj_persist_count.c, src/test/obj_pmalloc_mt/obj_pmalloc_mt.c, src/test/obj_tx_lock/obj_tx_lock.c, src/test/obj_tx_locks/obj_tx_locks.c, src/test/pmem_is_pmem_posix/pmem_is_pmem_posix.c, src/test/rpmem_basic/rpmem_basic.c, src/test/rpmem_fip/rpmem_fip_test.c, src/test/rpmemd_config/rpmemd_config_test.c, src/test/rpmemd_util/rpmemd_util_test.c, src/test/unittest/Makefile, src/test/util_ctl/util_ctl.c, src/test/util_poolset/util_poolset.c, src/tools/Makefile.inc, utils/check_license/Makefile
Those warnings are enabled in our libraries but not in tests.
By enabling this, we can detect simple errors in our tests.
Enabled:
-Wunreachable-code-return
-Wmissing-variable-declarations
-Wfloat-equal
-Wcast-function-type
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3089)
=> test: enable extra warnings in tests

src/tools/rpmemd/rpmemd.c, src/tools/rpmemd/rpmemd_log.h
The tab character is not allowed in rpmemd log,
because it is not well handled by syslog.
RPMEMD_LOG_INDENT has to be used instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3177)
=> rpmem: do not use tab character in rpmemd log

src/test/ctl_prefault/TEST0, src/test/ctl_prefault/TEST1, src/test/ctl_prefault/TEST2, src/test/tools/Makefile, src/test/tools/fallocate_detect/.gitignore, src/test/tools/fallocate_detect/Makefile, src/test/tools/fallocate_detect/fallocate_detect.c, src/test/unittest/unittest.sh
Ref: pmem/issues#901
In filesystems which do not have fallocate support posix_fallocate is emulated by
preforming multiple writes, which cause page faults on every create/open.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3171)
=> test: require fallocate support for ctl_prefault

src/common/vecq.h, src/libpmemobj/list.c, src/libpmemobj/list.h, src/libpmemobj/memops.c, src/libpmemobj/memops.h, src/libpmemobj/obj.c, src/libpmemobj/obj.h, src/libpmemobj/pmalloc.c, src/libpmemobj/pmalloc.h, src/libpmemobj/redo.c, src/libpmemobj/redo.h, src/test/obj_layout/obj_layout.c, src/test/obj_list/obj_list_mocks.c, src/test/obj_memops/obj_memops.c, src/test/obj_pmalloc_basic/obj_pmalloc_basic.c, src/test/tools/pmemspoil/spoil.c, src/tools/pmempool/info_obj.c
This patch changes the redo log algorithm to use a variably-sized
byte buffer with entries (similarly to how it's done for undo logs)
instead of having a fixed number of entries per redo log. While
the new code is more flexible and allows for logs larger than
8 bytes, it also has the downside of being more complicated to
use - we no longer have access to array of entries.
One of the consequences of this change is the removal of 'nentries'
counter in the redo log metadata. From now on, the stopping criteria
for iterating over entries is whether or not the next entry offset
is zero. To make this work, when storing/creating logs the algorithm
writes zeroes to a cacheline ahead of the actual log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> obj: change redo logs to offset-based entries

src/libpmempool/pool.c
with extra logging. Investigating ASSERT failure was impossbile
due to missing informations about dmapped and smapped.
Ref: pmem/issues#517
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3190)
=> pool: replace assert by conditional expression

src/windows/getopt/getopt.c
getopt was returning "option '%s' is ambiguous" when one long option
is a substring of the second.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3208)
=> [1.4] common: win: fix getopt returning "option is ambiguous"

src/common.inc, src/common/os_posix.c, src/tools/pmempool/info.c
These three patches allow pmdk to be built with the musl libc library (instead of glibc).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3210)
=> Allow pmdk to be built with musl

src/common/shutdown_state.c, src/libpmempool/replica.c
Ref: pmem/pmdk#3175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3207)
=> pool: adding error handling of shutdown_state_add_part (fix)

src/test/common_badblock.sh
It fixes the following issue: https://github.com/pmem/pmdk/pull/3057#issuecomment-424260256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3221)
=> test: fix path of resources of the nfit_test module

src/common/mmap.c
Check for misaligned address in util_unmap() (see
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=169608)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3205)
=> common: Workaround for FreeBSD munmap bug 169608

src/libpmem/libpmem_main.c, src/libvmem/libvmem_main.c, src/windows/include/win_mmap.h, src/windows/win_mmap.c
and call it from DLL_PROCESS_DETACH, so that it is called
before out_fini(). This ensures that logs from destructor
goes through out_common
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3226)
=> common: fix windows mmap destructor

src/test/unittest/unittest.sh
If pmemcheck was not installed at all get_pmemcheck_version() was
returning error string which wasn't handled correctly by
require_pmemcheck_version_ge / require_pmemcheck_version_lt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3238)
=> test: fix pmemcheck version detection

src/test/obj_root/TEST1, src/test/obj_root/TEST1.PS1, src/test/obj_root/obj_root.c
This test causes heavy swapping.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3236)
=> test: extract heavy part of obj_root test to separate "long" test

src/libpmemobj/lane.c, src/libpmemobj/ulog.c, src/libpmemobj/ulog.h, src/test/obj_lane/obj_lane.c, src/test/obj_persist_count/out0.log.match, src/test/obj_persist_count/out1.log.match
The ulog_construct function, which is called three times
for every lane at pmemobj_create, was severly impacting
test times due to prolonged lane initialization.
This patch reduces the number of persists, which
should improve overall pmemobj_create performance on very
slow storage and with remote replication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3239)
=>  obj: reduce the number flushes at create

src/libpmemobj/container_seglists.c, src/libpmemobj/heap.c, src/libpmemobj/memblock.c, src/libpmemobj/memblock.h, src/test/obj_ctl_alloc_class/TEST0, src/test/obj_ctl_alloc_class/TEST0.PS1, src/test/obj_ctl_alloc_class/obj_ctl_alloc_class.c
Up until recently the largest possible block offset inside of a run
was ~2500. This changed with the introduction of the flexible bitmap
and it allowed for creation of allocation classes with extremely
large "units_per_block" parameter. The new maximum is
max alloc size divided by the unit size. This new maximum exceeded
the uint16_t variable that stored this information in the runtime
state causing ASSERTs in debug builds and double allocation in
release ones. Instead of disallowing large units_per_block for certain
parameters, the runtime state variable has been changed to uint32_t
which is more than enough to store any possible units_per_block value.
Ref: pmem/issues#933
--- …
=> obj: bump block offset in memory block to 4 bytes

src/test/pmempool_sync_remote/TEST22, src/test/pmempool_sync_remote/TEST23, src/test/pmempool_sync_remote/TEST24, src/test/pmempool_sync_remote/TEST25, src/test/pmempool_sync_remote/TEST26, src/test/pmempool_sync_remote/TEST27, src/test/pmempool_sync_remote/TEST28, src/test/pmempool_sync_remote/TEST29, src/test/pmempool_sync_remote/TEST30, src/test/pmempool_sync_remote/TEST31, src/test/pmempool_sync_remote/TEST32, src/test/pmempool_sync_remote/TEST33, src/test/pmempool_sync_remote/TEST34, src/test/pmempool_sync_remote/TEST35, src/test/unittest/unittest.sh
- run ldd with env
- do not truncate parts on non existing paths
- do not use $DIR as local directory on remote nodes
Ref: pmem/pmdk#2957
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3244)
=> test: pmempool_sync_remotes fixes

src/test/daxio/TEST1, src/test/daxio/out1.log.match, src/tools/daxio/daxio.c
Behaviour of daxio was changed for cases when seek/skip + length
is beyond device size. Now, it is similiar to behaviour of dd.
Ref: pmem/issues#931
Failing test from the issue was caused by lack of adjusting len in some cases.
Tests without valgrind didn't detect that because /dev/null was used as an output device
and `write()`, which would normally fail, succeeded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3237)
=> daxio: refactor checking and adjusting length

doc/libpmemblk/pmemblk_ctl_get.3.md, doc/pmempool/pmempool-sync.1.md
use single "-" in NAME section (-- becomes \[en] in manpages, breaks
NAME section parsing)
+
too long word cause linitan warning manpage-has-errors-from-man "cannot
adjust line"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3247)
=> doc: small fixes in manpages

src/test/unittest/unittest.sh
It seems output is displaying last 20 lines, not first ones. In windows framework there are also last lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3249)
=> test: Fixing output info of unittest.sh

utils/build-dpkg.sh, utils/build-rpm.sh, utils/docker/build-local.sh, utils/docker/build-travis.sh, utils/pmdk.spec.in
Currently only one job on Travis actually tests ndctl code paths. While fixing this I noticed other severe bugs related to building packages. See each commit description for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3235)
=> common: fix ndctl integration (Travis & rpms/debs)

src/libpmemobj/obj.h, src/test/magic/out0.log.match, src/test/obj_rpmem_basic_integration/node_0_rpmemd20.log.match
Due to extensive changes to the lane layout we need to bump up
the layout version, making the old lane recovery incompatible.
Old pools will have to be converted using `pmempool convert`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3251)
=> obj: bump major layout version to 5

src/tools/daxio/daxio.c
Running daxio with not-existent input/otput file caused
program failure without any message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3258)
=> daxio: fix printing error when open fails

src/libpmempool/sync.c
Fix skipping all bad blocks from bbv_all with offsets
less than the offset of the current bb_old.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3263)
=> pool: fix sync_badblocks_assign_healthy_replica()

src/libpmemobj/memops.c
Reading data that was just written with non-temporal instructions
isn't the best idea ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3262)
=> obj: don't read just written ulog entry

src/common/os_dimm_ndctl.c
... because there are two 'bb' variables in the same scope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3267)
=> common: change name of a struct bad_block variable

src/test/pmempool_check/TEST1, src/test/pmempool_check/TEST9, src/test/pmempool_check/TEST9.PS1, src/test/pmempool_check/out9.log.match
Do not set the CHECK_BAD_BLOCKS compat feature on
in two  pmempool_check tests.
This patch fixes regression introduced by 3db00327.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3277)
=> test: fix two pmempool_check tests

src/libpmempool/check_util.c, src/libpmempool/libpmempool.c, src/libpmempool/pool.c
This patch fixes regression introduced by 3db00327.
The libpmempool_bttdev tests run on pmem FS fail without this fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3283)
=> pool: zero all features in pmempool_check_init()

src/test/pmempool_sync/TEST27, src/test/pmempool_sync/TEST28, src/test/pmempool_sync/TEST30, src/test/pmempool_sync/TEST31, src/test/pmempool_sync/TEST32, src/test/pmempool_sync/TEST33, src/test/pmempool_sync/TEST34, src/test/pmempool_sync/TEST35, src/test/pmempool_sync/TEST36, src/test/pmempool_sync/TEST37, src/test/pmempool_sync/TEST38, src/test/pmempool_sync/TEST39, src/test/pmempool_sync/TEST40, src/test/pmempool_sync/TEST41, src/test/pmempool_sync/TEST42, src/test/pmempool_sync/TEST43, src/test/pmempool_sync/TEST44, src/test/pmempool_sync/TEST45, src/test/pmempool_sync/TEST46, src/test/pmempool_sync/TEST47, src/test/pmempool_sync/TEST48, src/test/pmempool_sync/TEST49, src/test/pmempool_sync/TEST50, src/test/pmempool_sync/TEST51, src/test/pmempool_sync/TEST52, src/test/pmempool_sync/TEST53
The tests using the 'obj_verify' tool on a non-pmem filesystem
should have the PMEM_IS_PMEM_FORCE variable set,
because they can time-out otherwise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3287)
=> test: set PMEM_IS_PMEM_FORCE in tests using obj_verify tool

src/test/testconfig.sh.example, src/test/unittest/unittest.sh, utils/docker/configure-tests.sh
Tests using the 'sudo' command can be potentially very harmful,
so they have to be enabled deliberately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3289)
=> test: tests using sudo have to be enabled deliberately

doc/libpmempool/pmempool_feature_query.3.md, doc/pmempool/pmempool-feature.1.md
- poolsets with remote replicas are note supported
- op is not fail safe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3315)
=> doc: (lib)pmempool feature improvements

src/test/unittest/unittest.ps1, src/test/unittest/unittest.sh
Adding precise info on how much free space is required to msg in require_free_space function, and additionally expanding msg in require_nfit_tests_enabled function to contain entry for testconfig.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3319)
=> test: expand msg info from require_free_space and require_nfit_tests_enabled

src/test/pmempool_sync/TEST27, src/test/pmempool_sync/out27.log.match
1) turn checking bad blocks on before injecting them
2) inject bad blocks at offset 8 to not zero features in the header
3) add expect_bad_blocks() before running pmempool-sync to make sure
that bad blocks really exist
It fixes failing test on Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3318)
=>  test: fix pmempool_sync/TEST27 test

src/test/testconfig.sh.example, src/test/util_badblock/TEST1, src/tools/daxio/daxio.c
Add the option '-b/--clear-bad-blocks=yes/no' to be able to turn clearing bad blocks off in a DAX device
(because it may require the super user privileges).
This patch fixes failing daxio unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3304)
=> daxio: add option to turn clearing bad blocks off

src/test/pmem_deep_persist/pmem_deep_persist.c, src/test/testconfig.sh.example
Ref: pmem/issues#963
We need to write to deep_flush file, so we have to check write access.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3323)
=> test: fix pmem_deep_flush mock

src/test/unittest/unittest.sh
expect_normal_exit should not be used prior to run setup.
Setting LD_LIBRARY_PATH is sufficient.
Ref: pmem/pmdk#3244
Ref: pmem/issues#952
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3337)
=> test: run ldd with env

doc/libpmemobj/pmemobj_ctl_get.3.md, src/libpmemobj/pmalloc.c, src/test/obj_ctl_alloc_class/obj_ctl_alloc_class.c
For custom allocation classes the units_per_block variable is
adjusted to minimize fragmentation and most likely differs from
the user-provided value. This patch will make it so that the actual
value is written back to the allocation class desc structure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3340)
=> obj: modify units_per_block for new alloc classes

src/test/pmempool_check/TEST1, src/test/pmempool_check/TEST1.PS1, src/test/pmempool_check/TEST9, src/test/pmempool_check/TEST9.PS1, src/test/pmempool_check/common.sh, src/test/pmempool_check/out9.log.match
Do not enable the SHUTDOWN_STATE incompat feature in two pmempool_check tests: TEST1 and TEST9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3336)
=> test: do not enable the SHUTDOWN_STATE incompat feature

src/test/pmempool_sync_remote/TEST32, src/test/pmempool_sync_remote/TEST33, src/test/pmempool_sync_remote/TEST34, src/test/pmempool_sync_remote/TEST35
It fixes a regression:
- introduced by the commit: fbf58ac4
- than hidden by the commit: 3934541f
- and revealed again by the commit: ef225bf8
These four tests fail on Jenkins now. This patch fixes them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3353)
=> test: enable CHECK_BAD_BLOCKS feature in four pmempool_sync_remote tests

src/test/libpmempool_feature/common.PS1
Log files from libraries under Release are not created so it is required to check its existance prior to grep its content. Otherwise output is polluted with Exceptions.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3348)
=> test: check whether log exists prior to cat it

src/test/obj_fragmentation2/TEST8, src/test/obj_fragmentation2/TEST8.PS1
This test has the tendency to exceed our timeout threshold for medium
tests, so let's just make into a long.
It would be difficult to change the implementation, since it's
replicates a workload described in a research paper.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3356)
=> test: change obj_fragmentation2 TEST8 into long

src/libpmempool/replica.c
Checksums and signatures of remote replicas are checked
during opening them on the remote side by the rpmem deamon.
The local version of remote headers does not contain such data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3366)
=> pool: fix check_checksums_and_signatures()

src/benchmarks/pmembench.cpp
Turning on thread_affinity without providing affinity_list results in nonexisting affinity_list.
This patch handles nonexisting affinity_list case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3369)
=> benchmark: handle nonexisting affinity_list

src/test/obj_persist_count/TEST0, src/test/obj_persist_count/TEST1, src/test/pmempool_check/common.sh
- remote unnecesary ```require_sds```
- enable SDS by ctl in pmempool_check unittests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3380)
=> test: small SDS cleanups

src/benchmarks/pmembench_obj_gen.cfg, src/benchmarks/pmemobj_gen.cpp
They run afoul “recent” (Nov 2016) allocator optimizations that are not so optimal wrt taking randomly sized pieces out of a tiny pool.  As it's not what we benchmark here, just drop the randomization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3379)
=> bench: fix two obj_direct scenarios crashing

utils/style_check.sh
Without this, it says: ``SKIP: requires clang-format version 3.8`` even if clang-format-3.8 is installed, on distributions where the default version of Clang is other than 3.8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3398)
=> common: let style_check.sh find clang-format-3.8

src/test/unittest/unittest.sh, utils/docker/run-build-package.sh, utils/docker/run-build.sh, utils/docker/run-coverage.sh, utils/docker/run-coverity.sh
I have TEST_PROVIDERS=sockets set in testconfig.sh and when I ran obj_rpmem_basic_integration/TEST0 I got:
SETUP (medium/pmem/debug/sockets/GPSPM)
SKIP libfabric not compiled with verbs provider
SETUP (medium/pmem/debug/sockets/APM)
SKIP libfabric not compiled with verbs provider
This patch fixes this issue and removes the RPMEM_DISABLE_LIBIBVERBS variable, because it is not needed any more since this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3399)
=> test: do not require the verbs provider when it is not tested

src/common.inc
Distributions use names like "amd64" or "arm64" that are distinct from GNU triplets.  People tend to use those instead of what our makefiles expect.  Let's accept them.
Ref: pmem/issues#971
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3401)
=> common: accept ARCH=amd64

src/test/Makefile, src/test/Makefile.inc, src/test/tools/anonymous_mmap/.gitignore, src/test/tools/anonymous_mmap/Makefile, src/test/tools/anonymous_mmap/README, src/test/tools/anonymous_mmap/anonymous_mmap.c, src/test/tools/anonymous_mmap/check_max_mmap.sh, src/test/unittest/unittest.sh
When the client application runs against the Valgrind, the Valgrind intercepts the mmap call made by the client. For big length requests (i.e. in tests run on NVDIMMs) Valgrind may fail and it becomes a limitation which must be handled by Valgrind maintainers in the future.
This commit provides a simple way to detect possible valgrind mmap issues and skip uncertain tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3395)
=> test: add tool for checking mmap under valgrind

src/benchmarks/pmemobj_gen.cpp
As obj_direct calls are very fast compared to the test harness overhead, the results weren't visible in the noise — thus, we need to wrap them in a loop inside rather than outside the harness.  We also need to avoid the cache.
Here's also a simple Perl tool to compare the results of two benchmarks, giving a coloured overview.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3394)
=> bench: improve obj_direct tests

src/test/rpmemd_db/TEST0, src/test/rpmemd_db/TEST1
Fact 1) rpmemd_db test creates pools with randomly generated headers
filling them using characters from a-z range.
Fact 2) librpmem sometimes prints a pool signature.
Fact 3) After the test binary finishes, test scripts look for some
predefined messages in rpmem log file. One of those messages is about
"flock" system call failure.
If you connect those facts it's clear it's possible that the randomly
generated header can contain the word "flock" in pool signature,
which will mess up log matching.
It seems quite impossible, but this is exactly what happened on
Travis recently.
rpmem0.log contained:
<rpmemd_db>: <3> [set.c:2551 util_header_check_remote] valid header, signature "fnwflock"
Fix this by modifying the grep expression to never hit anything in
the randomly generated header.
--- …
=> test: fix rpmemd_db test

utils/SRCVERSION.ps1, utils/pkg-common.sh, utils/version.sh
Version with two dashes (like 1.5-19-gb8f78a329) confuses rpmbuild in
recent Fedoras, which makes it generate uninstallable -devel packages
(libpmem-devel doesn't have Provides: pkgconfig(libpmem) tag, which
doesn't satisfy Requires: pkgconfig(libpmem) in
libpmem[obj|blk|log]-devel).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3431)
=> common: use better versioning scheme for git snapshots

src/libpmemobj/obj.c, src/test/obj_pool/TEST34, src/test/obj_pool/TEST34.PS1, src/test/obj_pool/out34.log.match
If the mapped size of the pool was within 2 megabytes of a multiple
of max zone size, the heap checking function was reading unitialized
data, leading to a segfault. The size passed to heap_check must be
the actual heap size with which the heap was originally initialized.
Ref: pmem/issues#975
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3434)
=> obj: fix pmemobj_check for pools with some sizes (1.5)

src/libpmemobj/obj.c
If the mapped size of the pool was within 2 megabytes of a multiple
of max zone size, the heap checking function was reading unitialized
data, leading to a segfault. The size passed to heap_check must be
the actual heap size with which the heap was originally initialized.
Ref: pmem/issues#975
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3433)
=> obj: fix pmemobj_check for pools with some sizes (1.4)

Makefile, src/Makefile, src/common.inc, src/test/Makefile
If libfabric is not installed:
```$ make check-remote```
returns an error and:
```$ make check```
just skips remote tests.
Ref: pmem/issues#976
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3442)
=> common: do not run remote tests if libfabric is not installed

src/test/RUNTESTLIB.PS1
After #3099 pmemdetect on windows was silently failing due to
missing access to libpmem which was moved to a different directory.
To fix this issue we have to append lib directory to the PATH variable.
This change moves pmemdetect related code to a separate
thread (separate shell), as we should not modify PATH
variable in the user shell.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3444)
=> test: fix failing pmemdetect on windows

src/test/util_badblock/TEST7, src/test/util_badblock/out7.log.match
This is a workaround for a Linux kernel bug (at least v4.16):
fixed blocks have to be written to get bad blocks cleared.
This patch fixes util_badblock/TEST7 failing sporadically on Jenkins.
Ref: pmem/issues#980
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3449)
=> test: fix util_badblock/TEST7

src/test/unittest/unittest.ps1
Fixes require_free_space failure:
obj_root/TEST0: SETUP (check\pmem\debug)
Cannot convert value "19327352832966367641.6" to type "System.Int64".
Error: "Input string was not in a correct format."
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastFromStringToInteger
+ PSComputerName        : localhost
obj_root/TEST0: PASS			[00.957 s]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3450)
=> test: fix convert_to_bytes to actually return a number

doc/libpmemlog/pmemlog_ctl_get.3.md
Turns out, `-` vs `--` does make a difference, in this case it's a syntax error for man page indexer which breaks references from _UW aliases.
For reference, the common three kinds of dashes are:
* `-` (hyphen)
* `–` (en dash)
* `—` (em dash)
Unicode has a few tens more...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3470)
=> doc: fix lexgrog parsing (man-db index)

doc/pmem_ctl/pmem_ctl.5.md
Turns out that, after a recent fix, all manpages which get installed were correct.  Spot two problems in the preceding sentence. 😏
Because of the way the bot which updates `doc/generated/` works, the test case for man page errors has to go in a separate pull request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3473)
=> doc: another hyphen update

src/include/libpmemobj.h, src/include/libpmemobj/base.h
libpmemobj.h is supposed to include other files only...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3474)
=> obj: move flags definition to relevant header file

src/test/tools/cmpmap/cmpmap.c
This issue affects tests on devdax (detected on qb)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3478)
=> test: fix cmpmap ret val

src/test/ld.supp
This patch extends suppression for memcheck leak in ld.so,
because of differences between libc 2.26 and 2.27 stack traces.
General issue is described here: pmem/issues#858
**2.27**
==7758== HEAP SUMMARY:
==7758==     in use at exit: 155 bytes in 5 blocks
==7758==   total heap usage: 938 allocs, 933 frees, 797,593 bytes allocated
==7758== 
==7758== 18 bytes in 1 blocks are definitely lost in loss record 1 of 5
==7758==    at 0x4C2EDA7: malloc (vg_replace_malloc.c:299)
==7758==    by 0x6306C49: strdup (in /usr/lib64/libc-2.27.so)
==7758==    by 0x9532528: ???
==7758==    by 0x400F519: call_init.part.0 (in /usr/lib64/ld-2.27.so)
==7758==    by 0x400F615: _dl_init (in /usr/lib64/ld-2.27.so)
==7758==    by 0x401379E: dl_open_worker (in /usr/lib64/ld-2.27.so)
==7758==    by 0x63B49CE: …
=> common: extend suppression for memcheck leak

doc/Makefile, doc/generated/pmemobj_f_mem_nodrain.3, doc/generated/pmemobj_f_mem_noflush.3, doc/generated/pmemobj_f_mem_nontemporal.3, doc/generated/pmemobj_f_mem_temporal.3, doc/generated/pmemobj_f_mem_wb.3, doc/generated/pmemobj_f_mem_wc.3, doc/generated/pmemobj_f_relaxed.3
Ref: pmem/issues#992
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3489)
=> doc: add missing aliases to pmemobj_f_mem macros

utils/docker/images/Dockerfile.fedora-28
I would like to use rsync in auto doc file to have cp with more options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3487)
=> common: add rsync to Fedora28 docker file

src/tools/pmempool/common.c, src/tools/pmempool/common.h
Just a simplification for one too many levels of indirection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3496)
=> pool: get rid of a helper function

src/common/vecq.h, src/test/util_vecq/util_vecq.c
The vector based queue didn't properly dequeue elements whenever the
underlying buffer was resized in a way that resulted in the logical
queue being split into two halves.
To address this problem, these two halves need to be merged back together
after a realloc, and the front/back variables need to be adjusted to match.
This thankfully didn't affect the allocator, because the seglists container
doesn't grow past the initial size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3492)
=> common: fix vecq resize for not front-append scenarios

utils/check_license/check-license.c
Cherry-pick a couple of commits applied to vmemcache.  They fix a couple of warnings with new gcc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3502)
=> common: check-license warnings

src/include/libpmemobj/action_base.h
This can be fatal with -Werror or in otherwise warning-averse projects.
Ref: pmem/issues#994
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3501)
=> obj: fix a clang warning on our public headers

utils/build-dpkg.sh
The dependencies on generated daxio package use non-existent "libndctl" and "libdaxctl"; the real packages have soversion numbers attached.  There's no need to write explicit deps: packaged shared libraries already do the right thing.
This is a fixed version of #3498 by kcleung.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3518)
=> common: dpkg: drop bogus hardcoded library dependencies

utils/md2man.sh
It's a cross-distro effort to make the same package with same toolchain versions compile to bit-by-bit identical code; various distros follow it to various degrees, with at least Debian [nearly complete](https://isdebianreproducibleyet.com/), and if your package doesn't build reproducibly, you get shouted at.  I don't like being shouted at.
For PMDK, the only problem was date in generated man pages.
As a packaging fix, I'm submitting this for 1.5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3504)
=> doc: obey $SOURCE_DATE_EPOCH

src/include/libpmemobj/types.h
Like MSVC, it hates a GCC extension we use.
Not sure what ICC wants, thus I'm leaving the GCC path by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3523)
=> obj: fix clang++ breakage with TOID_ASSIGN

doc/libpmemblk/pmemblk_ctl_get.3.md, doc/libpmemlog/pmemlog_ctl_get.3.md, doc/libpmemobj/pmemobj_ctl_get.3.md, doc/pmem_ctl/pmem_ctl.5.md
This patch mostly clarifies the behavior of ctl functions in presence
of error conditions, but also removes outdated entry points
descriptions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3526)
=> doc: ctl man pages cleanup

src/common/os_dimm_ndctl.c, src/libpmem/aarch64/init.c
A couple of arm64 fixes; they're not enough to pass the testsuite, but it's still good to have them in case someone bothers to look at this again.
The PAGE_SIZE commit fixes compilation with kernel uapi headers 4.16..4.19 (Debian buster will probably release with linux-libc-dev 4.19).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3525)
=> common: incomplete arm64 fixes

src/benchmarks/benchmark_worker.cpp, src/libpmemblk/blk.c, src/libpmemlog/log.c, src/libpmemobj/critnib.c, src/libpmemobj/recycler.c, src/test/blk_recovery/TEST0, src/test/blk_recovery/TEST0.PS1, src/test/blk_recovery/blk_recovery.c, src/test/blk_recovery/check0.log.match, src/test/blk_recovery/out0.log.match, src/test/obj_ctl_arenas/obj_ctl_arenas.c, src/test/obj_direct/obj_direct.c, src/test/obj_oid_thread/obj_oid_thread.c, src/test/obj_tx_mt/obj_tx_mt.c
os variants should be used only for implementation of user locks (pmemobj_mutex_lock & co).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3532)
=> common: use util variants of locking APIs

src/libpmemobj/tx.c, src/test/obj_tx_lock/obj_tx_lock.c
Locking failure should NOT result in adding the lock to transaction!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3536)
=> obj: fix pmemobj_tx_lock error handling

src/libpmemobj/tx.c, src/test/obj_tx_lock/obj_tx_lock.c
Locking failure should NOT result in adding the lock to transaction!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3538)
=> [1.4] obj: fix pmemobj_tx_lock error handling

src/libpmemobj/obj.c
In an effort to make pool management threadsafe, pools_ht and pool_tree
global variables need to be initialized only one time. To accomplish
that, we use CAS to make sure that only one thread initializes these
variables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3539)
=> obj: make obj_pool_init threadsafe

doc/libpmem/pmem_is_pmem.3.md, src/libpmemobj/stats.c, src/libpmemobj/tx.c, src/test/obj_ctl_stats/TEST1, src/test/obj_ctl_stats/obj_ctl_stats.c, src/test/obj_tx_lock/obj_tx_lock.c, utils/docker/build-local.sh, utils/docker/build-travis.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3548)
=> Merge back changes from stable-1.5

src/benchmarks/pmembench.cpp
Benchmark name and brief are used unconditionally in the pmembench
codebase. It is better to assert they are not null during benchmark
registration to avoid tracking unclear SIGSEGV later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3551)
=> benchmark: assert name and brief are defined

src/test/rpmemd_config/TEST2, src/test/rpmemd_config/stdout2.log.match
Quoting rules changed.
There's one other failing test, and many others that _should_ fail but don't.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3553)
=> test: fix one of failing bash-5 tests

src/test/libpmempool_api/TEST9, src/test/magic/TEST0, src/test/pmempool_info/TEST26, src/test/rpmemd_config/TEST4, src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3554)
=> test: various fixes (mostly bash 5 related)

src/test/drd-log.supp, src/test/helgrind-log.supp
helgrind and drd fail a lot when faced with glibc 2.28.  This is not our bug — a threaded "hello world" fails the same, but as long as old versions of valgrind are around, we can keep hitting this.  In fact, this pair of suppressions already **were** in our tree, but glibc's implementation minutely changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3556)
=> test: valgrind suppressions for glibc 2.28

src/test/unittest/unittest.ps1
In b09db041cbc38c31ae897084136673d73c0d0bfb UNITTEST_NO_ABORT_MSG
was renamed, but not all uses were updated.
Ref: pmem/issues#983
Ref: pmem/issues#1001
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3576)
=> test: (win) fix timeouts from abort window popups

src/libpmemobj/critnib.c, src/test/obj_critnib/obj_critnib.c
Removing a non-existent key is supposed to work, and do nothing.  A segfault is no nothing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3572)
=> obj: fix a crash in critnib

src/test/RUNTESTS
The testsuite currently gets to:
```
./RUNTESTS: line 247: S.py: syntax error: invalid arithmetic operator (error token is ".py")
```
then aborts, returning a **successful** result.
The false success is another issue, but restricting names to numbers only will do the trick for now.
Obsoletes  #3570.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3581)
=> test: unbreak the testsuite after TESTS.py

src/common/os_posix.c
Split fallocate into 1GB chunks, restarting on ENOMEM and EINTR.  If we get either repeatedly, reduce the chunk size, failing if that doesn't help.
Ref: pmem/issues#168, pmem/issues#1018
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3580)
=> common: fallocate: workaround a tmpfs bug, restart on signals

src/test/Makefile.inc
./RUNTESTS: line 249: S.py: syntax error: invalid arithmetic operator (error token is ".py")
Ref: #3581
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3593)
=> test: fix another failure from merging of Python tests

src/libpmemobj/heap.c
It fixes infinity loop in err path.
(detected on qb + clang)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3598)
=> obj: fix loop comparison issue

src/common/util.h
Replace wrong 'memory_order_seqcst'
with correct 'memory_order_seq_cst'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3559)
=> util: fix util_atomic_load/store_explicit32/64

src/common/set.c, src/test/Makefile, src/test/obj_check_remote/.gitignore, src/test/obj_check_remote/Makefile, src/test/obj_check_remote/TEST0, src/test/obj_check_remote/config.sh, src/test/obj_check_remote/obj_check_remote.c
pmemobj_check fix for remote replicas
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3585)
=> common: unlink remote replicas from poolset when COW is enabled

src/libpmemobj/heap.c
By the time tls_destructor was called arena was already destroyed
fixes: d2fc16caed3c7fe2f188ab1bf44687c939b7c7e1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3603)
=> obj: fix use after free in heap_cleanup

src/examples/pmreorder/pmreorder_list.c
Found by Klockwork.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3625)
=> examples: fix incorrect length of pmem_persist in pmreorder_list

.travis.yml, src/test/scope/out1.log.match, src/test/scope/out2.log.match, src/test/scope/out3.log.match, src/test/scope/out4.log.match, src/test/scope/out6.log.match
In COVERAGE=1 job we ignore test failures, because coverage tracking
in gcc/clang is a bit buggy (memcheck complains).
This means that failures from fault injection are not detected.
Solve it by adding fault injection to 2 jobs which do not measure coverage.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3623)
=> common: build with fault injection in two more configs

utils/docker/pull-or-rebuild-image.sh
in pull-or-rebuild-image.sh to contain only
commits from a PR.
Ref: travis-ci/travis-ci/issues/4596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3641)
=> common: Adjust TRAVIS_COMMIT_RANGE variable

src/common/valgrind_internal.h, src/libpmemobj/critnib.c, src/test/obj_critnib_mt/TEST2
The helgrind warnings are correct: there are races; they just have clearly defined semantics that don't affect correctness — that's common for lock-free algorithms.  The rule is: a read can return any value that was current at any time between the read call started and finished.
So we need annotations.  Alas, I can't seem to find a way to set up ignoring races at allocation time — which should work according to my understanding of helgrind — reported errors don't disappear unless I repeat the annotation just prior to accessing the data.
But, with 1.6 release coming, there's no time.  Thus, here's a version that makes helgrind happy, at the cost of performance.  We can revisit this later.
--- …
=> obj: helgrind annotations for critnib

src/libpmemobj/critnib.c
Fixes drd very rarely reporting a race in `obj_critnib_mt/TEST2`.
Also avoids the performance hit of my previous fix here (`obj_critnib_mt/TEST1`).
Ref: pmem/issues#1005, pmem/issues#1040
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3656)
=> obj: do foogrind annotations at alloc time

src/libpmemobj/lane.c, src/test/obj_recovery/TEST9, src/test/obj_recovery/obj_recovery.c
The 'operation_context' structure was being created twice, once as part
of lane initialization, and once as part of the recovery operation.
The first context is used for all operations, whereas the second context
lives only for the duration of the undo log recovery.
The problem was that the recovery process can change the persistent
state in such a way that the context runtime information becomes stale.
This is perfectly fine, and it's handled for the operation that
does the recovery - but at the same time, this makes the data of the
lane context invalid.
This bug was triggering ASSERTs in debug builds and might have led to
NULL dereference on release builds. Fortunately the crash happens
after recovery has been finished and simply restarting the application
gets rid of the problem.
The …
=> obj: fix runtime state corruption after undo recovery

src/test/pmempool_create/TEST14, src/test/pmempool_create/TEST14.PS1, src/test/pmempool_create/err14.log.match, src/test/pmempool_create/out14.log.match, src/tools/pmempool/create.c
Pool layout was not set at the moment of printing when pool creation was called with verbose option enabled.
Ref. pmem/issues#1026
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3635)
=> pool: fix obj pool layout printing by pmempool create 

src/test/libpmempool_bttdev/TEST11.PS1, src/test/libpmempool_bttdev/TEST3.PS1, src/test/libpmempool_bttdev/TEST4.PS1, src/test/libpmempool_bttdev/TEST5.PS1, src/test/libpmempool_bttdev/TEST6.PS1, src/test/unittest/unittest.ps1
When allocating large pools on the windows we use up a lot of resources,
with automatic page file size management we eliminate the risk
of exceeding the available resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3687)
=> test: fix libpmempool_bttdev windows test

src/Makefile, src/Makefile.inc, src/common.inc, utils/libpmemblk.pc.in, utils/libpmemlog.pc.in, utils/libpmemobj.pc.in, utils/libpmempool.pc.in
"common: export libndctl and libdaxctl as private dependencies" matters only when linking to pmdk statically
"common: add libndctl directory to rpath" matters only for setups where both pmdk and ndctl are installed in private directories
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3688)
=> common: fix minor issues related to ndctl linking

src/test/tools/sparsefile/sparsefile.c
SetFilePointer returns DWORD
SetFilePointerEx returns BOOL
Found by code review, while looking for another bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3693)
=> test: (win) fix sparsefile error handling

src/test/unittest/unittest.sh
On 1.5 this produces a message without any apparent harm, on 1.6 it makes the tests fail if libfabric-bin is not installed.  At least on Debian and Ubuntu, libfabric-bin (tools) is a separate package than libfabric-dev (headers).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3689)
=> test: skip if fi_info is missing

utils/check-commit.sh, utils/check-doc.sh, utils/docker/pull-or-rebuild-image.sh
TRAVIS_REPO_SLUG should be always placed in double quotes
when used in the 'if' instruction, because it can be empty
(for example when the Travis build is run locally)
what causes syntax error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3699)
=> common: fix using TRAVIS_REPO_SLUG in if's

src/test/obj_critnib_mt/obj_critnib_mt.c
The structure is optimized for get speed, with little heed for puts and removes, which contend on a single lock.  Thus, MT write tests can take a long time on a machine with many cores.  Let's specify the # of ops as a total rather than per-thread number.
New values: same on a 10-thread machine, 1.25× longer on 8-threaded, 9.6× shorter on 96-threaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3706)
=> test: avoid obj_critnib_mt taking very long on many-core machines

src/common/file.c, src/libpmem/pmem.c
It turns out that _wopen on Windows can truncate a file by 1 byte when O_BINARY flag is not used and the last byte has a value of 0x1a. It doesn't always happen, but it does happen frequently enough. Currently this behavior is not mentioned in _wopen documentation (https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-wopen?view=vs-2019), but is in fopen documentation: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=vs-2019. Specifically it says:
> In text mode, CTRL+Z is interpreted as an EOF character on input. In files that are opened for reading/writing by using "a+", fopen checks for a CTRL+Z at the end of the file and removes it, if it is possible. This is done because using fseek and ftell to move within a file that ends with …
=> common: (win) fix possible pool file coruption

doc/libpmemblk/pmemblk_ctl_get.3.md, doc/libpmemlog/pmemlog_ctl_get.3.md, doc/libpmemobj/pmemobj_ctl_get.3.md, doc/librpmem/rpmem_persist.3.md, src/libpmemobj/tx.c
Debian lintian flagged this simple spelling mistake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3738)
=> Spelling fix (depracated -> deprecated)

src/common/os_dimm_ndctl.c
common: Fix build failure due to unused macro PAGE_SIZE
Commit b1251de66742("common: work around missing PAGE_SIZE") provided
a default value for PAGE_SIZE as a workaround for older kernels that
doesn't have the kernel fix f366d322ae("UAPI: ndctl: Remove use of
PAGE_SIZE").
However this causes a build failure when trying to build pmdk with
GCC-7.3.0 and a kernel that already has this above fix. GCC reports
following error indicating unused macro PAGE_SIZE:
$ gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
< snip >
$ make
< snip >
../../src/../src/common/os_dimm_ndctl.c:51:0: error: macro "PAGE_SIZE"
is not used [-Werror=unused-macros]
#define PAGE_SIZE 4096
< snip >
However since commit 10983411cc25 ("common: do not start ARS before
clearing bad blocks on DAX device") …
=> common: Fix build failure due to unused macro PAGE_SIZE

utils/build-dpkg.sh
In particular, it causes a Travis failure on downstream distributions that
have a non-volatile packaging directory there.  This causes noise that can
spook external contributors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3742)
=> common: dpkg: purge old debian/ dir if it exists

src/common/set.c
Function badblocks_recovery_file_exists now checks for status
-1, 0, 1 instead of !=0
Function returns:
- 0 when there are no bad block recovery files
- 1 when there is at least one bad block recovery file and
- -1 in any other case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3741)
=> common: fix bug in badblock file error handling

src/test/unittest/valgrind.py
The log with removed ignored warnings was generated in a faulty way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3751)
=> test: (py) fix valgrind validate log

src/test/RUNTESTS
The previous implementation allowed to run remote tests as local one
if the set of providers and the set of persistency-methods are empty.
Ref: pmem/issues#1055
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3735)
=> test: fix skipping remote tests

src/common/util.c, src/common/util.h
We need a function that returns checksum without
overwriting value in the buffer.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3755)
=> common: add a function that returns checksum

src/test/pmem_map_file/README, src/test/pmem_map_file/TEST0, src/test/pmem_map_file/TEST0.PS1, src/test/pmem_map_file/TEST1, src/test/pmem_map_file/TEST2, src/test/pmem_map_file/TEST3, src/test/pmem_map_file/TEST3.PS1, src/test/pmem_map_file/out0.log.match, src/test/pmem_map_file/out1.log.match, src/test/pmem_map_file/out2.log.match, src/test/pmem_map_file/out3.log.match, src/test/pmem_map_file/pmem_map_file.c
Added 6 test cases for pmem_map_file.
Scope of new test cases:
-Create mapping for an non-existing file
-Create mapping for an existing file passing nullptr as address for both mapped_lenp and is_pmem
-Create mapping for an existing file with an unnecesary creation flag
-Create mapping, forcing a sparse map file to be created
-Create mapping, forcing the map file to be created as a temporary file in a non-existent directory
-Create mapping for an existing file, forcing the map file to be created as a sparse file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3537)
=> test: add tests for pmem_map_file

src/libpmemobj/obj.c
Found using fault injection.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3780)
=> obj: don't overwrite errno when palloc_heap_check_remote fails

src/tools/Makefile.inc
This is an obvious thinko.  The result is that debug objects are
linked into the production build of the library.  Fix it.
Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3792)
=> tools: fix dynamic link line in Makefile.inc

src/libpmem/aarch64/arm_cacheops.h, src/libpmem/aarch64/flush.h, src/libpmem/aarch64/init.c
It was pointed out that we use CVAC instead of CVAP.  While this PR doesn't fix that yet, it does at least document my understanding so far, and fixes two other inefficiencies:
* a store fence is enough
* we shouldn't emulate CLFLUSH as even arm64 baseline has the equivalent of CLWB
The last part is especially egregious: our code effectively did:
```
MFENCE
CLFLUSH
MFENCE
```
for every cacheline.  Let's instead do the same thing we do on x86: a CLWB per cacheline, then a single SFENCE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3785)
=> pmem: improve flushes on arm64

src/libpmemobj/heap.c, src/libpmemobj/heap.h, src/libpmemobj/memblock.h, src/libpmemobj/palloc.c, src/libpmemobj/recycler.c, src/libpmemobj/recycler.h, src/test/obj_action/obj_action.c, src/test/obj_action/pmemcheck2.log.match, src/test/obj_heap/obj_heap.c, src/test/obj_pmalloc_mt/obj_pmalloc_mt.c
This patch removes the linear algorithm for reservation tracking
in favor of a simpler approach where reservations are immediately
resolved. This new approach has potentially lower scalability
(publish and cancel can contend on the bucket), but doesn't
exhibit prohibitive performance drops in cases with many
reservations.
Ref: pmem/issues#1034
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3642)
=> obj: optimize reservation handling

src/test/obj_reorder_basic/Makefile, src/test/pmreorder_flushes/Makefile, src/test/pmreorder_simple/Makefile, src/test/pmreorder_stack/Makefile, src/test/pmreorder_stack/pmreorder_stack.c
1. add comments clarifying linking LIBPMEMCOMMON
2. remove unnecessary macro call
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3803)
=> test: pmreorder VALGRIND_EMIT_LOG cleanup

src/Makefile, src/common.inc, utils/libpmemblk.pc.in, utils/libpmemlog.pc.in, utils/libpmemobj.pc.in, utils/libpmempool.pc.in
Older pkg-config (at least 0.27.1) doesn't support multiple
Requires.private's in a single file.
Ref: #3808
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3819)
=> common: support older versions of pkg-config

src/common/file_posix.c
The original implementation was looking at an NVDIMM specific attribute that is not generally applicable to all device-dax instances. It was also fragile in the face of the device-dax instances transitioning between 'dax-bus' and 'dax-class' device types.
Re-implement device_dax_alignment() to be compatible with either device model. The implementation walks the sysfs path hierarchy until it reaches the device hosting the "dax_region".
Link: https://github.com/pmem/issues/issues/1071
Signed-off-by: Dan Williams <dan.j.williams@intel.com>
Signed-off-by: Łukasz Plewa <lukasz.plewa@intel.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3828)
=> common: implement correct / robust device_dax_alignment

src/libpmemobj/heap.c, src/libpmemobj/palloc.c
Ref: pmem/issues#1077 pmem/issues#1078
@Greg091 Can you check if this patch fixes this on Travis? I ran the test a couple of times and it worked fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3821)
=> obj: fix helgrind false positive with memblock refcount

src/common/file_posix.c, src/common/util.c, src/common/util.h
The original implementation was looking at an NVDIMM specific attribute
that is not generally applicable to all device-dax instances. It was
also fragile in the face of the device-dax instances transitioning
between 'dax-bus' and 'dax-class' device types.
Re-implement device_dax_alignment() to be compatible with either device
model. The implementation walks the sysfs path hierarchy until it
reaches the device hosting the "dax_region".
Link: https://github.com/pmem/issues/issues/1071
Signed-off-by: Dan Williams <dan.j.williams@intel.com>
Signed-off-by: Łukasz Plewa <lukasz.plewa@intel.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3832)
=> [1.4] common: implement correct / robust device_dax_alignment

src/common/file_linux.c, src/common/util.c, src/common/util.h
The original implementation was looking at an NVDIMM specific attribute
that is not generally applicable to all device-dax instances. It was
also fragile in the face of the device-dax instances transitioning
between 'dax-bus' and 'dax-class' device types.
Re-implement device_dax_alignment() to be compatible with either device
model. The implementation walks the sysfs path hierarchy until it
reaches the device hosting the "dax_region".
Link: https://github.com/pmem/issues/issues/1071
Signed-off-by: Dan Williams <dan.j.williams@intel.com>
Signed-off-by: Łukasz Plewa <lukasz.plewa@intel.com>
[ Marcin: backported to pre-os-major tree ]
Signed-off-by: Marcin Ślusarz <marcin.slusarz@intel.com>
--- …
=> [1.3] common: implement correct / robust device_dax_alignment

src/libpmemobj/recycler.c, src/test/obj_zones/TEST1, src/test/obj_zones/obj_zones.c
In scenarios where free() is done very rarely the memory in the recycler
would not be looked at because the estimates would indicate that no memory
was freed and there's no reason to search the tree. Normally that's OK,
because eventually the heap would trigger a forced search of the entire
recycler for the allocation class, locating all the memory that might have
been missed. But, the forced recalculation erronously looked at the
estimates and required that at least some memory were freed since the
last recycler run - which might have not been the case.
This patch makes the forced recycling run without looking at the estimates.
Reported-by: Denny Zhao <denny.zhao@memverge.com>
--- …
=> obj: fix recycler not locating unused chunks

src/common/file.c
The old solution does not work since the kernel 5.1.X
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3844)
=> [1.3] common: fix device dax detection

src/common/file.c
The old solution does not work since the kernel 5.1.X
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3842)
=> [1.4] common: fix device dax detection

src/common/file.c
The old solution does not work since the kernel 5.1.X
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3843)
=> [1.2] common: fix device dax detection

src/test/rpmem_basic/TEST15, src/test/rpmem_basic/TEST18, src/test/rpmem_basic/TEST5, src/test/rpmem_basic/TEST6, src/test/rpmem_basic/TEST7
expect_normal_exit is incompatible with copy_file_to_node and is
causing trouble when used with Valgrind.
Ref: pmem/issues#1092
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3851)
=> test: remove invalid expect_normal_exit

src/test/rpmem_addr_ext/node_1_rpmem0.log.match
Information about libfabric fork safety is no longer printed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3862)
=> test: fix match file in rpmem_addr_ext test

src/test/obj_pmalloc_mt/obj_pmalloc_mt.c
Ref: pmem/issues#1076
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3864)
=> test: fix lock initialization in obj_pmalloc_mt

src/benchmarks/pmembench.vcxproj, src/common/libpmemcommon.vcxproj, src/test/blk_non_zero/blk_non_zero.vcxproj, src/test/blk_pool/blk_pool.vcxproj, src/test/blk_pool_lock/blk_pool_lock.vcxproj, src/test/blk_rw/blk_rw.vcxproj, src/test/blk_rw_mt/blk_rw_mt.vcxproj, src/test/test_debug.props, src/test/test_release.props, src/test/tools/bttcreate/bttcreate.vcxproj, src/test/tools/cmpmap/cmpmap.vcxproj, src/test/tools/ddmap/ddmap.vcxproj, src/test/tools/pmemalloc/pmemalloc.vcxproj, src/test/tools/pmemobjcli/pmemobjcli.vcxproj, src/test/tools/pmemspoil/pmemspoil.vcxproj, src/test/tools/pmemwrite/pmemwrite.vcxproj, src/test/unittest/libut.vcxproj, src/tools/pmempool/pmempool.vcxproj, src/windows/libs_debug.props, src/windows/libs_release.props, src/windows/srcversion/srcversion.vcxproj
Generate Manifest should always be set to true, what is a default value,
so we can remove it from all project files. Manifest is required for
long path support
Ref: pmem/issues#842
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3876)
=> [1.4] common: remove GenerateManifest from projects

src/test/obj_tx_lock/TEST0.PS1, src/test/obj_tx_lock/TEST1, src/test/obj_tx_lock/obj_tx_lock.c
Ref: pmem/issues#1105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3870)
=> [1.4] test: split test obj_tx_lock into two test cases

src/test/ex_librpmem_fibonacci/TEST1
For older kernels cleaning bad-blocks require sudo.
This is not relevant for this test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3869)
=> test: add option that disables cleaning bad-blocks

src/librpmem/rpmem_cmd.c, src/librpmem/rpmem_cmd.h, src/librpmem/rpmem_ssh.c
Killing daemon before starting waiting
for it to close is unnecessary and causes issues.
Ref: /pmem/issues#995
Ref: /pmem/issues#1060
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3872)
=> rpmem: remove kill command

src/examples/libpmemobj/array/array.c
the region between prev_size to size in array is not flushed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3860)
=> fix unflushed in relloc_int

src/test/rpmem_basic/TEST15, src/test/rpmem_basic/TEST5, src/test/rpmem_basic/TEST6, src/test/rpmem_basic/TEST7
expect_normal_exit is incompatible with copy_file_to_node and is
causing trouble when used with valgrind.
Ref: pmem/issues#1092
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3881)
=> [1.4] test: remove invalid expect_normal_exit

src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c
remove checking errno in obj_tx_add_range_direct.
Malloc sets errno, despite function succeed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3889)
=> [1.4] Fix obj_tx_add_range_direct test

src/test/rpmem_basic/TEST21
Was missed in 22bcbacac as this test didn't exist in 1.6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3882)
=> test: remove one last expect_normal_exit copy_file_to_node

utils/pmdk.spec.in
Pass the flag to disable ndctl down to the make `[install|check]` if the user builds
the rpm `--without-ndctl`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3681)
=> Give the NDCTL_ENABLE=n make option when using --without-ndctl

src/test/unittest/unittest.sh
`dd` spews some statistics to stderr, we don't want those.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3900)
=> test: hide irrelevant messages from dd

src/common/pmemcommon.inc, src/common/rand.c, src/common/rand.h, src/test/blk_rw_mt/blk_rw_mt.c, src/test/blk_rw_mt/blk_rw_mt.vcxproj, src/test/obj_critnib_mt/obj_critnib_mt.c, src/test/obj_critnib_mt/obj_critnib_mt.vcxproj, src/test/obj_fragmentation2/obj_fragmentation2.c, src/test/obj_fragmentation2/obj_fragmentation2.vcxproj, src/test/obj_pmalloc_rand_mt/obj_pmalloc_rand_mt.c, src/test/obj_pmalloc_rand_mt/obj_pmalloc_rand_mt.vcxproj, src/test/unittest/Makefile
Windows doesn't support rand_r(), fixed seeds for reproducible tests, and its rand() output is 15-bit only.  And on Linux/BSD, different versions of libc are unstable, too.  Thus, let's use a simple good RNG (such as xoshiro256**) on all platforms.
This copies code that's already in *vmemcache*.
This pull request changes all uses of rand in tests, it doesn't yet touch benchmarks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3894)
=> use the same RNG on Linux/BSD and on Windows

src/benchmarks/benchmark.hpp
The init_worker callback is called not from the master thread (as the old comment suggested) but from the worker thread itself.  These callbacks get run for each thread in turn.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3903)
=> clarify a comment about benchmark initialization

src/Makefile
To reproduce the fails:
`make tools`
or
`make libpmempool`
or
remove `.NOTPARALLEL`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3920)
=> fix missing Makefile dependencies for some targets

src/Makefile, src/test/Makefile
While build-testing them is nice, build artifacts littering the to-install dirs make installing examples prohibitively hard.
Debian carries a hard-coded patch that disables compiling them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3922)
=> allow not building examples

src/test/obj_tx_add_range/memcheck3.log.match, src/test/obj_tx_add_range_direct/memcheck2.log.match
On some systems (for example OpenSUSE) memcheck generates errors
which we are suppressing. This patch adds optional lines to
memcheck.log.match to match those suppressed errors.
Fixes test introduced in: #3921
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3935)
=> test: fix memcheck.log.match in obj_tx_add_range(_direct) tests

utils/docker/run-build.sh, utils/docker/run-coverage.sh
"1" is not a valid value for USE_LIBUNWIND. Instead of providing
the correct value, let pmdk build system detect whether it is available
or not. All distros we test on Travis ship with libunwind that
supports pkg-config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3938)
=> common: detect libunwind on Travis

src/test/obj_tx_add_range/TEST0, src/test/obj_tx_add_range/TESTS.py
TEST3 already has a match for this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3951)
=> disable an expected-fail test under valgrind

src/libpmemobj/tx.c
Rationale:
1. ERANGE is C99 standard defined error code.
2. EOVERFLOW is used when destination buffer is too small and data
transfer will overflow it. When ERANGE is used for values that do not
fit in the destination type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3957)
=> obj: replace EOVERFLOW with ERANGE

src/test/testconfig.py.example, src/test/testconfig.sh.example
All three test frameworks use their own, different, syntax.
Windows has no devdax, thus here come two of them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3966)
=> give examples how to specify multiple /dev/dax devices

src/test/unittest/unittest.sh
... for dev dax bad block tests, as some
may use an additional filesystem for replica
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3969)
=> test: change required fs from none to any

doc/libvmem/libvmem.7.md, doc/libvmmalloc/libvmmalloc.7.md
We want folks to use **memkind** instead.
Still, despite deprecation, the cost of keeping a library alive is minimal (fixing bugs and compiler/platform regressions), thus there's no need to force migrations. User code will work a decade in the future just as well as it does today.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3795)
=> doc: vmem, vmmalloc: document maintenance state

src/test/pmempool_sync/TEST27, src/test/pmempool_sync/TEST28, src/test/pmempool_sync/out27.log.match, src/test/pmempool_sync/out28.log.match
Make two pmempool_sync tests fixing bad blocks
in the pool header more precise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3980)
=> test: make two pmempool_sync tests more precise

src/common/os_posix.c
__USE_GNU does not cover all Linux platforms, e.g. when using musl as C
library, __USE_GNU may not be defined but it does provide secure_getenv
so instead of narrowing the else condition, lets speicifically check for
FreeBSD being the platform, since that seems to be the intention here
anyway
Signed-off-by: Khem Raj <raj.khem@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4000)
=> os_posix: Use __FreeBSD__ to control secure_getenv definition

src/libpmem/pmem.c
The comment wrongly stated that len is changed to cover the whole page.
This is actually not true, len is only increased by the amount of which
addr is decreased.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4006)
=> pmem: fix comment in pmem_msync

src/test/obj_tx_add_range_direct/TEST0, src/test/obj_tx_add_range_direct/TESTS.py
Same as obj_tx_add_range/TEST0
Ref: pmem/issues#1122, as reported by @Greg091.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4031)
=> test: disable memcheck on obj_tx_add_range_direct/TEST0

src/common/file.c
It is not a good idea to pass such big structures by value.
Ref: pmem/pmdk#4029
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4035)
=> common: prepare for libpmem2 needs (fix)

doc/pmempool/pmempool-check.1.md, src/tools/pmempool/check.c
The old name is kept as an undocumented alias.
Fixes pmem/issues#277.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4027)
=> pool: rename -N --no-exec to -d --dry-run

src/test/memcheck-ndctl.supp
This patch suppresses the following memory leak in ndctl 64.1:
```
[line 14166] daxio/TEST0: SETUP (all/pmem/debug/memcheck)
[line 14167] daxio/TEST0 failed with Valgrind. See memcheck0.log. Last 20 lines below.
[line 14168] daxio/TEST0 memcheck0.log ==62745== 156 bytes in 13 blocks are definitely lost in loss record 2 of 3
[line 14169] daxio/TEST0 memcheck0.log ==62745==    at 0x4C30701: realloc (vg_replace_malloc.c:836)
[line 14170] daxio/TEST0 memcheck0.log ==62745==    by 0x50F0A94: ??? (in /usr/lib64/libndctl.so.6.13.0)
[line 14171] daxio/TEST0 memcheck0.log ==62745==    by 0x50F2487: ??? (in /usr/lib64/libndctl.so.6.13.0)
[line 14172] daxio/TEST0 memcheck0.log ==62745==    by 0x50F970C: ??? (in /usr/lib64/libndctl.so.6.13.0)
[line 14173] daxio/TEST0 memcheck0.log ==62745==    by …
```
=> test: modify suppression for ndctl memleaks

utils/pmdk.spec.in
In order to use %fdupes, "BuildRequires: fdupes" has to be included
in the spec file:
https://en.opensuse.org/openSUSE:Packaging_Conventions_RPM_Macros#.25fdupes
Tested on openSuSE Tumbleweed-latest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4057)
=> common: add BuildRequires:fdupes to spec for opensuse

src/include/libpmem2.h, src/libpmem2/libpmem2.def, src/libpmem2/libpmem2.link.in, src/libpmem2/pmem2.c, src/test/scope/out13.log.match
We have realized it is not a useful functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4069)
=> pmem2: remove pmem2_get_config

src/include/libpmem2.h, src/libpmem2/config_posix.c, src/libpmem2/config_windows.c
- add missing brief
- change input argument type to const
Ref: pmem/pmdk#4076
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4086)
=> pmem2: _get_file_size (fix)

src/Makefile
Tests often fail on weird filesystems; lack of free disk space can also lead to non-obvious errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4032)
=> include df in testsuite output

utils/docker/images/Dockerfile.ubuntu-18.04, utils/docker/images/install-libndctl.sh
1) Documentation for ndctl is not needed.
2) It will speed up the build.
3) The 'asciidoctor' is not available in some Linux distros.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4091)
=> common: disable building ndctl's docs

src/tools/pmreorder/operationfactory.py, src/tools/pmreorder/statemachine.py
Fix following style issues:
./statemachine.py:150:17: F632 use ==/!= to compare str, bytes, and int literals
./statemachine.py:268:17: F632 use ==/!= to compare str, bytes, and int literals
./statemachine.py:271:17: F632 use ==/!= to compare str, bytes, and int literals
./statemachine.py:274:17: F632 use ==/!= to compare str, bytes, and int literals
./statemachine.py:277:17: F632 use ==/!= to compare str, bytes, and int literals
./operationfactory.py:109:21: E117 over-indented
./operationfactory.py:111:21: E117 over-indented
Found on Ubuntu-rolling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4092)
=> common: fix style issues in Python files

utils/docker/images/install-libfabric.sh, utils/docker/images/install-libndctl.sh, utils/docker/images/install-valgrind.sh, utils/docker/run-build-package.sh, utils/docker/run-build.sh, utils/docker/run-coverage.sh, utils/docker/run-coverity.sh, utils/docker/run-doc-update.sh
... and add '-j$(nproc)' where no '-j' option is present,
so that building can be faster when it is run locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4111)
=> common: replace '-j2' with '-j$(nproc)' in make calls

src/libpmemobj/memblock.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4240)
=> obj: remove 64 byte alignment in favor of cl alignment

doc/libpmem2/pmem2_config.3.md, doc/libpmem2/pmem2_config_new.3.md, doc/libpmem2/pmem2_errormsg.3.md, doc/libpmem2/pmem2_map.3.md, doc/libpmem2/pmem2_map_get_address.3.md, doc/libpmem2/pmem2_map_get_size.3.md, src/include/libpmem2.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4244)
=> pmem2: fix doc, libpmem2.h variable names and missing brackets

utils/docker/run-coverity.sh
Since dockerimages were updated (in #4110 ) gcc-6 is no longer available.
Wanting to test if Coverity will work correctly this old workaround is
deleted and gcc-9 (default one, for now) will be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4249)
=> common: use new version of gcc in Coverity

src/test/obj_memcheck/TEST0, src/test/unittest/unittest.sh
Used by vmmalloc tests. (obj_memcheck use doesn't make any sense)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4253)
=> test: remove support for TEST_LD_PRELOAD variable

utils/docker/configure-tests.sh
'find' can exit with status greater than 0, even if it found the files.
It happens on Arch Linux:
```
$ find /usr -name "libfabric.pc" ; echo RV=$?
find: ‘/usr/share/polkit-1/rules.d’: Permission denied
/usr/lib/pkgconfig/libfabric.pc
RV=1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4260)
=> common: ignore exit status of find

doc/libpmem2/pmem2_map.3.md, doc/libpmem2/pmem2_unmap.3.md, src/include/libpmem2.h, src/libpmem2/map.c, src/libpmem2/map_posix.c, src/libpmem2/map_windows.c, src/test/pmem2_integration/pmem2_integration.c, src/test/pmem2_map/pmem2_map.c
We have to document that our functions return 0 on success
so the user knows that he is allowed to do:
if (pmem2_xxxx()) {
/* error handling */
}
otherwise he must do:
if (pmem2_xxxx() != PMEM2_E_OK) {
/* error handling */
}
Also, this commit is replacing PMEM2_E_OK with 0
to make code aligned with documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4255)
=> pmem2: remove PMEM2_E_OK

src/test/util_file_open/TEST0w.PS1, src/test/util_file_open/out0w.log.match
Dropped as part of 8d65df7fcf0acfe8775d70f4ba11cabd9b5a819f.
Not needed thanks to 1de508f69a2be5dd4549348cb6d63fb8d9e5ee60.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4269)
=> test: restore one test case of util_file_open

doc/generated/pmemobj_cancel.3, doc/generated/pmemobj_publish.3, doc/generated/pmemobj_reserve.3, doc/generated/pmemobj_set_value.3, doc/generated/pmemobj_tx_publish.3, doc/generated/pmemobj_xreserve.3, doc/generated/pobj_reserve_alloc.3, doc/generated/pobj_reserve_new.3
These files are blacklisted from the usual whitespace check, thus the newlines haven't been found before.  Axing them simplifies my work elsewhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4275)
=> drop whitespace after a few manpage links

src/tools/pmreorder/pmreorder.py, utils/docker/run-build-package.sh
When pmreorder installed in the system python can't properly parse the extra argument (the one with version), so it's needed to remove it from the argv list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4273)
=> pmreorder: fix handling version's extra argument

src/libpmem2/map.c, src/libpmem2/map.h, src/libpmem2/map_posix.c, src/libpmem2/map_windows.c, src/test/pmem2_map/TESTS.py, src/test/pmem2_map/pmem2_map.c
Fix unmapping the not needed part of the reservation.
Ref: pmem/pmdk#4013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4282)
=> pmem2: fix map_reserve

src/libpmemobj/memops.c, src/libpmemobj/ulog.c, src/test/obj_memops/obj_memops.c
All transient actions in a single memory operation after 64th weren't
being applied correctly because the non-cached capacity of a transient ulog
wasn't being updated alongside the cached capacity - this caused a problem
where the vast majority of code used the cached version, but the actual
applying method used the uncached one.
The only public API that could conceivably trigger this is
pmemobj_set_value when used on volatile variables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4266)
=> obj: fix transient redo log of more than 64 entries

src/libpmemobj/list.c, src/libpmemobj/memops.c, src/libpmemobj/palloc.c, src/test/obj_list/obj_list_mocks_palloc.c, src/test/obj_memops/obj_memops.c
In 1.7 we made it so that memops ulogs are freed during operation
processing. This causes a problem because the free operation, for
redo logs, is now potentially nested inside of palloc operation
causing recursive lock acqusition on locks that aren't marked as
recursive, leading to hangs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4280)
=> obj: fix unintended recursive locking during palloc

.cirrus.yml
- to FreeBSD 12.1 version (released 4 November 2019)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4318)
=> common: update FreeBSD version in Cirrus CI

utils/build-dpkg.sh
The binary package of libfabric in Debian is called libfabric1 which
has been contained in shlibs:Depends. So remove the explicit dependency.
Signed-off-by: Changcheng Liu <changcheng.liu@aliyun.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4323)
=> common: fix Debian package dependency

src/test/pmem2_granularity/TESTS.py, src/test/testconfig.py.example, src/test/unittest/context.py, src/test/unittest/granularity.py
Take existence of config test dir fields into account
when selecting granularites to be used for execution
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4335)
=> test: (py) fix config granularity filter behaviour

src/libpmem2/Makefile, src/libpmem2/libpmem2.vcxproj, src/libpmem2/libpmem2.vcxproj.filters, src/test/Makefile.inc
These files are no longer needed:
- common/file.c
- common/file_posix.c
- common/file_windows.c
- common/mmap.c
- common/mmap_posix.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4344)
=> pmem2: trim the list list of linked files

src/libpmem2/Makefile, src/libpmem2/errormsg.c, src/libpmem2/libpmem2.vcxproj, src/libpmem2/libpmem2.vcxproj.filters, src/test/Makefile.inc, src/test/pmem2_config/Makefile, src/test/pmem2_config/pmem2_config.vcxproj, src/test/pmem2_config/pmem2_config.vcxproj.filters, src/test/pmem2_config_get_alignment/Makefile, src/test/pmem2_config_get_alignment/pmem2_config_get_alignment.vcxproj, src/test/pmem2_config_get_alignment/pmem2_config_get_alignment.vcxproj.filters, src/test/pmem2_config_get_file_size/Makefile, src/test/pmem2_config_get_file_size/pmem2_config_get_file_size.vcxproj, src/test/pmem2_config_get_file_size/pmem2_config_get_file_size.vcxproj.filters, src/test/pmem2_granularity/pmem2_granularity.vcxproj, src/test/pmem2_granularity/pmem2_granularity.vcxproj.filters, src/test/pmem2_map/Makefile, src/test/pmem2_map/pmem2_map.c, src/test/pmem2_map/pmem2_map.vcxproj, src/test/pmem2_map/pmem2_map.vcxproj.filters
libpmem2_init will soon call other modules init functions.
libpmem2.c is linked into some unit tests because of pmem2_errormsg.
When I'll extend libpmem2_init to call other module initialization
functions the above tests would have to link to those other modules...
Avoid that by splitting libpmem2.c and linking the tests that need
pmem2_errormsg with errormsg.c.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4351)
=> pmem2: split errormsg.c out of libpmem2.c

src/libpmem/pmem.c, src/libpmem2/aarch64/init.c, src/libpmem2/pmem2_arch.h, src/libpmem2/ppc64/platform_generic.c, src/libpmem2/x86_64/init.c
deep_flush is a misleading name - the callback behind it is supposed
to only flush the cpu caches and nothing more.
It is used to implement deep_flush **later**.
Splitted out of #4333.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4352)
=> pmem2: fix naming of arch flush callback

src/test/blk_rw/out0.log.match, src/test/blk_rw/out1.log.match, src/test/blk_rw/out2.log.match, src/test/blk_rw/out3.log.match, src/test/blk_rw/out4.log.match, src/test/blk_rw/out5.log.match, src/test/blk_rw/out6.log.match, src/test/blk_rw/out7.log.match, src/test/blk_rw/out8.log.match, src/test/blk_rw/out8w.log.match, src/test/blk_rw/out9.log.match, src/test/blk_rw/out9w.log.match, src/test/blk_rw_mt/out1.log.match, src/test/blk_rw_mt/out2.log.match, src/test/obj_basic_integration/out1.log.match, src/test/obj_tx_locks_abort/out0.log.match, src/test/obj_tx_locks_abort/out1.log.match, src/test/obj_tx_locks_abort/out2.log.match
lucmaga noticed and dropped them when copying ppc64 parts, let's drop them elsewhere as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4387)
=> get rid of $(nW)$(nW) in tests

src/common/set.h
With unsigned X and Y, (X+Y)%X = Y%X unless an overflow happens, and on overflow we trample over the wrong replica/part anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4356)
=> axe a bunch of useless additions

src/libpmemobj/memops.c, src/libpmemobj/ulog.c, src/libpmemobj/ulog.h, src/test/obj_list/obj_list_mocks.c, src/test/obj_memops/obj_memops.c
In situations where the total number of entries to be stored in the
ulog was an exact fit for the total capacity of the log,
the algorithm was unnecessarily trying to zero-out a non-existent
subsequent ulog. This triggered an ASSERT on debug builds and crashed
on NULL-dereferencing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4403)
=> obj: fix potential NULL-dereference in ulog_store

src/libpmemlog/log.h
For multiplatform compatibility the header should be aligned to the
platforms page size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4411)
=> log: fix libpmemlog header alignment

src/tools/pmempool/common.h
The header size definition should match the platform's size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4412)
=> tools: fix pmempool header sizes

src/test/pmem2_config_get_alignment/TESTS.py
Based on: https://github.com/pmem/pmdk/pull/4373 (test (py): enable defining devdax requirements)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4375)
=> test: pmem2 alignment test extension

src/libpmem/libpmem.vcxproj, src/libpmem/libpmem.vcxproj.filters, src/libpmem/pmem.h, src/libpmem/x86_64/flags.inc, src/libpmem/x86_64/init.c, src/libpmem/x86_64/memcpy/memcpy_nt_avx.h, src/libpmem/x86_64/memcpy/memcpy_nt_avx512f.h, src/libpmem/x86_64/memcpy/memcpy_nt_avx512f_noflush.c, src/libpmem/x86_64/memcpy/memcpy_nt_avx_noflush.c, src/libpmem/x86_64/memcpy/memcpy_nt_sse2_noflush.c, src/libpmem/x86_64/memcpy/memcpy_t_avx.h, src/libpmem/x86_64/memcpy/memcpy_t_avx512f.h, src/libpmem/x86_64/memcpy/memcpy_t_avx512f_noflush.c, src/libpmem/x86_64/memcpy/memcpy_t_avx_noflush.c, src/libpmem/x86_64/memcpy/memcpy_t_sse2_noflush.c, src/libpmem/x86_64/memcpy_memset.h, src/libpmem/x86_64/memset/memset_nt_avx.h, src/libpmem/x86_64/memset/memset_nt_avx512f_noflush.c, src/libpmem/x86_64/memset/memset_nt_avx_noflush.c, src/libpmem/x86_64/memset/memset_nt_sse2_noflush.c, src/libpmem/x86_64/memset/memset_t_avx.h, src/libpmem/x86_64/memset/memset_t_avx512f.h, src/libpmem/x86_64/memset/memset_t_avx512f_noflush.c, src/libpmem/x86_64/memset/memset_t_avx_noflush.c, src/libpmem/x86_64/memset/memset_t_sse2_noflush.c, src/libpmem/x86_64/sources.inc
Untested, because it's not possible to fake eADR in libpmem1.
Found by @Greg091 while testing libpmem2, where we can fake eADR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4406)
=> pmem: fix pmemcheck support on platforms with eADR

src/test/util_pool_hdr/util_pool_hdr.c
The test was broken on ppc64le because of a missing pad field present
only on platforms with page size bigger than 4096.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4421)
=> test: fix util_pool_hdr for page size > 4096

src/libpmemobj/palloc.c
Given a following (sorted) collection of heap actions on
memory blocks 1, 2:
Alloc 1.1, Alloc 1.2, Free 1.3, Free 2.2, Free 2.5
The algorithm looks at every action and acquires lock
for that memory block if that lock wasn't acquired previously.
In this example, two locks would be acquired (2 blocks).
After this is done, the actions are processed. Next,
the actions are iterated over again, in the exact same order,
and an "on_process" callback is invoked and the lock for
that action is dropped.
And this was the problem. The locks were being dropped before all
actions for the same memory block had their "on_process" callback
invoked.
In this example, the order of operations would be:
lock(m.1);
lock(m.2);
process_actions();
on_process(1.1);
unlock(m.1);
on_process(1.2);
on_process(1.3); …
=> obj: fix lock release order in palloc publish

src/librpmem/rpmem_fip.c
```rpmem_flush()``` may provide two possible ```flags``` values:
- ```RPMEM_FLUSH_WRITE``` where data is sent over RDMA.Write after which RDMA.Send is triggering ```pmem_persist()``` on the remote side (**Send-after-Write**)
- ```RPMEM_PERSIST_SEND``` where data is send inlined over RDMA.Send where on the remote side it is feed into ```pmem_memcpy_persist()``` (**Send-inline**)
The issue was ```rpmem_fip_flush_gpspm()``` assumed the **Send-after-Write** is fair enough but ```flags``` may still indicate **Send-after-Write** as well as **Send-inline**. Feeding ```flags``` indicating **Send-inline** into **Send-after-Write** caused RDMA.Send, meant for triggering ```pmem_persist()``` on the remote side, to be used for ```pmem_memcpy_persist()```, where the data for copying was missing, …
=> rpmem: add a missing case for GPSPM + FLUSH_STRICT

src/include/libpmemobj/types.h
Ref: pmem/pmdk#4303
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4433)
=> common: disable workaround for offsetof() since VS 15.5

src/libpmemobj/memops.c, src/test/obj_ulog_size/obj_ulog_size.c
For 128 bytes cacheline the append size of 256 are not enough to store a
ulog. In this case the append size are being added one more cacheline
size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4427)
=> test: fix obj_ulog_size append size

src/libpmempool/sync.c
When recovering from a healthy remote replica, we did try to stat a local file anyway, using *path* = NULL.  Which obviously caused errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4355)
=> rpmem: don't stat a non-local replica during recovery

src/librpmem/rpmem_fip.c
The struct is declared as `__attribute__((aligned(LANE_ALIGN_SIZE)))` (64) so we should obey that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4354)
=> rpmem: fix a lane misalignment

doc/libpmemobj/pmemobj_ctl_get.3.md, src/include/libpmemobj/ctl.h, src/libpmemobj/heap.c, src/libpmemobj/palloc.c, src/libpmemobj/stats.c, src/libpmemobj/stats.h, src/test/obj_ctl_stats/obj_ctl_stats.c, src/test/obj_fragmentation2/obj_fragmentation2.c
This patch introduces two new statistics: stats.heap.run_active and
stats.heap.run_allocated. Combination of these two can be used to
estimate the total potentially unused space in the heap, indicating
that defrag should be ran.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4332)
=> obj: introduce new statistics useful for defrag

src/libpmemobj/palloc.c, src/test/obj_fragmentation2/obj_fragmentation2.c
This patch removes a check from defrag that prevented
realloc of objects from highly filled runs to low filled runs.
This was originally done as a performance optimization to
reduce the number of realloced objects.
Turns out this has non-negligible negative impact on
effectivness of defrag.
Ref: #4477 #4473 #4474
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4492)
=> obj: remove fill ratio optimization from defrag

src/test/out_err_mt/TEST0, src/test/out_err_mt/TEST1, src/test/out_err_mt/TEST2, src/test/unittest/unittest.sh
It allows msyncs to succeeded even when called with intentionally bogus arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4482)
=> kill eatmydata in some tests

doc/Makefile
fixes "make install" without "make" on freshly cloned tree
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4495)
=> doc: add dependency between compressed and uncompressed man pages

doc/Makefile, src/tools/Makefile.inc
By default, gzip stores timestamps (which usually are the date the file was last checked out from git), and that makes builds produce different files for every checkout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4496)
=> make .gz files reproducible

src/test/obj_defrag_advanced/obj_defrag_advanced.c
Since our logging subsystem is not thread-safe
it should not be used by mulitple threads in parallel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4506)
=> test: remove logging from the parallelized path

doc/libpmemobj/pmemobj_alloc.3.md
with more precise description on using non-transactional API in transactions.
It's inspired by the latest addition - defrag func.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4511)
=> doc: update pmemobj_alloc.3

src/libpmemobj/heap.c, src/test/obj_heap/obj_heap.c
The calculations for total available heap size for user
allocations didn't take all possible metadata into account,
leading to situations where for certain heap sizes
the zone size was too large by a chunk.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4522)
=> obj: fix zone size calculations

src/test/obj_tx_add_range/memcheck3.log.match, src/test/obj_tx_add_range_direct/memcheck2.log.match
The order and wording of an advice message is different vs 3.15.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4524)
=> test: unbreak obj_tx_add_range{,direct} on valgrind-3.14

src/test/unittest/unittest.sh
Remove '/usr/bin/fi_info' from output of tests:
```
...
/usr/bin/fi_info
/usr/bin/fi_info
pmempool_sync_remote/TEST20: SETUP (check/pmem/debug/sockets/GPSPM)
pmempool_sync_remote/TEST20: PASS
/usr/bin/fi_info
/usr/bin/fi_info
...
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4534)
=> test: remove '/usr/bin/fi_info' from output of tests

utils/docker/prepare-for-build.sh
Travis has recently changed UID.GID of its user to 2000.2000
while the Docker user has: UID=1000(pmdkuser) and GID=27(sudo)
and it cannot write to the WORKDIR:
```
...
$ ./build-travis.sh
[sudo] password for pmdkuser: ./configure-tests.sh: line 41: /pmdk/src/test/testconfig.sh: Permission denied
The command "./build-travis.sh" exited with 1.
```
Make sure WORKDIR has correct access rights
by setting them to the current UID and GID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4540)
=> common: make sure WORKDIR has correct access rights

src/libpmem2/x86_64/cpu.c, src/libpmem2/x86_64/cpu.h
https://support.amd.com/TechDocs/24594.pdf documents it is supported
if the same feature bit (as on Intel CPUs) is set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4542)
=> pmem: clwb instruction is available on AMD CPUs

utils/check_license/check-headers.sh
before #4538 all errors from check-licence was printed in gcc style:
file:number: error message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4551)
=> utils: check-licence print errors in gcc style

src/jemalloc/jemalloc.mk
I like to be able to test them without mucking with compiler versions or chroots.
Obviously uplifting this commit will fail for 1.8, but 1.{5,6,7} want it.
Cherry-picked from vmem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4549)
=> let jemalloc on old branches build with gcc-10

.github/workflows/gha.yml
Remove redundant chown from GHA yaml script.
It is not needed since 424d420 was merged upstream.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4561)
=> common: remove redundant chown from GHA yaml script

src/libpmemobj/obj.c, src/test/obj_tx_alloc/obj_tx_alloc.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4555)
=> obj: detect msync failures in non-pmem variants of mem[cpy|move|set]

src/test/obj_zones/obj_zones.c
This test was timing out because of intensive page_fault
handling. By allocating more by each loop we minimize this
issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4578)
=> test: Fix obj_zones for ppc64le

GIT_VERSION, utils/SRCVERSION.ps1, utils/version.sh
It allows tools which expect version in form major.minor to work
correctly even in case when pmdk is downloaded as zip archive.
This can be tested by downloading zip archive from my fork (from branches stable-1.5, stable-1.6, stable-1.7, stable-1.8 or test_fix) and running utils/versions.sh
```
wget https://github.com/igchor/pmdk/archive/stable-1.6.zip
unzip stable-1.6.zip
cd pmdk-stable-1.6
utils/version.sh .
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4569)
=> common: prepend release number to version when using GIT_VERSION

.github/workflows/gha.yml, .travis.yml, utils/docker/build-travis.sh, utils/docker/images/push-image.sh, utils/docker/pull-or-rebuild-image.sh
This patch fixes regression introduced by commit 696786d.
It turned out that passing CI_* variables through environment
does not work - they are not passed through at all.
The 'set-ci-vars.sh' script has to be called directly
in other CI scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4591)
=> common: fix CI building

doc/Makefile, doc/libpmem2/.gitignore, doc/libpmem2/pmem2_map.3.md, doc/libpmem2/pmem2_source_size.3.md, src/PMDK.sln, src/common/file.c, src/include/libpmem2.h, src/libpmem2/libpmem2.def, src/libpmem2/libpmem2.link.in, src/libpmem2/map_posix.c, src/libpmem2/map_windows.c, src/libpmem2/source_posix.c, src/libpmem2/source_windows.c, src/test/Makefile, src/test/pmem2_integration/pmem2_integration.c, src/test/pmem2_persist_valgrind/pmem2_persist_valgrind.c, src/test/pmem2_source_file_size/.gitignore, src/test/pmem2_source_size/.gitignore, src/test/pmem2_source_size/Makefile, src/test/pmem2_source_size/TESTS.py, src/test/pmem2_source_size/pmem2_source_size.c, src/test/pmem2_source_size/pmem2_source_size.vcxproj, src/test/pmem2_source_size/pmem2_source_size.vcxproj.filters, src/test/scope/out13.log.match
Source may not necessarily be a file.
pmem2_source_file_size is now an alias for pmem2_source_size. It will be removed once other PRs, that might still use it, will be merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4585)
=> pmem2: rename pmem2_source_file_size to pmem2_source_size

src/include/libpmem2.h, src/libpmem2/usc_ndctl.c, src/libpmem2/usc_windows.c
Fixes build after 021c91e502a32707621148a6f73a09fb925b5a4a.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4595)
=> pmem2: use PMEM2_E_BUFFER_TOO_SMALL in pmem2_source_device_id

src/tools/pmempool/pmempool.c
Those functions can be not called in some cases now:
- util_remote_fini();
- rpmem_util_cmds_fini();
Fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4593)
=> pool: fix error handling in pmempool

utils/docker/run-coverity.sh
The command:
```
$ sudo tee -a /etc/ssl/certs/ca-
```
fails with the following error on GitHub Actions CI:
```
sudo: no tty present and no askpass program specified
```
This patch fixes this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4592)
=> common: fix run-coverity.sh script

doc/pmempool/pmempool.1.md, src/tools/pmempool/pmempool.c
Logs from the 'common' files (for example logs
regarding detecting and fixing bad blocks):
```
<pmempool>: <3> [badblock.c:26 badblocks_new]  
<pmempool>: <3> [badblock_ndctl.c:29 os_badblocks_get] file ./pool badblocks 0x5576d1c72c40
<pmempool>: <3> [os_dimm_ndctl.c:665 os_dimm_files_namespace_badblocks] path ./pool
<pmempool>: <3> [os_dimm_ndctl.c:629 os_dimm_files_namespace_badblocks_bus] ctx 0x5576d1c71f80 path ./pool pbus (nil) badblocks 0x5576d1c72c40
<pmempool>: <3> [os_dimm_ndctl.c:147 os_dimm_region_namespace] ctx 0x5576d1c71f80 stat 0x7ffeddcfff30 pregion 0x7ffeddcfff20 pnamespace 0x7ffeddcfff28
<pmempool>: <3> [os_dimm_ndctl.c:78 os_dimm_match_fsdax] st 0x7ffeddcfff30 devname pmem0
<pmempool>: <10> [os_dimm_ndctl.c:133 os_dimm_match_fsdax] skipping not matching device: …
```
=> pool: enable logs from 'common' files in pmempool

utils/check-manpage
Purely cosmetic, and RHEL7's pandoc causes those.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4602)
=> silence a man warning

Makefile
With this patch, setting explicitly DOC=n disables building and installing documentation, for instance: 
`make DOC=n install `
Some reasons behind a such change:
- drop dependency on pandoc
- build and install pmdk without documentation on deployment nodes
See https://github.com/pmem/pmdk/issues/4590
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4596)
=> Adding DOC variable to Makefile that enables/disables building & installing documentation

utils/docker/set-ci-vars.sh
Set CI_EVENT_TYPE to 'cron' when GITHUB_EVENT_NAME equals 'schedule'.
It fixes Coverity builds run on GHA. They are not started now,
because CI_EVENT_TYPE equals 'schedule' instead of 'cron'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4618)
=> common: set CI_EVENT_TYPE to 'cron' when GITHUB_EVENT_NAME is 'schedule'

utils/docker/run-doc-update.sh
The 'hub' command fails now with the following error:
```
Error creating pull request: Unauthorized (HTTP 401)
Requires authentication
github.com username: github.com password for  (never stored):
```
and it does not create a pull request with an automatic update
of documentation.
GitHub token has to be stored in the 'GITHUB_TOKEN' environment variable,
so that authentication of the 'hub' command worked correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4621)
=> common: fix automatic gh-pages docs update

utils/docker/run-coverity.sh
Skip running Coverity build on forked repos
if `COVERITY_SCAN_TOKEN` or `COVERITY_SCAN_NOTIFICATION_EMAIL` is not set,
because those variables have to be set in Coverity build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4630)
=> common: check if Coverity build can be run on forked repos

src/benchmarks/pmembench.vcxproj, src/common/libpmemcommon.vcxproj, src/examples/libpmemblk/assetdb/asset_checkin.vcxproj.filters, src/examples/libpmemblk/assetdb/asset_checkout.vcxproj.filters, src/examples/libpmemblk/assetdb/asset_list.vcxproj.filters, src/examples/libpmemblk/assetdb/asset_load.vcxproj.filters, src/libpmem2/libpmem2.vcxproj, src/libpmem2/libpmem2.vcxproj.filters, src/test/blk_non_zero/blk_non_zero.vcxproj, src/test/blk_pool/blk_pool.vcxproj, src/test/blk_pool_lock/blk_pool_lock.vcxproj, src/test/blk_rw/blk_rw.vcxproj, src/test/blk_rw_mt/blk_rw_mt.vcxproj, src/test/obj_persist_count/obj_persist_count.vcxproj.filters, src/test/pmem2_config/pmem2_config.vcxproj, src/test/pmem2_config/pmem2_config.vcxproj.filters, src/test/pmem2_source_size/pmem2_source_size.vcxproj, src/test/pmem2_source_size/pmem2_source_size.vcxproj.filters, src/windows/srcversion/srcversion.vcxproj
U+FEFF is an annoying dropping that MSVC adds.  Let's keep it consistent to avoid mysterious diffs with seemingly unchanged lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4631)
=> add BOMs to Windows stuff

.github/workflows/coverity.yml, .github/workflows/gha.yml
It fixes the following bug:
https://github.com/actions/checkout/issues/23
occurring recently in PMDK GHA builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4647)
=> common: bump GHA checkout action to v2

src/test/unittest/unittest.sh
Replace the 'arch' command with 'uname -m',
because the 'arch' command is not available by default
on all Linux distros.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4639)
=> common: replace 'arch' command with 'uname -m'

.github/workflows/coverity.yml, .github/workflows/gha.yml, .travis.yml, doc/RELEASE_STEPS.md, utils/docker/README, utils/docker/build-CI.sh
Rename 'build-travis.sh' to 'build-CI.sh'
and note that this script is used for building PMDK
on Travis and GitHub Actions CIs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4612)
=> common: rename build-travis.sh to build-CI.sh

src/test/pmempool_sync/TEST32, src/test/pmempool_sync/TEST33, src/test/pmempool_sync/TEST34, src/test/pmempool_sync/TEST35, src/test/pmempool_sync/TEST36, src/test/pmempool_sync/TEST37, src/test/pmempool_sync/TEST42, src/test/pmempool_sync/TEST43, src/test/pmempool_sync/TEST44, src/test/pmempool_sync/TEST45, src/test/pmempool_sync/TEST46, src/test/pmempool_sync/TEST47, src/test/pmempool_sync/TEST48, src/test/pmempool_sync/TEST49, src/test/pmempool_sync/TEST50, src/test/pmempool_sync/TEST51, src/test/pmempool_sync/TEST52, src/test/pmempool_sync/TEST53, src/test/pmempool_sync/setup.sh, src/test/pmempool_sync_remote/TEST26, src/test/pmempool_sync_remote/TEST27, src/test/pmempool_sync_remote/TEST28, src/test/pmempool_sync_remote/TEST29, src/test/pmempool_sync_remote/TEST30, src/test/pmempool_sync_remote/TEST31, src/test/unittest/unittest.sh
The pmempool_sync bad block tests for non-pmem medium
needs to take care on offset and zero size calculations.
The zero_blocks offsets and sizes used for 4K page size
systems create overlapping blocks in 64K page size systems.
This commit add a utility calculation for this test cases
to round the offset and zero sizes to avoid overlapped
blocks for systems running with page sizes different from
4K.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4627)
=> test: Fix pmempool_sync non-pmem cases for ppc64le

src/test/unittest/tools.py
This made us test the wrong version if there's anything installed on the system.
Ref #4359
The LD_LIBRARY_PATH still gets multiple copies, but that's a cosmetic problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4651)
=> pytest: use proper (in-tree) libs rather than system ones

src/include/libpmemobj/action_base.h, src/libpmemobj/palloc.c, src/libpmemobj/tx.c
Reading metadata of a persistent allocation is almost
always a guaranteed cache miss, so we should avoid doing
so whenever possible.
This patch removes a usable size check from transactional
allocations, avoiding one extraneous cache miss.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4657)
=> obj: optimize transactional allocation

src/test/pmem2_integration/pmem2_integration.c, src/test/pmem2_integration/pmem2_integration.vcxproj, src/test/pmem2_integration/pmem2_integration.vcxproj.filters, src/test/pmem2_map/pmem2_map.c, src/test/pmem2_map/pmem2_map.vcxproj, src/test/pmem2_map/pmem2_map.vcxproj.filters, src/test/pmem2_source_alignment/pmem2_source_alignment.c, src/test/unittest/ut_pmem2_config.c, src/test/unittest/ut_pmem2_config.h
To reproduce: memmap=4G! with (default) align of 2M, after headers/etc this gives 2015 pages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4652)
=> fix test fails when devdax has an odd number of pages

src/core/util.c
Real Fletcher64 uses modulos UINT32_MAX in the loop. We can't change
our implementation to follow the real Fletcher64, because it would break
some (~1/2^32) existing pmem pools.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4662)
=> common: util_checksum does not implement Fletcher64

.travis.yml
Travis' build config validation complains about these:
root: deprecated key sudo (The key `sudo` has no effect anymore.)
env: key matrix is an alias for jobs, using jobs
root: key matrix is an alias for jobs, using jobs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4678)
=> common: resolve Travis' build config issues

src/test/tools/obj_verify/obj_verify.c
The pmempool_sync_remote/TEST29 and TEST31 tests
sometimes timeouts, because obj_verify runs too long.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4720)
=> test: speed up obj_verify

src/libpmem2/x86_64/memcpy/memcpy_avx.h, src/libpmem2/x86_64/memcpy/memcpy_sse2.h, src/libpmem2/x86_64/memset/memset_avx.h, src/libpmem2/x86_64/memset/memset_sse2.h
To limit the number of used instructions, mem[move|set]_small_*
can store to part of memory twice (for example, they do 2 overlapping
8-byte stores for 15-byte copy).
This confuses pmemcheck's double store checks, which leads to
"overwritten stores before they were made persistent"
warnings.
Avoid that by redirecting small/unaligned mem[move|set] to generic
implementation, when executed under pmemcheck.
Before this patch, it's possible to reproduce this problem by running
obj_list_valgrind test with PMEM_AVX=1.
Note: libc's memcpy does similar optimizations, so it's still possible
to reproduce this problem by running  obj_list_valgrind test with
PMEM_NO_GENERIC_MEMCPY=1 PMEM_NO_MOVNT=1. This code path is undocumented
and exists only for comparisons of memcpy implementations, so we
can …
=> pmem2: (+pmem) avoid triggering harmless warning under pmemcheck

src/test/testconfig.py.example
fs_dir_force_pmem is not used no longer in test framework.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4734)
=> test: remove fs_dir_force_pmem field in testconfig.py.example

src/test/rpmem_addr_ext/TEST0
It cannot work on nondebug builds, because it matches logs, which are
generated only in debug builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4742)
=> test: fix rpmem_addr_ext test

src/core/util.h, src/libpmem2/x86_64/memcpy/memcpy_nt_avx.c, src/libpmem2/x86_64/memcpy/memcpy_nt_avx512f.c, src/libpmem2/x86_64/memcpy/memcpy_nt_sse2.c, src/libpmem2/x86_64/memcpy/memcpy_t_avx.c, src/libpmem2/x86_64/memcpy/memcpy_t_avx512f.c, src/libpmem2/x86_64/memcpy/memcpy_t_sse2.c, src/libpmem2/x86_64/memset/memset_nt_avx.c, src/libpmem2/x86_64/memset/memset_nt_avx512f.c, src/libpmem2/x86_64/memset/memset_nt_sse2.c, src/libpmem2/x86_64/memset/memset_t_avx.c, src/libpmem2/x86_64/memset/memset_t_avx512f.c, src/libpmem2/x86_64/memset/memset_t_sse2.c
Some compilers do some silly reordering which sadly affects CPU
ability to use write-combining buffers.
---
The first patch is a cleanup and doesn't change any generated code.
The second patch is the actual change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4746)
=> pmem: (+pmem2) insert compiler barriers after NT stores

appveyor.yml
Image version change is needed for VirtualAlloc2 function. Sort check is done on gh actions. Appveyor with image 2019 has a problem with our sorting perl script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4747)
=> common: change appveyor image version to 2019 and delete sln sort check

src/test/unittest/unittest.h
The command:
```
UT_ASSERTinfo_rt(0 == 1, "text");
```
prints out two messages now:
```
Error: assertion failure: 0 == 1 ("text" = text)
```
and with this patch only one:
```
Error: assertion failure: 0 == 1 (text)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4752)
=> test: fix UT_ASSERTinfo_rt() macro

src/libpmem2/extent_linux.c
This redundant NULL-check misleads readers and static code analyzers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4762)
=> pmem2: remove redundant NULL-check

src/libpmem2/badblocks_ndctl.c
Fix regression in badblocks_get() introduced by the commit 831d125.
Now (b773100) the condition in the line no. 628 looks like:
```
if (bb_found > 0) {
```
Earlier, before the commit 831d125, it looked like:
```
if (extents > 0 && bb_found > 0) {
```
so it was false for DAX devices (which have no extents).
Now the array of bad blocks in a DAX device (bbs) is cleared
and zeroed in the above 'if' condition (lines no. 629-630)
by being assigned to the empty in this case 'bbv' vector.
This patch adds the new `exit_free_exts` label,
so this 'if' condition is skipped for DAX devices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4764)
=> pmem2: fix regression in badblocks_get()

utils/style_check.sh
envconfig.py is an autogenerated file and it can have
too long lines inside:
```
envconfig.py:6:80: E501 line too long (104 > 79 characters)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4771)
=> common: exclude envconfig.py from style checking

src/test/obj_fragmentation2/Makefile, src/test/obj_fragmentation2/TESTS.py, src/test/obj_fragmentation2/obj_fragmentation2.c
This is a test designed mostly for longer running tests
with larger pools. The intention is to use a large amount of
different allocation classes, and stress the recycler module
of the allocator so that it has to constantly look for new
runs to reuse.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4744)
=> obj: implement new fragmentation test with highly variable sizes

src/libpmem2/x86_64/cpu.c, src/libpmem2/x86_64/cpu.h, src/libpmem2/x86_64/init.c, src/libpmem2/x86_64/memcpy/memcpy_nt_avx.c, src/libpmem2/x86_64/memcpy/memcpy_nt_sse2.c, src/libpmem2/x86_64/memcpy_memset.h, src/libpmem2/x86_64/memset/memset_nt_avx.c, src/libpmem2/x86_64/memset/memset_nt_sse2.c, src/test/pmem2_mem_ext/TESTS.py, src/test/pmem2_memcpy/TESTS.py, src/test/pmem2_memset/TESTS.py
I recommend looking at each patch individually to get the overall idea. The second patch ("pmem: (+pmem2) make WC issue workaround optional") is the messiest, but the least interesting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4774)
=> pmem/pmem2: optimize NT mem[cpy|set] for SSE2 and AVX

src/libpmem2/badblocks_ndctl.c
It fixes possible NULL-pointer dereference
in pmem2_badblock_context_delete().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4784)
=> pmem2: fix possible NULL-pointer dereference

src/libpmem2/aarch64/arm_cacheops.h
Explain what's an Inner Shareable domain.  Correct wrongness.
Links:
* a [LKML thread](https://lore.kernel.org/linux-arm-kernel/20200323123524.w67fici6oxzdo665@mail.google.com/T/#u)
* book: [ARM DDI 0487E.a](https://static.docs.arm.com/ddi0487/ea/DDI0487E_a_armv8_arm.pdf?_ga=2.164266557.306569205.1570439925-2017736311.1569857310) page B2-144
Note that the distinction between "full coherency" and "IO coherency" affects hardware implementors but not us (if I read things correctly...).
Per Janek's question about whether RDMA needs explicit flushes for global observability.  I'm not 100% sure about whether this is an adequate answer, but this should be a step forward.
--- …
=> corrections to docs about ARM64 cache coherency

doc/libpmemobj/pmemobj_tx_begin.3.md, src/include/libpmemobj/tx_base.h, src/libpmemobj/libpmemobj.def, src/libpmemobj/libpmemobj.link.in, src/libpmemobj/tx.c, src/test/obj_tx_add_range/obj_tx_add_range.c, src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c, src/test/obj_tx_alloc/obj_tx_alloc.c, src/test/obj_tx_flow/obj_tx_flow.c, src/test/obj_tx_free/obj_tx_free.c, src/test/obj_tx_lock/obj_tx_lock.c, src/test/obj_tx_strdup/obj_tx_strdup.c, src/test/obj_ulog_size/obj_ulog_size.c, src/test/obj_ulog_size/out0.log.match, src/test/obj_ulog_size/out1.log.match, src/test/obj_ulog_size/out2.log.match, src/test/scope/out11.log.match, src/test/scope/out5.log.match
This function can be used to disable or enable aborting tx
in case of an error (for example when allocation fails).
This patch also introduces pmemobj_tx_is_abort_on_failure
which allows to query current setting of a transaction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4654)
=> obj: introduce pmemobj_tx_set_abort_on_failure

src/tools/pmreorder/loggingfacility.py
It fixes the following 'make cstyle' error:
```
loggingfacility.py:71:26: F999 '...'.format(...) has unused arguments at position(s): 0
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4782)
=> pmreorder: fix a cstyle error

.github/workflows/gha.yml
stock Powershell does not interpret shebang to detect python as a
interpreter of the RUNTESTS.py script. For some reason powershell on
Appveyor understands shebangs but powershell on github actions doesn't.
This patch is fixing that python Windows tests are not ran on github.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4792)
=> common: python tests should be run through python in powershell

doc/Makefile
Makefile files do not take into account the order of executed
commands. As a result pmem2 documentation is installed twice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4783)
=> doc: fix pmem2 documentation installation

src/libpmemobj/alloc_class.c, src/libpmemobj/alloc_class.h, src/libpmemobj/heap.c, src/libpmemobj/memblock.c, src/libpmemobj/memblock.h, src/libpmemobj/pmalloc.c
Recalculating bitmap information was one of the most costly
operations performed during allocation. This patch eliminates
that cost by caching the bitmap data in the allocation class
instance, eliminating the need for costly computations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4773)
=> obj: cache run bitmap data for use during allocation

src/examples/libpmemobj/tree_map/rtree_map.c
Fixes warning
rtree_map.c:358:12: error: 'child_idx' may be used uninitialized in this function [-Werror=maybe-uninitialized]
Signed-off-by: Khem Raj <raj.khem@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4802)
=> examples: Initialize child_idx

src/libpmem2/badblocks_ndctl.c, src/libpmem2/region_namespace_ndctl.c, src/libpmem2/usc_ndctl.c
ndctl_new() does not set errno, it returns it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4808)
=> pmem2: fix error handling of ndctl new()

doc/libpmem2/pmem2_config_new.3.md
There is no description of libpmem2 error codes in libpmem2(7) manual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4807)
=> doc: remove a false sentence from pmem2_config_new(3) manual

src/test/unittest/valgrind.py
Fix the following flake8 v3.8.1 errors:
./valgrind.py:230:33: E741 ambiguous variable name 'l'
./valgrind.py:241:62: E741 ambiguous variable name 'l'
./valgrind.py:242:40: E741 ambiguous variable name 'l'
They occurred after the last update of flake8 to v3.8.1
(mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0)
CPython 3.8.2 on Linux
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4815)
=> test: fix flake8 v3.8.1 errors in valgrind.py

src/test/Makefile, src/test/pmem2_badblock_mocks/TESTS.py, src/test/testframework.py, src/test/unittest/ctx_filter.py, src/test/unittest/requirements.py
The pmem2_badblock_mocks test includes 'ndctl/libndctl.h',
so it requires libndctl to be enabled and installed in OS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4806)
=> test: compile and run pmem2_badblock_mocks only if ndctl is enabled and installed

src/test/RUNTESTS.py
The 'c' context has to be initilized before the 'for' loop,
because cf.get_contexts() can return no value ([])
and in case of the 'futils.Fail' exception
self._test_failed(tc, c, f) will be called
with uninitilized value of the 'c' context:
```
[...]
raise futils.Fail('Error: ...')
futils.Fail: Error: ...
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "./RUNTESTS.py", line 172, in <module>
main()
File "./RUNTESTS.py", line 168, in main
sys.exit(runner.run_tests())
File "./RUNTESTS.py", line 110, in run_tests
self._test_failed(tc, c, f)
UnboundLocalError: local variable 'c' referenced before assignment
```
--- …
=> test: fix run_tests() in RUNTESTS.py

src/test/obj_fragmentation2/obj_fragmentation2.c
In some cases, statistics: active and allocated can be equal to 0,
and it should be checked
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4821)
=> test: fix in obj_fragmentation2 test

src/libpmem2/pmem2_utils.c, src/test/pmem2_perror/pmem2_perror.c
Translate always the PMEM2_E_NOSUPP error into the ENOTSUP errno.
It will help handle this error on OSes, where some features
are not supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4827)
=> pmem2: always translate PMEM2_E_NOSUPP into ENOTSUP

src/core/out.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4833)
=> core: fix Last_errormsg_get when NO_LIBPTHREAD is defined

src/core/util.c
_On_drd is defined only if VG_DRD_ENABLED is defined and
_On_helgrind is defined only if VG_HELGRIND_ENABLED is defined.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4834)
=> core: fix _On_drd_or_hg in util_init()

src/libpmem/ppc64/.cstyleignore, src/libpmem/ppc64/platform_generic.c
The dcbst instruction doesn't flush a cache block correctly because it
doesn't mark that block as clean on Power 9, see Manual "POWER9
Processor User’s Manual" page 66.
Replace dcbst with dcbf in order to fix this issue. This change requires
to replace lwsync with a hwsync too in order to cover for the usage of dcbf.
Adopt the best practices according to the POWER ISA 3.1.
Fix #4843 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4844)
=> Fix data cache flush on ppc64

src/common/ravl.c, src/libpmem2/Makefile, src/libpmem2/libpmem2.vcxproj, src/libpmem2/libpmem2.vcxproj.filters, src/libpmem2/map.c, src/libpmem2/ravl_interval.c, src/libpmem2/ravl_interval.h, src/test/Makefile.inc, src/test/pmem2_granularity/pmem2_granularity.vcxproj, src/test/pmem2_granularity/pmem2_granularity.vcxproj.filters, src/test/pmem2_map/pmem2_map.vcxproj, src/test/pmem2_map/pmem2_map.vcxproj.filters, src/test/pmem2_map_prot/pmem2_map_prot.vcxproj, src/test/pmem2_map_prot/pmem2_map_prot.vcxproj.filters, src/test/util_sds/util_sds.vcxproj, src/test/util_sds/util_sds.vcxproj.filters
Move ravl map module implementation from map.c into separate files
map_ravl.c and map_ravl.h. Effectively map.c uses map_ravl structure
to keep track of the mappings in the ravl tree.
The reason for the separation is that the pmem2_vm_reservation feature
will be using ravl tree in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4813)
=> pmem2: separate ravl map module and map.c

src/libpmem2/ppc64/init.c
The ppc64le port should no longer be considered experimental.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4863)
=> pmem2: remove experimental message from ppc64le port

utils/docker/images/install-valgrind.sh
The recent change on flush instructions on power triggers a bug on
valgrind. The newest valgrind version 3.16.1 already have a patch for
this so, for now, we are changing to use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4876)
=> test: change valgrind version for PPC64LE

src/libpmem2/ppc64/init.c
This caused more issues then it solved... The CI environment simply
has to have a new enough valgrind.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4875)
=> pmem2: (+pmem) revert ppc64 workaround for valgrind

GIT_VERSION
I messed up restoring GIT_VERSION after a release...
I'm doing this through a PR so that I can be sure that CI builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4879)
=> common: fix GIT_VERSION string

libpmem/index.md
pmem_drain() is almost always an sfence...
Reported-by: Steve Heller <steve@steveheller.org>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4877)
=> doc: fix an inaccuracy in libpmem docs

src/libpmempool/sync.c, utils/cstyle
Make cstyle error out on extra space before or after ++/-- operators.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4887)
=> common: error out on extra space before or after ++/-- operators

doc/libpmemobj/libpmemobj.7.md
it was leading to the sub-section of Synopsis, instead of the proper section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4901)
=> doc: fix link in libpmemobj.7.md

src/benchmarks/pmembench_memset.cfg
Fix test name from pmem_memset_libc_memset_persist to pmem_memset_libc_memset_msync.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4893)
=> benchmark: fix memset scenario name

src/common.inc
If BUILD_RPMEM is set, LIBFABRIC_* are not set up by common.inc and cause rpmemd to fail building
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4912)
=> common: fix LIBFABRIC flags

src/libpmem2/deep_flush_linux.c, src/test/pmem2_integration/TESTS.py, src/test/pmem2_integration/pmem2_integration.c
Deep flushing uses msync, which requires address
to be page aligned. In our API, we usually round
down the address and increase the flushing length.
This wasn't done for deep flush, which caused failures
on unaligned deep flushes.
This patch simply copies the alignment mechanism from the
same functionality used in the persist.c file. Ideally,
we'd abstract this into its own method that then calls
msync. But the code is simple enough, and I decided not
to introduce extra complexity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4891)
=> pmem2: fix non-page-aligned deep flushes

src/libpmem2/map_posix.c
This was raported by coverity as use-after-free, but I think
it's unlikely to be a real problem. But the fix is simple enough...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4909)
=> pmem2: deregister valgrind mapping prior to unmap

doc/libpmem2/libpmem2.7.md
This is the easiest way to fix:
10:32:09,450 WARN  - libpmem2.7: <standard input>:109: warning [p 2, 4.3i]: can't break line
10:32:09,735 WARN  - make: *** [check-doc] Error 123
In fact, we do not use full page links anywhere in .md files. It was the only place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4919)
=> doc: fix too long line in the libpmem2.7 man

src/libpmem2/badblocks_ndctl.c
-Og enables some basic flow tracking, so this warning is enabled, yet the flow tracking is not yet deep enough to notice this can't actually happen.  Then, -Werror makes the build fail.
Got this on arm64 Debian unstable, doesn't repro on x86.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4928)
=> fix build with -Og on some platforms

src/test/drd-log.supp, src/test/helgrind-log.supp
Fixes fails on arm64 and ppc64.
The mem*cpy part is obvious; I don't fully understand why out_err is needed — somehow valgrind requires both sides to be suppressed.
Closes #4926
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4931)
=> update valgrind suppressions for new glibc

src/test/unittest/basetest.py
basetest.py:265:13: E741 ambiguous variable name 'l'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4934)
=> test: fix cstyle issue in py testframework

src/libpmem2/map_posix.c
Reservation region should be unmapped only when it wasn't provided
by the config, otherwise the job of cleaning up the reservation is
up to the invoking layer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4940)
=> pmem2: fix munmap when file mapping fails (posix)

src/benchmarks/clo.cpp, src/core/os_thread_windows.c, src/libpmemobj/heap.c, src/test/pmem2_map_prot/pmem2_map_prot.c, src/test/pmem2_memcpy/memcpy_common.c, src/test/tools/bttcreate/bttcreate.c, src/test/tools/pmemobjcli/pmemobjcli.c, src/test/unittest/ut.c, src/test/util_ctl/util_ctl.c
Thanks to Andrey Karpov and PVS-Studio for doing a thorough analysis of PMDK:
https://viva64.com/en/b/0756/
Even though we run two different static analysis tools and many runtime checkers, PVS-Studio managed to catch a couple of issues. The good news is that most of the problems were in tests or examples.
I didn't address the missing memory allocation error handling because while I 100% agree that library code should definitely handle all possible recoverable errors correctly, we usually omi extraneous error handling in tools/tests or benchmarks for the sake of brevity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4942)
=> Fix various issues reported by PVS-Studio analysis

utils/pmdk.spec.in
while building rpm packages for PMDK 1.9 on Fedora rawhide I encountered:
```
RPM build errors:
[91m    extra tokens at the end of %endif directive in line 160:  %endif #_pmem2_install
extra tokens at the end of %endif directive in line 570:  %endif # _with_fabric
extra tokens at the end of %endif directive in line 634:  %endif # _with_ndctl
Bad exit status from /var/tmp/rpm-tmp.dIyVYY (%build)
```
In other OSes it's treated just as warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4937)
=> endif clause in rpm spec file shouldn't have any inline comments

src/libpmemobj/heap.c, src/libpmemobj/memops.c, src/libpmemobj/tx.c, src/libpmemobj/ulog.c, src/test/obj_persist_count/out1.log.match, src/test/obj_reorder_basic/obj_reorder_basic.c, src/test/unittest/unittest.sh
This is a regression introduced in 5e137e0. That patch accidentally
modified the order in which huge chunk headers are updated, leading
to possible issue with failure atomicity where the chunk headers could
be inconsistent if a crash happened in between two header updates.
Closes #4945
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4947)
=> obj: fix pmreorder and two existing failure atomicity bugs

src/libpmem/ppc64/platform_generic.c
Typo broke ppc64le build.
Fix commit 28050429877321d0982a996ffe187f3f0f0a2fc5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4956)
=> pmem: Fix ppc64le build

src/test/README, src/test/unittest/basetest.py, src/test/unittest/unittest.ps1, src/test/unittest/unittest.sh
Signed-off-by: Michal Papinski <michalx.papinski@intel.com>
Issue:
At current version when we run tests for multiple build types, the logs will get overwritten. 
Solution:
To avoid loosing the log files I implemented feature to create directory tree for each specific build type inside the test group folder. When all the tests from specific group with specific build type will finish running, the logs will be moved to the proper folder.
Example logs:
https://github.com/pmem/pmdk/issues/4825
https://github.com/pmem/pmdk/issues/4715
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4895)
=> test: store logs in separate folders

doc/libpmem2/pmem2_map_new.3.md, src/libpmem2/map.c, src/libpmem2/map.h, src/libpmem2/map_posix.c, src/libpmem2/map_windows.c, src/libpmem2/vm_reservation.c, src/libpmem2/vm_reservation.h, src/libpmem2/vm_reservation_posix.c, src/libpmem2/vm_reservation_windows.c, src/test/pmem2_vm_reservation/TESTS.py, src/test/pmem2_vm_reservation/pmem2_vm_reservation.c
Due to possible races and bugs when mapping asynchronously to the
virtual memory reservation, rw_locks were added in the
pmem2_map_new/delete functions. Locks are invoked only when the
reservation is set in the config structure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4965)
=> pmem2: fix vm_reservation TEST29 bugs

src/libpmempool/check_sds.c, src/test/pmempool_check/TEST1.PS1, src/test/pmempool_check/TEST9.PS1
It seems like these checks are not necessary, and would prevent SDS from functioning in a situation where the pool was created with SDS enabled, but moved to a device without it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4996)
=> pool: remove sds extraneous

src/libpmem2/usc_ndctl.c
For PAPR devices ndctl_dimm_get_unique_id returns NULL which causes
strlen to trigger a SIGSEGV.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5027)
=> pmem2: Fix check ndctl_dimm_get_unique_id return before using it

.github/workflows/gha.yml
The old 'addPath' is depreciated now. For more details see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5054)
=> common: use special environment var in GHA for Windows' PATH

src/test/util_badblock/util_badblock.c
Otherwise, it fails on new toolchain (as in current Fedora rawhide).
Uninitialized const struct don't make any sense.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5081)
=> test: util_badblock: don't pass uninitialized attr

doc/libpmem/pmem_is_pmem.3.md
Since MAP_SYNC flag is already supported by XFS and EXT4,
pmem_is_pmem() can return true even if you use filesystem-dax.
So, we can fix the old description of its manual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5088)
=> doc: Fix the document of pmem_is_pmem(). It can be used for filesystem dax.

src/common/rand.c
During development, this was getentropy() which returns 0 on success
rather than number of bytes copied.  The wrong expectation results in
fallback to bad randomness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5098)
=> common: expect the correct return value from getrandom()

_data/releases_linux.yml, _data/releases_windows.yml
it seems Jekyll/JSON(?) treats 1.10 as it would have a trailing zero.
before: https://pmem.io/pmdk/manpages/linux/master/libpmem/libpmem.7.html
after: https://lukaszstolarczuk.github.io/pmdk/manpages/linux/master/libpmem/libpmem.7.html
(spot one difference ;) hint: look in the "shortcut" menu on the right-hand side)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5110)
=> [gh-pages] fix release tag for 1.10

src/common/uuid.c
One place has a sized array of chars, the other had a pointer to char.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5137)
=> fix uuid header mismatch

Makefile
`make clean`/`clobber` doesn't work well when switching branches (eg. it doesn't know about new files), and I type too carelessly to avoid losing the configs over and over again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5134)
=> "make gitclean" to nuke everything but configs

src/libpmem2/map_posix.c, src/test/pmem2_map/TESTS.py, src/test/pmem2_map/pmem2_map.c
We should ideally always try to align mappings to the largest possible
page size while taking into account the limitations of the
underlying source (e.g., devdax alignment)...
But instead of doing that, the existing code always forced
the smallest possible alignment for the source - unconditionally.
This patch fixes that by restoring the intended behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5143)
=> pmem2: don't force smaller alignment for fsdax mappings

utils/pmdk.spec.in
This is only a workaround, we'd want to get rid of the objcopy weirdness, but there's quite a bit of stuff to untangle.
Fixes #4938
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5150)
=> common: force no LTO for rpm build

src/core/ravl_interval.c
This function was supposed to return the earliest entry that overlaps
with the provided region (offset, offset + size).
It meets this criteria now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5146)
=> core: fix ravl_interval_find function

src/examples/libpmem2/Makefile, src/examples/libpmem2/ringbuf/.gitignore, src/examples/libpmem2/ringbuf/Makefile, src/examples/libpmem2/ringbuf/ringbuf.c, src/test/ex_libpmem2/Makefile, src/test/ex_libpmem2/TESTS.py
This example demonstrates the usage of the libpmem2 API
within a lock-free program.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5155)
=> examples: implement a ring buffer example for libpmem2

doc/libpmemset/pmemset_source_from_file.3.md, doc/macros.man
Replaced m4 macro for source_from_file function documentation (new macro is for char arg. as a second parameter)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5193)
=> doc: updated m4 macro for source_from_file function description

src/libpmem2/config.c, src/test/pmem2_map/pmem2_map.c
I removed file's size alignment when validating mapping fit into the file's size. After the change real size of the file is verified, instead of aligning-up this size (to the system's allocation granularity) before check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5194)
=> pmem2: removed file's size alignment during map fit check

src/common/file_posix.c, src/common/os_deep_linux.c, src/common/set.c, src/common/set_badblocks.c, src/core/os_posix.c, src/core/os_thread_posix.c, src/core/util_posix.c, src/libpmemobj/lane.c
_GNU_SOURCE is not for FreeBSD and defining it unconditionally lead
to conflicts with -Wunused-macros.
Wrap _GNU_SOURCE with !defined(__FreeBSD__) for now.
For src/core/util_posix.c, includes signal.h also.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5216)
=> Fix FreeBSD compilation when doing gmake

src/test/pmempool_sync/out6.log.match, src/test/pmempool_sync/out7.log.match, src/test/pmempool_transform/out7.log.match, src/test/pmempool_transform/out8.log.match, src/test/pmempool_transform/out9.log.match
For pmempool_sync and pmempool_transform tests, the lane offset is 0x2000 (8196) on
x86, while on PowerPC (64k page size), the lane offset will be 0x20000 (131072).
out7.log.match:34  Lanes offset             : 0x2000
out7.log:34        Lanes offset             : 0x20000
So replace 0x2000 with a $(nW).
Signed-off-by: Santosh Sivaraj <santosh@fossix.org>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5232)
=> Fix pmempool_sync/transform test failures on PowerPC

src/common/rand.c, src/libpmemobj/critnib.c
they seem redundant and it's partially required in vcpkg build, see:
https://github.com/microsoft/vcpkg/blob/master/ports/pmdk/remove-non-ascii-character.patch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5247)
=> common: update comments to get rid of non-ascii characters

src/test/obj_action/memcheck1.log.match, src/test/obj_memcheck/memcheck0.log.match, src/test/obj_tx_add_range/memcheck3.log.match, src/test/obj_tx_add_range_direct/memcheck2.log.match
There are released distributions with gcc 11 but valgrind <3.17; as gcc11
defaults to DWARF5 but valgrind can't read it yet, this results in valgrind
reporting function names but not source lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5248)
=> test: don't fail if valgrind can't resolve source lines

src/test/unittest/unittest.sh
On arm64, cores in the same system can have different caches (typically in
big.LITTLE).  Assuming the worse-case (ie, 64 bytes) ensures correctness
at the cost of some performance -- this is what our actual code does.  On
the other hand, tests insist on reading this data from hard-coded path of
CPU0's coherency_line_size; this file is not present on ARM, causing the
test framework to spew a massive number of warnings.
https://www.mono-project.com/news/2016/09/12/arm64-icache/ tells a tale
that gives interesting caveats, like eg. reading the value at runtime
being a Wrong Thing unless you pin your thread to identical cores only.
If someone wants to optimize this, patches welcome!  For now, I'm only
making the tests correct and non-spammy.
---
This change is [<img …
=> test: don't spam warnings if cacheline size can't be determined

src/libpmem2/aarch64/arm_cacheops.h, src/libpmem2/aarch64/flush.h, src/libpmem2/aarch64/init.c
You need to use Point-of-Persistency flushes, defined specifically for our use case.  This instruction has been split so Point-of-Coherency could be made lighter.
The documentation is clear here, and it's an obvious data loss bug, but no one of us had access to an ARMv8.2 machine to test before.  No help has been offered by ARM (in stark contrast to IBM with ppc) thus there's no official support for PMDK on arm64 — but not flushing is severe enough to be fixed even in experimental code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5257)
=> fix insufficient flushing on ARMv8.2+

src/libpmem2/aarch64/init.c
On Aarch64 platform, if the building is running on the Linux kernel which is previous than 4.14, it can not recognize the HWCAP_DCPOP feature.
So it's better to define it first to avoid the build failure.
Signed-off-by: Kevin Zhao <kevin.zhao@linaro.org>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5270)
=> Add HWCAP_DCPOP if not defined to avoid build failure

README.md, utils/build-dpkg.sh
We already have BUILD_RPMEM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5279)
=> drop RPMEM_DPKG + obsolete doc

doc/libpmemobj/pmemobj_ctl_get.3.md, src/libpmemobj/heap.c, src/libpmemobj/heap.h, src/libpmemobj/pmalloc.c, src/test/obj_ctl_arenas/TEST10, src/test/obj_ctl_arenas/TEST10.PS1, src/test/obj_ctl_arenas/obj_ctl_arenas.c
This PR has two separate patches.
1. `obj: lazily initialize recycler` - moves the initialization of recyclers (which can be quite big) to first use.
2. `obj: add heap.arenas_default_max global ctl` - allows applications to reduce the number of arenas, which will reduce memory use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5280)
=> obj: main memory consumption optimizations

src/common/uuid.c, src/core/util.h, src/libpmem2/x86_64/memcpy/memcpy_nt_avx.c, src/libpmem2/x86_64/memcpy/memcpy_nt_avx512f.c, src/libpmem2/x86_64/memcpy/memcpy_nt_sse2.c, src/libpmem2/x86_64/memset/memset_nt_avx.c, src/libpmem2/x86_64/memset/memset_nt_avx512f.c, src/libpmem2/x86_64/memset/memset_nt_sse2.c
The implementation of hardware fencing for non-temporal
memcpy variants is done using a function pointer. Some
of those pointers were called "barrier" which unfortunately
overlaps with a function-like macro that's used for compiler
barriers. This meant that a compiler barrier was being used
instead of a hardware store barrier.
This patch changes the compiler barrier to a static inline
function called "compiler_barrier" to avoid name conflicts.
Fixes #5292
Reported-by: @Transpeptidase
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5293)
=> common: fix missing sfence in non-temporal memcpy

utils/pkg-common.sh
AlmaLinux and Rocky Linux suppose to be a CentOS replacements,
since it is EOL-ing soon (at least in current form).
// tested it on my branch, on pmemkv using AlmaLinux and it worked just fine: https://github.com/lukaszstolarczuk/pmemkv/runs/3526201154?check_suite_focus=true#step:4:12939
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5304)
=> common: update rpm building script for new RHEL like OSes

src/common.inc
This may be a bit trivial, but when there are missing packages in build, I'm always a bit annoying to find the right package due to the difference package names among each distributions. I suppose that error message need to display the package names of RHEL which are ndctl-devel and daxctl-devel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5306)
=> common: Add package name of RHEL for ndctl and daxctl library on build error

README.md, src/Makefile.inc, src/common/pool_hdr.c, src/common/pool_hdr.h, src/core/page_size.h, src/core/util.h, src/core/valgrind_internal.h, src/examples/libpmem2/redo/redo.c, src/include/libpmemblk.h, src/libpmem2/riscv64/flags.inc, src/libpmem2/riscv64/init.c, src/libpmem2/riscv64/rv_cacheops.h, src/libpmem2/riscv64/sources.inc, src/test/pmem_deep_persist/Makefile, src/test/pmem_is_pmem_posix/Makefile
Thanks to cacheline/page sizes matching those of x86 and usual arm64 (pages are 4K/2M/1G/512G), all structs work unmodified, and the port Just Works, after adding an implementation of barriers, filing in magic numbers, and updating Makefiles.
The only oddity comes from the ISA designers being strongly opposed to any cache control from user code — their design for persistent memory is to require CPU caches being power fail protected.  This is the new mode supported by PMDK; cacheline granularity is impossible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5265)
=> riscv port

src/libpmemobj/tx.c
When valgrind is disabled there is error caused by
'-Wunused-parameter' flag in vg_verify_initialized.
Change-Id: I8c511974c2372baea64442c15a589b7a4684487f
Signed-off-by: Jun He <jun.he@arm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5321)
=> common: supress false positve of '-Wunused-parameter'

src/libpmem2/riscv64/init.c, src/test/libpmempool_bttdev/TEST11, src/test/libpmempool_bttdev/TEST3, src/test/libpmempool_bttdev/TEST4, src/test/libpmempool_bttdev/TEST5, src/test/libpmempool_bttdev/TEST6, src/test/pmempool_check/TEST5, src/test/pmempool_info/out27.log.match, src/test/unittest/unittest.sh, src/tools/pmempool/output.c
Three more issues popped up:
* `-Wunused-parameter` broke the build
* a pmempool test revealed that its info lacked the arch name
* tests with large sparse allocations won't fit within a sv39 (ie, 3-level page) model
The latter two tests were apparently skipped before, and got unblocked once I improved either the running kernel or disk space (I've replaced a shiny 16GB Optane NVMe with a boring legacy 250GB piece...).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5322)
=> riscv fixes

src/test/helgrind-log.supp
In this episode of helgrind failures, 2021 season, our star is ppc64el on Debian unstable, which has just got its glibc bumped to 2.32 (and aurel is going to upload 2.33 then 2.34 soonish...).  Here, fun:fputs is somehow missing from the backtrace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5328)
=> add a yet another helgrind suppression

src/libpmemobj/tx.c, src/test/obj_ulog_size/obj_ulog_size.c, src/test/obj_ulog_size/out0.log.match, src/test/obj_ulog_size/out1.log.match, src/test/obj_ulog_size/out2.log.match
Ref: pmem/issues#5291
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5326)
=> obj: fix invalid type when setting cache size ctl

src/test/pmreorder_simple/pmreorder0.log.match, src/test/pmreorder_simple/pmreorder3.log.match, src/test/pmreorder_stack/pmreorder0.log.match, src/tools/pmreorder/binaryoutputhandler.py, src/tools/pmreorder/consistencycheckwrap.py, src/tools/pmreorder/memoryoperations.py, src/tools/pmreorder/operationfactory.py, src/tools/pmreorder/opscontext.py, src/tools/pmreorder/pmreorder.py, src/tools/pmreorder/statemachine.py
Debug logs in pmreorder are rather empty right now. This PR extends and adds lots of new logs.
// example log output for failing test: [example.pmreorder.txt](https://github.com/pmem/pmdk/files/7363606/example.pmreorder.txt)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5348)
=> pmreorder: add more debug/info logs

src/test/pmem2_badblock/TESTS.py, src/test/pmemset_badblock/TESTS.py, src/test/unittest/badblock.py, src/test/unittest/devdax.py, src/test/unittest/granularity.py, src/test/unittest/requirements.py, src/test/unittest/tools.py
Added new require_real_pmem decorator.
When require_real_pmem parameter is set on the test case then every
pmem device that would be used in ths test case is checked to be
real, non-emulated pmem. Devdaxes and fsdaxes are both checked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5356)
=> test: add real pmem requirement to test framework

src/core/out.h
We currently use attribute((noreturn)) for empty asserts
in release builds, primarly to placate static analysis tools.
Until recently, this worked just fine. Lately klocwork started
reporting false-positives, seemingly ignoring any asserts in
the code.
This patch uses real asserts for release build that are used
for evaluation under klocwork.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5388)
=> common: use real asserts under klocwork

src/test/unittest/ut_file.c
```
ut_file.c: In function ‘ut_fclose’:
ut_file.c:92:17: error: pointer ‘stream’ may be used after ‘fclose’ [-Werror=use-after-free]
92 |                 ut_fatal(file, line, func, "!fclose: 0x%llx",
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
93 |                         (unsigned long long)stream);
|                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5400)
=> don't access the address of a FILE after fclose

utils/docker/build-CI.sh
The new website needs the man pages to be pushed directly
to pmem.github.io repository, and the markdown docs need to have
a slightly different format.
For now, this patch only disables docs updates to unblock builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5402)
=> common: disable auto doc updates

src/libpmemobj/bucket.c, src/libpmemobj/bucket.h, src/libpmemobj/heap.c, src/libpmemobj/heap.h, src/libpmemobj/memblock.h, src/libpmemobj/palloc.c, src/libpmemobj/pmalloc.c, src/test/obj_bucket/obj_bucket.c, src/test/obj_heap/obj_heap.c
This patch cleans up the previously leaky bucket
abstraction layer in preparation for heap segmentation.
Proper bucket locking is now enforced at the type level,
so it's easier to use and modify.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5230)
=> obj: refactor bucket abstraction

src/test/unittest/ut_file.c
```
ut_file.c: In function ‘ut_fclose’:
ut_file.c:92:17: error: pointer ‘stream’ may be used after ‘fclose’ [-Werror=use-after-free]
92 |                 ut_fatal(file, line, func, "!fclose: 0x%llx",
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
93 |                         (unsigned long long)stream);
|                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5434)
=> test: don't use a FILE pointer after fclose

src/libpmem2/mover.c, src/libpmem2/persist.c, src/test/pmem2_future/pmem2_future.c
Right now pmem2_xyz_async family of functions don't use
VDM_F_MEM_DURABLE vdm flags, they merely check if they
are supported by the vdm. This might lead to a situation
where a vdm supports durable writes, but pmem2 doesn't
take advantage of that support, even when it should.
This patch addresses that by using the durable flag
whenever that's appropriate, and handling the flag
correctly in pmem2 mover implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5468)
=> pmem2: make sure async functions use proper vdm flags

src/Makefile.inc, src/common/Makefile, src/common/pmemcommon.inc, src/core/Makefile
A recent change tried to globally add a new flag
in the makefiles, which inadvertently caused
the build system to stop adding important
compile flags like '-O2'...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5488)
=> common: fix default cflags in makefiles

src/libpmem2/x86_64/init.c, src/libpmem2/x86_64/memset/memset_movdir64b.h, src/libpmem2/x86_64/sources.inc, src/test/pmem2_memcpy/TESTS.py, src/test/pmem2_memset/TESTS.py, src/test/pmem2_movnt/TESTS.py, src/test/pmem2_movnt_align/TESTS.py, src/test/pmem_memcpy/TESTS.py, src/test/pmem_memmove/TEST0, src/test/pmem_memmove/TEST0.PS1, src/test/pmem_memset/TEST0, src/test/pmem_memset/TEST0.PS1, src/test/pmem_movnt/TEST0, src/test/pmem_movnt/TEST0.PS1, src/test/pmem_movnt_align/TEST0, src/test/pmem_movnt_align/TEST0.PS1, src/test/pmem_movnt_align/TEST1, src/test/pmemset_memcpy/TESTS.py, src/test/pmemset_memmove/TESTS.py, src/test/pmemset_memset/TESTS.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5471)
=> pmem2: enable movdir64b compilation but disable it in the runtime

src/PMDK.sln, src/libpmemobj/heap.c, src/libpmemobj/heap.h, src/libpmemobj/palloc.c, src/test/Makefile, src/test/obj_heap_reopen/.gitignore, src/test/obj_heap_reopen/Makefile, src/test/obj_heap_reopen/TESTS.py, src/test/obj_heap_reopen/obj_heap_reopen.c, src/test/obj_heap_reopen/obj_heap_reopen.vcxproj, src/test/obj_heap_reopen/obj_heap_reopen.vcxproj.filters
This patch fixes a bug where free prior to any allocs,
combined with reservations, could have led to overlapping
allocations - which ultimately was causing corrupted heap
and incorrect statistics.
This problem is caused by lazy heap runtime state reclamation.
Heap runtime state is rebuilt lazily whenever required
to serve allocation requests. Deallocations (free) simply update
persistent metadata and, in case of huge allocations, inserts
the freed chunk into a container of free chunks. On reclaim,
all free chunks not already deallocated are inserted into a freelist.
This would have been fine, but libpmemobj's allocator enables
software to reserve a chunk, removing it from the heap runtime state
without updating the persistent on-media layout.
This means that software can deallocate a …
=> obj: ensure zones are reclaimed prior to free (1.11)

doc/pmreorder/pmreorder.1.md, src/test/pmreorder_stack/pmreorder0.log.match, src/test/pmreorder_stack/pmreorder_stack.c, src/test/unittest/unittest.h, src/tools/pmreorder/opscontext.py, src/tools/pmreorder/pmreorder.py, src/tools/pmreorder/statemachine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5475)
=> Add information about state #5419

.github/workflows/gha.yml, utils/docker/images/Dockerfile.fedora-37
Update docker images to use Fedora 37.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5520)
=> common: use Fedora 37 version of docker images

src/test/tools/ddmap/Makefile, src/test/tools/pmemobjcli/Makefile, src/test/tools/pmemspoil/Makefile, src/test/tools/pmemwrite/Makefile, src/tools/Makefile.inc, src/tools/pmempool/Makefile
Fix dependencies with pmempool.
Not all tools that include 'src/tools/Makefile.inc' require linking with the common.o and output.o objects from pmempool. Only pmempool itself, ddmap, pmemobjcli, pmemspoil and pmemwrite tool require that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5521)
=> pool: fix dependencies with pmempool

utils/build-dpkg.sh
As of right now, compat level equal to 10 is adequate for:
- Debian 10 (Buster),
- Ubuntu 18.04 (bionic).
This change will eliminate warnings produced while preparing deb packages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5525)
=> common: bump compatibility level for debhelper

utils/docker/images/install-valgrind.sh
to include the latest fixes for ppc64 (merged into our pmem-3.20 branch).
// includes merged PR: https://github.com/pmem/valgrind/pull/90
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5530)
=> common: bump valgrind version

src/test/log_basic/out4.log.match, src/test/obj_list/obj_list.h, src/test/pmem_valgr_simple/pmem_valgr_simple.c, src/test/pmem_valgr_simple/pmemcheck0.log.match, src/test/pmempool_transform/out12.log.match, src/test/pmreorder_flushes/Makefile, src/test/pmreorder_flushes/pmreorder_flushes.c, src/tools/pmreorder/binaryoutputhandler.py
The pmemcheck works on ppc64le with https://github.com/pmem/valgrind/pull/90
Having that support, several tests on PMDK which were before failing need few tweaks in output, or ppc64le specific changes like pagesize(64k), cacheline size(128) or object lane offset(0x20000).
The pull request addresses these differences to get those tests working.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5518)
=> Revisit the tests with pmemcheck support on ppc64le

utils/check_license/check-headers.sh
It silents the following warnings:
grep: warning: * at start of expression
See: pmem/rpma@8dd612d
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5533)
=> common: remove unneeded '*' at start of expressions

src/Makefile.inc, utils/check-manpages
Few references to librpmem/rpmemd have been detected and removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5519)
=> common: remove remaining references to librpmem library

src/core/out.c
In order to survive and get an explicit message upon ENOMEM situation during logging, use a static generic message.
Ref: pmem/issues#5515
Signed-off-by: Bruno Faccini <bruno.faccini@intel.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5536)
=> core: handle ENOMEM gracefully during logging

src/tools/pmempool/common.c
This is flagged by clang 16+
common.c:844:4: error: cast from 'const char *(*)(enum chunk_type)' to 'enum_to_str_fn' (aka 'const char *(*)(int)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
(enum_to_str_fn)out_get_chunk_type_str);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5543)
=> pmempool: Match function prototypes of enum_to_str_fn function pointer

README.md, src/test/README, src/test/unittest/requirements.py
ndctl-related tests explicitly fail if ndctl is not installed instead of RUNTESTS.py script crash
Fixes: #5554
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5559)
=> test:  fail pmem tests if ndctl is not installed

utils/docker/build-CI.sh
The approach, when we run Coverity along other tests is long gone. Now various build can be run on cron jobs, and run-coverity.sh is now only executed in a separate workflow.
This cleanup enables Nightly jobs to run properly (now they are skipped).
// example skip in Nightly: https://github.com/pmem/pmdk/actions/runs/4549226087/jobs/8021078686#step:4:24
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5563)
=> common: omit checks for 'cron' jobs in build-CI.sh

utils/check_docs/exceptions.txt
// without this fix - the CI is failing: https://github.com/pmem/pmdk/actions/runs/4580274940/jobs/8088859857#step:5:26
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5569)
=> common: add win_depr_* defines to split_manpage_test's exceptions

utils/docker/run-build.sh
All tests shall be run sequentially to eliminate any interference between tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5572)
=> test: avoid parallel tests execution

utils/docker/images/Dockerfile.opensuse-leap-15
- fdupes was missing as a dependency for packaging,
- libndctl-devel is available in version 71.1 - use this one,
- minor cleanup.
// I tested this change on my fork, and it's full of green color 😉 
https://github.com/lukaszstolarczuk/pmdk/actions/runs/4616965238 (nightly build, with extra MAKE_PKG=1 job)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5576)
=> common: update opensuse docker

utils/gha-runners/get-system-info.sh
testconfig.sh.example says:
```
It is required to have [...] at least RO access to all of the following resource files (containing physical addresses) of NVDIMM devices (only root can read them by default):
/sys/bus/nd/devices/ndbus*/region*/resource
/sys/bus/nd/devices/ndbus*/region*/dax*/resource
/sys/bus/nd/devices/ndbus*/region*/pfn*/resource
/sys/bus/nd/devices/ndbus*/region*/namespace*/resource
Note: some tests require write access to:
/sys/bus/nd/devices/region*/deep_flush
```
(https://github.com/pmem/pmdk/blob/acd71e818af4afc2eb917e9d3b2e11a39f0381f3/src/test/testconfig.sh.example#L58-L67)
Let's print all those files to be able to check if they have required accesses.
- - - …
=> common: list nd resources in get-system-info.sh

src/test/unittest/badblock.py
The "sudo ndctl clear-errors" command resets permissions of DAX block device and its resource files,
because it removes the old files and creates new ones with default permissions, so their permissions have to be updated.
Fixes: #5606
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5611)
=> test: update permissions of DAX devices after clearing bad blocks

src/test/ex_libpmem2/TESTS.py
`ex_libpmem2/TEST6` would require two `VALGRIND_SET_CLEAN()` calls to be added to the "src/examples/libpmem2/ringbuf/ringbuf.c" example (see https://github.com/pmem/pmdk/pull/5604) in order to pass under pmemcheck, but it seems that examples do not use valgrind macros on purpose (to avoid unnecessary complication), so this test just should not be run under pmemcheck.
Fixes: #5598
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5618)
=> test: ex_libpmem2/TEST6 should not be run under pmemcheck

src/libpmem2/map_posix.c, src/test/unittest/ut_file.c
fixes: pmem/pmdk#5597
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5605)
=> pmem2: fix valgrind instrumentation in pmem2_map_from_exisiting

src/test/pmem2_map_prot/TESTS.py
Disable the test until #5599 is fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5653)
=> test: disable test until #5599 fixed

.github/workflows/unittest.yml
Enable Python tests (short+medium) to be run on PMem
Requires:
Fixes: #5649
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5648)
=> test: enable Python tests (short+medium) to be run on PMem

src/test/pmem2_mem_ext/TESTS.py
Disable avx512f tests (pmem2_mem_ext) until Valigrind will provide support for avx512f instruction.
See: #5640
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5658)
=> test: disable avx512f tests (pmem2_mem_ext) under Valgrind

src/test/pmem2_map_from_existing/TESTS.py
Disable tests pmem2_map_from_existing - TEST[0-2] for memcheck until #5594 is fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5663)
=> test: disable pmem2_map_from_existing TEST[0-2] until #5594 is fixed.

src/test/ex_libpmem2/TESTS.py
Ref:
- #5638
- #5593 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5664)
=> test: disable ex_libpmem2 TEST6 until #5638 and #5593 are fixed

src/test/obj_sync/TEST0, src/test/obj_sync/TEST2, src/test/obj_sync/TEST5, src/test/obj_sync/TEST6
Disable obj_sync TEST0,2,5,6 until #5643 and #5646 are fixed.
Ref: 
- #5643
- #5646
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5665)
=> test: disable obj_sync TEST0,2,5,6

src/test/ex_libpmem2/TESTS.py
@t.require_valgrind_disabled() can only be used one time as a class decorator.
This fix improves the fix #5664
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5668)
=> test:@t.req...val..._disable() used only once in ex_libpmem2/TEST6

src/test/pmem2_integration/TESTS.py
Disable pmem2_integration/TEST[39,41] with memcheck until https://github.com/pmem/pmdk/issues/5637 is fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5671)
=> test: disable pmem2_integration/TEST[39,41] w/ memcheck

src/test/pmem2_mover/TESTS.py
est: disable pmem2_mover/TEST[0-5, 9] w/ pmemcheck until #5595 is fixed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5673)
=> test: disable pmem2_mover/TEST[0-5, 9] w/ pmemcheck until #5595 is fixed

src/test/ex_libpmem2/TESTS.py
Disable ex_libpmem2/TEST5 with memcheck until issue #5635 is fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5667)
=> test: disable ex_libpmem2/TEST5 with memcheck

src/test/pmem2_mover/pmem2_mover.c
Fixes: #5678.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5679)
=> test: fix pmem2_mover/TEST1 with memcheck for #5678

src/test/pmem2_mover/TESTS.py
Disable the test for 'pmemcheck' and 'BYTE' granularity until #5686 is fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5688)
=> test: disable pmem2_mover/TEST[6-8] (pmemcheck/byte)

src/test/pmem2_vm_reservation/TESTS.py
Disable the test for 'pmemcheck', 'drd', 'helgrind', 'memcheck' until #5592 is fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5689)
=> test: disable pmem2_vm_reservation/TEST22 w/ Valgrind

.github/workflows/unittest_valgrind_py.yml, .github/workflows/unittest_valgrind_sh.yml
Reorder test execution to place long tests sequence (drd/pmemcheck)
at the beginning to complete all tests execution in a shorter time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5693)
=> test: shortening the overall execution of valgrind tests

src/test/obj_sync/DISABLE_TEST2, src/test/obj_sync/DISABLE_TEST5, src/test/obj_sync/DISABLE_TEST6
Disable tests until the issue #5646 is fixed.
Fixes: #5700.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5704)
=> test: disable obj_sync/TEST[2,5-6] for all configurations until #5646 is fixed

src/test/RUNTESTS.py, src/test/unittest/basetest.py
test: skip elapsed time calculation when start_time unavailable
Avoid elapsed time calculation in case the test setup fails and
start_time is not available.
https://github.com/pmem/pmdk/actions/runs/5150199008/jobs/9274067958#step:6:1942
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5712)
=> test: skip elapsed time calculation when start_time unavailable

src/test/obj_ctl_stats/obj_ctl_stats.c
Check the curr_allocated size before the first allocation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5720)
=> test: check curr_allocated size before the first allocation

src/test/unittest/unittest.sh
The ppc64 tests execution has been disabled by #5729.
All ppc64 tests are silently skipped as there is no easy way to disable them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5744)
=> common: silently skip ppc64 tests

ChangeLog, src/test/libpmempool_rm/TEST0, src/test/libpmempool_rm/out0.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5748)
=> test: remove log&blk tests from the libpmempool_rm group

.github/workflows/pmem_check.yml
pmem check test will be executed every 8 hours on the stable master branch instead of dealing with trivial issues like license errors, cstyle errors, etc.
https://crontab.guru/#0_*/8_*_*_*
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5758)
=> common: disable pmem check tests for every pull request

utils/ansible/README.md, utils/ansible/ansible.cfg, utils/ansible/configure-self-hosted-runner.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5742)
=> common: a playbook for GHA self-hosted runner configuration

.github/workflows/codeql.yml
- get rid of redundant env variables (not used without docker),
- run make command instead of calling extra script to build pmdk; the script (unnecessarily in this case) execute tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5735)
=> common: clean CodeQL workflow up

doc/pmempool/pmempool-check.1.md, doc/pmempool/pmempool-convert.1.md, doc/pmempool/pmempool-create.1.md, doc/pmempool/pmempool-dump.1.md, doc/pmempool/pmempool-feature.1.md, doc/pmempool/pmempool-info.1.md, doc/pmempool/pmempool-rm.1.md, doc/pmempool/pmempool-sync.1.md, doc/pmempool/pmempool-transform.1.md, doc/pmempool/pmempool.1.md, src/tools/pmempool/README
Adjust the pmempool documentation to follow the removal of blk/log/btt support from pmempool.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5759)
=> common: pmempool documentation w/o btt/log/blk

utils/ansible/library/env.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5798)
=> common: restore the env.py ansible library

src/test/RUNTESTS.py, src/test/pmem2_badblock/TESTS.py, src/test/unittest/basetest.py, src/test/unittest/futils.py, src/test/unittest/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5792)
=> Use dedicated DISABLED() function to disable tests in Python test framework

src/test/obj_sync/TEST4
Disable the test until #5699 and #5706 are fixed.
Requires:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5795)
=> test: disable obj_sync/TEST4 until #5699 and #5706 are fixed.

src/test/pmempool_sync/TEST18
Disable tests for all configurations until issue #5708 is fixed.
Requires:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5796)
=> test: disable pmempool_sync/TEST18 until #5708 is fixed

src/test/libpmempool_backup/TEST6, src/test/obj_many_size_allocs/TEST0, src/test/obj_pmalloc_mt/TEST0, src/test/obj_pmalloc_mt/TEST2, src/test/obj_pmalloc_mt/TEST3, src/test/obj_pmalloc_rand_mt/TEST0, src/test/obj_reserve_mt/TEST0, src/test/obj_reserve_mt/TEST2, src/test/obj_reserve_mt/TEST3, src/test/obj_tx_alloc_mt/TEST0, src/test/obj_tx_alloc_mt/TEST2, src/test/obj_tx_flow/TEST0, src/test/obj_tx_locks/TEST0, src/test/obj_zones/TEST0, src/test/obj_zones/TEST1
configure_valgrind and require_valgrind shall be used after require_test_type and require_fs_type to avoid SKIPs with message due to unsupported/unselected Valgrind configuration.
In case of require_test_type and require_fs_type the SKIP is executed but without message added to a test log.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5799)
=> test: avoid unnecessary skip in case of different expected test type

.github/workflows/docker_rebuild.yml, utils/docker/pull-or-rebuild-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5805)
=> Docker product

src/test/obj_pmalloc_mt/TEST1, src/test/obj_sync/TEST0, src/test/obj_sync/TEST1, src/test/obj_sync/TEST2, src/test/obj_sync/TEST3, src/test/obj_sync/TEST5, src/test/obj_sync/TEST6, src/test/obj_sync/TEST7, src/test/pmem2_vm_reservation/TESTS.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5808)
=> test: disable failing tests

.github/workflows/scan_coverage.yml, .github/workflows/scans.yml, .github/workflows/ubuntu.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5806)
=> common: add coverage scan

utils/create-testconfig.sh
Currently, it does not work as intended and looks really ugly in the output when fails.
https://github.com/pmem/pmdk/actions/runs/5599256917/jobs/10240056624?pr=5807#step:5:27
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5809)
=> common: fix ndctl & jq detection for testconfig generation

src/test/obj_sync/TEST0, src/test/obj_sync/err0.log.match, src/test/obj_sync/out0.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5817)
=> test: add a test that checks performance without valgrind

.github/workflows/pmem.io_doc_update.yml, utils/docker/build-CI.sh, utils/docker/run-build.sh, utils/run-doc-update.sh
Preview: https://github.com/pmem/pmdk/actions/runs/5621978355
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5818)
=> common: simplified pmem.io doc update

.github/workflows/scan_ubsan.yml, .github/workflows/scans.yml
https://github.com/osalyk/pmdk/actions/runs/5622110505/job/15234172907
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5819)
=> common: add UBSAN build

RELEASE_STEPS.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5822)
=> common: update RELEASE_STEPS.md file

.github/workflows/main.yml, .github/workflows/ubuntu.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5830)
=> common: add coverage build

.github/workflows/nightly.yml
There are currently no EXPERIMENTAL binaries produced. The EXPERIMENTAL APIs do not require any special treatment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5831)
=> common: drop EXPERIMENTAL builds testing

utils/docker/run-build-package.sh
Ref: #5839
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5840)
=> common: why Python-based tests are not used for package testing

utils/docker/run-coverity.sh
**Note**: This PR has not been directly tested. I had considered establishing a proper test environment for the Coverity build too cumbersome to prepare at this time. My proposition is to merge it as is and test it on the master branch. If it will cause problems I would revert the change and create an issue reporting the existence of this log which we have not managed to investigate.
I used this snippet in a standalone script and tested it against a random file. I swear it worked. xD
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5841)
=> common: view the Coverity log file

src/test/unittest/granularity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5855)
=> test: fix granularity requirement check

.github/workflows/main.yml, src/benchmarks/pmembench.cpp, utils/style_check.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5843)
=> common: install clang-format for cstyle purposes

src/test/unittest/unittest.sh
There is no practice of verbosely stating that the given requirement was met. What is more, this message was particularly confusing since no user-forced Valgrind tool does not mean no Valgrind test will be run. If a given test requires a Valgrind tool it still will be used.
Hence, the decision to replace it with a comment hopefully more precisely describing the situation and definitely less polluting the console.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5844)
=> test: replace a confusing message with a comment

ChangeLog
Ref: #5855
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5858)
=> common: fix granularity requirement check (changelog entry)

.github/workflows/pmem_valgrind.yml, src/test/README, src/test/RUNTESTS.sh, src/test/unittest/configurator.py, src/test/unittest/unittest.sh
With the `none` parameter added to the matrix, only one workflow
is needed to run all tests (with and without Valgrind)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5811)
=> test: 'none' value of force-enable to optimize PMem workflow

src/test/unittest/valgrind.py
Ref: #5811
Before: https://github.com/pmem/pmdk/actions/runs/5914014610
After: https://github.com/pmem/pmdk/actions/runs/5925859348 (just the `force-enable: none` configurations)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5867)
=> test: force-enable to accept none value (fix)

src/test/RUNTESTS.sh, src/test/unittest/unittest.sh
- By default, no Valgrind tool has been forced, and a Valgrind tool or lack of it will be picked depending on the particular test's requirements.
- Providing 'force-enable [memcheck|pmemcheck|helgrind|drd]' will force all tests to be run under the forced Valgrind tool unless a test forced a different Valgrind tool in which case the given will test will be skipped.
- Providing 'force-enable none' will run all tests that do not require explicitly any Valgrind tool and skip all other tests.
Ref: #5811
Ref: #5791
PMem Long (no force-enable provided)
Before regression: https://github.com/pmem/pmdk/actions/runs/5838427329/job/15835451743
After regression: https://github.com/pmem/pmdk/actions/runs/5908491536/job/16027995086
After fix: https://github.com/pmem/pmdk/actions/runs/5927643088/job/16071 …
=> test: fix CHECK_TYPE behaviour

src/test/pmem2_integration/TESTS.py
Before: https://github.com/pmem/pmdk/actions/runs/5914014610/job/16038897674 (5h)
After: https://github.com/pmem/pmdk/actions/runs/5931209667 (30m)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5871)
=> test: disable pmem2_integration/33-37 under pmemcheck

.github/actions/pmem_test_procedure/action.yml
Before: https://github.com/pmem/pmdk/actions/runs/5928806525/job/16075192921#step:3:11095
After: https://github.com/pmem/pmdk/actions/runs/5928308017/job/16073620787#step:3:10950
Before: https://github.com/pmem/pmdk/actions/runs/5928806525/job/16075191366#step:3:13638
After: https://github.com/pmem/pmdk/actions/runs/5928308017/job/16073621124#step:3:13815
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5869)
=> common: simplify pmem_test_procedure for Python-based tests

ChangeLog, RELEASE_STEPS.md
The next major version after 1.13 is 2.0 instead of 1.14.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5877)
=> doc: rename 1.14.0 to 2.0.0

utils/ansible/configure-pmem.yml
#5632 
Extracting pmem name from mount for /mnt/pmem0 mount point
Add /etc/fstab entry for permanent mount with ansible.posix.mount
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5885)
=> FEAT: permanent mounting of PMem in ansible script

ChangeLog, src/Makefile.inc, src/libpmem/Makefile
For libpmem `CFLAGS` are set before the `src/Makefile.inc` is included. As far as I can tell it was unintentionally introduced by #4797. This oversight excluded libpmem from using `DEFAULT_CFLAGS`. Which has significant consequences on the outcome e.g. restoring the use of `DEFAULT_CFLAGS` reduces the maximum stack usage from 50kB to 8kB.
The issue is present in releases >= 1.9. Note that non-NDCTL builds were not affected.
This regression although unintentional might had a not yet known influence on the performance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5890)
=> common: fix libpmem CFLAGS

utils/call_stacks_analysis/api-from-link-file.sh
Generate a list of libpmem and libpmemobj public API functions based on linker files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5899)
=> common: generate public API list based on linker file

utils/call_stacks_analysis/README.md, utils/call_stacks_analysis/generate_call_stacks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5909)
=> common: introduce the lower limit parameter

utils/call_stacks_analysis/generate_call_stacks.py
In order to streamline the process of generating stack usage, all ndctl functions are assumed to consume up to 4kB of memory.
Requires:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5912)
=> common: assume const size of ndctl stack consumption

utils/call_stacks_analysis/make_cflow.sh
Revert changes done for proper cflow analysis if the `make_cflow.sh` script is run on a unchanged github repo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5914)
=> common: revert automatically all changes made for cflow analysis

ChangeLog, src/libpmemobj/obj.c, utils/call_stacks_analysis/stack_usage.txt
obj_vg_check_no_undef is called from one thread at a time, as it is called in between
os_mutex_lock(&pools_mutex);
...
os_mutex_unlock(&pools_mutex);
We can use one instance of the function's data and limit stack usage to ~480 bytes (instead of ~16k). 
This is critical when libpmeobj is used in solutions with restricted stack size.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5893)
=> obj: reduce stack usage of obj_vg_check_no_undef

utils/call_stacks_analysis/make_call_stacks.py
Bypass call_stacks_all.json file dumping to decrease the overall time of call stacks analysis. Dumping may consume up 40% of the whole script time in case of complex stacks analysis.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5922)
=> common: skip by default dumping call_stacks_all.json file

utils/ansible/README.md, utils/ansible/configure-pmem.yml, utils/ansible/configure-self-hosted-runner.yml, utils/ansible/opensuse-setup.yml, utils/ansible/rockylinux-setup.yml
- opensuse/rhel-setup.yml playbooks should be run as root (remotely with ansible_user=root)
- other playbooks (configure-pmem, update-os, configure-self-hosted-runner) should be run as `pmdkuser` (remotely with ansible_user=pmdkuser)
- remove testUser variable from user-executed playbooks
- unify quotation usage across ansible playbooks and GitHub workflows
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5954)
=> common: Unify PMEM setup scripts

src/test/unittest/unittest.sh
Removing the Braille test directory suffix to simplify manual test reproduction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5977)
=> common: Removing the annoying test directory suffix

src/core/out.c, src/core/out.h, src/core/util.h, src/core/util_posix.c, src/test/out_err/out_err.c, src/tools/pmempool/output.c, src/tools/pmempool/output.h
Requires:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5976)
=> err() with explicit errno

utils/call_stacks_analysis/white_list.json
Add out_log_va to the white list as it is no longer used in the release version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5986)
=> common: add out_log_va to white list

src/test/pmempool_transform/TEST12, src/test/pmempool_transform/TEST9
The test 9 needed no special treatment to just work.
The test 12 needs just the kind of filtering other pmempool tests received.
Ref: #5966 #5982
Preview: https://github.com/pmem/pmdk/actions/runs/7828553673/job/21358689893#step:4:2544
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5997)
=> test: re-enable pmempool_transform[9,12]

src/core/log_internal.h
`CORE_LOG_FATAL_W_ERRNO()` calls `abort()` in the same way as `CORE_LOG_FATAL()`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6003)
=> common: call abort() after reporting a fatal issue

src/core/out.c, src/core/out.h, src/core/util.h, src/libpmempool/feature.c, src/test/helgrind-log.supp, src/test/tools/anonymous_mmap/anonymous_mmap.c, src/test/tools/obj_verify/obj_verify.c, src/tools/pmempool/output.h, utils/call_stacks_analysis/make_extra.py, utils/call_stacks_analysis/white_list.json
Include `core_log_default_function()` in call stack analysis 
and remove obsolete implementation of `LOG()` macro in release version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6007)
=> Call stack analysis w/ core_log_default_function()

utils/gha-runners/get-system-info.sh
ipmctl requires root priviledge for execution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6009)
=> common: use sudo for ipmctl command

src/core/log.c, src/core/log_internal.h, src/test/core_log/core_log.c, utils/call_stacks_analysis/README.md
Move errno string generation into `core_log_va()` to decrease overall stack usage.
Original implementation increases max stack usage by 320 to 11376 bytes compared to 11056 before the new logging solution implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6010)
=> common: log w/ errno handled internally

src/core/log.c, src/core/out.c, src/test/arch_flags/log0.log.match, src/test/core_log_max/call_all.c.generated, src/test/out_err/traces0.log.match, src/test/traces/custom_file0.log.match, src/test/traces/redir_stderr2.log.match, src/test/traces/redir_stderr3.log.match, src/test/traces/redir_stderr4.log.match, src/test/traces/redir_stderr5.log.match, src/test/util_poolset/grep0.log.match, src/test/util_poolset/grep1.log.match, src/test/util_poolset/grep10.log.match, src/test/util_poolset/grep2.log.match, src/test/util_poolset/grep3.log.match, src/test/util_poolset/grep4.log.match, src/test/util_poolset/grep5.log.match, src/test/util_poolset/grep6.log.match, src/test/util_poolset/grep7.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6021)
=> common: print basic lib info when new logging function is set

src/libpmemobj/tx.c, src/libpmempool/check_util.c, src/libpmempool/feature.c
The file originally has been included in `out.h`,
and is no longer there after the new core_log implementation.
In the majority of builds it was included via `valgrind.h,` but it is not valid for builds with
`make EXTRA_CFLAGS=-DVG_MEMCHECK_ENABLED=0`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6027)
=> common: missing header file stdarg.h added

.github/workflows/pmem_tests.yml
PMem tests required about 14h30m for execution.
With execution started at noon results are practically available at the end of working day.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6023)
=> common: start PMem tests at 6:00 pm to get results early next day

.github/workflows/main.yml
To get all results in a shorter time
Failed coverage scan does not stop Ubuntu build:
https://github.com/pmem/pmdk/actions/runs/8019036765
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6025)
=> common: run coverage scan in paralel w/ Ubuntu build

.github/workflows/scan_log_calls.yml, src/test/core_log_max/call_all.c.generated, utils/call_stacks_analysis/log_call_all_generate.py
Exclude line number from `call_all.c.generated to`
[log_calls_diff.zip](https://github.com/pmem/pmdk/files/14382080/log_calls_diff.zip)
avoid false Log call Scans GHA results because of changing the place where `CORE_LOG...()` is used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6022)
=> common: exclude line_no from call_all.c.generated

src/core/log.c, src/core/log_internal.h, src/test/core_log_max/core_log_max.c
- Minor fixes to core_log_va()
- Remove core_log_to_last() and keep only one way to use core_log_va() from core_log() (with new invisible level).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6030)
=> common: remove core_log_to_last

src/core/out.c, src/core/out.h
Requires:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6026)
=> common: no out_*() functions in release build

src/test/Makefile, src/test/core_log_internal/.gitignore, src/test/core_log_internal/Makefile, src/test/core_log_internal/TESTS.py, src/test/core_log_internal/core_log_internal.c, src/test/unittest/unittest.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6031)
=> test: CORE_LOG_* UT

src/core/log_default.c, src/test/Makefile, src/test/core_log_default_function/.gitignore, src/test/core_log_default_function/Makefile, src/test/core_log_default_function/TESTS.py, src/test/core_log_default_function/core_log_default_function.c, src/test/core_log_internal/Makefile, src/test/unittest/unittest.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6029)
=> common: core_log_default_function() ut

src/core/log.c, src/test/Makefile, src/test/core_log_mt/.gitignore, src/test/core_log_mt/Makefile, src/test/core_log_mt/TESTS.py, src/test/core_log_mt/core_log_mt.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6035)
=> common: core_log_set/get_threshold MT unit tests

src/core/log_internal.h, src/test/Makefile, src/test/core_log/.gitignore, src/test/core_log/Makefile, src/test/core_log/Makefile.inc, src/test/core_log/TESTS.py, src/test/core_log/core_log.c, src/test/core_log/core_log_common.c, src/test/core_log/core_log_common.h, src/test/core_log_internal/core_log_internal.c, src/test/core_log_no_func/.gitignore, src/test/core_log_no_func/Makefile, src/test/core_log_no_func/TESTS.py, src/test/core_log_no_func/core_log_no_func.c, src/test/unittest/unittest.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6033)
=> test: introduce core_log() unit tests

src/core/log.c, src/core/log_default.c, src/core/log_default.h, src/core/log_internal.h, src/core/out.c, src/include/libpmemobj/log.h, src/libpmemobj/obj_log.c, src/test/core_log/core_log.c, src/test/core_log/core_log_common.c, src/test/core_log_default_function/core_log_default_function.c, src/test/core_log_internal/core_log_internal.c, src/test/unittest/unittest.h, src/test/unittest/ut_log.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6037)
=> common: drop the logging context

src/core/log.c, src/test/Makefile, src/test/core_log_function_mt/.gitignore, src/test/core_log_function_mt/Makefile, src/test/core_log_function_mt/TESTS.py, src/test/core_log_function_mt/core_log_function_mt.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6041)
=> common: add core_log_set_function() MT unit test

.github/workflows/main.yml, src/test/Makefile.inc, src/test/core_log/core_log_common.c, src/test/core_log/core_log_common.h, src/test/core_log_function_mt/core_log_function_mt.c, src/test/core_log_threshold_mt/core_log_threshold_mt.c, src/test/unittest/README, src/test/unittest/unittest.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6045)
=> common: various clang fixes

.github/workflows/docker_rebuild.yml, .github/workflows/main.yml, .github/workflows/nightly.yml, .github/workflows/pmem.io_doc_update.yml, .github/workflows/pmem_ras.yml, .github/workflows/pmem_test_matrix.yml, .github/workflows/pmem_tests.yml, .github/workflows/scan_bandit.yml, .github/workflows/scan_codeql.yml, .github/workflows/scan_coverage.yml, .github/workflows/scan_coverity.yml, .github/workflows/scan_documentation.yml, .github/workflows/scan_log_calls.yml, .github/workflows/scan_stack_usage.yml, .github/workflows/scan_ubsan.yml, .github/workflows/ubuntu.yml
It seems the only thing changed between v3 and v4 is node20. v4.1.1 has been used in our ci before. It was unified to directly use v4 which will make our life easier since we would not need to update these workflows till v5.
Ref: https://github.com/actions/checkout/releases/tag/v4.0.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6046)
=> common: update actions/checkout to v4

src/test/core_log/TESTS.py, src/test/core_log/core_log.c, src/test/core_log/core_log_common.c, src/test/core_log/core_log_common.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6047)
=> test: UT for core_log_set_function()

src/include/libpmemobj.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6054)
=> common: add log.h to libpmemobj.h

doc/Makefile, doc/libpmemobj/.gitignore, doc/libpmemobj/pmemobj_log_get_threshold.3.md, doc/libpmemobj/pmemobj_log_set_function.3.md, doc/libpmemobj/pmemobj_log_set_threshold.3.md, src/include/libpmemobj/log.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6043)
=> doc: logging function documentation

.github/workflows/main.yml, ChangeLog, src/libpmemobj/Makefile
Requires:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5946)
=> pmemobj: introduce fuses against ill-considered use of NDCTL_ENABLE=n

.github/workflows/main.yml, utils/check_license/check-headers.sh
Preview:
- https://github.com/pmem/pmdk/actions/runs/8345468447?pr=6058 (fail)
- https://github.com/pmem/pmdk/actions/runs/8345518784?pr=6058 (success)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6058)
=> common: allow check_license to apply proposed changes

src/include/libpmem.h, src/libpmem/libpmem.c, src/test/Makefile, src/test/pmem_log_set_function/.gitignore, src/test/pmem_log_set_function/Makefile, src/test/pmem_log_set_function/TESTS.py, src/test/pmem_log_set_function/pmem_log_set_function.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6059)
=> pmem: add pmem_log_set_function function + UT

.github/actions/pmem_benchmark_run/action.yml, .github/workflows/pmem_benchmark.yml, src/benchmarks/obj_pmalloc.cpp, src/benchmarks/pmemobj_tx.cpp, utils/ansible/opensuse-setup.yml, utils/ansible/rockylinux-setup.yml, utils/benchmarks/run_and_combine.py
Preview: https://github.com/pmem/pmdk/actions/runs/8451896391
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6069)
=> common: benchmarking utility and workflow

src/test/obj_tx_locks/TEST1, src/test/out_err_mt/TEST1, src/test/out_err_mt/TEST2, src/test/util_ctl/TEST0, src/test/util_ctl/TEST1
Suppress **\*ERROR\*** messages from stderr in tests that verify faulty situations based on function return value and errno value. These tests ignore stderr/stdout at all.
This is to avoid a lot of unnecessary messages on the screen during test execution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6063)
=> test: suppress ERROR messages when irrelevant to the test result

src/include/libpmemobj/log.h, src/libpmemobj/obj_log.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6067)
=> obj: unify description with implementation pmemobj_log* fun

doc/libpmemobj/pmemobj_log_set_function.3.md, src/core/log.c, src/core/log_default.c, src/core/log_default.h, src/core/log_internal.h, src/core/out.c, src/core/out.h, src/include/libpmem.h, src/include/libpmemobj/log.h, src/test/core_log/core_log_common.c, src/test/core_log/core_log_common.h, src/test/core_log_default_function/core_log_default_function.c, src/test/core_log_function_mt/core_log_function_mt.c, src/test/core_log_internal/core_log_internal.c, src/test/core_log_max/core_log_max.c
To make PMDK logging system compatible with DAOS/vos logging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6064)
=> common: log uses unsigned instead of int for line_no as it is done in DAOS/vos

ChangeLog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6071)
=> common: 2.1.0 documentation update

src/common.inc
`#if NDCTL_ENABLED` that is used in the source code expects that `NDCTL_ENABLED` is defined all the time with either *0* or *non-0* value.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5943)
=> common: fix support of OS_DIMM_CFLAG

src/benchmarks/perf.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6072)
=> benchmark: tune perf.cfg for longer execution times

doc/libpmem/pmem_log_use_default_function.3
https://github.com/pmem/pmdk/actions/runs/8547715021/job/23420333917#step:4:2077
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6073)
=> doc: add missing doc file

src/test/core_log_max/call_all.c.generated, src/test/core_log_max/core_log_max.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6075)
=> common: add SDS related CORE_LOG_WARNING to core_log_max test

.github/workflows/scan_stack_usage.yml, utils/call_stacks_analysis/README.md
The problem was observed and confirmed only on Ubuntu
https://github.com/pmem/pmdk/actions/runs/8690027560/job/23828976964
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6078)
=> utils: change lower_limit

src/libpmemobj/memops.c, src/libpmemobj/memops.h, src/test/Makefile, src/test/obj_ulog_advanced/.gitignore, src/test/obj_ulog_advanced/Makefile, src/test/obj_ulog_advanced/TEST0, src/test/obj_ulog_advanced/TEST8, src/test/obj_ulog_advanced/TEST9, src/test/obj_ulog_advanced/TESTS.py, src/test/obj_ulog_advanced/common.sh, src/test/obj_ulog_advanced/err5.log.match, src/test/obj_ulog_advanced/err6.log.match, src/test/obj_ulog_advanced/err7.log.match, src/test/obj_ulog_advanced/err9.log.match, src/test/obj_ulog_advanced/obj_ulog_advanced.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6094)
=> test: introduce a test reproducing the #5583

src/test/obj_ulog_advanced/obj_ulog_advanced.c
No-Valgrind build fix.
Preview: https://github.com/pmem/pmdk/actions/runs/9505506732
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6098)
=> test: introduce a test reproducing the #5583 (fix)

src/test/obj_ulog_advanced/TESTS.py
Requires:
Preview: https://github.com/pmem/pmdk/actions/runs/9513026651
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6099)
=> test: introduce a test reproducing the #5583 (fix 2)

.github/workflows/pmem_ras.yml
Preview: https://github.com/pmem/pmdk/actions/runs/9547131969/job/26311475580
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6100)
=> common: increase PMEM RAS' sensitivity

.github/workflows/pmem_ras.yml, utils/gha-runners/run-ras-linux.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6101)
=> common: update files for updating repositories

.github/workflows/pmem_ras.yml, utils/gha-runners/run-ras-linux.yml
- on failure JSON -> YAML (as it is more human-readable)
- print the PMDK and pmdk-tests build outputs unconditionally but groupped so it won't consume too much vertical space.
- remove all ignore_erros: true so no error is ignored
Preview: https://github.com/pmem/pmdk/actions/runs/9992769191/job/27618560250 (🔴 is 🆗 in this case ONLY 😉 )
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6103)
=> common: improve the PMEM RAS workflow output

.github/actions/pmem_test_prepare/action.yml, .github/workflows/pmem_tests.yml
https://github.com/pmem/pmdk/actions/runs/10099290119/job/27928165433#step:3:3
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6104)
=> common: fix typo in pmem_tests.yml file

.github/workflows/main.yml, ChangeLog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6106)
=> common: add arm64 build

.github/actions/pmem_benchmark_run/action.yml, .github/workflows/docker_rebuild.yml, .github/workflows/main.yml, .github/workflows/nightly.yml, .github/workflows/pmem_benchmark.yml, .github/workflows/pmem_ras.yml, .github/workflows/pmem_test_matrix.yml, .github/workflows/pmem_tests.yml, .github/workflows/scan_bandit.yml, .github/workflows/scan_codeql.yml, .github/workflows/scan_coverage.yml, .github/workflows/scan_coverity.yml, .github/workflows/scan_documentation.yml, .github/workflows/scan_log_calls.yml, .github/workflows/scan_stack_usage.yml, .github/workflows/scan_ubsan.yml, .github/workflows/scorecard.yml, .github/workflows/ubuntu.yml
https://github.com/pmem/pmdk/security/code-scanning
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6108)
=> fix code scanning alerts

CODING_STYLE.md, CONTRIBUTING.md, LICENSE.txt, LICENSE/BSD-3-Clause, LICENSE/OPENSOLARIS.LICENSE, README.md, doc/.gitignore, utils/build-dpkg.sh, utils/check_license/file-exceptions.sh, utils/pmdk.spec.in
Organize licenses in a way to is fully compatible with OpenSSF Scorecard
There is no license issue with the given licenses configuration:
https://github.com/grom72/pmdk/security/code-scanning
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6112)
=> SPDX License setup

.github/workflows/docker_rebuild.yml, .github/workflows/main.yml, .github/workflows/nightly.yml, .github/workflows/pmem_benchmark.yml, .github/workflows/pmem_ras.yml, .github/workflows/pmem_test_matrix.yml, .github/workflows/pmem_tests.yml, .github/workflows/scan_bandit.yml, .github/workflows/scan_codeql.yml, .github/workflows/scan_coverage.yml, .github/workflows/scan_coverity.yml, .github/workflows/scan_documentation.yml, .github/workflows/scan_log_calls.yml, .github/workflows/scan_stack_usage.yml, .github/workflows/scan_ubsan.yml, .github/workflows/scans.yml, .github/workflows/ubuntu.yml
https://github.com/osalyk/pmdk/actions/runs/11030327278
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6113)
=> common: harden GitHub Actions

src/test/Makefile.inc, src/test/unittest/unittest.h
There is a code that do nothing. It has not been finished when last logging cleanup has been made.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6118)
=> common: remove obsolete code

utils/ansible/README.md, utils/ansible/configure-pmem.yml, utils/ansible/configure-self-hosted-runner.yml, utils/ansible/opensuse-setup.yml, utils/ansible/rockylinux-setup.yml, utils/ansible/update-os.yml
- `ansible_user` is undefined on  a localhost with a local connection and needs to be always passed with `--extra-vars`
https://radeksprta.eu/posts/ansible_user-is-undefined-on-localhost/
- several minor cleanups of Ansible scripts' documentation
- rename the `testUser` to a `new_user`
This PR is a replacement for #5955.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6055)
=> common: ansible_user support in ansible scripts

src/test/unittest/basetest.py
Just in case any of these fails it has to be defined.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6115)
=> test: start_time to be defined before clean() and setup()

src/test/unittest/basetest.py
common: fix cstyle introduced by PR #6115
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6123)
=> common: fix cstyle introduced by PR #6115

src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6052)
=> common: extend SKIPed tests description

utils/ansible/configure-self-hosted-runner.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6125)
=> common: fix proxy domain setup in self-hosted runner

.github/workflows/main.yml
`Zomzog/changelog-checker` action can only be run on PR, otherwise the action fails E.g. when the Main workflow is run manually.
Please take a look at: https://github.com/grom72/pmdk/actions/runs/11526775592/job/32091465108#step:3:9
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6128)
=> common: Zomzog/changelog-checker executed only for PR

src/common/bad_blocks.c, src/common/bad_blocks.h, src/common/set_badblocks.c, src/common/shutdown_state.c, src/libpmem2/badblocks.c, src/libpmem2/badblocks.h, src/libpmem2/badblocks_ndctl.c, src/libpmem2/badblocks_none.c, src/libpmempool/check_bad_blocks.c, src/libpmempool/replica.c, src/libpmempool/replica.h, src/test/pmem2_badblock_mocks/pmem2_badblock_mocks.c, src/test/util_badblock/util_badblock.c, src/tools/daxio/daxio.c, src/tools/pmempool/info.c
Skip warning: "Cannot find any matching device, no bad blocks found" when pmem2_badblock_next() is used internally.
Fixes: #6126
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6127)
=> common: skip warning: "Cannot find any matching device, no bad blocks found"

src/test/pmem2_mem_ext/TESTS.py
https://github.com/pmem/pmdk/issues/6129
https://github.com/pmem/pmdk/issues/5640
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6130)
=> test: disable VARIANT_MOVDIR64B under Valgrind

CONTRIBUTING.md, src/common.inc, src/core/util.h, src/libpmem/libpmem.c, src/libpmemobj/lane.c, src/libpmemobj/obj_log.c, src/test/ctl_prefault/ctl_prefault.c, src/test/obj_memops/obj_memops.c, utils/call_stacks_analysis/white_list.json, utils/style_check.sh
pmem2_badblock_next is no longer used as libpmem uses pmem2_badblock_next_internal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6133)
=> common: pmem2_badblock_next is replaced by pmem2_badblock_next_internal

ChangeLog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6136)
=> common: ChangeLog supplement for #6117 and #6127

src/core/util.h
https://github.com/osalyk/pmdk/actions/runs/13176992738/job/36779437402
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6139)
=> common: check clang version

src/test/libpmempool_feature/TEST1, src/test/libpmempool_feature/TEST2, src/test/obj_sds/TEST0, src/test/obj_sds/TEST1, src/test/obj_sds/TEST2, src/test/obj_sds/TEST3, src/test/obj_sds/TEST4, src/test/obj_sds/TEST5, src/test/obj_sds/TEST6, src/test/obj_sds/TEST7, src/test/pmempool_check/TEST28, src/test/pmempool_check/TEST29, src/test/pmempool_check/TEST30, src/test/pmempool_feature/TEST1, src/test/pmempool_feature/TEST10, src/test/pmempool_feature/TEST11, src/test/pmempool_feature/TEST12, src/test/pmempool_feature/TEST14, src/test/pmempool_feature/TEST15, src/test/pmempool_feature/TEST16, src/test/pmempool_feature/TEST2, src/test/pmempool_feature/TEST4, src/test/pmempool_feature/TEST5, src/test/pmempool_feature/TEST7, src/test/pmempool_feature/TEST8, src/test/pmempool_info/TEST14, src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6152)
=> test: call setup before require_sds

.github/workflows/scan_stack_usage.yml, utils/call_stacks_analysis/README.md, utils/call_stacks_analysis/examples/api_filter.txt, utils/call_stacks_analysis/install_cflow.sh, utils/call_stacks_analysis/make_cflow.sh, utils/call_stacks_analysis/run_call_stacks_analysis.sh
Provide call stack analysis for latest state of DAOS source code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6157)
=> common: call stack analysis for DAOS
