- src/version.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2811)
> common: [1.4] SRCVERSION for out of git tree builds

- src/version.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2812)
> common: [1.3] SRCVERSION for out of git tree builds

- ChangeLog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2808)
> doc: update ChangeLog for 1.4 release

- src/common/os_dimm_windows.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2814)
> test: fix volume path parsing

- src/common/out.c
- src/libpmemobj/obj.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2743)
> common: [1.4] fix free function in tls

- src/common/os_thread_windows.c
- src/test/obj_sync/obj_sync.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2770)
> common: [1.4] (win) fix timed locks 

- src/common/os_thread_windows.c
- src/test/obj_sync/obj_sync.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2771)
> common: [1.3] (win) fix timed locks 

- src/test/pmempool_sync/TEST27
- src/test/pmempool_sync/TEST28
- src/test/pmempool_sync/out27.log.match
- src/test/pmempool_sync/out28.log.match
Call pmempool-check just after pmempool-sync
and before pmempool-info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2827)
> test: check pool after syncing

- doc/libpmemobj/pmemobj_ctl_get.3.md
- src/include/libpmemobj/ctl.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2832)
> doc: tiny fixes

- src/libpmemobj/alloc_class.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2831)
> obj: use integer arithm. in alloc class selection

- src/libpmempool/replica.c
Check also signatures during syncing the poolset,
because it happened that the checksum was correct,
but the signature was invalid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2837)
> pool: check also signatures during syncing

- src/test/pmempool_sync/TEST25
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2842)
> test: fix incorrect number of required dax devices

- src/libpmempool/sync.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2843)
> pool: merge two messages

- src/test/vmem_mix_allocations/vmem_mix_allocations.c
Ref: pmem/issues#852
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2845)
> test: fix alloc sizes in vmem_mix_allocations

- src/librpmem/rpmem_fip.c
- src/test/rpmem_fip/rpmem_fip_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2846)
>  rpmem: early return from rpmem_read if len is 0

- src/libpmem/memops_generic.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2865)
> pmem: correctly copy memory in reversal order.

- src/test/RUNTESTS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2866)
> test: introduce test sequence execution

- src/test/common_badblock.sh
- src/test/pmempool_check/TEST31
- src/test/pmempool_check/TEST32
- src/test/pmempool_sync/TEST27
- src/test/pmempool_sync/TEST28
- src/test/pmempool_sync/out27.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2869)
> test: error out if injecting bad blocks failed

- src/test/testconfig.sh.example
- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2873)
> test: allow testing installed libraries

- src/libpmemobj/heap.c
- src/libpmemobj/heap.h
- src/libpmemobj/heap_layout.h
- src/libpmemobj/memblock.c
- src/libpmemobj/palloc.c
- src/libpmemobj/recycler.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2862)
> obj: minor cleanups

- src/test/pmempool_sync/TEST29
- src/test/pmempool_sync/out29.log.match
- src/test/tools/obj_verify/.gitignore
- src/test/tools/obj_verify/Makefile
- src/test/tools/obj_verify/README
- src/test/tools/obj_verify/obj_verify.c
- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2876)
> test: add obj_verify tool

- doc/generated/pmemobj_xflush.3
- doc/generated/pmemobj_xpersist.3
- doc/libpmemobj/pmemobj_memcpy_persist.3.md
Ref: pmem/issues#864
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2899)
> doc: pmemobj_x* references

- doc/libpmemobj/pmemobj_ctl_get.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2904)
> doc: add missing field to alloc class entry point (1.4)

- src/common/out.c
- src/test/drd-libfabric.supp
- src/test/helgrind-cxgb4.supp
- src/test/helgrind-libfabric.supp
- src/test/memcheck-libibverbs.supp
- src/test/obj_rpmem_basic_integration/TEST10
- src/test/obj_rpmem_basic_integration/TEST11
- src/test/obj_rpmem_basic_integration/TEST13
- src/test/obj_rpmem_basic_integration/TEST14
- src/test/obj_rpmem_basic_integration/TEST15
- src/test/obj_rpmem_basic_integration/TEST16
- src/test/obj_rpmem_basic_integration/TEST17
- src/test/obj_rpmem_basic_integration/TEST18
- src/test/obj_rpmem_basic_integration/TEST9
- src/test/rpmemd_config/Makefile
- src/test/rpmemd_dbg/Makefile
- src/test/rpmemd_log/Makefile
- src/test/rpmemd_util/Makefile
- src/test/unittest/unittest.sh
- src/tools/rpmemd/rpmemd_log.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2871)
> rpmem: mutliple valgrind fixes and clean ups

- doc/Makefile
Ref: pmem/issues#864
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2906)
> doc: fix Makefile dummy mans

- src/test/ld.supp
Ref: pmem/issues#858
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2908)
> test: add suppression for leak in ld.so

- src/test/ld.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2910)
> test: adapt ld.so leak suppression for Ubuntu

- src/test/common_badblock.sh
- src/test/util_badblock/TEST3
- src/test/util_badblock/TEST4
- src/test/util_badblock/TEST6
- src/test/util_badblock/TEST7
- src/test/util_badblock/TEST8
- src/test/util_badblock/TEST9
... in order to be sure that ndctl succeeded in injecting errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2915)
> test: add expect_bad_blocks in util_badblock

- src/test/obj_pool/TEST15
- src/test/obj_pool/TEST15.PS1
- src/test/obj_pool/TEST16
- src/test/obj_pool/TEST16.PS1
- src/test/obj_pool/TEST17
- src/test/obj_pool/TEST17.PS1
- src/test/obj_pool/obj_pool.c
- src/test/obj_pool/out15.log.match
- src/test/obj_pool/out16.log.match
- src/test/obj_pool/out17.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2917)
> test: Add new tests for pmemobj_create

- src/test/rpmem_basic/node_1_out7.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2928)
> test: fix rpmem_basic match file

- src/examples/libpmemobj++/pman/pman.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2926)
> examples: swap S and Q key in pman

- src/test/pmempool_rm/TEST2.PS1
- src/test/pmempool_rm/out2w.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2938)
> test: fix stderror handling in pmempool_rm test

- src/test/util_file_create/util_file_create.c
... before using it in util_file_create test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2939)
> test: verify fallocate is supported by fs

- utils/check-commit.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2940)
> common: remove 50 characters limitation from commit subject

- src/test/obj_direct_volatile/obj_direct_volatile.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2941)
> test: Add pmemobj_close() in obj_direct_volatile.c

- .mailmap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2944)
> common: .mailmap updates

- src/examples/libpmemobj/queue/queue.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2945)
> examples: properly initialize len of queue entry

- utils/check_license/check-headers.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2956)
> common: fix skipping checking dates for non-Intel commits

- CODING_STYLE.md
- Update missing daxio area name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2949)
> doc: update commit message guidelines

- src/libpmemobj/obj.c
- src/test/obj_list/obj_list_mocks.c
- src/test/obj_list/obj_list_mocks_palloc.c
- src/test/obj_memcheck/TEST0
- src/test/obj_memcheck/memcheck0.log.match
- src/test/obj_pmalloc_basic/obj_pmalloc_basic.c
- src/test/obj_redo_log/obj_redo_log.c
- src/test/pmempool_rm/TEST2.PS1
- src/test/pmempool_rm/out2w.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2955)
> Next round of backports for 1.4

- src/libpmemobj/heap.c
- src/libpmemobj/recycler.c
- src/libpmemobj/recycler.h
- src/test/obj_heap/obj_heap.c
This is a small cleanup that uses the new cleaner API provided by the
ravl tree.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2914)
> obj: recycler refactoring

- src/test/libpmempool_sync_win/libpmempool_sync_win.c
- src/test/libpmempool_sync_win/out0.log.match
- src/test/libpmempool_sync_win/out1.log.match
- src/test/libpmempool_transform_win/libpmempool_transform_win.c
- src/test/libpmempool_transform_win/out0.log.match
- src/test/libpmempool_transform_win/out1.log.match
If a function succeeds, a value of errno is not significant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2959)
> test: do not print errno in case of success

- utils/check-area.sh
- utils/check-commit.sh
... to propose valid area name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2930)
> common: improve commit message check

- .travis.yml
- utils/docker/build-travis.sh
- utils/docker/images/push-image.sh
- utils/docker/pull-or-rebuild-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2963)
> common: skip package check after build image

- utils/check_license/check-headers.sh
and append SOURCE_ROOT to file path to enable running check-license
from another directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2953)
> utils: add cmake files to check-headers.sh

- src/libpmemobj/palloc.c
- src/libpmemobj/palloc.h
- src/libpmemobj/tx.c
- src/test/Makefile
- src/test/obj_memcheck_register/.gitignore
- src/test/obj_memcheck_register/Makefile
- src/test/obj_memcheck_register/TEST0
- src/test/obj_memcheck_register/obj_memcheck_register.c
- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2931)
> obj: don't register undo logs twice in memcheck

- src/test/Makefile.inc
- src/test/blk_pool/Makefile
- src/test/compat_incompat_features/Makefile
- src/test/libpmempool_api/Makefile
- src/test/libpmempool_api/Makefile.inc
- src/test/libpmempool_sync/Makefile
- src/test/libpmempool_transform/Makefile
- src/test/log_pool/Makefile
- src/test/pmemobjcli/Makefile
- src/test/pmempool_check/Makefile
- src/test/pmempool_sync/Makefile
- src/test/pmempool_transform/Makefile
- src/test/pmemspoil/Makefile
- src/test/tools/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2961)
> test: fix build failure(s) with parallel check

- utils/docker/images/Dockerfile.fedora-25
- utils/docker/images/Dockerfile.ubuntu-16.04
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2965)
> Update Dockerfiles - use best practices

- utils/docker/images/install-valgrind.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2967)
> common: switch to Valgrind 3.13

- src/test/blk_non_zero/Makefile
- src/test/blk_recovery/Makefile
- src/test/log_recovery/Makefile
- src/test/obj_direct/Makefile
- src/test/obj_list_macro/Makefile
- src/test/obj_oid/Makefile
- src/test/obj_pool_lookup/Makefile
- src/test/obj_recovery/Makefile
- src/test/pmem_deep_persist/Makefile
- src/test/pmem_is_pmem_posix/Makefile
- src/test/pmem_valgr_simple/Makefile
- src/test/rpmem_addr/Makefile
- src/test/rpmem_addr_ext/Makefile
- src/test/rpmem_basic/Makefile
- src/test/rpmemd_config/Makefile
- src/test/rpmemd_dbg/Makefile
- src/test/rpmemd_log/Makefile
- src/test/rpmemd_util/Makefile
- src/test/vmem_check/Makefile
- src/test/win_getopt/Makefile
- src/test/win_mmap/Makefile
- src/test/win_mmap_fixed/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2969)
> test: remove not needed vpaths & cflags

- src/PMDK.sln
- src/test/obj_cpp_v/obj_cpp_v.vcxproj
- src/test/obj_direct_volatile/obj_direct_volatile.vcxproj
- src/test/obj_pool/obj_pool.vcxproj
- src/test/obj_pool/obj_pool.vcxproj.filters
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2975)
> test: add existing obj_pool tests (TEST15-TEST17) to PMDK.sln solution

- src/test/obj_cpp_v/obj_cpp_v.vcxproj
- src/test/obj_direct_volatile/obj_direct_volatile.vcxproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2974)
> test: fix obsolete SDK version requirements

- src/Makefile.inc
- src/common/util.c
- src/common/util.h
Ref: pmem/issues#876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2968)
> common: suppress -Wstringop-truncation in util_safe_strcpy

- src/libpmemobj/alloc_class.c
- src/libpmemobj/container.h
- src/libpmemobj/container_ravl.c
- src/libpmemobj/container_seglists.c
- src/libpmemobj/heap.c
- src/libpmemobj/memblock.c
- src/libpmemobj/memblock.h
- src/libpmemobj/palloc.c
- src/libpmemobj/ravl.c
- src/libpmemobj/ravl.h
- src/libpmemobj/recycler.c
- src/libpmemobj/recycler.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2978)
> obj: minor cleanups and documentation updates

- src/test/obj_check/TEST5
- src/test/obj_check/TEST5.PS1
- src/test/obj_check/TEST6
- src/test/obj_check/TEST6.PS1
- src/test/obj_check/TEST7
- src/test/obj_check/TEST7.PS1
- src/test/obj_check/TEST8
- src/test/obj_check/TEST8.PS1
- src/test/obj_check/obj_check.c
- src/test/obj_check/obj_check.vcxproj
- src/test/obj_check/obj_check.vcxproj.filters
- src/test/obj_check/out5.log.match
- src/test/obj_check/out6.log.match
- src/test/obj_check/out7.log.match
- src/test/obj_check/out8.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2973)
> test: add tests for pmemobj_check

- src/common/os_deep.h
- src/common/os_deep_linux.c
- src/common/os_deep_windows.c
- src/common/set.c
- src/common/shutdown_state.c
- src/common/shutdown_state.h
- src/libpmemcto/cto.c
- src/test/obj_persist_count/out1.log.match
- src/test/pmem_deep_persist/TEST5
- src/test/util_sds/util_sds.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2952)
> common: add deep drain before replica close

- src/test/pmempool_sync/TEST13
- src/test/pmempool_sync/TEST14
- src/test/pmempool_sync/TEST15
- src/test/pmempool_sync/TEST18
- src/test/pmempool_sync/TEST19
- src/test/pmempool_sync/TEST20
- src/test/pmempool_sync/TEST21
- src/test/pmempool_sync_remote/common.sh
- src/test/pmempool_transform/TEST11
- src/test/pmempool_transform/TEST12
- src/test/pmempool_transform/TEST14
- src/test/pmempool_transform/TEST15
- src/test/pmempool_transform/TEST16
- src/test/pmempool_transform/TEST18
- src/test/pmempool_transform/TEST22
- src/test/pmempool_transform_remote/common.sh
- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2988)
> test: set aligment sizes only once in unittest.sh

- README.md
- src/libpmemobj/palloc.c
- src/libpmemobj/palloc.h
- src/libpmemobj/tx.c
- src/test/Makefile
- src/test/Makefile.inc
- src/test/blk_pool/Makefile
- src/test/compat_incompat_features/Makefile
- src/test/libpmempool_api/Makefile
- src/test/libpmempool_api/Makefile.inc
- src/test/libpmempool_sync/Makefile
- src/test/libpmempool_transform/Makefile
- src/test/log_pool/Makefile
- src/test/obj_memcheck_register/.gitignore
- src/test/obj_memcheck_register/Makefile
- src/test/obj_memcheck_register/TEST0
- src/test/obj_memcheck_register/obj_memcheck_register.c
- src/test/pmemobjcli/Makefile
- src/test/pmempool_check/Makefile
- src/test/pmempool_sync/Makefile
- src/test/pmempool_transform/Makefile
- src/test/pmemspoil/Makefile
- src/test/tools/Makefile
- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2991)
> Next round of fixes for 1.4

- src/test/pmempool_check/TEST31
- src/test/pmempool_check/TEST32
- src/test/pmempool_create/TEST10
- src/test/pmempool_create/TEST11
- src/test/pmempool_create/TEST12
- src/test/pmempool_info/TEST24
- src/test/pmempool_info/TEST25
- src/test/pmempool_sync/TEST27
- src/test/pmempool_sync/TEST28
- src/test/unittest/unittest.sh
- src/test/util_badblock/TEST2
- src/test/util_badblock/TEST3
- src/test/util_badblock/TEST4
- src/test/util_badblock/TEST5
- src/test/util_badblock/TEST6
- src/test/util_badblock/TEST7
- src/test/util_badblock/TEST8
- src/test/util_badblock/TEST9
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2992)
> test: checking kernel module requires superuser rights

- src/common/os_dimm_ndctl.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2996)
> common: fix includes in os_dimm_ndctl.c

- src/test/RUNTESTLIB.PS1
- src/test/blk_pool/TEST10.PS1
- src/test/blk_pool/TEST11.PS1
- src/test/blk_pool/TEST25.PS1
- src/test/cto_pool/TEST10.PS1
- src/test/cto_pool/TEST11.PS1
- src/test/cto_pool/TEST25.PS1
- src/test/cto_pool/TEST26.PS1
- src/test/log_pool/TEST10.PS1
- src/test/log_pool/TEST24.PS1
- src/test/log_pool/TEST25.PS1
- src/test/log_pool/TEST9.PS1
- src/test/obj_pool/TEST10.PS1
- src/test/obj_pool/TEST11.PS1
- src/test/obj_pool/TEST25.PS1
- src/test/obj_pool/TEST26.PS1
- src/test/unittest/unittest.ps1
- src/test/util_file_create/TEST1.PS1
- src/test/util_file_open/TEST1w.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2995)
> Powershell changes

- src/common/os_dimm_ndctl.c
- src/common/os_dimm_windows.c
1. improve error handling 
2. simplify logic on windows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2982)
> common: refactor os_dimm module

- src/test/obj_fragmentation2/TEST0
- src/test/obj_fragmentation2/TEST1
- src/test/obj_fragmentation2/TEST2
- src/test/obj_fragmentation2/TEST3
- src/test/obj_fragmentation2/TEST4
- src/test/obj_fragmentation2/TEST5
- src/test/obj_fragmentation2/TEST6
- src/test/obj_fragmentation2/TEST7
- src/test/obj_fragmentation2/obj_fragmentation2.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3001)
> test: add 2MB workload to obj_fragmentation2

- src/common/file.h
- src/common/mmap.h
- src/common/os.h
- src/common/os_thread.h
- src/common/set.h
- src/common/util.h
- src/common/util_pmem.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3002)
> common: fix extern "C" usage in internal headers

- src/test/pmempool_transform_remote/node_0_out10.log.match
- src/test/pmempool_transform_remote/node_0_out12.log.match
- src/test/pmempool_transform_remote/node_0_out14.log.match
- src/test/pmempool_transform_remote/node_1_out16.log.match
- src/test/pmempool_transform_remote/node_1_out18.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3008)
> test: add last shutdown to match files

- src/common/os_dimm_ndctl.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3009)
> common: do not fail if dimm doesn't support USC

- src/test/obj_oid_thread/obj_oid_thread.c
- src/test/obj_oid_thread/obj_oid_thread.vcxproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3004)
>  test: add tests for pmemobj_oid 

- README.md
Ref: pmem/issues#893
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3011)
> doc: win: use pmdk from vcpkg

- src/test/obj_basic_integration/obj_basic_integration.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3012)
> test: add test case for layout

- src/test/obj_basic_integration/obj_basic_integration.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3014)
> test: add test case for pmemobj_root_size

- src/examples/libpmemobj++/pmpong/Makefile
- src/libpmemobj/cuckoo.c
- src/test/obj_cuckoo/obj_cuckoo.c
small typo fixes + commit guide for first pull request to pmdk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3019)
> obj: fix some typos around cuckoo hashmap

- doc/Makefile
- doc/generated/pmemobj_defer_free.3
- doc/libpmemobj/pmemobj_action.3.md
Ref: pmem/issues#896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3023)
> doc: fix pmemobj_defer_free linking

- src/libpmempool/replica.c
- src/libpmempool/sync.c
- src/test/pmempool_sync/out10.log.match
- src/test/pmempool_sync/out12.log.match
- src/test/pmempool_sync/out24.log.match
- src/test/pmempool_sync/out9.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3024)
> pool: do not overwrite the root cause of the failure

- src/libpmemobj/list.c
- src/libpmemobj/list.h
- src/libpmemobj/obj.c
- src/test/obj_basic_integration/obj_basic_integration.c
- src/test/obj_list/obj_list.c
The last time it worked is 1.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3036)
> obj: fix type numbers for pmemobj_list_insert_new

- doc/librpmem/rpmem_persist.3.md
- src/benchmarks/obj_pmalloc.cpp
- src/common/mmap_windows.c
- src/common/os_thread_windows.c
- src/common/valgrind/valgrind.h
- src/jemalloc/src/jemalloc.c
- src/test/RUNTESTS.PS1
- src/test/rpmem_fip/rpmem_fip_test.c
- src/test/unittest/unittest.ps1
- src/test/unittest/unittest.sh
- utils/pmdk.spec.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3035)
> common: fix typo

- src/test/pmempool_sync/out25.log.match
It fixes regression introduced by the commit 491f0e88
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3037)
> test: fix pmempool_sync/TEST25 match file

- src/test/Makefile
- src/test/pmem_reorder_simple/.gitignore
- src/test/pmem_reorder_simple/Makefile
- src/test/pmem_reorder_simple/README
- src/test/pmem_reorder_simple/TEST0
- src/test/pmem_reorder_simple/TEST1
- src/test/pmem_reorder_simple/outfile0.log.match
- src/test/pmem_reorder_simple/pmem_reorder_simple.c
- src/test/unittest/unittest.sh
- src/tools/pmreorder/.gitignore
- src/tools/pmreorder/binaryoutputhandler.py
- src/tools/pmreorder/consistencycheckwrap.py
- src/tools/pmreorder/loggingfacility.py
- src/tools/pmreorder/memoryoperations.py
- src/tools/pmreorder/operationfactory.py
- src/tools/pmreorder/opscontext.py
- src/tools/pmreorder/pmreorder.py
- src/tools/pmreorder/reorderengines.py
- src/tools/pmreorder/reorderexceptions.py
- src/tools/pmreorder/statemachine.py
- src/tools/pmreorder/utils.py
**!!!** Merge after https://github.com/pmem/pmdk/pull/2987 - rm pcommit from pmdk
Draft version of pmreorder tool.
The most important TODO (separate PR):
- obj tests
- parameterize reorder engine type
- docs?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/2964)
> common: store reordering tool

- src/libpmemobj/list.c
- src/libpmemobj/list.h
- src/test/obj_layout/obj_layout.c
- src/test/obj_list/mocks_windows.h
- src/test/obj_list/obj_list_mocks_palloc.c
- src/test/tools/pmemspoil/spoil.c
- src/tools/pmempool/info_obj.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3021)
> obj: use palloc_reserve in lists API

- src/common/valgrind/README
- src/common/valgrind/drd.h
- src/common/valgrind/helgrind.h
- src/common/valgrind/memcheck.h
- src/common/valgrind/pmemcheck.h
- src/common/valgrind/valgrind.h
- src/common/valgrind_internal.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3020)
> common: pmemcheck DEFAULT_REORDER support

- src/common/set.c
- src/test/obj_extend/TEST8
- src/test/obj_extend/err8.log.match
- src/test/obj_extend/obj_extend.c
Ref: pmem/issues#900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3031)
> common: fix address space reservation decrease error handling

- .travis.yml
- src/common.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3033)
> common: always build with ndctl

- src/test/obj_memcheck/obj_memcheck.c
- src/test/obj_pmalloc_mt/obj_pmalloc_mt.c
- src/test/obj_pmalloc_rand_mt/obj_pmalloc_rand_mt.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3042)
> test: log using framework functions

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3048)
> doc: ndctl is required to build pmdk

- src/test/pmempool_create/TEST10
- src/test/pmempool_create/TEST11
- src/test/pmempool_create/TEST12
- src/test/pmempool_create/out10.log.match
- src/test/pmempool_create/out11.log.match
- src/test/pmempool_create/out12.log.match
- src/test/pmempool_info/TEST24
- src/test/pmempool_info/TEST25
- src/test/pmempool_info/out24.log.match
- src/test/pmempool_info/out25.log.match
Ref: pmem/issues#897
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3046)
> test: add expect_bad_blocks after injecting errors

- src/test/common_badblock.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3054)
> test: fix expect_bad_blocks

- utils/check_whitespace
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3055)
> common: add cmake files to check_whitespace

- src/tools/Makefile
- src/tools/pmreorder/Makefile
- src/tools/pmreorder/binaryoutputhandler.py
- src/tools/pmreorder/consistencycheckwrap.py
- src/tools/pmreorder/memoryoperations.py
- src/tools/pmreorder/operationfactory.py
- src/tools/pmreorder/opscontext.py
- src/tools/pmreorder/pmreorder.py
- src/tools/pmreorder/reorderengines.py
- src/tools/pmreorder/reorderexceptions.py
- src/tools/pmreorder/statemachine.py
- src/tools/pmreorder/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3044)
> pmreorder: add flake8 check and fix issues

- src/test/common_badblock.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3058)
> test: print ndctl list -M to PREP_LOG_FILE

- src/test/obj_pool_lookup/obj_pool_lookup.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3066)
> test: add test cases for pmemobj_pool_by_ptr and pmemobj_pool_by_oid

- utils/docker/images/push-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3069)
> common: trigger docker update

- src/test/obj_basic_integration/obj_basic_integration.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3070)
> test: add test case for function pmemobj_alloc_usable_size

- src/test/pmem_reorder_simple/outfile0.log.match
- src/test/pmem_reorder_simple/pmem_reorder_simple.c
- src/tools/pmreorder/memoryoperations.py
- src/tools/pmreorder/opscontext.py
- src/tools/pmreorder/statemachine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3067)
> pmreorder: add support for default_engine

- doc/libpmemobj/pmemobj_action.3.md
- src/include/libpmemobj/action_base.h
- src/libpmemobj/memops.c
- src/libpmemobj/obj.c
- src/test/obj_action/obj_action.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3076)
>  obj: remove actions limit for the atomic publish

- src/test/Makefile
- src/test/obj_reorder_basic/.gitignore
- src/test/obj_reorder_basic/Makefile
- src/test/obj_reorder_basic/README
- src/test/obj_reorder_basic/TEST0
- src/test/obj_reorder_basic/obj_reorder_basic.c
- src/test/unittest/unittest.h
- src/test/unittest/ut.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3045)
> pmreorder: add obj test

- _layouts/manual.html
- index.md
- pmreorder/index.md
Merge after #3092
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3091)
> doc: gh-pages: add pmreorder man page

- src/test/unittest/unittest.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3107)
> test: fix corner case for dump_last_n_lines function

- src/PMDK.sln
- src/test/obj_ctl_alloc_class/TEST0.PS1
- src/test/obj_ctl_alloc_class/obj_ctl_alloc_class.vcxproj
- src/test/obj_ctl_alloc_class/obj_ctl_alloc_class.vcxproj.filters
- src/windows/include/sys/resource.h
Ref: pmem/issues#902
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3112)
> test: add obj_ctl_alloc_class windows test

- README.md
- Added table of contents
- Added navigatable headers that draw attention to key areas
- Contents didn't change much, just reorganized it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3109)
> doc: Refactor README.md

- src/common/os_dimm_windows.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3111)
> Os dimm windows fix

- src/common/os_dimm_ndctl.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3118)
> common: fix device dax parsing in os_dimm_ndctl

- src/test/util_badblock/util_badblock.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3123)
> test: fix error handling in util_badblock test

- src/common/os_badblock.h
- src/common/os_dimm_ndctl.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3132)
> common: add some comments about bad block structures

- src/common/ctl.c
- src/libpmemobj/obj.c
- src/test/util_ctl/util_ctl.c
Ref: pmem/issues#917
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3100)
> common: fix ctl_load_config during libpmemobj initialization

- doc/libpmemobj/oid_is_null.3.md
- src/include/libpmemobj/base.h
- src/libpmemobj/palloc.c
- src/libpmemobj/sync.c
- src/test/Makefile
- src/test/obj_direct_volatile/TEST1
- src/test/obj_direct_volatile/obj_direct_volatile.c
- src/test/obj_pmemcheck/.gitignore
- src/test/obj_pmemcheck/Makefile
- src/test/obj_pmemcheck/TEST0
- src/test/obj_pmemcheck/obj_pmemcheck.c
- src/test/obj_pmemcheck/pmemcheck0.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3128)
> obj: pmemobj_volatile changes

- src/examples/libpmemobj/map/mapcli.c
- src/examples/libpmemobj/tree_map/btree_map.c
- src/test/ex_libpmemobj/TEST22
- src/test/ex_libpmemobj/TEST22.PS1
- src/test/ex_libpmemobj/TEST23
- src/test/ex_libpmemobj/TEST23.PS1
- src/test/ex_libpmemobj/TEST24
- src/test/ex_libpmemobj/TEST24.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3134)
> examples: fix bugs in btree & add simple tests for btree, rtree and rbtree

- src/test/daxio/TEST0
- src/test/daxio/TEST3
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3139)
> test: fix daxio input

- src/libpmemobj/ctl.c
- src/libpmemobj/list.c
- src/libpmemobj/list.h
- src/libpmemobj/obj.c
- src/test/obj_basic_integration/obj_basic_integration.c
- src/test/obj_ctl/obj_ctl.c
- src/test/obj_list/obj_list.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3142)
> [1.4] Fixes

- src/libpmemblk/libpmemblk.c
- src/libpmemlog/libpmemlog.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3143)
> blk/log: fix FATAL message

- src/test/obj_reorder_basic/TEST0
- src/test/pmem_reorder_simple/TEST0
- src/test/pmem_reorder_simple/TEST1
- src/test/pmem_reorder_simple/TEST2
- src/test/pmem_reorder_simple/TEST3
- src/test/pmem_reorder_simple/TEST4
- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3145)
> test: add require pmemcheck version support

- src/test/obj_reorder_basic/TEST0
- src/test/pmem_reorder_simple/TEST0
- src/test/pmem_reorder_simple/TEST1
- src/test/pmem_reorder_simple/TEST2
- src/test/pmem_reorder_simple/TEST3
- src/test/pmem_reorder_simple/TEST4
- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3152)
> test: reorganize pmemcheck version detection

- doc/pmreorder/pmreorder.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3141)
> doc: update pmreorder man page

- doc/libpmemobj/pmemobj_open.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3153)
> Fixing misspell in pmemobj_open doc

- src/examples/libpmemobj/hashmap/hashmap_rp.c
- src/libpmemobj/heap.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3157)
> obj: coverity fixes

- CODING_STYLE.md
- doc/libvmem/vmem_malloc.3.md
- doc/pmreorder/pmreorder.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3160)
> doc: fix mispelling and update commit guidelines

- src/test/memcheck-dlopen.supp
- src/test/unittest/unittest.sh
Ref: pmem/issues#925
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3159)
> test: suppress memcheck error when using dlopen

- src/tools/pmempool/output.c
- src/tools/pmempool/output.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3158)
> pool: improve incompat feature detection

- src/test/ctl_prefault/ctl_prefault.c
Ref: pmem/issues#924
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3168)
> test: fix ctl_prefault for huge pages

- src/test/tools/obj_verify/obj_verify.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3167)
> test: fix creating/opening pools in obj_verify

- src/libpmempool/check_sds.c
- src/libpmempool/replica.c
- src/test/util_sds/util_sds.c
Ref: pmem/issues#919
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3175)
> pool: adding error handling of shutdown_state_add_part

- src/test/pmempool_sync/out25.log.match
Ref: pmem/pmdk#3174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3182)
> test: generalize pmempool info match files (fix)

- src/libpmem/pmem.c
- src/libpmem/pmem_posix.c
- src/libpmem/pmem_windows.c
- src/test/pmem_is_pmem/out0.log.match
- src/test/pmem_is_pmem/out1.log.match
- src/test/pmem_is_pmem/out2.log.match
- src/test/pmem_is_pmem/out3.log.match
- src/test/pmem_is_pmem/out4.log.match
- src/test/pmem_is_pmem/out5.log.match
- src/test/pmem_is_pmem/pmem_is_pmem.c
- src/test/pmem_is_pmem_posix/out0.log.match
- src/test/pmem_is_pmem_posix/out1.log.match
- src/test/pmem_is_pmem_posix/out2.log.match
Ref: pmem/issues#836
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3164)
> pmem: fix inconsistency in is_pmem_direct

- src/common/file_posix.c
- src/common/file_windows.c
- src/common/os_auto_flush_linux.c
- src/common/os_dimm_ndctl.c
- src/common/out.c
- src/common/uuid.c
- src/libpmempool/check_pool_hdr.c
- src/libpmempool/check_util.c
- src/librpmem/rpmem.c
- src/test/obj_direct/obj_direct.c
- src/test/obj_oid_thread/obj_oid_thread.c
- src/test/obj_pool_lookup/obj_pool_lookup.c
- src/test/tools/ctrld/ctrld.c
- src/test/unittest/ut.c
- src/tools/pmempool/output.c
- src/tools/rpmemd/rpmemd_config.c
- src/tools/rpmemd/rpmemd_db.c
- src/tools/rpmemd/rpmemd_log.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3183)
> common: add snprintf return value to error message

- src/test/pmempool_check/out25.log.match
- src/test/pmempool_check/out27.log.match
Ref: pmem/pmdk#3163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3188)
> pool: fix shutdown state check (fix)

- utils/build-rpm.sh
- utils/pkg-common.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3187)
> common: add openSUSE to pkg common get_os

- src/benchmarks/pmembench.cpp
- src/benchmarks/poolset_util.cpp
- src/common/badblock.c
- src/common/file.c
- src/common/file.h
- src/common/set.c
- src/libpmempool/check_backup.c
- src/libpmempool/pool.c
- src/libpmempool/replica.c
- src/libpmempool/transform.c
- src/test/obj_pmalloc_mt/Makefile
- src/test/obj_pmalloc_mt/obj_pmalloc_mt.c
- src/test/obj_pmalloc_rand_mt/Makefile
- src/test/obj_pmalloc_rand_mt/obj_pmalloc_rand_mt.c
- src/test/obj_tx_invalid/Makefile
- src/test/obj_tx_invalid/obj_tx_invalid.c
- src/test/remote_basic/Makefile
- src/test/remote_basic/node_0_err0.log.match
- src/test/remote_basic/node_0_err1.log.match
- src/test/remote_basic/node_0_trace0.log.match
- src/test/remote_basic/node_0_trace1.log.match
- src/test/remote_basic/remote_basic.c
- src/test/rpmemd_db/rpmemd_db_test.c
- src/tools/pmempool/create.c
- src/tools/pmempool/rm.c
and replace all usages of os_access(..., F_OK) with this function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3189)
> common: implement util_file_exists

- doc/libpmempool/pmempool_sync.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3195)
> doc: update-pmempool-flags

- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3214)
> test: fix fatal typo in require_command_node()

- src/rpmem_common/rpmem_fip_common.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3213)
> rpmem: fix dead loop if unknown provider returned.

- src/common/badblock.c
- src/common/set.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3216)
> common: fix error handling in util_pool_open/create_uuids

- Makefile
- utils/copy-source.sh
Ref: pmem/issues#918
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3199)
> common: fix building packages

- src/common/set.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3224)
> common: do not overwrite the real error message

- src/test/vmmalloc_dummy_funcs/vmmalloc_dummy_funcs.c
Both declarations are required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3204)
> test: Correct fix for PR #3191

- doc/libpmemobj/pmemobj_action.3.md
- src/libpmemobj/obj.c
Ref: pmem/issues#904
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3229)
> obj: forbid calling pmemobj_defer_free on NULL

- doc/libpmemobj/oid_is_null.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3230)
> doc: explain difficulties with pmemobj_volatile

- src/test/pmempool_info/TEST14
Ref: pmem/pmdk#3181
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3231)
> test: pmempool_info sds check fix

- src/test/pmreorder_simple/TEST3
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3228)
> test: pmreorder_simple fix test description

- src/tools/pmempool/check.c
- src/tools/pmempool/check.h
- src/tools/pmempool/convert.c
- src/tools/pmempool/convert.h
- src/tools/pmempool/create.c
- src/tools/pmempool/create.h
- src/tools/pmempool/dump.c
- src/tools/pmempool/dump.h
- src/tools/pmempool/info.c
- src/tools/pmempool/info.h
- src/tools/pmempool/pmempool.c
- src/tools/pmempool/rm.c
- src/tools/pmempool/rm.h
- src/tools/pmempool/synchronize.c
- src/tools/pmempool/synchronize.h
- src/tools/pmempool/transform.c
- src/tools/pmempool/transform.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3241)
> pool: use "const" more

- src/test/remote_obj_basic/TEST0
- src/test/remote_obj_basic/TEST1
- src/test/remote_obj_basic/TEST2
- src/test/remote_obj_basic/TEST3
- src/test/rpmemd_db/test0-root/test0-pool0.set
- src/test/rpmemd_db/test0-root/test0-pool1.set
- src/test/rpmemd_db/test1-root/test1-pool0.set
- src/test/rpmemd_db/test1-root/test1-pool1.set
Ref: pmem/pmdk#1378
Ref: pmem/pmdk#2346
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3243)
> test: fix paths + cleanup

- src/test/obj_first_next/obj_first_next.c
Ref: pmem/issues#940
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3248)
> test: add missing persist to obj_first_next

- doc/pmreorder/pmreorder.1.md
- src/test/pmreorder_simple/README
- src/test/pmreorder_simple/TEST0
- src/test/pmreorder_simple/TEST1
- src/test/pmreorder_simple/TEST2
- src/test/pmreorder_simple/TEST3
- src/test/pmreorder_simple/TEST4
- src/test/pmreorder_stack/README
Fixing few minor issues in documentation for pmreorder, including comments in tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3234)
> doc: Corrections in pmreorder docs

- src/tools/pmempool/synchronize.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3254)
> pool: fix setting pmempool sync flags

- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3252)
> test: do not overwrite the PREP log file

- src/test/obj_mem/obj_mem.c
- src/test/obj_memops/obj_memops.c
- src/test/pmem_memset/pmem_memset.c
Ref: pmem/issues#942 pmem/issues#943 pmem/issues#945
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3253)
> test: add missing persists

- utils/build-dpkg.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3255)
> common: fix lib version in dpkg

- ChangeLog
- utils/build-dpkg.sh
Ref:pmem/issues#775
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3250)
> common: fix building debian packages

- src/test/tools/fallocate_detect/fallocate_detect.c
On btrfs in the usual mode (ie, !nocow), every write goes to a new area (for data consistency reasons) — effectively causing a fault every time (per extent per filesystem commit).  This obviously makes prefault tests fail.
For btrfs, this is valid and expected.  Too bad, this can also happen on XFS if reflinks are involved (and incoming version of coreutils "cp" enables them by default), but let's discuss that elsewhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3256)
> disable a failing test on btrfs

- src/libpmemobj/tx.c
Transaction abort handler released the allocated memory back
to the heap before pmemcheck state was updated to reflect
that those allocated blocks no longer belong to this
transaction. This race caused erroneous reports about adding
snapshots from multiple threads.
Ref: pmem/issues#948
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3257)
> obj: fix pmemcheck macros race in tx_abort

- src/libpmemobj/memops.c
- src/libpmemobj/obj.c
- src/libpmemobj/tx.c
- src/test/obj_action/obj_action.c
This was difficult to trigger due to allocator entry merging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3264)
> two memops fixes

- utils/docker/test_package/.gitignore
- utils/docker/test_package/Makefile
- utils/docker/test_package/README
- utils/docker/test_package/test_package.c
Only libpmemobj package is verified for now. But we can add checks for other libraries as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3259)
> common: verify installed packages on travis

- utils/build-dpkg.sh
Combination of #3235 and #3250 was never tested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3266)
> common: fix Debian package building with libndctl and libfabric

- src/libpmemobj/ulog.c
Taking cache misses on memcpy seems to be faster than doing so
during the checksum calculation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3268)
> obj: memcpy ulog buffer before checksumming

- src/test/obj_list/obj_list_mocks.c
- src/test/obj_pmalloc_basic/obj_pmalloc_basic.c
Ref: pmem/issues#949
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3269)
> test: replace memcpy/memset with pmem_memcpy/memset

- src/libpmemobj/ulog.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3276)
> obj: add ASSERT to silence static analysis

- src/libpmempool/sync.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3270)
> pool: fix a suspicious code in sync_badblocks_assign_healthy_replica()

- src/tools/pmempool/common.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3279)
> pool: handle vsnprintf return value

- src/test/pmempool_sync_remote/TEST20
- src/test/pmempool_sync_remote/TEST21
Ref: pmem/pmdk#3265
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3281)
> test: enable shutdown state in pmempool_sync_remote (fix)

- src/common/util.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3278)
>  common: prevent using uninitialized array

- src/tools/pmempool/output.c
Ref: pmem/pmdk#3184
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3282)
> pool: fix features detection

- src/Makefile
- src/tools/pmreorder/.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3284)
> common: add pmreorder to make install

- doc/libpmempool/pmempool_feature_query.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3285)
> doc: fix pmempool_feature_* args

- doc/pmreorder/pmreorder.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3290)
>  doc: pmreorder fix code block format

- utils/SRCVERSION.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3273)
> common: remove one 0 from revison on windows

- doc/pmreorder/pmreorder.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3295)
> doc: pmreorder: typo fix

- src/tools/daxio/daxio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3296)
> daxio: remove unused flags assignment

- src/test/obj_heap/obj_heap.c
- src/test/obj_persist_count/obj_persist_count.c
- src/test/pmempool_info/TEST12
- src/tools/pmempool/info_obj.c
Ref: pmem/issues#953 pmem/issues#954 pmem/issues#955
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3306)
> various memcheck fixes

- doc/pmreorder/pmreorder.1.md
- utils/build-dpkg.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3297)
>  common: pmreorder: dpkg build

- src/Makefile
- utils/pmdk.spec.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3298)
> common: pmreorder: rpm build

- src/tools/daxio/daxio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3313)
> daxio: NULL initialize variables

- src/common/util.h
- src/common/valgrind_internal.h
- src/libpmemobj/obj.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3307)
> common: add pobj_emit_log

- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3330)
> test: add valgrind warning to ignored

- src/libpmempool/replica.c
Ref: pmem/issues#960
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3329)
> pool: transform: fix invalid errno

- doc/pmempool/pmempool-convert.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3321)
> doc: add link to pmdk-convert tool

- src/libpmempool/replica.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3333)
> pool: check POOL_FEAT_SDS in pmempool-sync/transform

- src/test/pmempool_sync_remote/TEST0
- src/test/pmempool_sync_remote/TEST1
- src/test/pmempool_sync_remote/TEST2
- src/test/pmempool_sync_remote/TEST20
- src/test/pmempool_sync_remote/TEST21
- src/test/pmempool_sync_remote/TEST3
- src/test/pmempool_sync_remote/TEST4
- src/test/pmempool_sync_remote/TEST5
- src/test/pmempool_sync_remote/TEST6
- src/test/pmempool_sync_remote/config.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3332)
> test: fix setting require_fs_type in pmempool_sync_remote tests

- src/benchmarks/pmembench.cpp
- do not pass two variables storing #threads and #ops
- store current #threads and #ops in args
- restore #threads and #ops after each pass
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3317)
> benchmark: calculating #threads and #ops

- src/libpmempool/replica.c
- src/libpmempool/transform.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3339)
>  pool: set ignore_sds flag basing on features read from the header

- src/test/common_badblock.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3331)
> test: fix resetting environment before nfit tests

- doc/libpmemobj/pmemobj_ctl_get.3.md
- src/libpmemobj/pmalloc.c
- src/libpmemobj/tx.c
- src/test/obj_ctl_alloc_class/obj_ctl_alloc_class.c
- src/test/tools/obj_verify/obj_verify.c
... to speed it up.
Hopefully this will resolve timeouts in pmempool_sync_remote tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3338)
> test: use transactions in obj_verify

- src/test/rpmemd_db/rpmemd_db_test.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3341)
> test: do not set random compat features, but zero it

- src/test/pmempool_sync/TEST28
- src/test/pmempool_sync/TEST30
- src/test/pmempool_sync/TEST31
- src/test/pmempool_sync/TEST38
- src/test/pmempool_sync/TEST39
- src/test/pmempool_sync/TEST40
- src/test/pmempool_sync/TEST41
- src/test/pmempool_sync_remote/TEST22
- src/test/pmempool_sync_remote/TEST23
- src/test/pmempool_sync_remote/TEST24
- src/test/pmempool_sync_remote/TEST25
- src/test/pmempool_sync_remote/TEST26
- src/test/pmempool_sync_remote/TEST27
- src/test/pmempool_sync_remote/TEST28
- src/test/pmempool_sync_remote/TEST29
- src/test/pmempool_sync_remote/TEST30
- src/test/pmempool_sync_remote/TEST31
- src/test/pmempool_sync_remote/TEST32
- src/test/pmempool_sync_remote/TEST33
- src/test/pmempool_sync_remote/TEST34
- src/test/pmempool_sync_remote/TEST35
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3346)
> test: insert expect_bad_blocks where bad blocks are required

- src/common/badblock.c
- src/common/out.h
- src/common/set.c
- src/common/set.h
- src/libpmemobj/heap.c
- src/libpmempool/replica.c
- src/tools/rpmemd/rpmemd_log.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3352)
> Klocwork-inspired fixes

- doc/daxio/daxio.1.md
Ref: pmem/issues#969
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3347)
> doc: add --clear-bad-blocks option to manual

- src/libpmemobj/memops.c
- src/libpmemobj/ulog.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3357)
> obj: add ASSERTs after ulog offset calculation

- src/test/pmempool_sync/out28.log.match
- src/test/pmempool_sync/out30.log.match
- src/test/pmempool_sync/out31.log.match
- src/test/pmempool_sync/out38.log.match
- src/test/pmempool_sync/out39.log.match
- src/test/pmempool_sync/out40.log.match
- src/test/pmempool_sync/out41.log.match
They were supposed to be added in the commit 2022b236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3361)
> test: add missing changes in match files

- src/common/os_auto_flush_linux.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3358)
> common: verify index of array in check_cpu_cache()

- src/benchmarks/rpmem_persist.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3360)
> benchmark: fix klocwork issue #222663

- doc/libpmemblk/pmemblk_ctl_get.3.md
- doc/libpmemlog/pmemlog_ctl_get.3.md
- doc/libpmemobj/pmemobj_ctl_get.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3350)
> doc: ctl: sds.at_create

- src/test/pmempool_sync_remote/TEST32
- src/test/pmempool_sync_remote/TEST33
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3367)
> test: fix remote mounting directory in 2 pmempool_sync_remote tests

- src/common/util_posix.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3359)
> common: fix klocwork issue #222263

- src/common/badblock_linux.c
- src/common/extent_linux.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3370)
> common: add some logs useful to debug bad blocks

- src/benchmarks/benchmark_worker.cpp
- src/benchmarks/pmembench.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3371)
> benchmark: handle worker init fail

- doc/pmempool/pmempool-feature.1.md
- src/test/common_badblock.sh
- src/test/testconfig.sh.example
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3372)
> common: update resource paths to the platform-independent ones

- src/tools/daxio/daxio.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3378)
> daxio: fix daxio help message

- doc/libpmemobj/oid_is_null.3.md
- doc/libpmemobj/pmemobj_memcpy_persist.3.md
- src/include/libpmemobj/base.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3376)
> doc: minor improvements

- src/test/libpmempool_feature/TEST1
- src/test/libpmempool_feature/TEST2
- src/test/pmempool_check/TEST28
- src/test/pmempool_check/TEST29
- src/test/pmempool_check/TEST30
- src/test/pmempool_feature/TEST15
- src/test/pmempool_info/TEST14
- src/test/tools/usc_permission_check/.gitignore
- src/test/tools/usc_permission_check/Makefile
- src/test/tools/usc_permission_check/usc_permission_check.c
- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3381)
> Add require_usc_permission to tests reading usc

- doc/pmempool/pmempool-info.1.md
- src/libpmempool/check_bad_blocks.c
- src/test/pmempool_check/TEST31
- src/test/pmempool_check/TEST32
- src/test/pmempool_check/out31.log.match
- src/test/pmempool_check/out32.log.match
- src/test/pmempool_info/TEST24
- src/test/pmempool_info/TEST25
- src/test/pmempool_sync/TEST27
- src/test/pmempool_sync/TEST28
- src/test/pmempool_sync/TEST30
- src/test/pmempool_sync/TEST31
- src/test/pmempool_sync/TEST38
- src/test/pmempool_sync/TEST39
- src/test/pmempool_sync/TEST40
- src/test/pmempool_sync/TEST41
- src/test/pmempool_sync/TEST42
- src/test/pmempool_sync/TEST44
- src/test/pmempool_sync/TEST45
- src/test/pmempool_sync/TEST46
- src/test/pmempool_sync/TEST47
- src/test/pmempool_sync/TEST48
- src/test/pmempool_sync/TEST49
- src/test/pmempool_sync/TEST50
- src/test/pmempool_sync/TEST51
- src/test/pmempool_sync/TEST52
- src/test/pmempool_sync/TEST53
- src/tools/pmempool/info.c
- src/tools/pmempool/info.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3377)
> common: check CHECK_BAD_BLOCKS compat feature in pmempool-info

- src/common/pool_hdr.c
- src/libpmempool/feature.c
- src/test/libpmempool_feature/TEST0
- src/test/libpmempool_feature/TEST0.PS1
- src/test/libpmempool_feature/TEST1
- src/test/libpmempool_feature/TEST1.PS1
- src/test/libpmempool_feature/TEST2w.PS1
- src/test/libpmempool_feature/TEST3
- src/test/libpmempool_feature/TEST3.PS1
- src/test/libpmempool_feature/common.PS1
- src/test/libpmempool_feature/common.sh
- src/test/libpmempool_feature/grep3.log.match
- src/test/pmempool_feature/common.PS1
- src/test/pmempool_feature/common.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3375)
>  test: pmempool_feature_* + invalid features in target pool

- ChangeLog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3384)
> doc: add change log for 1.5 release

- src/test/pmem_deep_persist/TEST9
- src/test/pmem_deep_persist/pmem_deep_persist.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3387)
> test: fix int overflow in pmem_deep_persist test

- src/test/pmem_deep_persist/pmem_deep_persist.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3389)
> test: do not store -1 value in unsigned variable

- src/test/pmempool_transform/TEST11
- src/test/pmempool_transform/TEST14
- src/test/pmempool_transform/TEST15
- src/test/pmempool_transform/TEST18
- src/test/unittest/unittest.sh
require_free_space:
- pmempool_transform/TEST14
- pmempool_transform/TEST18
require_root_object_size:
- pmempool_transform/TEST11
- pmempool_transform/TEST15
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3388)
>  test: add missing requirements

- pmempool/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3405)
> doc: add pmdk-convert 1.5 link

- doc/pmreorder/pmreorder.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3404)
> doc: fix pmreorder style (on web page)

- src/test/obj_many_size_allocs/TEST0.PS1
- src/test/obj_many_size_allocs/obj_many_size_allocs.vcxproj
- src/test/obj_many_size_allocs/obj_many_size_allocs.vcxproj.filters
Ref:pmem/issues#902
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3355)
> test: add obj_many_size_allocs windows test

- src/libpmempool/feature.c
- src/test/tools/usc_permission_check/usc_permission_check.c
- src/test/unittest/unittest.sh
Fix few misspells and empty line
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3385)
> common: fix minor misspellings

- src/test/unittest/unittest.ps1
- src/test/unittest/unittest.sh
The Braille text spells "NVML", we want the new name...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3410)
> test: replace "NVML" with "PMDK"

- doc/pmreorder/pmreorder.1.md
- src/common/valgrind_internal.h
- src/libpmem/pmem.c
- src/test/pmreorder_simple/README
- src/test/pmreorder_simple/TEST1
- src/test/pmreorder_simple/TEST2
- src/test/pmreorder_simple/TEST4
- src/test/pmreorder_simple/TEST5
- src/test/pmreorder_simple/pmreorder5.conf
- src/test/pmreorder_simple/pmreorder_simple.c
There is some common parts with PR #3307
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3316)
> common: add pmem_emit_log

- utils/docker/images/Dockerfile.fedora-25
I need to add hub package before changes related to autodoc.
It should simplify local test process and it will be necessary anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3417)
> common: add hub to fedora Dockerfile

- src/test/obj_pool/TEST17
- src/test/unicode_api/TEST0
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3418)
> test: add 'require_command bc' to two tests

- src/test/tools/anonymous_mmap/check_max_mmap.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3424)
> test: fix check_max_mmap.sh script

- doc/libpmemobj/pmemobj_action.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3421)
> doc: add missing return type

- src/test/pmemobjcli/TEST2
- src/test/pmemobjcli/TEST2.PS1
- src/test/pmemobjcli/out2.log.match
- src/test/tools/pmemobjcli/README
- src/test/tools/pmemobjcli/pmemobjcli.c
- src/test/tools/pmemobjcli/pmemobjcli.vcxproj
... instead of #3225
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3425)
> test: add shortening option to pmemobjcli

- src/test/vmmalloc_dummy_funcs/libvmmalloc_dummy_funcs.map
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3427)
> test: hide unnecessary symbols

- utils/docker/images/install-valgrind.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3428)
> common: update valgrind to v3.14 in docker images

- src/common/vec.h
Ref: pmem/issues#977
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3437)
> common: fix memory leak in VEC_MOVE()

- src/common/badblock_ndctl.c
... and close with os_close.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3440)
> common: replace open with os open

- src/test/blk_non_zero/TEST6
- src/test/blk_non_zero/TEST6.PS1
- src/test/blk_non_zero/TEST7
- src/test/blk_non_zero/TEST7.PS1
- src/test/blk_non_zero/TEST8
- src/test/blk_non_zero/TEST8.PS1
- src/test/blk_rw/TEST8
- src/test/blk_rw/TEST8w.PS1
- src/test/blk_rw/TEST9
- src/test/blk_rw/TEST9w.PS1
- src/test/obj_pmalloc_rand_mt/TEST0
- src/test/obj_pmalloc_rand_mt/TEST1
- src/test/obj_pmalloc_rand_mt/TEST1.PS1
- src/test/pmempool_create/TEST2
- src/test/pmempool_create/TEST2.PS1
- src/test/unittest/unittest.ps1
- src/test/unittest/unittest.sh
- src/test/vmem_multiple_pools/TEST0
- src/test/vmem_multiple_pools/TEST0.PS1
- src/test/vmem_multiple_pools/TEST1
- src/test/vmem_multiple_pools/TEST1.PS1
- utils/build-dpkg.sh
- utils/pmdk.spec.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3420)
> test: minor improvements

- README.md
Strawberry perl have a simpler licence then Activeperl and is 100% free
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3439)
> doc: change recomended perl version to strawberry perl

- src/test/pmempool_info/TEST18w.PS1
- src/test/pmempool_info/TEST19w.PS1
- src/test/pmempool_info/err18w.log.match
- src/test/pmempool_info/err19w.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3443)
> test: fix two windows pmempool-info tests

- src/test/pmempool_rm/TEST10
- src/test/pmempool_rm/TEST10.PS1
Ref: pmem/issues#840
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3386)
> test: rm confirmation

- src/test/Makefile
- src/test/testconfig.sh.example
- src/test/tools/anonymous_mmap/Makefile
- src/test/tools/anonymous_mmap/check_max_mmap.sh
- src/test/unittest/unittest.sh
change makefiles and move global-check to annonymous_mmap
Makefile level
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3445)
> test: fix check-max-mmap

- .travis.yml
- CONTRIBUTING.md
- src/.clang-format
- src/benchmarks/log.cpp
- src/benchmarks/map_bench.cpp
- src/benchmarks/pmem_flush.cpp
- src/benchmarks/pmem_memset.cpp
- src/benchmarks/pmembench.cpp
- src/benchmarks/pmemobj_atomic_lists.cpp
- src/benchmarks/poolset_util.cpp
- src/benchmarks/rpmem_persist.cpp
- src/benchmarks/vmem.cpp
- src/common.inc
- src/test/vmmalloc_dummy_funcs/libvmmalloc_dummy_funcs.map
- utils/docker/build-local.sh
- utils/docker/build-travis.sh
- utils/docker/images/Dockerfile.fedora-28
- utils/docker/images/Dockerfile.ubuntu-18.04
- utils/docker/images/build-image.sh
- utils/docker/images/push-image.sh
- utils/docker/pull-or-rebuild-image.sh
- utils/docker/run-build-package.sh
- utils/style_check.sh
Merge after #3431.
Already tested with #3431.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3432)
> common: upgrade docker images

- src/common/sys_util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3459)
> common: sys_util.h requires out.h

- src/common/set.c
- src/common/util.c
- src/common/util.h
- src/test/pmempool_rm/TEST1.PS1
- src/test/pmempool_rm/TEST10.PS1
- src/test/pmempool_rm/TEST11
- src/test/pmempool_rm/TEST7
- src/test/pmempool_rm/TEST7.PS1
- src/tools/pmempool/common.c
- src/tools/pmempool/rm.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3423)
> Overhaul pmempool rm confirmation

- .codecov.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3460)
> common: add benchmarks to codecov ignore list

- src/test/pmempool_create/TEST13
- src/test/pmempool_create/TEST13.PS1
- src/tools/pmempool/create.c
Ref: pmem/issues#968
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3396)
> pool: fix pmempool create -M

- src/test/tools/anonymous_mmap/Makefile
pmem/issues#982
fix possible race in dependent targets
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3466)
> test: fix race in builiding targets

- src/test/tools/anonymous_mmap/check_max_mmap.sh
((val++)) is not safe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3475)
> test: fix incrementation formula in bash script

- src/benchmarks/benchmark.hpp
- src/common/util.h
- src/common/util_posix.c
- src/test/tools/pmemalloc/pmemalloc.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3476)
> common: follow inclusion convention of internal header files

- src/tools/pmreorder/operationfactory.py
Ref: pmem/issues#974
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3477)
> pmreorder: fix markers nontype issue

- src/common/mmap.c
- src/common/mmap_posix.c
- src/common/set.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3485)
> common: don't hide the real reason why mmap failed

- src/libpmem/pmem.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3486)
> pmem: fix error message of pmem_map_fileU

- src/test/pmem_deep_persist/pmem_deep_persist.vcxproj
- src/test/pmem_deep_persist/pmem_deep_persist.vcxproj.filters
I think our CI tests only each pull request on their own rather than the result of merging -- but even if it does the latter, a time gap between CI and accepting lets problems like this through.
UNTESTED -- I don't have a working Windows setup here; let's see what Appveyor says...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3495)
> test: unbreak recently merged tests wrt cuckoo -> critnib

- src/common/file.c
Dan Williams' patch to allow using newest and greatest way to access dax instances.
Original patch at https://lists.01.org/pipermail/linux-nvdimm/2019-January/019352.html — I've merely updated code formatting and commit's header to make our checkers happy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3503)
> common: update /sys/.../dax path

- src/benchmarks/pmembench.cpp
- src/librpmem/rpmem.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3507)
> benchmark: do not fail on pmempool_rm ENOENT

- doc/libpmemobj/pmemobj_open.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3521)
> doc: fix typos in pmemobj_open man page

- src/test/pmempool_rm/TEST10
- src/test/pmempool_rm/TEST10.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3520)
> test: redirect pmempool_rm/TEST10 output to file 

- doc/libpmemobj/pmemobj_ctl_get.3.md
- src/libpmemobj/heap.c
- src/libpmemobj/heap.h
- src/libpmemobj/pmalloc.c
- src/test/obj_ctl_arenas/TEST1
- src/test/obj_ctl_arenas/TEST1.PS1
- src/test/obj_ctl_arenas/obj_ctl_arenas.c
- src/test/obj_ctl_arenas/obj_ctl_arenas.vcxproj
- src/test/obj_ctl_arenas/obj_ctl_arenas.vcxproj.filters
This PR has a common commits with #3505.
After merge #3505 I will rebase this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3515)
>  obj: add CTL to get arena size and arena id per thread

- src/common/valgrind/README
- src/common/valgrind/pmemcheck.h
- src/common/valgrind/valgrind.h
- src/common/valgrind_internal.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3530)
> common: update Valgrind headers

- src/common/ctl.c
- src/common/ctl.h
- src/common/ctl_prefault.c
- src/common/ctl_sds.c
- src/common/set.c
- src/libpmemobj/alloc_class.c
- src/libpmemobj/bucket.h
- src/libpmemobj/container.h
- src/libpmemobj/container_ravl.c
- src/libpmemobj/container_seglists.c
- src/libpmemobj/ctl_debug.c
- src/libpmemobj/memblock.c
- src/libpmemobj/palloc.c
- src/libpmemobj/pmalloc.c
- src/libpmemobj/stats.c
- src/libpmemobj/tx.c
- src/librpmem/rpmem_fip.c
- src/librpmem/rpmem_util.c
- src/rpmem_common/rpmem_fip_common.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3534)
> common: minor constness fixes

- src/test/pmempool_create/TEST13
- src/test/pmempool_create/TEST13.PS1
- src/test/pmempool_create/err13.log.match
- src/test/pmempool_create/grep13w.log.match
- src/tools/pmempool/create.c
Ref: #3396
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3497)
> pool: pmempool create -M fixes

- src/examples/pmreorder/.gitignore
- src/examples/pmreorder/Makefile
- src/examples/pmreorder/README
- src/examples/pmreorder/pmreorder_list.c
- src/test/Makefile.inc
- src/test/ex_pmreorder/Makefile
- src/test/ex_pmreorder/README
- src/test/ex_pmreorder/TEST0
- src/test/ex_pmreorder/TEST1
- src/test/ex_pmreorder/pmreorder1.log.match
- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3457)
> example: add pmreorder simple example

- index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3542)
> doc: add pmdk-convert to main index.md

- src/libpmemobj/stats.c
- src/test/obj_ctl_stats/TEST1
- src/test/obj_ctl_stats/obj_ctl_stats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3545)
> obj: suppress pmemcheck warnings for statistics

- src/librpmem/rpmem_fip.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3552)
> rpmem: remove dead code

- utils/pmdk.spec.in
Ref: pmem/issues#1003
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3555)
> common: fix librpmem package dependency on suse

- doc/librpmem/rpmem_persist.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3558)
> doc: rpmem_deep_persist was missing

- doc/generated/pmemobj_tx_xalloc.3
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3561)
> doc: fix manpage alias

- src/include/libpmem.h
- src/include/libpmemblk.h
- src/include/libpmemlog.h
- src/include/libpmempool.h
- src/include/librpmem.h
- src/include/libvmem.h
- src/include/libvmmalloc.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3560)
> common: include headers outside of extern "C" block

- src/test/rpmem_addr_ext/node_1_rpmem0.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3564)
> test: rpmem_addr_ext missing space in the match

- src/test/pmempool_info/TEST18w.PS1
- src/test/pmempool_info/TEST19w.PS1
- src/test/pmempool_info/err18w.log.match
- src/test/pmempool_info/err19w.log.match
- src/tools/pmempool/info.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3571)
> test: (win) work around PowerShell's error stream issue

- utils/librpmem.pc.in
pmem → rpmem
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3567)
> rpmem: fix library name in .pc

- Makefile
- appveyor.yml
- src/Makefile
- src/test/.gitignore
- src/test/Makefile
- src/test/RUNTESTS.py
- src/test/env.py
- src/test/obj_basic_integration/TESTS.py
- src/test/testconfig.py.example
- src/test/testframework.py
- src/test/unittest/basetest.py
- src/test/unittest/configurator.py
- src/test/unittest/context.py
- src/test/unittest/helpers.py
- utils/docker/configure-tests.sh
Based on #3349 and #3209
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3456)
> test: introduce the python test framework

- src/test/vmmalloc_fork/TEST1
- src/test/vmmalloc_fork/TEST2
- src/test/vmmalloc_fork/TEST3
- src/test/vmmalloc_fork/TEST4
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3579)
> test: add space requirements to vmmalloc_fork tests

- src/common/set.c
- src/test/util_poolset/TEST4w.PS1
- src/test/util_poolset/TEST5
- src/test/util_poolset/TEST5w.PS1
- src/test/util_poolset/TEST6
- src/test/util_poolset/TEST6w.PS1
- src/test/util_poolset/TEST7
- src/test/util_poolset/TEST8
- src/test/util_poolset/out8.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3578)
> common: handle opening empty directory poolsets

- ChangeLog
- src/common/set.c
- src/include/libpmem.h
- src/include/libpmemblk.h
- src/include/libpmemlog.h
- src/include/libpmempool.h
- src/include/librpmem.h
- src/include/libvmem.h
- src/include/libvmmalloc.h
- src/test/pmempool_info/TEST18w.PS1
- src/test/pmempool_info/TEST19w.PS1
- src/test/pmempool_info/err18w.log.match
- src/test/pmempool_info/err19w.log.match
- src/test/rpmem_addr_ext/node_1_rpmem0.log.match
- src/test/util_poolset/TEST4w.PS1
- src/test/util_poolset/TEST5
- src/test/util_poolset/TEST5w.PS1
- src/test/util_poolset/TEST6
- src/test/util_poolset/TEST6w.PS1
- src/test/util_poolset/TEST7
- src/test/util_poolset/TEST8
- src/test/util_poolset/out8.log.match
- src/test/vmmalloc_fork/TEST1
- src/test/vmmalloc_fork/TEST2
- src/test/vmmalloc_fork/TEST3
- src/test/vmmalloc_fork/TEST4
- src/tools/pmempool/info.c
- utils/librpmem.pc.in
- utils/pkg-common.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3583)
> Merge back 1.5.1 to master

- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3582)
> test: fix appveyor build

- src/libpmemobj/critnib.c
Per a request in #3572, this replaces some duplicated code with gotos.
Contains PR#3572.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3573)
> obj: deduplicate some returns in critnib

- src/common/set.c
Ref: #3493
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3586)
> common: check if part is dev dax before fallocate

- src/benchmarks/pmembench.vcxproj.filters
- src/libpmemlog/libpmemlog.vcxproj.filters
- src/libpmemobj/libpmemobj.vcxproj.filters
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3588)
> common: fix adding .c files in .vcxproj files

- utils/pmdk.spec.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3590)
> common: fix build of rpm packages on suse

- src/test/obj_tx_lock/TEST0.PS1
- src/test/obj_tx_lock/TEST1
- src/test/obj_tx_lock/obj_tx_lock.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3591)
> test: split test obj_tx_lock into two test cases

- doc/libpmemobj/pmemobj_ctl_get.3.md
- src/common/ctl.h
- src/libpmemobj/heap.c
- src/libpmemobj/heap.h
- src/libpmemobj/pmalloc.c
- src/test/obj_ctl_arenas/TEST2
- src/test/obj_ctl_arenas/TEST2.PS1
- src/test/obj_ctl_arenas/TEST6
- src/test/obj_ctl_arenas/TEST6.PS1
- src/test/obj_ctl_arenas/obj_ctl_arenas.c
- src/test/obj_ctl_arenas/obj_ctl_arenas.vcxproj
- src/test/obj_ctl_arenas/obj_ctl_arenas.vcxproj.filters
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3531)
> obj: ctl arena create

- utils/docker/images/Dockerfile.fedora-28
Will be needed by #3436.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3594)
> common: install "hub" on Fedora Docker image

- src/test/pmem_is_pmem_posix/README
- src/test/pmem_is_pmem_posix/TEST4
- src/test/pmem_is_pmem_posix/TEST5
- src/test/pmem_is_pmem_posix/pmem_is_pmem_posix.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3584)
> pmem: add pmem_is_pmem_posix test, which uses fault_injection option

- .travis.yml
- utils/check-commit.sh
- utils/check-doc.sh
- utils/docker/build-local.sh
- utils/docker/build-travis.sh
- utils/docker/images/build-image.sh
- utils/docker/images/push-image.sh
- utils/docker/pull-or-rebuild-image.sh
Will be needed by #3436.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3595)
> common: introduce GITHUB_REPO and DOCKERHUB_REPO on Travis

- src/test/memcheck-ndctl.supp
- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3599)
> common: add ndctl memcheck supp file

- .travis.yml
- src/test/obj_tx_lock/TEST0
- src/test/obj_tx_lock/TEST0.PS1
- src/test/obj_tx_lock/TEST1
- src/test/obj_tx_lock/obj_tx_lock.c
- utils/check-commit.sh
- utils/check-doc.sh
- utils/docker/build-local.sh
- utils/docker/build-travis.sh
- utils/docker/images/build-image.sh
- utils/docker/pull-or-rebuild-image.sh
- utils/pmdk.spec.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3600)
> Merge back changes from stable-1.5

- doc/libpmemobj/pmemobj_action.3.md
- doc/libpmemobj/pmemobj_alloc.3.md
- doc/libpmemobj/pmemobj_ctl_get.3.md
- doc/libpmemobj/pmemobj_tx_alloc.3.md
- src/include/libpmemobj/action_base.h
- src/include/libpmemobj/base.h
- src/include/libpmemobj/tx_base.h
- src/libpmemobj/heap.c
- src/libpmemobj/heap.h
- src/libpmemobj/list.c
- src/libpmemobj/obj.c
- src/libpmemobj/obj.h
- src/libpmemobj/palloc.c
- src/libpmemobj/palloc.h
- src/libpmemobj/pmalloc.c
- src/libpmemobj/tx.c
- src/test/obj_ctl_arenas/TEST3
- src/test/obj_ctl_arenas/TEST3.PS1
- src/test/obj_ctl_arenas/TEST4
- src/test/obj_ctl_arenas/TEST4.PS1
- src/test/obj_ctl_arenas/TEST5
- src/test/obj_ctl_arenas/TEST5.PS1
- src/test/obj_ctl_arenas/obj_ctl_arenas.c
- src/test/obj_ctl_arenas/obj_ctl_arenas.vcxproj
- src/test/obj_ctl_arenas/obj_ctl_arenas.vcxproj.filters
- src/test/obj_heap/obj_heap.c
- src/test/obj_list/obj_list_mocks_palloc.c
- src/test/obj_pmalloc_basic/obj_pmalloc_basic.c
**New commits are:**
6c1c406 - obj: add support for POBJ_ARENA_ID flag
3f8253d - doc: add POBJ_ARENA_ID flag to mans
369077b - test: add test for POBJ_ARENA_ID
0830fb1 - obj: add MAX_DEFAILT_ARENAS
53c5d35 - obj: add heap.narenas.max CTL
The rest is common with: #3531
___________________________________________________________
TODO:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3562)
> obj: POBJ_ARENA_ID flag

- librpmem/index.md
- use a page aligned local memory pool
Ref: pmem/pmdk#1317
Preview: http://janekmi.github.io/pmdk/librpmem/
The complete example gist: [janekmi/47fa646ada72b27f77692672e9d7988e](https://gist.github.com/janekmi/47fa646ada72b27f77692672e9d7988e)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3607)
> doc: fix librpmem example

- src/libpmemobj/heap.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3606)
> obj: add macro to simplify arenas vec access

- src/test/libpmempool_rm/libpmempool_rm.c
- src/test/libpmempool_rm_remote/TEST4
- src/test/obj_rpmem_heap_interrupt/TEST0
- src/tools/rpmemd/rpmemd_db.c
Ref: pmem/issues#833
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3601)
> rpmem: lock file prior to unlink

- src/examples/pmreorder/pmreorder_list.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3608)
> examples: handle fopen in pmreorder list example

- doc/libpmemobj/pmemobj_ctl_get.3.md
- src/libpmemobj/heap.c
- src/libpmemobj/heap.h
- src/libpmemobj/pmalloc.c
- src/test/obj_ctl_arenas/obj_ctl_arenas.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3610)
> obj: limit automatic arenas to min 1

- src/test/ctl_cow/TEST3
- src/test/ctl_cow/ctl_cow.c
- src/test/ctl_cow/err3.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3616)
> test: check if opening dax pool fails when COW is set 

- src/test/pmempool_rm/TEST10
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3621)
> test: skip pmempool_rm/TEST10 under root

- src/libpmempool/replica.c
Ref: pmem/issues#977
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3622)
> pool: free bad_block vector

- src/common/file.c
- src/common/file.h
- src/common/os_dimm_ndctl.c
ref: pmem/issues#1031
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3617)
> common: do not use /dev to read fsdax dev id

- src/test/unittest/unittest.sh
Ref: pmem/issues#1012
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3624)
> test: valgrind dependency fix

- doc/pmreorder/pmreorder.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3632)
> doc: fix typo in pmreorder conf

- src/Makefile.inc
- src/common/os_auto_flush_linux.c
- src/common/valgrind_internal.h
Ref: pmem/issues#990
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3626)
> common: fix FreeBSD build

- src/test/pmempool_check/TEST16.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3637)
> test: fix pmempool_check test

- src/test/tools/pmemobjcli/pmemobjcli.c
Ref: pmem/issues#998
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3633)
> test: set *oid to OID_NULL

- src/test/obj_check_remote/TEST0
Ref: #3585
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3630)
> test: wait for rpmemd finish before file copy

- src/tools/pmempool/create.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3636)
> pool: minor fixes for pmempool create 

- src/libpmemobj/tx.c
Ref: pmem/issues#1028
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3640)
> obj: fix possible memory leak in tx_add_lock

- src/common/os_dimm_ndctl.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3631)
> common: do not start ARS before clearing bad blocks on DAX device

- cpp_obj/index.md
for stable-1.5 and stable-1.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3643)
> doc: add links to C++ documentation

- src/common/set.c
Ref: pmem/issues#1036
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3645)
> common: fix for pool_set error handling

- src/test/tools/pmemobjcli/pmemobjcli.c
Ref: pmem/issues#1037
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3646)
> test: set *oidp to OID_NULL

- README.md
- src/common.inc
- src/common/os_dimm_ndctl.c
- src/common/shutdown_state.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3638)
> common: add variable to force use of old ndctl API

- src/test/unittest/ut.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3649)
> tests: add variable to suppress badblocks FD leak in ndctl 63

- src/test/obj_critnib/TEST0
- src/test/obj_critnib/TEST0.PS1
- src/test/obj_critnib_mt/TEST0
- src/test/obj_critnib_mt/TEST0.PS1
- src/test/obj_critnib_mt/TEST1
- src/test/obj_critnib_mt/TEST2
Repeating them for pmem/non-pmem is a waste of time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3652)
> test: make critnib tests fs type agnostic

- src/test/memcheck-ndctl.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3655)
> test: add suppression for ndctl 63 memory leak

- src/test/pmempool_check/TEST1
- src/test/pmempool_check/TEST1.PS1
- src/test/pmempool_check/TEST9
- src/test/pmempool_check/TEST9.PS1
- src/test/pmempool_check/out1.log.match
- src/test/pmempool_check/out9.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3654)
> test: fix pmempool check tests

- src/test/pmempool_sync/TEST18
- src/test/pmempool_sync/TEST19
- src/test/pmempool_sync/TEST20
- src/test/pmempool_sync/TEST21
Ref: pmem/issues#1045
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3658)
> test: add devdax size limit

- src/test/pmempool_transform/TEST12
- src/test/pmempool_transform/TEST14
- src/test/pmempool_transform/TEST16
- src/test/pmempool_transform/TEST18
- src/test/pmempool_transform/TEST22
Ref: pmem/issues#1046
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3659)
> test: add devdax and free space size requirements

- doc/Makefile
- doc/generated/rpmem_drain.3
- doc/generated/rpmem_flush.3
- doc/librpmem/librpmem.7.md
- doc/librpmem/rpmem_create.3.md
- doc/librpmem/rpmem_persist.3.md
- src/include/librpmem.h
- src/librpmem/librpmem.c
- src/librpmem/librpmem.link.in
- src/librpmem/rpmem.c
- src/librpmem/rpmem_fip.c
- src/librpmem/rpmem_fip.h
- src/librpmem/rpmem_util.c
- src/librpmem/rpmem_util.h
- src/rpmem_common/rpmem_common.c
- src/rpmem_common/rpmem_common.h
- src/rpmem_common/rpmem_fip_common.c
- src/rpmem_common/rpmem_fip_common.h
- src/rpmem_common/rpmem_proto.h
- src/test/rpmem_basic/TEST20
- src/test/rpmem_basic/TEST21
- src/test/rpmem_basic/TEST22
- src/test/rpmem_basic/rpmem_basic.c
- src/test/rpmem_fip/TEST5
- src/test/rpmem_fip/TEST6
- src/test/rpmem_fip/TEST7
- src/test/rpmem_fip/rpmem_fip_test.c
- src/tools/rpmemd/rpmemd_fip.c
DONE:
TBD:
- merge pmem/pmdk#3568 after this one
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3557)
> rpmem: flush and drain

- src/tools/pmempool/common.c
- src/tools/pmempool/feature.c
- src/tools/pmempool/info.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3662)
> pool: fix printing of error messages in pmempool tool

- utils/check-commit.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3664)
> common: remove cto from the list of valid area names in a commit message

- src/common/set.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3665)
> pool: fix pmempool create error msg

- src/test/pmempool_info/out24.log.match
- src/test/pmempool_info/out25.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3657)
> test: fix match files for pmempool info tests

- doc/pmempool/pmempool-create.1.md
- src/common/set.c
- src/tools/pmempool/create.c
with pmempool create
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3667)
> pool: rename long option for clearing bad blocks

- src/test/pmempool_feature/common.sh
Ref: pmem/issues#947
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3651)
> test: enable valgrind for pmempool_feature

- src/test/blk_pool/README
- src/test/blk_pool/TEST0
- src/test/blk_pool/blk_pool.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3627)
> blk: add blk_pool test, which uses fault_injection option

- src/test/unittest/unittest.ps1
Ref: pmem/issues#1013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3650)
> test: remove old log files for windows

- .cirrus.yml
- .gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3620)
> Add Cirrus CI support for FreeBSD

- src/librpmem/librpmem.c
- src/librpmem/rpmem.c
- src/librpmem/rpmem_fip.c
- src/librpmem/rpmem_fip.h
Ref: pmem/issues#1043
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3675)
> rpmem: change order of rpmem init

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3676)
> common: add Cirrus CI badge

- .gitignore
Ignore '.*' files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3678)
> common: update .gitignore from gh-pages branch

- utils/check-doc.sh
Ref: #3641
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3680)
> common: fix TRAVIS_COMMIT_RANGE also in check-doc script

- doc/librpmem/librpmem.7.md
- src/examples/librpmem/basic.c
- src/examples/librpmem/hello.c
- src/examples/librpmem/manpage.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3686)
> rpmem: fix typos

- index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3677)
> doc: add libvmemcache to main index.md

- doc/pmreorder/pmreorder.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3694)
> doc: pmreorder fix emit log macro to pmc

- manpages/linux/v1.5/pmreorder/pmreorder.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3696)
> doc: update web pages stable 1.5

- src/libpmemobj/obj.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3691)
> obj: rm recursion from pmemobj_next

- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3700)
> test: remove unused code

- utils/docker/run-build-package.sh
It happens when this build is run under docker locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3698)
> common: do not fail if tag already exists

- utils/check_license/check-license.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3702)
> common: fix printed name of file with incorrect license

- doc/pmreorder/pmreorder.1.md
- src/test/tools/sparsefile/sparsefile.c
- src/test/unittest/unittest.sh
- utils/check-commit.sh
- utils/check-doc.sh
- utils/check_license/check-license.c
- utils/docker/pull-or-rebuild-image.sh
- utils/docker/run-build-package.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3704)
> Merge changes from stable-1.5 to stable-1.6

- doc/pmreorder/pmreorder.1.md
- src/Makefile
- src/Makefile.inc
- src/common.inc
- src/libpmemobj/obj.c
- src/librpmem/librpmem.c
- src/librpmem/rpmem.c
- src/librpmem/rpmem_fip.c
- src/librpmem/rpmem_fip.h
- src/test/tools/sparsefile/sparsefile.c
- src/test/unittest/unittest.sh
- utils/check-commit.sh
- utils/check-doc.sh
- utils/check_license/check-license.c
- utils/docker/pull-or-rebuild-image.sh
- utils/docker/run-build-package.sh
- utils/libpmemblk.pc.in
- utils/libpmemlog.pc.in
- utils/libpmemobj.pc.in
- utils/libpmempool.pc.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3705)
> Merge stable-1.5 and stable-1.6 into master

- manpages/linux/v1.6/pmreorder/pmreorder.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3707)
> doc: update web pages stable 1.6

- src/test/testconfig.py.example
- src/test/unittest/basetest.py
- src/test/unittest/context.py
- src/test/unittest/helpers.py
- src/test/unittest/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3701)
> test: (py) print logs when test fails

- src/examples/librpmem/fibonacci/fibonacci.c
- store the recovery result in the variable
- if it fails return the stored value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3711)
> examples: rpmem fibonacci fix ret value

- .cirrus.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3712)
> Backport CirrusCI integration to stable-1.6

- appveyor.yml
- src/test/obj_basic_integration/TESTS.py
- src/test/testconfig.py.example
- src/test/testframework.py
- src/test/unittest/basetest.py
- src/test/unittest/configurator.py
- src/test/unittest/context.py
- src/test/unittest/helpers.py
- src/test/unittest/valgrind.py
- utils/docker/configure-tests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3697)
> test: add python valgrind support

- src/test/unittest/basetest.py
- src/test/unittest/context.py
- src/test/unittest/valgrind.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3717)
> test: fix flake8 errors and format

- src/librpmem/rpmem_cmd.c
- src/librpmem/rpmem_ssh.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3703)
> rpmem: fix error handling in rpmem_ssh_close

- src/test/testconfig.py.example
- src/test/testframework.py
- src/test/unittest/basetest.py
- src/test/unittest/context.py
- src/test/unittest/helpers.py
- src/test/unittest/poolset.py
- src/test/unittest/tools.py
- src/test/unittest/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3718)
> test: (py) add create_poolset functionality

- src/test/unittest/basetest.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3723)
> test: (py) remove old log files

- src/test/rpmem_basic/rpmem_basic.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3721)
> test: rpmem_basic: fix number of arguments and usage messages

- src/test/tools/pmemobjcli/for-afl/allocate.posc
- src/test/tools/pmemobjcli/for-afl/iterators.posc
- src/test/tools/pmemobjcli/for-afl/list.posc
- src/test/tools/pmemobjcli/for-afl/strdup.posc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3479)
> test: smaller afl scripts

- src/libpmemobj/container.h
- src/libpmemobj/container_ravl.c
- src/libpmemobj/container_seglists.c
- src/libpmemobj/lane.c
- src/libpmemobj/lane.h
- src/test/obj_bucket/obj_bucket.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3725)
> obj: remove some unused functions

- src/libpmemobj/alloc_class.c
- src/libpmemobj/stats.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3727)
> obj: bugfix in error handling

- src/common/ctl.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3731)
> common: bugfix in error handling

- src/test/ex_librpmem_fibonacci/TEST1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3726)
> test: split pool corruption into two steps

- CONTRIBUTING.md
Reporting issues process in CONTRIBUTING is outdated. I've added information about using recently added templates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3719)
> common: update filing issues process in contributing

- src/common/file.c
- src/libpmem/pmem.c
This is a backport of #3728 to 1.4 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3730)
> [1.4] common: (win) fix possible pool file coruption

- src/jemalloc/src/util.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3732)
> jemalloc: fix build with gcc-9.1

- src/test/obj_bucket/obj_bucket.c
- src/test/obj_heap/TEST0.PS1
- src/test/obj_heap/TEST1
- src/test/obj_heap/obj_heap.c
- src/test/obj_pool/TEST0
- src/test/obj_pool/obj_pool.c
Change tests:
obj_bucket, obj_pool, obj_heap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3708)
> obj: add obj tests, which use fault_injection option

- src/test/Makefile.inc
- src/test/unittest/basetest.py
- src/test/unittest/context.py
- src/test/unittest/tools.py
- src/test/unittest/utils.py
- src/test/unittest/valgrind.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3733)
> test: Python framework fixes and improvements

- src/test/util_badblock/TEST11
- src/test/util_badblock/util_badblock.c
- src/test/util_ctl/util_ctl.c
- src/test/util_poolset/TEST4
- src/test/util_poolset/util_poolset.c
- src/test/util_poolset_parse/TEST0
- src/test/util_poolset_parse/TEST0w.PS1
- src/test/util_poolset_parse/TEST1
- src/test/util_poolset_parse/TEST2
- src/test/util_poolset_parse/TEST3
- src/test/util_poolset_parse/TEST5
- src/test/util_poolset_parse/util_poolset_parse.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3740)
> common: add util tests, which use fault_injection option

- src/test/unittest/context.py
... to make adding args to command more intuitive
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3746)
> test: (py) modify ctx exec api

- README.md
The file has apparently been edited by a WYSINWYG editor. It's unlikely there's some hidden purpose as not all entries have these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3754)
> common: remove invisible characters from README.md

- src/test/match
It can take quite a bit of staring to spot the fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3757)
> test: colorize matching patterns

- src/test/obj_action/memcheck1.log.match
- src/test/obj_constructor/memcheck1.log.match
- src/test/obj_ctl_debug/memcheck1.log.match
- src/test/obj_locks/drd1.log.match
- src/test/obj_locks/helgrind2.log.match
- src/test/obj_memcheck/memcheck0.log.match
- src/test/unittest/unittest.sh
- src/test/vmem_valgrind/memcheck2.log.match
- src/test/vmem_valgrind/memcheck3.log.match
- src/test/vmem_valgrind/memcheck4.log.match
- src/test/vmem_valgrind_region/memcheck0.log.match
- src/test/vmem_valgrind_region/memcheck1.log.match
- src/test/vmem_valgrind_region/memcheck2.log.match
- src/test/vmem_valgrind_region/memcheck3.log.match
- src/test/vmem_valgrind_region/memcheck4.log.match
- src/test/vmmalloc_valgrind/memcheck1.log.match
- src/test/vmmalloc_valgrind/memcheck2.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3762)
> test: align tests to valgrind 3.15

- utils/docker/images/Dockerfile.ubuntu-18.04
- utils/docker/run-coverity.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3752)
> common: fix Coverity builds

- appveyor.yml
- src/test/Makefile
- src/test/RUNTESTS.py
- src/test/pmem_map_file_trunc/TESTS.py
- src/test/testconfig.py.example
- src/test/testframework.py
- src/test/unittest/basetest.py
- src/test/unittest/context.py
- src/test/unittest/futils.py
- src/test/unittest/helpers.py
- src/test/unittest/poolset.py
- src/test/unittest/tools.py
- src/test/unittest/utils.py
- src/test/unittest/valgrind.py
- utils/docker/configure-tests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3743)
> test: Python framework fixes and clean ups, part 2

- src/test/libpmempool_feature/TEST0.PS1
- src/test/libpmempool_feature/TEST1.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3758)
> test: libpmempool_feature require debug

- doc/librpmem/rpmem_persist.3.md
- src/benchmarks/pmembench_rpmem.cfg
- src/benchmarks/rpmem.cpp
- src/include/librpmem.h
- src/librpmem/rpmem.c
- src/librpmem/rpmem_fip.c
- src/librpmem/rpmem_fip.h
- src/librpmem/rpmem_util.h
- src/rpmem_common/rpmem_proto.h
- src/test/rpmem_basic/TEST20
- src/test/rpmem_basic/TEST21
- src/test/rpmem_basic/TEST22
- src/test/rpmem_basic/rpmem_basic.c
- src/test/rpmem_fip/rpmem_fip_test.c
- src/tools/rpmemd/rpmemd_fip.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3760)
> rpmem: flush strict and relaxed

- doc/libpmem/pmem_flush.3.md
- src/tools/daxio/README
2 small fixes in documentations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3767)
> common: fix misspells in docs

- src/test/pmempool_rm/TEST12
- src/test/pmempool_rm/TEST12.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3747)
> test: add test for pmempool_rm

- utils/docker/images/Dockerfile.fedora-28
- utils/docker/images/Dockerfile.ubuntu-18.04
- utils/docker/images/Dockerfile.ubuntu_ndctl_v60-18.04
... by using --no-install-recommends option and adding only necessary
packages back.
Also: remove cmake from installed packages - it was needed by libcxx.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3753)
> common: trim down the number of packages in Ubuntu Docker images

- utils/check-commit.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3756)
> common: extend check-commit script to accept commit ids

- doc/libpmemobj/pmemobj_tx_begin.3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3768)
> doc: update manpage

- src/libpmemobj/tx.c
- src/test/obj_lane/TEST0
- src/test/obj_lane/obj_lane.c
- src/test/obj_tx_flow/Makefile
- src/test/obj_tx_flow/TEST0
- src/test/obj_tx_flow/TEST0.PS1
- src/test/obj_tx_flow/obj_tx_flow.c
- src/test/obj_tx_flow/obj_tx_flow.vcxproj
- src/test/obj_tx_lock/Makefile
- src/test/obj_tx_lock/TEST0
- src/test/obj_tx_lock/obj_tx_lock.c
- src/test/obj_tx_lock/obj_tx_lock.vcxproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3749)
> obj: testing of exception handling

- src/test/libpmempool_check_version/libpmempool_check_version.vcxproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3776)
> test: fix libpmempool-check-version sdk

- src/test/unittest/basetest.py
- src/test/unittest/futils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3775)
> test: (py) disable valgrind tests on win

- src/tools/pmempool/common.c
- src/tools/pmempool/common.h
- src/tools/pmempool/output.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3773)
> pool: remove malloc

- utils/docker/build-local.sh
- utils/docker/build-travis.sh
- utils/docker/images/build-image.sh
- utils/docker/images/push-image.sh
- utils/docker/pull-or-rebuild-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3771)
> common: use separate Docker images for stable-1.6

- utils/docker/build-local.sh
- utils/docker/build-travis.sh
- utils/docker/images/build-image.sh
- utils/docker/images/push-image.sh
- utils/docker/pull-or-rebuild-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3774)
> common: use separate Docker images for stable-1.7

- utils/docker/images/Dockerfile.ubuntu-18.04
Ref: #3753
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3778)
> common: fix CodeCov builds

- utils/docker/images/install-valgrind.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3761)
> common: update valgrind to v3.15 in docker images

- utils/docker/images/Dockerfile.ubuntu-18.04
- utils/docker/images/Dockerfile.ubuntu_ndctl_v60-18.04
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3781)
> common: Docker images fixes/improvements

- appveyor.yml
- utils/check_sdk_version.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3777)
> common: add checker for SDK version

- src/include/libpmemobj/tx_base.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3784)
> obj: work around one more Coverity bug

- src/test/unittest/context.py
- src/test/unittest/valgrind.py
Ref: pmem/issues#1070
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3782)
> test: (py) fix behavior for unavailable valgrind tool

- utils/docker/images/install-valgrind.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3791)
> common: bump valgrind version on Docker

- src/libpmemobj/critnib.c
This warning doesn't trigger otherwise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3789)
> obj: fix a build failure with -fsanitize=undefined

- src/test/testconfig.ps1.example
- src/test/testconfig.py.example
- src/test/testconfig.sh.example
- src/test/unittest/basetest.py
- src/test/unittest/configurator.py
... and refine non-existent config attribute error message.
Ref: pmem/issues#1069
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3783)
> test: (py) skip test if _fs_dir is not provided 

- src/test/blk_non_zero/TEST10
- src/test/blk_non_zero/blk_non_zero.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3772)
> blk: add blk test, that use fault_injection option

- doc/libpmemobj/pmemobj_tx_add_range.3.md
- src/include/libpmemobj/base.h
- src/include/libpmemobj/tx_base.h
- src/libpmemobj/tx.c
- src/test/obj_tx_add_range/TEST0
- src/test/obj_tx_add_range/TEST0.PS1
- src/test/obj_tx_add_range/TEST2
- src/test/obj_tx_add_range/TEST2.PS1
- src/test/obj_tx_add_range/TESTS.py
- src/test/obj_tx_add_range/obj_tx_add_range.c
- src/test/obj_tx_add_range/pmemcheck1.log.match
- src/test/obj_tx_add_range_direct/TEST0
- src/test/obj_tx_add_range_direct/TESTS.py
- src/test/obj_tx_add_range_direct/obj_tx_add_range_direct.c
- src/test/obj_tx_add_range_direct/out0.log.match
- src/test/obj_tx_add_range_direct/pmemcheck1.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3759)
> obj: add POBJ_XADD_NO_SNAPSHOT_FLAG

- src/common/vecq.h
So far this causes a crash only on arm64 (for nearly any uses of pmemobj) with gcc in `-O2` and `-O3`, but working ok on our platforms is only due to luck: any future compiler may use this optimization, it might be triggered by something like LTO, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3799)
> vecq: fix a pointer-to-struct aliasing violation

- src/libpmemobj/lane.c
- src/libpmemobj/list.c
- src/libpmemobj/memops.c
- src/libpmemobj/memops.h
- src/libpmemobj/obj.h
- src/libpmemobj/palloc.c
- src/libpmemobj/tx.c
- src/libpmemobj/ulog.c
- src/libpmemobj/ulog.h
- src/test/magic/out0.log.match
- src/test/obj_heap_interrupt/obj_heap_interrupt.c
- src/test/obj_layout/obj_layout.c
- src/test/obj_list/obj_list_mocks_palloc.c
- src/test/obj_memops/obj_memops.c
- src/test/obj_persist_count/out0.log.match
- src/test/obj_persist_count/out1.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3750)
> obj: ulog checksum invalidation

- Makefile
- utils/check-area.sh
- utils/check-commit.sh
- utils/check-commits.sh
Fixes "make cstyle" when executed from top-level directory outside of Travis environment.
(Regression introduced by fe8b3db51b3ab314aa9f201c7778acab4711ade3)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3805)
> common: check-commit improvements

- utils/docker/build-travis.sh
- utils/docker/run-doc-update.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3809)
> common: fix path to valid-branches script

- src/libpmemobj/ulog.c
- src/test/obj_persist_count/out0.log.match
- src/test/obj_persist_count/out1.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3820)
> obj: quick fix for ulog-invalidation issue

- src/test/tools/pmemobjcli/pmemobjcli.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3827)
> test: initialize pointers in pmemobjcli.c

- src/examples/libpmemobj/array/array.c
- src/examples/libpmemobj/pmemobjfs/pmemobjfs.c
Let's replace it with safer strcpy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3830)
> examples: fix two strncpy issues

- src/test/obj_tx_add_range/obj_tx_add_range.c
- src/test/obj_tx_add_range/pmemcheck1.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3823)
> test: add abort after commit case to tx_add_range

- utils/docker/build-local.sh
- utils/docker/build-travis.sh
- utils/docker/images/build-image.sh
- utils/docker/images/install-valgrind.sh
- utils/docker/images/push-image.sh
- utils/docker/pull-or-rebuild-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3837)
> [1.3] common: use separate Docker images for stable-1.3 branch

- src/test/obj_zones/TEST1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3841)
> test: require enoug space for obj_zones/TEST1

- src/test/obj_basic_integration/Makefile
- src/test/obj_basic_integration/obj_basic_integration.c
- src/test/obj_basic_integration/obj_basic_integration.vcxproj
- src/test/obj_rpmem_basic_integration/TEST0
- src/test/obj_rpmem_basic_integration/node_1_out0.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3822)
> obj: add obj_rpmem test, that use fault_injection option

- src/libpmemobj/heap.c
- src/libpmemobj/recycler.c
This is the race uncovered after fixing #3821 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3834)
> obj: fix a benign race in arena mangement

- src/test/obj_heap/obj_heap.c
Ref: pmem/issues#1081
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3825)
> test: fix obj_heap

- src/examples/libpmemobj/hashmap/hashmap_rp.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3848)
> examples: fix persist range in hashmap_rp

- src/test/pmempool_create/TEST14.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3847)
> test: overwrite old log in pmempool_create/TEST14.PS1 

- .travis.yml
- src/test/obj_realloc/TEST1
- utils/docker/build.sh
- utils/docker/images/build-image.sh
- utils/docker/images/install-valgrind.sh
- utils/docker/images/push-image.sh
- utils/docker/pull-or-rebuild-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3850)
> common: use separate Docker images for stable-1.2 branch 

- src/common/os_auto_flush_linux.c
Ref: pmem/issues#1093
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3853)
> [1.4] common: fix persistent domain termination

- src/common/os_auto_flush_linux.c
Ref: pmem/issues#1093
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3852)
> common: fix persistent domain termination

- src/test/memcheck-dlopen.supp
Ref: pmem/issues#1098
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3854)
> test: suppress ld leak

- src/test/pmempool_check/out32.log.match
- src/test/pmempool_info/out24.log.match
- src/test/pmempool_sync/out28.log.match
- src/test/pmempool_sync/out31.log.match
- src/test/util_badblock/err8.log.match
- src/test/util_badblock/out1.log.match
- src/test/util_badblock/out2.log.match
- src/test/util_badblock/out3.log.match
- src/test/util_badblock/out4.log.match
- src/test/util_badblock/out8.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3861)
> test: fix match files in tests which use dax devices

- src/test/RUNTESTLIB.PS1
- src/test/pmempool_check/TEST16.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3867)
> Bug fixes from stable-1.6

- src/libpmemobj/tx.c
Ref: pmem/issues#1028
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3871)
> [1.4] obj: fix possible memory leak in tx_add_lock

- src/libpmemobj/tx.c
Ref: pmem/issues#1028
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3873)
> [1.5] obj: fix possible memory leak in tx_add_lock

- ChangeLog
- src/test/pmempool_check/out32.log.match
- src/test/pmempool_info/out24.log.match
- src/test/pmempool_sync/out28.log.match
- src/test/pmempool_sync/out31.log.match
- src/test/util_badblock/err8.log.match
- src/test/util_badblock/out1.log.match
- src/test/util_badblock/out2.log.match
- src/test/util_badblock/out3.log.match
- src/test/util_badblock/out4.log.match
- src/test/util_badblock/out8.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3878)
> Merge stable-1.5 into stable-1.6

- .mailmap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3874)
> common: update .mailmap

- utils/docker/pull-or-rebuild-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3865)
> Fix invalid TRAVIS_COMMIT_RANGE in case of non-upstream repository

- src/test/blk_pool/TEST10.PS1
- src/test/blk_pool/TEST11.PS1
- src/test/blk_pool/TEST25.PS1
- src/test/blk_pool/TEST26.PS1
- src/test/cto_pool/TEST10.PS1
- src/test/cto_pool/TEST11.PS1
- src/test/cto_pool/TEST25.PS1
- src/test/cto_pool/TEST26.PS1
- src/test/log_pool/TEST10.PS1
- src/test/log_pool/TEST24.PS1
- src/test/log_pool/TEST25.PS1
- src/test/log_pool/TEST9.PS1
- src/test/obj_pool/TEST10.PS1
- src/test/obj_pool/TEST11.PS1
- src/test/obj_pool/TEST25.PS1
- src/test/obj_pool/TEST26.PS1
- src/test/pmempool_check/TEST16.PS1
- src/test/util_file_create/TEST1.PS1
- src/test/util_file_open/TEST1w.PS1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3883)
> [1.4] test: porting bug fixes to stable-1.4

- src/common/util.h
- src/test/pmem_deep_persist/pmem_deep_persist.c
- src/test/unittest/unittest.h
- src/test/unittest/ut.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3875)
> [1.4] test: fix int overflow in pmem_deep_persist test

- src/libpmempool/transform.c
Ref: pmem/issues#1109
Ref: pmem/issues#1108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3885)
> [1.4] pool: do not copy same regions in update_uuids

- src/libpmempool/transform.c
Ref: pmem/issues#1109
Ref: pmem/issues#1108
(cherry picked from commit 9f503369d3f2594bab2a493bbedd6be8464e62dc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3886)
> pool: do not copy same regions in update_uuids

- utils/docker/run-coverage.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3895)
> common: add pycheck to coverage

- ChangeLog
- utils/docker/run-coverage.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3896)
> Merge stable-1.6 into master

- doc/pmempool/pmempool.1.md
Ref: https://github.com/pmem/issues/issues/1119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3897)
> man pmempool(1) hyphen

- src/include/libpmemobj/types.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3893)
> obj: fix incorrect link in error message

- src/test/common_badblock.sh
- src/test/unittest/unittest.sh
- src/test/util_badblock/TEST2
- src/test/util_badblock/TEST3
- src/test/util_badblock/TEST4
- src/test/util_badblock/TEST5
- src/test/util_badblock/TEST6
- src/test/util_badblock/TEST7
- src/test/util_badblock/TEST8
- src/test/util_badblock/TEST9
Preliminary refactoring for enabling execution on
proper hardware.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3858)
> test: simplify badblock tests code

- src/test/unittest/utils.py
- src/test/win_common/TESTS.py
... and provide usage example with win_common
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3890)
> test (py): add OS filtering

- index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3902)
> Add pmemkv to PMDK Github pages

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3904)
> doc: Marcin is a new Krzysztof

- src/test/tools/pmemobjcli/pmemobjcli.c
Ref: pmem/issues#1103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3907)
> [1.7] test: add missing pmemobj_persist to pmemobjcli

- src/test/obj_pmalloc_mt/obj_pmalloc_mt.c
Ref: pmem/issues#1115
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3910)
> [1.7] test: destroy mutexes and conditionals prior to reinit

- src/examples/libpmemobj/array/array.c
Ref: pmem/issues#1117
Ref: pmem/pmdk#3860
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3908)
> [1.7] examples: obj array fix int realloc

- src/common/ctl.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3918)
> common: add va_args support to ctl_node

- utils/check_sdk_version.py
Ref: pmem/issues#1120
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3919)
> common: check all .vcxproj file instead of only changed ones

- src/libpmemobj/palloc.c
Before inserting a memory block to the bucket it is required
to verify the bucket has an active memory block.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3923)
> obj: make sure the bucket is active

- src/test/obj_ulog_size/TEST1
- src/test/obj_ulog_size/obj_ulog_size.c
- src/test/obj_ulog_size/obj_ulog_size.vcxproj
Ref: pmem/issues#1121
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3925)
> test: obj_ulog_size/ fix stack problem

- src/test/obj_pmalloc_mt/obj_pmalloc_mt.c
Ref: pmem/pmdk#3911
Ref: pmem/issues#1118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3929)
> [1.7] test: obj_pmalloc_mt persistency fix

- src/test/ex_librpmem_fibonacci/TEST0
- src/test/ex_librpmem_fibonacci/TEST1
- src/test/ex_librpmem_fibonacci/TEST2
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3926)
> test: output/error stream redirection compatibility fix 

- src/test/util_badblock/out6.log.match
- src/test/util_badblock/out7.log.match
- src/test/util_badblock/util_badblock.c
... so that the tests were correct also in case of real hardware.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3930)
> test: print length of bad blocks in blocks

- src/test/pmempool_transform/TEST11
- src/test/pmempool_transform/TEST12
- src/test/pmempool_transform/TEST14
- src/test/pmempool_transform/TEST15
- src/test/pmempool_transform/TEST16
- src/test/pmempool_transform/TEST18
- src/test/pmempool_transform/TEST22
Ref: pmem/issues#1047
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3932)
> test: force-disable pmemcheck in a few pmempool_transform tests

- src/libpmemobj/memops.c
- src/libpmemobj/ulog.c
- src/libpmemobj/ulog.h
- src/test/obj_memops/obj_memops.c
- src/test/obj_persist_count/out0.log.match
- src/test/obj_persist_count/out1.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3824)
>  obj: prevent ulog_foreach from ever reading uninitialized data 

- src/libpmemobj/tx.c
- src/test/obj_tx_add_range/obj_tx_add_range.c
- src/test/obj_tx_add_range/pmemcheck1.log.match
now when in a tx two ranges are merged their flags are merged as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3924)
> Tx add range bug

- src/test/obj_basic_integration/TESTS.py
- src/test/unittest/basetest.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3941)
> test (py): handle tests inheritance

- src/test/util_badblock/util_badblock.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3943)
> test: fix printing length of bad blocks in case of DAX devices

- src/Makefile
A benign regression.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3936)
> fix make warnings about duplicated targets

- src/test/daxio/TEST0
- src/test/daxio/TEST1
- src/test/daxio/TEST2
- src/test/daxio/TEST3
Ref: pmem/issues#991
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3948)
> test: daxio fix tests print fail reason

- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3952)
> test: fix typo in require_badblock_tests_enabled

- src/include/libpmemobj/tx_base.h
- src/libpmemobj/libpmemobj.def
- src/libpmemobj/libpmemobj.link.in
- src/libpmemobj/tx.c
- src/test/scope/out4.log.match
- src/test/scope/out4w.log.match
Ref: pmem/issues#1123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3953)
> obj: align tx log funcs names

- src/test/unittest/basetest.py
... in case of running only selected tests from group
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3950)
> test (py): fix test inheritance behaviour

- src/test/testconfig.py.example
Again, it's done differently than in the old test framework.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3967)
> give an example how to specify multiple build types

- src/libpmemobj/memops.c
To make sure I can change status of KW issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3965)
> obj: add assert - one ulog must exists

- src/test/obj_ulog_size/obj_ulog_size.c
- restore the default value of tx.debug.verify_user_buffers CTL
- fix the counter type
- fix buffer handling
Ref: pmem/pmdk#3866
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3955)
> [1.7] test: obj_ulog_size fixes

- src/test/obj_tx_add_range/TESTS.py
- src/test/unittest/basetest.py
- src/test/unittest/configurator.py
- src/test/unittest/futils.py
- src/test/unittest/valgrind.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3954)
> test (py): fix valgrind force-enable behavior

- src/test/test_debug.props
- src/test/test_release.props
- src/windows/libs_debug.props
- src/windows/libs_release.props
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3962)
> common: fix compilation issue on Windows

- src/libpmemobj/tx.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3961)
> obj: check if errno is set

- appveyor.yml
- utils/CREATE-ZIP.PS1
Ref: pmem/issues#923
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3973)
> common: remove support for examples zip packages

- README.md
The latter is considered finished and in maintenance mode, it doesn't receive new features.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3787)
> Recommend memkind instead of vmem.

- src/libpmemobj/obj.c
- src/libpmemobj/tx.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3974)
> Klocwork fixes - removing unreachable code

- src/test/common_badblock.sh
- src/test/pmempool_check/TEST31
- src/test/pmempool_check/TEST32
- src/test/pmempool_create/TEST10
- src/test/pmempool_create/TEST11
- src/test/pmempool_create/TEST12
- src/test/pmempool_info/TEST24
- src/test/pmempool_info/TEST25
- src/test/pmempool_sync/TEST27
- src/test/pmempool_sync/TEST28
- src/test/pmempool_sync/TEST30
- src/test/pmempool_sync/TEST31
- src/test/pmempool_sync/TEST38
- src/test/pmempool_sync/TEST39
- src/test/pmempool_sync/TEST40
- src/test/pmempool_sync/TEST41
- src/test/pmempool_sync_remote/TEST22
- src/test/pmempool_sync_remote/TEST23
- src/test/pmempool_sync_remote/TEST24
- src/test/pmempool_sync_remote/TEST25
- src/test/pmempool_sync_remote/TEST32
- src/test/pmempool_sync_remote/TEST33
- src/test/pmempool_sync_remote/TEST34
- src/test/pmempool_sync_remote/TEST35
- src/test/util_badblock/TEST3
- src/test/util_badblock/TEST4
- src/test/util_badblock/TEST6
- src/test/util_badblock/TEST7
- src/test/util_badblock/TEST8
- src/test/util_badblock/TEST9
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3964)
> test: add $NAMESPACE parameter to expect_bad_blocks and print_bad_blocks

- utils/check_license/file-exceptions.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3972)
> don't complain about license in testconfig

- src/libpmemobj/ulog.c
An assert for readability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3975)
> [1.7] obj: if ANY_USER_BUFFER assert ulog_second != NULL

- src/test/pmempool_create/TEST10
- src/test/pmempool_create/TEST11
- src/test/pmempool_create/out10.log.match
- src/test/pmempool_create/out11.log.match
- src/test/pmempool_feature/TEST12
- src/test/pmempool_feature/TEST16
- src/test/unittest/unittest.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3970)
> test: update pmempool_create badblock tests

- src/test/obj_ulog_size/obj_ulog_size.c
- src/test/obj_ulog_size/out0.log.match
- src/test/obj_ulog_size/out1.log.match
- src/test/obj_ulog_size/out2.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3963)
> [1.7] test: obj_ulog_size misc tests and fixes

- utils/docker/run-doc-update.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3981)
> common: add libs_map auto update

- doc/libpmemblk/libpmemblk.7.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3990)
> doc: fix libpmemblk typo

- utils/docker/valid-branches.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3996)
> common: add stable-1.7 to the list of valid branches

- src/libpmemobj/tx.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3994)
> obj: fix pmemcheck marker in pmemobj_tx_wcsdup

- doc/libpmemobj/pmemobj_tx_add_range.3.md
- src/include/libpmemobj/tx_base.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3993)
> Update the descriptions of the functions

- index.md
Set a link to libpmemobj-cpp gh-pages content, rather than a content of pmdk's gh-pages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3998)
> Adjust gh-pages index.html with proper links

- src/test/obj_tx_add_range/TESTS.py
- src/test/unittest/basetest.py
- src/test/unittest/configurator.py
- src/test/unittest/valgrind.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3987)
>  test (py): skip tests that enable tool different than forced

- src/test/unittest/configurator.py
- src/test/unittest/context.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3988)
> test (py): enable debugging C code

- ChangeLog
- doc/libpmemblk/libpmemblk.7.md
- doc/libpmemlog/pmemlog_append.3.md
- doc/poolset/poolset.5.md
- src/examples/libpmemobj/setjmp.c
- src/include/README
- src/include/libpmem.h
- src/include/libpmemblk.h
- src/include/libpmemlog.h
- src/include/libpmemobj.h
- src/include/libpmempool.h
- src/include/librpmem.h
- src/include/libvmem.h
- src/include/libvmmalloc.h
- src/tools/pmempool/README
Fixes #1130.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4014)
> fix manpage sections references: lib* are in section 7 not 3

- src/test/unittest/unittest.sh
The cause may be unobvious otherwise.
Fixes pmem/issues#1131.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4015)
> give a helpful message if envconfig.sh is missing

- src/include/libpmem2.h
- src/libpmem2/Makefile
- src/libpmem2/libpmem2.c
- src/libpmem2/libpmem2.def
- src/libpmem2/libpmem2.link.in
- src/libpmem2/libpmem2.vcxproj
- src/libpmem2/libpmem2.vcxproj.filters
- src/libpmem2/pmem2.h
Just mindless copy from libpmem, plus required symbols.
Requires #4005.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4008)
> pmem2: error messaging

- src/common/file.c
- src/common/file.h
- src/common/mmap.c
- src/common/mmap.h
- src/libpmem/pmem_posix.c
- src/libpmem/pmem_windows.c
- src/libpmempool/pool.c
- src/libvmmalloc/libvmmalloc.c
- src/test/tools/bttcreate/bttcreate.c
- src/test/tools/cmpmap/cmpmap.c
- add fd variants of already existing functions:
- util_ddax_region_fd_find
- util_fd_get_size
- add offset argument to util_map
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4029)
> common: prepare for libpmem2 needs

- src/include/libpmem2.h
- src/libpmem2/libpmem2.def
- src/libpmem2/pmem2.c
- src/test/Makefile
- src/test/Makefile.inc
- src/test/pmem2_include/.gitignore
- src/test/pmem2_include/Makefile
- src/test/pmem2_include/pmem2_include.c
- src/test/pmem2_include/pmem2_include.vcxproj
- src/test/pmem2_include/pmem2_include.vcxproj.filters
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4033)
> pmem2: prepare libpmem2 header file

- utils/sort_solution
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4034)
> util: add comment in sort_solution

- src/common/fault_injection.h
- src/libpmem2/Makefile
- src/libpmem2/libpmem2.vcxproj
- src/libpmem2/libpmem2.vcxproj.filters
- src/libpmem2/pmem2_utils.c
- src/libpmem2/pmem2_utils.h
- src/test/unittest/unittest.h
- utils/check-area.sh
- utils/check-commit.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4036)
> pmem2: pmem2_utils / commit check / unittest.h

- doc/libpmem/libpmem.7.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4041)
> doc: fix pmem_errormsg description

- doc/pmreorder/pmreorder.1.md
This small change unbreaks the whole man page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4054)
> doc: fix formatting of pmreorder man page

- src/test/obj_root/TEST1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4058)
> test: force-disable pmemcheck in obj_root test

- index.md
- libvmem/index.md
- libvmmalloc/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4064)
> doc: updates vmem links on gh-pages

- src/libpmem2/config.h
- src/libpmem2/map.h
Please review: @lplewa
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4071)
> pmem2: pmem2_map structure

- src/common/out.c
- src/common/util.h
- src/common/util_posix.c
- src/common/util_windows.c
- src/include/libpmem2.h
- src/libpmem2/config_posix.c
- src/libpmem2/config_windows.c
- src/libpmem2/pmem2.c
- src/libpmem2/pmem2_utils.c
- src/test/pmem2_config/pmem2_config.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4074)
> pmem2: change error codes

- src/common/file.c
- src/libpmem/pmem.c
- src/test/pmem_deep_persist/pmem_deep_persist.c
- src/test/tools/cmpmap/cmpmap.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4075)
> common: use util_fd_get_size instead of util_file_get_size when possible

- src/common/util.h
- src/common/util_windows.c
- src/libpmem2/config_windows.c
- src/libpmem2/pmem2_utils.c
- src/libpmem2/pmem2_utils.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4077)
> pmem2: convert windows error code to errno

- src/libpmem2/config_posix.c
- src/libpmem2/config_windows.c
- src/libpmem2/pmem2_utils.c
- src/libpmem2/pmem2_utils.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4078)
> pmem2: add PMEM2_E_ERRNO

- src/include/libpmem2.h
- src/libpmem2/config.c
- src/libpmem2/config.h
- src/libpmem2/map.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4080)
> pmem2: add granularity fields to map and cfg

- src/common/out.c
- src/common/util.h
- src/common/util_posix.c
- src/common/util_windows.c
Ref: pmem/pmdk#4074
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4089)
> common: store and restore GetLastError (fix)

- src/test/pmem2_config/TESTS.py
- src/test/pmem2_config/pmem2_config.c
- src/test/unittest/unittest.h
- src/test/unittest/ut.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4094)
> pmem2: add function to suppress crt asserts

- src/test/unittest/ut.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4108)
> test: force load KernelBase.dll.mui

- src/libpmem2/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4112)
> pmem2: add missing dependencies

- src/include/libpmem2.h
- src/libpmem2/pmem2.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4245)
> pmem2: fix declaration of get_* functions

- .travis.yml
- utils/docker/images/Dockerfile.fedora-31
- utils/docker/images/Dockerfile.ubuntu-19.10
Ubuntu 18.04 -> 19.10
Fedora 28 -> 31
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4110)
> Update Docker images to newest versions

- doc/libpmem2/libpmem2.7.md
- doc/libpmem2/pmem2_map_get_store_granularity.3.md
- src/libpmem2/map.c
- src/libpmem2/pmem2.c
- src/test/pmem2_map/TESTS.py
- src/test/pmem2_map/pmem2_map.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4083)
> pmem2: get_store_granularity feature, test and doc

- src/test/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4250)
> common: add ex_libpmem2 to Makefile

- doc/Makefile
- doc/libpmem2/pmem2_config_set_fd.3.md
- src/libpmem2/config_posix.c
- src/libpmem2/config_windows.c
- src/test/pmem2_config/TESTS.py
- src/test/pmem2_config/pmem2_config.c
missing documentation of windows error codes (i have to add test for it to find them:) )
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4088)
> pmem2: pmem2_config_set_fd extra tests and manpage

- utils/docker/images/Dockerfile.fedora-31
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4252)
> common: add flake8 to Fedora 31 dockerfile

- doc/pmreorder/pmreorder.1.md
- src/Makefile
- src/tools/pmreorder/pmreorder.py
Ref: #4234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4109)
> pmreorder: add --version support

- doc/libpmem2/pmem2_map.3.md
Ref: pmem/pmdk#4251
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4256)
> doc: fix Windows API reference

- doc/libpmem2/pmem2_map.3.md
- src/common/file_windows.c
Behold the power of grep!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4259)
> a WinA function that has been missed

- src/test/Makefile.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4264)
> pmem2: libpmem2 internal debug/nondebug

- src/common.inc
- src/test/env.py
- src/test/ex_libpmem2/TESTS.py
- src/test/obj_basic_integration/TESTS.py
- src/test/obj_ulog_size/TESTS.py
- src/test/pmem2_config/TESTS.py
- src/test/pmem2_config_get_file_size/TESTS.py
- src/test/pmem2_integration/TESTS.py
- src/test/pmem2_map/TESTS.py
- src/test/pmem_map_file_trunc/TESTS.py
- src/test/testframework.py
- src/test/unittest/context.py
- src/test/unittest/futils.py
- src/test/unittest/poolset.py
- src/test/unittest/tools.py
- utils/style_check.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4248)
> common: add flake8 check to cstyle

- src/test/unittest/basetest.py
- src/test/unittest/futils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4265)
> test (py): various fixes

- src/common/file.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4268)
> common: fix util_read/util_write on Windows

- src/common/extent_linux.c
- src/common/file_posix.c
- src/common/util.c
- src/test/pmem_deep_persist/mocks_posix.c
- src/test/pmem_memcpy/pmem_memcpy.c
- src/test/pmem_memmove/pmem_memmove.c
- src/test/pmem_memset/pmem_memset.c
- src/test/pmem_movnt/pmem_movnt.c
- src/test/pmem_movnt_align/pmem_movnt_align.c
- src/test/pmreorder_flushes/pmreorder_flushes.c
- src/tools/daxio/daxio.c
- utils/check-os.sh
- utils/os-banned
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4276)
> utils: fix check-os script

- src/common/file.c
- src/libpmem2/config.c
- src/libpmem2/config.h
- src/test/pmem2_config/pmem2_config.c
- src/test/pmem2_config_get_file_size/pmem2_config_get_file_size.c
- src/test/pmem2_map/pmem2_map.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4278)
> pmem2: rename config_init to pmem2_config_init

- src/test/tools/gran_detecto/gran_detecto.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4279)
> test: fix compilation gran_detecto with clang 3.4.2

- .github/workflows/gha.yml
- .travis.yml
- utils/docker/build-travis.sh
- utils/docker/pull-or-rebuild-image.sh
- utils/docker/set-vars.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4277)
> common: add workflow file for GitHub actions

- src/benchmarks/Makefile
- src/benchmarks/benchmark_empty.cpp
- src/benchmarks/pmembench_tx_add_range.cfg
- src/benchmarks/pmemobj_tx_add_range.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/3986)
> benchmark: add benchmark template and tx_add_range benchmark

- .github/workflows/gha.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4283)
> common: run GitHub Actions also on pull requests

- src/examples/libpmem2/basic.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4284)
> examples: pmem2 basic small fix

- src/common/util.h
- src/libpmem/x86_64/memcpy/memcpy_avx.h
- src/libpmem/x86_64/memcpy/memcpy_sse2.h
- src/libpmem/x86_64/memset/memset_avx.h
- src/libpmem/x86_64/memset/memset_sse2.h
- src/libpmemobj/critnib.c
- src/libpmemobj/palloc.c
*FLAGS=-fsanitize=undefined
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4271)
> make UBSAN happy

- .github/workflows/gha.yml
Add build numbers in GitHub Actions to easily identify them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4288)
> common: reorder builds and add build numbers in GitHub Actions

- utils/docker/images/Dockerfile.fedora-31
- utils/docker/images/Dockerfile.ubuntu-19.10
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4285)
> common: docker: add missing packages for tests

- Makefile
- doc/Makefile
- src/Makefile
- src/Makefile.inc
- src/common.inc
- src/common/page_size.h
- src/common/pool_hdr.c
- src/common/pool_hdr.h
- src/common/util.h
- src/libpmem/memops_generic.c
- src/libpmem/ppc64/flags.inc
- src/libpmem/ppc64/init.c
- src/libpmem/ppc64/platform_generic.c
- src/libpmem/ppc64/platform_generic.h
- src/libpmem/ppc64/sources.inc
- src/test/pmem_deep_persist/TEST5
- src/test/pmem_is_pmem_posix/Makefile
- src/test/pmem_movnt_align/TEST0
- src/test/pmem_movnt_align/TEST1
- src/test/pmem_movnt_align/TEST2
- src/test/pmem_movnt_align/pmem_movnt_align.c
- src/tools/pmempool/output.c
- utils/build-dpkg.sh
- utils/build-rpm.sh
- utils/pmdk.spec.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4294)
> Merge devel-1.8 into master

- src/test/unittest/context.py
- src/test/unittest/valgrind.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4087)
> test (py): fix for passing whitespace args

- src/libpmem2/map_posix.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4302)
> pmem2: fix resource leak in pmem2_map

- src/common/file.h
- src/libpmemobj/memops.c
- src/libpmemobj/ulog.c
- src/test/obj_memops/obj_memops.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4297)
> Merge stable-1.6 into stable-1.7

- doc/RELEASE_STEPS.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4286)
> doc: add RELEASE_STEPS.md

- src/common/util_windows.c
- src/test/obj_badblock/obj_badblock.c
- src/test/pmem2_map/pmem2_map.c
- utils/check_whitespace
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4270)
> common: add duplicated empty line check

- src/test/Makefile
- src/test/pmem2_granularity/.gitignore
- src/test/pmem2_granularity/Makefile
- src/test/pmem2_granularity/TESTS.py
- src/test/pmem2_granularity/mocks_posix.c
- src/test/pmem2_granularity/pmem2_granularity.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4293)
> test: pmem2_granularity generic part

- src/common/file.h
- src/libpmemobj/list.c
- src/libpmemobj/memops.c
- src/libpmemobj/palloc.c
- src/libpmemobj/ulog.c
- src/test/obj_list/obj_list_mocks_palloc.c
- src/test/obj_memops/obj_memops.c
- src/test/unittest/basetest.py
- src/test/unittest/context.py
- src/test/unittest/futils.py
- src/test/unittest/valgrind.py
- src/tools/pmreorder/pmreorder.py
- utils/docker/run-build-package.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4304)
> Merge stable-1.7 into devel-1.8

- src/test/RUNTESTS.py
- src/test/env.py
- src/test/ex_libpmem2/TESTS.py
- src/test/obj_tx_add_range/TESTS.py
- src/test/obj_tx_add_range_direct/TESTS.py
- src/test/obj_ulog_size/TESTS.py
- src/test/pmem2_config/TESTS.py
- src/test/pmem2_config_get_file_size/TESTS.py
- src/test/pmem2_integration/TESTS.py
- src/test/pmem2_map/TESTS.py
- src/test/pmem_map_file_trunc/TESTS.py
- src/test/scope/TESTS.py
- src/test/testframework.py
- src/test/unittest/basetest.py
- src/test/unittest/builds.py
- src/test/unittest/configurator.py
- src/test/unittest/context.py
- src/test/unittest/ctx_filter.py
- src/test/unittest/filesystems.py
- src/test/unittest/futils.py
- src/test/unittest/test_types.py
- src/test/unittest/tools.py
- src/test/unittest/valgrind.py
- src/test/win_common/TESTS.py
- divide BaseTest class with only abstract test workflow scaffolding
and Test inheriting from it which implements this interface
in details, in a way common to most tests. It is therefore
advised to use Test as a common base class for test cases rather
than BaseTest directly. The intention is to make BaseTest more universal,
and not coupled in any specific test implementation.
- move main tests execution responsibilities into RUNTESTS.py, including:
* creation of context instances, executing the test over all contexts
* test result exceptions are ultimately handled in RUNTESTS.py
* basic test execution status messages are emmited by RUNTESTS.py
The rationale is that the test class itself should not care about how it
is run in the context of the whole test set execution.
- remake …
> test (py): refactor framework

- src/test/obj_pool_lookup/obj_pool_lookup.vcxproj
Fixes regression from 13eb4647d4e789a6b8b8336b84020cd8edd091d3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4314)
> test: fix reference to renamed VS project

- src/benchmarks/pmemobj_tx_add_range.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4311)
> Static analyzer fixes for master

- src/benchmarks/blk.cpp
- src/benchmarks/pmem_memcpy.cpp
- src/benchmarks/rpmem.cpp
- src/examples/libpmem/manpage.c
- src/examples/libpmemblk/assetdb/asset_checkin.c
- src/examples/libpmemblk/assetdb/asset_checkout.c
- src/examples/libpmemblk/assetdb/asset_list.c
- src/examples/libpmemblk/assetdb/asset_load.c
- src/examples/libpmemblk/manpage.c
- src/examples/libpmemlog/logfile/addlog.c
- src/examples/libpmemlog/logfile/printlog.c
- src/examples/libpmemlog/manpage.c
- src/examples/libpmemobj/manpage.c
- src/examples/libpmemobj/setjmp.c
- src/libpmempool/check_util.c
- src/test/rpmemd_config/rpmemd_config_test.c
- src/tools/rpmemd/rpmemd_config.c
- src/tools/rpmemd/rpmemd_log.c
Not important enough to backport to older branches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4310)
> Static analyzer fixes for stable-1.7

- utils/pmdk.spec.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4295)
> pmem2: include pmem2 manpages in libpmem2-devel rpm

- src/test/pmem2_integration/TESTS.py
- src/test/pmem2_integration/pmem2_integration.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4291)
> pmem2: set offset and len integration test

- src/test/unittest/valgrind.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4317)
> test: (py) fix framework if no valgrind found

- src/libpmem2/config.c
- src/libpmem2/config.h
- src/libpmem2/map.c
- src/libpmem2/map_posix.c
- src/libpmem2/pmem2.c
- src/test/Makefile
- src/test/pmem2_granularity_detection/Makefile
- src/test/pmem2_granularity_detection/TESTS.py
- src/test/scope/TESTS.py
- src/test/tools/gran_detecto/gran_detecto.c
- src/test/unittest/futils.py
- src/test/unittest/tools.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4290)
> common: PMEM2_FORCE_GRANULARITY + misc fixes

- src/test/pmem2_granularity/TESTS.py
- src/test/pmem2_granularity/err10.log.match
- src/test/pmem2_granularity/err2.log.match
- src/test/pmem2_granularity/err3.log.match
- src/test/pmem2_granularity/err4.log.match
- src/test/pmem2_granularity/err5.log.match
- src/test/pmem2_granularity/err8.log.match
- src/test/pmem2_granularity/err9.log.match
- src/test/pmem2_granularity/linux_eadr_paths/eadr_available/sys/bus/nd/devices/region0
- src/test/pmem2_granularity/linux_eadr_paths/eadr_available/sys/devices/platform/pmem/ndbus/region0/persistence_domain
- src/test/pmem2_granularity/linux_eadr_paths/eadr_not_available/sys/bus/nd/devices/region0
- src/test/pmem2_granularity/mocks_posix.c
- review is welcome 
- it needs rebase on Greg091 test: tests for granularity in pmem2 (Windows part)
- some minor fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4316)
> pmem2: granularity linux tests

- doc/libpmem2/pmem2_config_set_offset.3.md
- src/test/pmem2_config/TESTS.py
- src/test/pmem2_config/pmem2_config.c
In a man page and comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4319)
> pmem2: reword some text

- src/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4326)
> example: fix build examples

- utils/build-dpkg.sh
Making it work properly would require a fair amount of work, for little benefit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4327)
> build-dpkg: don't create .dsc

- src/include/libpmem2.h
- src/libpmem/pmem.c
- src/libpmem2/aarch64/init.c
- src/libpmem2/memops_generic.c
- src/libpmem2/pmem2_arch.h
- src/libpmem2/ppc64/init.c
- src/libpmem2/ppc64/platform_generic.c
- src/libpmem2/ppc64/platform_generic.h
- src/libpmem2/x86_64/init.c
I recommend reviewing this PR patch by patch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4324)
> pmem2: cleanups, in preparation for flush & persist support

- src/test/unittest/context.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4338)
> test: (py) fix requirements global state error

- src/test/obj_persist_count/TEST0
- src/test/obj_persist_count/TEST1
- src/test/obj_persist_count/TEST2
- src/test/obj_persist_count/TEST3
- src/test/obj_persist_count/out2.log.match
- src/test/obj_persist_count/out3.log.match
- src/test/unittest/unittest.sh
This implementation was made following the
solution we discussed on #3940 and on the
[mailing list](https://groups.google.com/d/msg/pmem/2Pl9SOfIPaQ/axyVHu71AgAJ).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4337)
> Fix obj_persist_count test for PPC64

- src/test/unittest/basetest.py
https://github.com/pmem/pmdk/issues/4321
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4348)
> test: (py) add missing pre-execution clean

- src/test/pmem2_granularity_detection/TESTS.py
- src/test/scope/TESTS.py
- src/test/unittest/futils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4331)
> test: (py) fix get_test_tool_path

- src/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4339)
> common: fix build examples

- src/test/pmem2_integration/TESTS.py
- src/test/pmem2_integration/pmem2_integration.c
- src/test/pmem2_integration/pmem2_integration.vcxproj
- src/test/pmem2_integration/pmem2_integration.vcxproj.filters
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4322)
> test: integration tests for granularity in pmem2

- src/libpmem2/libpmem2.def
- src/libpmem2/libpmem2.link.in
- src/test/scope/out13.log.match
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4358)
> pmem2: fix pmem2_config_get_alignment linking

- src/examples/libpmem2/advanced.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4357)
> pmem2: update libpmem2 advanced example

- src/test/pmem2_config_get_alignment/TESTS.py
- src/test/pmem2_config_get_alignment/pmem2_config_get_alignment.c
- src/test/pmem2_config_get_file_size/TESTS.py
- src/test/testframework.py
- src/test/unittest/configurator.py
- src/test/unittest/context.py
- src/test/unittest/ctx_filter.py
- src/test/unittest/devdax.py
- src/test/unittest/futils.py
- src/test/unittest/tools.py
- utils/docker/configure-tests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4347)
> test: (py) add minimal device dax support

- src/test/obj_basic_integration/TESTS.py
- src/test/obj_tx_add_range/TESTS.py
- src/test/pmem2_config/TESTS.py
- src/test/pmem2_config_get_alignment/TESTS.py
- src/test/pmem2_config_get_file_size/TESTS.py
- src/test/pmem2_granularity_detection/TESTS.py
- src/test/pmem2_integration/TESTS.py
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4340)
> test: apply granularities

- src/test/unittest/granularity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4361)
> test: (py) fix granularity filter if any required

- appveyor.yml
- src/test/RUNTESTS.py
- src/test/testconfig.py.example
- src/test/unittest/configurator.py
- src/test/unittest/futils.py
- src/test/unittest/tools.py
- utils/docker/configure-tests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4376)
> Test fail refinement

- src/test/pmem2_integration/TESTS.py
- src/test/pmem2_integration/pmemcheck5.log.match
- src/test/pmem2_map/TESTS.py
- src/test/pmem2_map/pmem2_map.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4368)
> test: add pmem2_map/integration DevDax tests

- doc/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4381)
> doc: fix Makefile make doc/web

- _data/releases_linux.yml
- _data/releases_windows.yml
**Merge after https://github.com/pmem/pmdk/pull/4381**
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4382)
> doc: add libpmem2 to releases gh-pages

- src/test/obj_memops/obj_memops.c
Ref: #4369 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4393)
> test: initialize redo log in obj_memops

- src/test/obj_tx_strdup/TEST0
TEST1 runs pmemcheck and has a test specific match file.
Ref: #4360
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4394)
> test: disable pmemcheck in obj_tx_strdup/TEST0
