src/test/unittest/unittest.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4372)

test: add validation to TEST_CASE_PROCESS if test returns negative value

---

src/test/unittest/granularity.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4399)

test: set PMEM_IS_PMEM_FORCE if forcing granularity

---

doc/libpmem2/pmem2_config_get_alignment.3.md
src/include/libpmem2.h
src/libpmem2/config_posix.c
src/libpmem2/config_windows.c
src/libpmem2/map.c

detected by KW, X mod 0 is undefined
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4385)

pmem2: additional alignment assert

---

src/test/pmem2_config_get_file_size/TESTS.py
src/test/pmem2_config_get_file_size/pmem2_config_get_file_size.c
src/test/unittest/Makefile
src/test/unittest/libut.vcxproj
src/test/unittest/libut.vcxproj.filters
src/test/unittest/ut_fh.c
src/test/unittest/ut_fh.h
src/test/unittest/ut_pmem2_config.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4308)

test: add HANDLE-based tests for pmem2_config_get_file_size

---

src/test/unittest/devdax.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4373)

test (py): enable defining devdax requirements

---

doc/libpmem2/libpmem2.7.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4404)

doc: add man for PMEM2_FORCE_GRANULARITY

---

src/test/pmem2_config_get_file_size/TESTS.py
src/test/pmem2_config_get_file_size/pmem2_config_get_file_size.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4416)

test: fix pmem2_config_get_file_size

---

src/common/out.c

Right now it's only supported in ERR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4342)

common: support !! syntax in LOG and FATAL

---

utils/docker/pull-or-rebuild-image.sh

It fixes rebuilding the image in case of GitHub Actions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4365)

Set the commit range in case of GitHub Actions

---

doc/libpmem2/pmem2_config_get_alignment.3.md
doc/libpmem2/pmem2_config_get_file_size.3.md
doc/libpmem2/pmem2_config_set_fd.3.md
doc/libpmem2/pmem2_config_set_length.3.md
doc/libpmem2/pmem2_config_set_offset.3.md
doc/libpmem2/pmem2_map.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4414)

doc: doc fixes rm backslash

---

src/Makefile

#4371
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4377)

fix "make install" from an unbuilt tree

---

src/test/pmem2_config/TESTS.py
src/test/pmem2_config/pmem2_config.c
src/test/pmem2_config_get_alignment/TESTS.py
src/test/pmem2_config_get_alignment/pmem2_config_get_alignment.c
src/test/pmem2_config_get_file_size/TESTS.py
src/test/pmem2_config_get_file_size/pmem2_config_get_file_size.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4366)

pmem2: cleanup pmem2 tests

---

src/libpmem2/map_windows.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4419)

pmem2: (win) mark create_mapping as static

---

src/test/log_basic/out0.log.match
src/test/log_basic/out1.log.match
src/test/log_basic/out2.log.match
src/test/log_basic/out3.log.match
src/test/log_basic/out5.log.match
src/test/log_basic/out6.log.match
src/test/log_pool/TEST7
src/test/log_pool/out0.log.match
src/test/log_pool/out1.log.match
src/test/log_pool/out11.log.match
src/test/log_pool/out7.log.match
src/test/log_recovery/out0.log.match
src/test/log_recovery/out1.log.match
src/test/pmempool_check/out1.log.match
src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4418)

Fix libpmemlog unity tests for PPC64LE

---

src/test/unittest/unittest.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4420)

test: fix typo in unittest.sh

---

src/libpmem/memops_generic.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4417)

pmem: add 128 bytes flush to memset

---

src/test/pmem2_granularity/pmem2_granularity.c
src/test/pmem2_integration/pmem2_integration.c
src/test/pmem2_map/TESTS.py
src/test/pmem2_map/pmem2_map.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4396)

pmem2: cleanup pmem2 tests part 2

---

src/test/unittest/unittest.sh

Ref: pmem/pmdk/issues/4231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4428)

common: fix noisy tests

---

src/libpmem2/config.c
src/libpmem2/config.h
src/libpmem2/map.c
src/libpmem2/map.h
src/libpmem2/map_posix.c
src/libpmem2/map_windows.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4402)

pmem2: remove and replace pmem2_get_length func

---

src/test/rpmem_basic/TEST7
src/test/rpmem_basic/rpmem_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4431)

test: rpmem_basic Device DAX fixes

---

src/test/pmem2_integration/TESTS.py
src/test/pmem2_integration/pmem2_integration.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4388)

test: integration tests for alignment

---

src/libpmem2/map_windows.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4437)

pmem2: add missing ERR to windows pmem2_map func

---

doc/generated/pmemobj_cancel.3
doc/generated/pmemobj_publish.3
doc/generated/pmemobj_reserve.3
doc/generated/pmemobj_set_value.3
doc/generated/pmemobj_tx_publish.3
doc/generated/pmemobj_xreserve.3
doc/generated/pobj_reserve_alloc.3
doc/generated/pobj_reserve_new.3
doc/libpmemobj/pmemobj_tx_begin.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4443)

fix manpage warnings

---

src/common/ctl.c
src/common/os.h
src/common/os_auto_flush_linux.c
src/common/valgrind/memcheck.h
src/common/valgrind/valgrind.h
src/libpmem/ppc64/init.c
src/libpmem2/config.c
src/libpmemobj/palloc.c
src/libpmemobj/tx.c
src/test/blk_non_zero/blk_non_zero.c
src/test/unittest/unittest.sh
src/test/util_poolset/mocks_windows.c
src/tools/daxio/daxio.c
src/tools/pmempool/Makefile
src/tools/rpmemd/rpmemd.c
src/tools/rpmemd/rpmemd_fip.c
src/windows/include/platform.h
utils/cstyle

One functional issue (man page Makefile), all the rest are in comments.  Plus all the copyright date bumps!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4438)

pre-release spelchekar run

---

src/test/tools/pmemspoil/spoil.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4442)

test: fix pmemspoil blk arena offset

---

src/libpmempool/check_btt_info.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4439)

pool: fix btt offset calculation

---

src/test/unittest/unittest.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4444)

test: fix lane and arena offsets in unittest.sh

---

src/libpmem/ppc64/init.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4447)

pmem: change ppc64 init logs to experimental

---

src/test/pmempool_info/out27.log.match

Too obvious fix to not commit immediately...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4451)

pool: accept "Machine" of "PPC64"

---

src/test/pmempool_transform/out10.log.match
src/test/pmempool_transform/out13.log.match
src/test/pmempool_transform/out17.log.match
src/test/pmempool_transform/out23.log.match
src/test/pmempool_transform/out24.log.match
src/test/pmempool_transform/out3.log.match
src/test/pmempool_transform/out4.log.match
src/test/pmempool_transform/out5.log.match
src/test/pmempool_transform/out6.log.match

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4465)

test: fix pmempool_transform for ppc64le

---

src/test/pmempool_sync/TEST0
src/test/pmempool_sync/out10.log.match
src/test/pmempool_sync/out2.log.match
src/test/pmempool_sync/out4.log.match

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4464)

test: fix pmempool_sync for ppc64le

---

src/test/util_poolset_size/TEST1
src/test/util_poolset_size/out1.log.match

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4463)

test: fix util_poolset_size for ppc64le

---

src/test/blk_pool/out38.log.match
src/test/blk_pool/out40.log.match

Both tests where expecting wrong file sizes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4460)

test: fix blk_pool for ppc64le

---

src/test/bttdevice/out0.log.match
src/test/bttdevice/out1.log.match
src/test/tools/bttcreate/bttcreate.c
src/test/tools/pmemspoil/spoil.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4461)

test: fix bttdevice for ppc64le

---

src/test/blk_non_zero/TEST10

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4459)

test: fix blk_non_zero/TEST10 non zero size

---

src/test/blk_nblock/TEST3
src/test/blk_nblock/TEST4
src/test/blk_nblock/out2.log.match
src/test/blk_nblock/out3.log.match
src/test/blk_nblock/out4.log.match

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4457)

test: fix blk_nblock for ppc64le

---

doc/Makefile
doc/libpmemobj/pmemobj_defrag.3
doc/libpmemobj/pmemobj_get_user_data.3
doc/libpmemobj/pmemobj_set_user_data.3
doc/libpmemobj/pmemobj_tx_get_user_data.3
doc/libpmemobj/pmemobj_tx_set_user_data.3

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4476)

doc: add missing aliases

---

doc/Makefile
utils/get_aliases.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4479)

common: fix generation of web documentation

---

src/test/libpmempool_sync/TEST0

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4484)

test: fix libpmempool_sync/TEST0 header size

---

src/test/libpmempool_api/out12.log.match

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4481)

test: fix libpmempool_api for ppc64le

---

src/test/libpmempool_map_flog/out2.log.match

Ref: #4478 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4480)

test: fix libpmempool_map_flog/TEST2 for ppc64le

---

doc/libpmemobj/pmemobj_alloc.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4485)

doc: add pmemobj_defrag to its man page NAME section

---

src/test/obj_tx_strdup/TEST1

Cause of change described in issue.
Ref:/pmem/pmdk/issues/4423
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4450)

test: move part of the test to a new test case

---

doc/libpmem2/pmem2_unmap.3.md
src/include/libpmem2.h
src/libpmem2/Makefile
src/libpmem2/libpmem2.c
src/libpmem2/libpmem2.vcxproj
src/libpmem2/libpmem2.vcxproj.filters
src/libpmem2/map.c
src/libpmem2/map_posix.c
src/libpmem2/map_windows.c
src/libpmem2/persist.c
src/libpmem2/persist.h
src/libpmem2/persist_posix.c
src/libpmem2/persist_windows.c
src/libpmem2/pmem2.c
src/test/Makefile.inc
src/test/pmem2_granularity/pmem2_granularity.c
src/test/pmem2_granularity/pmem2_granularity.vcxproj
src/test/pmem2_granularity/pmem2_granularity.vcxproj.filters
src/test/pmem2_map/Makefile
src/test/pmem2_map/pmem2_map.c
src/test/pmem2_map/pmem2_map.vcxproj
src/test/pmem2_map/pmem2_map.vcxproj.filters

Documentation: #4440
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4333)

pmem2: implement pmem2_get_[flush|drain|persist]_fn

---

src/test/obj_defrag_advanced/TESTS.py
src/test/obj_fragmentation2/TESTS.py
src/test/pmem2_config/TESTS.py
src/test/pmem2_config_get_alignment/TESTS.py
src/test/pmem2_config_get_file_size/TESTS.py
src/test/pmem2_granularity/TESTS.py
src/test/pmem2_granularity_detection/TESTS.py
src/test/pmem2_integration/TESTS.py
src/test/scope/TESTS.py
src/test/testframework.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4448)

test: add separate namespace for granularity

---

src/test/obj_memops/obj_memops.c

Ref: #4369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4489)

test: fix buffer overflow in obj_memops test

---

utils/build-dpkg.sh

Grammar fixes, expand a short shaped like itself, let shorts and longs work stand-alone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4491)

make package descs betterer

---

Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4497)

minor build system fixes

---

src/test/obj_defrag_advanced/TESTS.py
src/test/obj_fragmentation2/TESTS.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4499)

test: disable Valgrind in specified defrag test cases

---

src/test/obj_defrag/obj_defrag.vcxproj
src/test/obj_defrag/obj_defrag.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4513)

test: vcxproj obj_defrag fixes

---

src/libpmemobj/palloc.c

Ref: #4505
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4508)

obj: fix defrag when the last object is referenced the most

---

src/common/sys_util.h
src/test/blk_rw_mt/blk_rw_mt.c
src/test/obj_critnib_mt/obj_critnib_mt.c
src/test/obj_ctl_arenas/obj_ctl_arenas.c
src/test/obj_defrag_advanced/obj_defrag_advanced.c
src/test/obj_direct/obj_direct.c
src/test/obj_direct_volatile/obj_direct_volatile.c
src/test/obj_lane/obj_lane.c
src/test/obj_locks/obj_locks.c
src/test/obj_oid_thread/obj_oid_thread.c
src/test/obj_pmalloc_mt/obj_pmalloc_mt.c
src/test/obj_pmalloc_oom_mt/obj_pmalloc_oom_mt.c
src/test/obj_pmalloc_rand_mt/obj_pmalloc_rand_mt.c
src/test/obj_sync/obj_sync.c
src/test/obj_tx_locks/obj_tx_locks.c
src/test/obj_tx_mt/obj_tx_mt.c
src/test/out_err_mt/out_err_mt.c
src/test/out_err_mt_win/out_err_mt_win.c
src/test/pmem_is_pmem/pmem_is_pmem.c
src/test/pmem_is_pmem_windows/pmem_is_pmem_windows.c
src/test/rpmem_basic/rpmem_basic.c
src/test/rpmem_fip/rpmem_fip_test.c
src/test/unittest/unittest.h

It's best to review this PR one patch at the time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4516)

test: catch threading failures as soon as possible

---

src/common/util.c
src/common/util.h
src/libpmem2/pmem2_utils_linux.c
src/test/tools/dllview/dllview.vcxproj
src/test/tools/sparsefile/sparsefile.vcxproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4390)

pmem2: snprintf coverity fix

---

src/test/util_cpuid/TEST0

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4519)

test: fix util_cpuid to require x86_64

---

doc/Makefile
doc/libpmem2/.gitignore
doc/libpmem2/pmem2_get_drain_fn.3.md
doc/libpmem2/pmem2_get_flush_fn.3.md
doc/libpmem2/pmem2_get_persist_fn.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4440)

doc: add pmem2_get_[flush|drain|persist]_fn man pages

---

_data/releases_linux.yml
_data/releases_windows.yml

The only difference between Win and Lin is 'pmem2_config_set_handle.3' func on Win.
if there are any other differences to include, please let me know ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4531)

doc: sort and update funcs in 'releases_*.yml' for master branch

---

src/test/obj_defrag_advanced/TESTS.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4529)

test: fix cstyle in TESTS.py in obj_defrag_advanced test

---

src/test/Makefile
src/test/pmem2_persist_valgrind/.gitignore
src/test/pmem2_persist_valgrind/Makefile
src/test/pmem2_persist_valgrind/TESTS.py
src/test/pmem2_persist_valgrind/pmem2_persist_valgrind.c
src/test/pmem2_persist_valgrind/pmemcheck2.log.match
src/test/unittest/futils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4407)

test: tests for pmem2_persist_fn with Valgrind

---

doc/libpmem2/libpmem2.7.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4503)

doc: describe granularity concept

---

doc/libpmem/pmem_memmove_persist.3.md
src/libpmem/pmem.c
src/libpmem2/pmem2_arch.h
src/libpmem2/x86_64/init.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4504)

pmem: mem[cpy|set] optimization when eADR is available

---

doc/pmreorder/pmreorder.1.md

1. fixes a visual glitch, 2. makes my checker happy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4535)

reword an unbreakable man line

---

utils/check_license/check-headers.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4544)

common: print warning only in verbose mode

---

README.md

... and correct descriptions of other badges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4543)

common: add badge for GHA build

---

src/libpmem2/x86_64/cpu.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4547)

pmem: remove remnants of arm port from x86 arch code

---

utils/docker/build-local.sh
utils/docker/build-travis.sh
utils/docker/prepare-for-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4545)

common: change owner of WORKDIR only on CI's

---

src/include/libpmem2.h
src/libpmem2/map.h
src/libpmem2/map_posix.c
src/libpmem2/map_windows.c
src/libpmem2/persist.c
src/libpmem2/persist.h
src/libpmem2/pmem2.c
src/test/pmem2_granularity/pmem2_granularity.vcxproj
src/test/pmem2_granularity/pmem2_granularity.vcxproj.filters
src/test/pmem2_map/pmem2_map.vcxproj
src/test/pmem2_map/pmem2_map.vcxproj.filters
src/test/pmem2_persist/Makefile
src/test/pmem2_persist/pmem2_persist.vcxproj
src/test/pmem2_persist/pmem2_persist.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4518)

pmem2: add pmem2_mem[cpy|move|set] functions

---

utils/check-manpage
utils/check-manpages

Not fit for automated use yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4007)

a tool for checking man pages

---

utils/docker/build-local.sh
utils/docker/build-travis.sh
utils/docker/prepare-for-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4558)

Merge stable-1.7 into stable-1.8

---

utils/docker/build-local.sh
utils/docker/build-travis.sh
utils/docker/prepare-for-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4559)

Merge stable-1.8 into master

---

src/test/obj_defrag_advanced/TESTS.py
src/test/obj_fragmentation2/TESTS.py
src/test/pmem2_map/TESTS.py
src/test/pmem2_source_alignment/TESTS.py
src/test/pmem2_source_file_size/TESTS.py
src/test/pmem_memcpy/TESTS.py
src/test/unittest/context.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4560)

test: (py) make ctx exec accept non string args

---

src/test/pmem2_source_alignment/pmem2_source_alignment.vcxproj.filters
src/test/pmem2_source_file_size/pmem2_source_file_size.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4571)

pmem2: fix xml tags in pmem2_source_* vcxproj

---

src/common/badblock_ndctl.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4575)

common: make two comments more precise

---

utils/docker/images/Dockerfile.fedora-31

It's an inept continuation of the tremendous work
done in commit f8f0927.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4563)

common: document which packages are needed for what

---

doc/pmreorder/pmreorder.1.md

As a side effect, this makes a man page properly wrap on narrow screens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4576)

link a doc reference to HTML rather than XML source

---

utils/check-area.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4568)

common: simplify listing files modified in commit

---

utils/docker/images/Dockerfile.fedora-31
utils/docker/images/Dockerfile.ubuntu-19.10

Reduce docker images size using [Docker best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4573)

common: reduce docker images size

---

doc/libpmemobj/pmemobj_tx_begin.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4581)

doc: fix return type of pmemobj_tx_stage()

---

.github/workflows/gha.yml
.travis.yml
utils/check-commits.sh
utils/docker/build-travis.sh
utils/docker/pull-or-rebuild-image.sh
utils/docker/run-coverity.sh
utils/docker/run-doc-update.sh
utils/docker/set-ci-vars.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4564)

common: unify code for Travis and GitHub Actions CIs

---

Makefile
utils/check-manpages

After man pages are generated, see if `lexgrog` or `man --warnings` have anything to say.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4584)

test man page correctness

---

doc/libpmem2/libpmem2.7.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4599)

doc: fix bold tag in libpmem2.7.md

---

utils/check-commits.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4579)

common: fix check commits

---

src/test/obj_defrag_advanced/TESTS.py
src/test/unittest/context.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4562)

test: (py) add require_free_space

---

utils/docker/run-coverity.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4601)

common: fix failing Coverity build

---

.github/workflows/gha.yml
utils/docker/images/push-image.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4603)

common: add DOCKERHUB_USER/PASSWORD secrets to GHA yaml script

---

src/test/obj_defrag_advanced/Makefile

On my machine, it decreases TEST3 time from 52s to 20s and TEST5 from 30s to 11s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4604)

test: build obj_defrag_advanced with some optimizations

---

.github/workflows/gha.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4606)

common: reenable rpmem tests on GHA

---

src/common.inc
src/test/obj_defrag_advanced/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4607)

test: use -Og only when compiler supports it

---

src/examples/libpmem2/advanced.c
src/examples/libpmem2/basic.c
src/test/tools/gran_detecto/gran_detecto.c
src/test/tools/usc_permission_check/usc_permission_check.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4608)

pmem2: update libpmem2 with pmem2_perror func

---

doc/libpmem2/pmem2_map.3.md
src/include/libpmem2.h
src/libpmem2/config.c
src/test/pmem2_map/TESTS.py
src/test/pmem2_map/pmem2_map.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4556)

test: pmem2_map for zero size file and unset length

---

utils/docker/set-ci-vars.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4614)

common: add and export CI_CPU_ARCH environment variable

---

utils/check-commits.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4613)

common: fix check-commits.sh to make it work on GitHub Actions CI

---

doc/libpmem2/pmem2_source_from_fd.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4577)

doc: fix pmem2_source documentation

---

utils/check-area.sh
utils/check-commit.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4615)

common: add "core" to the list of valid commit prefixes

---

.github/workflows/gha.yml
utils/docker/build-local.sh
utils/docker/build-travis.sh

As GCC is very aggressive in assuming that undefined behaviour means "can't happen" (if it does, that's a program bug), we should keep an eye on these.  This includes even cases that are allowed by the architecture (eg. unaligned accesses on x86) but forbidden by the C standard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4300)

enable UBSAN in one of Travis jobs

---

doc/libpmem2/pmem2_config_new.3.md
doc/libpmem2/pmem2_source_from_fd.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4626)

doc: improve documentation of pmem2_source and pmem2_config

---

doc/Makefile
doc/libpmem2/.gitignore
doc/libpmem2/libpmem2.7.md
doc/libpmem2/pmem2_get_memcpy_fn.3
doc/libpmem2/pmem2_get_memmove_fn.3.md
doc/libpmem2/pmem2_get_memset_fn.3

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4598)

doc: add pmem2_get_mem[cpy|mov|set] doc

---

_data/releases_linux.yml
_data/releases_windows.yml

Merge after #4598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4628)

doc: update releases win/lnx lists

---

.github/workflows/gha.yml
.travis.yml
appveyor.yml
utils/docker/build-travis.sh
utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4629)

common: minor CI improvements

---

src/test/unittest/context.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4632)

test: (py) simplify suppress exception

---

utils/docker/images/build-image.sh
utils/docker/images/push-image.sh
utils/docker/pull-or-rebuild-image.sh
utils/docker/set-ci-vars.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4634)

common: make Docker images and files architecture-specific

---

src/test/obj_fragmentation2/TESTS.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4635)

test: (py) fix a setting an env variable in obj_fragmentation2 test

---

utils/docker/build-local.sh
utils/docker/build-travis.sh

Fixes cce1f53abe888671b1decebf115d7f5ca024583e.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4636)

common: use new per-arch images

---

src/examples/libpmem2/basic.c
src/test/ex_libpmem2/TESTS.py
src/test/unittest/futils.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4616)

Test: generalize ex_libpmem2 tests

---

src/test/unittest/granularity.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4641)

test: (py) multiple granularities requirements

---

src/include/libpmem2.h
src/test/pmem2_perror/pmem2_perror.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4648)

pmem2: remove pmem2_source_file_size compat wrapper

---

src/test/unittest/granularity.py

fixes bug introduced in 09aff7f
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4650)

test: fix skipping Any tests

---

src/test/obj_persist_count/out2.log.match

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4638)

test: Fix obj_persist_count/TEST2

---

src/benchmarks/benchmark.hpp
src/benchmarks/blk.cpp
src/benchmarks/log.cpp
src/benchmarks/obj_pmalloc.cpp
src/benchmarks/pmem_memset.cpp
src/benchmarks/pmemobj_tx_add_range.cpp
src/benchmarks/rpmem.cpp
src/common/libpmemcommon.vcxproj
src/common/libpmemcommon.vcxproj.filters
src/common/rand.h
src/test/obj_critnib_mt/obj_critnib_mt.c
src/test/pmem2_integration/pmem2_integration.c

Windows does not allow seeding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4625)

obey random seeds in several more tests&benchmarks

---

doc/Makefile
doc/libpmem2/.gitignore
doc/libpmem2/pmem2_config_set_sharing.3.md
doc/libpmem2/pmem2_map.3.md
src/include/libpmem2.h
src/libpmem2/config.c
src/libpmem2/config.h
src/libpmem2/map.c
src/libpmem2/map.h
src/libpmem2/map_posix.c
src/libpmem2/map_windows.c
src/libpmem2/pmem2.c
src/test/pmem2_config/TESTS.py
src/test/pmem2_config/pmem2_config.c
src/test/pmem2_integration/TESTS.py
src/test/pmem2_integration/pmem2_integration.c
src/test/pmem2_map/TESTS.py
src/test/pmem2_map/pmem2_map.c
src/test/pmem2_map/pmem2_map.vcxproj
src/test/pmem2_map/pmem2_map.vcxproj.filters

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4642)

pmem2: add shared/private mapping support

---

src/common/badblock.c
src/common/badblock_ndctl.c
src/common/badblock_none.c
src/common/os_badblock.h
src/libpmem2/Makefile
src/libpmem2/badblocks.h
src/libpmem2/badblocks_ndctl.c
src/libpmem2/badblocks_none.c
src/libpmem2/extent.h
src/libpmem2/extent_freebsd.c
src/libpmem2/extent_linux.c
src/libpmempool/replica.c
src/test/tools/extents/Makefile
src/test/util_badblock/util_badblock.c
src/test/util_extent/Makefile
src/tools/pmempool/info.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4665)

common: move extent* files and os_badblocks_(count|get) to libpmem2

---

src/common/badblock_ndctl.c
src/common/libpmemcommon.vcxproj
src/common/libpmemcommon.vcxproj.filters
src/common/pmemcommon.inc
src/common/set.c
src/common/set_badblocks.c
src/common/set_badblocks.h
src/libpmem2/badblocks_ndctl.c
src/libpmemblk/libpmemblk.vcxproj
src/libpmemblk/libpmemblk.vcxproj.filters
src/libpmemlog/libpmemlog.vcxproj
src/libpmemlog/libpmemlog.vcxproj.filters
src/libpmemobj/libpmemobj.vcxproj
src/libpmemobj/libpmemobj.vcxproj.filters
src/libpmempool/check_bad_blocks.c
src/libpmempool/libpmempool.vcxproj
src/libpmempool/libpmempool.vcxproj.filters
src/libpmempool/replica.c
src/test/Makefile.inc
src/test/obj_sds/obj_sds.vcxproj
src/test/obj_sds/obj_sds.vcxproj.filters
src/test/util_badblock/util_badblock.c
src/tools/pmempool/common.c
src/tools/pmempool/info.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4666)

common: rename common/badblock.c to common/set_badblocks.c

---

src/common/badblock_ndctl.c
src/common/badblock_none.c
src/common/os_badblock.h
src/common/set_badblocks.c
src/libpmem2/badblocks.h
src/libpmem2/badblocks_ndctl.c
src/libpmem2/badblocks_none.c
src/libpmempool/check_bad_blocks.c
src/libpmempool/replica.c
src/libpmempool/replica.h
src/test/util_badblock/util_badblock.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4667)

common: move the rest of badblock_ndctl.c to libpmem2

---

doc/Makefile
doc/libpmem2/.gitignore
doc/libpmem2/pmem2_config_clear_address.3.md
doc/libpmem2/pmem2_config_set_address.3.md
src/include/libpmem2.h
src/libpmem2/config.c
src/libpmem2/config.h
src/libpmem2/libpmem2.link.in
src/libpmem2/map_posix.c
src/libpmem2/map_windows.c
src/libpmem2/pmem2.c
src/test/pmem2_config/TESTS.py
src/test/pmem2_config/pmem2_config.c
src/test/pmem2_map/TESTS.py
src/test/pmem2_map/pmem2_map.c
src/test/scope/out13.log.match

implementation + tests + documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4624)

pmem2: add map fixed noreplace support to linux and windows

---

src/test/obj_fragmentation2/TESTS.py
src/test/unittest/context.py
src/test/unittest/ctx_filter.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4640)

test: (py) add generic param

---

src/test/pmem2_integration/pmem2_integration.c
src/test/pmem2_memcpy/memcpy_common.c
src/test/pmem2_memcpy/pmem2_memcpy.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4670)

test: fix pmemcheck defects in tests

---

src/libpmem2/pmem2_utils.c
src/libpmem2/pmem2_utils.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4676)

pmem2: add pmem2_zalloc()

---

src/libpmem2/badblocks_ndctl.c
src/libpmem2/extent.h
src/libpmem2/extent_freebsd.c
src/libpmem2/extent_linux.c
src/test/tools/extents/extents.c
src/test/util_extent/util_extent.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4675)

pmem2: make extent functions operate on file descriptor

---

src/common/file_posix.c
src/libpmem2/pmem2_utils.h
src/libpmem2/pmem2_utils_linux.c
src/libpmem2/pmem2_utils_other.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4677)

pmem2: mv get ddax region id to pmem2

---

src/libpmem2/badblocks_ndctl.c
src/libpmem2/ndctl_region_namespace.c
src/libpmem2/usc_ndctl.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4680)

pmem2: two minor fixes

---

src/libpmem2/extent_linux.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4684)

pmem2: remove incorrect close() calls

---

doc/pmreorder/pmreorder.1.md
src/core/valgrind_internal.h
src/libpmem2/persist.c
src/test/Makefile
src/test/pmem2_api/.gitignore
src/test/pmem2_api/Makefile
src/test/pmem2_api/TESTS.py
src/test/pmem2_api/pmem2_api.c
src/test/unittest/futils.py
src/test/unittest/ut_pmem2.h
src/test/unittest/ut_pmem2_map.c
src/test/unittest/ut_pmem2_map.h
src/test/unittest/ut_pmem2_source.c
src/test/unittest/ut_pmem2_source.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4668)

pmem2: add PMEM2_API_START() and PMEM2_API_END() to pmem2 API

---

src/test/obj_defrag_advanced/TESTS.py
src/test/obj_fragmentation2/TESTS.py
src/test/obj_tx_add_range/TESTS.py
src/test/obj_tx_add_range_direct/TESTS.py
src/test/obj_ulog_size/TESTS.py
src/test/unittest/valgrind.py

enforcing valgrind tool if tests disables it
should not be possible
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4661)

test: fix disabling valgrind mechanism

---

src/test/scope/TESTS.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4687)

test: disable Valgrind in scope tests

---

src/test/unittest/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4655)

test: x86_64 arch is AMD64 on win

---

src/common/os_deep_linux.c
src/common/pmemcommon.inc
src/libpmem/Makefile
src/libpmem2/Makefile
src/libpmem2/deep_sync.h
src/libpmem2/deep_sync_linux.c
src/libpmem2/deep_sync_none.c
src/libpmem2/libpmem2.vcxproj
src/libpmem2/libpmem2.vcxproj.filters
src/test/Makefile.inc
src/test/pmem_deep_persist/TEST0
src/test/pmem_deep_persist/TEST0.PS1
src/test/pmem_deep_persist/TEST1
src/test/pmem_deep_persist/TEST1.PS1
src/test/pmem_deep_persist/TEST2
src/test/pmem_deep_persist/TEST3
src/test/pmem_deep_persist/TEST4
src/test/pmem_deep_persist/TEST4.PS1
src/test/pmem_deep_persist/TEST5
src/test/pmem_deep_persist/TEST5.PS1
src/test/pmem_deep_persist/TEST6
src/test/pmem_deep_persist/TEST6.PS1
src/test/pmem_deep_persist/TEST7
src/test/pmem_deep_persist/TEST7.PS1
src/test/pmem_deep_persist/TEST8
src/test/pmem_deep_persist/TEST9

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4683)

pmem2: mv ddax deep write to pmem2

---

src/test/unittest/configurator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4689)

missing spaces in --help

---

src/test/pmem2_mem_ext/pmem2_mem_ext.c
src/test/pmem2_source_size/pmem2_source_size.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4690)

test: fix pmemcheck and memcheck defects in tests

---

src/libpmem2/x86_64/memcpy/memcpy_nt_avx.h
src/libpmem2/x86_64/memcpy/memcpy_nt_avx512f.h
src/libpmem2/x86_64/memcpy/memcpy_nt_sse2.h
src/libpmem2/x86_64/memset/memset_nt_avx.h
src/libpmem2/x86_64/memset/memset_nt_avx512f.h
src/libpmem2/x86_64/memset/memset_nt_sse2.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4694)

pmem2: (+pmem) call VALGRIND_DO_FLUSH only once per NT memcpy/memset

---

utils/docker/images/install-valgrind.sh

... with optimizations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4708)

common: update pmemcheck in Docker images to the latest version

---

src/libpmem2/badblocks.h
src/libpmem2/badblocks_ndctl.c
src/libpmem2/badblocks_none.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4705)

pmem2: make two bad block functions internal

---

src/include/libpmem2.h
src/libpmem2/libpmem2.def
src/libpmem2/libpmem2.link.in
src/libpmem2/source.c
src/test/scope/out13.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4707)

pmem2: make pmem2_badblock_clear() take pmem2_badblock_context

---

src/test/pmem2_mem_ext/TESTS.py

On my machine output of make pycheck for pmem2_mem_ext is much cleaner:
```
pmem2_mem_ext/TEST0: SETUP      (short/debug/cacheline/variant: libc)
pmem2_mem_ext/TEST0: PASS                       [00.008 s]
pmem2_mem_ext/TEST0: SETUP      (short/debug/cacheline/variant: generic)
pmem2_mem_ext/TEST0: PASS                       [00.010 s]
pmem2_mem_ext/TEST0: SETUP      (short/debug/byte/variant: libc)
pmem2_mem_ext/TEST0: PASS                       [00.010 s]
pmem2_mem_ext/TEST0: SETUP      (short/debug/byte/variant: generic)
pmem2_mem_ext/TEST0: PASS                       [00.008 s]
pmem2_mem_ext/TEST1: SETUP      (short/debug/cacheline/variant: sse2)
pmem2_mem_ext/TEST1: PASS                       [00.066 s]
pmem2_mem_ext/TEST1: SETUP      (short/debug/cacheline/variant: avx) …
```

test: simplify pmem2_mem_ext test by using "generic param" feature

---

src/benchmarks/log.cpp
src/benchmarks/pmem_memset.cpp
src/benchmarks/rpmem.cpp
src/test/unittest/ut_pmem2_source.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4714)

benchmark: test: fix copyrights

---

src/test/obj_defrag_advanced/TESTS.py
src/test/obj_defrag_advanced/obj_defrag_advanced.c

Fix required for #4682
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4711)

test: fix obj_defrag_advanced dump file name collision

---

.github/workflows/gha.yml
utils/docker/images/push-image.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4717)

common: set GHA actions/checkout.fetch-depth to 50

---

src/benchmarks/benchmark.hpp
src/benchmarks/blk.cpp
src/benchmarks/clo.cpp
src/benchmarks/log.cpp
src/benchmarks/obj_locks.cpp
src/benchmarks/obj_pmalloc.cpp
src/benchmarks/pmem_flush.cpp
src/benchmarks/pmem_memset.cpp
src/benchmarks/pmemobj_atomic_lists.cpp
src/benchmarks/pmemobj_gen.cpp
src/benchmarks/pmemobj_persist.cpp
src/benchmarks/pmemobj_tx.cpp
src/benchmarks/pmemobj_tx_add_range.cpp
src/benchmarks/rpmem.cpp
src/common.inc
utils/style_check.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4716)

common: bump clang-format requirement to 9.0

---

src/test/testconfig.sh.example

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4710)

test: sync testconfig.sh.example with pmempool-feature(1) manual

---

src/core/util.c
src/core/valgrind/helgrind.h
src/core/valgrind_internal.h
src/libpmemobj/bucket.c
src/libpmemobj/obj.c
src/libpmemobj/palloc.c
src/libpmemobj/pmalloc.c
src/libpmemobj/tx.c
src/libpmemobj/ulog.c

~~Also from now on On_valgrind == 0 for pmemcheck.~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4701)

core: fine-grained Valgrind plugin detection

---

src/test/Makefile
src/test/Makefile.inc
src/test/RUNTESTS.py
src/test/tools/Makefile
src/test/unittest/Makefile
src/test/unittest/configurator.py

~~obj_defrag_advanced needs to be fixed before this PR can be merged~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4682)

test: support make -jN in pycheck target

---

src/test/common_badblock.sh

Do not discard errors of daxio - log them,
because they may be helpful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4709)

test: do not discard errors of daxio and ndctl, log them

---

.github/workflows/gha.yml

Continuation of 965ebce8738f1896ab5d41addabaff80e4b26b58.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4725)

common: bump GHA checkout action to v2 for Windows too

---

src/common/pmemcommon.inc
src/libpmem2/Makefile
src/libpmem2/extent_none.c
src/test/Makefile.inc
src/test/tools/extents/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4733)

test: add bad block files to LIBPMEM2 internal-(non)debug

---

utils/docker/images/install-libfabric.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4745)

common: disable spin locks in libfabric

---

src/examples/libpmem2/redo/redo.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4727)

examples: fix redo error handling

---

README.md
utils/docker/images/Dockerfile.fedora-31
utils/docker/images/Dockerfile.ubuntu-19.10
utils/pkg-config.sh

I'm leaving the PMDK team soon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4739)

doc: Piotr is the new Marcin

---

src/include/libpmem2.h
src/libpmem2/ndctl_region_namespace.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4750)

pmem2: make ndctl_region_namespace return pmem2 errors

---

src/libpmem2/badblocks_ndctl.c
src/libpmem2/extent.h
src/libpmem2/extent_linux.c
src/libpmem2/extent_none.c
src/libpmem2/pmem2_utils.c
src/libpmem2/pmem2_utils.h
src/test/tools/extents/extents.c
src/test/util_extent/util_extent.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4749)

pmem2: make extent functions return pmem2 errors

---

src/common/badblock_ndctl.c

When a long bad block overlaps with two or more file's extents,
only the first extent is counted as a bad block,
because the original begin and end of a bad block
(`bb_beg` and `bb_end`) are overwritten in the `for` loop
with the values of the first extent:
```
bb_beg = (bb_beg > ext_beg) ? bb_beg : ext_beg;
bb_end = (bb_end < ext_end) ? bb_end : ext_end;
```
Use new auxiliary variables (`nbb_beg` and `nbb_end`)
to store new values and to not overwrite the original ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4765)

common: fix calculation of bad blocks in os_badblocks_get()

---

src/test/unittest/ut_fh.c
src/test/unittest/ut_fh.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4761)

test: add 'execute' protection support for fd/fh abstraction

---

src/include/libpmem2.h

... in more natural order, where core APIs are closer to the beginning
of the file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4778)

pmem2: sort public APIs

---

src/libpmem2/x86_64/init.c
src/test/pmem2_memcpy/TESTS.py
src/test/pmem2_memmove/TESTS.py
src/test/pmem2_memset/TESTS.py
src/test/pmem2_movnt/TESTS.py
src/test/pmem2_movnt_align/TESTS.py
src/test/pmem_memcpy/TESTS.py
src/test/pmem_memmove/TEST0
src/test/pmem_memmove/TEST0.PS1
src/test/pmem_memset/TEST0
src/test/pmem_memset/TEST0.PS1
src/test/pmem_movnt/TEST0
src/test/pmem_movnt/TEST0.PS1
src/test/pmem_movnt_align/TEST0
src/test/pmem_movnt_align/TEST0.PS1
src/test/pmem_movnt_align/TEST1

This PR doesn't depend on #4774, but logically it would make sense to merge it after #4774.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4775)

pmem/pmem2: enable AVX and AVX512F by default

---

src/test/libpmempool_sync/TEST0
src/test/pmem_deep_persist/TEST5
src/test/pmempool_sync/TEST0
src/test/unittest/unittest.sh
src/test/util_poolset/TEST10
src/test/util_poolset/TEST9
src/test/util_poolset/grep10.log.match
src/test/util_poolset/grep9.log.match
src/test/util_poolset/out10.log.match
src/test/util_poolset/out9.log.match
utils/docker/ppc64le.blacklist

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4660)

test: Fix util_poolset for ppc64le

---

src/benchmarks/rpmem.cpp
src/examples/libpmem2/advanced/advanced.c
src/examples/libpmemblk/assetdb/asset_list.c
src/examples/libpmemblk/assetdb/asset_load.c
src/examples/libpmemobj/array/array.c
src/examples/libpmemobj/hashmap/hashmap_rp.c
src/examples/libpmemobj/libart/arttree.c
src/examples/libpmemobj/libart/arttree_examine.c
src/examples/libpmemobj/libart/arttree_search.c
src/examples/libpmemobj/libart/arttree_structures.c
src/examples/libpmemobj/map/data_store.c
src/examples/libpmemobj/pmemobjfs/pmemobjfs.c
src/examples/libpmemobj/pminvaders/pminvaders2.c
src/examples/librpmem/basic.c

Too many people enable that by reflex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4605)

let examples compile with -Wall

---

src/benchmarks/pmemobj_tx.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4759)

benchmark: fix use-after-free in tx realloc benchmark

---

doc/libpmem2/.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4793)

doc: add vm_reservation manuals to .gitignore

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4796)

doc: add vm_reservation functions to linux and windows releases

---

src/test/pmempool_sync_remote/TEST33
src/test/pmempool_sync_remote/TEST34
src/test/util_badblock/TEST4
src/test/util_badblock/TEST7

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4800)

test: fix uninjecting bad blocks

---

src/libpmem2/badblocks_ndctl.c
src/test/Makefile
src/test/pmem2_badblock_mocks/.gitignore
src/test/pmem2_badblock_mocks/Makefile
src/test/pmem2_badblock_mocks/TESTS.py
src/test/pmem2_badblock_mocks/mocks_ndctl.c
src/test/pmem2_badblock_mocks/mocks_other.c
src/test/pmem2_badblock_mocks/mocks_pmem2.c
src/test/pmem2_badblock_mocks/pmem2_badblock_mocks.c
src/test/pmem2_badblock_mocks/pmem2_badblock_mocks.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4766)

test: add pmem2_badblock_mocks test

---

doc/libpmem2/libpmem2.7.md
doc/libpmem2/pmem2_map.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4780)

doc: pmem2 man granularity touch ups

---

doc/Makefile
doc/libpmem2/.gitignore
doc/libpmem2/pmem2_badblock_clear.3.md
doc/libpmem2/pmem2_badblock_context_delete.3
doc/libpmem2/pmem2_badblock_context_new.3.md
doc/libpmem2/pmem2_badblock_next.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4786)

doc: add pmem2_badblock_*() manuals

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4801)

doc: add pmem2_badblock_* functions to linux and windows releases

---

doc/libpmem2/pmem2_badblock_next.3.md
src/libpmem2/badblocks_ndctl.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4809)

pmem2: two small bad block fixes

---

src/test/Makefile.inc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4810)

test: always clobber static-(non)debug targets and __pycache__ from tests

---

doc/Makefile
doc/libpmemobj/pmemobj_tx_get_failure_behavior.3
doc/libpmemobj/pmemobj_tx_set_failure_behavior.3

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4817)

doc: add missing '.3' files to the libpmemobj documentation

---

.github/workflows/gha.yml
appveyor.yml
src/test/RUNTESTS.py
src/test/testconfig.py.example
src/test/unittest/requirements.py
utils/docker/configure-tests.sh
utils/docker/images/Dockerfile.fedora-31
utils/docker/images/Dockerfile.ubuntu-19.10

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4803)

test: add enable_admin_tests and require_admin() to Python test framework

---

src/test/pmem2_api/Makefile
src/test/pmem2_api/pmem2_api.c
src/test/pmem2_integration/Makefile
src/test/pmem2_integration/pmem2_integration.c
src/test/pmem2_integration/pmem2_integration.vcxproj
src/test/pmem2_integration/pmem2_integration.vcxproj.filters
src/test/pmem2_map/Makefile
src/test/pmem2_map/TESTS.py
src/test/pmem2_map/pmem2_map.c
src/test/pmem2_map/pmem2_map.vcxproj
src/test/pmem2_map/pmem2_map.vcxproj.filters
src/test/unittest/ut_pmem2_setup.c
src/test/unittest/ut_pmem2_setup.h
src/test/unittest/ut_pmem2_setup_integration.c
src/test/unittest/ut_pmem2_setup_integration.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4795)

test: separate prepare_config function to test utils

---

src/libpmem2/region_namespace_ndctl.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4822)

pmem2: get reg id fix memory leak

---

doc/Makefile
doc/libpmem2/.gitignore
doc/libpmem2/pmem2_deep_flush.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4697)

doc: add pmem2 deep flush man

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4699)

doc: add deep flush to gh pages

---

src/test/obj_basic_integration/obj_basic_integration.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4830)

test: fix arg check in obj_basic_integration

---

src/test/obj_fragmentation2/obj_fragmentation2.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4832)

test: fix implicit conversion warning in obj_fragmentation2

---

src/test/unittest/configurator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4816)

test: (py) simplify _str2list

---

src/test/pmem2_map_prot/Makefile
src/test/pmem2_map_prot/TESTS.py
src/test/pmem2_map_prot/pmem2_map_prot.c
src/test/pmem2_map_prot/pmem2_map_prot.vcxproj
src/test/pmem2_map_prot/pmem2_map_prot.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4755)

test: tests for pmem2_map with exec protection flag

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4829)

doc: add pmem2_source_from_anon to gh-pages

---

src/libpmem2/deep_flush.h
src/libpmem2/deep_flush_linux.c
src/libpmem2/deep_flush_other.c
src/libpmem2/deep_flush_windows.c
src/libpmem2/persist.c
src/test/pmem2_deep_flush/pmem2_deep_flush.c

Waiting for #4790 (ftype from map)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4820)

pmem2: deep flush range instead of Pagesize

---

src/common/file_posix.c
src/common/shutdown_state.c
src/libpmem2/badblocks_ndctl.c
src/libpmem2/deep_flush_linux.c
src/libpmem2/region_namespace.h
src/libpmem2/region_namespace_ndctl.c
src/libpmem2/region_namespace_ndctl.h
src/libpmem2/region_namespace_none.c
src/libpmem2/source.h
src/libpmem2/source_posix.c
src/libpmem2/usc_ndctl.c
src/test/pmem2_badblock_mocks/mocks_pmem2.c
src/test/pmem2_deep_flush/pmem2_deep_flush.c
src/test/tools/usc_permission_check/usc_permission_check.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4838)

pmem2: Unsafe Shutdown Count fixes

---

src/libpmem2/usc_ndctl.c

On some systems interleave set is not available
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4841)

pmem2: read usc from region instead of interleave set

---

src/libpmem2/deep_flush_linux.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4845)

pmem2: fix deep flush ret value

---

src/libpmem2/pmem2_utils.h

Otherwise, yell and return -EINVAL.
Per @marcinslusarz's idea.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4781)

check that errno is set for PMEM2_E_ERRNO

---

.cirrus.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4849)

common: fix freebsd CI

---

src/common/file_posix.c
src/libpmem2/region_namespace_ndctl.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4853)

pmem2: fix get alignment funcs

---

src/examples/libpmem2/map_multiple_files/.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4855)

examples: add gitignore to multiple map example

---

src/libpmemobj/heap.c
src/test/obj_ctl_stats/obj_ctl_stats.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4848)

obj: fix run allocated recalculation

---

doc/libpmem/pmem_is_pmem.3.md
doc/libpmemblk/pmemblk_create.3.md
doc/libpmemlog/pmemlog_create.3.md
doc/libpmemobj/pmemobj_open.3.md
src/core/os_windows.c
src/test/libpmempool_bttdev/TEST11.PS1
src/test/libpmempool_bttdev/TEST3.PS1
src/test/libpmempool_bttdev/TEST4.PS1
src/test/libpmempool_bttdev/TEST5.PS1
src/test/libpmempool_bttdev/TEST6.PS1
src/test/obj_pool/TEST35.PS1
src/test/tools/sparsefile/sparsefile.c
src/test/tools/sparsefile/sparsefile.vcxproj
src/test/unittest/unittest.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4831)

common: improve performance of os_posix_fallocate on windows

---

src/libpmem2/pmem2_utils.h
src/libpmem2/pmem2_utils_linux.c
src/libpmem2/pmem2_utils_ndctl.c
src/libpmem2/pmem2_utils_none.c
src/libpmem2/pmem2_utils_other.c
src/libpmem2/source_posix.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4850)

pmem2: ndctl get size

---

src/test/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4754)

clean away __pycache__ dirs

---

src/libpmem/ppc64/platform_generic.c

current version of Valgrind doesn't recognize ppc fence instruction
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4859)

pmem: (PPC) call msync instead flush on valgrind

---

src/examples/libpmem2/redo/redo.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4854)

examples: fix pmem2 redo example fd leak

---

src/test/pmem2_map_prot/TESTS.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4862)

test: disable pmem2_map_prot devdax exec test

---

doc/Makefile
doc/libpmem2/.gitignore
doc/libpmem2/libpmem2_unsafe_shutdown.7.md
doc/libpmem2/pmem2_source_device_id.3.md
doc/libpmem2/pmem2_source_device_usc.3.md

This is a continuation of  #4653
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4840)

doc: pmem2 unsafe shutdown count

---

src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4869)

test: skip devdax tests when ndctl is unavailable (sh)

---

utils/docker/valid-branches.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4870)

common: update valid-branches script (new 1.9)

---

doc/libpmem/pmem_is_pmem.3.md
doc/libpmemblk/pmemblk_create.3.md
doc/libpmemlog/pmemlog_create.3.md
doc/libpmemobj/pmemobj_open.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4865)

doc: fix a quote symbol in manpages

---

src/test/unittest/devdax.py
src/test/unittest/requirements.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4868)

test: skip devdax tests when ndctl is unavailable (py)

---

doc/libpmem2/pmem2_map.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4878)

doc: fix a typo in pmem2_map doc

---

src/test/Makefile
src/test/testframework.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4884)

test: disable bytecode on module import (py)

---

src/test/unittest/tools.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4882)

test: add support for ndctl list v63

---

src/test/pmem2_integration/TESTS.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4867)

test: enable dd tests for deep flush

---

doc/libpmem2/libpmem2_unsafe_shutdown.7.md
doc/libpmem2/pmem2_badblock_context_new.3.md
doc/libpmem2/pmem2_config_clear_address.3.md
doc/libpmem2/pmem2_config_new.3.md
doc/libpmem2/pmem2_map.3.md
doc/libpmem2/pmem2_source_device_id.3.md
doc/libpmem2/pmem2_source_from_fd.3.md
doc/libpmem2/pmem2_unmap.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4898)

doc: correct the manpages

---

utils/docker/build-CI.sh
utils/docker/build-local.sh
utils/docker/images/build-image.sh
utils/docker/images/push-image.sh
utils/docker/pull-or-rebuild-image.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4900)

common: bump tag version of docker images

---

utils/docker/images/0001-fix-generating-gcov-files-and-turn-off-verbose-log.patch
utils/docker/images/Dockerfile.ubuntu-19.10
utils/docker/images/download-scripts.sh
utils/docker/run-coverage.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4899)

common: fix gcov

---

src/libpmem2/badblocks_ndctl.c

Description of problem in #4907
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4908)

common: add header for FALLOC_FL_PUNCH_HOLE

---

index.md
libpmem2/index.md

Preview: http://wlemkows.github.io/pmdk/libpmem2/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4903)

doc: add libpmem2 index md with example (gh-pages)

---

src/test/RUNTESTS.py
src/test/testframework.py
src/test/unittest/basetest.py
src/test/unittest/configurator.py
src/test/unittest/context.py
src/test/unittest/ctx_filter.py
src/test/unittest/devdax.py
src/test/unittest/futils.py
src/test/unittest/granularity.py
src/test/unittest/test_types.py
src/test/unittest/tools.py
src/test/unittest/utils.py
src/test/unittest/valgrind.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4892)

test: document test framework 

---

src/test/pmem2_integration/pmem2_integration.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4915)

test: update unmap to delete

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4916)

doc: add libpmem2 functions (gh-pages)

---

doc/libpmem2/libpmem2.7.md
src/examples/libpmem2/basic/basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4913)

doc: libpmem2.7 man update

---

doc/libpmem2/pmem2_badblock_clear.3.md
doc/libpmem2/pmem2_badblock_context_new.3.md
doc/libpmem2/pmem2_config_new.3.md
doc/libpmem2/pmem2_config_set_address.3.md
doc/libpmem2/pmem2_config_set_offset.3.md
doc/libpmem2/pmem2_config_set_protection.3.md
doc/libpmem2/pmem2_config_set_required_store_granularity.3.md
doc/libpmem2/pmem2_config_set_sharing.3.md
doc/libpmem2/pmem2_config_set_vm_reservation.3.md
doc/libpmem2/pmem2_deep_flush.3.md
doc/libpmem2/pmem2_get_drain_fn.3.md
doc/libpmem2/pmem2_get_flush_fn.3.md
doc/libpmem2/pmem2_get_persist_fn.3.md
doc/libpmem2/pmem2_map_delete.3.md
doc/libpmem2/pmem2_map_get_store_granularity.3.md
doc/libpmem2/pmem2_map_new.3.md
doc/libpmem2/pmem2_source_alignment.3.md
doc/libpmem2/pmem2_source_device_id.3.md
doc/libpmem2/pmem2_source_device_usc.3.md
doc/libpmem2/pmem2_source_from_anon.3.md
doc/libpmem2/pmem2_source_from_fd.3.md
doc/libpmem2/pmem2_source_size.3.md
doc/libpmem2/pmem2_vm_reservation_new.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4910)

doc: align error section

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4922)

doc: fix typo in the releases list (gh-pages)

---

src/test/RUNTESTS.py
src/test/pmem2_map/pmem2_map.c
src/test/pmem2_map_prot/pmem2_map_prot.c
src/test/pmem2_mem_ext/TESTS.py
src/test/unittest/basetest.py
src/test/unittest/builds.py
src/test/unittest/consts.py
src/test/unittest/context.py
src/test/unittest/futils.py
src/test/unittest/poolset.py
src/test/unittest/utils.py
src/test/unittest/valgrind.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4921)

test: set libraries debug logs envs (py)

---

src/test/pmem2_config/pmem2_config.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4935)

pmem2: fix config test typo

---

src/test/tools/usc_permission_check/usc_permission_check.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4933)

test: fix usc permission check tool

---

src/examples/libpmemobj/map/data_store.c

Takes the inserts to the untransactional APIs out of the TX_BEGIN, TX_END transaction block.
Closes https://github.com/pmem/pmdk/issues/4923
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4939)

obj: fix data_store example transaction logic

---

src/libpmem2/usc_none.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4952)

pmem2: add errormsg in usc none

---

doc/Makefile

Ref: #4960
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4961)

doc: update doc Makefile

---

src/test/obj_persist_count/out2.log.match

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4967)

test: Fix obj_persist_count/TEST2 for ppc64le

---

src/test/pmempool_feature/common.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4966)

test: fix fail on return pmempool_feature

---

src/test/obj_persist_count/out3.log.match

Ref: #4962
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4964)

test: update persist count for ppc (drain after ulog processing)

---

src/test/obj_defrag_advanced/TESTS.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4971)

test: change obj_defrag_advanced TEST3 type to long

---

doc/libpmem2/.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4974)

doc: add missing libpmem2 functions in gitignore

---

src/test/ex_libpmem2/out5.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4979)

test: fix pmem2 example without libndctl

---

src/test/pmempool_feature/common.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4995)

test: fix sds support check in pmempool_feature

---

doc/libpmem2/libpmem2.7.md
doc/libpmem2/pmem2_config_new.3.md
doc/libpmem2/pmem2_config_set_length.3.md
doc/libpmem2/pmem2_config_set_offset.3.md
doc/libpmem2/pmem2_deep_flush.3.md
doc/libpmem2/pmem2_vm_reservation_new.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4973)

doc: tiny man page fixes

---

ChangeLog
README.md
src/libpmempool/check_sds.c
src/test/pmempool_check/TEST1.PS1
src/test/pmempool_check/TEST9.PS1
src/test/pmempool_feature/common.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4997)

Merge stable-1.9 into master 

---

src/libpmem2/map_posix.c
src/libpmem2/map_windows.c
src/libpmem2/vm_reservation.c
src/libpmem2/vm_reservation.h
src/libpmem2/vm_reservation_windows.c
src/test/pmem2_vm_reservation/TESTS.py
src/test/pmem2_vm_reservation/pmem2_vm_reservation.c

This change depends on the previous PR https://github.com/pmem/pmdk/pull/4965.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4994)

pmem2: move reservation struct to vm_reservation.c

---

README.md

preview:
https://github.com/lukaszstolarczuk/pmdk/tree/add-repology-badge#pmdk-persistent-memory-development-kit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4999)

common: add repology badge to README

---

src/test/README
src/test/unittest/basetest.py
src/test/unittest/unittest.ps1
src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5001)

test: store logs in separate folders

---

src/test/README
src/test/unittest/basetest.py
src/test/unittest/unittest.ps1
src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5002)

test: store logs in separate folders (1.8)

---

src/test/README
src/test/unittest/basetest.py
src/test/unittest/unittest.ps1
src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5003)

test: store logs in separate folders (1.7)

---

index.md

Need to upgrade in the pmem/rpma
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5000)

doc: gh-pages: add rpma man page

---

index.md

Fix description of librpma:
- fix broken link
- break too long lines
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5008)

doc: fix description of librpma

---

.github/workflows/coverity.yml
.github/workflows/gha.yml
.travis.yml
utils/docker/README
utils/docker/build-CI.sh
utils/docker/build-local.sh
utils/docker/images/build-image.sh
utils/docker/images/push-image.sh
utils/docker/pull-or-rebuild-image.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5009)

common: migrate from Docker Hub to GitHub Container Registry

---

.github/workflows/coverity.yml
.github/workflows/gha.yml
.travis.yml
utils/docker/README
utils/docker/build-CI.sh
utils/docker/build-local.sh
utils/docker/images/build-image.sh
utils/docker/images/push-image.sh
utils/docker/pull-or-rebuild-image.sh

Reverts pmem/pmdk#5009
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5013)

Revert "common: migrate from Docker Hub to GitHub Container Registry"

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4955)

doc: add pmem2_map_from_existing

---

doc/RELEASE_STEPS.md
utils/docker/build-CI.sh
utils/docker/build-local.sh
utils/docker/images/build-image.sh
utils/docker/images/push-image.sh
utils/docker/images/set-images-version.sh
utils/docker/pull-or-rebuild-image.sh
utils/docker/set-ci-vars.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5019)

common: set common variable with version of Docker images

---

utils/docker/set-ci-vars.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5021)

common: fix bash include path

---

_data/releases_linux.yml
_data/releases_windows.yml
index.md
libpmemset/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4991)

doc: add libpmemset to pmem.io (gh-pages)

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5022)

common: add pandoc to dependencies

---

.github/workflows/coverity.yml
.github/workflows/gha.yml
.travis.yml
utils/docker/README
utils/docker/build-CI.sh
utils/docker/build-local.sh
utils/docker/images/build-image.sh
utils/docker/images/push-image.sh
utils/docker/pull-or-rebuild-image.sh

it reverts commit from #5013 and adds few fixes for GHCR to work (and some minor cleanups).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5023)

common: enable GH Container Registry after all

---

Makefile
src/Makefile
utils/build-dpkg.sh
utils/build-rpm.sh
utils/libpmemset.pc.in
utils/pmdk.spec.in

Depends on https://github.com/pmem/pmdk/pull/5004.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5012)

set: add rpm and dpkg package build

---

doc/libpmemset/pmemset_config_new.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5035)

doc: update section list in config_new manpage

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5036)

doc: update libpmemset funcs releases list

---

utils/docker/README

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5041)

common: fix one typo in utils/docker/README

---

doc/libpmem2/libpmem2.7.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5044)

doc: remove exprimental moniker from libpmem2(7)

---

README.md
doc/README
src/include/README

preview: https://github.com/lukaszstolarczuk/pmdk/tree/update-readme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5057)

common: update README's

---

src/test/Makefile.inc
src/test/pmem2_config/Makefile
src/test/pmem2_config/pmem2_config.c
src/test/pmem2_map_from_existing/Makefile
src/test/pmem2_perror/Makefile
src/test/pmem2_perror/pmem2_perror.c
src/test/pmem2_source/Makefile
src/test/pmem2_source/pmem2_source.c
src/test/pmem2_source_alignment/Makefile
src/test/pmem2_source_alignment/pmem2_source_alignment.c
src/test/pmem2_source_size/Makefile
src/test/pmem2_source_size/pmem2_source_size.c
src/test/pmemset_config/Makefile
src/test/pmemset_new/Makefile
src/test/pmemset_part/Makefile
src/test/pmemset_perror/Makefile
src/test/pmemset_source/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5065)

test: fix test makefiles

---

doc/Makefile
doc/libpmemset/.gitignore
doc/libpmemset/pmemset_source_delete.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5068)

doc: add pmemset_source_delete manpage

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5078)

doc: update releases list

---

src/test/pmem2_source_numa/TESTS.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5079)

test: add require ndctl to numa tests

---

index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5085)

doc: fix link to libpmemset

---

.github/workflows/coverity.yml
.github/workflows/gha.yml
.travis.yml
utils/docker/images/Dockerfile.ubuntu-20.04

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5082)

common: upgrade Ubuntu docker image to 20.04 LTS

---

src/test/drd-log.supp

Closes: #5084
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5086)

test: Update valgrind suppressions for ppc64le Ubuntu 20.04

---

src/test/pmem2_map_prot/TESTS.py
src/test/tools/Makefile
src/test/tools/mapexec/.gitignore
src/test/tools/mapexec/Makefile
src/test/tools/mapexec/README
src/test/tools/mapexec/mapexec.c
src/test/unittest/devdax.py
src/test/unittest/tools.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/4864)

test: Skip DevDax test if mmap exec is not allowed

---

utils/get_aliases.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5090)

doc: update get_aliases.sh (libpmemset)

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5091)

set: pmemset_part_map pages update

---

_data/libs_map.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5099)

doc: update libs_map.yml (and fix indentation)

---

doc/Makefile
doc/libpmemset/.gitignore
doc/libpmemset/pmemset_config_set_required_store_granularity.3.md
doc/libpmemset/pmemset_get_store_granularity.3.md
src/include/libpmemset.h
src/libpmemset/config.c
src/libpmemset/config.h
src/libpmemset/libpmemset.def
src/libpmemset/libpmemset.link.in
src/libpmemset/part.c
src/libpmemset/part.h
src/libpmemset/pmemset.c
src/test/pmemset_part/TESTS.py
src/test/pmemset_part/pmemset_part.c
src/test/scope/out16.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5076)

set: granularity support in the part map

---

utils/get_aliases.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5101)

doc: fix typo in get_aliases.sh

---

src/libpmemset/config.c
src/libpmemset/config.h
src/libpmemset/pmemset.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5102)

set: fix granularity enum value assignment

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5104)

doc: update releases lists

---

.travis.yml
utils/docker/arm64.blacklist
utils/docker/build-CI.sh
utils/docker/images/install-valgrind.sh

Change-Id: I8c98a4eb4691c7beac419f7be56c455772b51c71
Signed-off-by: Jun He <jun.he@arm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5107)

common: add arm64 to travis ci matrix

---

doc/Makefile

Solves https://github.com/pmem/pmdk/issues/5105.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5109)

doc: fix pmemset manpage Makefile

---

doc/Makefile
doc/libpmemset/.gitignore
doc/libpmemset/pmemset_part_map_drop.3.md
src/core/ravl_interval.c
src/core/ravl_interval.h
src/include/libpmemset.h
src/libpmemset/part.c
src/libpmemset/part.h
src/libpmemset/pmemset.c
src/libpmemset/pmemset.h
src/test/pmemset_part/TESTS.py
src/test/pmemset_part/pmemset_part.c

Depends on https://github.com/pmem/pmdk/pull/5075, https://github.com/pmem/pmdk/pull/5076 and https://github.com/pmem/pmdk/pull/5051.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5080)

set: add multiple parts support

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5113)

doc: add pmemset_part_map_drop to the pages

---

doc/Makefile

Solves https://github.com/pmem/pmdk/issues/5116.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5120)

doc: fix manpage duplicate in Makefile

---

src/libpmemset/pmemset.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5119)

set: fix iteration functions null dereference

---

doc/Makefile
doc/libpmemset/.gitignore
doc/libpmemset/pmemset_part_map_by_address.3.md
doc/libpmemset/pmemset_part_map_drop.3.md
src/include/libpmemset.h
src/libpmemset/part.c
src/libpmemset/part.h
src/libpmemset/pmemset.c
src/test/pmemset_part/TESTS.py
src/test/pmemset_part/pmemset_part.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5106)

set: get part map by addr

---

src/test/pmem2_map/pmem2_map.c
src/test/pmempool_sync/out6.log.match
src/test/pmempool_sync/out7.log.match
src/test/pmempool_transform/out7.log.match
src/test/pmempool_transform/out8.log.match

Solve issue #5112 and some other related issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5118)

Fix DAX tests for ppc64le

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5125)

doc: add pmem2_vm_reservation_extend to the pages

---

libpmem2/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5135)

[gh-pages] misspells and small fixes in libpmem2 description

---

doc/libpmem2/pmem2_deep_flush.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5142)

doc: update pmem2_deep_flush man

---

.cirrus.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5148)

common: upgrade freebsd CI to 12.2

---

.codecov.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5151)

common: reduce codecov sensitivity

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5140)

doc: update pmem2 and pmemset pages

---

doc/libpmem2/.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5159)

doc: update libpmem2 .gitignore

---

.cirrus.yml
.codecov.yml
src/common/mmap.h
src/common/os_posix.c
src/common/pool_hdr.h
src/common/uuid.c
src/common/valgrind/valgrind.h
src/librpmem/rpmem_fip.c
src/test/obj_defrag_advanced/obj_defrag_advanced.c
src/test/unittest/futils.py
src/test/unittest/utils.py
src/tools/pmempool/rm.c
utils/docker/run-build-package.sh
utils/pmdk.spec.in

We merged this patch only for master, so I did PR fo1.8 manually. @pbalcer  Should I do the same for 1.9 and 1.10?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5160)

common: backport master fixes [stable-1.8]

---

.cirrus.yml
.codecov.yml
src/common/mmap.h
src/common/pool_hdr.h
src/common/uuid.c
src/core/os_posix.c
src/core/valgrind/valgrind.h
src/libpmem2/badblocks_ndctl.c
src/librpmem/rpmem_fip.c
src/test/RUNTESTS.py
src/test/obj_defrag_advanced/obj_defrag_advanced.c
src/test/obj_pool/TEST35.PS1
src/test/pmem2_api/TESTS.py
src/test/pmem2_integration/TESTS.py
src/test/pmem2_integration/pmem2_integration.c
src/test/pmem2_mem_ext/TESTS.py
src/test/unittest/futils.py
src/test/unittest/tools.py
src/test/unittest/utils.py
src/tools/pmempool/rm.c
utils/docker/run-build-package.sh
utils/pmdk.spec.in

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5162)

common: backport master fixes [stable-1.9] 

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5167)

doc: add mem[set|move|cpy] to releases list

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5166)

doc: update gh-pages releases

---

doc/libpmemset/pmemset_memcpy.3
doc/libpmemset/pmemset_memset.3

This should fix rpm build issues
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5170)

doc: add missing .so aliases

---

src/libpmemobj/heap.c

libpmemobj was silently ignoring pthread key creation
failures, which led to allocation failures when arenas
weren't being properly found for threads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5169)

obj: add error checking for key creation

---

doc/Makefile
doc/libpmem2/pmem2_vm_reservation_map_find.3.md
doc/libpmemset/.gitignore
doc/libpmemset/pmemset_part_map.3.md
doc/libpmemset/pmemset_remove_part_map.3.md
doc/libpmemset/pmemset_set_contiguous_part_coalescing.3.md
src/include/libpmemset.h
src/libpmem2/vm_reservation.c
src/libpmemset/part.c
src/libpmemset/part.h
src/libpmemset/pmemset.c
src/test/pmemset_part/TESTS.py
src/test/pmemset_part/pmemset_part.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5133)

set: add pmemset_remove_part_map function

---

src/common/file.h
src/common/file_posix.c
src/common/file_windows.c
src/core/util.h
src/core/util_posix.c
src/core/util_windows.c
src/include/libpmemset.h
src/libpmemset/source.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5177)

common: move tmpfile to core and minor changes

---

.github/workflows/gha.yml
utils/docker/build-CI.sh
utils/docker/build-local.sh

The main intention of this PR is to detect man errors like 5154 or 5116 earlier.
I extend the utils layer but I am not sure what is the best approach regarding matrix configuration(after changes from this PR the number of jobs is equal to 14 (https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration)
Current status:
https://github.com/michalbiesek/pmdk/actions/runs/617761895
Status before #5170:
https://github.com/michalbiesek/pmdk/actions/runs/616841482
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5174)

[RFC] common: use PMEMSET_INSTALL in GHA jobs

---

src/libpmemset/source.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5182)

set: quick fix for coverity issue in source file

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5184)

set: updated lists with xsource_from_file

---

.github/workflows/gha.yml

Purpose of this PR is to include "experimental" code in scope of codecov analysis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5196)

common: added experimental flag for for coverage job-run

---

doc/libpmemset/pmemset_part_map.3.md
doc/libpmemset/pmemset_source_from_file.3.md
doc/libpmemset/pmemset_source_from_temporary.3.md
src/include/libpmemset.h
src/libpmemset/file.c
src/libpmemset/source.c
src/test/pmemset_part/TESTS.py
src/test/pmemset_part/pmemset_part.c
src/test/pmemset_source/TESTS.py
src/test/pmemset_source/err12.log.match
src/test/pmemset_source/out12.log.match
src/test/pmemset_source/pmemset_source.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5191)

set: xsource truncate flag

---

.github/workflows/gha.yml
utils/docker/run-coverage.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5201)

common: keep going coverage py tests

---

src/test/obj_lane/obj_lane.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5208)

test: remove manual ctor/dtor call in obj_lane

---

doc/Makefile
doc/libpmemset/.gitignore
doc/libpmemset/pmemset_part_map.3.md
doc/libpmemset/pmemset_remove_part_map.3.md
doc/libpmemset/pmemset_remove_range.3.md
src/include/libpmemset.h
src/libpmem2/vm_reservation.c
src/libpmemset/part.c
src/libpmemset/part.h
src/libpmemset/pmemset.c
src/test/pmemset_part/TESTS.py
src/test/pmemset_part/pmemset_part.c

In accordance with the discussed changes it replaces https://github.com/pmem/pmdk/pull/5175.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5185)

set: add pmemset_remove_range function

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5186)

doc: add pmemset_remove_range to gh pages

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5223)

doc: add pmemset_config_set_event_callback manpage

---

doc/libpmemobj/pmemobj_ctl_get.3.md
src/include/libpmemobj/ctl.h
src/libpmemobj/heap.c
src/libpmemobj/heap.h
src/libpmemobj/obj.c
src/libpmemobj/pmalloc.c
src/libpmemobj/pmalloc.h
src/test/obj_ctl_arenas/TEST7
src/test/obj_ctl_arenas/TEST7.PS1
src/test/obj_ctl_arenas/TEST8
src/test/obj_ctl_arenas/TEST8.PS1
src/test/obj_ctl_arenas/TEST9
src/test/obj_ctl_arenas/TEST9.PS1
src/test/obj_ctl_arenas/obj_ctl_arenas.c

Ref: #5172
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5210)

obj: add thread arena assignment CTL

---

src/examples/libpmem2/unsafe_shutdown/unsafe_shutdown.c
src/tools/pmempool/common.c
src/tools/rpmemd/rpmemd_fip.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5228)

fix various small issues found by static analysis (klocwork) - stable 1.10

---

src/examples/libpmem2/ringbuf/ringbuf.c
src/examples/libpmem2/unsafe_shutdown/unsafe_shutdown.c
src/libpmemset/pmemset.c
src/tools/pmempool/common.c
src/tools/rpmemd/rpmemd_fip.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5227)

fix various small issues found by static analysis (klocwork)

---

doc/Makefile
doc/libpmem2/pmem2_vm_reservation_new.3.md
doc/libpmemset/.gitignore
doc/libpmemset/pmemset_config_set_reservation.3.md
doc/libpmemset/pmemset_part_map.3.md
src/core/ravl_interval.c
src/include/libpmemset.h
src/libpmemset/config.c
src/libpmemset/config.h
src/libpmemset/pmemset.c
src/test/pmemset_part/TESTS.py
src/test/pmemset_part/pmemset_part.c

Depends on https://github.com/pmem/pmdk/pull/5214.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5222)

set: add config set vm reservation

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5234)

doc: add vm reservation iterators to gh-pages

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5231)

doc: add config set reservation to gh-pages

---

ChangeLog

`to` → `no`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5249)

common: fix a meaning-changing typo in the changelog

---

src/libpmemset/pmemset.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5239)

set: fix virtual reservation leak

---

src/Makefile.inc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5252)

common: add disable lto to cflags

---

doc/libpmemset/pmemset_config_set_event_callback.3.md
doc/libpmemset/pmemset_part_map.3.md
src/include/libpmemset.h
src/libpmemset/config.c
src/libpmemset/pmemset.c
src/test/pmemset_config/pmemset_config.c
src/test/pmemset_part/TESTS.py
src/test/pmemset_part/pmemset_part.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5235)

set: add part_add event

---

README.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5261)

common: Update readme with PowerPC port section

---

_data/releases_linux.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5267)

doc: fix version typo in manpage list

---

utils/docker/images/set-images-version.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5268)

common: bump docker images version

---

doc/libpmemset/pmemset_config_set_event_callback.3.md
doc/libpmemset/pmemset_remove_part_map.3.md
src/include/libpmemset.h
src/libpmemset/part.c
src/libpmemset/part.h
src/libpmemset/pmemset.c
src/test/pmemset_event/TESTS.py
src/test/pmemset_event/pmemset_event.c
src/test/pmemset_part/TESTS.py
src/test/pmemset_part/pmemset_part.c

Depends on https://github.com/pmem/pmdk/pull/5235 and https://github.com/pmem/pmdk/pull/5239.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5250)

set: add remove range event

---

src/core/util.c
src/core/util.h
src/examples/libpmemobj/libart/arttree_examine.c
src/examples/libpmemobj/libart/arttree_search.c
src/examples/libpmemobj/libart/arttree_structures.c
src/examples/libpmemobj/map/kv_server.c
src/examples/libpmemobj/pi.c
src/examples/libpmemobj/pminvaders/pminvaders.c
src/libpmemobj/ulog.c
src/libpmempool/check_sds.c
src/libpmempool/check_util.c
src/libpmempool/feature.c
src/librpmem/rpmem_util.c
src/test/util_badblock/util_badblock.c
src/tools/pmempool/output.c

These are all minor issues.
There's one bug left: passing cache size as an int, despite it being possibly as big as 8GB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5281)

lgtm warnings

---

README.md

// preview: https://github.com/lukaszstolarczuk/pmdk/tree/add-lgtm.com-badge#pmdk-persistent-memory-development-kit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5283)

common: add LGTM.com badge to the top-level README

---

utils/docker/images/install-valgrind.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5284)

common: update pmem valgrind in images to 3.17

---

src/examples/libpmemobj/hashmap/hashmap_atomic.c
src/examples/libpmemobj/map/map_btree.c
src/examples/libpmemobj/map/map_ctree.c
src/examples/libpmemobj/map/map_rbtree.c
src/examples/libpmemobj/map/map_rtree.c
src/examples/libpmemobj/map/map_skiplist.c
src/examples/libpmemobj/map/mapcli.c
src/test/ex_libpmemobj/TESTS.py
src/test/unittest/context.py
src/test/unittest/futils.py
src/test/unittest/python_gdb.py
src/test/unittest/requirements.py
utils/docker/build-CI.sh
utils/docker/build-local.sh

Ref: pmem/issues#5220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5273)

examples: add manual recovery and fix bug with creating maps

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5276)

doc: add sds feature to gh-pages

---

src/common/uuid.c
src/core/util.h
src/libpmem2/x86_64/memcpy/memcpy_nt_avx.c
src/libpmem2/x86_64/memcpy/memcpy_nt_avx512f.c
src/libpmem2/x86_64/memcpy/memcpy_nt_sse2.c
src/libpmem2/x86_64/memset/memset_nt_avx.c
src/libpmem2/x86_64/memset/memset_nt_avx512f.c
src/libpmem2/x86_64/memset/memset_nt_sse2.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5295)

merging stable-1.9 into stable-1.10

---

src/common/uuid.c
src/core/util.h
src/libpmem2/x86_64/memcpy/memcpy_nt_avx.c
src/libpmem2/x86_64/memcpy/memcpy_nt_avx512f.c
src/libpmem2/x86_64/memcpy/memcpy_nt_sse2.c
src/libpmem2/x86_64/memset/memset_nt_avx.c
src/libpmem2/x86_64/memset/memset_nt_avx512f.c
src/libpmem2/x86_64/memset/memset_nt_sse2.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5297)

merge stable-1.11 into master

---

src/libpmemobj/memblock.c
src/test/util_badblock/util_badblock.c

Reported-by: Hamed Gorjiara <hgorjiar@uci.edu>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5298)

obj: use explicit atomics for metadata stores

---

CODING_STYLE.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5302)

doc: add set as valid area name

---

src/test/pmemset_sds/pmemset_sds.vcxproj
src/test/pmemset_sds/pmemset_sds.vcxproj.filters

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5316)

set: fix missing error message in a test

---

src/test/rpmemd_db/rpmemd_db_test.c

Backport from 1.11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5313)

test: fix types in rpmemd_db_test [stable-1.9]

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5311)

doc: add mcsafe read/write to gh-pages

---

src/include/libpmemset.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5317)

set: sort libpmemset.h

---

src/libpmemobj/heap.c
src/libpmemobj/heap.h
src/libpmemobj/pmalloc.c

I forgot to commit my changes in the previous PR...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5286)

obj: fix missing recycler NULL checks

---

doc/libpmemset/pmemset_map.3.md
doc/libpmemset/pmemset_map_config_new.3.md
src/include/libpmemset.h
src/libpmemset/map_config.c
src/libpmemset/map_config.h
src/libpmemset/pmemset.c
src/test/pmemset_deep_flush/pmemset_deep_flush.c
src/test/pmemset_event/pmemset_event.c
src/test/pmemset_map_config/pmemset_map_config.c
src/test/pmemset_memcpy/pmemset_memcpy.c
src/test/pmemset_memmove/pmemset_memmove.c
src/test/pmemset_memset/pmemset_memset.c
src/test/pmemset_part/pmemset_part.c
src/test/pmemset_persist/pmemset_persist.c
src/test/pmemset_sds/pmemset_sds.c
src/test/unittest/ut_pmemset_utils.c
src/test/unittest/ut_pmemset_utils.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5327)

set: set opt map_cfg and mv set to pmemset_map

---

src/tools/pmreorder/consistencycheckwrap.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5330)

pmreorder: fix repeated import

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5332)

doc: update gh-pages releases lists

---

doc/libpmem2/pmem2_source_pread_mcsafe.3.md
src/libpmem2/mcsafe_ops_posix.c
src/libpmem2/mcsafe_ops_windows.c
src/test/pmem2_badblock/TESTS.py
src/test/pmem2_badblock/pmem2_badblock.c
src/test/pmem2_source/TESTS.py
src/test/pmem2_source/pmem2_source.c
src/test/pmem2_source/pmem2_source.vcxproj
src/test/pmem2_source/pmem2_source.vcxproj.filters

Depends on https://github.com/pmem/pmdk/pull/5289.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5294)

pmem2: add devdax support for mcsafe read/write source ops

---

doc/Makefile
doc/libpmemset/.gitignore
doc/libpmemset/pmemset_source_pread_mcsafe.3.md
doc/libpmemset/pmemset_source_pwrite_mcsafe.3
src/include/libpmemset.h
src/libpmemset/source.c
src/test/Makefile
src/test/pmem2_badblock/pmem2_badblock.c
src/test/pmemset_badblock/.gitignore
src/test/pmemset_badblock/Makefile
src/test/pmemset_badblock/TESTS.py
src/test/pmemset_badblock/pmemset_badblock.c
src/test/pmemset_source/TESTS.py
src/test/pmemset_source/pmemset_source.c

Depends on https://github.com/pmem/pmdk/pull/5294.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5307)

set: add machine safe read/write source operations

---

_data/releases_linux.yml
_data/releases_windows.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5338)

doc: add set mcsafe ops + fix to pmem2 doc

---

doc/libpmem2/libpmem2.7.md
doc/libpmem2/libpmem2_unsafe_shutdown.7.md
doc/libpmem2/pmem2_map_from_existing.3.md
doc/libpmem2/pmem2_map_new.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5341)

doc: fix typos in libpmem2 manpages

---

doc/libpmemset/pmemset_persist.3.md
src/examples/libpmemset/basic/basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5355)

examples: fix always 0 ret value in the libpmemset basic

---

index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5359)

doc: move librpma before librpmem [gh-pages]

---

src/examples/libpmemobj/pminvaders/pminvaders.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5358)

examples: remove unnecessary persists in pminvaders

---

doc/libpmem2/pmem2_vm_reservation_new.3.md
src/libpmem2/vm_reservation.c
src/libpmem2/vm_reservation.h
src/libpmem2/vm_reservation_posix.c
src/libpmem2/vm_reservation_windows.c
src/test/pmem2_vm_reservation/pmem2_vm_reservation.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5343)

pmem2: add addr alignment prediction to vm reservation

---

utils/docker/configure-tests.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5362)

utils: fix random error during GH actions tests.

---

src/test/pmemset_part/TESTS.py
src/test/pmemset_part/pmemset_part.c

Includes https://github.com/pmem/pmdk/pull/5343.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5344)

set: add devdax tests to pmemset_part

---

src/test/unittest/tools.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5367)

test: change pmem provider string

---

doc/pmreorder/pmreorder.1.md
src/test/pmreorder_simple/pmreorder0.log.match
src/test/pmreorder_simple/pmreorder3.log.match
src/test/pmreorder_stack/pmreorder0.log.match
src/tools/pmreorder/binaryoutputhandler.py
src/tools/pmreorder/consistencycheckwrap.py
src/tools/pmreorder/loggingfacility.py
src/tools/pmreorder/markerparser.py
src/tools/pmreorder/memoryoperations.py
src/tools/pmreorder/operationfactory.py
src/tools/pmreorder/opscontext.py
src/tools/pmreorder/pmreorder.py
src/tools/pmreorder/reorderengines.py
src/tools/pmreorder/statemachine.py
src/tools/pmreorder/utils.py

Few fixes related to pmreorder.
man previews:
// before: https://pmem.io/pmdk/manpages/linux/master/pmreorder/pmreorder.1.html
// after: https://lukaszstolarczuk.github.io/pmdk/manpages/linux/master/pmreorder/pmreorder.1.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5366)

Cleanup pmreorder

---

src/test/unittest/tools.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5371)

test: fix device string for real pmem requirement

---

doc/libpmemset/.gitignore
src/examples/libpmemset/README
src/examples/libpmemset/basic/basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5372)

common: pmemset minor fixes

---

doc/pmreorder/pmreorder.1.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5377)

doc: fix cannot break line issue in pmreorder man

---

doc/libpmemset/pmemset_map.3.md
doc/libpmemset/pmemset_source_set_sds.3.md
src/include/libpmemset.h
src/libpmem2/mcsafe_ops_posix.c
src/libpmemset/sds.c
src/libpmemset/source.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5379)

Klocwork fixes

---

src/libpmemset/source.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5381)

set: fix klocwork basic example warning

---

utils/check-commit.sh
utils/check_license/file-exceptions.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5382)

add miniasync to pmdk part1/3

---

src/test/Makefile
src/test/ex_pmreorder/pmreorder1.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5385)

test: update pmreorder tests' match file

---

src/libpmem2/deep_flush_other.c
src/libpmem2/numa_none.c
src/libpmem2/pmem2_utils_other.c
src/libpmem2/region_namespace_none.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5391)

pmem2: add SUPPRESS_UNUSED to pmem2 none/other files

---

src/libpmem2/x86_64/init.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5392)

pmem2: add missing unused suppression

---

src/test/obj_tx_alloc/obj_tx_alloc.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5394)

test: rm usuned code from obj tx alloc

---

.github/workflows/gha.yml
utils/docker/images/Dockerfile.fedora-35
utils/docker/images/install-valgrind.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5389)

common: upgrade Fedora docker image to version 35

---

doc/libpmem2/pmem2_source_pread_mcsafe.3.md
doc/libpmem2/pmem2_vm_reservation_extend.3.md
doc/libpmem2/pmem2_vm_reservation_map_find.3.md
doc/libpmemset/libpmemset_shutdown_state.7.md
doc/libpmemset/pmemset_config_set_event_callback.3.md
doc/libpmemset/pmemset_source_alignment.3.md
doc/libpmemset/pmemset_source_pread_mcsafe.3.md
doc/libpmemset/pmemset_source_set_sds.3.md
src/core/ravl_interval.c
src/deps/miniasync/examples/CMakeLists.txt
src/libpmem2/mcsafe_ops_posix.c
src/libpmem2/mcsafe_ops_windows.c
src/libpmem2/vm_reservation_windows.c
src/libpmempool/check_util.c
src/libpmemset/map_config.c
src/libpmemset/part.c
src/libpmemset/source.c
src/test/obj_ulog_size/obj_ulog_size.c
src/test/pmem_eADR_functions/TESTS.py
src/test/pmemset_deep_flush/pmemset_deep_flush.c
src/test/pmemset_part/pmemset_part.c
src/test/pmemset_persist/TESTS.py
src/test/unittest/devdax.py
src/tools/pmempool/output.c

Apparently Marquis de Favras is my patron saint...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5399)

typo fixes

---

README.md
doc/README
doc/librpmem/librpmem.7.md
doc/librpmem/rpmem_create.3.md
doc/librpmem/rpmem_persist.3.md
doc/rpmemd/rpmemd.1.md
src/benchmarks/Makefile
src/common/Makefile
src/common/pmemcommon.inc
src/common/set.c
src/core/Makefile
src/examples/librpmem/Makefile
src/examples/librpmem/fibonacci/Makefile
src/include/librpmem.h
src/librpmem/README
src/test/rpmem_addr_ext/Makefile
src/test/rpmem_basic/Makefile
src/test/rpmemd_config/stdout0.log.match
src/tools/rpmemd/README
src/tools/rpmemd/rpmemd_config.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5409)

rpmem: set librpmem as deprecated

---

.github/workflows/unittest.yml
utils/gha-runners/build-pmdk.sh
utils/gha-runners/get-system-info.sh

Added GHA workflow to build PMDK along with bash scripts to make it possible
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5410)

common: add GHA unittest workflow for self-hosted runners

---

src/deps/miniasync/doc/data_mover_sync_get_vdm.3.md
src/deps/miniasync/doc/data_mover_threads_get_vdm.3.md
src/deps/miniasync/doc/manuals.txt
src/deps/miniasync/doc/miniasync_vdm.7.md
src/deps/miniasync/doc/miniasync_vdm_synchronous.7.md
src/deps/miniasync/doc/miniasync_vdm_threads.7.md
src/deps/miniasync/doc/vdm_memcpy.3.md
src/deps/miniasync/doc/vdm_memset.3.md
src/deps/miniasync/src/data_mover_sync.c
src/deps/miniasync/src/data_mover_threads.c
src/deps/miniasync/src/include/libminiasync/data_mover_threads.h
src/deps/miniasync/src/include/libminiasync/vdm.h
src/deps/miniasync/tests/CMakeLists.txt
src/deps/miniasync/tests/memmove_threads/memmove_threads.c
src/deps/miniasync/tests/memmove_threads/test_memmove_threads.cmake
src/deps/miniasync/tests/memset_sync/memset_sync.c
src/deps/miniasync/tests/memset_sync/test_memset_sync.cmake
src/deps/miniasync/tests/memset_threads/memset_threads.c
src/deps/miniasync/tests/memset_threads/test_memset_threads.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5421)

miniasync update

---

README.md

I'm not working for IBM anymore so I want to add someone from IBM to be a contact for the PowerPC port as well. @tuliom agreed to be that person.
@tuliom please review if your information is correct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5418)

common: Update PowerPC contacts on Readme.md

---

src/test/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5423)

test: fix Makefile typo

---

utils/docker/images/Dockerfile.ubuntu-20.04

I am going to add bandit scans for pmreorder files (Bandit is a tool designed to find common security issues in Python code).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5436)

common: add bandit to Ubuntu dockerfile

---

src/include/libpmem2/async.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5443)

pmem2: fix wrong manual reference

---

.github/workflows/bandit.yml
README.md
src/tools/pmreorder/consistencycheckwrap.py
utils/docker/build-CI.sh
utils/docker/run-bandit.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5437)

common: add Bandit security scan for pmreorder tool

---

.github/workflows/unittest.yml
utils/check-commit.sh

Reference:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif
prisma/prisma-examples#1988
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5457)

Do not run self-hosted jobs on forks

---

src/test/Makefile
src/test/pmempool_inval/Makefile
src/test/pmempool_inval/TEST0
src/test/pmempool_inval/out0.log.match

This PR adds a few test cases for potentially unsafe pmempool input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5448)

test: add a few inval pmempool cases

---

src/libpmem2/mover.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5447)

Fix KW issue in mover.c

---

ChangeLog

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5426)

common: update changelog

---

.github/workflows/unittest.yml

Removed SLES from runner list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5464)

common: remove SLES from GH workflow

---

utils/docker/build-CI.sh
utils/docker/run-build.sh
utils/docker/run-doc-update.sh
utils/version.sh

the major fix here is for the master not building properly, due to `run-doc-update.sh` issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5466)

Docker updates

---

src/examples/libpmemobj/pmemobjfs/pmemobjfs.c
src/libpmem/pmem.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5463)

small compile fixes

---

utils/docker/run-doc-update.sh

avoid cloning PMDK repo (we already have that in WORKDIR),
add fetching upstream (fix for failing CI: https://github.com/pmem/pmdk/runs/7317255452?check_suite_focus=true#step:4:24106),
add more prints,
update commit message & PR title.
I've only updated the script for CI to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5473)

common: update run-doc-update.sh

---

src/tools/pmreorder/consistencycheckwrap.py
src/tools/pmreorder/pmreorder.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5467)

Pmreorder signal propagation

---

src/common/util.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5481)

common: bump up msc ver in util.h

---

src/examples/libpmemobj/pmemobjfs/pmemobjfs.c
src/libpmem/pmem.h

Backporting a couple of tiny fixes that were committed to master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5472)

backport fixes from master to 1.12

---

.github/workflows/unittest.yml
utils/gha-runners/create-testconfig.sh
utils/gha-runners/get-system-info.sh

Added script for testconfig files creation
Modified workflow to config the runner and make check PMDK repo
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5486)

common: update for GHA workflow - create config & run tests

---

src/deps/miniasync/examples/hashmap/hashmap.c
src/deps/miniasync/src/include/libminiasync/future.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5498)

masync update for stable 1.12

---

.github/workflows/unittest.yml

Added a new self-hosted runner to GHA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5499)

common: add openSUSE GHA runner

---

src/test/pmempool_inval/TEST0
src/test/pmempool_inval/out0.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5501)

test: add more security checks for pmempool input

---

utils/docker/images/install-valgrind.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5502)

common: upgrade valgrind - dwarf2 abbrev patches

---

.github/workflows/bandit.yml
.github/workflows/coverity.yml
.github/workflows/gha.yml
.travis.yml
utils/docker/images/Dockerfile.ubuntu-22.04

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5503)

common: upgrade docker image to Ubuntu 22.04

---

.github/workflows/ras_linux.yml
utils/gha-runners/run-ras-linux.yml

Added gha workflow which launch ras related ansible playbook
Added ansible playbook which launch ras linux tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5504)

common: add GHA RAS Linux tests execution

---

src/libpmem2/badblocks_none.c
src/libpmem2/pmem2_utils_none.c
src/libpmem2/usc_none.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5505)

pmem2: suppress unused params

---

src/Makefile.inc
src/common/pool_hdr.c
src/common/pool_hdr.h
src/core/page_size.h
src/core/util.h
src/core/valgrind_internal.h
src/examples/libpmem2/redo/redo.c
src/include/libpmemblk.h
src/libpmem2/loongarch64/flags.inc
src/libpmem2/loongarch64/init.c
src/libpmem2/loongarch64/loongarch_cacheops.h
src/libpmem2/loongarch64/sources.inc
src/test/pmem_deep_persist/Makefile
src/test/pmem_is_pmem_posix/Makefile

Signed-off-by: Wenlong Zhang <zhangwenlong@loongson.cn>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5510)

add loongarch support for pmdk

---

src/deps/miniasync/examples/hashmap/hashmap.c
src/deps/miniasync/src/include/libminiasync/future.h
src/deps/miniasync/tests/future_properties/future_property_async.c
src/deps/miniasync/tests/memmove_sync/memmove_sync.c
src/libpmemobj/bucket.c
src/libpmemobj/obj.c
src/tools/pmreorder/pmreorder.py
utils/gha-runners/create-testconfig.sh

found by codespell
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5516)

common: fix misspells

---

README.md
utils/README
utils/docker/images/README

- lgtm status badge replacement,
- update content in utils' README files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5517)

Update readme files

---

src/deps/Makefile

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5522)

common: fix make format for src/deps subfolder

---

src/examples/libpmemobj/pmemobjfs/pmemobjfs.c
src/examples/pmreorder/pmreorder_list.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5526)

common: fix coverity issues

---

src/libpmempool/replica.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5527)

common: fix coverity issue

---

.github/workflows/nightly.yml
utils/docker/images/Dockerfile.opensuse-leap-15

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5524)

common: add openSUSE Leap 15 to Nightly CI

---

.github/workflows/nightly.yml
utils/docker/images/Dockerfile.debian-11

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5523)

common: add Debian 11 build to Nightly CI

---

src/libpmem/pmem.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5541)

common: fix unused suppression

---

src/libpmem/Makefile

Ref: #5540
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5542)

pmem: add miniasync cflag

---

.github/workflows/gha.yml
.github/workflows/nightly.yml
utils/docker/images/Dockerfile.rockylinux-8
utils/docker/images/install-valgrind.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5545)

common: add Rocky Linux 8 to execution

---

.github/workflows/nightly.yml
utils/docker/images/Dockerfile.rockylinux-9

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5546)

common: add Rocky Linux 9 to execution

---

doc/libpmem2/libpmem2.7.md

Fixes: #5483
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5551)

doc: change libpmem2 example's link - gist wasn't properly displayed

---

README.md
doc/libpmem2/pmem2_async.3.md
src/deps/README.md
src/include/libpmem2/async.h
src/test/pmem2_future/Makefile
src/test/pmem2_mover/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5552)

pmem2: set async as deprecated

---

README.md
doc/libpmem/libpmem.7.md
doc/libpmem2/libpmem2.7.md
doc/libpmemblk/libpmemblk.7.md
doc/libpmemlog/libpmemlog.7.md
doc/libpmemobj/libpmemobj.7.md
doc/libpmempool/libpmempool.7.md
doc/pmempool/pmempool.1.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5557)

common: set FreeBSD support as deprecated

---

src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5562)

test: add missing variable initialization

---

.github/workflows/unittest_valgrind.yml
utils/gha-runners/create-testconfig.sh

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5567)

Update tests timeout for CI's self-hosted workflows

---

utils/ansible/README

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5564)

common: add ansible directory

---

src/test/obj_memops/obj_memops.c

Fixes:
```
==26679== Number of stores not made persistent: 4
==26679== Stores not made persistent properly:
==26679== [0]    at 0x110001: test_free_entry (obj_memops.c:65)
==26679==    by 0x139CD9: ulog_free_next (ulog.c:681)
==26679==    by 0x1287A7: operation_finish (memops.c:837)
==26679==    by 0x110230: test_set_entries (obj_memops.c:112)
==26679==    by 0x110753: test_redo (obj_memops.c:209)
==26679==    by 0x11216F: main (obj_memops.c:717)
==26679==       Address: 0x53c3388      size: 8 state: DIRTY
==26679== [1]    at 0x110001: test_free_entry (obj_memops.c:65)
==26679==    by 0x139CD9: ulog_free_next (ulog.c:681)
==26679==    by 0x1287A7: operation_finish (memops.c:837)
==26679==    by 0x110230: test_set_entries (obj_memops.c:112)
==26679==    by 0x110753: test_redo …
```

test: fix pmemcheck obj memops issue

---

src/test/Makefile
src/test/obj_pmalloc_mt/obj_pmalloc_mt.c
src/test/obj_tx_alloc_mt/.gitignore
src/test/obj_tx_alloc_mt/Makefile
src/test/obj_tx_alloc_mt/TEST0
src/test/obj_tx_alloc_mt/TEST1
src/test/obj_tx_alloc_mt/TEST2
src/test/obj_tx_alloc_mt/TEST3
src/test/obj_tx_alloc_mt/obj_tx_alloc_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5574)

test: separate tx_alloc_mt from obj_pmalloc_mt tests

---

src/examples/libpmemobj/btree.c
src/test/ex_libpmemobj/out1.log.match

with more verbose usage and extra prints, for better user experience
Fixes: #5476
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5577)

examples: update btree example

---

.github/workflows/pkg_linux.yml
utils/docker/images/Dockerfile.opensuse-leap-15
utils/docker/packages/test-build-packages.py
utils/docker/packages/test-packages-installation.py

Added opensuse to pkg_linux workflow
Modified the Dockerfile of opensuse 15 for PKG tests
Modified python scripts to work with opensuse specific issues
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5582)

common: Adding opensuse to PKG tests

---

utils/gha-runners/get-system-info.sh

Display of available pmem devices to improve failed tests analysis process
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5586)

common: show pmem devices as part of system info

---

ChangeLog

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5603)

Add "Known issues" to the 1.13 change log entry

---

doc/RELEASE_STEPS.md
utils/docker/images/set-images-version.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5612)

Bump docker image version (after 1.13.0 release)

---

doc/RELEASE_STEPS.md
utils/docker/images/set-images-version.sh

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5614)

Merge 'stable-1.13' into 'master'

---

utils/docker/images/Dockerfile.debian-11
utils/docker/images/Dockerfile.fedora-31
utils/docker/images/Dockerfile.fedora-37
utils/docker/images/Dockerfile.opensuse-leap-15
utils/docker/images/Dockerfile.rockylinux-8
utils/docker/images/Dockerfile.rockylinux-9
utils/docker/images/Dockerfile.ubuntu-22.04

- clean redundant packages,
- make order in ENV variables,
- update comments,
- update maintainer.
// Preview of nightly build on my fork: https://github.com/lukaszstolarczuk/pmdk/actions/runs/4860296738
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5616)

common: docker cleanups

---

.github/workflows/gha.yml
.github/workflows/nightly.yml
utils/docker/get-system-info.sh
utils/gha-runners/get-system-info.sh

Display all build system components' versions to help with build system-related bugs diagnosis.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5655)

test: print out build system version

---

.github/workflows/unittest.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5659)

test: speedup tests on PMem

---

src/test/pmem2_future/TESTS.py

test: disable pmem2_future/TEST[0-3]: w/ pmemcheck until #5596 is fixed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5672)

test: disable pmem2_future/TEST[0-3]: w/ pmemcheck until #5596 is fixed

---

utils/docker/images/Dockerfile.ubuntu-22.04

Fixes: #5674
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5675)

common: install hub on Ubuntu to build proper documentation

---

utils/docker/images/Dockerfile.ubuntu-22.04

Fixes: #5674
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5676)

common: install rsync on Ubuntu to build proper documentation

---

utils/gha-runners/create-testconfig.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5677)

test: display execution time of each test

---

src/test/obj_tx_alloc_mt/obj_tx_alloc_mt.c

Fixes: #5660
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5680)

test: add missing persist in obj_tx_alloc_mt/TEST1

---

.github/workflows/unittest_long.yml

Common: enable manual triggering of long tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5685)

common: enable manula trigerring of long tests

---

.github/workflows/unittest.yml
.github/workflows/unittest_long.yml
.github/workflows/unittest_valgrind_py.yml
.github/workflows/unittest_valgrind_sh.yml
utils/gha-runners/build-pmdk.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5683)

common: Increasing the parallelism of test execution

---

src/test/pmem2_mover/pmem2_mover.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5687)

test: fix memory leak in pmem2_mover test

---

src/test/RUNTESTS.py
src/test/unittest/basetest.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5684)

common: print elapsed time for failed tests

---

.github/workflows/unittest_valgrind_sh.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5697)

common: fix typo in GHA script

---

utils/check_whitespace

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5701)

common: fix Copyright date

---

ChangeLog

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5703)

common: ChangeLog update based on review feedback.

---

doc/libpmem2/pmem2_source_from_handle.3
src/common/file.c
utils/check-area.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5728)

common: remove leftover Windows

---

doc/README
doc/libpmem/libpmem.7.md
doc/libpmem2/libpmem2.7.md
doc/libpmem2/pmem2_source_alignment.3.md
doc/libpmem2/pmem2_source_size.3.md
doc/libpmemblk/libpmemblk.7.md
doc/libpmemlog/libpmemlog.7.md
doc/libpmemobj/libpmemobj.7.md
doc/libpmemobj/oid_is_null.3.md
doc/libpmemobj/pmemobj_mutex_zero.3.md
doc/libpmempool/libpmempool.7.md
doc/pmempool/pmempool.1.md
src/libpmemobj/obj.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5725)

doc: remove FreeBSD from documentation

---

.github/workflows/centos.yml
doc/libpmem2/libpmem2.7.md
utils/docker/images/Dockerfile.centos-7
utils/docker/images/Dockerfile.centos-stream
utils/docker/images/install-valgrind.sh

Centos OS is used by DAOS.
PMDK-61
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5733)

common: add CentOS to build system

---

.github/workflows/bandit.yml
.github/workflows/main.yml
.github/workflows/pmem_check.yml
.github/workflows/pmem_long.yml
.github/workflows/pmem_ras.yml
.github/workflows/pmem_valgrind_py.yml
.github/workflows/pmem_valgrind_sh.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5654)

common: unify workflows' names and file naming

---

.github/workflows/bandit.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5736)

common: simplify Bandit workflow configuration

---

.github/workflows/centos.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5737)

common: enable CentOS build w/o ndctl

---

utils/ansible/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5741)

common: fix cstyle issues in the README.md file

---

ChangeLog

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5753)

common: add the next release changelog entry stub

---

.gitignore
ChangeLog
utils/docker/README
utils/docker/build-CI.sh
utils/docker/build-local.sh
utils/docker/run-coverage.sh
utils/docker/set-ci-vars.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5738)

common: remove obsolete Travis support

---

.github/workflows/pmem_ras.yml

pmem ras test will be executed every 8 hour on stable master branch instead of dealing with trivial issues like license errors, cstyle errors, etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5761)

common: disable pmem ras test for every pull request

---

.github/workflows/scan_bandit.yml
.github/workflows/scan_codeql.yml
.github/workflows/scan_coverity.yml
.github/workflows/scan_documentation.yml
.github/workflows/scans.yml

Requires:
Preview: https://github.com/janekmi/pmdk/actions/runs/5425215198
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5766)

common: group all scans into one GHA workflow

---

doc/libpmempool/libpmempool.7.md
doc/libpmempool/pmempool_check_init.3.md
doc/libpmempool/pmempool_rm.3.md
doc/libpmempool/pmempool_sync.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5774)

doc: remove log and blk references from libpmempool

---

.github/workflows/centos.yml
.github/workflows/docker_rebuild.yml
.github/workflows/main.yml
.github/workflows/nightly.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5776)

common: separate workflow for rebuilding Docker images

---

.github/workflows/centos.yml
.github/workflows/main.yml
.github/workflows/ubuntu.yml

Requires:
Preview: https://github.com/janekmi/pmdk/actions/runs/5446021253
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5777)

common: introduce preliminary checks GHA

---

SECURITY.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5780)

common: add SECURITY.md according to Intel policy

---

.github/workflows/ubuntu.yml

Preview: https://github.com/janekmi/pmdk/actions/runs/5446863142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5778)

common: stop the failing Codecov uploader from stopping the build

---

utils/docker/images/install-valgrind.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5767)

common: remove aarch64 Valgrind support

---

.github/workflows/pmem_check.yml
.github/workflows/pmem_tests_main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5787)

common: main pmem tests workflow for all tests in sequence

---

src/test/pmempool_check/TEST8

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5785)

test: delete logging into stdout

---

utils/ansible/configure-pmem.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5788)

common: fix configure-pmem.yml file

---

.github/workflows/pmem_check.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5790)

common: use RUNTESTS.* instead of make (py)check

---

.github/workflows/scan_coverity.yml
.github/workflows/scans.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5793)

common: test coverity scan

---

src/test/obj_sync/TEST2
src/test/obj_sync/TEST5
src/test/obj_sync/TEST6
src/test/unittest/unittest.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5789)

Use dedicated DISABLED() function to disable tests in bash test framework

---

.github/workflows/scan_coverity.yml
.github/workflows/scans.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5794)

common: pass secret variables to scan_coverity.yml reusing workflow

---

README.md

- introduces an "Archived and deprecated" section
- adds missing libraries
- harmonizes formatting
Preview: https://github.com/janekmi/pmdk/blob/README-libs-archive/README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5782)

common: cleanup README

---

src/test/unittest/python_gdb.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5797)

test: print error/warning message in case of Valgrind failure

---

src/tools/pmempool/dump.c

Removes unreachable code as detected by the Coverity tool.
https://scan3.scan.coverity.com/reports.htm#v62257/p10600/fileInstanceId=97952431&defectInstanceId=13143835&mergedDefectId=415983
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5800)

pool: remove unreachable code

---

.github/workflows/docker_rebuild.yml
utils/docker/pull-or-rebuild-image.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5804)

common: force rebuild docker images

---

ChangeLog
Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5786)

common: separate make commands for whitespace and commits checking

---

src/test/obj_sync/TEST4
src/test/pmempool_sync/TEST18
src/test/unittest/python_gdb.py
utils/md2man.sh

Fix licenses for files modified in:
#5795
#5796
#5797
#5801
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5810)

common: fix licenses for #5759

---

.github/workflows/main.yml

Issue: https://github.com/pmem/pmdk/actions/runs/5610818506/jobs/10266317510
Preview: https://github.com/pmem/pmdk/actions/runs/5610796937/jobs/10266267971
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5812)

common: longer history is required for make check-license

---

.github/workflows/docker_rebuild.yml
.github/workflows/nightly.yml

- includes a small revamp of the docker rebuild matrix
Preview: https://github.com/pmem/pmdk/actions/runs/5611467586
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5815)

common: drop Debian and Fedora from CI

---

src/test/obj_sync/err0.log.match

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5820)

test: improve err_log.match file

---

src/test/RUNTESTS.py
src/test/obj_bucket/TEST0
src/test/obj_critnib/TESTS.py
src/test/obj_heap/TEST1
src/test/obj_lane/TEST0
src/test/obj_pool/TEST20
src/test/obj_tx_flow/TEST0
src/test/obj_tx_lock/TEST0
src/test/pmem2_config/TESTS.py
src/test/pmem2_map_from_existing/TESTS.py
src/test/pmem2_source/TESTS.py
src/test/pmem2_vm_reservation/TESTS.py
src/test/pmem_is_pmem_posix/TEST0
src/test/pmem_is_pmem_posix/TEST4
src/test/pmem_is_pmem_posix/TEST5
src/test/scope/TESTS.py
src/test/unittest/basetest.py
src/test/unittest/configurator.py
src/test/unittest/unittest.sh
src/test/util_badblock/TEST11
src/test/util_ctl/TEST0
src/test/util_ctl/TEST1
src/test/util_poolset/TEST4
src/test/util_poolset_parse/TEST5
src/test/util_ravl/TEST0

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5821)

test: introduce fault_injection test label

---

.github/workflows/nightly.yml
.github/workflows/pmem_check.yml

Requires:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5823)

common: rationalize fault injection testing

---

.github/actions/pmem_test_procedure/action.yml
.github/workflows/pmem_check.yml

To reduce code duplication in the existing and upcoming workflows.
Preview: https://github.com/pmem/pmdk/actions/runs/5673797355
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5828)

common: introduce action/pmem_test_procedure

---

.github/workflows/nightly.yml

Preview: https://github.com/pmem/pmdk/actions/runs/5693862059
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5832)

common: split nightly into in-tree and packaging testing

---

.github/workflows/nightly.yml

Requires:
Preview: https://github.com/pmem/pmdk/actions/runs/5695026813
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5834)

common: no fail-fast and no Docker rebuild on nightly

---

INSTALL.md
README.md
RELEASE_STEPS.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5833)

common: split README.md file to README.md and INSTALL.md files

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5826)

common: update README.md file

---

ChangeLog

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5837)

common: prepare changelog for the upcoming release

---

src/test/unittest/unittest.sh

Ref: #5615
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5856)

test: add a comment on the effect of device DAXes order

---

.github/workflows/pmem_check.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5842)

common: make "PMEM NDCTL_ENABLE=n" more human-friendly

---

.github/workflows/main.yml

Fail preview: https://github.com/pmem/pmdk/actions/runs/5695231758/job/15437949829
Skip preview: https://github.com/pmem/pmdk/actions/runs/5695294607/job/15438148089#step:3:9
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5835)

common: force changelog update on PR

---

src/test/ex_libpmemobj/TEST15
src/test/ex_libpmemobj/TEST16

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5857)

test: add comment about req_tty to ex_libpmemobj tests

---

ChangeLog
INSTALL.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5861)

common: 2.0.0 release

---

src/tools/pmempool/common.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5866)

pool: fix coverity issue 374612

---

RELEASE_STEPS.md
utils/docker/images/set-images-version.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5862)

common: update PMDK version

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5874)

doc: fix links to PMDK tutorials

---

ChangeLog
INSTALL.md
RELEASE_STEPS.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5878)

doc: rename 1.14.0 to 2.0.0

---

.github/workflows/scan_bandit.yml
.github/workflows/scan_codeql.yml
.github/workflows/scan_coverage.yml
.github/workflows/scan_coverity.yml
.github/workflows/scan_documentation.yml
.github/workflows/scan_ubsan.yml
.github/workflows/ubuntu.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5881)

common: disable manual triggering for subworkflows

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5880)

common: update status badges in README.md file

---

utils/call_stacks_analysis/examples/api_filter.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5901)

common: add sample api_filter file

---

utils/call_stacks_analysis/.gitignore
utils/call_stacks_analysis/generate_call_stacks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5905)

common: loading the api from file + small fixes

---

utils/call_stacks_analysis/generate_call_stacks.py

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5906)

common: add api_filter parameter + small fix

---

utils/call_stacks_analysis/make_cflow.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5911)

common: work around cflow's for-loop issue

---

utils/call_stacks_analysis/README.md
utils/call_stacks_analysis/list_api_callers.py
utils/call_stacks_analysis/list_stack_usage.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5910)

common: revisit accessory scripts

---

utils/call_stacks_analysis/make_stack_usage.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5913)

common: use relative path for stack usage files

---

utils/call_stacks_analysis/README.md
utils/call_stacks_analysis/make_call_stacks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5915)

common: generate_call_stacks.py -> make_call_stacks.py

---

utils/call_stacks_analysis/make_call_stacks.py

Ref: #5915
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5916)

common: generate_call_stacks.py -> make_call_stacks.py (fix)

---

utils/call_stacks_analysis/make_call_stacks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5917)

common: raise an exception instead of assert() call

---

utils/call_stacks_analysis/make_call_stacks.py

Requires:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5919)

common: go through API calls with the call stacks generation

---

utils/call_stacks_analysis/make_call_stacks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5920)

common: add more stack usage examples to support existing regex

---

utils/call_stacks_analysis/make_call_stacks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5921)

common: reduce the actual number of stack to analyze

---

utils/call_stacks_analysis/make_call_stacks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5923)

common: add const stack usage for all daxctl* functions

---

utils/call_stacks_analysis/README.md
utils/call_stacks_analysis/check_stack_usage.sh
utils/call_stacks_analysis/make_call_stacks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5924)

common: check zero-sized functions

---

src/libpmem2/pmem2_utils_linux.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5925)

pmem2: reduce stack usage of pmem2_get_type_from_stat

---

utils/call_stacks_analysis/make_call_stacks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5926)

common: final ndctl/daxctl stack usage with recurrence

---

utils/call_stacks_analysis/stack_usage.txt

Ref: #5925
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5927)

pmem2: reduce stack usage of pmem2_get_type_from_stat (fix)

---

utils/call_stacks_analysis/.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5928)

common: fix call stack analysis .gitignore

---

src/libpmemobj/heap.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5933)

obj: fix coverity issue heap_get_arena_auto

---

utils/call_stacks_analysis/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5931)

common: extend example run sequence

---

.github/workflows/scan_stack_usage.yml
.github/workflows/scans.yml

Preview:
- As a part of a set of scans: https://github.com/pmem/pmdk/actions/runs/6968535140
- As a separate run: https://github.com/pmem/pmdk/actions/runs/6968400099
I recommend reviewing also the uploaded artefacts. I introduced them since I believe they might be useful in sorting out stack usage-related issues.
**Note**
1. This workflow is meant to fail till we sort out the issues it has found. I believe it should not stop us from merging this workflow per se.
2. This workflow has built-in another fuse which is commented out intentionally. The `stack_usage.txt` fuse will be addressed as a part of a separate task.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5937)

common: introduce a stack usage scan

---

.github/workflows/scan_codeql.yml
.github/workflows/scan_documentation.yml
utils/ansible/opensuse-setup.yml
utils/ansible/rockylinux-setup.yml
utils/check_license/check-headers.sh
utils/check_whitespace
utils/docker/images/Dockerfile.centos-7
utils/docker/images/Dockerfile.centos-stream
utils/docker/images/Dockerfile.debian-11
utils/docker/images/Dockerfile.fedora-31
utils/docker/images/Dockerfile.fedora-37
utils/docker/images/Dockerfile.opensuse-leap-15
utils/docker/images/Dockerfile.rockylinux-8
utils/docker/images/Dockerfile.rockylinux-9
utils/docker/images/Dockerfile.ubuntu-22.04
utils/gha-runners/run-ras-linux.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5932)

common: remove obsolete dependency: cmake

---

.github/workflows/scan_stack_usage.yml

Preview: https://github.com/pmem/pmdk/actions/runs/6970910199
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5938)

common: adjust the stack usage size limit to account for small differences between OSes

---

utils/call_stacks_analysis/make_call_stacks.py

https://github.com/osalyk/pmdk/actions/runs/6978341195/job/18989587374
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5939)

common: remove assert from make_call_stacks.py

---

utils/docker/run-coverity.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5940)

common: enable coverity scan on workflow_dispatch event

---

utils/ansible/README.md
utils/ansible/handlers/reboot.yml
utils/ansible/roles/update_rocky/tasks/main.yml
utils/ansible/roles/update_suse/tasks/main.yml
utils/ansible/update-os.yml

Add ansible playbook for kernel and OS packages update for Suse and RedHat/Rocky based systems
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5908)

common: Add kernel and os packages update playbook

---

.github/actions/pmem_host_update/action.yml

Add composite action that will handle ansible playbook for kernel and OS packages update for Suse and RedHat/Rocky based systems
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5918)

common: Add composite action for update-os playbook

---

.github/actions/pmem_test_prepare/action.yml

Integrate update-os composite action into PMEM test prepare action. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5930)

common: Integrate update-os into PMEM test prepare

---

.github/actions/pmem_test_prepare/action.yml
.github/actions/update_dax_permissions/action.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5949)

common: Add fix for DAX permissions reset after platform reboot

---

src/core/log.c
src/core/log_default.c
src/core/log_internal.h
src/core/out.c
src/core/out.h
src/test/Makefile.inc
src/test/drd-log.supp
src/test/pmem2_persist_valgrind/Makefile
src/test/pmem2_persist_valgrind/pmem2_persist_valgrind.c
src/test/unittest/Makefile
src/test/unittest/unittest.h
src/test/unittest/ut_log.c
src/test/util_ravl/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5962)

common: introduce LOG_ALWAYS for library info logging

---

src/test/Makefile.inc
src/test/helgrind-log.supp
src/test/unittest/Makefile
src/test/unittest/unittest.h
src/test/util_ravl/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5964)

common: use ut-dedicated logging function for pmemobj logs

---

.github/workflows/ubuntu.yml

Preview:
- failed build: https://github.com/pmem/pmdk/actions/runs/7613729461 (logs uploaded)
- successful build: https://github.com/pmem/pmdk/actions/runs/7613664508 (no logs)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5970)

common: upload test logs

---

.github/workflows/main.yml

Preview: https://github.com/pmem/pmdk/actions/runs/7652764402/job/20853220540
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5975)

common: skip checking changelog for master and stable-* branches xD

---

ChangeLog
src/common/ctl.c
src/common/shutdown_state.c
src/test/ctl_cow/TEST0
src/test/ctl_cow/TEST3
src/test/obj_ctl_arenas/TEST8
src/test/obj_ctl_arenas/TEST9
src/test/obj_defrag/TESTS.py
src/test/obj_defrag_advanced/TESTS.py
src/test/obj_extend/TEST1
src/test/obj_pool_open_mt/TESTS.py
src/test/obj_tx_user_data/TESTS.py
src/test/pmem2_granularity_detection/TESTS.py
src/test/pmempool_check/common.sh
src/test/pmempool_feature/TEST14
src/test/pmempool_feature/TEST15
src/test/unittest/basetest.py
src/test/unittest/unittest.sh
utils/build-dpkg.sh
utils/build-rpm.sh
utils/docker/build-CI.sh

Fixes: #5968
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5969)

common: does not allow open pmem w/o USC

---

src/libpmem/pmem.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5980)

pmem: disable flag verification until #5979 is fixed

---

src/core/log.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5973)

common: fix coverity issue 1969782

---

src/core/log_default.c

- put the primary destination first and the auxiliary second
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5978)

common: final touch for the default logging function

---

src/common/os_deep_linux.c
src/common/uuid_linux.c
src/core/log.c
src/core/log_default.c
src/core/log_default.h
src/core/log_internal.h
src/core/out.c
src/core/out.h
src/libpmem2/auto_flush_linux.c
src/libpmem2/deep_flush_linux.c
src/libpmemobj/obj.c
src/test/log_errno/TEST0
src/test/log_errno/log_errno.c
src/test/unittest/unittest.h
src/test/unittest/ut_log.c

Requires:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5994)

common: do not call ERR_W(O)_ERRNO just to write to TLS

---

src/test/obj_tx_add_range/TESTS.py
src/test/obj_tx_add_range_direct/TESTS.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/5998)

test: re-enable obj_tx_add_range[3] and obj_tx_add_range_direct[2]

---

src/core/log_internal.h
src/test/Makefile
src/test/core_log/.gitignore
src/test/core_log/Makefile
src/test/core_log/TESTS.py
src/test/core_log/core_log.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6001)

common: fine-tuned _CORE_LOG_MAX_ERRNO_MSG

---

CODING_STYLE.md
src/core/out.c
src/core/out.h
src/test/out_err/out0.log.match
src/test/out_err/out_err.c
src/test/out_err/traces0.log.match
utils/call_stacks_analysis/make_extra.py

Remove obsolete out_err()
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6006)

common: remove obsolete out_err()

---

ChangeLog
src/core/last_error_msg.c
src/core/last_error_msg.h

Resolves: #5999
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6005)

common: remove support for NO_LIBPTHREAD build option

---

.github/workflows/scan_log_calls.yml
.github/workflows/scans.yml
src/test/core_log/call_all.c.generated
utils/call_stacks_analysis/log_call_all_generate.py

Preview:
- https://github.com/pmem/pmdk/actions/runs/7931103297 (successful)
- https://github.com/pmem/pmdk/actions/runs/7930031574 (failed, a little bit older revision)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6011)

common: add a scanner for the log calls test

---

utils/call_stacks_analysis/log_call_all_generate.py

https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6014)

common: stop using subprocess with shell=True

---

.github/workflows/scan_stack_usage.yml
utils/call_stacks_analysis/README.md

https://github.com/pmem/pmdk/actions/runs/8042194303/job/21962517418#step:9:629
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6028)

common: inrease total stack usage limit causes by new logging function

---

src/test/arch_flags/log0.log.match
src/test/util_poolset/grep7.log.match

https://github.com/pmem/pmdk/actions/runs/8069388320/job/22044337777#step:4:1647
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6032)

test: fix util_poolset test to work w/o ndctl

---

src/test/core_log_default_function/core_log_default_function.c

https://github.com/pmem/pmdk/actions/runs/8164312612/job/22319768987#step:5:19521
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6040)

test: fix static variable for clang

---

src/core/valgrind_internal.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6051)

common: remove unsupported FreeBSD related define

---

doc/Makefile
doc/libpmemobj/pmemobj_log_use_default_function.3
utils/check_docs/exceptions.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6056)

doc: add an exception and a macro

---

src/libpmem2/x86_64/init.c
utils/call_stacks_analysis/make_call_stacks.py
utils/call_stacks_analysis/make_extra.py

Requires:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6065)

common: avoid pmem_ prefix for pmem2 functions

---

src/common/set.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6074)

obj: verify the shutdown state in pmemobj pool

---

doc/Makefile
doc/libpmem/pmem_log_use_default_function.3

https://github.com/pmem/pmdk/issues/6077
This fixes the documentation scan
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6076)

doc: remove unneeded file

---

doc/libpmem/.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6091)

common: typo in file names

---

src/libpmem2/aarch64/init.c

Fixes #6088
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6096)

Add missing log_internal.h to fix build on aarch64

---

utils/ansible/README.md
utils/ansible/opensuse-setup.yml
utils/ansible/rockylinux-setup.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6110)

common: add small amendments

---

utils/docker/images/Dockerfile.opensuse-leap-15
utils/docker/images/Dockerfile.rockylinux-8
utils/docker/images/Dockerfile.rockylinux-9
utils/docker/images/Dockerfile.ubuntu-22.04

https://github.com/pmem/pmdk/actions/runs/11054941468/job/30712957960
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6114)

common: fix hash commits in docker files

---

src/core/log.c
src/core/log_internal.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6119)

common: make _CORE_LOG_TO_LAST macro internal

---

src/test/unittest/basetest.py
utils/docker/prepare-for-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6120)

common: print Linux release name during build in Docker

---

.pre-commit-config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6124)

common: revert (c) to align with general Copyright template

---

.github/workflows/main.yml
README.md

Regular `main.yml` execution to avoid incidental PR validation failures due to GitHub runners configuration changes. 
Resolves: #6134
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6135)

Regular main execution

---

.github/workflows/scan_stack_usage.yml
utils/call_stacks_analysis/README.md

Two functions resized:
pmemobj_create()
heap_populate_bucket()
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6138)

common: change lower_limit

---

LICENSE.txt
LICENSE/BSD-3-Clause

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6141)

Include HPE in general license files

---

ChangeLog
INSTALL.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6151)

Release 2.1.1

---

.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6155)

common: update before install (aarch64)

---

src/test/obj_sds/TEST0
src/test/obj_sds/TEST1
src/test/obj_sds/TEST2
src/test/obj_sds/TEST3
src/test/obj_sds/TEST4
src/test/obj_sds/TEST5
src/test/obj_sds/TEST6
src/test/obj_sds/TEST7

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6153)

test: unblock obj_sds tests for non-pmem

---

src/test/obj_sds/obj_sds.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk/6154)

test: check if mock functions are used
